### ISSUE TITLE
There has not been any language update since 2017.

### ISSUE THREAD

**Issue by libreajans** [mypaint/mypaint#1000]
I'm keen on libre/free software and I have finalized the translation of GIMP and Krita to Turkish recently. 

When I checked .po files of MyPaint, I saw that there hasn't been any update since 2017! (https://github.com/mypaint/mypaint/tree/master/po) 

It looks pipeline of Weblate to MyPaint has been broken.

**Comment by xendez** [comment]
I've just finished the translation to Portuguese in weblate and was checking that. Any chance to see languages updated in a alpha release to check the translation?

**Comment by briend** [comment]
I started looking at this, it shouldn't be too difficult to fix.  If
nothing else I will never all the changes manually

**Comment by jplloyd** [comment]
I've pulled in all of the Weblate translations. Based on the number of merge commits in the log, I'm not sure if it was ever set up to push automatically. Whatever the case may be, we'll have to this manually on a periodical basis until administrative access to the Weblate account can be recovered (if that is at all possible).
