### ISSUE TITLE
BrushEditor does not show libmypaint translations

### ISSUE THREAD

**Issue by libreajans** [mypaint/mypaint#1003]
libmypaint translations are being ingored by BrushEditor. 

![mybrush](https://user-images.githubusercontent.com/6218679/57198626-98671b80-6f7d-11e9-94dd-701557fb51d9.png)

The red area reads Category strings (Experimental, Base, Opacity, etc) from mypaint.po and the other entries come from libmypaint.po (brushsetting.json file). Brusheditor.py is not showing any translations from libmypaint.po and ignoring them.

The yellow area reads entries from mypaint.po file. I have checked twice and mypaint.po does not have these strings.

If I put them on the file, it works and accepts translations.

```
msgid "Random:"
msgid "Stroke:"
msgid "Direction:"
msgid "Declination/Tilt:"
msgid "Ascension:"
msgid "Fine speed:"
msgid "Gross speed:"
msgid "Custom:"
msgid "Direction 360:"
msgid "Attack Angle:"
msgid "Declination/Tilt X:"
msgid "Declination/Tilt Y:"
msgid "GridMap X:"
msgid "GridMap Y:"
msgid "Zoom Level:"
msgid "Base Brush Radius:"

```

#### Basic system details

MyPaint version: 2.0.0-alpha+git.d5bd2a8 via AppImage (20190331)
Operating system: Ubuntu 18.04.2
Desktop environment: GNOME

**Comment by jplloyd** [comment]
Thanks for the find. This was caused by a miss in a change to libmypaint that led to the wrong translation files being looked for. Building/installing the latest libmypaint master should fix this.
