### ISSUE TITLE
A tiny glitch on the about page

### ISSUE THREAD

**Issue by libreajans** [mypaint/mypaint#1004]
meta.py (the about page) uses an escape function on the copyright string and as a result some letters are been showing untidy.

In my example, it is a Turkish character: Ş. It's important, because "Development Team" means "Geliştirme Ekibi" in Turkish.

` d.set_copyright(escape(COPYRIGHT_STRING))`

![2019-05-05 22-31-56 ekran görüntüsü](https://user-images.githubusercontent.com/6218679/57207494-d17faa00-6fd6-11e9-8cda-f29b8d2815b7.png)

MyPaint version: 2.0.0-alpha+git.d5bd2a8 (Via AppImage)
Operating system: Ubuntu 18.04.2
Desktop environment: GNOME

**Comment by jplloyd** [comment]
Over-eager escaping caused some of these strings (including the copyright string) to be escaped twice (once in MyPaint, once in GTK). This is now fixed in master. Thanks for drawing attention to this, and finding the reason!
