### ISSUE TITLE
my computer had slowed down and I'd also opened mypaint. And this happened:

### ISSUE THREAD

**Issue by wallflowerpaper** [mypaint/mypaint#1007]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 2.0.0-alpha+git.d5bd2a87
System information: Windows-10-10.0.17134-SP0
Using: Python 2.7.16, GTK 3.24.5, GdkPixbuf 2.38.1, Cairo 1.16.0, GLib 2.58.3
Traceback (most recent call last):
  File "D:/mypaint-w64/mingw64/lib/mypaint/gui/document.py", line 1660, context_cb(self=<gui.document.Document object>, action=<Gtk.Action object at 0x000000000e1c1c30 (GtkAction at 0x000000000e0ab4f0)>)
                context.brushinfo = self.app.brush.clone()
                context.preview = bm.selected_brush.preview
                context.save()
  variables: {'context.preview': ('local', <GdkPixbuf.Pixbuf object at 0x000000001092d320 (GdkPixbuf at 0x0000000010840d80)>)}
AttributeError: 'NoneType' object has no attribute 'preview'
```

**Comment by jplloyd** [comment]
There is very little to work with here. If you remember: 

* Were you actively using MyPaint when the slowdown started - and did the MyPaint window freeze?
* If the answer to the above is "yes", did the freeze happen when you were drawing a brushstroke?
* Did the computer become more responsive (less slow) after MyPaint had crashed out?

**Comment by jplloyd** [comment]
I think this may have been caused by a libmypaint allocation-related bug that was fixed here : [commit](https://github.com/mypaint/libmypaint/commit/01586a204d412acd7d00441ef560e6c93f6ee5bc).

I could be wrong, but it seems we're not getting more information here.
