### ISSUE TITLE
AppImage floodfill issue

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#1009]
I kicked off an appimage build (we really need to automate this! ;-):
https://github.com/mypaint/mypaint-appimage/releases/download/continuous/MyPaint---20190622.AppImage

But it's getting an error on my machine (Debian Stable).  I don't get any error when I run mypaint master from source; just the appimage.

  File "/tmp/.mount_MyPainkr8FOk/usr/lib/mypaint/lib/floodfill.py", line 38, in <module>
    _GAPLESS_TILE = np.full((N, N), INF_DIST, 'uint16')
AttributeError: 'module' object has no attribute 'full'

Not exactly sure why it's complaining yet. . .  @jplloyd  any ideas?

Full Log:
./MyPaint---20190622.AppImage 
DIR: /tmp/.mount_MyPainkr8FOk
AILIBDIR=/tmp/tmp.8RaSHkUr6P
System stdc++ library: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
System stdc++ library version: "3.4.22"
Bundled stdc++ library version: "3.4.19"
Newest stdc++ library version: "3.4.22"
Using system stdc++ library
atomiclib: /usr/lib/x86_64-linux-gnu/libatomic.so.1
Checking versions of library "libfontconfig"
  system library: "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.8.0" (libfontconfig.so.1.8.0)
  system library version: 1.8.0
  ailib: "/tmp/.mount_MyPainkr8FOk/usr/lib/libfontconfig.so.1.11.1"
  bundled library: "/tmp/.mount_MyPainkr8FOk/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  bundled library version: 1.11.1
  newest library version: "1.11.1"
Checking versions of library "libfreetype"
  system library: "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.3" (libfreetype.so.6.12.3)
  system library version: 6.12.3
  ailib: "/tmp/.mount_MyPainkr8FOk/usr/lib/libfreetype.so.6.14.0"
  bundled library: "/tmp/.mount_MyPainkr8FOk/usr/lib/libfreetype.so.6.14.0" (libfreetype.so.6.14.0)
  bundled library version: 6.14.0
  newest library version: "6.14.0"
GTK_PATH=/tmp/.mount_MyPainkr8FOk/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_MyPainkr8FOk/usr/lib/gtk-2.0:/tmp/.mount_MyPainkr8FOk/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_MyPainkr8FOk/usr/lib
/tmp/.mount_MyPainkr8FOk/apprun-helper.sh: line 131: /tmp/.mount_MyPainkr8FOk/startup_scripts/*.sh: No such file or directory
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPainkr8FOk/usr'
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
Traceback (most recent call last):
  File "/tmp/.mount_MyPainkr8FOk/usr/bin/mypaint", line 483, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/tmp/.mount_MyPainkr8FOk/usr/lib/mypaint/gui/main.py", line 97, in main
    from gui import application
  File "/tmp/.mount_MyPainkr8FOk/usr/lib/mypaint/gui/application.py", line 48, in <module>
    import lib.document
  File "/tmp/.mount_MyPainkr8FOk/usr/lib/mypaint/lib/document.py", line 36, in <module>
    import lib.tiledsurface as tiledsurface
  File "/tmp/.mount_MyPainkr8FOk/usr/lib/mypaint/lib/tiledsurface.py", line 35, in <module>
    import lib.floodfill
  File "/tmp/.mount_MyPainkr8FOk/usr/lib/mypaint/lib/floodfill.py", line 38, in <module>
    _GAPLESS_TILE = np.full((N, N), INF_DIST, 'uint16')
AttributeError: 'module' object has no attribute 'full'

**Comment by jplloyd** [comment]
I guess the numpy version bundled with the image is < 1.10, which introduced the full() "constructor".

We could bump the version up, but if this is the only break (and it's only used 5 times) I'll just change the calls to use construction+fill, which should be compatible with anything >= 1.6

**Comment by jplloyd** [comment]
The reason for the old dependencies can be found in the appimage script - it uses the Ubuntu 14.04 repos. Not necessarily bad to support old versions, though I did note that 14.04 is not officially supported by MyPaint as of 2016.

**Comment by jplloyd** [comment]
I don't know how/where to rebuild the appimages, but I'll dig out a 14.04 VM I think I have lying around somewhere to see if there are other dependency issues.

**Comment by briend** [comment]
For now I go here and create a release, which triggers the appimage build via Travis-CI. https://github.com/mypaint/mypaint-appimage/  
There are ways to hook this all together but I haven't invested the time in that yet :-P

I don't know why it uses Ubuntu 14.04, but maybe for better compatibility?

**Comment by jplloyd** [comment]
Turns out Travis-CI did not support 16.04 until November last year (https://blog.travis-ci.com/2018-11-08-xenial-release). I actually logged in to Travis-CI and ran a rebuild, which overwrote the previous AppImage upload for today's date (good to know). Ran fine on Fedora 30 and Ubuntu 16.04, though issue #975 was happening on my own machine. I'll have to look into that later.
