### ISSUE TITLE
Looking for support with mypaint debian 

### ISSUE THREAD

**Issue by graphic2017designer** [mypaint/mypaint#1018]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem
Hi all, 
Thanks for offering this support community. Currently I'm using mypaint appimage v. 2 alpha 12 on my deepin 15.11 
Tablet pc with intel atom 1.44 4 cores and 4 rams. 
The current issue is many brushes too lag and the other part work fine until I paint over previous stroke it's become too lag also. 
With mention on my tablet pc krita app image work fine when I lower graphic acceleration. So if wondering if there the same option for mypaint or alternative option to reduce the lag issue. 
Looking forward to your support ASAP.

**Comment by jplloyd** [comment]
In the tool options there is a slider called Pigment. Set it to 0. This should make it less laggy (it enables a more advanced type of colour mixing). For the alpha version you are running, you will have to change the slider whenever you change to a new brush (this is something that will be configurable later).

I will note that your hardware is quite slow, so you'll have to weigh your expectations accordingly.

**Comment by jplloyd** [comment]
Since we try to limit this tracker to bugs, I'm closing this. If you have any other issues that aren't bugs, you can post questions on [the mypaint forum](https://community.mypaint.org/).
