### ISSUE TITLE
Brush Settings Editor: highlight changed settings (boldtext)

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#102]
When we are designing or modifying the brushes on MyPaint is very difficult to have a picture of parameters used for a brush. This trouble in many times become hard the design and future revisions.

My idea, I don't know if is possible, to have the parameters highlighted and so is more easy to identify the parameters out of the default values ​​or curves, where and what our brushes are using.

**Comment by achadwick** [comment]
@americogobbo What changes do you want to see highlighted in bold?

1. Settings which have changed from the MyPaint brush defaults (that boring round brush where every setting is 1 or 0)
  - if this, won't almost every setting be bold?
2. Settings which have been changed relative to the brush's saved settings on disk, but which haven't been saved yet
  - if this, almost no setting will be shown in bold most of the time
  - there may be better ways of showing that a brush's changes haven't been saved yet

Both are useful, to my mind.

**Comment by americogobbo** [comment]
For me is a bit difficult to resolve the workflow of point 1.
The approach on point 2., of the in progress editing, is a good way to control the single brush editing session.
Perhaps we need the concept of the default brush on MyPaint... where it is the base or the startup of the new brushes ... but here is off-topic.

**Comment by achadwick** [comment]
Often a `*` or an `[unsaved]` marker is used to indicate that an object hasn't been saved. We could extend that to the list of settings in the left-hand pane:

![screenshot from 2015-04-15 00 59 01](https://cloud.githubusercontent.com/assets/61299/7149857/b8f366d2-e30a-11e4-912c-4bbff83dd413.png)

So you might see

> * About *
> * Experimental
>   * Pressure gain
> * [...]

And for the header

> b000 *

**Comment by americogobbo** [comment]
Yes is a good and clean way to resolve it.
To understand better, for example:
> Smudge * (something on smudge unsaved)
When you open > Smudge the [voice(s) unsaved *] is also marked.

**Comment by achadwick** [comment]
**Triage note**: this is something of a new feature, and it *may* need some string changes. Therefore it either needs to be addressed in the remainder of the alpha cycle, or bumped until after the 1.2 release.
