### ISSUE TITLE
How am I supposed to download this?

### ISSUE THREAD

**Issue by CanisVulpis** [mypaint/mypaint#1021]
How am i supposed to download MyPaint? Im just a digital artist looking to use it, since I had it on my old laptop. Back then it was simple, but now its insanely complex and I can't figure out for the life of my how I'm supposed to get it. I tried following the links but I just don't understand what I'm supposed to do right after that. 
If someone could just leave a step by step that would be so helpful. 
Thank you.

**Comment by jplloyd** [comment]
The latest official release is still [1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1), you can find the latest alpha releases here: https://github.com/mypaint/mypaint/releases

* Download the appimage file
* open a terminal
* `cd path_to_the_folder_of_the_downloaded_appimage_file`
* set it as executable with `chmod u+x name_of_appimage_file`
* run it with `./name_of_appimage_file` or just double clicking the file in your file browser/navigator

If that works out, you can close this issue.

**Comment by jplloyd** [comment]
I will interpret the lack of response as that of a happy user painting away. I hope that is the case :)
We should perhaps add some download instructions in the README. At least there are some on mypaint.org
