### ISSUE TITLE
how to script with fake input?

### ISSUE THREAD

**Issue by flyinskybtx** [mypaint/mypaint#1023]
i am working on a AI calligraphy subject,
I wonder if it is possible to script the strokes for autonomous calligraphic stroke rendering?
are there APIs or could I script with a fake input?

my sincere gratitudes for any help

**Comment by jplloyd** [comment]
Cool, I've been thinking  along the same lines a few times.

There is no API for doing this conveniently, and i don't think one will be on the table for a while (you can open a feature proposal in the forums and see if it gains support), but it shouldn't be that difficult hooking in and using the existing methods to do what you want.

Check out the `BrushWork` class in `lib/command.py` - I think specifically the stroke_to method will be of interest. That will give you an idea of the parameters used and how they are used in calls further down the chain.

You can also check out the `paint` test function in `tests/unported/performance.py` for an example of painting with pre-recorded data. The parameters might be slightly out of date for that one though.

I'm closing this as it's more of a feature request or enhancement than an issue (current policy is to focus on bugs), but if you proceed with this, I hope the hints are enough to get you started!

**Comment by flyinskybtx** [comment]
> Cool, I've been thinking along the same lines a few times.
> 
> There is no API for doing this conveniently, and i don't think one will be on the table for a while (you can open a feature proposal in the forums and see if it gains support), but it shouldn't be that difficult hooking in and using the existing methods to do what you want.
> 
> Check out the `BrushWork` class in `lib/command.py` - I think specifically the stroke_to method will be of interest. That will give you an idea of the parameters used and how they are used in calls further down the chain.
> 
> You can also check out the `paint` test function in `tests/unported/performance.py` for an example of painting with pre-recorded data. The parameters might be slightly out of date for that one though.
> 
> I'm closing this as it's more of a feature request or enhancement than an issue (current policy is to focus on bugs), but if you proceed with this, I hope the hints are enough to get you started!

Thanks for the answers.
The performance.py script indeed covered what i expect
