### ISSUE TITLE
Cannot disable the startup autorecover from settings

### ISSUE THREAD

**Issue by flyinskybtx** [mypaint/mypaint#1024]
Built from source, with no install but run mypaint.py
I cannot find a way to disable autorecovery startup from script or from settings.
Any idea how can I disable this function?

**Comment by jplloyd** [comment]
Under the "Load & Save" tab in the preferences there is a section where
`Automated Backups` can be turned off. If you are running your build using
`python setup.py demo` the setting will not persist between runs, so you'll
have to turn it off in the source.

Search for this line in gui/application.py and change the value to `False`
```
'document.autosave_backups': True,
```
If that does not work, something might be amiss.

Den mån 5 aug. 2019 kl 14:28 skrev flyinskybtx <notifications@github.com>:

**Comment by flyinskybtx** [comment]
> Under the "Load & Save" tab in the preferences there is a section where Automated Backups can be turned off. If you are running your build using "python setup.py demo" the setting will not persist between runs, so you'll have to turn it off in the source. Search for this line in gui/application.py and change the value to `False` 'document.autosave_backups': True, If that does not work, something might be amiss.

Thanks for your suggestions.
Does it means that if I want to disable the pop up at startup, I should disable autosave completely?

**Comment by jplloyd** [comment]
No problem. For future reference, there are two instances of these lines, one as below and one with `run(startup=True)`.
```
autosave_recovery = gui.autorecover.Presenter(self)
autosave_recovery.run(startup=False)
```
 Only the first instance should be removed to disable startup-triggered autorecovery, the second would disable the recovery functionality altogether.

Even after disabling autosave, the autorecovery would still trigger on the existing backups if you didn't deal with them first. If you _did_, the autorecover triggering would be a bug.

Assuming that wasn't the case, I'm closing this.
