### ISSUE TITLE
[Feature Request] Add support for dragging and dropping images into scratchpad

### ISSUE THREAD

**Issue by ykhurshid** [mypaint/mypaint#1028]
I covet this feature specifically for making it easier to use reference images. It's rather tedious to have to download images that I intend for one off use and would greatly prefer to being able to drag and drop them onto the scratchpad.

**Comment by odysseywestra** [comment]
@ykhurshid Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get wider community feedback.

**Comment by ykhurshid** [comment]
Done
