### ISSUE TITLE
Obtain MyPaint (and updates) through Chocolatey.org

### ISSUE THREAD

**Issue by victorwestmann** [mypaint/mypaint#103]
There's this new thing on Windows (that is available for 20 years or more in Linux) called [**Chocolatey**](www.chocolatey.org). It's sort of a package management application to let Windows users download, install and update softwares like Linux does. It could be a good idea to make **MyPaint** available there to make this project even more popular and to spread even more the word about us. ;-)

[I searched for **MyPaint** over there](http://chocolatey.org/packages?q=mypaint) and, by the time I write this, there is no package over there to serve our software. Even though **FileZilla, Gimp, Inkscape** and **Krita**, for instance, are already there.

So this could be useful. Cheers!

**Comment by viszu** [comment]
I try to use chocolatey for all of my installs now, and I also miss mypaint there
