### ISSUE TITLE
Add a repology badge to README

### ISSUE THREAD

**Issue by luzpaz** [mypaint/mypaint#1034]
### Summary
A way for users to see what downstream repositories carry mypaint

### Proposed design
The compact badge looks like so:  
[![Packaging status](https://repology.org/badge/tiny-repos/mypaint.svg)](https://repology.org/project/mypaint/versions)

The full badge looks like so (but may be too "bulky"):  
[![Packaging status](https://repology.org/badge/vertical-allrepos/mypaint.svg?header=mypaint)](https://repology.org/project/mypaint/versions)  

---------

**Note:** There is also a possibility to add the full badge in to it's own section, like so:

```
### Packaging Status

<details>
  <summary>Expand to see the packaging status of mypaint...</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/mypaint.svg?header=mypaint)](https://repology.org/project/mypaint/versions)  

</details>
```

**Which gives us:**  

### Packaging Status

<details>
  <summary>Expand to see the packaging status of mypaint...</summary

[![Packaging status](https://repology.org/badge/vertical-allrepos/mypaint.svg?header=mypaint)](https://repology.org/project/mypaint/versions)  

</details>

**Comment by jplloyd** [comment]
Added this when fixing some other badge problems, thanks for the suggestion!
