### ISSUE TITLE
Brushstrokes on touchscreen

### ISSUE THREAD

**Issue by ShaunNoWay** [mypaint/mypaint#1041]
Brushstrokes made with a mouse are smooth and controlled, but strokes made on a touchscreen with my finger or stylus pen are thin and fragmented.

![stroke](https://user-images.githubusercontent.com/14033754/68785774-abce0000-060c-11ea-8cd0-78feee992df2.png)

I'm running Arch Linux on a Lenovo Yoga 730

**Comment by jplloyd** [comment]
Hmm, that doesn't look like the same brush being used even. Every device has an individual brush associated to it, did you make sure to use the same brush for both devices (additionally, the stylus _might_ be a separate device as well, but I think that depends on hardware/drivers).

**Comment by ShaunNoWay** [comment]
Oh, my touchscreen was using a different brush than my mouse. That was easy.

Thanks. I will close this now.
