### ISSUE TITLE
MyPaint crashes as soon as Huion tablet is used

### ISSUE THREAD

**Issue by Incendia-Alba** [mypaint/mypaint#1043]
#### As soon as I touch the stylus to my Huion tablet, the program crashes.

It works fine with just the mousepad but crashes with the tablet.  Searching through past issues revealed a similar problem with MyPaint version 1.2, where using a Huion tablet caused the program to crash, but that error seems to have been resolved; in my case, the error report turned up by the debugging console is different from that past case (screenshot below, error message starts at Exception code).

Any help resolving the issue would be appreciated.  Thank you.

#### Basic system details

MyPaint version: v2.0.0-alpha. 13
Operating system: Windows 7
Desktop environment: Windows Explorer?  Not sure what this means
Huion Tablet driver: v14.7.60.339

#### Steps to reproduce

1. Start MyPaint
2. Plug in Huion Tablet (driver typically runs automatically in the background at computer startup)
3. Touch stylus to Huion Tablet (results in "click" on-screen)

#### Backtraces or error messages

![MyPaint Debug report](https://user-images.githubusercontent.com/58532254/70183602-5634c280-16a3-11ea-87ec-4a67eb5a52d4.png)

**Comment by jplloyd** [comment]
"Desktop environment" does not really apply to Windows, so don't worry about that.

What is the model of the tablet?

Two differences I notice between this case and #946:
* Windows 7
* Different and seemingly older driver version (but maybe driver versions are tied to models?)

Have you tried installing the latest drivers for your model?

**Comment by Incendia-Alba** [comment]
Apologies for the late response.  My tablet is a Huion 1060 Plus.  I'm in the midst of reinstalling a newer version of the driver, since the old one's Update button doesn't seem to be working.

Finished reinstalling the driver, and the tablet now works for painting with MyPaint, but the undo shortcut key on the tablet doesn't work.  That I can work around, so it's not as big of a deal; I'm not worried about it.

Thank you for your response.  The update did the trick.

**Comment by jplloyd** [comment]
Glad to hear that the update solved it!

Tablet settings usually have options for setting which key combination each tablet button/key should output. You could check which combination it outputs and just rebind "Undo" in MyPaint to match it (or vice versa).

**Comment by AesaraB** [comment]
Potentially related to #1043, I'm glad it's fixed for you
