### ISSUE TITLE
Brush Renaming Broken

### ISSUE THREAD

**Issue by civAnimal** [mypaint/mypaint#1045]
#### Description of the problem

In Brush Editor:
Attempting to rename a brush results in an auto-generated brush name; like b001, b002, etc.

#### Basic system details
Windows 8
mypaint w64 2.0.0 beta git 97372

**Comment by odysseywestra** [comment]
Could you read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs and edit your issue ticket accordingly? Thanks.

**Comment by jplloyd** [comment]
Cannot reproduce in Linux build. @odysseywestra You have a windows installation, right? Can you check if this and #1046 are actual issues on Windows? Both work fine on Linux.

**Comment by odysseywestra** [comment]
Can confirm that I can't rename any brushes in Window 10 as well. Can't even renamed them running as administrator either so we can probably scratch permissions off as an issue. Running in Debug mode gave me the following error when trying to rename a brush.

```python
Mypaint version: 2.0.0-beta.0+git.0bc97372
System information: Windows-10-10.0.17134-SP0
Using: Python 3.8.0, GTK 3.24.13, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.62.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint\gui\brusheditor.py", line 536, rename_button_clicked_cb(self=<brusheditor.BrushEditorWindow object at 0x00000...heditor+BrushEditorWindow at 0x000000002080adc0)>, button=<Gtk.Button object at 0x00000000218e8580 (GtkButton at 0x000000002157da40)>)
            dst_deleted = None
            for group, brushes in bm.groups.iteritems():
                for b2 in brushes:
  variables: {'group': (None, []), 'brushes': (None, [])}
AttributeError: 'dict' object has no attribute 'iteritems'
```
