### ISSUE TITLE
Three strings appear untranslated

### ISSUE THREAD

**Issue by libreajans** [mypaint/mypaint#1047]
I have completed Turkish translation on Weblate (https://hosted.weblate.org/projects/mypaint/mypaint/tr/)

When I compile MyPaint these three strings appear untranslated.

```
Always open in 1.x mode
Always open in 2.x mode
Open in 1.x mode unless file contains pigment layers
```

My PO file is here. 
[tr.po.txt](https://github.com/mypaint/mypaint/files/3992333/tr.po.txt

I used this repo to building an AppImage with my translation. 
https://github.com/mypaint/mypaint-appimage/releases

![2019-12-22 12-55-53 ekran görüntüsü](https://user-images.githubusercontent.com/6218679/71320483-02a4e000-24bd-11ea-8964-f53be153d320.png)

**Comment by odysseywestra** [comment]
@jplloyd Could you look into this since you are familiar with the translation process of MyPaint?

**Comment by jplloyd** [comment]
Confirmed that it isn't working as intended. I'll look into it.
