### ISSUE TITLE
MyPaint v2.0.0-beta.0 needs a libmypaint v2.0.0-beta.0

### ISSUE THREAD

**Issue by crabbedhaloablution** [mypaint/mypaint#1049]
Hi,
Really appreciate the work on mypaint.
Wanted to compile the beta0 today, but it errored out.
Looking through the last months commits, it looks to me like we need a beta0 of libmypaint to be able to compile the mypaint beta0 due to some commits on December 16th

Error attached, compiling against libmypaint 2.0.0_alpha2:
python3.6 setup.py build -j 24
running build
running build_config
running build_ext
building 'lib._mypaintlib' extension
swigging lib/mypaintlib.i to lib/mypaintlib_wrap.cpp
swig -python -Wall -noproxydel -c++ -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/libmypaint-2.0 -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pygobject-3.0 -I/usr/include/libpng16 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -DNO_TESTS -o lib/mypaintlib_wrap.cpp lib/mypaintlib.i
Deprecated command line option: -noproxydel. This option is now always on.
creating /var/tmp/portage/media-gfx/mypaint-2.0.0_beta0/work/mypaint-2.0.0-beta.0_python3.6/temp.linux-x86_64-3.6
creating /var/tmp/portage/media-gfx/mypaint-2.0.0_beta0/work/mypaint-2.0.0-beta.0_python3.6/temp.linux-x86_64-3.6/lib
creating /var/tmp/portage/media-gfx/mypaint-2.0.0_beta0/work/mypaint-2.0.0-beta.0_python3.6/temp.linux-x86_64-3.6/lib/fill
x86_64-pc-linux-gnu-g++ -march=native -mtune=native -ggdb -O2 -pipe -fPIC -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/libmypaint-2.0 -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pygobject-3.0 -I/usr/include/libpng16 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libdrm -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/python3.6m -c lib/mypaintlib_wrap.cpp -o /var/tmp/portage/media-gfx/mypaint-2.0.0_beta0/work/mypaint-2.0.0-beta.0_python3.6/temp.linux-x86_64-3.6/lib/mypaintlib_wrap.o --std=c++11 -Wall -Wno-sign-compare -Wno-write-strings -D_POSIX_C_SOURCE=200809L -DNO_TESTS -g -pthread -DMYPAINT_BRUSHES_DIR=\"/usr/share/mypaint-data/2.0/brushes\" -fopenmp -O3
<command-line>: warning: missing terminating " character
In file included from lib/mypaintlib.hpp:18,
                 from lib/mypaintlib_wrap.cpp:2806:
lib/tiledsurface.hpp: In member function ‘void TiledSurface::set_symmetry_state(bool, float, float, SymmetryType, int)’:
lib/tiledsurface.hpp:58:9: error: cannot convert ‘float’ to ‘MyPaintSymmetryType’
   58 |         symmetry_angle,
      |         ^~~~~~~~~~~~~~
      |         |
      |         float
In file included from lib/tiledsurface.hpp:13,
                 from lib/mypaintlib.hpp:18,
                 from lib/mypaintlib_wrap.cpp:2806:
/usr/include/libmypaint-2.0/mypaint-tiled-surface.h:73:62: note:   initializing argument 5 of ‘void mypaint_tiled_surface_set_symmetry_state(MyPaintTiledSurface*, gboolean, float, float, MyPaintSymmetryType, int)’
   73 |                                          MyPaintSymmetryType symmetry_type,
      |                                          ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from lib/mypaintlib.hpp:18,
                 from lib/mypaintlib_wrap.cpp:2806:
lib/tiledsurface.hpp: In member function ‘std::vector<std::vector<int> > TiledSurface::end_atomic()’:
lib/tiledsurface.hpp:67:7: error: ‘MyPaintRectangles’ was not declared in this scope; did you mean ‘MyPaintRectangle’?
   67 |       MyPaintRectangles bboxes = {BBOXES, rects};
      |       ^~~~~~~~~~~~~~~~~
      |       MyPaintRectangle
lib/tiledsurface.hpp:69:64: error: ‘bboxes’ was not declared in this scope
   69 |       mypaint_surface_end_atomic((MyPaintSurface *)c_surface, &bboxes);
      |                                                                ^~~~~~
error: command 'x86_64-pc-linux-gnu-g++' failed with exit status 1

**Comment by jplloyd** [comment]
Good point, and this is not necessarily obvious from reading the docs.

There are actually two changes to the libmypaint API that requires updating to the latest libmypaint master (well, not quite, since there have been a few localization-related commits). For the recent API-changes, you can check the commit logs for the exact commit of libmypaint required to build against. Just search for libmypaint in the log.

The full 2.0.0 release will be accompanied by a new stable release of libmypaint, but there are still a couple of things that need to be fixed, possibly including changes to the API (hence my reluctance to tag a beta for libmypaint just yet, but it'll be soon).

I have altered and expanded the [build instructions](https://github.com/mypaint/mypaint/blob/master/BUILDING.md) in 53b1cc8b77901e1c7121001783b6590745ce5d1b to make it clear that building the latest master in general requires the latest master of libmypaint.

Reopen if you don't think this is sufficient.
