### ISSUE TITLE
Trend Micro Deep Security thinks mypaint.exe is malware

### ISSUE THREAD

**Issue by rogierhofboer** [mypaint/mypaint#1055]
#### Description of the problem
Trend Micro Deep Security thinks mypaint.exe is malware.

![image](https://user-images.githubusercontent.com/6314129/74659724-24f16c00-5195-11ea-81ca-be57c6efddea.png)

Downloaded the Windows 64-bit .exe installer from:
https://github.com/mypaint/mypaint/releases/tag/v2.0.0

https://github.com/mypaint/mypaint/releases/download/v2.0.0/mypaint-w64-2.0.0-installer.exe

**Comment by jplloyd** [comment]
Hmm, could be the nsis installer component that is giving off a false (hopefully...) positive. To verify this, could you please download and extract the .7z standalone archive (same place as where you downloaded the .exe) and run the scanner on that folder instead. If it _does_ complain about something there, we can maybe do something about it, but otherwise it's probably the installer.

If the scanner can provide more detailed information about what exactly it thinks the malware is, that would be helpful.

_As with anything regarding Windows, I'll add that until we have someone willing to work actively on the port (more than just to keep it functional), Windows will in effect remain a second class citizen for this project, which is unfortunate._

**Comment by rogierhofboer** [comment]
It is not the installer, but the mypaint.exe started after installing.

**Comment by jplloyd** [comment]
Ok. That .exe only invokes [`python3w.exe mingw64/bin/mypaint %f`](https://github.com/mypaint/mypaint/blob/0991ebaebb8e9112ae45968087c9daaa37b2c760/windows/styrene/mypaint.cfg#L91), which means that Deep Security either:

* Thinks that `python3w.exe` is malware.
* Things that an executable that invokes another executable (of this kind) is malware.

I can't really blame them for that, since I assume it's very hard to trace what's actually happening once the python invocation is made (assuming it even tries to do that).

No more information from the scanner either than the malware claim? No details?

**Comment by rogierhofboer** [comment]
It started ok at first, but then when drawing a little, suddenly a got the warning.

It seems it happened because of the autosave, which explains why it first runs for a few minutes without problems. Some virus scanners trigger on any software that tries to encrypt or secure-hash things, even if it is legit, because it is what ramsonware does as well. The strange thing is... The autosave feature doesn't seem to do this at all... So I am kinda lost on this one.

The more detailed log entry:

`2020-02-17 14:40:51.000000 [+0100]: [Info/5] | Receive ADC Event!! <AntiMalwareAdcEvent userSid="S-1-5-21-1842990803-1696481106-3584784989-5417" scanType="0" engineType="1074790400" patternVersion="1.983.64" amConfigId="4" errorCode="0" fileSHA256="" scanResultAction="0" policyId="" sectionId="" recordTime="1581946851000" targetType="3" target="Multiple" eventId="0" scanAction="6" engineVersion="8.5.0.1116" malwareName="HEU_AEGIS_CRYPT" fileSHA1="1BAE44E923E524E4EF085E25F32ABB60CABD2D4E" infectedFilePath="c:\program files\mypaint-w64\mypaint.exe" fileMD5="">

	<AntiMalwareAdcEventItems>

		<AntiMalwareAdcEventItem restoreResult="-520159231" attackingProgram="c:\program files\mypaint-w64\mingw64\bin\python3w.exe" target="c:\users\rogierhofboer\appdata\local\microsoft\windows\inetcache\mypaint\doc.uk427z8h\autosave\data\a7696f16-f85a-487e-b170-1921d2affcde.png.tmp" />

		<AntiMalwareAdcEventItem restoreResult="-520159231" attackingProgram="c:\program files\mypaint-w64\mingw64\bin\python3w.exe" target="c:\users\rogierhofboer\appdata\local\microsoft\windows\inetcache\mypaint\doc.uk427z8h\autosave\data\b01a28ee-2565-406d-b728-5f085223744e-tile.png.tmp" />

		<AntiMalwareAdcEventItem restoreResult="-520159231" attackingProgram="c:\program files\mypaint-w64\mingw64\bin\python3w.exe" target="c:\users\rogierhofboer\appdata\local\microsoft\windows\inetcache\mypaint\doc.uk427z8h\autosave\data\b01a28ee-2565-406d-b728-5f085223744e.png.tmp" />

	</AntiMalwareAdcEventItems>

</AntiMalwareAdcEvent>`

**Comment by jplloyd** [comment]
Aha, I think it's triggered by the md5 hash function in the python hashlib
module, which in turn uses a shared object that also deals with some
encryption stuff.
I'll have to look into it, but yeah, there's nothing to worry about.


Den mån 17 feb. 2020 kl 17:29 skrev rogierhofboer <notifications@github.com

**Comment by jplloyd** [comment]
Just out of curiosity, if you feel inclined to dig deeper, do you get the same error when using MyPaint 1.2.1? The relevant (presumed relevant) code hasn't really changed.

**Comment by rogierhofboer** [comment]
Same result:

```
2020-02-18 13:14:23.000000 [+0100]: [Info/5] | Receive ADC Event!! <AntiMalwareAdcEvent userSid="" scanType="0" engineType="1074790400" patternVersion="1.985.64" amConfigId="4" errorCode="0" fileSHA256="" scanResultAction="0" policyId="" sectionId="" recordTime="1582028063000" targetType="3" target="Multiple" eventId="0" scanAction="6" engineVersion="8.5.0.1116" malwareName="HEU_AEGIS_CRYPT" fileSHA1="1BAE44E923E524E4EF085E25F32ABB60CABD2D4E" infectedFilePath="c:\program files\mypaint-w64\mypaint.exe" fileMD5="">

	<AntiMalwareAdcEventItems>

		<AntiMalwareAdcEventItem restoreResult="-520159231" attackingProgram="c:\program files\mypaint-w64\mingw64\bin\python2w.exe" target="c:\users\rogierhofboer\appdata\local\microsoft\windows\inetcache\mypaint\doc.xxqrmz\autosave\data\37435d49-a107-4861-80e4-621b53f6dd3c.png.tmp" />

		<AntiMalwareAdcEventItem restoreResult="-520159231" attackingProgram="c:\program files\mypaint-w64\mingw64\bin\python2w.exe" target="c:\users\rogierhofboer\appdata\local\microsoft\windows\inetcache\mypaint\doc.xxqrmz\autosave\data\92ac0ab6-3372-43b0-beb5-6ddf73dfd716-tile.png.tmp" />

		<AntiMalwareAdcEventItem restoreResult="-520159231" attackingProgram="c:\program files\mypaint-w64\mingw64\bin\python2w.exe" target="c:\users\rogierhofboer\appdata\local\microsoft\windows\inetcache\mypaint\doc.xxqrmz\autosave\data\92ac0ab6-3372-43b0-beb5-6ddf73dfd716.png.tmp" />

	</AntiMalwareAdcEventItems>

</AntiMalwareAdcEvent>
```

**Comment by rogierhofboer** [comment]
Some things that might prevent the false positive (didn't try yet):
- Use a different file location. Why is the Windows inetcache used?
- Don't use a UUID, but generate a regular temporary file and use the name as "autosave_uuid"

**Comment by jplloyd** [comment]
Ok, so it's something that simply hasn't been picked up on before.

> Some things that might prevent the false positive (didn't try yet):
> 
>     * Use a different file location. Why is the Windows inetcache used?
> 

Yeah, I noticed that too. Apparently the cache directory is determined by a call to this function: https://valadoc.org/glib-2.0/GLib.Environment.get_user_cache_dir.html (not via vala bindings, but the same function), which falls back to the inetcache when XDG_CACHE_HOME is not set (when is it ever on Windows?).

Not sure what the correct directory to use would be.

>     * Don't use a UUID, but generate a regular temporary file and use the name as "autosave_uuid"

It seems the use of uuid is more of a convenience than a necessity - as it avoids having to track the names assigned to other layers, either via some common structure or by checking existing files in the cache dir. Frankly I don't see why it couldn't just as well be a simple counter, but I might be overlooking something.

**Comment by jplloyd** [comment]
Here's a standalone build where the uuid is set up on layer creation and not immediately before the first backup: [mypaint-git-w64-2.1.0-alpha-master.73-standalone.7z](https://ci.appveyor.com/api/buildjobs/ke8abjr7q9udhhhm/artifacts/out%2Fbundles%2Fmypaint-git-w64-2.1.0-alpha-master.73-standalone.7z)  (41MB 7z archive).

Does it trigger the same warning?

**Comment by rogierhofboer** [comment]
Sorry, for the delay. I've tried, but same result.
I am going to report this to Trend Micro.

**Comment by jplloyd** [comment]
In a way it's good that it still triggers, if time delay or indirection made a difference that would easy to circumvent for actual malware. On the other hand I don't think one false positive is enough to warrant rewriting that part of the autosave (and potentially anything that uses the uuid calls). If it happens with multiple malware scanners we'll revisit it.
