### ISSUE TITLE
frame setting broken : spawns error message (icon also missing)

### ISSUE THREAD

**Issue by ncmprhnsbl** [mypaint/mypaint#1064]
#### Description of the problem

frame setting broken : spawns error message (icon also missing)
#### Basic system details

MyPaint version: Mypaint version: 2.1.0-alpha.0+git.425afe29 (libmypaint-git 2.0.0.alpha.r981.c28b059-1 )
Operating system: Arch(obarun) (AUR builds)
Window manager:  openbox

#### Steps to reproduce
1. Start MyPaint
2.notice missing icon (or broken icon) for enable frame (some others too*)
3. press enable frame > error message box appears(and frame setting process does not occur(edit: it does initiate if i just click on the canvas))
4. try menu>file>enable frame > error message box appears(and frame setting process does occur but error windows repeatedly appear while frame setting is enabled, seems ok once brush is reenabled)

#### Backtraces or error messages
```
python
Mypaint version: 2.1.0-alpha.0+git.425afe29
System information: Linux-5.5.9-arch1-2-x86_64-with-glibc2.2.5
Using: Python 3.8.2, GTK 3.24.14, GdkPixbuf 2.40.0, Cairo 1.17.3, GLib 2.64.0
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/document.py", line 2198, mode_radioaction_changed_cb(self=<gui.document.Document object>, action=<Gtk.RadioAction object at 0x7fd436e217c0 (GtkRadioAction at 0x562750d496d0)>, current_action=<Gtk.RadioAction object at 0x7fd436e21980 (GtkRadioAction at 0x562750f565e0)>)
                    mode = mode_class()
                self.modes.context_push(mode)
  variables: {'self.modes.context_push': ('local', <bound method ModeStack.context_push of <ModeStack [FreehandMode, FrameEditMode]>>), 'mode': ('local', <gui.framewindow.FrameEditMode object at 0x7fd43567c250>)}
  File "/usr/lib/mypaint/gui/mode.py", line 1369, context_push(self=<ModeStack [FreehandMode, FrameEditMode]>, mode=<gui.framewindow.FrameEditMode object>)
            self._stack.append(mode)
            mode.enter(doc=self._doc)
            self.changed(old=old_mode, new=mode)
  variables: {'mode.enter': ('local', <bound method FrameEditMode.enter of <gui.framewindow.FrameEditMode object at 0x7fd43567c250>>), 'doc': (None, []), 'self._doc': ('local', <gui.document.Document object at 0x7fd436dff2b0>)}
  File "/usr/lib/mypaint/gui/framewindow.py", line 116, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
            """Enter the mode"""
            super(FrameEditMode, self).enter(doc, **kwds)
            # Assign cursors
  variables: {'super': ('builtin', <class 'super'>), 'FrameEditMode': ('global', <class 'gui.framewindow.FrameEditMode'>), 'self': ('local', <gui.framewindow.FrameEditMode object at 0x7fd43567c250>), 'enter': (None, []), 'doc': ('local', <gui.document.Document object at 0x7fd436dff2b0>), 'kwds': ('local', {})}
  File "/usr/lib/mypaint/gui/mode.py", line 442, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
            self.__reset_delta_totals()
            return super(ScrollableModeMixin, self).enter(doc, **kwds)
  variables: {'super': ('builtin', <class 'super'>), 'ScrollableModeMixin': ('global', <class 'gui.mode.ScrollableModeMixin'>), 'self': ('local', <gui.framewindow.FrameEditMode object at 0x7fd43567c250>), 'enter': (None, []), 'doc': ('local', <gui.document.Document object at 0x7fd436dff2b0>), 'kwds': ('local', {})}
  File "/usr/lib/mypaint/gui/mode.py", line 1108, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
                try:
                    self.inactive_cursor = self.doc.app.cursors. \
                            get_action_cursor(self.ACTION_NAME,
  variables: {'self.inactive_cursor': ('local', <gui.framewindow.FrameEditMode object at 0x7fd43567c250>), 'self.doc.app.cursors.get_action_cursor': ('local', <bound method CustomCursorMaker.get_action_cursor of <gui.cursor.CustomCursorMaker object at 0x7fd43aeb3ac0>>), 'self.ACTION_NAME': ('local', 'FrameEditMode'), 'gui.cursor.Name.ARROW': ('global', 'cursor_arrow')}
  File "/usr/lib/mypaint/gui/cursor.py", line 331, get_action_cursor(self=<gui.cursor.CustomCursorMaker object>, action_name='FrameEditMode', cursor_name='cursor_arrow')
                return Gdk.Cursor.new(Gdk.CursorType.ARROW)
            return self.get_icon_cursor(icon_name, cursor_name)
  variables: {'self.get_icon_cursor': ('local', <bound method CustomCursorMaker.get_icon_cursor of <gui.cursor.CustomCursorMaker object at 0x7fd43aeb3ac0>>), 'icon_name': ('local', 'mypaint-frame-symbolic'), 'cursor_name': ('local', 'cursor_arrow')}
  File "/usr/lib/mypaint/gui/cursor.py", line 351, get_icon_cursor(self=<gui.cursor.CustomCursorMaker object>, icon_name='mypaint-frame-symbolic', cursor_name='cursor_arrow')
                if "symbolic" in icon_name:
                    icon_pixbuf = gui.drawutils.load_symbolic_icon(
                        icon_name, 18,
  variables: {'icon_pixbuf': (None, []), 'gui.drawutils.load_symbolic_icon': ('global', <function load_symbolic_icon at 0x7fd439cff700>), 'icon_name': ('local', 'mypaint-frame-symbolic'), 'fg': (None, []), 'outline': (None, [])}
  File "/usr/lib/mypaint/gui/drawutils.py", line 300, load_symbolic_icon(icon_name='mypaint-frame-symbolic', size=16, fg=(1, 1, 1, 1), success=None, warning=None, error=None, outline=(0, 0, 0, 1))
        icon_pixbuf, was_symbolic = info.load_symbolic(
            fg=rgba_or_none(fg),
  variables: {'icon_pixbuf': (None, []), 'was_symbolic': (None, []), 'info.load_symbolic': ('local', gi.FunctionInfo(load_symbolic)), 'fg': ('local', (1, 1, 1, 1)), 'rgba_or_none': ('local', <function load_symbolic_icon.<locals>.rgba_or_none at 0x7fd4365a2e50>), 'success_color': (None, []), 'success': ('local', None), 'warning_color': (None, []), 'warning': ('local', None), 'error_color': (None, []), 'error': ('local', None)}
Error: rsvg-error-quark: XML parse error: error code=201 (3) in (null):26:121: Namespace prefix xlink for href on use is not defined
 (0)
```
*other missing icons : zoom, "zoom switch", "overview navigation" .. these appear to work ok without errors

**Comment by jplloyd** [comment]
The xlink issue should have been fixed in b665173985de3f0c05af9db88b1e24cb4357fbc2, though that commit introduces a bunch of visual errors (export script and source sheet were not exactly in tip-top shape). Those errors will hopefully be fixed today.

Have you tried running: `gtk-update-icon-cache --force`

If that doesn't fix it, open the offending svg (which should live in
`$PREF/share/icons/hicolor/scalable/actions/`) in a text editor, and see if `xmlns:xlink="..."` appears in the `svg` tag (it should).

**Comment by ncmprhnsbl** [comment]
i presume `gtk-update-icon-cache --force /usr/share/icons/hicolor`
no noticable effect.. ( the install script does: `gtk-update-icon-cache -q -t -f usr/share/icons/hicolor`)
and  yes: `xmlns:xlink="http://www.w3.org/1999/xlink"`

**Comment by jplloyd** [comment]
That's curious. A temporary solution is to downgrade librsvg to the previous version (which is not as strict), but I'll see about fixing this properly within a day or two.

**Comment by ncmprhnsbl** [comment]
thanks, downgrading librsvg works for now.

**Comment by jplloyd** [comment]
With the latest commit _all_ icons should now be completely valid svg. I haven't run them against librsvg 0.48, so please try the latest master when you have time.

**Comment by ncmprhnsbl** [comment]
sorry to say, getting the exact same error :(

**Comment by jplloyd** [comment]
Ok, then it may be that old icon files are being used, cached or not. I ran the latest `rsvg-convert` (double checked to make sure it was running against 2.48) on the new icon svgs, and it produced correct pngs without warnings or errors across the board.

First we should test if the new icons are actually used: if they are, adding e.g. `<oh></dear>` right before the `svg` tag in both versions of mypaint-frame-symbolic.svg should result in a different error.

If they _are_ used, the problem is most likely a bug in a librsvg _dependency_, with libxml2 seeming like the most plausible culprit.

**Comment by ncmprhnsbl** [comment]
ok, seems like the new icons are not being used.. ie. added ,<oh></dear> etc.. and the error is the same .. so... this means? there's old icons somewhere? or the cache is not updating as it should?
tried deleting the cache then updating, to no avail..

**Comment by jplloyd** [comment]
My guess is that you have two sets of icons installed. I'm no Arch user, but it looks like it should install under whatever directory `pkgdir` was set to during the build/install.

If you don't know what that was, run

```
find /usr/share /usr/local/share $HOME/.local/share -name "mypaint-frame-symbolic.svg"
```
to see if you have multiple copies of the icons, and where they are located.

**Comment by ncmprhnsbl** [comment]
yep, that was it, extra hicolor set in ~/.local/share/icons.. no idea how that happened, something to keep an eye on..
thank you for you time and patience :)

**Comment by digitalcircuit** [comment]
## Workaround for Ubuntu 20.04
This is not supported and may break things.  Proceed at your own risk (there is a way to undo this).

For anyone finding this issue when using MyPaint on Ubuntu 20.04 LTS (`focal`), e.g. by hitting the `Search Tracker…` button, you can work around it by installing the latest `mypaint-data` from the current Ubuntu 20.10 (`groovy`) builds.

1.  Visit https://packages.ubuntu.com/groovy/all/mypaint-data/download
2.  Download the .deb file from any mirror
3.  Install via package manager (QApt, dpkg, Ubuntu Software, etc)
```
sudo dpkg -i mypaint-data_2.0.*_all.deb

# Example:
# sudo dpkg -i mypaint-data_2.0.0+git20200502-1_all.deb
```

In case an updated `mypaint-data` version gets uploaded to 20.10/`groovy` that no longer works with 20.04/`focal`, I've uploaded a copy of the [May 2nd version here](https://zorro.casa/sync/Hosting/Utilities/Development/MyPaint/issues/frame-setting-broken-icons/mypaint-data_2.0.0+git20200502-1_all.deb ).
*SHA256: `e7145fa95c09d1833d92d89d265e2af5b5eca01a4707b6de7faa474a6ce8f3fa`*

I'd still suggest trying the Ubuntu packages link first, or switch to the AppImage, be patient, etc.

### Undoing workaround
If you want to undo the changes, you can downgrade `mypaint-data`:
```
sudo apt install mypaint-data=2.0.0-2
```

The exact version may change!  Check `apt-cache show mypaint-data | grep 'Version'`.

## Developer discussion
@jplloyd I went to file a bug on Launchpad, and [I see you've already responded, thanks](https://bugs.launchpad.net/ubuntu/+source/mypaint/+bug/1878578 )!  In case it helps others, I'll share this comment over on Launchpad, too.

**Comment by HughR** [comment]
Very first use of MyPaint.  Crashes with
  Error: rsvg-error-quark: XML parse error: error code=201 (3) in (null):26:121: Namespace prefix xlink for href on use is not defined
 (0)

I had just installed it from Fedora 32 repos.  Version 2.0.0-0.6.beta.0.fc32.
Oh, and the error reporting mechanism screwed up somehow.  I got a 500 error from github.

You need more newbies like me to blunder into odd behaviour :-)
