### ISSUE TITLE
deleting/changing a keybind leaves default key in use

### ISSUE THREAD

**Issue by LightspeedLife** [mypaint/mypaint#1066]
#### Description of the problem

For example, changing or deleting the `backspace = 'clear layer'` binding, then returning to the paint window and hitting backspace will still clear the layer. Changing it to something that isn't so easy to hit with my wrist just adds the new binding to the action, making the action accesable with both bindings.

#### Basic system details

MyPaint version: both 1.2.1 and 2.0.0
Operating system: Arch Linux
Desktop environment: none

**Comment by jplloyd** [comment]
There are two underlying issues here:

1) The fallback bindings cannot be reconfigured (`backspace -> clear layer` is a fallback binding, I believe the default binding is the `delete` key).
2) `Backspace` cannot be bound to another action in the interface; pressing backspace in the keybinding prompt will simply delete the existing assignment for that action.

A short-term solution is to add a way to disable default bindings in the settings (on a per-setting basis) and possibly allow binding `Backspace` to actions as well (unless there is a good reason not to). That's probably going to be the solution in 2.1.0.

In the longer term keyboard input needs a proper rework to fix the issues preventing easy numeric inputs, contextual bindings (e.g. a binding having different actions for different tools) etc.

**Comment by LightspeedLife** [comment]
Okay, how do I disable the default bindings? I don't see an option in the settings.

**Comment by jplloyd** [comment]
> Okay, how do I disable the default bindings? I don't see an option in the settings.

I should have added some emphasis before, but I'll do it now instead:

>The fallback bindings __cannot be reconfigured__ ...

Until this can be changed in the UI, you'll have to manually remove or comment out the line 
```
k('Backspace', 'ClearLayer')
```
in the `_init_extra_keys` method in the file `$pref/lib/mypaint/gui/document.py`, where `$pref` is the installation prefix; usually `/usr` or `/usr/local` for system-wide installs. Not very convenient I'm afraid, but at least no recompilation is involved.

If you don't want any of the fallback bindings you can just comment out the line where `_init_extra_keys` is called.

**Comment by LightspeedLife** [comment]
Oh oh oh, I see. Now we're on the same page. Thanks for taking the time to point me where I needed to go. I'm sure it would've taken me a long time to figure it out myself.
