### ISSUE TITLE
MyPaint is not registering small strokes

### ISSUE THREAD

**Issue by danichou** [mypaint/mypaint#1074]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem

Hi there, I currently use a Huion tablet + Pen. I just installed MyPaint yesterday and it was working perfectly. 

I launched it today. Seemed fine at first but it is now having trouble registering my strokes. What happens is when I do a little stroke with the brush nothing comes. the only way to do this is for me to drag my pen across a large area and then MyPaint populate the whole stroke which I just did. If I want to just do tiny strokes, for some reason I have to double tap my pen on the tablet first to then draw. Which is very inconvenient because I can't little tiny lines or even bullet point etc. 

I do not think there is a n issue with my tablet and pen as it is brand new. I have actually tried using these with Microsoft whiteboard which worked perfectly fine. It easily registered all of my stokes and pen pressure too. 

Please if you can help that would be amazing :)

Dan
[✍ Fill in this section with a clear description of **ONE** problem.]
[☞ Stay on topic. Separate problems go in separate issues.]
[☞ Read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs first.]
[⚠ If you don't give us enough detail to allow us to reproduce your issue, we cannot help and your report will be closed.]
[☞ Check the title is short but useful. It should echo this description.]
[☞ Pictures and videos help us a lot. You can paste screenshots.]

#### Basic system details

MyPaint version: [✍ 1.2.0 stable, 1.2.1-beta.1, git revision NNNNNNN, …]
Operating system: [✍ Debian 8.3, Ubuntu 16.04, Windows 7, …]
Desktop environment: [✍ GNOME, Xfce, …]

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. Just try and draw on your canvas. 

#### Backtraces or error messages

There are no error messages, although what I notice is, when I tap my pen on the tablet the first time, a circle translucent circle seems to appear on the canvas, as if it is about to load something?? 
```
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by danichou** [comment]
strangely enough all it needed was to for me to close the app and relaunch it!!!!!!

**Comment by jplloyd** [comment]
Weird, but glad that it works now.

Feel free to reopen if this occurs again (if it's caused by something fixable on our end, we should fix it).

I edited your original post to remove the template stuff.

**Comment by danichou** [comment]
Thanks for getting back to me :) 

Now I worked out what the issues is. 

So on the Huion Tablet driver app which I have attached there is a button name "Administrator privileges". I will be honest I have no idea what this is meant to be for or what it is supposed to trigger. 
When I first use the pad on the left hand side it says device disconnected. Although I can still use my pen to draw on the pad. Now, when I don't tick Administrator privileges this is when I need to double tap my pen on the pad to start drawing on MyPaint or as I said to execute small strokes or bullet points. 

When I tick administrator privileges then app shows the device status as connected. When this happens MyPaint works perfectly fine.  

Now, what I am intrigued about is, why is it that I do not need to do this with Microsoft WhiteBoard. 

I wonder, is there a possibility that the way MyPaint is configured it decides not to recognise the pen at first until I have allowed for administrator privileges. 

What do you reckon? :)

Dan
 
![Huion Driver](https://user-images.githubusercontent.com/63809758/79592409-dea38500-80d1-11ea-85ca-fbfe4c5ec28f.PNG)

**Comment by jplloyd** [comment]
I'm afraid I don't know why that makes a difference, but thanks for posting the follow-up, it'll be useful to other people with the same problem.

MyPaint doesn't handle input directly; it gets the data from Gdk, which in turn (I believe) gets it from one of the API's provided by Windows. The problem could be with the Gdk implementation, or the API (unlikely), or the way the driver feeds data to said API (I think there are two, could be a bug in one of them). Probably nothing we can do about it, short of patching Gtk/Gdk and shipping said patched version (if indeed that is where the problem is).

**Comment by danichou** [comment]
Thank you so much for your help and insight on this. Hopefully someone else with the same issue will be able to see this. 

Take care
