### ISSUE TITLE
[bug] error on image drag n drop

### ISSUE THREAD

**Issue by jkotra** [mypaint/mypaint#1092]
#### Description of the problem

when i try to drag n drop a image into mypaint, i get the following error.

 `A Programming error has been detected`

#### Basic system details

MyPaint version:  2.0.1+git.478280f.dirty (flatpak)
Operating system: Arch Linux
Desktop environment: GNOME 3.36

#### Steps to reproduce

1. Start MyPaint
2. drag a image file into mypaint.
3. you get the error message  `A Programming error has been detected`
4. Nothing happen on clicking `Ignore Error`

#### Backtraces or error messages

```py
```python
Mypaint version: 2.0.1+git.478280f.dirty
System information: Linux-5.4.50-1-lts-x86_64-with-glibc2.2.5
Using: Python 3.7.4, GTK 3.24.20, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.3
Traceback (most recent call last):
  File "/app/lib/mypaint/gui/drawwindow.py", line 290, _drag_data_received_cb(self=<drawwindow.DrawWindow object at 0x7f70369a8960 (MyPaintDrawWindow at 0x55c3378722a0)>, widget=<drawwindow.DrawWindow object at 0x7f70369a8960 (MyPaintDrawWindow at 0x55c3378722a0)>, context=<GdkX11.X11DragContext object at 0x7f703517e1e0 (GdkX11DragContext at 0x55c337c08e50)>, x=471, y=435, data=<Gtk.SelectionData object at 0x7f7035185980 (GtkSelectionData at 0x7ffea79cb2a0)>, info=1, time=1176246)
                # working file.
                uri = rawdata.split("\r\n")[0]
                file_path, _h = lib.glib.filename_from_uri(uri)
  variables: {'uri': (None, []), 'rawdata.split': ('local', <built-in method split of bytes object at 0x7f70351859d0>)}
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jplloyd** [comment]
Thanks for reporting, when I found this bug myself last month I was really surprised that nobody had reported it.

It only affects python3 builds, and was fixed here: 66b2ba98bd953afa73d0d6ac71040b14a4ea266b

The fix will be part of the 2.1.0 release, which will probably be in September or October of this year, but if some other serious bugs are surfaced, there may be a 2.0.2 release before that (which would include the fix as well).

Until then python3 users will either have to use patched builds (using the commit referenced above) or use `Open file` from the menu.

**Comment by mttkay** [comment]
I'm still running into this bug with MyPaint 2.0.1. I installed it as a flatpak (Pop_OS 21.04)

The release notes mention several Python 3 related bug fixes:


![Screenshot from 2021-09-23 08-36-49](https://user-images.githubusercontent.com/102802/134463971-acde78cc-c380-4749-8361-b00e969f1d0c.png)

Was the bug fix released already? Is the solution to install a different version of Python if not?

Thanks!

**Comment by rugk** [comment]
@mttkay see https://github.com/mypaint/mypaint/issues/1165 it's likely the same issue

**Comment by eintr** [comment]
Got same issue just now.

~~~~
2.0.1+gitexport.478280f

(Python 3.10.6, GTK 3.24.33, GdkPixbuf 2.42.8, Cairo 1.16.0, GLib 2.71.3)
~~~~
