### ISSUE TITLE
Some brushes do not stop to paint (when should) using wacom tablet

### ISSUE THREAD

**Issue by omaluma** [mypaint/mypaint#1096]
#### Description of the problem

Using some brushes, even not pressing onto the wacom tablet, but just dragging on the air over the canvas, a less opaque stroke is traced.

![Captura de pantalla de 2020-07-22 21-26-43](https://user-images.githubusercontent.com/6019562/88247077-176b7100-cc62-11ea-8207-425dcf8c6de7.png)

This suddenly  starts to happen with no apparently reason.

Modifying the pen sensitiveness on gnome-control-center do not change the result.

#### Basic system details

MyPaint version: 2.0.0+gitexport.af5225a
Operating system: Ubuntu 20.04 LTS
Desktop environment: GNOME
Wacom Tablet: Intuos 3 6x11

#### Steps to reproduce

1. Start MyPaint
2. choose a brush (some brushes with this error on classic collection: dry-brush, rounded, knife, marker fat, marker-small, textured ink, ink blot, short grass).
3. press the pen over the tablet surface.
4. stop to press and drag to other point on canvas.

#### Backtraces or error messages

This is what `mypaint` command drop until close the window:

```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: POSIX: LANG='es_MX.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE='es_MX:es'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'es_MX:es'
INFO: gui.compatibility: Setting mode to 2.x (standard)
INFO: gui.compatibility: Setting default layer type to Pigment
INFO: gui.device: New device 'Wacom Intuos3 6x11 Pen cursor' (GDK_SOURCE_CURSOR, axes:6, class=X11DeviceXI2, vendor='056a', product='00b5')
INFO: gui.device: New device 'Wacom Intuos3 6x11 Pen eraser' (GDK_SOURCE_ERASER, axes:6, class=X11DeviceXI2, vendor='056a', product='00b5')
INFO: gui.device: New device 'Wacom Intuos3 6x11 Pen stylus' (GDK_SOURCE_PEN, axes:6, class=X11DeviceXI2, vendor='056a', product='00b5')
INFO: gui.device: New device 'Wacom Intuos3 6x11 Pad pad' (GDK_SOURCE_TABLET_PAD, axes:6, class=X11DeviceXI2, vendor='056a', product='00b5')
INFO: gui.device: New device 'Virtual core XTEST pointer' (GDK_SOURCE_MOUSE, axes:2, class=X11DeviceXI2, vendor=None, product=None)
INFO: gui.document: Initialized background from '/usr/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'
WARNING: gui.topbar: No icon for 'WindowMenu' in the fullscreen state

(mypaint:10194): Gtk-WARNING **: 21:30:52.438: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
INFO: gui.brushmanager: Switching default pigment setting to On
INFO: gui.compatibility: Setting default layer type to Pigment
INFO: lib.document: save_ora: '/home/myuser/.local/share/mypaint/scratchpads/.tmpsave.autosave.ora' (None, {'save_srgb_chunks': True, 'progress': <Progress 0.0/None>})


```

**Comment by jplloyd** [comment]
First thing to check is if the global pressure curve in your preferences has been changed. The leftmost point should be at the very bottom for an input pressure of 0 to map to a _brush pressure_ of 0.

If the curve is ok, run `mypaint` from a terminal, click on the menu option `Help->Debug->Print Brush Input Values to Console` (if translated, those are the second items in both menus). Then move the stylus over the canvas without touching it and check the reported value in the terminal. It should be 0. If it is not, your wacom settings need to be adjusted.

Side note:
In the general case, whether a stroke is created is not directly connected to pressure, but rather radius and opacity. By default, pressure is mapped so that a pressure of 0 results in an opacity of 0 (no stroke is drawn), though individual brushes are free to override this. However, all of the brushes you list has the default behaviour, unless the `opacity multiply` setting has been modified so that it is not 0 even when the pressure is 0.

**Comment by jplloyd** [comment]
@omaluma Have you tried any of the suggestions in my previous reply?

If the case is that the stylus always reports a low pressure, even when it is lifted from the tablet, that is easily fixable by adjusting the global pressure mapping in the preferences. If for example that the stylus is reporting a pressure of 0.2 (an exaggerated example), when it should be 0, you could set the mapping like this:

![image](https://user-images.githubusercontent.com/5107852/88845729-dedd1180-d1e4-11ea-94a8-cef3d06ce35a.png)

**Comment by omaluma** [comment]
Sorry about being late on answers.

After rebooting the computer (but only after this, because I tried removing the config files, and even the package), the brush behavior return to normal.

No changes on the pressure curve on the next start.

But very useful to have your advice on eye for troubleshooting.

I have tried, since then, to reproduce the problem, so I can figure how it happens and bring this information here, because it has not been the only time it has happened to me -the first time, it happened on my laptop using a cintiq tablet. But no success on reproducing the issue.

So I'd prefer to close the issue, and, if it happen again, check the logs generated, the changes made on the preferences, try to fix if I'm able, and bring that information here to make it useful to you and other.

Thank you.

**Comment by bschibalsky** [comment]
I had the same problem. It seems to be an issue with some wacom pens. I tried 3 different pens. Two of them constantly report something like 0.005 pressure, even when only hovering. For some reason other painting applications doesn't seem to care (maybe has something to do with the default threshold?). Fortunately it's easily fixable by adjusting the global pressure (thanks @jplloyd)
