### ISSUE TITLE
Add installing mypaint with winget (Windows)

### ISSUE THREAD

**Issue by dinhanhx** [mypaint/mypaint#1098]
Like the title, recently my [pull request in winget-pkgs](https://github.com/microsoft/winget-pkgs/pull/2959) has been merged. Therefore, now it's possible to download and install MyPaint 2.0.1 with [winget](https://github.com/microsoft/winget-cli)

### To search
```Shell
winget search MyPaint
```

### To install
```Shell
winget install --id MyPaint.MyPaint
```

Please add these details to README.md or Repos wiki section to make everyone know about this.

**Comment by jplloyd** [comment]
The manifest looks fine to me. Thanks for putting in the work!

Info added to README.md in: da4da88c0db1cf3237cb8aacb9094be08bf52471
