### ISSUE TITLE
Install libs to standard dir on POSIX

### ISSUE THREAD

**Issue by badshah400** [mypaint/mypaint#1105]
### Description of the problem

Currently on my Linux (openSUSE Tumbleweed, 64-bit) mypaint defaults to installing its lib to `/usr/lib` which is not a standard dir on 64 bit Linux systems (`/usr/lib64` is). Indeed, a comment on Line#171 in [mypaint.py](../blob/master/mypaint.py) suggests as much. This is a request to move the default installation of the libs to a more standard path; the best location may be the system `PYTHONPATH` or into `/usr/lib(64)/` for 32-bit (64-bit) systems.

openSUSE is currently switching from using `/usr/lib` to `/usr/libexec` as the dir for non-path executables, which causes mypaint's builds to fail. That is what prompted me to open this issue.

#### Basic system details

MyPaint version: 2.0.1
Operating system: openSUSE Tumbleweed
Desktop environment: GNOME on Wayland

**Comment by badshah400** [comment]
To be clear, the build failure for openSUSE RPMs itself isn't a major issue and quite easily fixed. Nonetheless, I wanted to raise the issue for a more general fix for mypaint's installation paths.

**Comment by jplloyd** [comment]
I agree, the way things are currently set up has a few shortcomings, and this is one of them. The packagers can override where the files are installed by providing the installation directories to the `setup.py` script, e.g:

```
python3 setup.py install --prefix=/usr/  \
--install-purelib='$base/lib64/mypaint' \
--install-platlib='$base/lib64/mypaint'
```

but the main script just makes assumptions about the library directories based on the location of the main script (a slightly modified version of `mypaint.py`), regardless of what was specified.

I will probably fix it this weekend.

**Comment by badshah400** [comment]
Thanks, that would be greatly appreciated.

**Comment by jplloyd** [comment]
Quick update on this. I have written a patch that makes the main script respect the paths set at installation (except when running from the source tree), but I need to set up something sensible to allow the setup to work for both absolute and relative installs (necessary for the appimage and windows builds).

**Comment by badshah400** [comment]
Big thanks for PR #1109. I was just trying that PR as a patch and it correctly respects the `--install-pure/platlib` specifications made during `./setup.py install` However, one problem when building RPM packages is that the `mypaint` and `mypaint-ora-thumbnailer` scripts seem to pick up the `DESTDIR` (or `--root`) (which for RPM builds refers to `buildroot` — the root dir of the system on which the pkg is built). This will almost certainly cause issues when these RPMs are installed on another machine. For example, when setting `/usr/bin/python3 setup.py install -O1 --skip-build --force --root /home/abuild/rpmbuild/BUILDROOT/mypaint-2.0.1-0.x86_64 --prefix /usr --install-platlib=/usr/lib64/mypaint
`

`cat /usr/bin/mypaint-ora-thumbnailer`
```
[   14s] #!/usr/bin/python3 -s
[   14s] 
[   14s] #
[   14s] # ***DO NOT EDIT THIS FILE***: edit mypaint-ora-thumbnailer.py instead.
[   14s] #
[   14s] # Auto-generated version info follows.
[   14s] MYPAINT_VERSION_BASE='2.0.1'
[   14s] MYPAINT_VERSION_FORMAL='2.0.1'
[   14s] MYPAINT_VERSION_CEREMONIAL='2.0.1+gitexport.478280f'
[   14s] 
[   14s] MYPAINT_DIR_PATHS = {'platlib': '/home/abuild/rpmbuild/BUILDROOT/mypaint-2.0.1-0.x86_64/usr/lib64/mypaint', 'purelib': '/home/abuild/rpmbuild/BUILDROOT/mypaint-2.0}
```

**Comment by jplloyd** [comment]
Thanks for the feedback. Yes, I suspected this solution wouldn't really work without considering `--root`. I think solving that by determining the relative paths (relative to the scripts) at install time, should work. That would also get rid of the special case currently there for windows/appimage installs. I'll see about it this weekend.

**Comment by jplloyd** [comment]
The PR is updated (windows build fails for unrelated reasons, as is so often the case) with changes that should allow for most/all kinds of packaging approaches. Do take a look when you have time (I'm not in a hurry to merge this).

**Comment by badshah400** [comment]
+1 from me for this updated patch. Builds fine and runs fine with `--install-platlib` specified during install. Thanks.

**Comment by jplloyd** [comment]
The PR is merged, so packagers can now control the installation layout according to whatever convention their target system uses. The default configuration is unchanged, however.
