### ISSUE TITLE
Edit Icon window always appears behind the Brush Settings Editor

### ISSUE THREAD

**Issue by charbelnicolas** [mypaint/mypaint#1110]
#### Description of the problem

When you click on the "Edit Icon" button it will always appear behind the "Brush Settings Editor" window, most of the times hiding it from view.

#### Basic system details

MyPaint version: v2.0.1 Official AppImage
Operating system: Arch Linux
Desktop environment: Gnome 3.36

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint.
2. Right click on any brush and click on "Edit Brush Settings".
3. Click on "Edit Icon".
4. The "Brush Icon" window should appear behind the "Brush Setttings Editor" window (this is on a 1920 x 1080 resolution).

** Check attached zip with video for more evidence.

[editiconbug.zip](https://github.com/mypaint/mypaint/files/5210529/editiconbug.zip)

**Comment by jplloyd** [comment]
Thanks for reporting, and sorry for the slow response. I _can_ replicate this with Gnome 3.30 on Ubuntu 20.04, (but not on Awesome WM, everything else being the same).

I will see what can be done about it some time next week.

**Comment by jplloyd** [comment]
The fix will be part of the 2.1.0 release (won't be for another couple of months), but in the meantime you can comment out or remove the line that is removed in [the commit above](https://github.com/mypaint/mypaint/commit/c0b7ea028cbb1e4092aacb30a8cb1b10675547a8).
