### ISSUE TITLE
Colour Picker doesn't pick up from the cursor point

### ISSUE THREAD

**Issue by peterws** [mypaint/mypaint#1116]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem

[✍ Fill in this section with a clear description of **ONE** problem.]
[☞ Stay on topic. Separate problems go in separate issues.]
[☞ Read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs first.]
[⚠ If you don't give us enough detail to allow us to reproduce your issue, we cannot help and your report will be closed.]
[☞ Check the title is short but useful. It should echo this description.]
[☞ Pictures and videos help us a lot. You can paste screenshots.]

#### Basic system details

MyPaint version: [✍ 1.2.0 stable, 1.2.1-beta.1, git revision NNNNNNN, …]
Operating system: [✍ Debian 8.3, Ubuntu 16.04, Windows 7, …]
Desktop environment: [✍ GNOME, Xfce, …]

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. [✍ second step]
3. [✍ third step]

#### Backtraces or error messages

```I'm running 1.2 and 1.0.  Problem's the same.  Cursor point is not the pick up point; that is one inch south-east.  Help appreciated!
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by peterws** [comment]
I'm running windows 10 with a wacom tablet but this issue happens with a touchpad and also a mouse.  I tried the latest stable version for W10,  but !.0 or 12 are much better.

**Comment by jplloyd** [comment]
>  I tried the latest stable version for W10

So this problem does not occur with 2.0.1?

**Comment by peterws** [comment]
I tried 2 something or other.  It was the latest stable, and it threw up some strange stuff.  I'll try it again; I have a laptop (netboo) and desktop both running W10, full version.  Both exhibit the same .
Thx for your response.

**Comment by peterws** [comment]
I tried the  2.01 and it went crazy.  Thought my little lappie was gonna throw a wobbler.  It was me who did that.
Won't accept my Wacom; I ran the thing through test MyPaint tablet support.  Kinda hoping things'll improve; there seems nothing out there to compare.

**Comment by jplloyd** [comment]
If we are talking about a netbook in the sense of an intel atom-powered, or A-series apu-powered machine from 8-9 years ago, running windows on top of that, it's almost certainly not powerful enough to run v2.0 smoothly (iirc those machines struggled running v1.0 even).

That being said, other than the title you haven't actually provided a description of your problem. You can edit your original post and fill in the details in the template (replacing the placeholders). Versions, and steps to reproduce is what's most important there.

**Comment by peterws** [comment]
I'll try harder.
The problem is on MyPaint 1.00.  and !.20 both of which display the same characteristic.  Using an HP Ideapad with Windows 10 (full) there's a problem with the colour picker.  It does not pick the colour from the cursor point, either using a Wacom or just my laptop touchpad.  I need to move the cursor 30mm southeast of the target colour to achieve it.
Utilsing a Q-book from goodness knows when, everything is fine.
So all I want is the cursor colour detector "R"  to work fine with my Windows 10 device.
Thanks for listening!

**Comment by jplloyd** [comment]
So it's an offset problem. Are you using an external monitor, with the mypaint window on that monitor? There are plenty of issues (upstream issues, nothing we can do anything about in our code) of input offsets with secondary displays, but I don't recall seeing anyone having that problem on their primary display.

**Comment by peterws** [comment]
Thanks for your help; in desperation, I reduced the Windows display from 125% to default 100%.
Everything's fine now!  Working as it should.

**Comment by peterws** [comment]
Hello!  I managed to sort the problem.  You'll see my response on Github.
It was nothing more than the need to utilise the Windows default screen
magnification.  I was using 125%.

**Comment by jplloyd** [comment]
Thank you, I did see it (and your email shows up in the issue tracker as well).
