### ISSUE TITLE
My Wacom CTL-470 isn't recognised in MyPaint (in Fedora 32 & Fedora 33).

### ISSUE THREAD

**Issue by GlacierFox** [mypaint/mypaint#1119]
Hi there. I'm using a Wacom CTL-470 and it isn't being recognised in MyPaint so I get no pressure input. The strange thing is, it works fine in Krita and Gimp. My tablet is recognised in the operating system.
I'm currently on the latest stable release and I've also tried the rolling release and alpha to the same effect.

I'm on Fedora 33 using KDE. It works fine on my Debian system, also running KDE. Is there some dependency I need to install on Fedora that I may have missed? 

Is there anything I can provide to you that may help? Some sort of log or something, sorry I'm not too versed in software programming.

EDIT

Here's the output of x-setwacom >

> xsetwacom --list devices        
> Wacom Bamboo Connect Pen stylus         id: 9   type: STYLUS    
> Wacom Bamboo Connect Pad pad            id: 10  type: PAD       
> Wacom Bamboo Connect Pen eraser         id: 18  type: ERASER  

and its recognised by x-input as a wacom pen tablet. Not sure why its not working, works in krita and gimp. Wont show up in the devices menu in Mypaint, only my mouse does.
Thanks!

**Comment by jplloyd** [comment]
The device information and setup uses Gtk's device api, so I would guess that some depency of _that_ code has changed slightly in Fedora 33 (just a guess). Krita uses their own version of libinput (if my info is up to date) and I _think_ GIMP is still using gtk2 in release builds, so that could be why only MyPaint is affected.

If you go to `Help -> Debug -> Test Input Devices` and move the stylus over your tablet, does it show up in the info panel?
If not, what does it say there instead?

**Comment by GlacierFox** [comment]
Hi there.
When I use the 'Test Input Devices' tool it seems to recognize that my tablet is a pointing device . It shows if its lifted up and down and where it is on the axis but no pressure information. I can essentially use my tablet like a mouse in MyPaint. The pressure options are unavailable in the brush settings also.
The only thing that shows in the Devices menu in the settings editor is some sort of generic pointing device and nothing else which I expect is my mouse.  On my Debian laptop, if I plug in my tablet it shows it correctly in the Devices menu with its correct name and allows me to use pen pressure fine.
Just loaded up a fresh copy of fedora 32 on a spare SSD just to check and I have the same problem there too after updating the system.  Its something to do with a code difference on Fedora after version 30... I'm guessing of course.

I've tried both versions of the Appimage and the flatpack and got the same results.

**Comment by jplloyd** [comment]
Running the docker image for Fedora 33 I have confirmed a couple of things:
* The GIMP release is indeed still using gtk2.
* Your tablet model is listed in the libwacom database.
* The version of MyPaint in the repo is 2.0.0

When you said that you were using the latest stable release, were you referring to the appimage of v2.0.1.
If so, do you get the same problem with the version in the repo (the one you would get when running `dnf install mypaint` or `yum install mypaint`)?

**Comment by GlacierFox** [comment]
Yes, I was referring to 2.0.1. I tried both the ALT version and the smaller version of the AppImage. 
I also tried the Flatpak version which seems to be at version 2.0.1 also. 
I also tried running it from the default repo and get the same problems.

**Comment by AlbinoDrought** [comment]
Similar issue here, running:

    MyPaint 2.0.1+gitexport.478280f

    (Python 3.9.5, GTK 3.24.29, GdkPixbuf 2.42.6, Cairo 1.17.4, GLib 2.68.0)

```
xsetwacom --list devices
Wacom Intuos S Pen stylus       	id: 22	type: STYLUS    
Wacom Intuos S Pen eraser       	id: 23	type: ERASER    
Wacom Intuos S Pen cursor       	id: 24	type: CURSOR    
Wacom Intuos S Pad pad          	id: 25	type: PAD     
```

```
OS: Manjaro Linux x86_64 
Kernel: 5.11.19-1-MANJARO 
Resolution: 1920x1080 
DE: Plasma 
WM: KWin 
```

 MyPaint only shows the `Core Pointer` device:

![image](https://user-images.githubusercontent.com/852873/119858359-40cfdb80-bec9-11eb-82df-aedd9962af63.png)

It can be used for basic lines, but pressure sensitivity doesn't work.

Xournal++, also GTK 3, also shows an empty list of devices: 

![image](https://user-images.githubusercontent.com/852873/119860366-1717b400-becb-11eb-9edb-853836c2ecab.png)

GIMP 2.10.24 (GTK 2?) shows many devices including the tablet, but I don't know how to use GIMP or which settings would make sense here (all the tablet devices started as "Disabled", lines are drawn without pressure sensitivity, might be a setting somewhere):

![image](https://user-images.githubusercontent.com/852873/119858989-cfdcf380-bec9-11eb-8191-d61a05cde6ad.png)

Pressure works as expected in Krita 4.4.3:

![image](https://user-images.githubusercontent.com/852873/119858290-30b7fc00-bec9-11eb-85c3-b695cf5c9cb2.png)

**Comment by AesaraB** [comment]
Consolidated to #1220
