### ISSUE TITLE
Touching the color or stroke pickers with finger touch throws an error

### ISSUE THREAD

**Issue by 4903000** [mypaint/mypaint#1123]
#### Description of the problem

This is about the two pickers that sit at the bottom corners of the main window. When either is poked with a touch device, the following error is given:

```python
Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-5.6.19-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-gentoo-2.7
Using: Python 3.7.9, GTK 3.24.22, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.3
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/picker.py", line 545, _clicked_cb(self=<gui.picker.ButtonPresenter object>, button=<Gtk.Button object at 0x7f7caced3820 (GtkButton at 0x5624f11fec00)>)
            assert event.type == Gdk.EventType.BUTTON_RELEASE, (
                "The docs lie! Current event's type is %r." % (event.type,),
            )
  variables: {'event.type': ('local', <enum GDK_TOUCH_END of type Gdk.EventType>)}
AssertionError: ("The docs lie! Current event's type is <enum GDK_TOUCH_END of type Gdk.EventType>.",)
```

It seems that simply removing the failing assert (or ignoring the error) and accounting for the TOUCH_END event in activate_from_button_event() allows you to start picking things with a touch press on the button.

#### Basic system details

Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-5.6.19-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-gentoo-2.7
Using: Python 3.7.9, GTK 3.24.22, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.3
Operating system: Gentoo
Desktop environment: GNOME

#### Steps to reproduce

1. Start MyPaint
2. Using touch screen, touch either of the buttons on the bottom panel - color or stroke picker
3. Error window appears

#### Backtraces or error messages

See above

**Comment by odysseywestra** [comment]
@jplloyd Okay so it looks we'll need to add support for GDK_TOUCH_END EventType or at least treat them as BUTTON_RELEASE in line 113 of `gui/picker.py`. MyPaint at the current doesn't really handle touch events from the looks of it. It something that needs to be added eventually.

**Comment by jplloyd** [comment]
Yep, fortunately my old laptop has a touchscreen (that I never use, except by accident) so I can confirm the problem, and fixing it shouldn't be difficult.

**Comment by odysseywestra** [comment]
@4903000 so you just need to rebuild and your are good.

**Comment by 4903000** [comment]
Absolutely fantastic. Thank you for your time.
