### ISSUE TITLE
Option to align menu bar from right to left (right handed comfort on screen tablets like cintiq) Possible?

### ISSUE THREAD

**Issue by Lovewyrm** [mypaint/mypaint#1131]
What the title states.

If it's possible, it would be extremely awesome, comfort wise, if the menu bar could be 'flipped' and aligned to the right of the application window.

instead of:
File | Edit | Etc | Help |............................................................................|
|...........................................................................| Help | Etc | Edit | File

Or a similar configuration, anything but having go alllllllllllllllllllllll the way over to the left with my right hand on a huge mc large screen like on a high end cintiq.
In fact, this should be a thing for anything, but I'm starting to suggest it here, because I love mypaint.

**Comment by jplloyd** [comment]
While it _is_ possible to set up something like that. The better solution, in my opinion, is to use the **Popup Main Menu** action, which you can bind with both key- and key+button combinations. That way you barely have to move your hand at all.

**Comment by Lovewyrm** [comment]
Ah, yes. That is true. I'm going to close this then and move on to the next project :P
