### ISSUE TITLE
Brush editor slider disappeared?

### ISSUE THREAD

**Issue by ChengduLittleA** [mypaint/mypaint#1133]
#### Description of the problem

Brush editor sliders all disappeared as in the screen shot:
![图片](https://user-images.githubusercontent.com/7886249/105457073-31dde000-5cc1-11eb-951f-c40197d8ec28.png)

#### Basic system details

MyPaint version: 2.1.0-alpha+git.31ba28f9  (On another machine of mine I have 2.0.0 and it works okay, I haven't been explicitly adjusting brushes on this build, so I just noticed the problem today.)
Operating system: Xubuntu 20.04
Desktop environment: XFCE

#### Steps to reproduce

Open the brush editor and no slider is present. Doesn't seem to be a theme problem as the version worked is also using this gtk theme.

#### Backtraces or error messages

These are the messages shown during launching

```
INFO: mypaint: Running from installed script...
INFO: mypaint: ...using static relative paths
WARNING: gui.userconfig: Failed to load settings file: /tmp/demo-lhMRtX/_config/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: POSIX: LANG='zh_CN.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE='zh_CN:en_US:en'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'zh_CN:en_US:C:en'
INFO: gui.application: Created basedir u'/tmp/demo-lhMRtX/_config'
INFO: gui.application: Created data subdir u'/tmp/demo-lhMRtX/_config/backgrounds'
INFO: gui.application: Created data subdir u'/tmp/demo-lhMRtX/_config/brushes'
INFO: gui.application: Created data subdir u'/tmp/demo-lhMRtX/_config/scratchpads'
WARNING: gui.userconfig: Failed to load settings file: /tmp/demo-lhMRtX/_config/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.compatibility: Setting mode to 2.x (standard)
INFO: gui.compatibility: Setting default layer type to Pigment
INFO: gui.brushmanager: Merging upstream brush changes into your collection.
INFO: gui.device: New device 'Microsoft Surface Type Cover Touchpad' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='045e', product='09c0')
INFO: gui.device: New device 'ipts 045E:001F Touchscreen' (GDK_SOURCE_TOUCHSCREEN, axes:4, class=X11DeviceXI2, vendor='045e', product='001f')
INFO: gui.device: New device 'ipts 045E:001F Pen (0)' (GDK_SOURCE_PEN, axes:5, class=X11DeviceXI2, vendor='045e', product='001f')
INFO: gui.device: New device 'ipts 045E:001F Mouse' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='045e', product='001f')
INFO: gui.device: New device 'ipts 045E:001F UNKNOWN' (GDK_SOURCE_TOUCHSCREEN, axes:4, class=X11DeviceXI2, vendor='045e', product='001f')
INFO: gui.device: New device 'Microsoft Surface Type Cover Consumer Control' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='045e', product='09c0')
INFO: gui.device: New device 'Microsoft Surface Type Cover Mouse' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='045e', product='09c0')
INFO: gui.device: New device 'Virtual core XTEST pointer' (GDK_SOURCE_MOUSE, axes:2, class=X11DeviceXI2, vendor=None, product=None)
INFO: gui.document: Initialized background from u'/tmp/demo-lhMRtX/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'
INFO: gui.brushmanager: Switching default pigment setting to On
INFO: gui.compatibility: Setting default layer type to Pigment
WARNING: gui.brusheditor: Setting 'softness' should be added to a group

```

Thanks for taking a look into it :D

**Comment by ChengduLittleA** [comment]
Update: After some fiddling, I managed to get the UI to show correctly:

- If you open brush settings editor from right click on a brush icon, the sliders won't show up.
- If then you open brush settings editor from the drop down menu, the sliders **will** show up.
- If then you again try to open it from right click on the icon, the UI will behave normally.

I'm trying to look at the code to see if there's anything I can do to fix this behaviour :D

**Comment by jplloyd** [comment]
Thanks for the report, and for finding the fix!

This regression was caused by the introduction of a custom slider that allows keyboard input (double click the sliders to switch to numeric input mode). The new widget is actually a container, swapping out a slider with a spinbutton, hence (I think) the need for the recursive `show_all` instead of just `show`.
