### ISSUE TITLE
There's an "X" showing every time I paint a stroke in My Paint 

### ISSUE THREAD

**Issue by Inkelly** [mypaint/mypaint#1140]
I've been using My Paint recently and I really like it, however I keep having this issue where the brush keeps showing this "X" Icon whenever I'm painting, it can be very annoying and distracting when rendering. I've already tried reinstalling but it was no use. 
could anyone help me out with this? 
https://imgur.com/0hGCGrD

**Comment by jplloyd** [comment]
You accidentally activated one of the feedback settings.

In the main menu, go to:

`View -> Feedback -> Show Last Painting Position`

and turn it off.

**Comment by Inkelly** [comment]
> You accidentally activated one of the feedback settings.
> 
> In the main menu, go to:
> 
> `View -> Feedback -> Show Last Painting Position`
> 
> and turn it off.

It worked! Thanks a lot!
