### ISSUE TITLE
Some icon in the toolbar doesn't appear

### ISSUE THREAD

**Issue by jhongiv** [mypaint/mypaint#1143]
MyPaint version: 2.0.0+gitexport.af5225a
Operating system: Xubuntu 20.04
Desktop environment: XFCE

Some icon in the toolbar doesn't appear. 
- Edit Frame
- Pan View
- Flip View Left
- Switch Between Fitted
- Dockable Panel (Managing Layers)
- Dockable Panel (Navigation Canvas)
- 
![mypaint_tools_icons](https://user-images.githubusercontent.com/64324578/110778202-55092280-8262-11eb-9051-e94bbb55b877.png)

**Comment by jplloyd** [comment]
See this comment for a summary of duplicates: https://github.com/mypaint/mypaint/issues/1111#issuecomment-691526927

A workaround was provided here: https://github.com/mypaint/mypaint/issues/1064#issuecomment-632988335
