### ISSUE TITLE
no libmypaint-2.0 on MINGW2 ?

### ISSUE THREAD

**Issue by pydemo** [mypaint/mypaint#1149]
$ pacman -S mingw-w64-x86_64-libmypaint
warning: mingw-w64-x86_64-libmypaint-1.5.1-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-libmypaint-1.5.1-3

**Comment by AesaraB** [comment]
This is a discussion to be had with the package maintainers for Arch Linux

**Comment by odysseywestra** [comment]
1.6.1-3 is available via MSYS2 Package search which matches the releases in libmypaint. libmypaint uses a different versioning than mypaint itself. Transfering issue and then closing it.
