### ISSUE TITLE
Map tablet to the MyPaint window

### ISSUE THREAD

**Issue by aadcg** [mypaint/mypaint#1171]
Thank you for this amazing tool.

I'm wondering if it's possible to map the tablet to the window as opposed to the whole screen.

**Comment by ChengduLittleA** [comment]
I don't think you can do it directly, but I think you may be able to write a script to get the active window's dimension and then use that coordinate to call `xsetwacom` if you are on linux.

**Comment by aadcg** [comment]
ChengduLittleA ***@***.***> writes:

> I don't think you can do it directly, but I think you may be able to
> write a script to get the active window's dimension and then use that
> coordinate to call xsetwacom if you are on linux.

I wasn't aware of xsetwacom.  That does it for me, thanks.
