### ISSUE TITLE
Latest MSYS2 GTK3 version breaks wacom intuos 3 tablet in mypaint v2.0.1

### ISSUE THREAD

**Issue by kvnvallis** [mypaint/mypaint#1173]
#### Description of the problem

I used the info in [this thread](https://github.com/mypaint/mypaint/issues/717) to diagnose a new graphic tablet bug in the latest gtk3 version from msys2 repos. When compiling mypaint v2.0.1 on windows 10 with the following gtk3 version, my graphics tablet was not detected correctly (no pressure sensitivity, buttons don't work).

- mingw-w64-x86_64-gtk3 3.24.31

I recompiled with the gtk3 version found in the mypaint stable release for windows, and my pen tablet worked right away.

    $ pacman -U mingw-w64-x86_64-gtk3-3.24.20-3-any.pkg.tar.zst
    $ python setup.py clean --all
    $ python setup.py demo

I also tried testing the master branch and v2.1.0-alpha, but neither of those would compile.

#### Basic system details

MyPaint version: v2.0.1
Operating system: Windows 10
Tablet Model: Wacom Intuos 3 4x6

#### Steps to reproduce

To reproduce the bug, just open msys2 and install the latest gtk3 package, then compile mypaint v2.0.1

Alternatively, to test the working version you'll need to download the old gtk3 from <http://repo.msys2.org/mingw/mingw64/>. I attached the file as a zip in case it gets taken down.

- [mingw-w64-x86_64-gtk3-3.24.20-3.zip](https://github.com/mypaint/mypaint/files/7896190/mingw-w64-x86_64-gtk3-3.24.20-3.zip)

Then open msys2, uninstall gtk3 recursively to avoid conflicts, and install the old version.

    $ pacman -Rs mingw-w64-x86_64-gtk3
    $ pacman -U mingw-w64-x86_64-gtk3-3.24.20-3-any.pkg.tar.zst

**Comment by AesaraB** [comment]
[Added to compatibility table](https://github.com/mypaint/mypaint/wiki/Device-support-table)
