### ISSUE TITLE
Stylus mouse button 2: not working with HUION H1060P on windows

### ISSUE THREAD

**Issue by r4ulill0** [mypaint/mypaint#1176]
#### Description of the problem

I have the right click mapped in one button on the stylus, the other one is for the eraser. The eraser button works without a problem but the right click doesn't. It works normally with the mouse and I've checked that it works in other software (Krita and Concepts).

I've tried to disable windows ink because it's known to generate problems but it didn't make a difference.

#### Basic system details

MyPaint version: 2.0.1+git.478280f2
Operating system: Windows 10

#### Steps to reproduce

1. Start MyPaint
2. Pressing the stylus button used as right click

#### Backtraces or error messages

There weren't any errors in the debug console so maybe the log has some clue about the issue:

```
Running python3.exe...
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix 'C:/Program Files/mypaint-w64/mingw64'
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: Windows: LANG='en_US.utf-8'
INFO: lib.i18n: Windows: LANGUAGE='es_ES'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'es_ES'
WARNING: C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/gettext_setup.py: No bindtextdomain builtins found in module 'locale'.
INFO: C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/gettext_setup.py: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/gettext_setup.py: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
INFO: gui.compatibility: Setting mode to 2.x (standard)
INFO: gui.compatibility: Setting default layer type to Pigment
INFO: gui.device: New device 'System Aggregated Pointer' (GDK_SOURCE_MOUSE, axes:2, class=GdkDeviceWin32, vendor=None, product=None)
INFO: gui.document: Initialized background from 'C:/Program Files/mypaint-w64/mingw64/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'
INFO: gui.brushmanager: Switching default pigment setting to On
INFO: lib.document: load_ora: 'C:/Users/king_/AppData/Local/mypaint/scratchpads/autosave.ora'
INFO: lib.document: 0.069s load_ora total
INFO: gui.filehandling: Loaded scratchpad from 'C:/Users/king_/AppData/Local/mypaint/scratchpads/autosave.ora'
INFO: gui.compatibility: Setting default layer type to Pigment
INFO: gui.device: New device 'HUION Tablet Pressure Stylus' (GDK_SOURCE_PEN, axes:5, class=GdkDeviceWintab, vendor=None, product=None)
```
I have found some insight checking the help>debug input device window. The event on the button mapped to E works fine and triggers this kind of events:

```
642171       KEY_PRESS state=0x0000 keyval=101 hw_keycode=69 [drawWindow]
642375     KEY_RELEASE state=0x0000 keyval=101 hw_keycode=69 [drawWindow]
643281       KEY_PRESS state=0x0000 keyval=101 hw_keycode=69 [drawWindow]
643468     KEY_RELEASE state=0x0000 keyval=101 hw_keycode=69 [drawWindow]
647812       KEY_PRESS state=0x0000 keyval=101 hw_keycode=69 [drawWindow]
647984     KEY_RELEASE state=0x0000 keyval=101 hw_keycode=69 [drawWindow]
```
But the right click of the stylus button doesn´t even appears there as registered.

I could try to look more in depth if someone provide me more instructions as this is all I could find

**Comment by MitchesD** [comment]
I think I have the same problem with my XP Pen Deco Pro M. 

My right click button is binded to move view, but it does not work. Also, when pressing while debugging it does not appear in event log as well.

I am using My Paint 2.0.1 stable release also on Windows 10. I have tried my pen on MyPaint on Ubuntu 20.04, where it worked as intended, so I think it is only windows related issue.

**Comment by TaviBird** [comment]
I have encountered the same issue on my Gaomon PD1161

**Comment by AesaraB** [comment]
Consolidated to #1220
