### ISSUE TITLE
Weird pen lag double click nonsense

### ISSUE THREAD

**Issue by TheDJTC** [mypaint/mypaint#118]
I tried mypaint just now and I couldn't use it with my bamboo. I try to select a color, and it wouldn't register, I had to hold it for a second to work, and it only sometimes works.

When I tried to sketch it kept skipping beats and I couldn't even do a cirlce. If I never lift up the pen it works fine enough, but otherwise it glitches.

I use a relatively new bamboo and have never had this problem before on any other art program, so I assume it's the program's problem.

**Comment by achadwick** [comment]
Closing in favour of chasing these Windows/Wintab bugs using an MSYS2 build of 1.1.1-alpha (and beyond). See #177, #178.
