### ISSUE TITLE
Python 3.10 incompatibility likely

### ISSUE THREAD

**Issue by eeickmeyer** [mypaint/mypaint#1182]
#### Description of the problem

Hi there! Leader of Ubuntu Studio here, which preinstalls MyPaint. Unfortunately, I have discovered that MyPaint crashes upon launch, likely a compatibility issue with Python 3.10 in Ubuntu Jammy Jellyfish (future 22.04 LTS). As such, unless this issue is fixed, I may have to remove MyPaint from Ubuntu Studio again.

#### Basic system details

MyPaint version: [✍ 1.2.0 stable, 1.2.1-beta.1, git revision NNNNNNN, …]
Operating system: Ubuntu 22.04 LTS Beta Jammy Jellyfish
Desktop environment: [✍ GNOME, Xfce, …]

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. MyPaint crashes upon launch.

#### Backtraces or error messages

```
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 293, in <module>
    = get_paths()
  File "/usr/bin/mypaint", line 241, in get_paths
    from lib import fileutils
  File "/usr/lib/mypaint/lib/fileutils.py", line 25, in <module>
    import lib.helpers
  File "/usr/lib/mypaint/lib/helpers.py", line 25, in <module>
    from . import mypaintlib
  File "/usr/lib/mypaint/lib/mypaintlib.py", line 13, in <module>
    from . import _mypaintlib
ImportError: cannot import name '_mypaintlib' from 'lib' (/usr/lib/mypaint/lib/__init__.py)
```

#### More Info

Reported at https://launchpad.net/bugs/1967163

**Comment by ncmprhnsbl** [comment]
no problem here(arch) with mypaint-2.0.1, libmypaint-1.6.1 and python-3.10.4

**Comment by eeickmeyer** [comment]
We're trying a no-change rebuild to see if that fixes the issue. At the moment we're in beta freeze, so I won't know for a couple more days.

**Comment by odysseywestra** [comment]
Yeah MyPaint 2.0.1 requires libmypaint 1.6.0 or later. APT is installing version 1.5-1 so this may be an upstream issue with how Ubuntu is building the packages.

**Comment by odysseywestra** [comment]
Scratch that. I read that wrong Ubuntu is technically shipping version 1.6.0. My question would be why is Ubuntu shipping two separate packages related to libmypaint? This is what I see in the dependency.txt list.

libmypaint-1.5-1 1.6.0-2
libmypaint-common 1.6.0-2

BTW I did install the latest image of ubuntu 22.04 and did reproduce the issue. I'll try to manually build it and see if its a dependency issue or not.

**Comment by odysseywestra** [comment]
Okay I did mange to build from source and install it in ubuntu and cannot reproduce the issue in 2.0.1 release or master branch. So its might be still pointing towards a packaging issue upstream.

**Comment by eeickmeyer** [comment]
Good to read you, @odysseywestra ! Long time no see!

As for your evaluation, it's not so much a packaging issue as it is the package wasn't built against Python 3.10. Hence, there is a current no-change rebuild of the package waiting in the queue for the beta freeze to thaw. At that point, it'll be let through the queue and start building.

So, this is work-in-progress, and we're doing what we can. :)

**Comment by eeickmeyer** [comment]
Good news! The rebuild fixed this issue, I'm closing. Sorry for the noise!

**Comment by odysseywestra** [comment]
Ahh no problem. That's what alpha and betas of distros are for. If it wasn't caught and fixed it would have been a bigger issue when the LTS released.
