### ISSUE TITLE
Having issues enabling pressure sensitivity in MyPaint on Surface Studio

### ISSUE THREAD

**Issue by BlueRascal** [mypaint/mypaint#1189]
Been having issues with trying to figure out how to get the pressure sensitivity to work on my Surface Studio laptop and had the same issues with the previous laptop I had, which was a Surface Pro 4. How do I enable it for the laptop with the Surface Pen.

**Comment by ghaspias** [comment]
I also have this issue, and it seems that it happens due to the use of the old WinTab API (Krita has an option to choose the API to use, choosing the new Windows Ink API fixes the issue in Krita)

**Comment by AesaraB** [comment]
[Added to compatibility table](https://github.com/mypaint/mypaint/wiki/Device-support-table)

**Comment by AesaraB** [comment]
> I also have this issue, and it seems that it happens due to the use of the old WinTab API (Krita has an option to choose the API to use, choosing the new Windows Ink API fixes the issue in Krita)

Referring to #1150

**Comment by BlueRascal** [comment]
How do you choose the new Windows Ink API function in MyPaint?
