### ISSUE TITLE
Brushes don't work at all - can't select brush option

### ISSUE THREAD

**Issue by error-404-** [mypaint/mypaint#119]
For some reason, when I use my tablet pen, instead of registering the click as something it should be painting with, the program decides I must want a box with all my recently used colors in it.  I can't draw anything because it refuses to select a brush.  I should note that this doesn't happen when I use my mouse trackpad, but of course, no pressure sensitivity.  What is squirrely with my tablet?  I thought this program was designed to be used with tablets?  And before anyone asks, yes I updated to the most recent tablet driver, yes I restarted my computer, etc.  I have Windows 8.1 (not that I ever wanted it - Windows 8 forced it on me without ever giving me a chance to stop it) and it fucked up all my drivers for just about everything, but seeing as I managed to get back pressure sensitivity for my tablet in Photoshop CS5, I figured my other paint programs would be fine, too.  Yeah, no.

**Comment by achadwick** [comment]
**Triage note:** very stale bug, unsupported version (1.0.0, we're working on 1.2 now), needs steps to reproduce against master.

Let's give this one 28 days to live and then close it if none of the requested information is forthcoming.

**Comment by achadwick** [comment]
Closed due to lack of response. We have newer binary releases now: <https://github.com/mypaint/mypaint/releases>. Please open an issue against something newer than 1.0.0 if this is still happening (which it might be: check out #380 )
