### ISSUE TITLE
MyPaint 2.0.1 does not see Intuos4 tablet

### ISSUE THREAD

**Issue by theres1** [mypaint/mypaint#1203]
System Details:
Windows 7
mypaint-w64-2.0.1
Wacom Intuos 4

Pressure is not working, the tablet is not listed in the device list in the preferences.

MyPaint 1.2.1 works correctly.

**Comment by AesaraB** [comment]
[Added to compatibility table](https://github.com/mypaint/mypaint/wiki/Device-support-table)
