### ISSUE TITLE
Building: Rely on Python virtual environment instead of system python environment

### ISSUE THREAD

**Issue by AesaraB** [mypaint/mypaint#1224]
### Point of concern

In order to build MyPant, there will likely always be a requirement to make changes to the system/user environment through the installation of packages. All the same we want to reduce the number of moving parts, both in the OS, and in MyPaint's environment.

### Suggested improvements

System python installations may be full of extraneous packages, use Python venv in the documentation instead.

Here's an [example of a project](https://beancount.github.io/fava/development.html) that uses Python's virtual environment capabilities in the documentation

**Comment by jtojnar** [comment]
`venv`+`pip` are still full of moving parts, you just move where the stuff is moving. If you want more predicability, you will need something like [Poetry](https://python-poetry.org/).

But since we only depend on four Python libraries:

- pycairo
- pygobject3
- numpy
- setuptools

and the first half will need other libraries installed through the system package manager, installing the Python dependencies through non-system means would increase the amount of moving parts, not decrease it.

**Comment by AesaraB** [comment]
I agree with your comment, after I first started trying to test venv+pip I quickly came across these issues. Since then, I hadn't really known what to do with this issue.

In practice making the build environment portable is unnecessary. These days developers wanting that should containerise their building and testing workflow (which is easier than ever with tools like distrobox).

And, if we want more reproducible build environments, it's easier to just use NixOS in a container to do this.

A more productive use of time than addressing this issue is to remove the [tech debt from our building and testing system](1229).

I'm the one who opened this issue, and I see no need for it to remain open with the added context provided by your comment, as well as what I just stated in mine.

**Comment by jtojnar** [comment]
> And, if we want more reproducible build environments, it's easier to just use NixOS in a container to do this.

If you want to go the Nix way, you do not even need containers – Nix will run on any Linux distro and MacOS.

It can be used for building [very light Docker images](https://nix.dev/tutorials/nixos/building-and-running-docker-images), [Appimages](https://mediocregopher.com/posts/building-appimages-with-nix), [Snaps](https://nixos.org/manual/nixpkgs/stable/#ssec-pkgs-snapTools-build-a-snap-firefox). Or just for quickly getting some of thousands of tools [that Nixpkgs provides out of the box](https://search.nixos.org/packages). 

Nixpkgs even supports cross-compilation to mingw2, if we want to target Windows but it currently does not have all the patches necessary to build GTK (and its dependencies) like msys2 has, so separate msys2 toolchain will still be needed, at least for now.

There is quite a lot to learn if you decide to go the Nix way. But both [Nix](https://nix.dev/contributing/how-to-get-help) and [Meson](https://mesonbuild.com/#community) have quite active and helpful community. I can help withe either too, if needed.

**Comment by AesaraB** [comment]
I appreciate your offer for help, no doubt I'll have some questions for these softwares as I learn more about them.

I think Nix is a wonder of technology as it stands, but my focus is on the application itself. I *am* competent in system administration, but I'm grateful that @odysseywestra is here to focus on that side of the project.
