### ISSUE TITLE
Discussion: Add CLA for MyPaint

### ISSUE THREAD

**Issue by AesaraB** [mypaint/mypaint#1230]
### Documentation issue

The project has a page on how code should be licensed, but ideally we want something more formal.

### MyPaint version

N/A

### Code of Conduct

- [X] I acknowledge that my conduct contributes to shaping the community.

**Comment by AesaraB** [comment]
[Apache CLA for reference](https://apache.org/licenses/contributor-agreements.html)

**Comment by QuLogic** [comment]
Are you sure you want a CLA? That could scare people off.

**Comment by QuLogic** [comment]
Contributions to code that is GPL must be under a license that is compatible with the GPL; this _could_ be something like MIT, though people generally assume contributions are under the same license as the project. There is absolutely not a copyright waiver in the GPL; all contributors retain their copyright.

**Comment by AesaraB** [comment]
Nice catch, that's my bad. I'm not a lawyer, but could that fall under a technicality? I.e., while the contributor's code could potentially be licensed as MIT or another compatible permissive license, as distributed in this repo it will automatically be distributed as GPLv2+.

An issue may be that one could implicitly license the code restrictively in a way that can't be converted bidirectionally (e.g. can you distribute GPLv3 code as GPLv2?).

I'm [drafting the licenses page](https://aesarab.github.io/mypaint-website/design/contributing/licensing), which is why I'm thinking about how licensing should work moving forward.

**Comment by odysseywestra** [comment]
I'm not interested in MyPaint having a CLA. We don't have the numbers to warrant that kind of commitment and CLA always tends to have a bad taste in the contributor's mouth. We only have the CoC to make sure no person is decimated from contributing code to MyPaint and steps to keep it that way if the need arises. If they have questions about licensing, what you are doing with documentation will be enough for now. 

With that said, I'm going to close the Issue regarding the CLA since it is not necessary for us to have it.

**Comment by AesaraB** [comment]
I don't think that's a conclusive enough answer to the discussion.

Each cycle of MyPaint's development has been led by a handful of people, sure. But, the licensing page in the documentation is informational at best and does not signify any contributor's understanding or will to follow MyPaint's licensing structure.

The discussion posed here is more of a "how should we help contributors understand how they're licensing code?" than a "how do we get contributors to sign a legal document?". Should our gold standard for both contributors and project members really be "trust me bro"?
