### ISSUE TITLE
Saving issues in Windows 7 ["TypeError: coercing to Unicode: need string or buffer, NoneType found" when thumbnailing]

### ISSUE THREAD

**Issue by springvanillarose** [mypaint/mypaint#125]
A friend of mine who I introduced MyPaint to cannot save her files unless it in .jpg on her Windows 7 machine. She is currently using the latest version as well. Could anybody help with this? Thank you in advance.

**Comment by achadwick** [comment]
The traceback from @crispysnore in #277 indicates that this issue in old versions of MyPaint has nothing to do with non-Unicode characters in paths (something I should've realized myself, actually: "why is the thing None?")

(Still nobody has reported any version numbers, but the reporters' version is 1.0 on Windows I think)

I don't know what's happening here, but for now at least (I hope!) the workaround is to upgrade to a 1.1.1-alpha build. I simply don't have the time to diagnose faults in old versions, so can someone affected by this bug please try something newer and let us know if it's fixed or not?

**Comment by springvanillarose** [comment]
My friend was using the 1.0 version of MyPaint on Windows 7. She says the issue has been resolved and no more bugs are are happening. Thank you very much.

**Comment by achadwick** [comment]
Awesome - thanks for confirming!
