### ISSUE TITLE
mypaint-git fails to build in AUR package

### ISSUE THREAD

**Issue by charbelnicolas** [mypaint/mypaint#1264]
### Description of bug

I don't know if this is an AUR packaging failure or if mypaint is to blame but I get the following error when building:

```==> Starting prepare()...
patching file gui/brushmodifier.py
Hunk #1 FAILED at 96.
1 out of 1 hunk FAILED -- saving rejects to file gui/brushmodifier.py.rej
patching file gui/document.py
Hunk #1 succeeded at 366 with fuzz 2 (offset 12 lines).
Hunk #2 succeeded at 1726 with fuzz 2 (offset 35 lines).
patching file gui/menu.xml
patching file gui/resources.xml
patching file gui/userconfig.py
Hunk #1 FAILED at 91.
1 out of 1 hunk FAILED -- saving rejects to file gui/userconfig.py.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'mypaint-git-2.0.0.main.r6208.8187b1e2-1': 
error: packages failed to build: mypaint-git-2.0.0.main.r6208.8187b1e2-1```

### Steps to reproduce

1. Try to install from Arch Linux's User Repository `paru -S my-paint-git`

### Backtraces or error messages

```shell
==> Starting prepare()...
patching file gui/brushmodifier.py
Hunk #1 FAILED at 96.
1 out of 1 hunk FAILED -- saving rejects to file gui/brushmodifier.py.rej
patching file gui/document.py
Hunk #1 succeeded at 366 with fuzz 2 (offset 12 lines).
Hunk #2 succeeded at 1726 with fuzz 2 (offset 35 lines).
patching file gui/menu.xml
patching file gui/resources.xml
patching file gui/userconfig.py
Hunk #1 FAILED at 91.
1 out of 1 hunk FAILED -- saving rejects to file gui/userconfig.py.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'mypaint-git-2.0.0.main.r6208.8187b1e2-1': 
error: packages failed to build: mypaint-git-2.0.0.main.r6208.8187b1e2-1
```

### MyPaint version

mypaint-git

### Operating System(s)

Arch Linux

### Desktop Environment (Linux)

Labwc (wayland)

### Code of Conduct

- [X] I acknowledge that my conduct contributes to shaping the community.

**Comment by charbelnicolas** [comment]
![ss_2024_09_11_18_32_49](https://github.com/user-attachments/assets/78730f3d-5bf6-4df0-9d3c-fda3868e899e)

**Comment by AesaraB** [comment]
Looks like the packaging patches applied aren't playing nicely, but since @odysseywestra is in charge of that package he might know what to do

**Comment by AesaraB** [comment]
The error might be caused by the formatting differences since #1257

**Comment by odysseywestra** [comment]
Try disabling the patch in the PKGBUILD build file and see if it builds.

**Comment by charbelnicolas** [comment]
> Try disabling the patch in the PKGBUILD build file and see if it builds.

Alright, I'll try that and see if it builds, thank you.

**Comment by charbelnicolas** [comment]
I commented out the patch and it worked! Thanks a lot!

**Comment by odysseywestra** [comment]
Updated upstream PKGBUILD. I will need to rewrite all three AUR packages when we transition to Meson. Closed.
