### ISSUE TITLE
Can't build mypaint-git from AUR: "==> ERROR: One or more files did not pass the validity check!"

### ISSUE THREAD

**Issue by charbelnicolas** [mypaint/mypaint#1270]
### Description of bug

```
==> Validating source files with sha256sums...
    mypaint ... Skipped
    mypaint-git.install ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'mypaint-git-2.0.0.main.r6214.ad795c76-1': 
error: packages failed to build: mypaint-git-2.0.0.main.r6214.ad795c76-1
```

### Steps to reproduce

1.  sudo pacman -S mypaint-git

### Backtraces or error messages

```shell
fetching devel info...
==> Making package: mypaint-git 2.0.0.main.r6214.ad795c76-1 (Tue 22 Oct 2024 07:13:38 PM EST)
==> Retrieving sources...
  -> Cloning mypaint git repo...
Cloning into bare repository '/home/charbel/.cache/paru/clone/mypaint-git/mypaint'...
remote: Enumerating objects: 40491, done.
remote: Counting objects: 100% (2597/2597), done.
remote: Compressing objects: 100% (683/683), done.
remote: Total 40491 (delta 1973), reused 2392 (delta 1900), pack-reused 37894 (from 1)
Receiving objects: 100% (40491/40491), 104.40 MiB | 1.33 MiB/s, done.
Resolving deltas: 100% (29669/29669), done.
  -> Found mypaint-git.install
==> Validating source files with sha256sums...
    mypaint ... Skipped
    mypaint-git.install ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'mypaint-git-2.0.0.main.r6214.ad795c76-1': 
error: packages failed to build: mypaint-git-2.0.0.main.r6214.ad795c76-1
```

### MyPaint version

mypaint-git

### Operating System(s)

Arch Linux

### Desktop Environment (Linux)

LABWC

### Code of Conduct

- [X] I acknowledge that my conduct contributes to shaping the community.

**Comment by jtojnar** [comment]
This looks like an issue with the the AUR package. Please report it on https://aur.archlinux.org/packages/mypaint-git

**Comment by charbelnicolas** [comment]
There is no way to report a bug on the actual package on the AUR, or at least I could not find it. Simple comments on the package get ignored. I was actually trying to build bug it to report another bug but this time I didn't even get to the build step.

**Comment by charbelnicolas** [comment]
> Jan is correct here, while we did help you out for a packaging issue the last time, that was only because one of our maintainers is also a packager for ArchLinux. It's bad form to facilitate downstream packaging issues on the upstream tracker, so we can't keep facilitating what happened last time.
> 
> Reporting bugs: https://wiki.archlinux.org/title/Bug_reporting_guidelines#Opening_a_bug Have a go at fixing the bug yourself: https://wiki.archlinux.org/title/DeveloperWiki:How_to_be_a_packager

Bug reporting on gitlab is not for AUR packages :(
