### ISSUE TITLE
Add an inking tool (replace Bézier curves in "Lines and Curves")

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#13]
I want to add an inking tool beyond 1.2 to replace the Bézier curve drawing aspects of the "Lines and Curves" tool. Code exists in [gui/linemode.py](https://github.com/mypaint/mypaint/blob/fc4fafadb41fba752dc6a656b7e899f68c9aedf1/gui/linemode.py) for drawing and interpolating arbitrary smooth shapes with Catmull-Rom cubics, so it's just a "small matter" of creating a great UI for it. Rough bullet-point workflow:

* User clicks on an "ink" tool
* User draws a squiggle,
  - while drawing, present the curve differently
  - perhaps drop in the initial control points as we go
  - program captures the shape while rendering it (pressure, tilt, position) as control points
* User stops drawing the squiggle
  - program allows control points to be moved around, curve will update
  - drag far away from the curve to delete a point (= smooth here)
  - click on the curve to add a new point (= new wiggles here)
* UI should allow user to click away from from the curve being edited to start creating a new one

Graphical options for the tool would cover density of initial control points. I envisage no more than one point per 20 to 25 screen pixels while doing the initial capture pass.

Use cases: basically anybody making comics or manga-style images.

Drawbacks: strokes are still strokes, and cannot be edited once a new one is created. Even if the tool does create special "spline edit" actions, users will not be able to save the document, reload it, and edit arbitrary stroke shapes as first-class objects. There may be scope later on for special layer types which revisit this.

*Very* much post-1.2.

**Comment by achadwick** [comment]
I've added an inking tool - 

![inking tool](https://cloud.githubusercontent.com/assets/61299/6404447/0ad9f77e-be10-11e4-8db1-0751d7ae89e0.png)

please test and let me know how it goes on!

**Comment by mikshaw** [comment]
That....is.....

CRAZY!

This is really fun, and i don't think i've seen anything quite like it before. You can use it with texture brushes too, and moving the control points around doesn't blur or smudge the texture.  Very clever tool andrew =o)

**Comment by achadwick** [comment]
Fallout issue the first: evdev pressure dropouts again! #223 :sigh:

Keep the testing coming, and please report new issues for each thing you see. Suggestions welcome via the issue system as well, if you have mockups or code! I kinda want to make the capture interval configurable in the options panel, and allow users to tweak the pressures and tilts that get captured on each point.

Early days yet. All testing and feedback welcome!

**Comment by AtsusaKaneytza** [comment]
Is this up for testing in a Windows version yet?

**Comment by Cloudef** [comment]
This is very awesome.
