### ISSUE TITLE
"Ctrl+Z" and "Delete" keyboard buttons don't always work on the canvas?

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#131]
I'm using MyPaint 1.1.0 (32-bit) on Windows 8.1 64-bit
I'm not really sure if this is easily reproducable, but I'll try...

"Ctrl+Z" is my shortcut for Undo, and "Delete" is my shortcut for "Clear." After painting strokes for a while, sometimes those shortcuts don't register or work. To get the shortcuts to work again, I have to either: minimize the window and maximize it again; or click on a subwindow, then click on the canvas again before using the desired shortcut (I think) It's possible that this happens with other shortcuts that affect the strokes on the canvas, but I'm not entirely sure.

**Comment by achadwick** [comment]
@AtsusaKaneytza is this a duplicate of #190 by any chance? Right now this looks fairly impossible to reproduce, but maybe looking at your updates there there's a chance.

Please let us know.

**Comment by achadwick** [comment]
@AtsusaKaneytza Is this still happening with the recent beta releases? If it is, I still need a recipe for seeing it for myself. Thanks in advance...

https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.0

**Comment by achadwick** [comment]
@AtsusaKaneytza Can you let me know whether this is still happening in recent beta releases please?

--------------------

**Triage note** stale, needs steps to reproduce, no response from reporter or anyone else. If no confirmation, let's close this one 7 days from now.

**Comment by AtsusaKaneytza** [comment]
Hasn't been a problem in new releases.

**Comment by achadwick** [comment]
Thanks for the confirmation.
