### ISSUE TITLE
Clicks on MyPaint dialog windows don't register

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#132]
Using MyPaint 1.1.0 32-bit on Windows 8.1 64-bit

When MyPaint has a popup dialog (like "Change Brush Settings" or "Import Brush Group") sometimes clicks won't register on the windows (happens to subwindows too, when trying to click on a subwindow's tab)
or the clicks will register on the Main MyPaint window as if the dialog windows aren't there. Minimizing and maximizing the Main Window fixes this.

**Comment by achadwick** [comment]
@AtsusaKaneytza Is this still happening with the 1.2.0 betas?

**Comment by achadwick** [comment]
No feedback from the reporting user, but I can kinda reproduce this with mypaint v1.2.0-beta.2 and WacomTablet drivers 6.3.14-1, on real hardware under Win7.

1. Make sure you have the tablet driver installed.
2. Start MyPaint in fullscreen mode.
3. Draw something, and let the stroke complete rendering.
4. Press the V key to bring up the palette.
5. **Speedily**, tap a colour chip with the paint nib.
6. Attempt to draw.
7. Repeat steps 4 to 6 until it happens!

When it happens, the stylus can't be used for panning the canvas with btn2 (or whatever it is on Windows), and you can't draw. Pressing the V key again seems to unfreeze things.

**Comment by achadwick** [comment]
It seems to be heavily timing-related. You need to be quick on the tap to reproduce this one.

Additionally, pressing the C/V/B keys should commit pending brushwork, and that doesn't seem to be happening. I'm noticing that it almost seems to consider the mouse button to be pressed down while the floating dialog is active, which can result in smears when the dialog goes away and normal motions on the canvas resume.

**Comment by achadwick** [comment]
Sorry for the accidental comments here. I've moved the, to the correct issue.

**Comment by achadwick** [comment]
Stale old bug, closing. Please test with 1.2.0 or later and report this as a new bug if it's still happening.
