### ISSUE TITLE
Brush group dock-panels: add group switcher UI, rework group options dialog

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#138]
Split out from #106. @AtsusaKaneytza requested:

I noticed that some useful features in MyPaint 1.0 aren't in the Windows version of MyPaint 1.1.

[...]

-The brush groups tab seems to have "downgraded" to menu-like tabs and subwindows, in my (opinion) Instead of being one efficient and accessible subwindow (the Brush List Editor) that you can drag varying brushes to.
![brushgroup-prev-conceptdesign_ramon](https://cloud.githubusercontent.com/assets/8382492/4354781/ef57406e-4241-11e4-891d-50dc14787c14.jpg)

[...]

**Comment by achadwick** [comment]
Vaguely related issue: #260. That bug is almost a proposal to make brush group panels *searchable* or filterable by some user-defined characteristic.

**Comment by achadwick** [comment]
Best get this one looked at.

**WONTFIX** on "reinstate 1.0-era single-window Brush List Editor". Sorry if that's what you wanted, but the "tag list" thing was technically awful (full disclosure: I've worked on it) as well as (IMO) aesthetically nasty.

------------------------------

Now let's turn this into something positive :smiley: 

----------------------------

@iirelu 

> We should definitely figure out some way to balance the ease of navigation of 1.1.0 and the ability to have multiple brush windows open at once of the current `master` branch.
> 
> Hm, how about giving each brush panel the ability to swap to any other brush set? It could take over this (really user-hostile and counter-intuitive) settings window:
![blender](https://cloud.githubusercontent.com/assets/3432543/5152240/e1e117a6-71e5-11e4-8391-e4c9924a9cbd.png)

This. I think this is the most concrete and implementable proposal falling out of this issue. Quoting it here again, and retitling/retagging the issue. I think the pictured dialog is so awful it merits a bug flag.

What we need for this:

* Workspace guts: add the ability for those wrench icons to drop down menus for the current panel (let panels expose config menus in a simple way?)
* Maybe change the button's icon from a wrench to an arrow when it's housing a menu?
* Expose the actions in that dialog as menu items instead
* Add switcher actions to the menu for any brushes panel
* Perhaps separate "Switch to Group..." and "Open Group..." submenus/sections?

**Comment by iirelu** [comment]
@achadwick Haha, changing that was a big part of my brush pack overhaul I've been planning. (It's on hold until 1.2 releases so hopefully I can find more useful things to do)

Let's close this issue for now and open a new one for this topic.
