### ISSUE TITLE
Make Floating Subwindows easier to drag around, like they were in the 1.0 era

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#140]
Split out from #106. @AtsusaKaneytza requested:

I noticed that some useful features in MyPaint 1.0 aren't in the Windows version of MyPaint 1.1.

[...]

-Floating Subwindows were easier to drag around in 1.0 than in 1.1. In 1.1 you have to grab the window by its tab and HOPE that it will end up in the same position you released your mouse-click at.

**Comment by achadwick** [comment]
@AtsusaKaneytza Is this still happening with the 1.1.1-alpha builds you've been trying of late? Windows seems to behave itself for me with those versions in Win7/64-bit with the documented build I use for testing stuff out.

**Comment by achadwick** [comment]
**Triage note:** Flagged as needing info, can't reproduce, non-development version. Needs steps to reproduce against locally-built current master (ideally) to get this back on track. If that doesn't happen, please close this issue report after 28 days of inactivity (but retest in Windows first!)

**Comment by AtsusaKaneytza** [comment]
(Sorry for the late feedback)
Seems to be fixed/resolved in the latest Windows version: 1.2.0-alpha.20150504+git.a80a54b from Tumagonx's blog. The windows drag more easily without lagging and don't crash the software.

**Comment by achadwick** [comment]
@AtsusaKaneytza Thanks for the feedback. Closing now.

If it reoccurs in one of the [latest betas][1], please report a new issue referring back to this one (using the `#140` notation). Thanks!

[1]: https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.0
