### ISSUE TITLE
Visibility and lock icons are moved to the right side of the layers subwindow

### ISSUE THREAD

**Issue by android272** [mypaint/mypaint#144]
I have been playing around with the testing branch for the past week and I was wondering. Why did the visibility and lock layers switch to the right side of the layers subwindow? every single art app I have ever seen with a layers subwindow have visibility and lock on the left. it really through me off to have it over there.

This is very frustrated when coming from any other art app on the market.  When mussel memory kicks in and go to the left of the layer to find that lock and visibility buttons are not there.  Please fix this.

**Comment by achadwick** [comment]
Let's take a look at this during the beta test cycle. It won't require any string changes, probably.

**Comment by achadwick** [comment]
Annoyingly, to do this properly is going to require some repacking of the TreeView's columns, for assorted finicky reasons relating to layout of the tree lines (which I love and we're keeping!). There are some layout bugs which cause icon columns to break in certain cases when they're nominated 

Repacking the columns requires string changes (columns have headers! hidden ones, but headers nonetheless), so this cannot be done in the beta cycle.

I'm not so sure I even like the flag icons on the left still. I prefer a balanced look. However when previews come along, I'll be revisiting the row layout anyway.

**Comment by achadwick** [comment]
On the other hand, the hover-enabled vertical scrollbars in GTK 3.16 are *hugely* annoying - they make almost impossible to click on the lock column when the number of rows exceeds the vertical space in the widget. Reassigning to the beta development phase. :angry:

**Comment by achadwick** [comment]
A flipped layout retaining near-identical column defs doesn't look too bad...

![flippedlayout](https://cloud.githubusercontent.com/assets/61299/9093288/20311146-3ba3-11e5-94ec-bf64b4458eb1.png)

**Comment by achadwick** [comment]
... and normally there's no need to click on those icons that are being hidden by the scrollbar. I guess that's the best compromise: if they were on the left, the panel would look pretty cluttered.
