### ISSUE TITLE
Layer dragging/dropping no longer working

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#148]
As of 10c7183254b128df7d9dfed6c3e1fef744fc4e08 and gir1.2-gtk-3.0 3.14.4-2 under Debian testing/unstable, dragging in the layers tree appears broken. Steps to reproduce:

1. Create a load of layers and/or layer groups,
2. Drag a layer between tow other layers without holding any modifier keys
3. Drop!

Expected: the layer moves to where you drop it. Reality: nothing happens.

Quickly inserting debugging prints into `gui/layers.py` for the tree drag protocol vfunc implementations shows that `do_row_drop_possible()` is behaving sensibly in the middle of the drag, but that `do_drag_data_received()` never gets called. Wtf?

This is fairly minor, since the buttons at the bottom of the panel allow layers to be bubbled up and down, and this allows a layer to go anywhere in the tree. However the statusbar now tells the user that things can be dropped, and that modifier drags are special thanks to #68 and 9630a96a964cfe8a66f868057333d5a4b46eb6c6, so if this can't be fixed for 1.2, the status bar message and dragging should be turned off.

**Comment by achadwick** [comment]
The code works fine in Ubuntu Trusty (14.04LTS, gtk=3.10.8), breaks in Ubuntu Utopic (14.10, 3.12.2), and is still broken with Debian testing (gtk=3.14.5). Our code has remained unchanged between the releases.

[Page showing versions of GTK3 in recent Ubuntu releases](http://packages.ubuntu.com/gir1.2-gtk-3.0)

**Comment by achadwick** [comment]
For my logging/investigation branch reffed above:

* Fail case with gtk-3.14.5: http://paste.debian.net/144712
* Success case with gtk-3.10.8: http://paste.debian.net/144714

**Comment by achadwick** [comment]
I'll report it upstream once the gnome bugzilla is back from its upgrade downtime...

**Comment by iirelu** [comment]
Sure love working with a giant toolkit with no regards for backwards compatibility or any semblance of stability.

Would it be possible to get around GTK's buggy as hell DnD by doing our own? As in, not bothering with the floating overlay display and just worrying about mouseup/mousedown moving the layer around.

**Comment by achadwick** [comment]
Reported upstream: https://bugzilla.gnome.org/show_bug.cgi?id=745388

**Comment by iirelu** [comment]
Woo, this is fixed finally! Thanks for getting it working.
