### ISSUE TITLE
We need new screenshots

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#149]
Currently, all the screenshots on our website are of very old versions. Once 1.2 is released, we should work on updating those.

I'm willing to commission a few artists, if need be.

**Comment by mikshaw** [comment]
Here's one...possibly a little grotesque for a showcase image, but i'll upload more in the future.
![a monstah](http://i.imgur.com/iaeCmtq.jpg)

**Comment by iirelu** [comment]
Haha yeah, probably something less grotesque. Does a good job showing off the various panels, though! Maybe making the window a little smaller so there's no blank space under the panels would be a good idea.

**Comment by crydalch** [comment]
Here's a little doodle! Feel free to use it (or not, either way). I don't think that screenshot above is grotesque, FWIW.

![screenshot-window-2015-02-18-214919](https://cloud.githubusercontent.com/assets/458856/6262465/7d292330-b7b8-11e4-9082-de128734db35.png)

Finally got around to building the latest code on Linux (can't wait till it works on SP3!), and my goodness, so many improvements since MyPaint 1.0/1.1 (which are the defaults in so many repos! 

Kudos!!!

**Comment by iirelu** [comment]
Keep them coming, any new screenshots we can use would help!

**Comment by crydalch** [comment]
![2015-02-19--1424388633_screenshot](https://cloud.githubusercontent.com/assets/458856/6278716/f99aecd8-b84d-11e4-9f97-bb3682655b81.png)

This one I built on Crunchbang/Debian Wheezy, which I don't recommend, as Wheezy's Gtk+ 3.4 is too old for preferences, it appears:

```python
GError: ./gui/preferenceswindow.glade: required gtk+ version 3.6, current version is 3.4
```

**Comment by iirelu** [comment]
Thanks! Still looks good, despite the GTK age.

**Comment by AtsusaKaneytza** [comment]
![image](https://cloud.githubusercontent.com/assets/8382492/6362917/71dd221c-bc57-11e4-8734-adeb5332aa52.png)

**Comment by iirelu** [comment]
Thank you!

**Comment by AtsusaKaneytza** [comment]
Here's another screenshot submission (better than the WIP up there, haha)
![image](https://cloud.githubusercontent.com/assets/8382492/6705001/55411758-cd1e-11e4-966d-7f838b16371d.png)

**Comment by mikshaw** [comment]
non-blobby something
![15-0330-223745-window](https://cloud.githubusercontent.com/assets/5081349/6911398/36e3b3a0-d72e-11e4-83d0-3e17e74a4d29.jpg)

**Comment by Griatch** [comment]
It has been some time since I contributed a screenshot to MyPaint ... so here are two, using Linux Mint KDE and the GIT version of MyPaint: 

![mypaint_screenshot_griatch_02](https://cloud.githubusercontent.com/assets/294267/7279226/a76acb06-e91a-11e4-8a31-611901863ef3.jpg)
![mypaint_screenshot_griatch_01](https://cloud.githubusercontent.com/assets/294267/7279227/a76ac688-e91a-11e4-81e2-bbfd8e775c06.jpg)

**Comment by Griatch** [comment]
And a third one for more variety:

![mypaint_screenshot_griatch_03](https://cloud.githubusercontent.com/assets/294267/7279367/c2a0c028-e91b-11e4-8363-a02c59638581.jpg)

**Comment by iirelu** [comment]
Thanks so much! Those are great screenshots.

**Comment by mikshaw** [comment]
I love the textures on that monster!

**Comment by Ico-dY** [comment]
I didn't see this topic! I'll post some work as soon as possible! ^^

**Comment by Ico-dY** [comment]
My screenshots: ^^

![screenshot_1280px_meeting_halfway](https://cloud.githubusercontent.com/assets/10749813/7464086/c08c78c4-f2bf-11e4-8d94-4ce8dcdeaf8f.jpg)
![screenshot_1280px_empty_blue](https://cloud.githubusercontent.com/assets/10749813/7464088/ccb52b5a-f2bf-11e4-8e12-c8cc450b539a.jpg)

**Comment by achadwick** [comment]
Woah. I've been neglecting this, and I shouldn't have been. Those screenshots look amazing!

I have to ask about licensing - are all of these available for us to repost under the terms we need for distribution on the mypaint.org website, and on third-party things like Debian's screenshot uploader or other things that end up in "app-store"-like (hehehe) installers (GNOME Software)?

Our policy is currently as expressed at
https://github.com/mypaint/mypaint/wiki/Licensing-policy#supplemental-artwork-or-promotional-material

Quick summary:
* We need to be able to repost these images to promote MyPaint (obviously)
* We need to be able to allow third parties to repost them as well, and allow others to do the same
  * ... **including commercially** (yikes!) (that's a Debian guideline thing ("no discrimination against fields of endeavour" covers commercial reuse))
* I'm totally cool with the license being share-alike, so you get to require tat you get credit all along the path
* It's best if the credit you require is part of the image itself - perhaps huge watermarks would be excessive, but remember that the images might be seen shrunk down quite small!

**Comment by AtsusaKaneytza** [comment]
Sounds fine for the screenshots I've provided

**Comment by Ico-dY** [comment]
It's fine for me too! I've just added the credit at the bottom of the screenshots. ^^

**Comment by iirelu** [comment]
I've been away from Mypaint for the most part lately but I'm still maintaining [Made With Mypaint](http://made-with-mypaint.tumblr.com/). Contacting good artists from that about having their artwork show off Mypaint officially might be a good idea.

**Comment by crydalch** [comment]
Done, I can't edit these images at the moment, and I'm not sure when I'll get to it, I hope that comment is enough!

Cheers!

**Comment by Griatch** [comment]
@achadwick 

I've been contributing screenshots to MyPaint and the website since version 0.5, I'm not about to stop now. So sure.

I can't edit the images at this point, just post them next to the credit when on the mypaint website; if people repost it elsewhere without the credit ... well it's not like it's the first time. 
.
Griatch

**Comment by odysseywestra** [comment]
Here are a couple more screenshots to add to the mix. I'm getting pretty excited for this release. ^^

![screenshot from 2015-07-16 02 42 08](https://cloud.githubusercontent.com/assets/1840562/8720135/b28edc2e-2b65-11e5-91ce-9d557bcd2c9e.png)

Plus one with an example of the Inking Tool
![screenshot from 2015-07-16 02 57 04](https://cloud.githubusercontent.com/assets/1840562/8720280/9a3f7be6-2b66-11e5-8adc-e593c02fc173.png)

**Comment by cg-cnu** [comment]
Am late to reply, are you guys still looking for screenshots?
Here are couple of studies I did with mypaint on centos7.

![kimidoll2](https://cloud.githubusercontent.com/assets/2767425/9202862/defd8b5e-4021-11e5-9397-6d50f354b9be.png)
![kitchentable2](https://cloud.githubusercontent.com/assets/2767425/9202865/e134b74e-4021-11e5-9eb8-df00490576d4.png)

This is the first time am contributing screenshots. Let me know if you guys need any additional info.

**Comment by achadwick** [comment]
Hello everyone -

These screenshots all look magnificent, and we will definitely be using them for the mypaint.org website rebuild. @odysseywestra is handling that now over in mypaint/mypaint.github.io#8, far better than I have been able to. Thanks for stepping in, Albert!

I'll close this issue now, in favour of the website issue. It all links up, so your contributions won't be lost! If anyone has new screenshots to post, please drop them off in mypaint/mypaint.github.io#8.

**Comment by achadwick** [comment]
Hello everyone - [whoops, sorry. I referenced the wrong issue. I hope this works better this time!]

These screenshots all look magnificent, and we will definitely be using them for the mypaint.org website rebuild. @odysseywestra is handling that now over in mypaint/mypaint.github.io#15, far better than I have been able to. Thanks for stepping in, Albert!

I'll close this issue now, in favour of the website issue. It all links up, so your contributions won't be lost! If anyone has new screenshots to post, please drop them off in mypaint/mypaint.github.io#15.
