### ISSUE TITLE
[MacPorts. OSX 10.9.5] Missing icons; Exception: Icon 'gtk-missing-image' not present in theme"

### ISSUE THREAD

**Issue by bunk3m** [mypaint/mypaint#159]
I am running MyPaint on Mac using MacPorts.  OSX 10.9.5
I tried to start MyPaint today.  Haven't had a problem before.  
Version of MyPaint: MyPaint-devel @1.1.1.alpha.20140929+git.4fafd2ad
Got this traceback.

```
 Traceback (most recent call last):
  File "/opt/local/share/mypaint/gui/history.py", line 110, on_size_allocate(self=<ManagedBrushPreview object at 0x106703be0 (gui+history+ManagedBrushPreview at 0x7fea4d923660)>, widget=<ManagedBrushPreview object at 0x106703be0 (gui+history+ManagedBrushPreview at 0x7fea4d923660)>, alloc=<CairoRectangleInt>)
                self.image_size = alloc.width, alloc.height
                self._update()
  variables: {'self._update': ('local', <bound method ManagedBrushPreview._update of <ManagedBrushPreview object at 0x106703be0 (gui+history+ManagedBrushPreview at 0x7fea4d923660)>>)}
  File "/opt/local/share/mypaint/gui/history.py", line 133, _update(self=<ManagedBrushPreview object at 0x106703be0 (gui+history+ManagedBrushPreview at 0x7fea4d923660)>)
            s = min(w, h)
            scaled_pixbuf = self._get_scaled_pixbuf(s)
            self.set_from_pixbuf(scaled_pixbuf)
  variables: {'self._get_scaled_pixbuf': ('local', <bound method ManagedBrushPreview._get_scaled_pixbuf of <ManagedBrushPreview object at 0x106703be0 (gui+history+ManagedBrushPreview at 0x7fea4d923660)>>), 's': ('local', 24), 'scaled_pixbuf': (None, [])}
  File "/opt/local/share/mypaint/gui/history.py", line 115, _get_scaled_pixbuf(self=<ManagedBrushPreview object at 0x106703be0 (gui+history+ManagedBrushPreview at 0x7fea4d923660)>, size=24)
                theme = Gtk.IconTheme.get_default()
                return theme.load_icon(Gtk.STOCK_MISSING_IMAGE, size, 0)
            else:
  variables: {'Gtk.STOCK_MISSING_IMAGE': ('global', 'gtk-missing-image'), 'theme.load_icon': ('local', gi.FunctionInfo(load_icon)), 'size': ('local', 24)}
Error: gtk-icon-theme-error-quark: Icon 'gtk-missing-image' not present in theme (0)
```

**Comment by achadwick** [comment]
The issue tracker is not a user support forum, but let's try to fix your issue.

This is happening because MyPaint cannot find the standard GTK icons. Something has happened with your installation, perhaps? Please check that GTK3 is installed properly from MacPorts.

**Comment by achadwick** [comment]
You may find it's in the `adwaita-icon-theme` port: https://www.macports.org/ports.php?by=name&substr=adwaita

**Comment by bunk3m** [comment]
Thanks @achadwick !
I've decided to do a fresh install of Macports and will check if the issue continues afterwards.

**Comment by achadwick** [comment]
@bunk3m Did that work? Do we need to do anything to MyPaint?

**Comment by bunk3m** [comment]
I did a fresh install of MacPorts, then MyPaint (MyPaint-devel
    @1.1.1.alpha.20141216+git.68f876fc_0) and X11 v2.7.7
    
    Everything is working properly again.
    
    Thanks for your help!
    
    B.
    
    On 4.01.2015 16:26 , Andrew Chadwick
      wrote:
    
    
      @bunk3m Did that work? Do we need to
        do anything to MyPaint?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by achadwick** [comment]
Good stuff. Thanks for testing!
