### ISSUE TITLE
1.2 release: decide GTK3 version range to support, & document

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#16]
We need to decide which versions of GTK should be supported for the upcoming release. I've been testing in 3.10 recently, and now 3.12 on Debian testing/unstable.

Ramon Miranda reports successes with the layers panel (notably new and potentially fragile) under Linux Mint Petra's GTK 3.8.7, but crashes when the brush editor tries to start up:

> [during BrushEditorWindow's "self._builder.add_from_string(ui_xml)" call]
> [... Builder XML in dump omitted...]
> GError: Unknown internal child: plus_button
 -- http://www.pasteall.org/52412

to give us an idea of the sorts of fun things we can expect.

Flagging as "docs+artwork" because our choice will need documenting.

**Comment by achadwick** [comment]
**Update!** Now that #48 is fixed and documented, I've discovered that the MSYS2 people are doing regular WIN32 and WIN64 builds of GTK3 stable (3.14.x). It's also a nice testing environment, good for Unixy guys like me, but with native Windows built output. @tumagonx's build is using 3.14 too.

I'm assuming this means that the Windows restriction has gone away, so I'm now thinking 3.10 should be our target minimum, since that's the version in the latest Ubuntu LTS ("trusty", 14.04). Our testing procedures would be simplified to firing up a trusty VM and trying to break stuff.

Any objections? If not, 3.10 it is.

**Comment by iirelu** [comment]
Ubuntu 14.04 is a good target environment, as it's stable but not ancient. I don't know the painful details of GTK's versioning but if 3.10 is what 14.04 has, sure, let's go for it.
