### ISSUE TITLE
crash at startup (first installation)

### ISSUE THREAD

**Issue by gustavklopp** [mypaint/mypaint#160]
First time installation of MyPaint on my computer.
MyPaint launches but a popup window appears :
```
A programming error has been detected.
It probably isn't fatal, but the details should be reported to the developers nonetheless.
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/tileddrawwidget.py", line 496, expose_cb(self=<CanvasRenderer object >at 0x7f3c47e8eb90 (GtkDrawingArea at 0x2809730)>, widget=<CanvasRenderer object at 0x7f3c47e8eb90 (GtkDrawingArea at 0x2809730)>, event=<gtk.gdk.Event at 0x7f3c47e8cb48: GDK_EXPOSE area=[13, 40, 816, 609]>)
                self.repaint(cr, event.area)
            return True
  variables: {'cr': ('local', <gtk.gdk.CairoContext object at 0x7f3c4868d5d0>), 'self.repaint': ('local', <bound method CanvasRenderer.repaint of <CanvasRenderer object at 0x7f3c47e8eb90 >(GtkDrawingArea at 0x2809730)>), 'event.area': ('local', gtk.gdk.Rectangle(13, 40, 816, 609))}
  File "/usr/share/mypaint/gui/tileddrawwidget.py", line 566, repaint(self=<CanvasRenderer object at 0x7f3c47e8eb90 (GtkDrawingArea at 0x2809730)>, cr=<gtk.gdk.CairoContext object>, device_bbox=gtk.gdk.Rectangle(13, 40, 816, 609))
        def repaint(self, cr, device_bbox=None):
            cr, surface, sparse, mipmap_level, clip_region = self.render_prepare(cr, device_bbox)
            self.render_execute(cr, surface, sparse, mipmap_level, clip_region)
  variables: {'clip_region': (None, []), 'surface': (None, []), 'device_bbox': ('local', gtk.gdk.Rectangle(13, 40, 816, 609)), 'mipmap_level': (None, []), 'sparse': (None, []), 'cr': ('local', <gtk.gdk.CairoContext object >at 0x7f3c4868d5d0>), 'self.render_prepare': ('local', <bound method CanvasRenderer.render_prepare >of CanvasRenderer object at 0x7f3c47e8eb90 (GtkDrawingArea at 0x2809730)>>)}
  File "/usr/share/mypaint/gui/tileddrawwidget.py", line 654, render_prepare(self=<CanvasRenderer object at 0x7f3c47e8eb90 (GtkDrawingArea at 0x2809730)>, cr=<gtk.gdk.CairoContext object>, device_bbox=gtk.gdk.Rectangle(13, 40, 816, 609))
            # calculate the final model bbox with all the clipping above
            x1, y1, x2, y2 = cr.clip_extents()
            if not translation_only:
  variables: {'y1': (None, []), 'x2': (None, []), 'x1': (None, []), 'y2': (None, [])}
AttributeError: 'gtk.gdk.CairoContext' object has no attribute 'clip_extents'
```
When I close the window, it keeps reappearing, so I have no other solution than to quit.
OS: Lubuntu 14.10

**Comment by achadwick** [comment]
Hi - I noticed you changed the title. Does it work on *second or subsequent* installations?

This looks like an older version of MyPaint. Which one exactly? Are you able to try again with the git master?

**Comment by gustavklopp** [comment]
I meant: I have NEVER installed MyPaint on this computer before.
So, I've tried build from sources.
Everything's building fine, but at launch, a popup window appears :
>A programming error has been detected.
>It probably isn't fatal, but the details should be reported to the developers nonetheless.
>Mypaint version: 1.1.1-alpha
>System information: Linux-3.16.0-28-generic-x86_64-with-Ubuntu-14.10-utopic
>Traceback (most recent call last):
>  File "/home/susskind/Documents/mypaint-git/mypaint/gui/tileddrawwidget.py", line 789, draw_cb(self=><CanvasRenderer object at 0x7f43f367eb40 (gui+tileddrawwidget+CanvasRenderer at 0x1ba12a0)>, >widget=<CanvasRenderer object at 0x7f43f367eb40 (gui+tileddrawwidget+CanvasRenderer at >0x1ba12a0)>, cr=<cairo.Context object>)
>            # Render the document
>            render_info = self.render_prepare(cr, None)
>            self.render_execute(cr, *render_info)
>  variables: {'cr': ('local', <cairo.Context object at 0x7f43f3b705f0>), 'None': ('builtin', None), >'self.render_prepare': ('local', <bound method CanvasRenderer.render_prepare of <CanvasRenderer >object at 0x7f43f367eb40 (gui+tileddrawwidget+CanvasRenderer at 0x1ba12a0)>>), 'render_info': >(None, [])}
>  File "/home/susskind/Documents/mypaint-git/mypaint/gui/tileddrawwidget.py", line 905, >render_prepare(self=<CanvasRenderer object at 0x7f43f367eb40 >(gui+tileddrawwidget+CanvasRenderer at 0x1ba12a0)>, cr=<cairo.Context object>, device_bbox=(0, >0, 1338, 676))
>            # calculate the final model bbox with all the clipping above
>            x1, y1, x2, y2 = cr.clip_extents()
>            if not self.is_translation_only():
>  variables: {'y1': (None, []), 'x2': (None, []), 'x1': (None, []), 'y2': (None, [])}
>AttributeError: 'cairo.Context' object has no attribute 'clip_extents'

**Comment by achadwick** [comment]
Works for me in Debian testing/unstable (the upcoming 8.x release). Could you check your Cairo and GTK libs are all up-to-date?

```
$ dpkg -l python-gi-cairo gir1.2-gtk-3.0 python-cairo
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  gir1.2-gtk-3.0 3.14.5-1     amd64        GTK+ graphical user interface lib
ii  python-cairo   1.8.8-1+b2   amd64        Python bindings for the Cairo vec
ii  python-gi-cair 3.14.0-1     amd64        Python Cairo bindings for the GOb
```

Did you install the dependencies as described in `README.md`?

**Comment by gustavklopp** [comment]
>dpkg -l python-gi-cairo gir1.2-gtk-3.0 python-cairo
>Desired=Unknown/Install/Remove/Purge/Hold
>| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
>|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
>||/ Name           Version      Architecture Description
>+++-==============-============-============-===============================>==
>ii  gir1.2-gtk-3.0 3.12.2-0ubun amd64        GTK+ graphical user interface lib
>ii  python-cairo   1.8.8-1ubunt amd64        Python bindings for the Cairo vec
>ii  python-gi-cair 3.14.0-1     amd64        Python Cairo bindings for the GOb

Apparently, maybe there's a problem with the standard version of gir1.2 provided with Lubuntu? (version 3.12 versus 3.14 needed?)
How can I update to the new 3.14 gir1.2 version? (It's not provided in Synaptic because apparently 3.12 is the last version for Lubuntu). It's strange because MyPaint is already installable by Synaptic but with a broken dependency so?

**Comment by achadwick** [comment]
Those libs should be fine.

Which sources are you using here? Please tell me the exact revision ID (it can be obtained from `git log`; it's the long hex string. Just paste that in here in ordinary text and it'll link up.)

Please verify that you are following the instructions at https://github.com/mypaint/mypaint#build--install-linux , i.e. the instructions in `README.md`. Does the exception still occur after you have uninstalled any Lubuntu packages, and then run a cleanly built MyPaint from the git tree as described in the **Testing (interactive)** section.

**Comment by gustavklopp** [comment]
The exact revision ID :
 ```
commit c3bba39da8927d88c964a87df3b94a3e10c1ef90
Author: tumagonx <mr.tiar@gmail.com>
Date:   Sun Jan 11 14:15:03 2015 +0700

    Add ldflags for .def file generation on Windows
```
I've followed exactly the instructions as marked in the link.
I've uninstall the 'mypaint' and 'mypaint-data' in synaptic also, before the building.

I've still got the same error with :
 ```
Traceback (most recent call last):
  File "/home/susskind/Documents/mypaint-git/mypaint/gui/tileddrawwidget.py", line 789, in draw_cb
    render_info = self.render_prepare(cr, None)
  File "/home/susskind/Documents/mypaint-git/mypaint/gui/tileddrawwidget.py", line 905, in render_prepare
    x1, y1, x2, y2 = cr.clip_extents()
AttributeError: 'cairo.Context' object has no attribute 'clip_extents'
```

**Comment by gustavklopp** [comment]
Isn't there a problem with my Python-cairo version? (I'm still wondering about this clip_extents function not working: apparently, this function exists since the 1.4 version:  http://cairographics.org/documentation/pycairo/2/reference/context.html?highlight=clip_extent#cairo.Context.clip_extents )

When I check with ```dpkg -l python-gi-cairo gir1.2-gtk-3.0 python-cairo```, the version of python-cairo is 1.8.8.
But when I do :
```
$ python
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cairo; cairo.version
'1.2.2'
```
Isn't this a problem? (Python-cairo is installed thanks to synaptic)

**Comment by gustavklopp** [comment]
Okay, It's solved. I had different version of cairo installed (1.2 and 1.8. I didn't know it was even possible :0 ). I've deleted the package "cairo" inside "dist-packages" of my python version, and now it's all good!
