### ISSUE TITLE
Layer drag tool causes a crash when the layer is not moved

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#161]
Steps to reproduce:
1. Select layer drag tool
2. Mouse down
3. Mouse up without moving the mouse

There's also another big issue where, if the layer is moved around but the drag ends at the original position, the layer will seemingly break and become unusable.

The problem causing the first issue is that in [TiledSurfaceMove](https://github.com/mypaint/mypaint/blob/master/lib/tiledsurface.py#L515), `self.slices_x` and `self.slices_y` are undefined until `self.update()` is called and that's only called once the mouse has moved. The solution to this would be having `self.slices_[xy] = calc_translation_slices(0)` in `__init__()`, but that can't be done for the same reason as why problem number two is a thing: `calc_translation_slices(0)` returns seemingly bogus data that, when given to [TiledSurfaceMove._process_moves()](https://github.com/mypaint/mypaint/blob/master/lib/tiledsurface.py#L620), causes it to seemingly destroy the current layer.

**Comment by achadwick** [comment]
Confirmed here, Debian testing/unstable/mishmash in GNOME 3.  Testing out a fix for it.

(Also, nice spot! Looking at the code, `calc_translation_slices(0)` is returning valid data, but it's data that results in a move of an integer number of tiles. We have an optimization for it, but it's not a very well tested code path, and evidently a broken one...)
