### ISSUE TITLE
Duplicate buttons for opening the tool config panel

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#162]
There's this one at the top:
![blender](https://cloud.githubusercontent.com/assets/3432543/5599785/9e47f36a-92c5-11e4-942a-88b5604cd3c9.png)
And this one at the bottom:
![blender](https://cloud.githubusercontent.com/assets/3432543/5599790/aa7b4db2-92c5-11e4-85e9-f03d5bcbd87d.png)

They do the exact same thing (toggle visibility of the tool configuration panel). I vote for removing the one at the bottom. For reference, all the lines of code needed to rip out to do so are [here](https://github.com/mypaint/mypaint/blob/master/gui/mypaint.glade#L149-172) and [here](https://github.com/mypaint/mypaint/blob/master/gui/drawwindow.py#L179-181).

**Comment by achadwick** [comment]
Good idea. I'll have a bash at this shortly.

**Comment by iirelu** [comment]
[Here's a commit that completely removes it](https://github.com/iirelu/mypaint/commit/3e8b1e829dde2cd16fdb32e07a9b93387843a433). The changes seem okay to me.

**Comment by achadwick** [comment]
Sorry, I've been crap and/or I've a weird definition of "shortly". Looks good, can you push?

**Comment by iirelu** [comment]
Yup, [it's in](https://github.com/mypaint/mypaint/commit/3e8b1e829dde2cd16fdb32e07a9b93387843a433).
