### ISSUE TITLE
Basic pen functionality broken.

### ISSUE THREAD

**Issue by eanbowman** [mypaint/mypaint#164]
This may be a re-post since it was filed under another bug on your old bug tracker.

Using the pen at all in the Windows x64 build does not work.

The lines are drawn seconds after the stroke is made and are often broken lines as if the user were tapping the pen rather than dragging it.

![image](https://cloud.githubusercontent.com/assets/1637212/5608874/ad0e83a6-945e-11e4-84c2-03f9ea5db540.png)

Windows 7 x64
8GB RAM
256GB SSD
Lenovo X201 Tablet

**Comment by achadwick** [comment]
Is this http://gna.org/bugs/?19948 at all?

Which version of MyPaint are you using?

**Comment by eanbowman** [comment]
This is indeed  http://gna.org/bugs/?19948 

The latest download of Windows x64 installer.

I downloaded it freshly last night and was unable to use it.

My laptop is at home so I can't verify the exact version but it is the x64 Windows build that was on the site last night when I posted this.

**Comment by iirelu** [comment]
1.0.0 is very old (2011) so chances are it's probably fixed by now. Can you try 1.1.0 or one of the downloads from [this page](http://opensourcepack.blogspot.co.uk/search/label/mypaint)?

**Comment by eanbowman** [comment]
Will do when I get home. I gather from the title those are all unofficial builds. Wonder when the page I downloaded from will update to a newer version?

http://mypaint.intilinux.com/?page_id=6

I am sorry for reporting on an older version but I was fooled by the MyPaint project page.

**Comment by iirelu** [comment]
Yeah, we've had lots of issues with Windows, mostly down to the fact that we have no active Windows developers. I *think* we're going to manage something for it in 1.2.0(?), but I'm not sure.

**Comment by eanbowman** [comment]
This works in v1.1.0. So... fixed? Just not in the binary on the MyPaint project site. I guess there are other issues to be fixed before that is updated?

Tried compiling it for myself today just for kicks. Not a Windows dev but I'd be willing to put some time into it if I could.

**Comment by iirelu** [comment]
Honestly, *any* help with Windows would be helpful. I was going to try myself, but then I found out the Windows partition I hadn't touched in months was completely broken.

I'll close this for now, as it looks like this probably doesn't affect the current master.

**Comment by achadwick** [comment]
@eanbowman Basically we'd love you forever if you could help out with #48 ☺
