### ISSUE TITLE
Freehand Circle Cursor Degrades after Reaching a Certian Size

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#166]
This is something else I've notice when I was working on my last drawing. When I resize the brush, the cursor will degrade after reaching a certian size. I would have captured it, but it won't show up thanks to xorg. This seems to only effect the circle cursors. Steps to reproduce:

-Open MyPaint with Circle cursor
-Mouse over on the canvas
-Press D or key for increase sizing the brush
-Cursor should degrade

I've notice this degrade after 2806d71, however I went back to before that commit and I still have the same problem. 

System information: Linux-3.16.0-28-generic-x86_64-with-Ubuntu-14.10-utopic
Version:1.1.1-alpha.20150106+git.6947ad9

**Comment by achadwick** [comment]
I don't see any degradation when pressing the "increase brush size" key when using the freehand tool. The size does stop increasing when the resultant cursor would be bigger than your graphics hardware's maximum cursor size.

Could you clarify what you mean by "degrade" and try to post a screenshot please? Use a camera if you have to. FWIW, I find that Xfce's screenshot tool, and the GNOME one, work fairly well for capturing cursors.

(We have had instances where software screencaps don't reflect what you see. Are you using an NVidia card? Those don't handle white cursor outlines with alpha so well.)

**Comment by achadwick** [comment]
That is weird! Thanks for the capture.

Does it happen with a fresh throwaway config too (`mypaint -c /tmp/throwawayconfig$$`), and for all cursor types in _Prefs → View_?

What does 

```
$ python 
Python 2.7.8 (default, Oct 18 2014, 12:50:18) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gdk
>>> Gdk.Display.get_default().get_maximal_cursor_size()
(64L, 64L)
>>> 
```

say on your system?

**Comment by achadwick** [comment]
The drawing code is in `gui/cursor.py` if you want to experiment. I use Intel hardware myself, 

```[171942.538] (--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics 4400```

according to `Xorg.0.log`, and I can't reproduce this one.

**Comment by achadwick** [comment]
We may be doing the wrong thing if get_maximal_cursor_size() is returning something non-square, come to think of it.

**Comment by odysseywestra** [comment]
Hmmm.... the cursor maximum size is actually larger...

```
$ python
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gdk
>>> Gdk.Display.get_default().get_maximal_cursor_size()
(128L, 128L)
>>> 
```

However when I typed it in my virtual machine image, it outputs the same as what you have.

Could it be related to the calculated hotspot?

**Comment by odysseywestra** [comment]
Oh, and it seems to only effect the circle cursors( all three thicknesses). Also when I change view such as zooming in, it will degrade as well.

 Lastly yes, every single test I did, I did it with a fresh config file.

**Comment by achadwick** [comment]
The code trusts the values it gets back from the server, and it looks to me as if your display claims it can handle bigger cursors than it actually can, since the smaller cursors in your animation are actually OK.
If it were *all* cursors showing the corruption, I'd be pointing the finger at `supports_cursor_color()` / `supports_cursor_alpha()` and our assumptions about those being true... ☺

Quick and dirty patch below: could you try this out please?

```
diff --git a/gui/cursor.py b/gui/cursor.py
index e282260..4a8e8f8 100644
--- a/gui/cursor.py
+++ b/gui/cursor.py
@@ -7,6 +7,7 @@
 # (at your option) any later version.
 
 import gui.drawutils
+from lib.helpers import clamp
 
 from gi.repository import Gtk
 from gi.repository import Gdk
@@ -15,6 +16,8 @@ from gi.repository import GdkPixbuf
 import cairo
 import math
 from cStringIO import StringIO
+import logging
+logger = logging.getLogger(__name__)
 
 # Absolute minimum size
 BRUSH_CURSOR_MIN_SIZE = 3
@@ -68,38 +71,79 @@ def get_brush_cursor(radius, style, prefs={}):
     global last_cursor, last_cursor_info, max_cursor_size
 
     display = Gdk.Display.get_default()
-    if not max_cursor_size:
-        max_cursor_size = max(display.get_maximal_cursor_size())
-    d = int(radius*2)
-    min_size = max(prefs.get("cursor.freehand.min_size", 4),
-                   BRUSH_CURSOR_MIN_SIZE)
-    if d < min_size:
-        d = min_size
-    if d+1 > max_cursor_size:
-        d = max_cursor_size-1
-    cursor_info = (d, style, min_size)
-    if cursor_info != last_cursor_info:
-        last_cursor_info = cursor_info
-        surf = cairo.ImageSurface(cairo.FORMAT_ARGB32, d+1, d+1)
-        cr = cairo.Context(surf)
-        cr.set_source_rgba(1, 1, 1, 0)
-        cr.paint()
-        draw_brush_cursor(cr, d, style, prefs)
-        surf.flush()
-
-        # Calculate hotspot. Zero means topmost or leftmost. Cursors with an
-        # even pixel diameter are interesting because they can never be
-        # perfectly centred on their hotspot. Rounding down and not up may be
-        # more "arrow-cursor" like in this case.
-        #
-        # NOTE: is it worth adjusting the freehand drawing code to add half a
-        # pixel to the position passed on to brushlib for the even case?
-        hot_x = hot_y = int(d/2)
-
-        pixbuf = _image_surface_to_pixbuf(surf)
-        last_cursor = Gdk.Cursor.new_from_pixbuf(display, pixbuf,
-                                                 hot_x, hot_y,)
-    return last_cursor
+
+    # Attempt to set a cursor size which is as big as possible on this
+    # display. Note that some displays lie about their capabilities:
+    # https://github.com/mypaint/mypaint/issues/166
+    max_cursor_size = min(display.get_maximal_cursor_size())
+    logger.debug("verif: display says %r is the maximal cursor size",
+                 max_cursor_size)
+
+    max_sizes_tried = set()
+    while max_cursor_size not in max_sizes_tried:
+
+        # Circle diameter
+        d = int(radius*2)
+        min_size = min(
+            max_cursor_size,
+            max(prefs.get("cursor.freehand.min_size", 4),
+                BRUSH_CURSOR_MIN_SIZE),
+        )
+        d = clamp(d, min_size, max_cursor_size-1)
+
+        # Regenerate, consulting the cache
+        cursor_info = (d, style, min_size)
+        if cursor_info == last_cursor_info:
+            return last_cursor
+
+        # Generate, then verify that the size is OK.
+        new_cursor = _new_brush_cursor(display, cursor_info, prefs)
+        pbuf = new_cursor.get_image()
+        if pbuf is None:
+            logger.debug("verif: cannot test resultant cursor, "
+                         "trusting the display's advertised sizes")
+            last_cursor = new_cursor
+            last_cursor_info = cursor_info
+            return new_cursor
+
+        pw, ph = pbuf.get_width(), pbuf.get_height()
+        if max(pw, ph) == max_cursor_size:
+            logger.debug("verif: size %d was OK for this display",
+                         max_cursor_size)
+            last_cursor = new_cursor
+            last_cursor_info = cursor_info
+            return new_cursor
+        else:
+            logger.debug("verif: tried to make a cursor of %dx%d, "
+                         "but got %dx%d; ignoring corrupt version")
+            max_sizes_tried.append(max_cursor_size)
+            max_cursor_size = min([pw, ph, max_cursor_size])
+
+    return Gdk.Cursor(Gdk.BOGOSITY)
+
+
+def _new_brush_cursor(display, cursor_info, prefs):
+    d, style, min_size = cursor_info
+    surf = cairo.ImageSurface(cairo.FORMAT_ARGB32, d+1, d+1)
+    cr = cairo.Context(surf)
+    cr.set_source_rgba(1, 1, 1, 0)
+    cr.paint()
+    draw_brush_cursor(cr, d, style, prefs)
+    surf.flush()
+    # Calculate hotspot. Zero means topmost or leftmost. Cursors with an
+    # even pixel diameter are interesting because they can never be
+    # perfectly centred on their hotspot. Rounding down and not up may be
+    # more "arrow-cursor" like in this case.
+    #
+    # NOTE: is it worth adjusting the freehand drawing code to add half a
+    # pixel to the position passed on to brushlib for the even case?
+    hot_x = hot_y = int(d/2)
+    pixbuf = _image_surface_to_pixbuf(surf)
+    return Gdk.Cursor.new_from_pixbuf(
+        display,
+        pixbuf,
+        hot_x, hot_y,
+    )
 
 
 def _image_surface_to_pixbuf(surf):
```

**Comment by achadwick** [comment]
Oh, and for the log messages to be visible, please run it in debug mode:

```
$ MYPAINT_DEBUG=1 ./mypaint -c /tmp/blah
```

I'm interested in what the lines starting with

```
DEBUG: gui.cursor: verif:
```

say, so feel free to omit any lines originating from outside `gui.cursor` ☺

**Comment by odysseywestra** [comment]
Here is the output for DEBUG:

```
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.cursor: verif: display says 128L is the maximal cursor size
DEBUG: gui.cursor: verif: cannot test resultant cursor, trusting the display's advertised sizes
```

**Comment by achadwick** [comment]
There's really not a lot we can do about this other than set an arbitrary upper limit for hardware cursors in the codebase. However it might be worth chasing this up with (I guess) the XOrg guys (if you're using XOrg).

Can you paste the output of `dpkg -l xserver-xorg gir1.2-gtk-3\* libgtk-3-0` too, for other people's reference?

**Comment by odysseywestra** [comment]
Alright, here is the output for reference.
```
$ dpkg -l xserver-xorg gir1.2-gtk-3\* libgtk-3-0
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  gir1.2-gtk-3.0 3.12.2-0ubun amd64        GTK+ graphical user interface lib
ii  libgtk-3-0:amd 3.12.2-0ubun amd64        GTK+ graphical user interface lib
ii  xserver-xorg   1:7.7+7ubunt amd64        X.Org X server
```
I'll also post another gif of yet another degration, however this one sticks even after I move the mouse off the canvas. Plus it will show up at random times. The only way to I could get rid of it was to lock and unlock my screen. However, if your limit for hardware cursor works, this might just be a moot point.
![vid_20150108_040626_101-214](https://cloud.githubusercontent.com/assets/1840562/5662820/2990b368-96f3-11e4-81f6-c5ac9e340af8.gif)

![vid_20150108_040626_600-655](https://cloud.githubusercontent.com/assets/1840562/5662898/052b9348-96f4-11e4-9560-2d4a060f2ecb.gif)

I'll see what happens when I post this bug upstream in xorg.

**Comment by odysseywestra** [comment]
For reference, I found this bugzilla report for libreoffice that seems to have the same effect as this bug. The connection is that it is happening on 4gen intel hardware like mine. Hope this helps figure out what is going on.

https://www.libreoffice.org/bugzilla/show_bug.cgi?id=82273

**Comment by achadwick** [comment]
@odysseywestra that's a dead link for me, sorry.
Did you file an xorg or gdk bug for this? If so, could you please paste a link to it here?

Another useful piece of info it would be useful to gather (for us and them) is what happens if you take both MyPaint and GDK out of the loop. Turns out that xdpyinfo reports this little factlet:

```
$ xdpyinfo | grep cursor
  largest cursor:    64x64
```

on mine, anyway :)

Sorry I couldn't help further here.

MyPaint users bitten by this could try using the crosshair cursor for freehand mode, available in prefs. Patches would be welcome for *good* software cursors too.

**Comment by odysseywestra** [comment]
Sorry, I've been on the road for the past few weeks, so internet has bee spotty. 

Sadly no, I didn't report the bug due to not know where to report it. And I'm not confortable with building software esspecially the display server.

By the way here the output for `xdpyinfo`
```
$ xdpyinfo | grep cursor
   largest cursor:    256x256
```
This is larger than what pygtk is outputting, so mayber there is a conflict?

**Comment by 0ion9** [comment]
@odysseywestra xorg bugs are tracked through https://bugs.freedesktop.org/ . The product id is 'xorg' -- for example, [here](https://bugs.freedesktop.org/buglist.cgi?query_format=specific&order=relevance+desc&no_redirect=0&bug_status=__open__&product=xorg&content=cursor) is a list of all open bugs containing the string 'cursor'.

As far as I can see, nobody is suggesting you should try to rebuild the display server, though, so I'm not sure what that comment was about. A misunderstanding?

**Comment by achadwick** [comment]
@odysseywestra GTK and GDK bugs are tracked through https://bugzilla.gnome.org , with product id "gtk+" for both (if I remember rightly)

You don't have to rebuild the display server or the graphical toolkit unless you are 100% comfortable with it. FWIW I always do that sort of invasive stuff on a throwaway VM snapshot.

"Software cursors" are those that render on the canvas in Python code, not via a little texture managed by the display hardware. They're often suggested as an alternative, but I've never been able to make a good software cursor myself: they tend to be laggy and slow, and not do entirely what you want... pull requests or patches welcome (because that indicates someone has a better idea).

**Comment by odysseywestra** [comment]
Well I open up mypaint again today and it seem to have fixed itself. It funny that it fixed itself when I updated the intel driver through their tool....

**Comment by achadwick** [comment]
@odysseywestra Ha! Well, I guess that toes it down to a driver issue. I don't suppose you could paste the version of intel_drv.so here at all? You may be able to get it from Xorg.0.log.

FWIW I recently upgraded the xorg intel myself; I'm using xserver-xorg-video-intel 2.99.917 out of Debian experimental for TearFree/SNA reasons (unrelated). On my hardware I don't see this issue with either this or the one in unstable, however.

**Comment by odysseywestra** [comment]
Yeah. Here the Intel Info.
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  xserver-xorg-v 2:2.99.917-1 amd64        X.Org X server -- Intel i8xx, i9x


Module intel: vendor="X.Org Foundation"
[    25.853] 	compiled for 1.16.0, module version = 2.99.917
[    25.853] 	Module class: X.Org Video Driver
[    25.853] 	ABI class: X.Org Video Driver, version 18.0
[    25.853] (II) LoadModule: "modesetting"
```

Is there a way to roll back the driver on my system to see if it was the intel driver that caused it? I'm using Gnome Ubuntu 14.10.

**Comment by achadwick** [comment]
You should be able to download and install a suitable version from http://packages.ubuntu.com/xserver-xorg-video-intel

**Comment by achadwick** [comment]
Still happening with some combinations of hardware & software: <https://twitter.com/artelizdesouza/status/660072341251211264>. Let's look at doing software cursors again after the 1.2.0 release.
