### ISSUE TITLE
HSV Triangle don't fit to the widget

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#169]
The size of HSV Triangle only changes at small amount, and don't fit to the widget unlike all other color selectors which are fit perfectly.

screencast: https://drive.google.com/file/d/0BwvdX1pBENi1OHZjemZQcUJTTEU/view

**Comment by achadwick** [comment]
[GtkHSV has been deprecated](https://developer.gnome.org/gtk3/stable/GtkHSV.html) for some time. I don't want to do any more work on our current implementation, and would readily accept code to replace it with a square or triangle selector like it but of our own devising.

**Comment by iirelu** [comment]
Yeah, that colour wheel is just a thin wrapper around GTK/GIMP's one. I experimented with removing [the line that clamps it down](https://github.com/mypaint/mypaint/blob/master/gui/colors/hsvtriangle.py#L84), but if it got any larger it became extremely laggy to resize.

Having something that fit into the rest of our pretty widgets would be nice.

**Comment by loentar** [comment]
In MyPaint 1.1.0 it worked perfectly, is this regression on GTK/GDK 3 side?

**Comment by achadwick** [comment]
The out-of-date docstring says

> The widget is extracted from a `gtk.ColorSelector` for greater compatibility [with ancient version of PyGTK that didn't wrap GtkHSV]

But we don't actually do that now.
Oh, what a horrible fudge it was since basically forever. I'll need to fix the misleading string anyway, so I'll see what I can do.

**Comment by achadwick** [comment]
Looking at the code, there's basically nothing we can do with this ancient, deprecated widget that doesn't do proper height-for-width/width-for-height management. Deferring things to make resizes less laggy just defers the part of the loop[1] that causes an Eternal Expansion bug that I don't want to ever see come back.

[1] We have to set the GtkHSV metrics, but this causes a realloc; but the process is driven from size allocation, and must be.
