### ISSUE TITLE
Exception when painting after picking a brushstroke with no parent info: `KeyError: 'parent_brush_name'`

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#172]
(At least) when picking a stroke in some old ORA files, it's possible to trigger an exception when painting with the picked brush:

```
ERROR: lib.observable: Failed to call observer <BoundObserverMethod gui.brushmanager.BrushManager._input_stroke_ended_cb>
Traceback (most recent call last):
  File "/home/andrewc/Development/MyPaint/gui/document.py", line 561, in button_release_cb
    return CanvasController.button_release_cb(self, tdw, event)
  File "/home/andrewc/Development/MyPaint/gui/document.py", line 108, in button_release_cb
    result = mode.button_release_cb(tdw, event)
  File "/home/andrewc/Development/MyPaint/gui/freehand.py", line 366, in button_release_cb
    self.doc.input_stroke_ended(event)
  File "/home/andrewc/Development/MyPaint/lib/observable.py", line 284, in __call__
    observer(observed, *args, **kwargs)
  File "/home/andrewc/Development/MyPaint/lib/observable.py", line 467, in __call__
    self._observer_func(observer, observed, *args, **kwargs)
  File "/home/andrewc/Development/MyPaint/gui/brushmanager.py", line 756, in _input_stroke_ended_cb
    brush_name = b.settings["parent_brush_name"]
```

Steps to reproduce:

1. Locate an ancient scrap .ora and load it.
2. Pick strokes and paint with them.
3. When a picked stroke uses just a generic scribble icon (indicating that its parent_brush_name refers to something that doesn't exist any more), the next paint attempt triggers the exception above.

Example squiggle icon and stored parent_brush_name:

![squiggle icon and ](https://cloud.githubusercontent.com/assets/61299/5785759/940fab50-9dd2-11e4-8165-6d8c2c608e71.png)

On master as of 4a72252d7708fc0089b9256e54085cc140e5360c, no brush exists with this name (deevad/rigger got renamed when @Deevad updated his brushset).

**Comment by iirelu** [comment]
It can be fixed by just making it check to see if the brush has the property "parent_brush_name" and then returning early, but this is sub-optimal as then it doesn't show up in the history. Where is the hover text for the brush picker getting the brush name from? There doesn't seem to be anything of value in b.settings.

**Comment by iirelu** [comment]
I think in the interest of clarity and code quality we should have a function for explicitly checking the "loose-ish equality" of two brushes. Error checking could then be handled in there.

**Comment by achadwick** [comment]
@iirelu re refactoring brushes. Goodness, yes. There's about three layers of abstraction in the python code alone. Those could do with being consolidated into one representation which I *think* could live in `lib/`. There's some GdkPixbuf hair on some of them and maybe GLib too, but those alone wouldn't prevent `gui/` being recoded into a (hypothetical) Clutter UI or a Gtk/Clutter hybrid. GLib hair might preclude a (hypothetical) qt rewrite, but that's pretty far off the map of future paths.
