### ISSUE TITLE
Problem with opening .ora files

### ISSUE THREAD

**Issue by Dawid90dd** [mypaint/mypaint#173]
I can't open .ora files. I always get this nasty programming error:
http://pastebin.com/h4Hc7Vvj

Any ideas? I'm using Kubuntu 14

Edit: I noticed, that i have the same problem in GIMP - cannot open .ora files. I also tried saving them in GIMP, and then open them in GIMP. The same problem.

**Comment by achadwick** [comment]
Pasting it here for convenience.

```
Traceback (most recent call last):
  File "/home/dawid90dd/mypaint-0.8.2/gui/filehandling.py", line 369, open_recent_cb(self=<gui.filehandling.FileHandler object>, action=<gtk.RecentAction object at 0x7f03585a75f0 (GtkRecentAction at 0x23b11f0)>)
            fn = helpers.get_file_path_from_dnd_dropped_uri(uri)
            self.open_file(fn)
  variables: {'self.open_file': ('local', <bound method FileHandler.wrapper of <gui.filehandling.FileHandler object at 0x7f0361a82710>>), 'fn': ('local', '/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora')}
  File "/home/dawid90dd/mypaint-0.8.2/gui/drawwindow.py", line 41, wrapper(self=<gui.filehandling.FileHandler object>, *args=('/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora',), **kwargs={})
            try:
                func(self, *args, **kwargs)
            finally:
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x7f0361a82710>), 'args': ('local', ('/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora',)), 'func': ('local', <function open_file at 0x7f0361a7c410>), 'kwargs': ('local', None)}
  File "/home/dawid90dd/mypaint-0.8.2/gui/filehandling.py", line 166, open_file(self=<gui.filehandling.FileHandler object>, filename='/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora')
            try:
                self.doc.load(filename)
            except document.SaveLoadError, e:
  variables: {'self.doc.load': ('local', <bound method Document.load of <lib.document.Document instance at 0x7f0358594368>>), 'filename': ('local', '/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora')}
  File "/home/dawid90dd/mypaint-0.8.2/lib/document.py", line 276, load(self=<lib.document.Document instance>, filename='/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora')
            try:
                load(filename)
            except gobject.GError, e:
  variables: {'load': ('local', <bound method Document.load_ora of <lib.document.Document instance at 0x7f0358594368>>), 'filename': ('local', '/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora')}
  File "/home/dawid90dd/mypaint-0.8.2/lib/document.py", line 426, load_ora(self=<lib.document.Document instance>, filename='/home/dawid90dd/Ace Of Space/Images & Sounds & Concepts/concept_scrap3.ora')
            xml = z.read('stack.xml')
            image = ET.fromstring(xml)
            stack = image.find('stack')
  variables: {'xml': ('local', '<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<image h="1920" w="2432">\n  <stack>\n    <layer mypaint_strokemap="data/layer000_strokemap.dat" opacity="1.0" src="data/layer000.png" x="0" y="0" />\n    <layer mypaint_strokemap="data/layer001_strokemap.dat" opacity="0.457" src="data/layer001.png" x="0" y="448" />\n    <layer background_tile="data/background_tile.png" name="background" opacity="1.0" src="data/background.png" x="0" y="0" />\n  </stack>\n</image>\n'), 'image': (None, None), 'ET.fromstring': ('global', <function XML at 0x7f0361de1e60>)}
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1299, XML(text='<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<image h=...ckground.png" x="0" y="0" />\n  </stack>\n</image>\n', parser=None)
        if not parser:
            parser = XMLParser(target=TreeBuilder())
        parser.feed(text)
  variables: {'parser': ('local', None), 'XMLParser': ('global', <class 'xml.etree.ElementTree.XMLParser'>), 'target': (None, None), 'TreeBuilder': ('global', <class 'xml.etree.ElementTree.TreeBuilder'>)}
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1465, __init__(self=<xml.etree.ElementTree.XMLParser object>, html=0, target=<xml.etree.ElementTree.TreeBuilder object>, encoding=None)
                    raise ImportError(
                        "No module named expat; use SimpleXMLTreeBuilder instead"
                        )
ImportError: No module named expat; use SimpleXMLTreeBuilder instead
```

**Comment by achadwick** [comment]
@Dawid90dd 
Is this really MyPaint 0.8.4? If it is, sorry that's way too old for us to support. Try updating to 1.1.0: http://packages.ubuntu.com/mypaint

(If not, please let me know which git revision this is and I'll try to find some time to have a look at it.)

**Comment by Dawid90dd** [comment]
I've updated mypaint to 1.1.0 but i have another problem... im getting weird problem in python files. When im trying to execute mypaint 1.1.0 i get this:

0
Using GTK2
builtin python 2.6 json support
DEBUG: getlocale(): ('en_US', 'UTF-8')
DEBUG: localepath:  /usr/share/locale
DEBUG: localepath_brushlib:  /usr/share/locale
confpath = /home/dawid90dd/.mypaint/
DEBUG: mode stack updated: <ModeStack [SwitchableFreehandMode]>
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 199, in <module>
    main.main(datapath, extradata, confpath)
  File "/usr/share/mypaint/gui/main.py", line 77, in main
    run()
  File "/usr/share/mypaint/gui/main.py", line 52, in run
    app = application.Application(datadir, extradata, options.config, args)
  File "/usr/share/mypaint/gui/application.py", line 142, in __init__
    self.drawWindow = self.layout_manager.get_widget_by_role("main-window")
  File "/usr/share/mypaint/gui/layout.py", line 102, in get_widget_by_role
    self.main_window = result[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

Im really confused, everything is messing up. I think its something with dependencies

**Comment by achadwick** [comment]
The issue tracker is not intended for user help requests. Sorry. But let's try to get you a working MyPaint.

* 1.1.0 is the current stable, and things have moved on in development. I can only offer limited support for it. Does this problem go away if you try 1.1.1-alpha? Get it from https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing

* Does the problem go away if you try running MyPaint with a fresh toy config?

  ```sh
mypaint -c /tmp/toyconfig$$
```

  If it does, please delete your MyPaint config and try again. Because you started out with such an ancient version, things may be awry in there:

  ```sh
cd ~
tar cvpfz mypaint-config.`date +'%Y%m%d%H%M%S'`.tar.gz .{,config/,cache/,local/share/}mypaint
# The 2 lines above BACK UP all MyPaint config areas
# Don't worry about any errors above
rm -Irv .{,config/,cache/,local/share/}mypaint
# CAUTION: THIS DELETES ALL CONFIG AREAS. Although it will ask first!
```

* If you see an error popup or any backtraces on the command like, please paste the full text of any exceptions you see between triple backtick fences, like this:

    ```
    (error goes here)
    ```

  and paste it into a *new* issue.
