### ISSUE TITLE
No pressure on Windows (Intuos 5, Surface Pro 3 Ntrig, probably others)

### ISSUE THREAD

**Issue by crydalch** [mypaint/mypaint#178]
I followed the build instructions in README_WINDOWS.md (thank you BTW!) on my Surface Pro 3. I can launch the build, but I get no pressure sensitivity. 

Is there something missing from the build instructions, to get pressure sensitivity to work? Or is that part of the code that still needs work?

Thanks!

**Comment by achadwick** [comment]
I'm still investigating Windows behaviour with GDK, so I simply don't know. But let's investigate! Can you tell me if you're able to run https://gist.github.com/achadwick/54e5b111e5ac908becf1 with the MSYS2 python from the instructions and get sensible output?

I note with some dismay that on my Win7 VM I see

```
$ python axischart.py

(python.exe:3968): Gdk-CRITICAL **: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(python.exe:3968): Gdk-CRITICAL **: gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed

(python.exe:3968): Gdk-WARNING **: gdk_input_wintab_init: gdk_window_new failed
INFO:Axischart:New device class='gtk.gdk.DeviceWin32' name='System Aggregated Pointer' (src='mouse')

```

Even with USB pass-through in my Win7 VM and the most recent Wacom drivers. That's for mouse, eraser end of the pen, and mouse: all are treated the same.

FWIW, I get a much more healthy:

```
$ python axischart.py 
INFO:Axischart:Found device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Pen stylus' (src='pen')
INFO:Axischart:Found device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Finger' (src='touchpad')
INFO:Axischart:Found device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Pen pad' (src='pen')
INFO:Axischart:Found device class='gtk.gdk.X11DeviceXI2' name='Wacom Intuos5 touch M Pen eraser' (src='eraser')
INFO:Axischart:Found device class='gtk.gdk.X11DeviceXI2' name='DLL060A:00 06CB:2734' (src='touchpad')
```

when running it from the host OS without the VM running and intercepting USB things.

Let me know what you get on your real hardware.

**Comment by crydalch** [comment]
Interesting, the stylus appears as a mouse, not a stylus:
```
$ python axischart.py
(python.exe:5852): Gdk-CRITICAL **: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
(python.exe:5852): Gdk-CRITICAL **: gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed
(python.exe:5852): Gdk-WARNING **: gdk_input_wintab_init: gdk_window_new failed
INFO:Axischart:New device class='gtk.gdk.DeviceWin32' name='System Aggregated Pointer' (src='mouse')
```
I'm not seeing pressure appear, though it seems to be tracking XY properly. The Ntrig stylus doesn't have a wheel or eraser; though I figured the WinTab drivers would take care of the stylus 'translation', so at least pressure would work (Ntrig doesn't have tilt either).

![mypaint-axischart-capture](https://cloud.githubusercontent.com/assets/458856/5848526/392a74d0-a18e-11e4-9205-90e345546f79.png)

Maybe something's changed in Gtk3? MyPaint 1.0 was Gtk2, right?

Sometimes I wish Microsoft had continued with Wacom stylus, but Ntrig allowed them to get more accuracy, no craziness near the boarders, and a thinner computer. Tradeoffs, *sigh* :) 

Thanks for being willing to investigate and see what we can uncover! Love using MyPaint, so anything I can do, I'm happy to try! Thanks!

**Comment by odysseywestra** [comment]
I can also confirm this on my HP laptop running windows 8.1 with my wacom intous medium tablet as well. So it's not isolated to Ntrig.

**Comment by achadwick** [comment]
Looking at this one and #177, I'm not liking this warning in particular:

```
(python.exe:3968): Gdk-WARNING **: gdk_input_wintab_init: gdk_window_new failed
```

Looks like GDK's trying to put up some sort of screen area to capture input the `WinTab`by way and just failing.

Paging @tumagonx again (sorry!): I'd be interested to know if the axischart test code above shows pressure traces with the Python+GDK you've been using, and what its terminal output is when it detects new devices. Simply put, I want to see the success case too!

Strongly suspect that this is an upstream (GDK) issue that should be flagged here and monitored. Ideally we want it to be fixed upstream for newer GTK-and-GDK versions, and to keep doing experimental toy builds on the MSYS2 bleeding-ish edge.

**Comment by achadwick** [comment]
The warning in question is being emitted from [win32/gdkdevicemanager-win32.c line 454](https://git.gnome.org/browse/gtk+/tree/gdk/win32/gdkdevicemanager-win32.c?h=gtk-3-14#n454). So why is it failing to create that window and bailing out?

**Comment by achadwick** [comment]
Related upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=743330

**Comment by tumagonx** [comment]
@achadwick IIRC it really was about incorrect window initialization, this cause in some case (unreproducible unfortunately) where context menu window are sent behind main window instead of going on top. Wintab issue probably just side effect.

That is the actual bug cause:
gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

which cause:
gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed
which cause wintab fail

I need to diffing 3.9.4 and 3.9.3 again though, I only remember there was one/two important function (an init function I think) that significantly changed and that changes still relevant up to current GTK.

**Comment by achadwick** [comment]
Mini observation: I don't get the Gdk-WARNING or Gdk-CRITICAL on a VM where the Wacom drivers (and wintab[32].dll, I guess) aren't installed.

**Comment by achadwick** [comment]
Making some progress on https://bugzilla.gnome.org/show_bug.cgi?id=743330

@tumagonx I think we're at a stage in the GTK bugzilla report where we could really use your input. You seem to know a lot about what's going on here...

**Comment by achadwick** [comment]
Lots of progress on https://bugzilla.gnome.org/show_bug.cgi?id=743330 now - looks like we'll have this patched in short order upstream.

![winpressure](https://cloud.githubusercontent.com/assets/61299/5925281/4dfceaa2-a65a-11e4-9145-1cddf2b4030a.png)

**Comment by achadwick** [comment]
I can confirm that pressure sensitivity is back in Gtk 3.14.8: and binary builds are available via MSYS. Please retest, and re-open this issue (or make a new one) if pressure is still broken on Windows.

![winout](https://cloud.githubusercontent.com/assets/61299/5993975/5d62e2bc-aa5b-11e4-83c6-70216ae0a401.png)

**Comment by crydalch** [comment]
Hey Andrew, your little test suite shows pressure properly, and it reports the Ntrig device. But I'm still having issues in MyPaint when I rebuild. There's a chance I missed an update or something, so I'll wait to re-open or create an issue until I have more time to look carefully.

Thanks for helping get that Gtk bug fixed!

**Comment by odysseywestra** [comment]
Sadly, I'm not getting pressure sensitivity. I've update my to the latest packages and I even reinstalled MSYS and restarted from the ground seeing if my environment was broken. I even tested using the Axischart.py to see it was just mypaint alone, and it's sadly it's not. Both report my wacom as a mouse device.

Here is a list of packages and their version numbers: https://gist.github.com/0456414d66079fa574c6.git

And here's what axischart.py list my device as:
```
INFO:Axischart:New device class='gtk.gdk.DeviceWin32' name='System Aggregated Pointer' (src='mouse')
```
wacom device: http://www.wacom.com/en-us/products/pen-tablets/intuos-pen-and-touch-medium

**Comment by tumagonx** [comment]
Which driver package you've download and version
What's your wintab32.dll version in your system directory
So someone on the same tablet could jump in and help

Or it could be GDK's wintab haven't keep up with the latest standard and (non-standard). Tough luck

**Comment by odysseywestra** [comment]
So far on my windows 8.1 partition everything is up to date. I'm using the
standard wacom drivers for my tablet. As far as wintab32.dll version, I
have no idea how to look that up. I rarely use windows. And if I do, it's
only for testing.

**Comment by achadwick** [comment]
Poking this one to see if it needs any attention.

If so, and if pressure isn't working when it should be on some device models, please could anyone affected make a new issue referencing this one (as `#178`). That's probably best.
