### ISSUE TITLE
Error popup with super/alt/draw

### ISSUE THREAD

**Issue by black-silence** [mypaint/mypaint#182]
When holding `super` (win) + `alt` while drawing a line with the Graphire 4 pen a program error dialog pops up with the following traceback. I can always reproduce this. When I choose to close the popup I can continue using MyPaint.
`super` + `alt` + left mouse draw is bound to the compiz screenshot plugin on my system. I didn't press this combination on purpose so it would not be a problem if there's nothing you can do.

64bit arch linux, xfce + compiz 0.8.4, MyPaint 1.1.0, gtk 2.24.25/3.14.7

```
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/document.py", line 76, button_press_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7fbb73df55f0 (GtkEventBox at 0x291ecd0)>, event=<gtk.gdk.Event at 0x7fbb73e2b1c0: GDK_BUTTON_PRESS x=76,17, y=718,13, button=1>)
            """
            result = self.modes.top.button_press_cb(tdw, event)
            self.__update_last_event_info(tdw, event)
  variables: {'event': ('local', <gtk.gdk.Event at 0x7fbb73e2b1c0: GDK_BUTTON_PRESS x=76,17, y=718,13, button=1>), 'tdw': ('local', <TiledDrawWidget object at 0x7fbb73df55f0 (GtkEventBox at 0x291ecd0)>), 'result': (None, []), 'self.modes.top.button_press_cb': ('local', <bound method SwitchableFreehandMode.button_press_cb of <gui.canvasevent.SwitchableFreehandMode object at 0x7fbb73e05b90>>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 580, button_press_cb(self=<gui.canvasevent.SwitchableFreehandMode object>, tdw=<TiledDrawWidget object at 0x7fbb73df55f0 (GtkEventBox at 0x291ecd0)>, event=<gtk.gdk.Event at 0x7fbb73e2b1c0: GDK_BUTTON_PRESS x=76,17, y=718,13, button=1>)
            if action_name is not None:
                return self._dispatch_named_action(None, tdw, event, action_name)
  variables: {'None': ('builtin', None), 'action_name': ('local', u'ColorPickMode'), 'tdw': ('local', <TiledDrawWidget object at 0x7fbb73df55f0 (GtkEventBox at 0x291ecd0)>), 'event': ('local', <gtk.gdk.Event at 0x7fbb73e2b1c0: GDK_BUTTON_PRESS x=76,17, y=718,13, button=1>), 'self._dispatch_named_action': ('local', <bound method SwitchableFreehandMode._dispatch_named_action of <gui.canvasevent.SwitchableFreehandMode object at 0x7fbb73e05b90>>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 647, _dispatch_named_action(self=<gui.canvasevent.SwitchableFreehandMode object>, win=None, tdw=<TiledDrawWidget object at 0x7fbb73df55f0 (GtkEventBox at 0x291ecd0)>, event=<gtk.gdk.Event at 0x7fbb73e2b1c0: GDK_BUTTON_PRESS x=76,17, y=718,13, button=1>, action_name=u'ColorPickMode')
                else:
                    return mode.button_press_cb(tdw, event)
            elif handler_type == 'popup_state':
  variables: {'tdw': ('local', <TiledDrawWidget object at 0x7fbb73df55f0 (GtkEventBox at 0x291ecd0)>), 'event': ('local', <gtk.gdk.Event at 0x7fbb73e2b1c0: GDK_BUTTON_PRESS x=76,17, y=718,13, button=1>), 'mode.button_press_cb': ('local', <bound method ColorPickMode.button_press_cb of <gui.colorpicker.ColorPickMode object at 0x7fbb73aabf10>>)}
  File "/usr/share/mypaint/gui/colorpicker.py", line 72, button_press_cb(self=<gui.colorpicker.ColorPickMode object>, tdw=<TiledDrawWidget object at 0x7fbb73df55f0 (GtkEventBox at 0x291ecd0)>, event=<gtk.gdk.Event at 0x7fbb73e2b1c0: GDK_BUTTON_PRESS x=76,17, y=718,13, button=1>)
            self._button_press_seen = True
            self.doc.app.pick_color_at_pointer(self.doc.tdw, self.PICK_SIZE)
            return super(ColorPickMode, self).button_press_cb(tdw, event)
AttributeError: 'NoneType' object has no attribute 'app'
```

**Comment by odysseywestra** [comment]
If you change the compiz screenshot shortcut and repeat it again, dose the error still pop up.

**Comment by black-silence** [comment]
With the screenshot plugin disabled I see the color picker, no error popup.
I guess it's a problem when compiz steals the cursor but not the initial mousedown event or something?

**Comment by odysseywestra** [comment]
It's showing up same colorpicker with me when I press ```super``` + ```alt```, so maybe that what it causing it. However, I'm also reciving a similar error when I use ```ctl```+```space_bar``` then try to draw on the canvas though I don't know if the shortcut is bind to the DE or another program. Plus I'm using Gnome3 instead of xfce. Here's a dump of the traceback:

```python
Mypaint version: 1.1.1-alpha
System information: Linux-3.16.0-29-generic-x86_64-with-Ubuntu-14.10-utopic
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/document.py", line 543, button_press_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7f799f0792d0 (TiledDrawWidget at 0x32286c0)>, event=<void>)
                    return self._dispatch_named_action(None, tdw, event,
                                                       action_name)
            # User-configurable forbidding of particular devices
  variables: {'action_name': ('local', u'ColorPickMode')}
  File "/usr/local/share/mypaint/gui/document.py", line 670, _dispatch_named_action(self=<gui.document.Document object>, win=None, tdw=<TiledDrawWidget object at 0x7f799f0792d0 (TiledDrawWidget at 0x32286c0)>, event=<void>, action_name=u'ColorPickMode')
                else:
                    return mode.button_press_cb(tdw, event)
            elif handler_type == 'popup_state':
  variables: {'tdw': ('local', <TiledDrawWidget object at 0x7f799f0792d0 (TiledDrawWidget at 0x32286c0)>), 'event': ('local', <void at 0x4ce4ae0>), 'mode.button_press_cb': ('local', <bound method ColorPickMode.button_press_cb of <gui.colorpicker.ColorPickMode object at 0x7f798c0fc350>>)}
  File "/usr/local/share/mypaint/gui/colorpicker.py", line 77, button_press_cb(self=<gui.colorpicker.ColorPickMode object>, tdw=<TiledDrawWidget object at 0x7f799f0792d0 (TiledDrawWidget at 0x32286c0)>, event=<void>)
            self._button_press_seen = True
            self.doc.app.pick_color_at_pointer(self.doc.tdw, self.PICK_SIZE)
            return super(ColorPickMode, self).button_press_cb(tdw, event)
AttributeError: 'NoneType' object has no attribute 'app' 
```

The only thing really similar of the bug is in the ```/gui/colorpicker.py``` where it calling the same lines of code.

Let's see what @achadwick, or @iirelu think before we do anything esle.

**Comment by jy2wong** [comment]
I got the same error as @odysseywestra. I'm using no DE and an obscure tiny window manager called goomwwm. ctrl+space pulls up a run dialog on my machine, which showed up along with the error dialog window. When I kill the program that handles my keyboard shortcuts (sxhkd), no error dialog appears, just as @black-silence described.

I did spot something new in the console, though:
```
WARNING: gui.mode: Keyboard grab failed: <enum GDK_GRAB_ALREADY_GRABBED of type GdkGrabStatus>
WARNING: gui.mode: Keyboard grab failed: <enum GDK_GRAB_ALREADY_GRABBED of type GdkGrabStatus>
```

Seems to implicate gui/mode.py.

**Comment by iirelu** [comment]
> Let's see what @achadwick, or @iirelu think before we do anything esle.

Aw, you make me blush. Anyway, to me this looks like some code is making assumptions it shouldn't that end up breaking when things don't go the way it likes. I can't reproduce this myself, so feel free to investigate further.

**Comment by achadwick** [comment]
I can't reproduce this one either (Gnome3, Debian testing/unstable), even with @odysseywestra  's binding of Ctrl+Btn2 to Pick Color.

There's some very hairy grab code in there though, which I don't really think is warranted. Grab on enter? Ugh. Perhaps a rewrite is in order? It does date from before the migration to GTK3, and should have its syntax ported to PyGobject's style.

**Comment by achadwick** [comment]
@odysseywestra What's your Window Action Key bound to in GNOME? Try turning Window Actions off temporarily in Tweak Tool and seeing if that improves matters.

I still think it needs to be less of a drag-based thing. There are a lot of requirements bodged into a single class too: it's messy stuff.

**Comment by odysseywestra** [comment]
The Window Action key is binded to the super key. I turned it off and tried the ```Ctl```+```Space```+```Btn1```, and I'm still getting the traceback error, so I don't think it's the windows action key causeing it.

**Comment by odysseywestra** [comment]
Figured how to reproduce this by chance. It was caused by an external application known as wallch which is a destop wallpaper manager.

I set in the preferences to when ever I press ```ctl```+```space``` to switch my wallpaper.

Steps to reproduce:
* Install an applicatoin which utilizes global shortcuts like wallch.

*buntu instructions
```
sudo add-apt-repository ppa:wallch/wallch-4.0
sudo apt-get update
sudo apt-get install wallch
```
* Open appliation and go to edit > preferences and click on the wallpaper tab.
* Check "Use Shortcut for 'Next Wallpaper':" and set combination to ```ctl```+```space```
* Close, select wallpaper location and start the service.
* Open up MyPaint and use ```ctl```+```space```+```btn1```
* Traceback Error should pop up.

By the looks of it, MyPaint is haveing trouble distinguishing between global shortcuts and local shortcuts here. I also explain why's @black-silence was having a similar error but with compiz's screenshot plugin instead.

Oh and thanks @Deevad for helping me figure it out by chance. If it wasn't for me downloading your illustration on patreon, I would have not figured it out. Funny how things work out huu? ^^'

**Comment by achadwick** [comment]
Interesting. It's clearly a screwup involving global hotkeys of various kinds (app-specific bindings, DE specific bindings, WM-specific bindings). And that grab message looks cause-ish.

I wonder if one of GNOME or Xfce's global hotkeys could trigger it too, and what tools it affects in MyPaint.

**Comment by achadwick** [comment]
Reproduced!
* In GNOME's Keyboard→Shortcuts→Windows, bind "Toggle window on all workspaces or one" to Ctrl+space.
* Launch MyPaint with a fresh build and a throwaway `-c` config area.
* Hold down Ctrl
* *then* hold down space
* *then* click the mouse button (no need to attempt a drag)

The following exception and associated log messages are shown

```
WARNING: gui.mode: Keyboard grab failed: <enum GDK_GRAB_ALREADY_GRABBED of type GdkGrabStatus>
WARNING: gui.mode: Keyboard grab failed: <enum GDK_GRAB_ALREADY_GRABBED of type GdkGrabStatus>
Traceback (most recent call last):
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/document.py", line 543, in button_press_cb
    action_name)
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/document.py", line 670, in _dispatch_named_action
    return mode.button_press_cb(tdw, event)
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/colorpicker.py", line 77, in button_press_cb
    self.doc.app.pick_color_at_pointer(self.doc.tdw, self.PICK_SIZE)
AttributeError: 'NoneType' object has no attribute 'app'
```

This does not happen when you remove the global binding in GNOME's Keyboard settings.

Normally, holding Ctl+Space allows you to pan the view by moving the pointer. However if it's intercepted by anything else, MyPaint only sees a Ctrl, followed by a click, and tries to drop into picker mode with the default app keyboard bindings. Clearly this is when it starts fighting with other things over keyboard grabs and doing weird things.

**Comment by achadwick** [comment]
With a few debugging messages, it looks like it's trying to leave() in the middle of enter()ing the mode, which is doubtless screwing up the internal state:

```
CRITICAL: gui.colorpicker: >>> enter()
CRITICAL: gui.colorpicker:     enter: calling _force_drag_start()
WARNING: gui.mode: Keyboard grab failed: <enum GDK_GRAB_ALREADY_GRABBED of type GdkGrabStatus>
CRITICAL: gui.colorpicker: >>> leave()
CRITICAL: gui.colorpicker: <<< leave()
CRITICAL: gui.colorpicker:     enter: _force_drag_start() done
CRITICAL: gui.colorpicker: <<< enter()
CRITICAL: gui.colorpicker: >>> enter()
CRITICAL: gui.colorpicker:     enter: calling _force_drag_start()
WARNING: gui.mode: Keyboard grab failed: <enum GDK_GRAB_ALREADY_GRABBED of type GdkGrabStatus>
CRITICAL: gui.colorpicker: >>> leave()
CRITICAL: gui.colorpicker: <<< leave()
CRITICAL: gui.colorpicker:     enter: _force_drag_start() done
CRITICAL: gui.colorpicker: <<< enter()
WARNING: gui.colorpicker: *** click
```

Removing the grab forcing attempt during enter() restores a more normal

```
CRITICAL: gui.colorpicker: >>> enter()
CRITICAL: gui.colorpicker: <<< enter()
WARNING: gui.colorpicker: *** click
WARNING: gui.mode: Keyboard grab failed: <enum GDK_GRAB_ALREADY_GRABBED of type GdkGrabStatus>
CRITICAL: gui.colorpicker: >>> leave()
CRITICAL: gui.colorpicker: <<< leave()
```

sequence and stops it from crashing, but the mode does end up subtly broken as a result, particularly the "R" key behaviour. Time for that rewrite, clearly.

Perhaps the colour picker should only pick from the canvas? Doing that would simplify the code a lot.

**Comment by achadwick** [comment]
I'm pretty certain that will have fixed it. @odysseywestra, @jy2wong, and @black-silence (if you're testing against master): can you all test it please as of 5fa2cab? Thanks.

**Comment by jy2wong** [comment]
looks fine from over here.

**Comment by black-silence** [comment]
```
python2.7 brushlib/generate.py brushlib/mypaint-brush-settings-gen.h brushlib/brushsettings-gen.h
Writing brushlib/mypaint-brush-settings-gen.h
Traceback (most recent call last):
  File "brushlib/generate.py", line 137, in <module>
    writefile(args[1], generate_internal_settings_code())
  File "brushlib/generate.py", line 105, in generate_internal_settings_code
    [settings_info_struct(i) for i in brushsettings.settings])
  File "brushlib/generate.py", line 69, in generate_static_struct_array
    entries.append(indent + "{%s}" % (", ".join(entry)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```
build fails :/

I added a `print(entry)` before generate.py:69, the last line printed is 
`(u'"hardness"', 'N_("H\xc3\xa4rte")', 'FALSE', '0.0', '0.8', '1.0', u'N_("Hard brush-circle borders (setting to zero will draw nothing). To reach the maximum hardness, you need to disable Pixel feather.")')`
"H\xc3\xa4rte" should probably be the German word "Härte"

Funny thing is, the unicode marker at the string is only missing for translated strings, not those without translation...
```
(u'"opaque"', 'N_("Deckkraft")', 'FALSE', ...
(u'"opaque_multiply"', u'N_("Opacity multiply")', 'FALSE', ...
```

... managed to build it after removing that translation from the po file. No more hotkey related crashes.

**Comment by achadwick** [comment]
Thanks for the confirmation.

The build error is a separate issue, unrelated to this one. Please report it against the libmypaint ("brushlib") component via https://github.com/mypaint/libmypaint/issues.
We'll need to know the version inside brushlib/ `(cd brushlib && git log)`, what your locale is exactly (`locale -v`), and what locales are supported on your system (`locale -a`).

**Comment by achadwick** [comment]
Apologies, was accidentally reopened.
