### ISSUE TITLE
Regression: After clicking on "Change the Axis of Symmetry" icon MyPaint crashes.

### ISSUE THREAD

**Issue by Ico-dY** [mypaint/mypaint#184]
Regression: After clicking on "Change the Axis of Symmetry" icon MyPaint crashes.
I'm using the latest git version. (Main Branch)
It always happens.

Details:

```
Mypaint version: 1.1.1-alpha
System information: Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/tileddrawwidget.py", line 801, draw_cb(self=<CanvasRenderer object at 0x7f6f144f5690 (gui+tileddrawwidget+CanvasRenderer at 0x28aeae0)>, widget=<CanvasRenderer object at 0x7f6f144f5690 (gui+tileddrawwidget+CanvasRenderer at 0x28aeae0)>, cr=<cairo.Context object>)
                cr.save()
                overlay.paint(cr)
                cr.restore()
  variables: {'cr': ('local', <cairo.Context object at 0x7f6f00a44d50>), 'overlay.paint': ('local', <bound method SymmetryOverlay.paint of <gui.symmetry.SymmetryOverlay object at 0x7f6efb848cd0>>)}
  File "/usr/local/share/mypaint/gui/symmetry.py", line 553, paint(self=<gui.symmetry.SymmetryOverlay object>, cr=<cairo.Context object>)
                    size=gui.style.FLOATING_BUTTON_ICON_SIZE,
                    fg=(0, 0, 0, 1),
                )
  variables: {'fg': (None, [])}
  File "/usr/local/share/mypaint/gui/drawutils.py", line 298, load_symbolic_icon(icon_name='mypaint-trash-symbolic', size=16, fg=(0, 0, 0, 1), success=None, warning=None, error=None, outline=None)
        rgba_or_none = lambda tup: (tup is not None) and Gdk.RGBA(*tup) or None
        icon_pixbuf, was_symbolic = info.load_symbolic(
            fg=rgba_or_none(fg),
  variables: {'info': ('local', None), 'icon_pixbuf': (None, []), 'success': ('local', None), 'rgba_or_none': ('local', <function <lambda> at 0x7f6ef9655ed8>), 'warning_color': (None, []), 'error': ('local', None), 'warning': ('local', None), 'success_color': (None, []), 'error_color': (None, []), 'fg': ('local', (0, 0, 0, 1)), 'was_symbolic': (None, [])}
AttributeError: 'NoneType' object has no attribute 'load_symbolic'
```

**Comment by achadwick** [comment]
Do the toolbar icons look OK?

Please make sure librsvg is installed, and that your loaders.cache (`man gdk-pixbuf-query-loaders`) refers to it . Still happening?

**Comment by achadwick** [comment]
Also please let me know if the behaviour is different when run from the build tree as `./mypaint`, or with a fresh install.

**Comment by achadwick** [comment]
Finally, I need to know what git revision this is (`git log`, top commit is the latest)

**Comment by Ico-dY** [comment]
Loaders.cache refers to /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so installed by librsvg2-common package and the toolbar icons always look ok. From the build tree MyPaint doesn't crash but it crashes when running from a fresh /usr/local installation. The git revision is: commit ac2876bf0c608217b3c91805acb9a48c37f7f7b3

**Comment by tumagonx** [comment]
about this loaders.cache, on windows i'd rather build gdk-pixbuf with all image format modules statically linked than have to deal with gdk-pixbuf-query-loaders at startup especially in portable app case.

another trick on win32 by Tor Lilqvist is using length hex PREFIX path during configure like 
echo gdk-pixbuf_2.30.8-1_win32 | md5sum | cut -d

I don't understand at all why, but this way even if loaders.cache's paths are wrong ( e.g after mypaint installed on other computer) it will always work. This is how official GTK binaries was built.

but it just a minor matter of convenience...

**Comment by achadwick** [comment]
Cannot reproduce this one on Debian testing/unstable. Will try to reproduce it exactly as specified on a Trusty VM shortly.

**Comment by achadwick** [comment]
@Ico-dY Do you get a similar crash when trying to pan the view with space or the mouse?

**Comment by achadwick** [comment]
Cannot reproduce this on Ubuntu 14.04 Trusty, installing it as documented in `README_LINUX.md`, i.e. with sudo and into a fresh /usr/local.

@Ico-dY please can you paste the output of `find /usr/local -name 'mypaint-trash-symbolic*' -exec ls -l {} \;` and let me know its output? Thanks.

**Comment by Ico-dY** [comment]
No problem with panning. 
Find output:
-rw-r--r-- 1 root root 950 Dec  9 13:57 /usr/local/share/icons/hicolor/scalable/actions/mypaint-trash-symbolic.svg

**Comment by achadwick** [comment]
:confused: Okay then. Are the icons for any other MyPaint installations installed anywhere, and what state are your icon-theme.cache files in? Can you try

```
find /usr -name icon-theme.cache -exec ls -l {} \;
find /usr -name mypaint.svg -exec ls -l {} \;
find /usr -name tileddrawwidget.py -exec ls -l {} \;
```

please? It's possible you have an outdated icon-theme.cache in /usr/local *and* a package-managed or locally-installed MyPaint in /usr from where it's picking up the icons it can find. Please [update your icon caches as described in `README_LINUX.md`](https://github.com/mypaint/mypaint/blob/1187bc898d044362b98f428adec91a3095864f2c/README_LINUX.md#post-install), although I guess if it's `/usr/local` junk you can just delete the icon caches.

**Comment by achadwick** [comment]
(The reason I asked about panning is that it uses a custom cursor. Since 085bc4a9eea0d7380b7bd621e34e984a677fe5f4, those custom cursors use gui.drawutils.load_symbolic_icon() too, so if there is a problem with that function, it should show up when you pan with space or the mouse. The error can show up late though.

I think you have an incorrect local installation issue here, but I think the module should have better testing and be more fault-tolerant.)

**Comment by achadwick** [comment]
Here's what Symmetry Mode *should* look like:

![symmetry mode](https://cloud.githubusercontent.com/assets/61299/6020308/54c42312-aba2-11e4-8240-a82a0b1d91f8.png)

The butterfly and the trash icon are both rendered by the same function.

**Comment by Ico-dY** [comment]
Thank you! 
Solved with: sudo gtk-update-icon-cache --ignore-theme-index /usr/local/share/icons/hicolor 
Other icons cache refreshing method didn't work. The trash icon was the problem...
You can close this issue. Thanks again. ^^

**Comment by achadwick** [comment]
No problem, glad you sorted it out!

(Maybe just deleting the icon caches in /usr/local would be better in the long run?)
