### ISSUE TITLE
Every time when the line is drawn, cursor_remove.png appears

### ISSUE THREAD

**Issue by stsdc** [mypaint/mypaint#192]
Is this the intendend behavior ?
Is there any option to disable this ?
I'm using MyPaint 1.1.0+git on eOS with 3.13.0-34-generic #60~precise1-Ubuntu

**Comment by iirelu** [comment]
You mean this thing?
![cursor_remove](https://cloud.githubusercontent.com/assets/3432543/6098687/986da684-afde-11e4-8aff-6ec247d66605.png)

**Comment by achadwick** [comment]
What sort of line are you trying to draw? Freehand or one of the geometric line tools? Please supply exact steps to reproduce this issue.

* eOS is https://en.wikipedia.org/wiki/Elementary_OS , correct?
* This is GTK+ 3.13.0, right? I'll assume this is actually unrelated to issue `#60` ☺
* Is is still happening with 1.1.1-alpha, a.k.a. the current development head?

**Comment by stsdc** [comment]
@iirelu, Nope, looks like I have been mistaken. 
![screenshot - 08 02 2015 - 23 21 09](https://cloud.githubusercontent.com/assets/6031763/6098811/d8e581ea-afe9-11e4-9c3f-a3e1dc016c68.png)

Only happens when I try to draw a freehand line.
*  Besides elementaryOS, this icon also appears on Xubuntu 14.04
* Sorry for this hashtag, I copypasted it from terminal with all of these info.
* The first attempt to build alpha was unsuccesful. I'll will try again.

**Comment by achadwick** [comment]
Oh! That's MyPaint showing you where the last drawing position was (note how it fades out - it's a fading overlay that's almost there for debugging purposes). You can turn it off in **View→Feedback→Last Painting Position** if it's distracting.

This is intended behaviour :grinning:

**Comment by iirelu** [comment]
Oh wow, that IS distracting. Shouldn't that be off by default, or in the debug menu?

**Comment by stsdc** [comment]
There is possibility that I played with options and forgot about it. I'm feeling a bit ashamed.
Thank You very much and sorry for taking Your time !

**Comment by achadwick** [comment]
@stsdc Hey, no problem. That happens :)

@iirelu It seems to be off by default, with fresh configs. It's theoretically handy for people using the geometric line modes that care about last-position, though TBH those don't seem to update it. Ehhh.
