### ISSUE TITLE
Changelog for 1.2.0

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#193]
We probably need one!

I went through the last two years of commit history and picked out any major changes I could find and compiled them into a draft [here](https://gist.github.com/iirelu/64f1cab810ff67e4ea5f), someone please tell me if I missed anything important.

**Comment by achadwick** [comment]
Looks good - thanks for doing this.

Can I suggest moving the user-facing changes first?

Maybe we should mention the GTK2->3 migration, since that's been the major cause of delay.

**Comment by iirelu** [comment]
I split it up into two categories because that seemed like a better idea:

# Changelog:

* Bugfixes!
* Tons of tweaks to everything!
* Lots of improvements!
* Windows support has gotten better!
* [Everything is on Github now](https://github.com/mypaint/mypaint)!
* The brush engine has been moved over to [its own repository](https://github.com/mypaint/libmypaint)!
* Everything has been migrated from GTK2 to GTK3!
* Big code quality improvements!

## Features

* [New brush pack](http://kaerhon.deviantart.com/art/Kaerhon-Brush-Pack-v1-for-Mypaint-1-1-378138104)!
* Vector layers! MyPaint can't edit them itself but you can open them in whatever program you want and edit them there!
* New brush and colour history panel!
* Flood fill tool!
* Layer trimming!
* New Red/Yellow/Blue and Red-Green/Blue-Yellow colour wheel options!
* Dark theme!
* Cursors look better!
* Icons look better!
* More preferences for devices! If you've had problems in the past, this should help at bit.
* Eraser mode no longer changes the size of the brush!
* More kinds of images can be used as layers, even if MyPaint doesn't understand what they look like! No longer will your .ORAs get corrupted if they do weird things!
* More kinds of images now work as backgrounds!

**Comment by 0ion9** [comment]
"More kinds of images can be used as layers, even if MyPaint doesn't understand what they look like! No longer will your .ORAs get corrupted if they do weird things!"

Not sure exactly what 'kinds of images' is supposed to mean. 
File types (eg. TIFF, JPG, or even BMP, PS etc rather than just PNG)?
Or image content/encoding types (PNGs using [interlacing | colordepth != 8])?

The same ambiguity is present in "More kinds of images now work as backgrounds!"

**Comment by tumagonx** [comment]
@0ion9 Theoretically we could use any image format that gdkpixbuf support, it would vary across distro but we could get the list with:
<pre>
for i in GdkPixbuf.Pixbuf.get_formats():
  GdkPixbuf.PixbufFormat.get_extensions(i)
<pre>

**Comment by 0ion9** [comment]
@tumagonx  :.. and?

My comment was supposed to point out that exactly what "More kinds of images" means is ambiguous.
The user doesn't care that we are using GdkPixbuf, they generally want to know what a given change means in pragmatic terms:

a) they can put exotic file types (TIFF etc) in ORA files without worry of corruption
b) they can put exotic image types (high bitdepth, single channel, RGB rather than RGBA) in ORA files without worry of corruption.
c) both

Since I haven't spent the time to track down the relevant commits, unlike iirelu, I have no idea of which of the above is the case.

**Comment by achadwick** [comment]
**Boring theory, skip if dull**

Current class hierarchy for layers:

![layerhier](https://cloud.githubusercontent.com/assets/61299/6146455/bedb3e78-b1e4-11e4-816c-c0a96a25a991.png)

The interesting ones for users are:

* LayerStack **★NEW★** - appears as a folder ("Layer group") and applies its own mode, or can be used for pass-through
* PaintingLayer **★OLD★** - the usual bitmap brush painting layer, used for PNGs inside the ORA container.
* VectorLayer **★NEW★** - used for any SVGs inside the ORA. They get bitmap-ified for display, but they're great for captions you want to edit later
* FallbackBitmapLayer **★NEW★** - this is used for GdkPixbuf-renderable things like JPEGs, PS(?), that shouldn't be converted to PNG automatically. You can edit them in an external editor, like any other FileBackedLayer.
* FallbackDataLayer **★NEW★** - the everything-else fallback. All you get is a (rather crappy) icon, and it's not really a feature: more of a way of preserving stuff MyPaint doesn't understand.

**Comment by achadwick** [comment]
Practically though, for the changelog:

@iirelu Can you mention/tweak:

* Layer groups. Layers can be arranged in groups[, which apply their own mode].
* [Groups can act as simple pass-through folders instead if you don't want them to have modes.]
* Mask layers. Two new layer modes make masking groups possible [Destination-In, Destination-Out]
* Data conservation. ORA layers which contain data MyPaint can't render[,] or edit [without bitrot, ]are kept unchanged[ to avoid data loss].

(Unduly verbose crap in []s)

Mask layers are supposed to be used inside (non-pass-through) groups, so it's best to mention them close together.

**Comment by tumagonx** [comment]
@0ion9 
sorry, that would be (a) then. I think (b) may need gegl, how gegl integration has been?

**Comment by 0ion9** [comment]
@tumagonx @iirelu
In that case, I suggest the following amendments:

* More image file types can be used as layers, even if MyPaint doesn't understand what they look like! No longer will your .ORAs get corrupted if they do weird things!
* More image file types now work as backgrounds!

..
Pretty sure that we're nowhere near that level of functionality with gegl. Though if I understand correctly, read-only b) could be implemented without any gegl use (similar to the way vector layers are implemented -- storing the 'data for saving' and 'data for display' separately). Anyway that's getting off topic.

**Comment by mikshaw** [comment]
The preview and editable symmetry axis are new and exciting features since 1.1

**Comment by iirelu** [comment]
I'll use my draft and all the suggestions in this issue to make the full changelog once we get to that point, thanks!

**Comment by mikshaw** [comment]
Is autosave a new feature? The question was just asked on irc, and i can't seem to find any hint of it in 1.1

**Comment by achadwick** [comment]
@mikshaw alas, no. The way I want to do it requires quote a few changes, and there hasn't been time. Relevant issue is #90.

**Comment by mikshaw** [comment]
what is the filename.ora.BAK file that the dev version has been creating? Not autosave in the sense of being automatically updated incrementally, but it's related i assume

**Comment by achadwick** [comment]
The .BAK is just a backup copy of what's already there, if there was anything there before.

Would people prefer a `~` suffix, like vim/emacs/various other text editors? Please let me know on #203.

**Comment by mikshaw** [comment]
as far as i've seen, the .BAK is created regardless of whether or not something with that name was there before. I've been making a new daily image with a unique name each day, and every time there is a new .BAK file associated with each new .ora.  Does the file get created when you hit ctrl+s on an existing file?

**Comment by achadwick** [comment]
Just pushed an initial stab at issue #13. Could we add

> * New tool for inking long smooth curves and finessing them

please?

**Comment by jy2wong** [comment]
Seems like it's worth mentioning brush right click menus, too.

**Comment by achadwick** [comment]
@iirelu How's this going? Is it in a form where it can be pushed and managed within the source tree?

**Comment by iirelu** [comment]
Sorry, haven't had much time to be productive lately.

Putting everything here into a CHANGELOG.md and building on it from there sounds like the best idea. If we want, we could also add the changelogs for all the previous versions for consistency (are there changelogs for those? Not actually sure).

**Comment by achadwick** [comment]
Yeah, [changelog](https://github.com/mypaint/mypaint/blob/b9a3cf72894a4e39993f540332496af5d400671d/changelog) is the current version. Markdown-ifying it sounds like a good idea!

**Comment by iirelu** [comment]
Did a quick search-replace on the changelog and renamed it to [Changelog.md](https://github.com/mypaint/mypaint/blob/332498f3f7836f0012291675e7256f8b8a9343af/Changelog.md)

**Comment by achadwick** [comment]
Moving to the beta phase because this still requires a code commit, and reassigning to myself.
