### ISSUE TITLE
"Move layer in stack" unconditionally appears when dragging over the layers list

### ISSUE THREAD

**Issue by jy2wong** [mypaint/mypaint#199]
Discovered this while poking around with issue #148.

From a fresh config, press l (lower case L) and shift+c. Drag a palette colour square over the layers list. "Move layer in stack..." will show up in the status bar, even though the thing that is being dragged is not a layer.

**Comment by iirelu** [comment]
It's the tiniest of bugs but it's worth fixing, I guess. It's so subtle that I nearly didn't notice anything.

**Comment by jy2wong** [comment]
Honestly I only noticed because I was actively trying to break things (who drags colours into the layers list anyway? haha.) I agree that it's the most microscopic bug ever, but I figured that a bug is a bug.

**Comment by achadwick** [comment]
Closed by the fix for #148: the code is careful to be all `Gtk.TargetFlags.SAME_WIDGET` about the drag setup now ☺
