### ISSUE TITLE
wen stroking undo don't work

### ISSUE THREAD

**Issue by kakachiex2** [mypaint/mypaint#200]
wen i make some stroke sometime i have to ctrl+z a lot to undoing the operation
- win 7
- geforce gts 250 1giga vram, 4giga ddr3...

**Comment by achadwick** [comment]
I think this issue may be a duplicate of #174.

@kakachiex2 Does it look like https://drive.google.com/file/d/0BwvdX1pBENi1WEhUYm1TcTNrbW8/view ?

**Comment by kakachiex2** [comment]
yes is exactly the behavior i'm getting
