### ISSUE TITLE
Cannot start, icon is gone?

### ISSUE THREAD

**Issue by kokizzu** [mypaint/mypaint#201]
I'm using 64-bit ArchLinux, installed using `community` repository https://www.archlinux.org/packages/community/x86_64/mypaint/

```
1 community/mypaint 1.1.0-3 [installed]
    A fast and easy painting application for digital painters, with brush dynamics
```

The output of `mypaint` command:

```
0
Using GTK2
builtin python 2.6 json support
DEBUG: getlocale(): ('en_CA', 'UTF-8')
DEBUG: localepath:  /usr/share/locale
DEBUG: localepath_brushlib:  /usr/share/locale
confpath = /home/asd/.mypaint/
Error: Where have my icons gone?
Icon search path: ('/home/asd/.icons', '/home/asd/.local/share/icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/share/mdm/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/usr/share/mdm/pixmaps', '/usr/share/pixmaps', '/usr/share/icons')
Mypaint can't run sensibly without its icons; please check your installation.
see https://gna.org/bugs/?18460 for possible solutions
```

**Comment by iirelu** [comment]
Did it work previously? It sounds like whoever's packaging it is doing it improperly. Have you tried installing from source?

**Comment by kokizzu** [comment]
No, this is the first time I try it..

No, not yet, I'll try later building from source at home.

**Comment by achadwick** [comment]
The file list looks sensible for that Arch package, and the search path is right.

Before you try building from source, can you try reinstalling the Arch package using pacman? That may fix it.

*If not*, does using the workaround involving `gtk-update-icon-cache` described in https://gna.org/bugs/?18460 or at https://github.com/mypaint/mypaint/blob/master/README_LINUX.md#post-install make the problem go away? If that fixes it, this is a downstream packaging bug, and you need to to report it [on the archlinux.org tracker](https://bugs.archlinux.org/?project=5&cat%5B%5D=33&string=mypaint). A link to it here would be welcome.

(And you can build the latest alpha from source, or any tagged release if you want to try it for yourself)

**Comment by kokizzu** [comment]
Yes, I've tried reinstalling and the `gtk-update-icon-cache` command but the error still the same.

**Comment by achadwick** [comment]
Pkay. Do you have any cache files for hicolor earlier in the icon search path than what the package installs? Sometimes ensuring they're readable and/or removing them fixes this problem.

```
for a in "$HOME/.icons" "$HOME/.local/share/icons" '/usr/local/share/icons' '/usr/share/icons'; do ls -l "$a/hicolor/icon-theme.cache"; done
```

**Comment by kokizzu** [comment]
`$ for a in "$HOME/.icons" "$HOME/.local/share/icons"
'/usr/local/share/icons' '/usr/share/icons'; do ls -l
"$a/hicolor/icon-theme.cache"; done`

```
ls: cannot access /home/asd/.icons/hicolor/icon-theme.cache: No such file
or directory
ls: cannot access /home/asd/.local/share/icons/hicolor/icon-theme.cache: No
such file or directory
ls: cannot access /usr/local/share/icons/hicolor/icon-theme.cache: No such
file or directory
-rw-r--r-- 1 root root 32784 2015.02.12 20:52
/usr/share/icons/hicolor/icon-theme.cache
```

**Comment by achadwick** [comment]
And of course, are the icons actually in the locations listed in https://www.archlinux.org/packages/community/x86_64/mypaint/ (click on "View the file list for mypaint")?

**Comment by kokizzu** [comment]
Yes, they are there (in `usr/share/icons/hicolor/`)

**Comment by kokizzu** [comment]
```
$ ll /usr/share/icons/hicolor/
total 120
drwxr-xr-x 21 root root  4096 2015.02.12 20:52 ./
drwxr-xr-x 21 root root  4096 2015.01.26 10:38 ../
drwxr-xr-x  3 root root  4096 2014.12.19 15:35 1024x1024/
drwxr-xr-x 15 root root  4096 2014.02.17 18:20 128x128/
drwxr-xr-x  3 root root  4096 2013.12.10 07:11 160x160/
drwxr-xr-x 15 root root  4096 2014.06.07 20:26 16x16/
drwxr-xr-x 15 root root  4096 2014.02.17 18:20 192x192/
drwxr-xr-x  3 root root  4096 2014.10.12 00:14 20x20/
drwxr-xr-x 15 root root  4096 2014.06.07 20:26 22x22/
drwxr-xr-x 15 root root  4096 2014.06.07 20:26 24x24/
drwxr-xr-x 15 root root  4096 2014.02.17 18:20 256x256/
drwxr-xr-x 15 root root  4096 2014.06.07 20:26 32x32/
drwxr-xr-x 15 root root  4096 2014.02.17 18:20 36x36/
drwxr-xr-x  3 root root  4096 2014.05.14 16:16 384x384/
drwxr-xr-x  3 root root  4096 2014.10.12 00:14 40x40/
drwxr-xr-x 15 root root  4096 2014.02.17 18:20 48x48/
drwxr-xr-x  4 root root  4096 2014.08.29 22:10 512x512/
drwxr-xr-x 15 root root  4096 2014.06.07 20:26 64x64/
drwxr-xr-x 15 root root  4096 2014.02.17 18:20 72x72/
drwxr-xr-x 15 root root  4096 2014.02.17 18:20 96x96/
drwxr-xr-x 15 root root  4096 2014.06.07 20:26 scalable/
-rw-r--r--  1 root root 32784 2015.02.12 20:52 icon-theme.cache
-rw-------  1 root root     0 2014.11.03 10:37 index.theme
```

**Comment by kokizzu** [comment]
Ah wait after `chmod +R a+r /usr/share/icons/hicolor` and starting `mypaint` again, the error changed:

```
0
Using GTK2
builtin python 2.6 json support
DEBUG: getlocale(): ('en_CA', 'UTF-8')
DEBUG: localepath:  /usr/share/locale
DEBUG: localepath_brushlib:  /usr/share/locale
confpath = /home/kyz/.mypaint/
/usr/share/mypaint/gui/application.py:65: GtkWarning: Theme file for hicolor has no name

  if not icon_theme.has_icon('mypaint') \
/usr/share/mypaint/gui/application.py:65: GtkWarning: Theme file for hicolor has no directories

  if not icon_theme.has_icon('mypaint') \
Error: Where have my icons gone?
Icon search path: ('/home/kyz/.icons', '/home/kyz/.local/share/icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/share/mdm/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/usr/share/mdm/pixmaps', '/usr/share/pixmaps', '/usr/share/icons')
Mypaint can't run sensibly without its icons; please check your installation.
see https://gna.org/bugs/?18460 for possible solutions
```

**Comment by achadwick** [comment]
It's [looking for a specific pair of icons under its search path](https://github.com/mypaint/mypaint/blob/v1.1.0/gui/application.py#L65), namely `mypaint-tool-brush` and `mypaint`.

Can you show me the output of

```
cd /usr/share/icons
find hicolor -name 'mypaint-tool-brush.*' -exec ls -ld {} \;
find hicolor -name 'mypaint.*' -exec ls -ld {} \;
```

That's where I think this Arch package is trying to install them, but please repeat this for the other paths in `Icon search path:` above if they're not installed there - I don't really know how Arch packages work in detail.

**Comment by kokizzu** [comment]
```
$ find hicolor -name 'mypaint-tool-brush.*' -exec ls -ld {} \;
-rw-r--r-- 1 root root 16353 Jan  1  2013 hicolor/scalable/actions/mypaint-tool-brush.svg
-rw-r--r-- 1 root root 2148 Jan  1  2013 hicolor/48x48/actions/mypaint-tool-brush.png
-rw-r--r-- 1 root root 919 Jan  1  2013 hicolor/24x24/actions/mypaint-tool-brush.png
-rw-r--r-- 1 root root 885 Jan  1  2013 hicolor/22x22/actions/mypaint-tool-brush.png
-rw-r--r-- 1 root root 1053 Jan  1  2013 hicolor/32x32/actions/mypaint-tool-brush.png
-rw-r--r-- 1 root root 635 Jan  1  2013 hicolor/16x16/actions/mypaint-tool-brush.png
$ find hicolor -name 'mypaint.*' -exec ls -ld {} \;
-rw-r--r-- 1 root root 21547 Jan  1  2013 hicolor/scalable/apps/mypaint.svg
-rw-r--r-- 1 root root 2802 Jan  1  2013 hicolor/48x48/apps/mypaint.png
-rw-r--r-- 1 root root 922 Jan  1  2013 hicolor/24x24/apps/mypaint.png
-rw-r--r-- 1 root root 940 Jan  1  2013 hicolor/22x22/apps/mypaint.png
-rw-r--r-- 1 root root 1721 Jan  1  2013 hicolor/32x32/apps/mypaint.png
-rw-r--r-- 1 root root 654 Jan  1  2013 hicolor/16x16/apps/mypaint.png
```

**Comment by achadwick** [comment]
Wait, what? "Theme file for hicolor has no name", "Theme file for hicolor has no directories"? It's zero length too. That's just not right.

Is https://www.archlinux.org/packages/extra/any/hicolor-icon-theme/ properly installed? Please reinstall it if it is, and see if it's making a nonzero /usr/share/icons/hicolor/index.theme.

**Comment by kokizzu** [comment]
ah it works now.. after reinstalling `hicolor-icon-theme`

**Comment by achadwick** [comment]
There's the problem then. Thanks for investigating!

Are you able to report this to the Arch tracker? It looks like a problem with the MyPaint packaging (either dependency, or not running the icon theme cache builder as a postinstall), but further investigation may be needed by the maintainer. If you do open a bug in Arch, please link it here so that other MyPaint users on Arch will be able to find it amongst our issues.

**Comment by achadwick** [comment]
Incidentally, it looks like this is two separate machines, so you may need to revisit some or all of this on another box. The same workaround may not work, but reinstalling `hicolor-icon-theme` should be a powerful approach.

Closing now.
