### ISSUE TITLE
Pick a better backup file suffix (".BAK" => "~", or something else?)

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#203]
I deliberately made MyPaint's overwrite backup file suffix a bit bulky and ugly (`.BAK`) so that it would be obvious to people and get testers discussing what they want, but that hasn't happened as I hoped.  Personally, I'm in favour of vim-style `~` suffixes

`some-name.ora` → `some-name.ora~`

like vim/gedit/emacs, but what do people think? I find that the `.BAK` files tend to visually clutter up a folder, and that file managers like Thunar or Nautilus tend to hide *~ (for better or worse).

Other relevant discussion: #90.

**Comment by iirelu** [comment]
I'd rather them not be in the same directory as what's being backed up. I have vim set up so that temporary files all get put in ~/.vim/backup, which stops directories from being cluttered up. Mypaint should do a similar thing. Maybe re-use the default ~/Pictures/MyPaint/ directory?

**Comment by achadwick** [comment]
MyPaint has been using *~ for some time now since #264 was merged, and no-one has complained about it yet. I'll treat that as meaning that this is resolved now!

#264 also merged a proper os.replace()-workalike function for Python 2, so replace-via-tempfile handling should be more robust generally now. And there are (additional non-fsysnc()ed because performace) autosave backups happening to the user's cache area now: basically backups everywhere and properly managed ones too.

I'd still be happy to accept PRs for turning the old "make a backup copy of overwritten files (*~)" feature off. Personally I don't much like putting all the backup copies in the same directory, but that's just personal taste.
