### ISSUE TITLE
Touchpads: horizontal scrolling does rotate, which is weird

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#204]
When horizontal scrolling is turned on in the DE's settings, `org.gnome.settings-daemon.peripherals.touchpad.horiz-scroll-enabled` for example, scrolling horizontally on a touchpad performs stepwise rotation, which feels *weird* because it's quite easy to go from vertical-only scrolling to horizontal with the two-finger drag gesture and suddenly the viewport is turned by 30°.

Suggest making unmodified horizontal and vertical scroll work like Ctrl+Btn2+Drag, i.e.:

* vertical scrolling zooms in and out
* horizontal scrolling pans left and right

This seems more right to me somehow.

Ctrl- and Shift-modified scroll could still do rotation or panning. We should also support smooth scrolling if the model is closer to what Ctrl+Btn2+Drag does. Though maybe it should be accessible via modifiers because stepwise is nice too. What about:

* Unmodified: vertical=smooth-zoom, horizontal=smooth-pan
* Shift: both=smooth-pan
* Ctrl: vertical=smooth-rotate
* +Alt: make it non-smooth

maybe?

(Note that touchPAD gestures are ones which are interpreted by hardware and delivered as either oldskool notchy scrolls kinda like button presses, or modern smooth scroll events with direction. TouchSCREEN gestures are a completely different kettle of fish, and would need us to write our own software-side interpretation.)

**Comment by achadwick** [comment]
Relevant thread with an illustrative patch (thanks, Sakse Dalum!) over at https://mail.gna.org/public/mypaint-discuss/2014-11/msg00000.html - though I'd like to do it in a different way that doesn't need any configuration.

**Comment by achadwick** [comment]
That `org.gnome.settings-daemon.peripherals.touchpad.horiz-scroll-enabled` is the default in GNOME.

**Comment by jy2wong** [comment]
I find horizontal scroll-rotate extremely irritating, and I'm not sure I'd find horizontal scroll-pan less irritating. If I'm trying to zoom in with a touchpad (trackpoint actually, but it doesn't really matter for this discussion), I'm invariably going to screw up and end up with a line that isn't perfectly vertical. I didn't find it intuitive when the canvas started rotating when I was trying to zoom, and IMO any behaviour other than zooming seems confusing.

Also IMO vertical panning and horizontal panning should always be together (with a modifier, perhaps shift, to constrain the panning to one dimension or the other).
