### ISSUE TITLE
Frame tool: add a remove button, like symmetry mode

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#206]
The frame tool should allow the frame to be removed by clicking a button on the canvas, just like the symmetry tool.

Mockup: ![frame remove button](https://cloud.githubusercontent.com/assets/61299/6201684/3370a9a8-b4b0-11e4-8c94-d9df45b9d3de.png)

Once the frame is removed, the next click should crate a new frame centred on the cursor and sized according to the viewport minimum dimension: just like clicking in Symmetry Mode when there's no axis crates a new axis.

Mockup is from one of my local working branches. Useful, intuitive placement of the button might be an interesting challenge. Assigned myself...

**Comment by iirelu** [comment]
If the frame is resized down it doesn't let you move it to the bottom right corner. Found that after a few seconds of testing. It seems you specifically need to drag the bottom left corner of the frame towards the top right in order to get that bug.

**Comment by achadwick** [comment]
@iirelu Is the trash button getting in the way of the grab edges and handles or something? That could be a problem given the way the hit zones are worked out.

(Sorry about the crappy packed-out commit above, yeah that's bad and I should split stuff up more)

**Comment by iirelu** [comment]
Here's a gif:
![buggy](https://cloud.githubusercontent.com/assets/3432543/6212538/57151bbc-b5de-11e4-96d5-086cd36b076c.gif)

**Comment by achadwick** [comment]
@iirelu Good spot! It can be reproduced with 496e016846c5019810395aac315cfd72858010e7 too, so it doesn't look like a new thing. I'll report it as a new issue so I don't forget about it.
