### ISSUE TITLE
OpenRaster 0.0.4 ... can the version number be cleaned before MyPaint 1.2

### ISSUE THREAD

**Issue by horkana** [mypaint/mypaint#212]
I've been taking at look at MyPaint 1.1.1-alpha.20150216+git.320a581
and I notice the OpenRaster version is set as 0.0.4-pre.1

that number was proposed by Andrew Chadwick @achadwick 
http://lists.freedesktop.org/archives/create/2014-February/004878.html
there don't appear to have been any objections to his proposals on the Create mailing list

Can the version number be bumped to a clean 0.0.4? 
(Such outrageous version number inflation after only 12 months year might cause a scandal!)
I was going to ask on the create mailing list but since Andrew Chadwick seems to be the main person driving forward the specification and testing out the ideas here it seemed more direct to ask here.

**Comment by achadwick** [comment]
Can do. I suspect nobody will bat an eyelid if I bump the spec up to version 0.0.4 too.

* [ ] Bump version in http://www.freedesktop.org/wiki/Specifications/OpenRaster/Draft/
* [ ] Use a non-prerel version in MyPaint.
