### ISSUE TITLE
Default background layer shifted when opening ora file in another application

### ISSUE THREAD

**Issue by mikshaw** [mypaint/mypaint#214]
![15-0223-124906](https://cloud.githubusercontent.com/assets/5081349/6336395/535757dc-bb70-11e4-92d0-edec65ae49c6.jpg)
For the past few months, dev version creates ora files in which the background layer (the one that doesn't display in mypaint's layer panel) is shifted when opening the file in gimp or krita, maybe other programs as well.  The direction and distance of the offset seem to vary from one file to the next.

Debian Testing, 64-bit

**Comment by achadwick** [comment]
Looks like the [conventional layer-style background we save to keep other apps happy](https://github.com/mypaint/mypaint/blob/4d51a9153471c2985338f276a6be0da29352f3db/lib/layer.py#L3645), er, doesn't. Couple of questions for you:

* Is the background layer in your screenshots of the right size?
* If it has a pattern, is the pattern properly aligned with artwork layers on top of it?
* Do I have to get my black NSFW marker out for that... hooded thing... on the right? :fearful:

**Comment by achadwick** [comment]
Confirmed within MyPaint itself

1. Create an image with a background pattern
   * One of the comic guide pages is good for this
   * Draw something aligned to this background
   * Frame it nicely, be sure to adjust the frame to something other than a tile boundary
   * Save it to a .ora file
2. Set MyPaint's default background to something else to make what happens next apparent
3. Close MyPaint
4. Open MyPaint, and open the image: all should be as expected :ok:
   ![image](https://cloud.githubusercontent.com/assets/61299/6348142/63c91c0e-bc15-11e4-876b-75c1755a7350.png)
   * I turned the frame tool on to make it more apparent what's what
   * this is what I expect next too, at least within the frame
5. Close MyPaint
6. Turn off MyPaint's own special handling of its background tile with the patch below
   * now MyPaint emulates what other paint programs do
7. Open the modified MyPaint, and open the image: now things are all misaligned :bug: 
    ![image](https://cloud.githubusercontent.com/assets/61299/6347792/8b3fafa8-bc12-11e4-9792-191b4f00bb29.png)
8. Moving the additional "background" layer reveals that it wasn't scaled wrongly, but it's:
    * obviously misaligned
    * less obviously: it's trimmed to multiples of the background tile in both dimension (in this case 256x320px)

------------------------

Patch to tuirn off MyPaint's special background handling during load (applies to 4d51a9153471c2985338f276a6be0da29352f3db)

```patch
diff --git a/lib/layer.py b/lib/layer.py
index c3d13e3..48c5e65 100644
--- a/lib/layer.py
+++ b/lib/layer.py
@@ -3143,7 +3143,7 @@ class RootLayerStack (LayerStack):
         """Loads and appends a single child layer from an open .ora file"""
         attrs = elem.attrib
         # Handle MyPaint's special background tile notation
-        bg_src = attrs.get('background_tile', None)
+        bg_src = None
         if bg_src:
             assert self._no_background, "Only one background is permitted"
             try:
```

**Comment by mikshaw** [comment]
to answer your initial questions,
1. No, it was scaled down...the screenshot (both programs in one) was originally 1600x900, but in addition to that the image on the left was zoomed to fit into the gimp window.
2. I haven't tested with patterns...they are a distraction to me =o)
3. It's an eye. I was actually afraid it would be accused of looking too much like Kodos and Kang.

**Comment by achadwick** [comment]
3.: Phew! Also, is it weird that I find the hermit crab oddly adorable?
2. & 1.: No problem. I think I've figured out what the problem was.

I've pushed a quick fix to master. Are you able to test it out and make sure it doesn't break saving or loading (into other apps)?

I've tested that it saves ordinary layers, vector layers, and the background sensibly when there's a frame now. I've not tested the no-frame case, fallback image layers, or fallback data layers. The generated .ora files load into GIMP and Krita on my Debian testing box correctly although neither Krita nor GIMP know about SVG files as vector layers yet.

It *looks* right...

**Comment by mikshaw** [comment]
seems to be fine now =o)
Thank you!

I don't know what you mean with "no-frame case, fallback image layers, or fallback data layers", but the only place i saw a problem was with saving an ora with no specified background or frame and then opening the same ora in gimp. That problem seems to be gone.

**Comment by achadwick** [comment]
Glad it seems fixed, and thank you for the testing as well as the clear writeup and description of the issue. Pictures really do help!
