### ISSUE TITLE
[evdev] Inking tool pressure drops out

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#223]
I think this occurs when pressure remains relatively constant.
Anyway, no matter what brush I use, the result is a line broken in many places.

[**EDIT:** linked image properly: markdown docs [here](https://guides.github.com/features/mastering-markdown/) -- achadwick]
![image](https://i.imgur.com/Xdp1JUn.png)

Specs:
* My tablet uses evdev driver.
* Gtk+ 3.13.8
* Arch Linux x86_64

**Comment by achadwick** [comment]
Well at least it's obvious on which nodes it's happening.

This is happening because evdev/X11 feeds the wrong data to Gdk. The fix will be to add a workaround like the long-standing #29 for freehand mode.

**Comment by achadwick** [comment]
Upstream bug is https://bugzilla.gnome.org/show_bug.cgi?id=703610. Please shout at the GTK guys there to get it fixed properly, or to determine if this is a kernel/evdev bug and get them to fix it.

**Comment by achadwick** [comment]
Does it work with a mouse? It'll record [0%, 50%, 50% .... 50%, 0%], but that should be enough.

Also please test with https://gist.github.com/achadwick/54e5b111e5ac908becf1 and your evdev tablet, and paste a screenshot. You can just drag files into the github window, or copy it to your clipboard and press paste when typing.

**Comment by 0ion9** [comment]
Mouse works fine -- no breakage.
I cannot paste a screenshot. Pasting has no effect. Using the 'selecting them' link or dropping a file has the below effect:

![Uploading screenshot_462.png . . .]()

Therefore, I'll post an imgur link as before: http://i.imgur.com/N9PNRv8.png. Indeed the discontinuity is clear.

**Comment by 0ion9** [comment]
Sorry about that. Like my edit says, it was unintentional, 'close and comment' was the only clickable button.

**Comment by achadwick** [comment]
Missing Javascript?

Anyway I think we should add a workaround. Is your tablet a Genious/Huion/Monoprice/UC-Logic/clone by any chance?

Skeleton of the workaround is in c8a84143baefc5b58e8ef9dc33e632a909beaf53 already. I'll adapt it for the ink tool.

**Comment by 0ion9** [comment]
I'm running NoScript, but github is permitted. This was the first time 'Comment' has ever been insensitive, and the sensitivity changed as I was writing my comment + you were doing some things. Not that important, but kind of interesting.

Oh, I obviously forgot to include that detail. Yes, it is -- lsusb says "UC-Logic Technology Corp. Tablet PF1209". Visible branding is Monoprice.

**Comment by achadwick** [comment]
Okay, apologies for the delay. This one's reproducible on Wacom hardware by deinstalling the wacom input module in Xorg and letting evdev handle the input. The commit above seems to make the problem go away for me, please test if you can!

**Comment by 0ion9** [comment]
Yep, works fine :)

**Comment by achadwick** [comment]
Upstream have a workaround for the underlying issue now: https://bugzilla.gnome.org/show_bug.cgi?id=703610
Please test it if you can, and report back to the GTK developers there.
