### ISSUE TITLE
Inking tool: give some feedback about pressure

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#225]
I haven't got a mockup together for this yet, but the idea is to display a larger, different colored circle around the current 'filled black outlined circle' that indicates an ink tool node. Black(unfilled) with white outline, perhaps?

Ultimately I think this could fit into a system for adjustment similar to Synfig's 'ducks', with a third (filled) circle resting over the second, and serving as a pressure adjustment handle.

But this issue is just about what the pressure **display** could look like. We could make up some arbitrary size basis: say, radius 16 for pressure=0.0 and radius 64 for pressure=1.0. We might want to later adapt these to window size, but it seems like enough to start with.

**Comment by achadwick** [comment]
Sorry, but this isn't on the radar. I want to keep the tool's canvas display as uncluttered as possible. The maximum level of feedback I'd consider for this (other than the curve itself!) would be widgets in the options panel[1] when you click a node to select it. Basically for detailed editing of pressure, tilt, and Δ-time.

[1] Or next to the node. But that's really hard.

**Comment by 0ion9** [comment]
Ugh. Well, I can agree with your reasoning. We definitely don't need to show the pressure on everything. Not pleased with the prospect of only being able to **edit** pressure in the options panel, but that is a separate issue( and it might turn out that redrawing is actually faster than tweaking pressure, however frustrating it is)

**Comment by achadwick** [comment]
(I don't *really* want to expose users to raw tilt/time/pressure readings really!)

For a panel or on-canvas thing: what about vertical and horizontal sliders for pressure and delta-time, and some sort of canvas-aligned joystick thing in a circle for the tilt. The layout could be

```
 | 
 |          [tilt]
[P]            \
 ^              \
 ^               ·
 ^ 
 ^ 
 ^ 
 ^ 
   >>>>>>>>>>>>>>>>>>>[ΔT]-------
```

Where the · is supposed to be the centre of the tilt stick's circle. I can't do a circle easily in ASCII-art :D

But yeah. Cluttering up each individual node wouldn't be very [Tufte](https://en.wikipedia.org/wiki/Edward_Tufte)-compliant. We could use one of those newfangled speech-balloon things (GtkPopover) to present any widgets we like close to a _selected_ node once we drop support for gtk 3.10.

**Comment by 0ion9** [comment]
Well, I was picking on Pressure because a) it's very important for inking AFAICS, and b) it can't really be hidden behind 'brush size' or whatever, since the effect of pressure of brush size is not reliable and in some cases brush size is even randomized.  Though I thought raw values were usually avoided anyway, since we get 0..1.0 regardless of whatever scale the tablet internally works on.

Not having a tablet with Tilt, I can't comment on how useful Tilt is for inking.

ΔT controls the knot position, so adjusting it should change the tightness of curves from/to the edited point, I guess. Not sure if we'd need to show that or just redrawing a tighter curve is okay?

Your diagram seems like a good start on an intuitive editing design.
