### ISSUE TITLE
MyPaint from Git master stopped launching

### ISSUE THREAD

**Issue by prokoudine** [mypaint/mypaint#228]
I'm on Fedora 21. A checkout form January 5 worked fine, I've just done a clean checkout, as well as force-updated git submoduile. At build time I get this:

g++ -o lib/mypaintlib_wrap.os -c -Wall -Wno-sign-compare -Wno-write-strings -fopenmp -O3 -Wall -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -DHAVE_GTK3 -Ilib -I/usr/include/json-c -Ibrushlib -Ibrushlib/tests -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pygobject-3.0 -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 lib/mypaintlib_wrap.cc
In file included from /usr/include/python2.7/Python.h:80:0,
                 from lib/mypaintlib_wrap.cc:154:
lib/python_brush.hpp: In member function 'PyObject* PythonBrush::python_stroke_to(Surface*, float, float, float, float, float, double)':
/usr/include/python2.7/object.h:767:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
/usr/include/python2.7/boolobject.h:27:31: note: in expansion of macro 'Py_INCREF'
 #define Py_RETURN_TRUE return Py_INCREF(Py_True), Py_True
                               ^
lib/python_brush.hpp:55:7: note: in expansion of macro 'Py_RETURN_TRUE'
       Py_RETURN_TRUE;
       ^
/usr/include/python2.7/object.h:767:22: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ((PyObject*)(op))->ob_refcnt++)
                      ^
/usr/include/python2.7/boolobject.h:28:32: note: in expansion of macro 'Py_INCREF'
 #define Py_RETURN_FALSE return Py_INCREF(Py_False), Py_False
                                ^
lib/python_brush.hpp:57:7: note: in expansion of macro 'Py_RETURN_FALSE'
       Py_RETURN_FALSE;
       ^

Then, after installing, I get this:

$ mypaint
CRITICAL: mypaint: We are not correctly installed or compiled!
CRITICAL: mypaint: script: '/usr/local/bin/mypaint'
Traceback (most recent call last):
  File "/usr/local/bin/mypaint", line 267, in <module>
    = get_paths()
  File "/usr/local/bin/mypaint", line 190, in get_paths
    from lib import mypaintlib
ImportError: No module named lib

**Comment by iirelu** [comment]
You installed by `sudo scons install`, right?

**Comment by prokoudine** [comment]
I did that, yes :)

**Comment by achadwick** [comment]
@prokoudine Does the problem go away when you don't run from the build tree? If so, I think it's my fault and we need to reverse the blocks at  [mypaint.py:135](https://github.com/mypaint/mypaint/blob/56a86e1e7fb4c132069286a7d4e92353e1e7174d/mypaint.py#L135) and [mypaint.py:142](https://github.com/mypaint/mypaint/blob/56a86e1e7fb4c132069286a7d4e92353e1e7174d/mypaint.py#L142).

Those Python macro warnings during the build are annoying, but all we can do about it is avoid using the convenience macros (which should be fixed upstream to turn off these warnings) or turn off `-Wstrict-aliasing`. They're not relevant to this issue.

**Comment by achadwick** [comment]
Reproduced and fixed. One little warning from the commit comment:

> You'll only see this fix take effect when you update that other installation. Luckily this bug is a super-rare thing that'll probably only bite developers and testers.

**Comment by prokoudine** [comment]
Thank you!
