### ISSUE TITLE
Right-click menu for brushes

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#229]
This is flat-out *needed*, and it's kind of silly how we don't have one yet. Obvious settings include "Delete", "Copy", "Edit", "Favourite", but more things will likely be added later.

**Comment by jy2wong** [comment]
So I'm about halfway done implementing this, but figure I can do some code cleanup here too. Before I start, though, is there a good reason for `QuickBrushChooser`s to avoid using the `BrushList` class, @achadwick ?

**Comment by achadwick** [comment]
@jy2wong I can't see any obvious reason, although anything popped up should be kept as a pure single-click chooser with no menus or fancy features IMO. Fancy features like menus can go on `gui.brushselectionwindow.BrushList`.
