### ISSUE TITLE
Add "New from Visible" action, make "Merge Visible" delete existing visible layers

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#231]
About the short discussion on #230.
I think that is useful both voices, "Merge visible" (deleting all visible layers) and the safe "New from Visible" on the layers menu options.
The current option is equal to "New from Visible", present on GIMP.
Some times I did a bit confusion how to use the merge between GIMP and MyPaint.

**Comment by achadwick** [comment]
Yep. Regarding wording: the terms should both start or end with "visible" too. See also #28 for a general strings review which we need to get done before release.

Though to be clear, this issue is asking for a new layer merge action: same as the existing Merge Visible, but deleting all the previously visible layers instead of leaving them in place.

**Comment by achadwick** [comment]
Might have the bitesize nature too: most of this is already worked out.

**Comment by achadwick** [comment]
This will need the introduction of new strings, so it cannot be done during the beta cycle. Let's either get it done during the alpha phase, or defer it to after the 1.2 release.

**Comment by americogobbo** [comment]
I've tested it now and the behaviour is OK. But is appearing a strange effect with New Layer from Visible: the new visible layer is making some blend operation to reinforce the colour value, is it normal?

1- Screenshot of three layers
![three-layers](https://cloud.githubusercontent.com/assets/8180638/8315980/7b1a49a6-19ca-11e5-83ce-e400abd498fa.png)

2- Screenshot of New layer from Visible - all layers visible
![new-from-visible](https://cloud.githubusercontent.com/assets/8180638/8315994/8d94c886-19ca-11e5-86f4-85ec3fd4b5f2.png)

3- Screenshot of New layer from Visible - only this layer visible
![new from visible - only on](https://cloud.githubusercontent.com/assets/8180638/8316005/9c35676a-19ca-11e5-9e31-9e997c7db726.png)

4- Screenshot of Merge visible layer
![merge-layers](https://cloud.githubusercontent.com/assets/8180638/8316014/aa775edc-19ca-11e5-9b39-f29bdc2c13c4.png)

**Comment by achadwick** [comment]
@americogobbo Please report that as a new issue, and attach your source .ora when you do that.

"New Layer from Visible" is *exactly* the same operation as the old "Merge Visible".
