### ISSUE TITLE
Feature Request: Better Formatted Tooltips

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#235]
As of bebc68e the tooltips are simple one line description of a tool in mypaint. However for tooltips that are longer than 72 characters such as the compositing layer descriptions, the tooltips begin to look out of place and awkward as shown by @iirelu in pull requrest #187 .

@achadwick has an idea on how to format them properly in the same pull request as well.
>If we need more gloss than what we have for the operations, it's possible to use a diagram+title+description tooltip with not much extra coding: similar to what we do for the current tool indicator I think. The layout can look like:
```
>DIAGRAM   TITLE.TITLE.TITLE     ← in bold
>DIAGRAM
>DIAGRAM   DESCRIPTION.DESCRIPTION.DESCRIPTION.DESCR
>DIAGRAM   IPTION.DESCRIPTION.DESCRIPTION
```

>The image/diagram is approx 48x48 px, and it' optional.

For more context and ref pictures, refer to pull request #187 

Edit: Plus I'm guessing this will be more of a post-1.2 feature?

**Comment by achadwick** [comment]
Yeah, sorry about that. Thanks for linking it all up to the relevant commits and issues.

(Large-ish tooltip diagrams for the modes would rock. I wonder what they should show? Maybe the effects on a [W3C Standard Rubber Ducky](http://www.w3.org/TR/compositing-1/#blendingnormal)?)

**Comment by iirelu** [comment]
In my opinion, a graphical representation in the tooltip would be useless as the only point at which the tooltip shows up is when the blend mode is already selected. I think all artists need is a good description to figure things out on their own.

**Comment by jy2wong** [comment]
You can see the tooltip without the blend mode being selected if you go through `Layer > Compositing Mode` in the menu bar.

**Comment by iirelu** [comment]
@jy2wong Do menu bar entries have tooltips usually? They don't on Ubuntu, at least for me.

**Comment by odysseywestra** [comment]
Another thing we probably want to add to the tooltips is to show the shortcut key as well if there is any.

**Comment by odysseywestra** [comment]
I'm closing this feature request and moving it over to the MyPaints Community Fourms [here](http://community.mypaint.org/t/better-formatted-tooltips/299).
