### ISSUE TITLE
Brush changing drop-down looks weird

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#237]
![b](https://cloud.githubusercontent.com/assets/3432543/6508711/4f1dd440-c352-11e4-8797-7f6c9c148fdb.png)

I imagine that bar at the top isn't supposed to be black.

Stock Unity, Ubuntu 14.10.

**Comment by achadwick** [comment]
Does it affect the brush popup on the B key as well?

(Those colour and brush dropdowns are a thing I want to move down to the footer and replace, once I have a replacement up to speed)

**Comment by iirelu** [comment]
No, it doesn't. It's only rendering wrong in that one place.
