### ISSUE TITLE
Locked or invisible layers can be moved (but cursor shows "forbidden" symbol)

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#238]
Layers which are locked, or even invisible, can be moved.
There's an inconsistency between the move cursor and what's actually allowed too:

![Moving a locked layer (in this case, a group layer)](https://cloud.githubusercontent.com/assets/61299/6513423/db72aa0e-c372-11e4-9557-e3e6e6274c5b.gif)

The gif shows a locked group layer being moved, but this applies to any layer which is itself locked (closed padlock icon, :lock:).

Normally users cannot paint to locked or invisible layers, and the cursor will change to reflect this.
IMO, users should not be able to move layers which are locked or invisible either; locked should mean locked, and if you can't see what you're doing, you shouldn't get the opportunity to mess things up.

---------------

Probably unlocked layers inside locked groups should count as locked, the same way that open-eye layers inside closed-eye groups are functionally invisible.

There's another discrepancy there: if a group is invisible (it's eye icon is closed), it's still possible to paint to its open-eye children. Of course, you won't see the changes until you make the group visible again...

**Comment by iirelu** [comment]
Yeah, you shouldn't be able to reposition locked/invisible layers, nor should you be able to modify layers within a locked/invisible layer group.

**Comment by achadwick** [comment]
Okay, I think the closing commit is the right approach.

* Layers which are themselves locked cannot be moved
* Unlocked layers *within* a locked group *can* be moved (that move operation is a move relative to the current layer's parent, and that's OK)
* Layers which are themselves invisible can't be moved.
* Layers marked as visible which are inside invisible layers *also* can't be moved (because they can't be seen, so you'll screw up if you try)
