### ISSUE TITLE
When reordering layers, it doesn't detect a drag until you've moved 100ish pixels

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#240]
![buggy](https://cloud.githubusercontent.com/assets/3432543/6518336/fb81bb08-c39c-11e4-84a2-0b0dc4390654.gif)
It's a little hard to see when mousedown/mouseup happens (that's another awkward thing, it should make the mouse a `grabbing` cursor).

As @jy2wong [describes](https://github.com/mypaint/mypaint/commit/2705b937217761d32687eccc38464fd85f14cebe#commitcomment-10061430):

> [..] there's maybe an 80 pixel square in which nothing appears to happen. This is about a row and a half, so if you have two layers and you're trying to drag the bottom layer over the top layer, nothing appears to happen.

It appears to be non-existent for some, intermittent for others, and occasionally consistent (like with me, the bug always occurs).

Oddly enough, this has persisted even through the layer dragging code rewrite.

**Comment by achadwick** [comment]
Couple of questions for anyone bitten by this one:

* If you run the layers list in self-test mode, does the problem present the same way it does within the app itself? To do that, run:

        $ cd path/to/mypaint-git
        $ PYTHONPATH=. python gui/layers.py

* What's your system default drag-threshold? Whether you're using GNOME or not, please try

        $ gsettings get org.gnome.settings-daemon.peripherals.mouse drag-threshold
        8

  And please let me know if you're running GNOME when this problem presents itself.
  The default is 8, but this problem can be reproduced for `gui.layers` on its own by setting it to 100 on a DE with the GNOME settings daemon running using dconf-editor or whatever.
  It should match what GTK itself sees:

      $ python
      Python 2.7.8 (default, Oct 18 2014, 12:50:18) 
      [GCC 4.9.1] on linux2
      Type "help", "copyright", "credits" or "license" for more information.
      >>> from gi.repository import Gtk
      >>> settings = Gtk.Settings.get_default()
      >>> settings.get_property("gtk-dnd-drag-threshold")
      8
      >>> 

There are a couple of places around the code where we **set** that property, and I'm not happy about doing that.

**Comment by achadwick** [comment]
For me by the way, it kicks in pretty much instantly. About 8 pixels, I guess.

(Word of warning: don't set the GNOME one too high or you'll find that drags in the DE stop working nicely)

**Comment by achadwick** [comment]
On my (GNOME) DE, setting `drag-threshold` of `org.gnome.settings-daemon.peripherals.mouse` high affects `gui/layers.py` run as standalone, but not the app when run from within its source dir. That kinda hints that the problem could be self-inflicted within the main app - but why only for some users and not all?

**Comment by achadwick** [comment]
Ugh, there's initalization order issues too: colour adjusters vs. brush pixbuflists. Changing the order changes the drag threshold subtly (for me). We should probably rip any custom setting of the drag threshold out and just use the system one, wherever it comes from, unless the default values are completely unsound for some folks.

**Comment by iirelu** [comment]
```
> gsettings get org.gnome.settings-daemon.peripherals.mouse drag-threshold
8
```

And yes, layer dragging works just fine when running ./gui/layers.py.

I `git pull`ed after your commit, but it didn't fix the issue. Dragging remains insensitive when running the main Mypaint app.

**Comment by achadwick** [comment]
@iirelu What does the Python snippet say for "gtk-dnd-drag-threshold"? GTK could be getting that setting from some other settings manager.

**Comment by achadwick** [comment]
@iirelu Also, does

```patch
diff --git a/gui/colors/adjbases.py b/gui/colors/adjbases.py
index f7145d2..66204fe 100644
--- a/gui/colors/adjbases.py
+++ b/gui/colors/adjbases.py
@@ -471,7 +471,6 @@ class ColorAdjusterWidget (CachedBgDrawingArea, ColorAdjuster):
 
     SCROLL_DELTA = 0.015  #: Delta for a scroll event
     IS_DRAG_SOURCE = False  #: Set to True to make press+move do a select+drag
-    DRAG_THRESHOLD = 10  #: Drag threshold, in pixels
     _DRAG_COLOR_ID = 1
     _DRAG_TARGETS = [("application/x-color", 0, _DRAG_COLOR_ID)]
     HAS_DETAILS_DIALOG = False  #: Set true for a double-click details dialog
@@ -554,8 +553,6 @@ class ColorAdjusterWidget (CachedBgDrawingArea, ColorAdjuster):
         if self.IS_DRAG_SOURCE:
             self.connect("drag-data-get", self.drag_data_get_cb)
         self.connect("drag-data-received", self.drag_data_received_cb)
-        settings = self.get_settings()
-        settings.set_property("gtk-dnd-drag-threshold", self.DRAG_THRESHOLD)
 
     def _drag_source_set(self):
         targets = [gtk.TargetEntry.new(*e) for e in self._DRAG_TARGETS]
diff --git a/gui/pixbuflist.py b/gui/pixbuflist.py
index 52c748c..6a8e72a 100644
--- a/gui/pixbuflist.py
+++ b/gui/pixbuflist.py
@@ -81,11 +81,6 @@ class PixbufList(gtk.DrawingArea):
                         gdk.PROXIMITY_OUT_MASK |
                         gdk.PROXIMITY_IN_MASK)
 
-        self.get_settings().set_property(
-            "gtk-dnd-drag-threshold",
-            int(min(item_w, item_h) * 0.75)
-        )
-
         self.realized_once = False
         self.connect("realize", self.on_realize)
```

make any difference? For me it makes the main app sensitive to the GNOME settings again.

**Comment by iirelu** [comment]
Does Unity count as Gnome? It's based on it, I believe.
```
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk
>>> settings = Gtk.Settings.get_default()
>>> settings.get_property("gtk-dnd-drag-threshold")
8
>>> 
```

I applied your patch and yes! That works!

**Comment by achadwick** [comment]
Okay, pushed. Could anyone else bitten by this please me know if the problem's fixed?

You may find the brush groups' dnd sensitivity has been changed quit a lot by 6b3a1e7, so if people could please test that the behaviour there is acceptable, that'd be brilliant.

(There's also #142 which might be affected by this. Maybe the dnd code in there should be revisited more generally: it's ancient stuff)

**Comment by jy2wong** [comment]
Before the fix, `PYTHONPATH=. python gui/layers.py` was working great.

```bash
* jy2 >> gsettings get org.gnome.settings-daemon.peripherals.mouse drag-threshold
No such schema 'org.gnome.settings-daemon.peripherals.mouse'
```
```python
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk
>>> settings = Gtk.Settings.get_default()
>>> settings.get_property("gtk-dnd-drag-threshold")
8
```
After the fix, everything is working great (if I had to guess, the area-of-nothing is now consistently a 16 pixel square). Even with `MYPAINT_DEBUG=1`.

(There's a lot of stuff spewed out to stdout by `MYPAINT_DEBUG=1`; I did notice that setting that environment variable made mypaint start up a bit slower. I suspect it affected initialization order of colour adjusters and brush pixbuflists.)

**Comment by achadwick** [comment]
Eight pixels in any direction is probably sensitive enough for the layers list, and <i>in</i>sensitive enough for the brush list. I'm assuming we can call this one closed.

Thanks for the excellent testing and feedback, by the way! It's helped tie down a very tricky to reproduce (and long-standing) bug that would have just annoyed people if we left it.
