### ISSUE TITLE
Feature Request: Single-Window Mode

### ISSUE THREAD

**Issue by martensms** [mypaint/mypaint#245]
Is there a single-window mode still available?
I can't find it anywhere in the settings nor debug menus nor anywhere in the menu.

If not: Please add single-window mode to stable. It's pretty much unusable on multi-monitor setups because GTK decides to randomly spawn all sub windows in different positions (not saved/restored positions of each window).

The only thing related were links to the old issue a guy filed 2010:
https://www.mail-archive.com/mypaint-bugs@gna.org/msg00942.html

**Comment by achadwick** [comment]
Panels are dockable in alpha, and window positions have been saved and restored for ages. Is this what you mean?

**Comment by achadwick** [comment]
Dockable panels have in stable since 1.1 at least. Nothing to do here.

**Comment by thekyriarchy** [comment]
How do you turn the various windows into docked panels? The most I can get is gnome's window-border sticking by dragging a window for their edges to touch...really ugly and a pain
