### ISSUE TITLE
Single finger panning?

### ISSUE THREAD

**Issue by mimimintan** [mypaint/mypaint#246]
Ey, first of all let me say that I can't believe I didn't look at this sooner; I've been looking for a free infinite canvas software with which to doodle, and had given up until I heard someone mention MyPaint. What a gem!

My biggest nitpick, though, is that because I'm on a Surface Pro 3 and don't always have convenient access to a keyboard, it's tough to pan without putting in a lot of unnecessary effort. At first I was using Mischief, which does have this (but I have to be honest, the only thing I like better about it is the fact that it's vector so it's infinite zoom as well)... but it uses two fingers. A lot of drawing programs use two fingers, but I'm used to Manga Studio, where it only takes one. I can take either, but I really just need it implemented somehow, or the infinite canvas kind of loses it's purpose!

Another cool thing would be the ability to make the window transparent, but this is by no means a necessity. :)

**Comment by mimimintan** [comment]
Also, the zooming is a little choppy; not sure if this is intentional or not but it's a little annoying. Not something unbearable, though!

**Comment by tumagonx** [comment]
Does it really matter to press a button while dragging? How MSEX do that? a toggle state between draw/pan?

**Comment by aigleghis** [comment]
I don't know if it works with the surface pro 3 stylus, but on my wacom tablet I mapped the "Scroll View" function to the right click.  It is the button on the side of my stylus.

Go in the Edit -> Preferences menu, under the "Buttons" tab, you can add (or remap) the "Scroll View" binding.  Simply hold the desired button of your stylus over the "Edit binding" dialog to map to it.

**Comment by achadwick** [comment]
It's always a question of where to make the cut.

Sakse Dalum's patch in #204 could net us **two-finger omnidirectional scrolling** for touchpads (or anything delivering smooth scroll events), via a prefs toggle. I don't know if the gesture is the same on touchscreen right now, but I'll see what my XPS13 delivers for its screen when I have a chance.

Touchscreen devices can be distinguished from touchpads, styli, etc. pretty reliably on Linux.

MyPaint git already has a notion of devices being enabled for: everything, nothing, or "non-painting tasks only". "Non-painting tasks only" is a hack to get around accidentally brushing the touchpad on pen-and-touch devices and glitching drawing for configurations where the driver doesn't reliably turn the touchpad off when the stylus is in use, but we could reuse that. Perhaps "clicking and dragging" with Button1 on devices assigned a "non-painting tasks only" usage type could be treated as Button2? That would get us **one-finger panning**, but you might have to turn it on in prefs.

We *could* default touchscreens to "non-painting tasks only", but I'd prefer not to. I want touchscreens to have tablet/phone-like gesture support eventually, and that means finger-painting :D

@mimimintan (or any Surface Pro user) - does a finger on the screen present as a different device to the stylus? Basically, does it have its own associated brush and does _Help→Debug→Test Input Devices_ give it a different name?  I'd appreciate a screengrab of the _Edit→Preferences→Devices_ tab too.

**Comment by achadwick** [comment]
> Another cool thing would be the ability to make the window transparent, but this is by no means a necessity. :)

WONTFIX. Configure your window manager to do this :D

**Comment by achadwick** [comment]
@mimimintan wrote:
> Also, the zooming is a little choppy; not sure if this is intentional or not but it's a little annoying. Not something unbearable, though!

When zooming with a wheel or 2-finger touchPAD gesture, or some other technique?

If it's "scroll event" zooming, the patch in #204 touches it, and I really need to get that fixed up and integrated.

**Comment by mimimintan** [comment]
@achadwick Sorry it took so long to respond! Been working the lame day job, yuck.

The stylus is called "N-Trig DuoSense device Stylus", while the finger is called "Core Pointer". Unfortunately I did not find a "Devices" tab on the preferences window. Is there somewhere else I could find the information that you seek?

**Comment by achadwick** [comment]
@mimimintan It's a thing from the latest development version - you can find unofficial builds at http://opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html courtesy of @tumagonx . There's a picture of it at the bottom of https://github.com/mypaint/mypaint/wiki/FAQ

(My asking for the screengrab was a "just in case" question, no need to upgrade or anything if you have a stable version. Let me know what version it is though please! (Help->About))

**Comment by mimimintan** [comment]
@achadwick Oh my, 1.0.0 apparently. Snap. ©2005-2010 lmao

**Comment by mimimintan** [comment]
Ah, apparently it's not that far behind. Oh well. 

I've never really worked with stuff like this before, so I'm not sure how to implement any "patches" or anything. 

Looking back at the comments and slowly understanding more of them. I guess I understand the desire to finger paint. I'm not sure I understand any of the other explanations (I am not very bright). But essentially, yeah, have a preference that lets one finger slide either paint or pan? For those who plan on drawing exclusively with a stylus. I'm not sure how any of it works or where this conversation is even going. I'm sorry! > __ <
