### ISSUE TITLE
Palette Editor Dialog - Mistakes loading external palettes where name file = name palette

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#251]
When I try select a palette in a different folder, external of mypaint filesystem... if I try load the second palette present on the list of file-manager, it seems, that always is loaded the first palette of the list, it seems a joke :-)
In the dialog it appears always the name of first palette although the was loaded truly the second palette.
If you choose a palette on bottom of the list is loaded... and the name of palette is updated.
This behavior is present only to external folders of mypaint fs.

I've made 2 videos to show it... that is very difficult to understand this behavior:

https://www.youtube.com/watch?v=SO3dG80IPeA
https://www.youtube.com/watch?v=hJv6C3qEnHM

**Comment by americogobbo** [comment]
I understood where is the problem... in certain cases... when you rename the file palette on MyPaint the name inner on the palette is not modified.

**Comment by achadwick** [comment]
Is it just the Name field that's at fault?  I don't think we seed that the the name of any files...

![pal ed](https://cloud.githubusercontent.com/assets/61299/6560174/f1d2bd56-c67f-11e4-9a5b-5449a013fb0f.png)

It's just a name you can fill in. If something else has put something silly (like a file name) in there, there's not much we can do except preserve it.

**Comment by achadwick** [comment]
I checked, and we write "None" in there for the name when you make a new palette with the Clear button above:

```
GIMP Palette
Name: None
#
171 66 66
225 181 68
0 0 0
```

Perhaps we should use a localized `_("Untitled")` string instead. I think that's just Python's `None` (=NULL) value as a string.

And probably the field should be labelled "Title:" to make it clear that it has no relation to the file name.

**Comment by americogobbo** [comment]
OK, is a good precaution!
