### ISSUE TITLE
Color picker awkwardness when invoked via keyboard

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#253]
I have the right arrow on the numpad bound to Color Picker.
Its behaviour has changed undesirably, recently:

* Previously, I could pick up a color just by hovering over what I wanted and hitting KP_6 - the color is instantly picked up.

* Now, I have to first hold (not press) KP_6, then click on a color to pick it up. Further, as soon as I take the pen away, I must then release KP_6 and re-press it in order to pick a color again.

**Comment by iirelu** [comment]
By previously do you mean 1.1.0 or an earlier version? If so, that likely changed a long time ago. I can't seem to produce your second bullet point, though. With ctrl (the default eyedropper button), I can select multiple colours while its still held.

**Comment by 0ion9** [comment]
@iirelu : CTRL+clicking to pick works for me (that is, I can do it. I don't think it's as good as hover picking.).

However, that is a **button** assignment, not a key assignment.
The type of thing I am talking about is a key assignment:

![screenshot_480](https://cloud.githubusercontent.com/assets/115782/6613003/3c21eb40-c8d6-11e4-9db4-676b3574973e.png)

**Comment by achadwick** [comment]
@0ion9 Does it change either side of 8f438497c0767b913649fb5cfdb97545ae769d2a (/guess)? If it's not that, would you mind triaging for a bit to track down where this started - or give us some versions to work with so we can do it ourselves?

That's normally bound to the "R" key. Is the behaviour different with the defaults?

**Comment by 0ion9** [comment]
@achadwick 
* Behaviour is the same with the defaults.
* The parent of 8f43849 does not exhibit the misbehaviour.
* 8f43849 exhibits the misbehaviour

So it's 8f43849, all right.

**Comment by achadwick** [comment]
Reproduced with 08f3cc53133f50eca8d9211d6b267a8d971081c5. Thanks for the report.

**Comment by achadwick** [comment]
Another hopefully quite small task here.

**Comment by achadwick** [comment]
**Triage note:** reproducible, no string changes needed, not super-urgent; bump to the beta phase for fixing.

**Comment by borda-flash** [comment]
I will try on this

**Comment by achadwick** [comment]
@borda-flash Any progress on this?

**Comment by iisupreme** [comment]
Hi @achadwick 

Is the update required to reverse the changes made in 8f43849...

Regards
Val
