### ISSUE TITLE
Wheel axis support

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#26]
Transferred here from [Gna! bug 14694](https://gna.org/bugs/?14694):

> The current release does not support the wacom artpen rotation (have not tried the airbrush but I think that it uses the same value). 
> In xidump it is reported as "wheel". 
> I have searched the code for any use of AXIS_WHEEL but I have not found any so I'll report this to be valid for all versions and all platforms. 
> -- [Emil Assarsson <metabaronen>](https://gna.org/users/metabaronen)

Looking at this again, this seems to refer to the wheel input on devices like the Wacom airbrush ([amazon via ddg](https://duckduckgo.com/?q=!az+Wacom+airbrush)). I have an (Intuos 5) ~~artpen~~ **EDIT: grip pen** myself, but while my tablet presents a wheel axis for the stylus device, the axis value is always the same.

Emil clarifies:

> It should act as an input for the brush engine. It is an extra axis for the input device. It could be used to rotate the brush. 
> Please also note that the same axis is used for the top wheel on the airbrush tool.
> -- [Emil Assarsson <metabaronen>](https://gna.org/users/metabaronen)

Maybe it's the Cintiq pen that supplies rotation information? ([amazon via ddg](https://duckduckgo.com/?q=!az+Cintiq+artpen)). The Amazon blurb says something about rotation being a thing.

**Comment by briend** [comment]
I have a branch of libmypaint and mypaint that add Art-Pen (rotation) support.  Please check it out!  
https://github.com/briend/libmypaint/tree/pen-rotation
https://github.com/briend/mypaint/tree/pen-rotation

**Comment by briend** [comment]
https://community.mypaint.org/t/barrel-rotation-input-support-wip/440/28
