### ISSUE TITLE
line tool shift add curves

### ISSUE THREAD

**Issue by artsnake** [mypaint/mypaint#262]
shift not working to curve straight line. It worked once then quit.
ubuntu 14.04 gnome mypaint 1.1.1  alpha. 20150305+gitexport.ba0649b

**Comment by iirelu** [comment]
Is there any error message? What does it say?

**Comment by achadwick** [comment]
Can't reproduce in Debian testing GNOME with ba0649b. @artsnake how are you trying to curve a straight line? What works for me:

1. Click on the Lines and Curves tool in the toolbar
2. Click and drag to make a straight line
3. Hold down shift and drag to add the first bezier control
4. Hold down shift again and drag near the other end of the line to add the second bezier control
5. Repeat as often as needed to change the two control points

It all works fine for me, and the app doesn't quit. Also the curving facility doesn't quit working. Did you mean something else?

**Comment by artsnake** [comment]
The curve facility stopped working after the first  try with the new up grade. It did not work with the last alpha as well. 
In line and curves mode, shift constrains line angle like ctrl key. it dose the same in connected line mode as well.
In freehand as well as ellipses and circles mode shift works properly.
Here is the terminal out put 
$ mypaint
INFO: mypaint: Using the old-style configuration area found in u'/home/pogo/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOMEand $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
INFO: gui.application: Initialized background from u'/home/pogo/.mypaint/backgrounds/default.png'

(mypaint:6019): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendMode'
WARNING: gui.workspace: Empty tab group in workspace, not added
INFO: gui.layers: initial drag source target list: <GtkTargetList at 0x225d970>
INFO: gui.layers: initial drag dest target list: <GtkTargetList at 0x225d880>
WARNING: gui.workspace: Empty tab group in workspace, not added
INFO: lib.document: Using u'load_ora' to load u'/home/pogo/.mypaint/scratchpads/autosave.ora' (kwargs={'feedback_cb': <function gtk_main_tick at 0x7f72933950c8>})
INFO: lib.document: load_ora: u'/home/pogo/.mypaint/scratchpads/autosave.ora'
ERROR: lib.layer.group: Could not load any layer, document is empty.
INFO: lib.layer.group: Adding an empty painting layer
INFO: lib.document: 0.008s load_ora total
INFO: gui.filehandling: Loaded scratchpad from u'/home/pogo/.mypaint/scratchpads/autosave.ora'
WARNING: gui.freehand: Add motion event compression workaround: using evhack filter (<TiledDrawWidget object at 0x7f72925c6730 (TiledDrawWidget at 0x184c610)>, <gui.freehand.FreehandMode object at 0x7f7290a941d0>)

(mypaint:6019): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
WARNING: gui.freehand: Remove motion event compression workaround: removing evhack filter (<TiledDrawWidget object at 0x7f72925c6730 (TiledDrawWidget at 0x184c610)>, <gui.freehand.FreehandMode object at 0x7f7290a941d0>)
^C

**Comment by achadwick** [comment]
Reproduced in 08f3cc53133f50eca8d9211d6b267a8d971081c5:

1. Run mypaint with a fresh config: `./mypaint -c /tmp/cfgtmp$$`
2. WITHOUT pressing any modifier keys, click on the Lines and Curves tool in the toolbar
3. Click and drag to draw a line.
4. WITH shift held, try and adjust the curvature of the line you just drew by clicking and dragging

Expected: curvature of the line previously drawn is tweaked (it's a Bezier thing now)

Result: a new line is drawn, with constrained angles.

**Comment by achadwick** [comment]
Bisected; 153eeb72464171da29a2b9092cfbb82cdd5ca6ca is the first bad commit.

**Comment by achadwick** [comment]
Should be fixed in development now; I'll push out a new PPA build when I get a chance later today.
