### ISSUE TITLE
Cant generate POT file

### ISSUE THREAD

**Issue by prescott66** [mypaint/mypaint#270]
after executing command "scons translate=pot" in root git folder i get this output:

scons: Reading SConscript files ...
building for 'python2.7' (use scons python_binary=xxx to change)
using 'python2.7-config' (use scons python_config=xxx to change)
Delete(["libmypaint-tests.so", "libmypaint-tests.so", "libmypaint.so", "libmypaintlib.so", "libmypaint.a", "libmypaint-tests.a", "lib/_mypaintlib.so"])
Enabling i18n for brushlib in full application build

scons: warning: Ignoring missing SConscript 'brushlib/SConscript'
File "/home/dusan/Plocha/mypaint/SConstruct", line 214, in <module>

----------------------------------------------------------------------

Missing submodule "brushlib"

Please run "git submodule update --init" to create it. See the README
for more information.

----------------------------------------------------------------------

...and no POT file is generated.

**Comment by prescott66** [comment]
"git submodule update --init" fixed it after i clone mypaint from git again. i have downloaded ZIP from github. closing issue

**Comment by achadwick** [comment]
You need to run the command indicated first, namely

```
$ git submodule update --init
```

Let's fix up the docs in `po/` to make this clearer.

**Comment by achadwick** [comment]
Sorry, think my comment crossed yours. But I think the docs should be updated just in case someone with a zip download reads *only* `po/README.md`.
