### ISSUE TITLE
Eyedropper tool doesn't work on the scratchpad

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#272]
Version: MyPaint 32-bit 1.1.1-alpha.20150319+git.4d5bd9b
Windows 8, 64-bit
It used to, but now it doesn't. Using the keyboard shortcut or clicking the eyedropper tool and trying to select the color doesn't work.

**Comment by artsnake** [comment]
There are two eyedropper shortcuts one using the R key to select what the cursor is hovering over. The other uses the ctrl key plus the touch of the pen on a tablet or mouse click.
On my Ubuntu 14.04 box the ctrl plus click works on the scratchpad. The R key does not. 
I think that works just fine.

**Comment by iirelu** [comment]
Still a bug, though.

**Comment by jplloyd** [comment]
This was fixed by the 1.2 release (at the latest). Tested on Win7, 10 and Ubuntu.
