### ISSUE TITLE
Replace global pressure mapping with better UI? (decided: no, just document it)

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#275]
Extracting this TODO from the [comment in gui/application.py](https://github.com/mypaint/mypaint/blob/ec20e767cd898d82b51374fcf1f35e271c907116/gui/application.py#L569) just so I can get rid of a link to the old wiki in the program text.

```python
# TODO: maybe replace this stupid mapping by a hard<-->soft slider?
#       But then we would also need a "minimum pressure" setting,
#       or else this often used workaround is no longer possible:
#       http://wiki.mypaint.info/File:Pressure_workaround.png
```

The image of what needs to be replaced, and the workaround in question:

![The `Pressure_workaround.png` from the comment. Essentially it makes MyPaint treat non-zero but low-pressure inputs as zero-pressure](https://cloud.githubusercontent.com/assets/61299/6882643/7a0b608e-d584-11e4-85f8-221c226878d0.png)

Need to decide if this idea is still relevant or helpful with modern hardware. What was this pressure workaround used for originally?

**Comment by AtsusaKaneytza** [comment]
That's a workaround I used for when my tablet pen would make strokes before the tip of it even touched the tablet surface. I think it's still a nice tip for those that are experiencing similar issues.

**Comment by achadwick** [comment]
Weird. It's something we should document if that's still useful.

@AtsusaKaneytza what device is/was this, and what MyPaint version? Does it still happen with the most recent alpha version you've tested on the same hardware?

**Comment by iirelu** [comment]
I get the same sort of problem, but that's because my tablet is ancient and the nib is gunked up with stuff that means it's always a little depressed.

**Comment by achadwick** [comment]
I think we should keep the feature here, and just document the kinds of things the prefs mapping can be used for. Next actions:

* [ ] Code: remove comment about this needing removal. It doesn't.
* [ ] Document in the wiki, on its own manual page.
  * Code: optional: help button in the GUI pointing at the wiki explanation?

**Comment by iisupreme** [comment]
Hello, My name is Val I'm new to open source, git, Python etc. I found your project which looks very interesting and would like to assist if possible.

Thanks

**Comment by achadwick** [comment]
Hi @iisupreme , thanks for your interest!

Do you have MyPaint built from source yet? That's a big help for documentation, and pretty much necessary for any development work. A word of warning: Linux is currently the best supported platform. Windows support is getting a lot better now, but there are rough edges. Mac OS X may have wrinkles, and is the least tested platform (I have no access to a Mac).

For the wiki documentation aspects, anyone with a github account can just edit. The starting place for writing docs for the new release is <https://github.com/mypaint/mypaint/wiki/v1.2-User-Manual>, and its "Edit" button :pencil2:. You'll be using a language called "Markdown", documented at <https://guides.github.com/features/mastering-markdown/>. This task is going to need a page about the global pressure mapping curve, probably located under a page about the preferences dialog itself.

The coding aspects of this one are probably fairly trivial - comment removal!

Getting the code, and advanced work on the wiki docs needs "git" knowledge. It's probably best you read through Github's own docs on the subject (I'm just the MyPaint maintainer). They're at <https://help.github.com/categories/bootcamp/>, and that looks like a great place to get started generally actually.

I hope that's helpful information to get started with.

**Comment by iisupreme** [comment]
Hi @achadwick , 

Thanks for all the resource links, I'll start on those.

I've not built MyPaint yet, I currently on a Windows OS so will try the build on there (understanding there are some rough bits), if that's not successful I will look into getting a Linux environment setup.  

Will get back to you soon if there are any questions.

Val

**Comment by iisupreme** [comment]
Hi @achadwick 
Having some challenges building MyPaint on Windows, should I post errors here or to the MyPaint user forum.

Thanks 

Val

**Comment by AtsusaKaneytza** [comment]
@achadwick (oop this response is overdue, sorry) It was a fix for a Monoprice 4x3" Graphics Tablet. In my experience with them, it was a problem with the standard pen that comes with the tablet, for whatever reason. Never been an issue for replacement pens.

**Comment by achadwick** [comment]
@iisupreme If it's a problem using MSYS2, I may be able to help out over there. Drop it into http://forum.intilinux.com/mypaint-development-and-suggestions/ I guess, and link me to it.

(The MSYS2 folks hang out on IRC: `#msys2` on OFTC. In my experience they're pretty helpful people)

**Comment by iisupreme** [comment]
@achadwick 

Ok thanks, actually placed it in the General Discussion forum - Topic 'Windows 8.1 Install Help please", can I move it to the forum you suggested, if so how.

In the meantime I'll hop on IRC to see if I can get some more assistance there.

**Comment by iisupreme** [comment]
Hi @achadwick 

I created a local wiki page to document the pressure around, can you review and provide feedback.

https://github.com/iisupreme/mypaint/wiki/v1.2-Global-Pressure-Mapping-Pressure-workaround

Regards

Val

**Comment by achadwick** [comment]
Hi @iisupreme - your wiki fork and the screenshots especially look good, if you like I can just merge that.

One technical note: you write 

> For devices where the pen makes brush strokes before the tip of the pen touches the device surface, the input pressure on the Global Pressure Mapping preference can be set to 0.5 to lower the pressure threshold of the pen.

but the graphs don't actually show that. What the GPM preference is being used for in this instance is increasing the minimum pressure for making a stroke, i.e. increasing the amount you need to physically press down for MyPaint to begin recording >0 pressure internally. Greater input pressures than that are remapped linearly so that there's no big cut-off.

I'd drop any references to 0.5 pressure - that's a value that's only magical for the mouse (mouse devices send no pressure information, so we use 0.5 for them. I think the invented 0.5 is affected by the G.P.M. pref. nevertheless, but it's not a very relevant setting for computer mice).

We should probably recommend that users don't change this setting unless their hardware makes it necessary - if they do, then other users' brush collections may not work for them very well.

**Comment by iisupreme** [comment]
Hi @achadwick  - thanks for the feedback, I have updated the wiki page based on it.

Please review and if it covers what is required, then it can be merged.

Regards

**Comment by achadwick** [comment]
@iisupreme Thanks - looks good. Merged.
