### ISSUE TITLE
Lock brush size to zoom

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#289]
I have just discovered this feature in Gimp 2.9, and TBH it is of extreme utility when painting. It allows a very natural 'iterative refinement' process with no need to repeatedly ask the application to change brush size as you go between the broad strokes and the detailing.

What it does, is:
- Interpret brush size values as 'values at 100% zoom'. Let's take an example brush size of 100.
- Supposing you zoom to 300%; Then, the effective brush size becomes (100 / (1/3)) == 33.33
- Then you zoom out to 50%: the effective brush size is now (100 \* (2/1)) == 200
- So the onscreen size of the brush remains constant, meaning that the size relative to the image shrinks as you zoom in, and expands as you zoom out
- Brush sizes shown in settings do not change; when brush size is locked to zoom, the brush sizes shown are always the sizes that would be used at 100% zoom.

(brush sizes listed above are linear, not logarithmic, for simplicities sake; But of course the scaling is also a linear one.)

I believe there is no major obstacle to implementing this in MyPaint, after the 1.2 release. MyPaint's brush system is somewhat more complex than GIMP's, so what would work best probably needs a little discussion.
My initial impression is that, past the 'obvious first step' of scaling the base radius value, we should also scale the values found in curves that relate to spatial qualities (radius, tracking noise, offset).
This appears to be pretty much the same thing that GIMP is doing.

Here's an example I painted with GIMP pencil tool and no modification of brush size:

![gimp-autobrushscale-cliffs](https://cloud.githubusercontent.com/assets/115782/7080924/2b0d9b4c-df79-11e4-9d67-8992f1120839.png)

I think it adequately demonstrates the value of this option.

I guess in MyPaint's framework, this would be part of a brush (but it would be important to be able to override it globally too IMO -- freehand tool options?)

**Comment by iirelu** [comment]
Technically it would be simple to implement, but I'd want to give it more thought than "stick it in some menu option", so lets think of something once 1.2's done.

Looks pretty cool, though!

**Comment by 0ion9** [comment]
Indeed, the UI is the hardest part. Though as a first step, it makes sense to consider it as part of brush data, as some brushes make sense to scale in this way and others do not (for example IIRC there is a 1px 'detailing' brush); whatever additional UI affordances we might add afterward, I'm fairly confident that it is correct to add it to brush data in the 'Basic' section.

One issue that may be relevant is 'scaling down beyond meaningfulness'. GIMP clamps static brush scaling so that a brush cannot be <1x1px in size. This is just the base scale -- dynamics can make it smaller. Is it meaningful and non-intrusive to do this for MyPaint? Clearly this is relevant when your base brush scale is being automatically reduced as you zoom in.

In terms of how the setting may be expressed, It seems logical to consider the possibility of using a scalar value (like Pixel Feather) rather than a threshold (like Eraser, Colorize). This could express the strength of the scaling, with 0.0 being no scaling (effective brush scale remains constant), 1.0 being the scaling I described above, 0.5 being half as much scaling, 2.0 being twice as much scaling. Even if we ultimately decide that having it work as a scalar is not useful, this would be a useful tool for experimenting to see what behaviours *are* useful.

**Comment by achadwick** [comment]
I'd call it something like "Scale Radius by Zoom" or somesuch.

Like the idea of it being an effect multiplier.

Don't like the idea of pushing the viewport zoom down into the brush engine much. Perhaps it's more of a [BrushModifier](https://github.com/mypaint/mypaint/blob/2170164521c3a86bbded6df968653654f1b7f2de/gui/brushmodifier.py) thing?

It would make sense to have it available in the common panel options for line and freehand modes.

**Comment by kaerhon** [comment]
UI-wise, from a user point of view, i think the best would be a checkbox in brush tool docker. i don't know what it needs as i don't know anything about code structure or code itself, but it could be nice to have it with a quick access like the "size, opaque,sharp,gain,smooth", saved for each brush, but easy to mark/unmark

**Comment by iirelu** [comment]
> UI-wise, from a user point of view, i think the best would be a checkbox in brush tool docker

Haha, I was just about to write that. Checkbox that, when ticked, locks the brush to its current size relative to the viewport, and then when unticked goes back to normal.

**Comment by 0ion9** [comment]
@achadwick 
Honestly, I hadn't even considered the possibility it could be anything -but- a BrushModifier (which is why I was very clear about including the setting in the brush data)

It's a little confusing logistically in the sense that it would be a modifier that sets a property that itself modifies the brush that is ultimately used.
Yeah, AFAICS there is no reason that brushlib should have any special interaction with it. It should just result in an indirection so that the brush we pass to brushlib is a modified version of the one showing in the UI. 
(which, I guess, is a point -against- including it in brush data? But it does make sense to turn it on for certain brush types (painting and modelling) and off for others (precision drawing, perhaps inking).).

"Scale Radius by Zoom" seems good and suitably mypaint-ish.

@kaerhon @iirelu : sounds like we are in agreement, at least on that.

**Comment by crydalch** [comment]
In Mischief it's a toggle in the preferences, but I wouldn't mind having it in the toolbar.

**Comment by briend** [comment]
This might fit the bill:
https://github.com/mypaint/libmypaint/pull/70
You can map a 1:1 zoom to brush ratio really easily-- or create interesting non-linear mappings or even square off the graph to create zoom-zones and a handful of brush sizes.  After all, in real life you wouldn't have 10,000 brushes, you'd have maybe 6 or so and switch between them as you "zoom" in on your painting.

**Comment by briend** [comment]
Master now has zoom % as an Input so you can map zoom to brush size somewhat intuitively.  Try -4.15 and that should be pretty close. Or make stair-stepped curve to have "zones" with different sizes.
