### ISSUE TITLE
Broken lines with devices that use the evdev driver (UC-Logic-based, Monoprice, Genius... and Wacom!)

### ISSUE THREAD

**Issue by Marand-** [mypaint/mypaint#29]
(Migration of [gna bug 20883](https://gna.org/bugs/?20883))

MyPaint is currently unusable when using the evdev xorg driver due to the strokes breaking up frequently.  Known to affect multiple UC-Logic devices from multiple vendors, including Monoprice, Huion, and whatever device [this forum user](http://forum.intilinux.com/mypaint-help-and-tips/broken-lines-when-drawing-with-pen-tablet/msg12883/#msg12883) was using. (Probably a Genius-branded one, according to digimend.)  May affect other evdev-using devices, but uc-logic devices are more common than others.

Non-wacom devices are becoming more prevalent, especially with the recent proliferation of affordable Cintiq alternatives, and everyone but wacom seems to be standardised on using evdev, so this is a fairly nasty issue.  Gtk2 apps such as Gimp, Inkscape, and older builds of MyPaint work with the evdev driver.  Krita 2.8 and newer works as well.

Some devices can use the xorg wacom driver as a workaround, but this isn't a proper fix.  Doing so means access to some xinput settings are lost, such as calibration ("evdev axis calibration"), which is useful for tablet display devices such as the ones by Monoprice and Huion.

The poster of the original port provided a couple sample videos and log information:

Video of the behaviour in MyPaint: https://www.youtube.com/watch?v=MnNbCo2dWlk
Video of testinput + console output: https://www.youtube.com/watch?v=L_Iqs-bGWaI
Log of "xinput test" and screenshot of image made during test: [log](https://gna.org/support/download.php?file_id=18179), [image](https://gna.org/support/download.php?file_id=18180)

My device (Monoprice 19" pen display) has the same input problem and "xinput test" produces the same gaps, though in my case the gaps are more frequent and more pronounced.

He also opened a bug report against gtk3 to get help, but nothing was resolved there.  Someone indicated that a difference in evdev and wacom driver's behaviour regarding coordinate reporting may be at fault, but that the behaviour difference itself isn't a bug.  ref.: https://bugzilla.gnome.org/show_bug.cgi?id=703610

Affects all version of gtk3 + git-mypaint tested so far.  He tested gtk 3.6.2, 3.6.4, 3.8.2; I tested 3.10.7, 3.12.0, 3.12.2.

**Comment by achadwick** [comment]
Upstream have a workaround for this issue now: https://bugzilla.gnome.org/show_bug.cgi?id=703610
Please test it if you can, and report back to the GTK developers there.
