### ISSUE TITLE
MyPaint won't Open

### ISSUE THREAD

**Issue by alexleiii** [mypaint/mypaint#294]
I downloaded MyPaint 1.0.0 around December when I registered my tablet. For months it has worked just fine. Last week I  had MyPaint opened without closing the program or shutting down my computer for 5 days. When I saved and closed the program everything seemed fine, but a few days later when I tried to open MyPaint, it would sit there loading for a a bit while nothing happened. I've uninstalled and reinstalled both MyPaint for Windows 32-bit and 64-bit. I downloaded the version from winPenPack and was able to open it (with X-MyPaint as the title) for a day, but when I tried to open it a second time I received several types of error messages including that there was no file or location.

**Comment by iirelu** [comment]
1.0.0 is a suuuuper old version! We won't really be able to help with that, sorry!
