### ISSUE TITLE
Symmetry Axis Feedback

### ISSUE THREAD

**Issue by whitetree** [mypaint/mypaint#295]
The symmetry system has had a great overhaul - but it appears this old option is missing. View - Feedback - Symmetry axis.  Sometimes it can be hard to see what you are doing with this line in the way. Does the new adjustable line allow it to be turned on and off while still mirroring strokes?
![axis](https://cloud.githubusercontent.com/assets/8498592/7217498/268507c8-e626-11e4-9289-3110d3480d23.png)

**Comment by achadwick** [comment]
The new system doesn't allow this, sorry.

I don't consider it helpful to have some state active, but to have absolutely no feedback on screen about it. However I'm not very keen on the style of the line, admittedly, and I'd welcome patches or mockups for what to do with it in its non-editable state.

Please note: the issue tracker is for reporting defects and proposing changes, not for general discussion threads. There's nothing here to take forward yet. If you have a concrete UI suggestion with a mockup or a patch, please add that to this issue or make a new one referencing this one.

--------------

**Triage note:** no patch, no mockup, only a question about behaviour so far. Please close after two weeks if nothing's forthcoming.

**Comment by whitetree** [comment]
I believe it was a great feature that should stay - Perhaps when Symmetry feedback is turned off, it only shows the beginning/end of line or greatly diminishes the line. 
I often work on dark backdrops and the 2px stark white dotted line is very distracting. Limiting to one pixel, with possibly opacity and layer blending like exclusion or difference or invert so it shows up even across color changes. 

![post](https://cloud.githubusercontent.com/assets/8498592/7335194/5d621314-eba6-11e4-82c2-b1f79415e107.png)

**Comment by kaerhon** [comment]
yeah, a thinner line would be better, as it is a bit too fat now. 
Maybe some erase/move button less easy to click on, to avoid erasing/moving it by mistake? maybe toggle the button's display in the toolbox on the right, allowing it to be moved only when needed

**Comment by achadwick** [comment]
Okay, suggestions taken on board. I'll need to see what Cairo can do in this case.

If we add a setting for it, it will need a new string. Moved to alpha...

**Comment by achadwick** [comment]
Done, but I don't want to fiddle with the trash button's opacity. Those aren't permanently on-screen, and in particular they can't be seen while painting.

![Symmetry editor, as modified by the closing commit.](https://cloud.githubusercontent.com/assets/61299/8379315/1088aac0-1c17-11e5-9df8-d6186db46bf8.png)

Set the alpha to zero if you really really want to be unable to see the axis while you're painting.

**Comment by achadwick** [comment]
(XOR was not possible, sorry. But opacity setting is easy and effective.)
