### ISSUE TITLE
Deleting a layer should shift focus to the layer above, not the topmost layer

### ISSUE THREAD

**Issue by Griatch** [mypaint/mypaint#297]
When deleting a layer, the currently active layer is switched to be the *topmost* layer. This is illogical when for example wanting to delete multiple layers in a row - I would expect to end up on the layer *above* the deleted one instead. This way you could click again and keep removing topmost layers from that point.

When having a long enough layer-list to have to scroll, this becomes even more annoying as every layer-deletion will cause you to jump to the top and you thus have to scroll back down again to find where you were. 

This is using latest GIT version on Linux Mint (with KDE).

**Comment by achadwick** [comment]
Specific MyPaint version and OS version please?

What sequence of actions are you using?

**Comment by Griatch** [comment]
This is GIT version of MyPaint pulled yesterday (will check specific ref when I get back to that computer), but I've seen this behavior for quite some time. As for Specific OS version, this is Linux Mint 17 with KDE desktop. 

Sequence of actions: 
1. Create a bunch of layers. Optionally make the list longer than the window is tall (so you need to scroll to get to the top). 
2. Select a layer further down in the stack and click the "-" button to delete it. 
3. The layer is deleted and I am now on the topmost layer in the stack. If scrolled down, the window scrolls up to the top.

**Comment by achadwick** [comment]
Weird. This isn't happening for me with git master at 0b3067fcb29312135aa14d8e90076611cc2b3f01 (Apr 21). I click "-", and the layer *below* the deleted layer is selected (which seems sensible behaviour). Not the top one in the stack.

* How are you creating the layers? Keys or clicks?
* How are you selecting the layer fuirther down the stack? Keys or click?
   - same behaviour with Shift+Delete as with the "-" button in the layers window
* Can this be reproduced with a flat layer structure, or do you have to nest layers to show the bug up?

**Comment by achadwick** [comment]
Cannot reproduce with 0b3067fcb29312135aa14d8e90076611cc2b3f01 , a fresh MyPaint confign, and  a fresh Linux Mint 7.1 KDE VM with all the default themes and KDE settings.

I can't reproduce this by deleting layers using the keyboard, or by clicking the "-" button in the layers panel: all that happens is that the layer below the current layer becomes the new selected layer.

@Griatch 

* **What version of GTK3 are you using?**
* **Are you using any other theme than the default Linux Mint one?**
* **Please provide more detailed instructions telling me how to reproduce this issue on my screen**
  * How are you creating the layers? Keyboard, menu, or clicking in the panel?
  * How are you selecting the layer further down the stack? Keyboard, menu, or clicking in the panel?
* Can this be reproduced with a flat layer structure, or **do you have to nest layers to show the bug up?**

**Comment by Griatch** [comment]
@achadwick 

You know, this has turned up multiple times for me during working on a larger image; to the point of being actively annoyed by it. But when sitting with 0b3067f and an empty image and trying to reproduce this by creating/deleting layers over and over, I cannot. Maybe there is some other condition required that I've not noticed. 

So I'll have to get back to you on this when I can reproduce it properly.  I'm taking the freedom to close this issue in the interim. Sorry for the trouble!

**Comment by achadwick** [comment]
No problem, thanks for the report even if it's being elusive - it gives people something to search for :+1:  

If this glitch only presents with larger images, that's a useful pointer to where the problem might originate from.
