### ISSUE TITLE
Incompatible Overlay mode in MyPaint vs GIMP

### ISSUE THREAD

**Issue by Griatch** [mypaint/mypaint#300]
MyPaint's Overlay layer is not compatible with the GIMP equivalent. Now, I don't recall if this is one of those famous cases where GIMP "does it wrong" but the fact remains that this inconsistency makes exporting/importing certain images back and forth between the two programs useless. 

The example file is two layers large. The topmost layer is in Overlay mode. In Gimp, cloning to an overload-mode layer is one way for cloning texture onto a flat surface. 

First, how this looks in GIMP 2.8.10 at 100% opacity:
![comparing_overlay_gimp1](https://cloud.githubusercontent.com/assets/294267/7280570/f2283fbc-e923-11e4-9083-21d067b88c57.png)

Next, we let GIMP save this as an .ORA file which is opened in MyPaint (rev 0b3067f) : 
![comparing_overlay_gimp2](https://cloud.githubusercontent.com/assets/294267/7280606/2b666484-e924-11e4-913a-a190a9efc536.png)

Mypaint is doing something completely different than GIMP for its overlay. 

This may be an issue with GIMP rather than MyPaint but if GIMP's Overlay layer is actually something else than it should be then I would like to know what MyPaint could use in its place in order to represent the GIMP image exactly.

**Comment by achadwick** [comment]
We're doing whatever's specified in the [OpenRaster specification](https://wiki.freedesktop.org/www/Specifications/OpenRaster/Draft/LayersStack/) for `svg:overlay`.

This is *probably* a GIMP issue. What does Krita do?

**Comment by achadwick** [comment]
You could collapse the two layers in GIMP into a single Normal layer, and load that into MyPaint. Not the greatest solution, admittedly, but if you're up against a deadline...

I'll consider this a bug in MyPaint if it can be demonstrated that we're doing the wrong thing w.r.t. the w3c definition. If GIMP is doing something other than the w3c definition of "overlay" and saving it to OpenRaster as "svg:overlay", it is GIMP that is in error.

**Comment by Griatch** [comment]
Krita produces the same look from this file as does MyPaint. So I presume this is an issue in GIMP then. 

But just to weed out all the possible causes ...  who maintains the GIMP .ora save/load mechanism? I remember this being a GIMP plugin supplied by mypaint developers at one point. Or is this now handled fully by the GIMP project?

**Comment by Griatch** [comment]
And yes, collapsing the layers is what I've been doing. It is, needless to say, not ideal as a workaround unless for the very last step of the process when the image is to be flattened anyway.

**Comment by martinxyz** [comment]
Probably needs to to be fixed in GIMP's ORA plugin. Famous GIMP bug: https://bugzilla.gnome.org/show_bug.cgi?id=162395

**Comment by achadwick** [comment]
Closing - not us. Though this should be reported to the GIMP ORA maintainers.

**Comment by martinxyz** [comment]
Active GIMP bug: https://bugzilla.gnome.org/show_bug.cgi?id=673501

**Comment by Griatch** [comment]
@martinxyz 

Thanks for that, saves me the time to go dig up my bugzilla password. :smile: 
.
Griatch
