### ISSUE TITLE
Speed management for "Line & Curve" tool could be better

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#301]
This is using a brush where size is tied to speed. It displays vast incongruities between the 'straight line' and 'curved' versions.

![screenshot_498](https://cloud.githubusercontent.com/assets/115782/7333253/94a859e0-eba7-11e4-8d4e-59b0ca7cb6ab.png)

Even making the line very slightly curved using shift is enough to display this.

To me, this suggests that the time values used  in rendering the curve are inappropriate: at least, I'd propose that it is both possible and desirable to make the linear and curved renderings match closely in general appearance.

MyPaint version: Current git HEAD, ie commit 52a7a61

**Comment by achadwick** [comment]
Which line tool is this?

What version of MyPaint is this?

**Comment by 0ion9** [comment]
Not sure what notifications will fire from my edits of the OP, so, FWIW the version is current HEAD ( 52a7a61 )

Connected Lines does it too (which appears even more strange, since that makes a continuous line that swaps big -> small whenever we switch from straight segment to curved segment.)

Ink doesn't do it .. well, sort of. The size doesn't switch, it is consistent with the sizes used by curved segments in L+C / connected lines tools. Given the way ink tool works, the 'curved' rendering is probably the 'correct' one and it is the straight segments that have wrong speed metrics.

Ellipse, too, is consistent with curved segments in L+C and connected lines tools.

**Comment by achadwick** [comment]
Thanks for the revision marker.

What brush are you using there? Can you paste it here so I can examine it please?
Also, are you using any particular pressure variation curve (options panel → Pressure variation...) for the tool?

The Inking tool basically uses real time values, so it should be really close to the equivalent freehand stroke. It's newer code with an independent history, whereas Lines and Curves has accumulated some bodges over time to cope with API changes...

Speaking of which, is this a regression? Does 1.1.0 do the same thing, or has this always been here?

(Thanks in advance for answering all these questions!)

**Comment by 0ion9** [comment]
Brush file: https://bpaste.net/raw/1c09dbe64286
I -think- it's a simple modification of one of deevad's modelling brushes, to be hard-edged.

Pressure variation is just a straight 100% all the way across.

Wait.. Hmm.

**PEBCAK error**. I'm running with various mostly-trivial patches (palette cell max size, color history size, slight change in zoom levels, pixelation threshold) but forgot I was also running with my experimental armature-drawing patch. After taking that out, everything looks normal (curves match lines in sizes) . Sorry for the churn, closing.
