### ISSUE TITLE
Review and clear out unused icons

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#306]
There are still huge numbers of old Tango-style icons which are basically unused in desktop/icons/. Let's review what's needed and have a cleanout of anything that's fallen out of use.

**Comment by borda-flash** [comment]
Hey there, my name is Mukul, I am new to Open source contribution, I know python,javascript and C, this is my first work, please Help

my first question,
1. How find unused icons
>What I think, I have to run mypaint and check which are icons are not being used from some directory which contains all icon!
am I right??

**Comment by achadwick** [comment]
@borda-flash Hi there! Just to give me an idea, how familiar are you with source control, and the Git source control program specifically? If you're very new indeed, https://help.github.com/ and the "Bootcamp" section looks like a great place to start!

> 1. How find unused icons

You've already identified the right folder.

Searching though the source code for mentions (or more usefully, a lack of any mentions) of the files you find is how I'd do it.

For this problem, you only need to look for the last bit without its extension (`.png`, `.svg`). So if you want to see if the icon named (deep breath...)

```desktop/icons/hicolor/48x48/actions/mypaint-brush-mods-inactive.png```

is being used, you only need to look for `mypaint-brush-mods-inactive`.

In Linux, I'd use a tool called [grep](http://man.cx/grep) to look for mentions in recursive mode, but you don't have to do it that way.

> What I think, I have to run mypaint and check which are icons are not being used from "desktop/icons/" directory! and delete them in directory!!
> am I right??

This is basically right ☺

However not only do you have to delete the unused files, you need to publish those deletions, which is where knowledge of Git comes in. Unfortunately you pretty much *have* to use Git to publish the fact that a file should be deleted, which makes this bitesize task actually a bit bigger than it may look at first glance. If you don't fancy learning Git right away, tasks like a simple change of a single file may be more approachable.

Hope that's useful.

**Comment by borda-flash** [comment]
I am little but familiar with source control and Git, btw I already cloned the source and running mypaint build.

Description you provided is very helpful, I am on it.

**Comment by borda-flash** [comment]
@achadwick , almost done, got one more question
There are some exact same icon but of different sizes like 
>desktop/icons/hicolor/16x16/actions/mypaint-tool-color-palette.png
and
>desktop/icons/hicolor/24x24/actions/mypaint-tool-color-palette.png

Deleting the 16x16 one is affecting mine "mypaint" but deleting 24x24 dosent made any difference, does this thing will be same globally or I should keep those 24x24 icons too?

**Comment by achadwick** [comment]
Sorry, I *just* missed you (github is telling me "4 hours ago" for that comment, GB time here (currently UTC+1)).

FreeDesktop.org icons come in sized sets, so if you get rid of a 16x16 one, you should also get rid of the "scalable", "24x24" etc. versions having the same prefix. Scalable ones are .svg, pixel sizes are normally .png.

The `git commit` command will work from anywhere within your mypaint clone, and it'll do the same thing from anywhere. When you have a local commit, push it to a repo on github or somewhere else public, and I can merge it in from there (github has things called Pull Requests too, which are like a branch with associated commentary that act as a formal request to merge - good if the branch needs discussion and changing!)

Take care deleting any icons with "-symbolic" in the name. Those are the newer style, but some aren't referenced (yet).

What would be cool would be a little Python script to automate this kind of cleanup task. It could even be integrated as an automated test... \</bluesky\>

**Comment by borda-flash** [comment]
sorry for the delay I was at my grandfather's home(village - no Internet), All things are taken care of, 

but I am unable to make final move
git commit not working, I searched the Internet(boot camp) but unable to find how to update.
>git commit
not working
prob : How to notify git about removed/deleted file, like there is option "git add" to notify for modified or new file
then how to upload or commit this thing to somewhere, so you can merge from there?
Sorry for all this trouble I am causing, but I am new please help me out.

**Comment by achadwick** [comment]
The command is "git rm":

```
git rm path/to/file1
git rm path/to/file2 path/to/file3
```

all of which update the index of uncommitted changes with some deletions. See
https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#Removing-Files

Once all the deletions are in the index, and `git status` shows them in `Changes to be committed:`, you can run

```
git commit
```

and add your message. This commits the changes locally, and you can review them with tools like `gitk`.


When publishing, you need to push your local changes to a branch you can write to in your https://github.com/borda-flash/mypaint space. The master branch of that will work fine.

Then make a pull request in github, ideally referencing this issue by number, e.g. `mypaint/mypaint#306` ☺

Hope that makes sense. Git is an intricate program, and I hope I'm explaining it correctly!

**Comment by achadwick** [comment]
(`git status` is the kind of  thing you should be running like every 10 minutes or so just so you know what state all the files are in ☺)

**Comment by borda-flash** [comment]
Thanks, I did everything, hope it will help, and I found 
> git add -u

this updates everything by itself, it was too long to write git rm for each file and illogical too, there was some bash option too but i hate bash.

**Comment by achadwick** [comment]
> This removes as well as modifies index entries to match the working tree, but adds no new files.
-- git-add(1), on `-u, --update`

Oh, cool - I didn't know about that flag! Then again my working trees are usually very messy so I've tended to shy away from the big batch forms of `add` in the past.

**Comment by borda-flash** [comment]
did you checked my commit?
I also made a pull request too.

**Comment by achadwick** [comment]
Thanks for the cleanup work and the patch, it's very welcome! Sorry I wasn't able to get around to applying it earlier - my offline life is a bit of a juggling act at the moment.

**Comment by borda-flash** [comment]
It's very nice of you, you helped me on so many things else it was not easy to figure out how things work,  Thank-you :).
