### ISSUE TITLE
Layer dialogue scrolls automatically when hiding/showing layers

### ISSUE THREAD

**Issue by Griatch** [mypaint/mypaint#308]
## How to reproduce:

1. Make a long list of layers in the layer dialogue (repeatedly press the + button). Shrink the window so that it gets a scroll bar. Docked dialogue or free-floating doesn't matter. 
2. Make sure that the topmost layer of the stack is selected.
3. Scroll down towards the bottom of the list.
4. Click the eye icon, for example with the intention of quickly hiding and then again showing one of the lower layers in the stack. 

You will find that the moment you click the eye icon (hide/show doesn't matter), the layer list will try to show the currently selected layer, which means that if your topmost layer is selected in a scrollable list, it will scroll to the top. The only way to prevent this is to select a layer in the bottom part first so that it doesn't need to scroll to revert to it. The same is true if your current layer is low in the stack and you want to hide/show a layer near the top. 

This is counterproductive and quite disorienting. Most commonly you want to keep a certain layer selected (to paint on)  while quickly hiding/showing some other layer for comparisons with line art or checking a sketch - as it is, you cannot rapidly click two times in a row to quickly switch the layer on/off but need to manually scroll to find it again every time.

I would suggest that the layer list does not move at all when modifying layer visibility.

## Notes 

Tested with MyPaint git, rev 43b4fe6 on Linux Mint 17.1.

This is what I originally thought to report in #297, but was then mis-remembering the effect to be from deletion when it was in fact with layer visibility that mattered. But actually, the principle is the same if you scroll your layer window and use Shift+Delete to delete the currently selected layer - the dialogue will then scroll to show the new selected layer. I'm not convinced this is a good idea either - if I have scrolled the layer dialogue to a particular position I think the program should trust that I have done so for a reason and not start scrolling for me.

**Comment by achadwick** [comment]
Reproduced with GNOME, Debian testing/unstable. 43b4fe6740ee0b35679e8925317613b2d34ad1df.

String changes are unlikely to be needed, pushing back to the beta phase. But it's probably something simple.
