### ISSUE TITLE
Preview dockable panel does not update when zooming in the main window (regression)

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#313]
When the main area is zoomed, the preview panel's view of the document does not update its viewfinder rectangle. To make it update, you have to pan a bit to force the viewfinder to be redrawn in the side panel.

**Comment by rcrimp** [comment]
Reproduced with GNOME, Fedora 21 master branch SHA: ada992407c155809d5f8a5294221b27edd1a825d
