### ISSUE TITLE
1.1 to 1.2 glitch

### ISSUE THREAD

**Issue by artsnake** [mypaint/mypaint#317]
I updated from 1.1.1 alpha to 1.2.1 on an ubuntu 14.04 system but I am not sure it worked.The software centre and synaptic package manager says  1.2.1 is installed but the about page says 1.1.1.

**Comment by achadwick** [comment]
Huh? 1.2.1 has not been released yet. That version number isn't even on the current roadmap.

You can find my 1.2.0-alpha builds at https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing. Please check your sources. I don't believe that any developer is releasing builds anywhere else, and they wouldn't be messing with the version number like that.

The issue tracker isn't for direct user support, but the fake version number is intriguing me.

Please paste the output of 

    dpkg -l '*mypaint*' | cat

between two 3 backtick lines like

    ```
    ```

for the sake of github.

**Comment by achadwick** [comment]
Stale, no feedback, closing.
