### ISSUE TITLE
Edit current color in detail (status bar) > pick color with eyedropper problems

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#325]
I've understood the this eyedropper can be used directly on canvas to pick any nuance of a colour or another colour... but  when I try use the eyedropper on canvas it has an attenuated aspect and the colours are different, e.g, the background is white... but if I use this feature the colour results HSV(0,0,70).
![set-current-color-problem](https://cloud.githubusercontent.com/assets/8180638/7785240/389fca4a-015d-11e5-87a0-cb7a8d71a0f3.png)
Linux Ubuntu Gnome 14.04.2
Last MyPaint Git Master: 1.2.0-alpha.20150522+git.ea85620

**Comment by achadwick** [comment]
Looks like you've configured your WM to grey out / diminish the visibility of windows that don't have the focus, is that right? The colours in your screenshot pick as #B2B2B2 (hsv(0, 0, 0.7)) on my screen with gcolor2.

**Comment by achadwick** [comment]
I think this may be working as defined. Though given #324 I can see why you're taking this route...

**Comment by americogobbo** [comment]
The behaviour of my gnome desktop is the default defined by Ubuntu Gnome 14.04.2.
For all tabs or MyPaint dialogues that are positioned over the canvas they result focused only the dialogues and it is correct. But if you read a colour using the eyedropper the colour results a bit more greyish... the white background reads hsv(0,0,7) instead hsv(0,0,1).
I've made a short video to show it: https://www.youtube.com/watch?v=iqtPzru92lI

**Comment by achadwick** [comment]
Reproduced with Debian testing/unstable: set Tweak Tool→Windows→Attached Modal Dialogs to "ON", and then this modal dialog greys out its parent. IIRC this is default GNOME behaviour too.

**Comment by achadwick** [comment]
Ugh. This is because GNOME's trying to be too pretty about modal dialogs (well, actually just any dialog window with a parent window set in the `transient-for` property). Looks like setting GDK_WINDOW_TYPE_HINT_UTILITY on the dialog is the fix.

**Comment by achadwick** [comment]
Okay - please test and re-open if the behaviour isn't right now.

**Comment by americogobbo** [comment]
I've tested (with default => set Tweak Tool→Windows→Attached Modal Dialogs to "ON") and now is OK! Thanks!
