### ISSUE TITLE
Concentric Rings doesn't change hue?

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#326]
![image](https://cloud.githubusercontent.com/assets/8382492/7785761/183edacc-0165-11e5-8199-dbe697f4f6ea.png)

A minor thing, but still... the hue ring (the outermost selector ring) doesn't always change hue when clicking on part of it. Sometimes clicking one of the inner rings first will change it, but it doesn't always work. Clicking on the saturation ring (the innermost selector) usually triggers it to work.

**Comment by americogobbo** [comment]
For me also the behaviour is a bit problematic with values near to black. I've made a small video to show it:
https://www.youtube.com/watch?v=i-KfTV6kMck

**Comment by achadwick** [comment]
Can you be a bit more detailed about your OS and the version of MyPaint you are using please? You should always provide this info in your report.

This is one of the older colour selectors in MyPaint, and it may suffer from HSV <-> RGB round tripping issues. Whether or not you see the issue may even depend on the previous selector you use. Any hint of that sort of behaviour? Try

1. Change the colour with the RGB sliders, then see if the problem presents with these rings
2. Change the colour with the HSV wheel, then see if the problem presents with these rings

Any difference between the two cases?

**Comment by americogobbo** [comment]
I've made another short video with a comparison between the different color selectors.
Perhaps is more usable to describe the problem... it seems that has a relation with HSV Triangle selector...
https://www.youtube.com/watch?v=jcCYLBSSlH4
My DE is gnome > Ubuntu Gnome 14.04.2
Mypaint 1.2.0-alpha.20150523+git.b7836aa

**Comment by AtsusaKaneytza** [comment]
Windows 8.1 64-bit, using MyPaint 32-bit version 1.2.0-alpha.20150504+git.a80a54b downloaded from Tumagonx's blog (sorry for neglecting this info)

Changing the RGB/HSV sliders before using the concentric rings allows the concentric rings to be changed, but after that, I can't draw on the canvas (that's an entirely different issue though, which I'm sure I've reported...)

I usually don't use a different selector before I use the Concentric Rings because I usually don't *need* to.

**Comment by achadwick** [comment]
@AtsusaKaneytza 
Both the RGB sliders and the HSV wheel? There are no HSV sliders.

But if adjusting the RGB sliders then adjusting the rings works, that's one possible source of oddity excluded.

**Comment by AtsusaKaneytza** [comment]
Er, I thought you meant use a different color changer before using the Concentric Rings...

**Comment by AtsusaKaneytza** [comment]
This appears to have been fixed in the MyPaint Beta.

**Comment by achadwick** [comment]
@martinxyz fixed something hue-related in the guts of these selectors recently. It may have cured this problem too.

@americogobbo Can you check whether this is still affecting Ubuntu please? If so, let's close this one.

**Comment by americogobbo** [comment]
@achadwick is working nice on Ubuntu!

**Comment by achadwick** [comment]
Thanks for testing, everyone!
