### ISSUE TITLE
grey highlight not turning off in pick stroke and layer tool

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#331]
While using pick stroke and layer, the grey overlay highlight which appears while picking is not turning off. What I observed is, it happens more on a stroke which is drawn with a relatively huge brush or a long stroke. To get rid of it you need to pick another stroke.

![media-20150531](https://cloud.githubusercontent.com/assets/2767425/7901790/7adbb8fe-07b8-11e5-9d21-4ddcfd2d6736.png)

**Comment by achadwick** [comment]
Looks like a duplicate of #8. Thanks for the report though! I've flagged the old issue to be looked at during the beta cycle.

This is quite a long-standing issue, related to timing: the overlay has to be removed after a short period to make the blink effect work, but it also takes some time to prepare the shape for display - and if that takes too long, the removal timer may already have run.

**Comment by cg-cnu** [comment]
oh, didn't find the old issue while searching. 
Thanks for conforming.
