### ISSUE TITLE
Display filters: eyedropping picks filtered color, not document color

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#333]
Consequently, switching off the display filter is necessary before you can pick a color to paint with.

Existing pen colors are not affected, but, for example, if you switch to Grayscale filter and then pick a color, you will be painting with a grey, not the color at that location.

**Comment by achadwick** [comment]
This is working as designed, while the colour picker tools are capable of picking from any window on the screen. Do you have a use case for changing it?

**Comment by 0ion9** [comment]
.. Use case is simply painting in color while toggling grayscale on and off. If you pick at the wrong time and go on to paint (eg. in fullscreen, where there is not always a color display), you damage the image.

**Comment by AtsusaKaneytza** [comment]
Color pickers in other programs have a "sample merged/canvas" option (which is what MyPaint's color picker) currently does. 
Maybe there needs to be a "sample layer" option for the color picker, like what magic wand tools do in other software

**Comment by achadwick** [comment]
I agree that MyPaint should handle this internally, and will probably need a Sample Merged option. A "sample merged" option will need a new UI string. Deferring until after 1.2.0 is released - we're in string freeze right now.
