### ISSUE TITLE
Move layer mode tool property window not updated

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#335]
The tool property window is not update for the move layer, they show the settings of the previous used tool.

(Just mentioning; am on a bit older version. Couldn't compile the latest one because centos 7 has gtk 3.8; might take a while to come to the latest build)

**Comment by achadwick** [comment]
Duplicate of #252. This has been fixed recently on master - you'll see "no options available" for this and the Pan View mode when you update your working copy.

Sorry about the GTK requirement - we have been requiring GTK 3.10 for some time: see #16.

**Comment by cg-cnu** [comment]
Sorry for the double post. 
I am on centos 7 with GTK 3.8. Any idea how I can upgrade to GTK 3.10. 
Any help / links on how to upgrade would be helpful.
