### ISSUE TITLE
changing from Edit symmetry axis mode / Edit frame mode to Move layer mode doesn't update the UI correctly

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#336]
Switching from Edit symmetry axis mode / edit frame mode to move layer mode doesn't bring the display of the previously used tool to normal. They are still shown in edit mode (with the delete icon) but the icons are not accessible; So, more of an ux issue.

**Comment by achadwick** [comment]
I'm not seeing this at my end with b6d06a46f93065e31b9cc21143f05155bfec974f. Please can you paste the version of MyPaint you're working with? I think you use git versions, so the hex string will be fine.

Can you give me some more detailed steps to reproduce this - starting with a fresh config? A good way of doing that is to run MyPaint with the -c option and a throwaway config:

```
$ rm -fr /tmp/cfgtmp1
$ ./mypaint -c /tmp/cfgtmp1
```

which will allow you to test stuff without breaking your personal config ☺

**Comment by achadwick** [comment]
Oh, and can you confirm that this is a *canvas* display issue? Screenshots welcome!

If there are any backtraces in the terminal, those would be useful to see. It looks very like a mode not exiting cleanly here.

**Comment by cg-cnu** [comment]
ok, First thing, I will try to get the latest gtk and move to the latest version on git. 
I am working with this version 1.1.1-alpha.20150308+git.6b3a1e7.
I didn't got any error even in the terminal.
Hope this screenshots helps.
Even though i changed the tool from Edit symmetry axis mode to Move layer mode but I can still see the delete icon, but its not accessible
![mypainterr](https://cloud.githubusercontent.com/assets/2767425/7960568/2c491786-0a1f-11e5-80de-ed6506497a05.jpeg)
The same thing with the Edit frame mode
![mypainterr2](https://cloud.githubusercontent.com/assets/2767425/7960690/02d57010-0a20-11e5-8382-8a72c2faf967.jpeg)

Let me know if its not clear....

**Comment by achadwick** [comment]
I can't reproduce this with a fresh config in GNOME, using 6b3a1e7f21e6cc597baa31a48f6947ced9f760e3.

* Does it happen every time?
* Please explain the *exact* sequence of operations needed to reproduce this,
  - starting with a *fresh* config please, to rule out your personal config causing this (we'll address that separately if it's the case)
  - tell me what you click, what you paint, whether the problem kicks in immediately, or after multiple tries
* Does pressing the Escape key make the extra canvas elements disappear?
* Does panning the canvas using the middle mouse button or the space bar make the extra canvas elements disappear?

**Comment by cg-cnu** [comment]
Ok, I struggled to get the latest mypaint working on my existing version of centos but couldn't because of the gtk version mismatch. Now, I finally updated to CentOS Linux release 7.2.1511 and got the latest mypaint. Yeahhhh!

I no longer see this bug.  Closing it :)
