### ISSUE TITLE
Liquid Wash Picker Problems - Flipping or unstable when is selecting a colour.

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#337]
When you try to use the Liquid Wash the picker remains unstable and it seems to do a flip cycles... I've made a short video to show it:
https://youtu.be/rEVGeDDEPHg
My DE is Gnome 3.10 - Ubuntu Gnome 14.04.2
MyPaint 1.2.0-alpha.20150602+git.b6d06a4

Another short video to show better the problem:
https://youtu.be/0qokQ3EVfWQ
When you pick a colour it is slipping to black... is possible to see this behaviour in the traditional picker colour HSV Square.

**Comment by achadwick** [comment]
Yep - reproduced. It's worth fixing this for the popup selectors,
