### ISSUE TITLE
Moving the mouse and simultaneously moving the tablet pen causes an OverflowError

### ISSUE THREAD

**Issue by aaronjwoodard** [mypaint/mypaint#344]
Here's the error:
```python
Exception while analyzing the exception.
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/freehand.py", line 555, in _motion_queue_idle_cb
    self._process_queued_event(tdw, event)
  File "/usr/local/share/mypaint/gui/freehand.py", line 597, in _process_queued_event
    self.stroke_to(model, dtime, x, y, pressure, xtilt, ytilt)
  File "/usr/local/share/mypaint/gui/mode.py", line 760, in stroke_to
    cmd.stroke_to(dtime, x, y, pressure, xtilt, ytilt)
  File "/usr/local/share/mypaint/lib/command.py", line 389, in stroke_to
    xtilt, ytilt, dtime,
  File "/usr/local/share/mypaint/lib/layer/data.py", line 1319, in stroke_to
    pressure, xtilt, ytilt, dtime
  File "/usr/local/share/mypaint/lib/mypaintlib.py", line 285, in stroke_to
    def stroke_to(self, *args): return _mypaintlib.PythonBrush_stroke_to(self, *args)
OverflowError: in method 'PythonBrush_stroke_to', argument 7 of type 'float'

```
It happened to me when I was using my tablet and bumped into my mouse. It seems that MyPaint doesn't like it when you move both at the same time. The result is MyPaint will not let you continue to draw.

OS: Debian (Linux 3.16) amd64
Tablet: Wacom Inutos

**Comment by achadwick** [comment]
Interesting. When you dismiss the exception dialog, will MyPaint let you continue to draw?

Can you provide more info on your tablet model, and whether you were pressing a mouse button at the time? Basically let me know how to replicate this exception here.

**Comment by martinxyz** [comment]
Uh, "Exception while analyzing the exception", which is why we can't see the values. But it smells like infinity or NaN... maybe some mouse event delivered with an earlier/same timestamp compared to a tablet event? I can't reproduce (Debian testing, Linux 3.16, Intuos3, xfce). Try to enable the "input test" window in Help->Debug, maybe you'll get more info.

**Comment by achadwick** [comment]
Oh yes. In which case the dialog will be a bit useless probably.

I can't reproduce this here with my Intuos5 + laptop touchpad setup.

I've been assuming that event times are GLib-style "system monotonic time" values, even when delivered from different devices. I guess it's not enforced that events are handled in order across multiple devices though, so perhaps in an interleaved stream calculating dtime could generate negative deltas or other weirdness.

@aaronjwoodard : one workaround might be to restrict your mouse to navigation-only events or even less in the prefs. If painting is disallowed for it, events that 

It's known that sending painting events from more than one device at the same time glitches things up. Maybe fixing #259 would fix this bug too.

**Comment by aaronjwoodard** [comment]
@achadwick : No it will not let me continue painitng when I dismiss the error. The model number on my intuos is CTL-480 (small).

**Comment by achadwick** [comment]
@aaronjwoodard Does this happen every time you try that sequence of inputs?

**Comment by aaronjwoodard** [comment]
@achadwich Yes, every time.

**Comment by achadwick** [comment]
@aaronjwoodard That's very strange. Sorry to be a pain, but I have to ask...

1. What version of MyPaint is this please? (top shasum from `git log`, or the about box version string)
2. What model of mouse is this? Is it an actual hardware mouse?
3. Does MyPaint throw this exception any time you move the mouse, regardless of whether the tablet has been used before (in MyPaint)?
   * Related: are you able to use the mouse at all, ever, after using the tablet once?
4. Is your X server configured in an unusual way for this mouse and this tablet? Please paste the output of `xinput --list` in a [fenced code block](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) if you can.
5. What desktop environment are you using?
6. Please paste the output of `dpkg -l libgtk-3-0 xserver-xorg xserver-xorg-input-wacom` too.

Sorry for all the questions, and thanks in advance for any answers you can give.

**Comment by aaronjwoodard** [comment]
1. 1.2.0-alpha.20150614+git.f74d988
2. Logitech, Inc. M90/M100 Optical Mouse
3. The mouse and tablet both work the way they are intended until both of them are used simultaneously. I can open MyPaint and use the mouse to paint. I can paint with the tablet and then use the mouse (seperately). The exception only occurs when the mouse and tablet are moved simultaneously.
4. 
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech USB Optical Mouse              	id=10	[slave  pointer  (2)]
⎜   ↳ Wacom Intuos S Pen stylus               	id=11	[slave  pointer  (2)]
⎜   ↳ Wacom Intuos S Pen eraser               	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Logitech USB Keyboard                   	id=8	[slave  keyboard (3)]
    ↳ Logitech USB Keyboard                   	id=9	[slave  keyboard (3)]
```
5. xfce
6.
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libgtk-3-0:amd 3.14.5-1     amd64        GTK+ graphical user interface lib
ii  xserver-xorg   1:7.7+7      amd64        X.Org X server
ii  xserver-xorg-i 0.26.0+20140 amd64        X.Org X server -- Wacom input dri
```

No problem. Hope you figure out what it is.

**Comment by KuyaMarc** [comment]
Hello from The Philippines! I'm running MyPaint 1.2.0-alpha.20150610+git.f74d988 that I've compiled a few days ago. I tried to reproduce the Overflow Error and could not do it. No problems in my setup.

64-bit Debian 9 "Stretch" GNU/Linux with 4.1.0-rc8 Kernel. (MyPaint originally compiled until rc7 kernel.) XFCE desktop.
Computer: 3.06GHz P4 with 2GB RAM.
Tablet: Genius EasyPen i405X
Mouse: Connectland Wireless mouse

Nice to see there are other developers! :) Enjoy!

**Comment by achadwick** [comment]
Replicated with f74d988ce15f7cd0c16670ef8e709d1d3ad9ab27, a Lenovo-branded mouse (really an "04b3:310c IBM Corp. Wheel Mouse", model MO28UOL, USB), and a "056a:0027 Wacom Co., Ltd Intuos5 touch M" model PTH-650, USB.

```
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/freehand.py", line 555, in _motion_queue_idle_cb
    self._process_queued_event(tdw, event)
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/freehand.py", line 597, in _process_queued_event
    self.stroke_to(model, dtime, x, y, pressure, xtilt, ytilt)
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/mode.py", line 760, in stroke_to
    cmd.stroke_to(dtime, x, y, pressure, xtilt, ytilt)
  File "/home/andrewc/Development/MyPaintProject/mypaint/lib/command.py", line 389, in stroke_to
    xtilt, ytilt, dtime,
  File "/home/andrewc/Development/MyPaintProject/mypaint/lib/layer/data.py", line 1319, in stroke_to
    pressure, xtilt, ytilt, dtime
  File "/home/andrewc/Development/MyPaintProject/mypaint/lib/mypaintlib.py", line 285, in stroke_to
    def stroke_to(self, *args): return _mypaintlib.PythonBrush_stroke_to(self, *args)
OverflowError: in method 'PythonBrush_stroke_to', argument 7 of type 'float'
```

## Steps to reproduce:

1. Start MyPaint
2. Draw with the tablet for a bit, without moving the mouse
3. Draw with the mouse for a bit, without using the tablet in any way
4. Satisfy yourself that steps 2 and 3 can be repeated as much as you like without error ☺
5. Now draw with the tablet, and as you do so move the mouse...
   * after a few glitchy scribble type events (expected), the exception above is produced on the terminal (not expected)
   * clicking the "Ignore Error" button in the exception dialog does not restore MyPaint to a paintable state.

## Hardware/software details

* **OS:** Debian stretch/sid (testing/unstable)
* **DE:** GNOME 3.16/3.14 mix (gnome-shell 3.14, apps newer - the joys of testing/unstable)

```
<rewc@spatula:/home/andrewc$ uname -a
Linux spatula 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
<rewc@spatula:/home/andrewc$ xinput --list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ DLL060A:00 06CB:2734                    	id=11	[slave  pointer  (2)]
⎜   ↳ SYNAPTICS Synaptics Large Touch Screen  	id=9	[slave  pointer  (2)]
⎜   ↳ Wacom Intuos5 touch M Pen stylus        	id=14	[slave  pointer  (2)]
⎜   ↳ Wacom Intuos5 touch M Pen eraser        	id=15	[slave  pointer  (2)]
⎜   ↳ Wacom Intuos5 touch M Pen cursor        	id=16	[slave  pointer  (2)]
⎜   ↳ Wacom Intuos5 touch M Pen pad           	id=17	[slave  pointer  (2)]
⎜   ↳ Wacom Intuos5 touch M Finger            	id=18	[slave  pointer  (2)]
⎜   ↳ USB Optical Mouse                       	id=19	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=13	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD                    	id=10	[slave  keyboard (3)]
<rewc@spatula:/home/andrewc$ dpkg -l libgtk-3-0 xserver-xorg xserver-xorg-input-wacom
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libgtk-3-0:amd 3.14.13-1    amd64        GTK+ graphical user interface lib
ii  xserver-xorg   1:7.7+9      amd64        X.Org X server
ii  xserver-xorg-i 0.26.0+20140 amd64        X.Org X server -- Wacom input dri
```

**Comment by achadwick** [comment]
Oddly, I cannot replicate this with tablet + touchpad (the oddly-identified "DLL060A:00 06CB:2734" above, which `lsusb` knows as "06cb:0af8 Synaptics, Inc."). Nor with touchpad+touchscreen.

I can with tablet + touchscreen though.

**Comment by achadwick** [comment]
### Test patch

```patch
diff --git a/lib/layer/data.py b/lib/layer/data.py
index 922e294..f7abb04 100644
--- a/lib/layer/data.py
+++ b/lib/layer/data.py
@@ -1314,6 +1314,12 @@ class PaintingLayer (SurfaceBackedLayer, core.ExternallyEditable):
         new one.
         """
         self._surface.begin_atomic()
+        logger.debug(
+            "stroke_to: x=%r, y=%r, pressure=%r, "
+            "xtilt=%r, ytilt=%r, dtime=%r",
+            x, y, pressure,
+            xtilt, ytilt, dtime,
+        )
         split = brush.stroke_to(
             self._surface.backend, x, y,
             pressure, xtilt, ytilt, dtime
```

### Output

Painting away with the stylus. Note sensible tilt values...

```
DEBUG: lib.layer.data: stroke_to: x=483.3023681640625, y=152.360595703125, pressure=0.8232421875, xtilt=-0.023622047244094488, ytilt=0.023622047244094488, dtime=0.007
DEBUG: lib.layer.data: stroke_to: x=484.7197265625, y=152.86309814453125, pressure=0.822265625, xtilt=-0.023622047244094488, ytilt=0.023622047244094488, dtime=0.008
[...]
DEBUG: lib.layer.data: stroke_to: x=493.95361328125, y=156.57379150390625, pressure=0.8203125, xtilt=-0.03937007874015748, ytilt=0.03937007874015748, dtime=0.007
DEBUG: lib.layer.data: stroke_to: x=495.0701904296875, y=156.9603271484375, pressure=0.82080078125, xtilt=-0.03937007874015748, ytilt=0.03937007874015748, dtime=0.008
DEBUG: lib.layer.data: stroke_to: x=496.2298583984375, y=157.34686279296875, pressure=0.81884765625, xtilt=-0.03937007874015748, ytilt=0.03937007874015748, dtime=0.008
DEBUG: lib.layer.data: stroke_to: x=497.389404296875, y=157.8106689453125, pressure=0.81982421875, xtilt=-0.03937007874015748, ytilt=0.03937007874015748, dtime=0.007
```

Okay, here's where I start drawing with both mouse and tablet

```
DEBUG: gui.device: Device change: name='USB Optical Mouse' source=GDK_SOURCE_MOUSE
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: lib.command: Brushwork: stop_recording: 3.782s, tiles_changed=True
DEBUG: lib.observable: Recursive call to <MethodWithObservers lib.document.Document.sync_pending_changes> detected and skipped
DEBUG: lib.document: autosave_countdown: autosave will run in 10s
DEBUG: lib.document: autosave: updates detected, doc marked autosave-dirty
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='Wacom Intuos5 touch M Pen stylus' source=GDK_SOURCE_PEN
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='USB Optical Mouse' source=GDK_SOURCE_MOUSE
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='Wacom Intuos5 touch M Pen stylus' source=GDK_SOURCE_PEN
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='USB Optical Mouse' source=GDK_SOURCE_MOUSE
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='Wacom Intuos5 touch M Pen stylus' source=GDK_SOURCE_PEN
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='USB Optical Mouse' source=GDK_SOURCE_MOUSE
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
[...]
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='USB Optical Mouse' source=GDK_SOURCE_MOUSE
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.device: Device change: name='Wacom Intuos5 touch M Pen stylus' source=GDK_SOURCE_PEN
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
```

All that only takes up a few tens of milliseconds, but note the ugly chopping and changing, and in particular the heavy checkpointing.

The capture queue then gets a chance to deliver the pending input data to the brush-engine/rendering leg... now we have silly values for the tilts from the stylus:
```
DEBUG: lib.layer.data: stroke_to: x=498.463134765625, y=158.08123779296875, pressure=0.5, xtilt=0.0, ytilt=0.0, dtime=0.008
DEBUG: lib.command: Brushwork: stop_recording: 0.000s, tiles_changed=False
DEBUG: lib.layer.data: stroke_to: x=499.463134765625, y=158.08123779296875, pressure=0.81982421875, xtilt=2.4e-322, ytilt=5e-324, dtime=0.003
DEBUG: lib.layer.data: stroke_to: x=499.450927734375, y=158.50640869140625, pressure=0.5, xtilt=0.0, ytilt=0.0, dtime=0.005
DEBUG: lib.layer.data: stroke_to: x=500.450927734375, y=157.50640869140625, pressure=0.81982421875, xtilt=1.63e-322, ytilt=5.217e-321, dtime=0.003
DEBUG: lib.layer.data: stroke_to: x=500.3958740234375, y=158.7769775390625, pressure=0.5, xtilt=0.0, ytilt=0.0, dtime=0.004
DEBUG: lib.layer.data: stroke_to: x=501.3958740234375, y=158.7769775390625, pressure=0.81982421875, xtilt=1.63e-322, ytilt=5.217e-321, dtime=0.004
DEBUG: lib.layer.data: stroke_to: x=501.2977294921875, y=159.04754638671875, pressure=0.5, xtilt=0.0, ytilt=0.0, dtime=0.004
DEBUG: lib.layer.data: stroke_to: x=503.2977294921875, y=158.04754638671875, pressure=0.81982421875, xtilt=2.4e-322, ytilt=3.55337744e-316, dtime=0.004
DEBUG: lib.layer.data: stroke_to: x=502.11376953125, y=159.27947998046875, pressure=0.5, xtilt=0.0, ytilt=0.0, dtime=0.004
```

And one ytilt value that's too big to go in a binary32 (float), but could fit in a binary64 (double). Not that SWIG's little deficiency here matters, it's obviously a spurious value.

```
DEBUG: lib.layer.data: stroke_to: x=503.11376953125, y=159.27947998046875, pressure=0.81982421875, xtilt=1.63e-322, ytilt=1.178811761825107e+180, dtime=0.004
Traceback (most recent call last):
[...]
OverflowError: in method 'PythonBrush_stroke_to', argument 7 of type 'float'
```

**Comment by achadwick** [comment]
Should be fixed now. You'll get some pretty wild discontinuous barbed wire effects with a tilt-sensitive brush, 

![Glitchyglitch](https://cloud.githubusercontent.com/assets/61299/8197150/30a7ea24-148c-11e5-812c-9ed09b0fc25e.png)

if you cross the streams now, but maybe that's okay? Better than interrupting work, anyway.

@aaronjwoodard Can you re-test with your hardware please, and let me know if this fix doesn't work for you?

**Comment by aaronjwoodard** [comment]
@achadwick It works. I get a bunch of jaggy lines like what you have in your pictures. But MyPaint doesn't throw that exception, and I can keep painting afterwards. The stroke lags behind the cursor when I paint with the tablet and the mouse simultaneously, but I think it shouldn't be a problem. I doubt many people are going to be painting with the mouse and the tablet at the same time. As long they can continue painting, I think it is fixed.
