### ISSUE TITLE
Drawing quickly produces very line-y curves

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#35]
![blender](https://cloud.githubusercontent.com/assets/3432543/3476624/8d5f3100-0303-11e4-8a22-03bec93a79c5.png)
As an example.

For reference, here's some lines drawn very rapidly with Gimp:

![blender](https://cloud.githubusercontent.com/assets/3432543/3476637/c22d6154-0303-11e4-8144-65469cdaa809.png)

They're a lot uglier, because Gimp, but they're a lot smoother than Mypaint's lines.

**Comment by achadwick** [comment]
I'm kinda all out of ideas for this one. I don't think we should be poking at this for the 1.2 release though; deferring until after the 1.2 release just to get it off the list, and I suggest we close it as WONTFIX if we haven't had any smarter ideas about how to improve matters by then.

**Comment by iirelu** [comment]
I've been thinking of different things to try but yeah, let's close this for now.
