### ISSUE TITLE
"color erase" and "behind" brush blend modes

### ISSUE THREAD

**Issue by blurymind** [mypaint/mypaint#350]
gimp has those implemented and they are great!!

https://www.youtube.com/watch?v=ixfK0qCEmbg
This would be very useful for cleaning up sketch drawings. Tvpaint and PAP use this feature in order to allow the user to draw with multiple colored brushes. So if using a blue brush for a rough pass, then draw with a black brush on top to ink it and then erase the blue brush lines bellow.

It would be nice to have it in mypaint.

User case example :
To illustrate this, lets say we have a hand and need to draw a new variation of it. We will start with the previous drawing, but erase the parts that need to be changed:
![screenshot_2015-06-10_11-42-00](https://cloud.githubusercontent.com/assets/6495061/8078478/be4813de-0f66-11e5-9d2c-e6fd8ca129c3.png)

Then we use the blue pencil to sketch a drawing of the new hand variation:
![screenshot_2015-06-10_11-43-30](https://cloud.githubusercontent.com/assets/6495061/8078506/eb5be120-0f66-11e5-94be-8e3cde07c111.png)
The blue pencil is set to NOT affect existing pixels by drawing on top of them.

We finish the blue line sketch, then we do the opposite, we set a black pencil and set it to overwrite already existing pixels with its color and ink with it:
![screenshot_2015-06-10_11-59-55](https://cloud.githubusercontent.com/assets/6495061/8078725/4532596c-0f68-11e5-971d-83d1a4c15749.png)

Finally, we execute the "erase all color on a layer" command, with color set to blue! What we are left with is the clean line art:
![screenshot_2015-06-10_12-01-48](https://cloud.githubusercontent.com/assets/6495061/8078761/7e15f4f0-0f68-11e5-8155-c57c668433b0.png)

All done on a single layer!

You can also apply this to selective eraser mode, where the eraser tool  can be set to work only on lines that have the same color as the one that is currently set to the eraser tool.

Why else is this useful?
- When you draw for animation, and in general - it is good practice to draw an object complete, when the object is behind another object and then erase the part of the line that is behind the other object. In this case we have the fingers of the hand covering the handle. We must draw the entire handle, then clean up the part that is behind the fingers.

The draw behind brush blend mode will be very useful for fixing errors left by bad bucket fill results. Filling areas that it missed, without disrupting the ink lines.

The color erase brush blend mode will be useful for erasing color spills without disrupting the lineart. Or erasing parts of lineart without disrupting fills.

**Comment by achadwick** [comment]
Sounds useful, but after 1.2. This will need a libmypaint change too: can you raise this as one or two issues there as well?

**Comment by blurymind** [comment]
posted here, with more information on the feature:
https://github.com/mypaint/libmypaint/issues/17

**Comment by blurymind** [comment]
also have a loot at:
https://github.com/callaa/Drawpile/issues/191

Drawpile just got these features

**Comment by odysseywestra** [comment]
@blurymind Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue. Thanks.

**Comment by AesaraB** [comment]
Consolidated into #1219
