### ISSUE TITLE
Disable cursor

### ISSUE THREAD

**Issue by amarao** [mypaint/mypaint#356]
(feature request)

Cintiq (monitor with tablet) and thinkpad X220 tablet (laptop with built-in wacom under screen) do not need pointer to say users where image will appear (it appears under pen/stylus). Most operating system updates cursor with low frequency, and fast hatching/drawing causing stroboscopic effect for pointer with significant perceptible lag.

Disabling cursor make process much more pleasant.

Request: Add to mypaint option 'hide cursor on canvas'. Krita has that option and it much smoother experience than mypaint for now.

**Comment by achadwick** [comment]
@amarao Sounds like a very slow screen update. I'll take a look, but let's gather requirements quickly...

* What version of Mypaint are you using, please?
* Have you tried turning the pointer into a crosshair in Prefs→View→Freehand cursor type? That should reduce the visual noise you're seeing a lot. Does that make MyPaint smooth enough for your use?

If we implement, I suggest that the new setting turns off the cursor while drawing (button1-press, proximity-in, or 1st motion event with pressure > 0) and turns it back on after drawing (at button1-release or tablet proximity-out). It's OK and desirable for non-tablet users to see where the cursor is on the screen when it's not painting anything.

This will need a new UI text for the setting, so it will need to be done either before the string freeze on the 11th, or after the 1.2.0 release.

**Comment by achadwick** [comment]
Thanks for the suggestion, @amarao, and I'm sorry that there wasn't really time to plan it out. It was simple enough to implement, so I just did what I saw fit. Hope this is OK.

**Comment by amarao** [comment]
It is amazing. I'd built it, and there is a  brave new world of drawing. Like on paper. Pen(cil) and medium, nothing else in between.

Thank you!
