### ISSUE TITLE
Cursor behaves strangely after clicking in docked Favorites subwindow

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#357]
_Using 32-bit MyPaint 1.2.0-alpha.20150605+git.4e8a6b5, downloaded from tumagonx's blog.
Using a Yiynova MVP10U screen tablet. Windows 8.1 64-bit system._

After clicking on a brush from my "Favorites" window, the cursor will show up as a normal mouse pointer on the canvas instead of showing the brush cursor. It'll behave this way for long periods of time until I press "Esc" to fix it.

I think this behavior is related to the fact that I can't click and move brushes between brush groups or re-arrange brushes in the group. But I'm not sure...
I noticed this strange behavior after I tried adding a kneaded eraser from set no. 2 to my favorites MANY times. After frustration, I right clicked on it and added it, but I needed to drag it closer to my other erasers (which didn't work)

**Comment by achadwick** [comment]
Cannot reproduce with git master MyPaint as of 513e9e2 (2015-07-02) and 3.16.4, so whatever you're seeing doesn't seem related to the dnd regression in #359. But I am only using a mouse right now. Hmm.

Does this affect the cursor after:

* Clicking on a brush from any other docked docked brush list subwindow?
* Clicking on a brush in the popup brush chooser, on the B key?

Triage: fairly minor impact since painting still works, possibly Windows-specific. Would Be Nice for a beta fix if we can. No string changes necessary.

**Comment by AtsusaKaneytza** [comment]
_Does this affect the cursor after:
>Clicking on a brush from any other docked docked brush list subwindow?_
Sometimes.
_>Clicking on a brush in the popup brush chooser, on the B key?_
Yes. For some reason, clicking on a brush in the popup brush picker causes the brush to default to "straight or curved lines" mode. The straight or curved lines mode is not activated before choosing a brush this way. Then again, my shortcut for the brush picker is "Shift+B" because "B" is my shortcut for "Freehand Drawing" (I changed my brush picker shortcut since...)

After a bit more fidgeting around with this, I've noticed that the cursor's being strange after I use my shortcuts for increasing and decreasing the brush size as well. With enough pen pressure for some reason, the pointer cursor turns back into a brush cursor.

(sorry if this seems really trivial...)

**Comment by achadwick** [comment]
Sounds like it's related to #384. Deferring for the same reason...

**Comment by achadwick** [comment]
@AtsusaKaneytza 
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) was released recently. Please can you test it out, and let us know whether this issue is still happening?

Thanks!

**Comment by AtsusaKaneytza** [comment]
Trying (too often) to drag brushes between brush group windows results in the program freezing, and a window that says "Pythonw32.exe has stopped responding" or something to that effect. So still buggy, I guess

**Comment by achadwick** [comment]
@AtsusaKaneytza 
That is *definitely* something else. This one is a minor glitch, what you are seeing there is a major crash. Please make a separate report about it, with super-clear instructions about how I can reproduce that "Pythonw32.exe has stopped responding".

I think that this issue has been fixed, based on other reports about cursors going weird.
