### ISSUE TITLE
Brush drag-and-drop is broken: error noted in terminal output ("No brush named … in drag source widget")

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#359]
Possible regression on #142. Noted in passing in #357 witha  recent Windows build - @AtsusaKaneytza , can you provide more information on this side issue?

Sample error messages when trying brush DnD:

```
ERROR: gui.brushselectionwindow: No brush named 'kaerhon v1/paint barrr sm' in drag source widget
ERROR: gui.brushselectionwindow: No brush named 'kaerhon v1/wet paint sm' in drag source widget
ERROR: gui.brushselectionwindow: No brush named 'deevad/kneaded eraser large' in drag source widget
ERROR: gui.brushselectionwindow: No brush named 'deevad/kneaded eraser large' in drag source widget
ERROR: gui.brushselectionwindow: No brush named 'deevad/detail brush thin' in drag source widget
```

Not limited to any particular brush group.

## Steps to reproduce

1. Run MyPaint with a freshly-created blank config
    
    $ rm -fr /tmp/cfgtmp1
    $ MYPAINT_DEBUG=1 ./mypaint -c /tmp/cfgtmp1

2. Open any brush group from the brushes toolbar item, or from the menus (e.g. Brush → Brush Groups → Classic)
3. Try and drag a brush fom one position in the group to another.

* Expected: the brush will move to where you release the button
* Observed: no motion, drag has not worked, errors in terminal log.

This also affects attempts to drag brushes from one group to another, e.g. from "Set #4" to "Favorites".

What is weird is that sometimes a drag within the same group *will* work - but IMX this is vanishingly rare. I've not managed to isolate the circumstances in which it does work.

I'm using a regular mouse for the DnD, and I noticed that on the button-down event, the current brush indicator in the bottom right corner of the screen updates.

## Debugging output

For one minimal DnD attempt within the same widget, I'm seeing

```
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: lib.command: Brushwork: stop_recording: 0.000s, tiles_changed=False
DEBUG: gui.mode: BrushworkModeMixin: checkpoint()
DEBUG: gui.pixbuflist: drag-data-get: sending type=Gdk.Atom.intern("text/plain", False)
DEBUG: gui.pixbuflist: drag-data-get: sending fmt=8
DEBUG: gui.pixbuflist: drag-data-get: sending data='kaerhon v1/fill c' len=17
DEBUG: gui.pixbuflist: drag-data-received: got type=Gdk.Atom.intern("text/plain", False)
DEBUG: gui.pixbuflist: drag-data-received: got fmt=8
DEBUG: gui.pixbuflist: drag-data-received: got data='kaerhon v1/fill c' len=17
ERROR: gui.brushselectionwindow: No brush named 'kaerhon v1/fill c' in drag source widget
```

looks like all the details are bring filled in properly, so what's going on here?

Tested with GTK+ 3.16.4, GNOME, and MyPaint master at 513e9e2bb35ab710395880b1dee6c916350998aa.

**Comment by AtsusaKaneytza** [comment]
How do I open MyPaint with blank config? (and will I be able to get my old config back if I do?)

**Comment by achadwick** [comment]
@AtsusaKaneytza the command to use is documented above, on Linux machines. It's documented in the READMEs too.

On Windows, rename the `mypaint` folder in `%LOCALAPPDATA%` to `mypaint.BAK-issue359` and launch MyPaint normally. That will generate a fresh config. To revert, you get rid of the new `mypaint` folder and rename the backup you made to its original name.

**Comment by AtsusaKaneytza** [comment]
Thank you for the info, I'll test it out and see what I come up with.

**Comment by AtsusaKaneytza** [comment]
Still persistent in the latest version: MyPaint 1.2.0-beta.0+gitexport.adc9032

**Comment by achadwick** [comment]
Looks like this is a mishandling of brushes with spaces in the name, which on disk are replaced with underscores. Some brushes are affected, others aren't...

**Comment by achadwick** [comment]
"Spaces in the name" was a sign we were using the display name internally (which can now show brush descriptions) rather than some sort of consistent identifier. Fixed!
