### ISSUE TITLE
Error when generate translation template

### ISSUE THREAD

**Issue by tumagonx** [mypaint/mypaint#361]
Under MSYS when invoke <code>scons translate=pot</code> against git master I get:

    ...
    intltool-update -g mypaint --pot
    ERROR: xgettext failed to generate PO tempalte file because the following file contains strings marked for translation, not encoded in UTF-8. Please ensure all strings marked for translation are UTF-8 encoded.

           ./../gui/filehandling.py:282
    ...

intltool-update (intltool) 0.50.2
xgettext.exe (GNU gettext-tools) 0.18.1

At least I know msys 1.x do not fully support unicode, but error is by xgettext which is not msys binary in my case.

**Comment by achadwick** [comment]
Reproduced on current Debian.

Seems to be the result of using `-*- coding: utf8 -*-` instead of `-*- coding: utf-8 -*-` at the top of Python files. Sigh. Will patch soon.

**Comment by achadwick** [comment]
@tumagonx 
BTW, I'm fighting a lack of translation of GtkBuilder files in MSYS2 as we speak. Any consequences to doing

```python
    if sys.platform.startswith('win'):
        libintl = None
        import ctypes
        for libname in ['libintl-8.dll', 'intl.dll']:
            try:
                libintl = ctypes.cdll.LoadLibrary(libname)
            except:
                logger.exception(
                    "Windows bindtextdomain() ctypes hacks failed (%r).",
                    libname,
                )
            else:
                logger.info("Windows: found libintl in %r", libname)
                break
        if libintl:
            bindtextdomain = libintl.bindtextdomain
            bind_textdomain_codeset = libintl.bind_textdomain_codeset
            textdomain = libintl.textdomain
```

(other than feeling really dirty about it?)

I'm not sure what era `intl.dll` is from, and really I'm just cribbing from <https://github.com/carlos-jenkins/nested/blob/1.x/nested/context.py#L110>, but `libintl-8.dll` seems to be the name for it in MSYS2:

```
testuser@win7test MINGW32 /e/MyPaintProject/mypaint
$ pacman -Q --owns /mingw32/bin/libintl-8.dll
/mingw32/bin/libintl-8.dll is owned by mingw-w64-i686-gettext 0.19.4-3
```

Does libintl go by the same DLL name on your MSYS build env?

(Reason for this nasty ctypes hack is that the MSYS2 python2 I'm using doesn't expose those 3 setup functions as builtins from its `locale` module - and calling the ones in `gettext` doesn't make GtkBuilder happy. And I think this is fairly normal for Windows Python.)

**Comment by tumagonx** [comment]
I can really comment on that, I'm kind of on my own dirty patch on my own customized MSYS. In my case MSYS 1.x gettext official have broken unicode support, so I using static native build instead. Generally msys binary would named msys-$libname.dll. But tha's MSYS2 intl appears to be native build

**Comment by achadwick** [comment]
Yeah, in MSYS2, `/mingw32` is a native Win32 tree. Trying to pull in cygnus-style `msys-intl-8.dll` results in

```
ERROR: mypaint: Windows: attempt to load libintl from 'msys-intl-8.dll' failed (ctypes)
Traceback (most recent call last):
  File "./mypaint", line 321, in <module>
    libintl = ctypes.cdll.LoadLibrary(libname)
  File "C:/msys64/mingw32/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:/msys64/mingw32/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

Are you able to do…

```python
>>> import ctypes
>>> ctypes.cdll.LoadLibrary("msys-intl-8.dll")
```

… on your build system, or anything else in the list ['msys-intl-8.dll', 'libintl-8.dll', 'libintl.dll', 'intl.dll'], or simlar names?

(Maybe it'd be just simpler to wrap our own in MyPaint's C extension module. But I feel like I'm getting somewhere with this at least...)
