### ISSUE TITLE
Can't format images after saving.

### ISSUE THREAD

**Issue by princepippa** [mypaint/mypaint#363]
I usually save my works with a transparent background, meaning when I save it for the final time I select the transparent png format.   The problem I've been having recently is that after I save my file once, regardless of format, or if I upload an image already formatted, I can't select anything on the save menu.  The only way I'm able to even name my stuff it by using the arrow keys- so either I have to finish a work all in one go without saving until it's done, or I can only have a solid background.

I'm planning on doing art commissions soon and would really like this bug to be resolved if possible.

---
update:  well it turns out i have to have my pc mouse connected along with the tablet?  idk at least it works again

**Comment by achadwick** [comment]
What version of MyPaint is this, and what OS? 

> * When reporting your issue, be sure to describe what operating system you're on and which version of MyPaint you're using.
> * Please limit your issue reports to a single, fixable problem.
> * If you are requesting a new feature, please submit mockups, pictures or other clear explanations of what it is you want, and how it would help you.
>
> The tracker is not really intended for user support, but we can sometimes help investigate your problems there. Your problem report may turn into a workaround you can use, and many reports have helped us uncover a more fundamental bug in the program code. However don't be discouraged if the issue gets closed when there's nothing we can do about it in the current phase of development.
>
> Note that Mypaint 1.0.0 is a really old version, so if possible you should upgrade to the latest version before reporting anything, as it's probably been fixed by now. If you are on Windows, look here for relatively up-to-date builds: http://opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html
-- <https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md#test-the-program-and-report-issues>

**Comment by achadwick** [comment]
@princepippa I'm guessing this isn't an issue any more?

> update: well it turns out i have to have my pc mouse connected along with the tablet? idk at least it works again

(Github doesn't send notifications on updates attached like this)

**Comment by achadwick** [comment]
Assume this wasn't an issue after all.
