### ISSUE TITLE
Colour dropper

### ISSUE THREAD

**Issue by susoelsucio** [mypaint/mypaint#369]
The colour picker tool with de dropper icon doesn't work in mypaint running in Windows 8.1 64bits.
When I select a color from the drawing, the tool sets another different colour.

**Comment by susoelsucio** [comment]
Sorry, I forget to mention I'm using mypaint v. 1.0.0. in Windows 8.1. 64bits.

**Comment by achadwick** [comment]
(Thanks for the feedback! Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md#test-the-program-and-report-issues) so we can deal with this issue more effectively.)

* I need to know what version of MyPaint this is, and from where you got it. You can find the version in Help→About MyPaint.
* Can you tell me or show me which dropper icon you are using? There's more than one.
* Is it always the same wrong colour?
* Do you try to pick from your artwork, or somewhere else?

A change to the behaviour here may cut across #333. To be sure nothing's fully decided there yet.

**Comment by achadwick** [comment]
Okay, my comment crossed yours. 1.0.0 is very old, and is not supported.

I'll be putting a beta for 1.2.0 up shortly (hopefully before the end of today). Watch this space.

**Comment by susoelsucio** [comment]
The dropper icon I use is the one under the triangular color picker.
No, i think wrong colours are random, I'm not sure now.
Yes, picking from my artwork and from the sketch sheet (hoja de pruebas), I'm not sure how is it called in English.
Thank you achadwick, I will be waiting.

**Comment by achadwick** [comment]
Hi there - there is a new early pre-release (bleeding edge!) version available on github now: <https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.0>, and also a similarly recent (and better tested!) version available from @tumagonx 's blog: <www.opensourcepack.blogspot.fr/2013/01/mypaint-and-pygi.html>. Could you test this out again, and let us know if the problem has been resolved for you?

**Comment by achadwick** [comment]
**Triage note:** needs to be reproduced with a recent build or a build from source. Needs steps to reproduce.

**Comment by susoelsucio** [comment]
Hello,

I've tried to install de W64 beta but it doesn't work. The install process runs fine, but wen I execute the program, it happens nothing.
I don't know if I'm doing something wrong.

**Comment by achadwick** [comment]
There are known problems if you have accented characters in your Windows username. I will work on making it easier to find out what went wrong in the beta series: these early releases are meant for testing.

**Comment by achadwick** [comment]
@susoelsucio Please can you try v1.2.0-beta.0.73, just released at <https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.0>? It contains fixes for several Windows-related startup bugs.

**Comment by susoelsucio** [comment]
Sorry @achadwick,  I couldn't try this before.
With this new beta the colour dropper works fine in Windows 8.1.
The problem now is that the program doesn't detect the pressure on my wacom (intuos 4).
Also I think this beta works a bit slower, I think there is a bigger delay when drawing but I'm not sure. My PC sould run any software fastly (I7, 16GB RAM, SSD HD).

Thank you very much for your work.

**Comment by achadwick** [comment]
Thanks for the confirmation. The other two issues you mention may have been reported already:

* Lag: #390 
* Pressure: #283 (maybe)
