### ISSUE TITLE
Pick layer and brush (W key) occasionally doesn't work

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#37]
At first I thought there was a bug where the W key wouldn't get the correct colour seemingly randomly, but while I was trying to reliably replicate it, I stumbled across a lot more bugs with the W key:

From what I can tell, there seems to be two points of failure. The first is where a stroke is drawn, as sometimes it doesn't save the data needed to recreate layer and brush information. [Here's a link to an .ora where this happens](https://docs.google.com/file/d/0B3TmldcdmeFgS1JUNFh5dFlCNU0/edit).

![blender](https://cloud.githubusercontent.com/assets/3432543/3490126/6bc0598e-055b-11e4-9b06-fba36fb80b16.png)
The circled strokes won't work when you press W on them, while the rest of them will (except for a few of the annotation strokes, ironically).

The second point of failure is when it's trying to get the stroke information, as it seems the W key randomly fails around 0.5% of the time. Trying again will usually work. This doesn't seem to be caused by anything in particular.

**Comment by achadwick** [comment]
Would still appreciate a way of reproducing this error, if that's possible. Anyone able to provide a recipe (including ways of nobbling the code to make it more apparent where to start looking)?

**Comment by achadwick** [comment]
**Triage note**: no way to reproduce yet. Needs exact steps to reproduce, or a patch to illustrate where in the code this is going wrong.

Chalked up for the beta cycle, but this is a stale bug. Let's close it after a couple of weeks if it seems to have gone away now, or if it simply can't be reproduced reliably.

I think the strokemap in the original report is corrupt or incomplete, sure, but I need more information to chase this one down. Sorry.

**Comment by achadwick** [comment]
Or of course a video of it happening - that might help.

**Comment by iirelu** [comment]
This is a heisenbug, I'm going to just close it until I find some way to reproduce it (or someone makes a duplicate).
