### ISSUE TITLE
MyPaint v1.2.0-beta.0 Windows 7 x64. Difference in mouse and tablet.

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#373]
Bamboo Pen and Touch

1. Tablet - no tooltips
2. Menu like list of layer modes.
    Mouse - one click to open menu, Tablet - point and hold down to open menu
3. Open program with mouse - 'preferences/device usage'  only mouse in list, but tablet working.
    Open program with tablet - mouse and tablet in list.
4. Tick 'Hide controls in fullscreen' - Go fullscreen - No hide - Using eraser on my pen, triggers hiding of interface

Sorry for my english.

**Comment by achadwick** [comment]
All I can suggest is ensuring you have the latest Wacom drivers for your computer (Linux, Mac or Windows?). MyPaint's tablet support is only as good as GDK's.

There's basically nothing MyPaint can do to improve things here, and I'm not sure what you're asking me to do. Sorry.

**Comment by achadwick** [comment]
Ah, it is Windows. Just re-read the title. Sorry.

I'll try and respond as best I can, but there's a lot in here and I'm having difficulty understanding what you wrote.

1. Tablets generate a lot of very small movements, so tooltips often do not work. Tooltips require stillness. Try taking your stylus out of range: the tooltip may appear.
2. I don't understand what you are asking me to do here. Is this just different behaviour between mouse and tablet that you're objecting to?
3. That's weird, and I *have* seen a lot of similar weird behaviour with Windows in a VM with my tablet. I'm not certain it's a bug that I can do anything about though - at least, not without a clearer description.
4. "Hide controls in fullscreen" uses a timer internally, and it's triggered by pointer motion. Perhaps that's the source of the oddity you're seeing?

(Please, when sending issue reports, only put one problem in each issue. Thank you!)

**Comment by achadwick** [comment]
**Triage note:** needs to be split into multiple separate issues. Needs clarification. Might not be bugs or enhancement requests at all. The first one looks resolved, or at least to be working as designed. The others need a lot more clarification. Close in 2 weeks if nothing actionable is forthcoming. Link any split-off issues here.

**Comment by achadwick** [comment]
3. is an interesting piece of information about how GDK does device lists on Windows. I understand a bit more about it now. The underlying issue for MyPaint usability should have been fixed in 5cc2da4ffa7360566109f385fe87e032f749af6d - thanks for reporting it!

I'm not sure what to make of the other points you make still, and they should probably be raised as separate issues, and clarified separately. Sorry.
