### ISSUE TITLE
Cannot determine install type on Arch linux. 

### ISSUE THREAD

**Issue by tcuc** [mypaint/mypaint#378]
I am unable to start Mypaint even after waiting for several updates. this is the error i get:
```
Traceback (most recent call last):
  File "/usr/sbin/mypaint", line 420, in <module>
    = get_paths()
  File "/usr/sbin/mypaint", line 186, in get_paths
    raise RuntimeError("Unknown install type; could not determine paths")
RuntimeError: Unknown install type; could not determine paths
```
i gather that there are paths not defined or something but i really have no idea how to fix this. 
I can start Mypaint fine an Ubuntu MATE, it just seems to be arch. (Antergos)

**Comment by achadwick** [comment]
`/usr/sbin` is for sysadmin binaries. MyPaint will not run from there.

If it was installed to one of the normal place for user binaries, `/usr/bin` or `/usr/local/bin`, you would probably get further.

**Comment by tcuc** [comment]
Thanks, I'll try to edit the PKGBUILD to reflect this. 
( I hope this is the right place to ask questions like this?)

**Comment by achadwick** [comment]
If you're the maintainer of a PKGBUILD, then certainly! Sorry if my earlier response was a bit terse.

You might be interested in <https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-mypaint> - alien species sure, but it builds perfectly fine and could be adapted. There are recent issues in MSYS2's MINGW packages that break it when run on that platform however.

You should basically just let `scons` install to the prefix you choose. The prefix/sandbox/install target triple is always tricky though, and I'd be happy to explain. It *is* standard SCons, inasmuch as "standard scons" is a valid concept...

**Comment by tcuc** [comment]
I'm not the maintainer, but if I can find out what changes need to be done I can add a comment to the package and hope the maintainer can add that to the PKGBUILD. 

I will have to read up on a few of the things you just mentioned since I have never written any code other than Arduino. But this seem like a smaller issue that might be insightful to the considerations that are required for running python code on a system. 

And your previous response was to the point and I did not interpret any intention either positive or negative, but I wanted to assure that I was not adding unnecessary noise in the wrong place.

**Comment by 0ion9** [comment]
Installing to /usr/sbin is confusing, but on an Arch Linux system it has no meaning other then semantic:

```
$ file /bin /sbin /usr/bin /usr/sbin 
/bin:      symbolic link to usr/bin
/sbin:     symbolic link to usr/bin
/usr/bin:  directory
/usr/sbin: symbolic link to bin
```

(in other words, an installed mypaint is accessible via all four of those paths, because they are all the same actual directory)

That said, yeah, the package is broken  -- I guess it has a launcher pointing at /usr/sbin.

**Comment by achadwick** [comment]
Okay - didn't realise it was doing that. Thanks @0ion9 !

The test should either use os.path.realpath() in addition to what it's currently doing, or be rewritten to go looking for ../share/mypaint, ../lib/mypaint, ../share/locale, and ../share/icons relative to the script dir.

**Comment by tcuc** [comment]
@0ion9 thanks! i just typed 
/usr/bin/mypaint 
and the program fired right up!

**Comment by ncmprhnsbl** [comment]
i'm not seeing this using arch(bang),   
have built mypaint (using  AUR pkgbuild via apacman helper) six times in the last three months no problems... last build 23/07
@tcuc   what method are you using to build?

**Comment by tcuc** [comment]
yauort. and i belive i used packer once to to no avail. i have also installed this via pacman with a similar error.

**Comment by tcuc** [comment]
this is the error i get when trying to launch mypaint installed via pacman;
```
We are not correctly installed or compiled!
script: "/usr/sbin/mypaint"

Traceback (most recent call last):
  File "/usr/sbin/mypaint", line 170, in <module>
    datapath, extradata, confpath, localepath, localepath_brushlib = get_paths()
  File "/usr/sbin/mypaint", line 111, in get_paths
    from lib import mypaintlib
ImportError: No module named lib
```

**Comment by achadwick** [comment]
@tcuc Looks like an older version's error report from the line numbers. I've had to squelch that semi-nice "not correctly installed or compiled!" message in the most recent master commits because Win64 GLib & GTK screw up unicode user profile paths badly if the C++ bits of MyPaint are imported that early.

I'll have another look at the way MyPaint does its runtime path detection, to see if I can make it more robust in the case of symlink thickets, but the AUR package (or whatever "via pacman" pulls in on your Arch install) is not maintained here. The only one I'm responsible for is that MSYS2/MINGW-w64 thing above.

**Comment by achadwick** [comment]
a9f71f2 works for our Debian and Windows packaging scripts. Not tested with common Arch PKGBUILDs, but the code should be sound, and tolerant of whether the actual location is $prefix/bin or $prefix/sbin now.

**Comment by ncmprhnsbl** [comment]
some clarification...
'pacman' installs from official arch binary (version 1.1.0)
'apacman' builds from AUR PKGBUILD (git version)
for further confusion, AUR is currently being migrated to
a new version AUR4, breaking some helpers...
also note AUR helpers, yaourt etc, must be run as a normal
user...
