### ISSUE TITLE
MyPaint won't draw after I open it?

### ISSUE THREAD

**Issue by lilych4** [mypaint/mypaint#381]
Hey, recently I bought a drawing tablet so I installed MyPaint 1.0.0. It worked beautifully, that is until I unplugged my tablet and closed the program and opened it again the next day. The program wouldn't let me interact with it using the tablet unless I reinstalled it. I closed the program again and tried reopening it later and had the same issue. How can I fix this?

**Comment by achadwick** [comment]
Dup of #380.

**Comment by achadwick** [comment]
Sorry, not sure that this is a duplicate. Reopened.

@lilych4 Please upgrade to a recent 1.2.0-beta and let me know if this is still happening. 1.0.0 is too old for us to support.

Are you using Microsoft Windows?

**Comment by achadwick** [comment]
There's not quite enough information in your original report to move this issue forward. Please read the [reporting guidelines][reporting]: we need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

**Comment by achadwick** [comment]
**Triage note** needs system information, unsupported MyPaint version. Reporter: please upgrade and test again.

**Comment by achadwick** [comment]
Closing this old issue now: 1.0.0 is an unsupported version.
