### ISSUE TITLE
MyPaint w64 1.2.0 keeps glitching

### ISSUE THREAD

**Issue by lilych4** [mypaint/mypaint#386]
I used to have MyPaint 1.0.0 but I kept having to reinstall it so it would work with my tablet, so I upgraded to MyPaint w64 1.2.0 (I downloaded the file called mypaint-w64-1.2.0-beta.0.73-setup.exe). The trouble is, it keeps glitching. Whenever I try to draw, there's these straight lines that keep appearing while I draw. When I try to click on the file, edit etc. tabs, they either don't work or only appear for a split second. How do I fix this? I have Windows 8.1 and a monoprice tablet.

**Comment by tumagonx** [comment]
Both menubar and tablet support glitches are upstream issue that never really resolved since GTK 3.0 even GTK 2.x start to show menubar bug with newer Windows. I recommend to nag at GTK developers :p https://bugzilla.gnome.org/

**Comment by achadwick** [comment]
IRC is also a helpful way to chase a bug report: #gtk+ on GIMPnet: https://wiki.gnome.org/Community/GettingInTouch/IRC

I don't own a monoprice tablet, so I can't really help here myself.

@lilych4 Does it look like the glitch in #177 ? Screenshots would be helpful to everyone, particularly for drawing glitches.  You can attach them here if you need hosting (drag+drop!)

**Comment by achadwick** [comment]
@lilych4 Please tell us whether it looks like the glitch in #177 

**Triage note** no user feedback, no confirmation (but for sure we don't have a library of every Monopriice device out there!), and glitchy input with "straight lines that keep appearing" makes this sound like a duplicate. Close as duplicate in 2 weeks if nothing more from the reporter.
