### ISSUE TITLE
Fonts in Windows 10

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#387]
I updated to Windows 10 and now have such strange fonts. Krita, Gimp, Inkscape have normal fonts like in windows 7. Beta 0.73 W64.

![23](https://cloud.githubusercontent.com/assets/13454470/9009815/f38604ec-37bc-11e5-8c20-000b4c2a342c.jpg)

**Comment by achadwick** [comment]
Can you clarify why these are strange please? I'm not a Russian speaker, but the type looks legible to me, and it's (hopefully!) correctly translated...

(I'm assuming the lack of Japanese characters in sigetch's name is not what this complaint is about)

**Comment by achadwick** [comment]
(I just noticed you are contributing translations at <https://hosted.weblate.org/engage/mypaint/>. Thank you!)

**Comment by zb13y** [comment]
Wide fonts, hard to read, bad for interface. E.g. must be Tahoma (idk what type of fonts used for programs), but they like Comic Sans. Problem in type of fonts (Arial, Calibri, DejaVu etc).

**Comment by achadwick** [comment]
@zb13y I see that you've closed this. What was the fix, out of interest?

**Comment by zb13y** [comment]
I think that in mypaint 1.0 was same type of fonts.

**Comment by zb13y** [comment]
Hmm... i thought that in mypaint 1.0 type of fonts was same, but not.

Left 1.0, Right 1.2.0
![1](https://cloud.githubusercontent.com/assets/13454470/9711155/e241b2e2-555a-11e5-85f2-b99cdc05a9b3.jpg)

![2](https://cloud.githubusercontent.com/assets/13454470/9711158/e57dfe2a-555a-11e5-8751-528d2be5b8bd.jpg)
As you see, in mypaint 1.0 i can see japanese fonts.

![3](https://cloud.githubusercontent.com/assets/13454470/9711159/e8be9586-555a-11e5-9506-3492f27e5489.jpg)

**Comment by achadwick** [comment]
Nice comparison, thanks.

I don't have much experience with programming fonts on the Windows platform. However MyPaint does not dictate which font it uses.

The choice of font is made by the theme, Adwaita in the case of 1.2.0, and I'm fairly sure that GDK uses the FreeType font engine to render them on Windows. I'm much less certain about which fonts it has available however: all Windows system fonts, only `.ttf` files we ship in the MyPaint bundle, or the union of both sets?

If it's GDK, it has a fallback mechanism: rendering can use one font for one script, and a different font fallback fonts for other scripts.

The font used for Latin in the most recent 1.2.0 screenshots above does not appear to be Cantarell, the GNOME3 default font. The "nder" cluster in "Zoom and Rendering" is quite [badly kerned](https://en.wikipedia.org/wiki/Kerning) too.

I still need to check this out properly with a copy of Win7 Ultimate and different language packs. Sorry for being slow to investigate.

**Comment by zb13y** [comment]
I think this problem only in windows 10. Windows 10 have different default fonts. In windows 7 all must be fine.

<i>The choice of font is made by the theme</i>
So this is windows issue. I think issue can be closed, if there are no problems with other versions of windows (e.g. windows 7).

**Comment by tokyogeometry** [comment]
Hi,
although I can't confirm as I use Linux, but in Windows in Japanese locale, the UI text seems to be displayed in a fallback monospace font instead of _Meiryo UI_(Windows 8/8.1)/_Yu Gothic UI_(Windows 10) which is usually used.

**Comment by achadwick** [comment]
@tokyogeometry 
There's a new release of MyPaint available, with a newer GTK/Pango/Cairo/everything bundle in for the Windows builds. Can you have a quick test with it and check whether fonts display correctly?
https://github.com/mypaint/mypaint/releases/tag/v1.2.1

@zb13y 
I'm assuming everything's OK in a real Russian locale under Windows 10.

FWIW, on my screen, "Сан Саныч ‘MrMamurk’ (patterns)" and "しげっち ‘sigetch’ (programming)" are legible in the 1.2.1 build's About box under Windows 7. They appear to use a vector font.
