### ISSUE TITLE
Interface is unexpectedly in Russian

### ISSUE THREAD

**Issue by ryandesign** [mypaint/mypaint#389]
mypaint 1.2.0-beta cfec87c3ac9a6bf34488e98e3c38f712f702c2b6 (20150731) launches with its interface in Russian. Last time I checked in 508f6654095b46d2e62a012f374def32b8538cec (20150712) it launched in English. The terminal output includes these lines:

```
INFO: lib.i18n: OSX: LANG='en_US.UTF-8'
INFO: lib.i18n: OSX: LANGUAGE=u'en:pt:ru:tr:th:en_US'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
ERROR: mypaint: No platform-specific fallback for locating bindtextdomain is known for 'darwin'
```

But trying different locales doesn't help.

**Comment by achadwick** [comment]
Yikes! (but also: yay, someone is testing the OSX i18n code we stole^H^H^H^H^Hacqired from QuodLibet!)

How have you been trying different locales?

Dissecting your output a bit, 

```
INFO: lib.i18n: OSX: LANG='en_US.UTF-8'
INFO: lib.i18n: OSX: LANGUAGE=u'en:pt:ru:tr:th:en_US'
```

This is the automagic OSX fill-ins for the environment variables that lib18n (and Python's builtin workalike) needs to do their job. They should be pulled from your OSX settings, including the language priority list: they're not from within MyPaint; we have a Turkish translation, but no Thai.
The bit of code in question is in <https://github.com/mypaint/mypaint/blob/6d8befd777d8452be9035c50fc1c46ba063b557f/lib/i18n.py#L102>.

```
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
ERROR: mypaint: No platform-specific fallback for locating bindtextdomain is known for 'darwin'
```

This refers to the fact that we need tell both Python and libi18n where to find the translation files on disk. Python code is easy: the standard API never changes. For libi18n, it's trickier and what we currently do involves finding "low-level" bindings of libi18n's `bindtextdomain`, `bind_textdomain_codeset`, and `textdomain` functions, and calling them early, before loading GTK. That varies a lot between platforms, and as I don't have a Mac, I haven't been able to find a good workaround. So I'm guessing *not all* of your UI is in Russian? In particular, are the preferences window and the menus translated into Russian, or using the source language (US English)?

The menus and prefs windows are defined in XML files that GTK reads, and uses libi18n to translate. Things like the statusbar texts are translated by Python's own `gettext` module in older code, and in newer code via GLib (which uses i18n).

The code in question for this bit resides in mypant.py. Someone needs to write a clause like <https://github.com/mypaint/mypaint/blob/6d8befd777d8452be9035c50fc1c46ba063b557f/mypaint.py#L291> for darwin essentially. 

Finally there are some fixups we do which can screw up the interpretation of `LANGUAGE`, which is a priority list. Do you get a line saying something like

```
DEBUG: lib.i18n: Sanitized the priority list in LANGUAGE to 'en:C:ru'
```

when you run with MYPAINT_DEBUG=1 ? It's supposed to inject a "C" after the first instance of an English code in `LANGUAGE`, but that might be a remnant QuodLibetism.

**Comment by ryandesign** [comment]
> This is the automagic OSX fill-ins for the environment variables that lib18n (and Python's builtin workalike) need to do their job. They should be pulled from your OSX settings, including the language priority list 

You are correct, `en:pt:ru:tr:th:en_US` seems to be translated from my OS X settings. I have no idea how my OS X settings got changed to that; I don't know those languages, except English. I do know German, which I typically configure into OS X as a secondary language, but OS X appears to have forgotten that.

> So I'm guessing *not all* of your UI is in Russian? In particular, are the preferences window and the menus translated into Russian, or using the source language (US English)?

With `LANG=en_US.UTF-8` in my environment (the OS X Terminal application sets this automatically based on system preferences), the menus are in Russian, except a few menu items that perhaps don't have translations? "Recover File from an Automated Backup..."; "Feedback"; "Hide Controls in Fullscreen"; "Trim Layer to Frame"; "Edit Layer in External App..."; "Update Layer with External Edits"; "Save Scratchpad as Default".

The Preferences window is a combination of English and Russian, and the leftmost button is titled "Reverter" which must be Portuguese.

The title of the About window is "Sobre MacPaint". The link to the MyPaint web site in the About window is titled "Página Web". The rightmost button in the About window is "Fechar" while the other two buttons are in Russian. The copyright notice is in English.

> How have you been trying different locales?

I had tried to specify a different locale by starting MyPaint using `LANG=en_GB.UTF-8 mypaint` and `LANG=en_GB mypaint`. This is reflected in the output at startup, but has no effect on the interface languages.

If I use `LANG=en mypaint` this is apparently invalid; I get the warning:

```
(process:26765): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
```

and I get English menus, because that's the C locale. I get the same English menus if I use the "invalid" locale `de`. With either `en` or `de`, the status bar is still Russian and the About box is unchanged from what I described above.

> Do you get a line saying something like
> 
> ```
> DEBUG: lib.i18n: Sanitized the priority list in LANGUAGE to 'en:C:ru'
> ```
> 
> when you run with MYPAINT_DEBUG=1 ? It's supposed to inject a "C" after the first instance of an English code in LANGUAGE, but that might be a remnant QuodLibetism.

This is what I get when I use `MYPAINT_DEBUG=1`:

```
INFO: lib.i18n: OSX: LANG='en_US.UTF-8'
INFO: lib.i18n: OSX: LANGUAGE=u'en:pt:ru:tr:th:en_US'
DEBUG: lib.i18n: Sanitized the priority list in LANGUAGE to u'en:pt:ru:tr:th:en_US:C'
```

**Comment by achadwick** [comment]
Hm - looks like the priority hack we use could at least be fixed to make LANGUAGE `en:C:pt:ru:tr:th:en_US` instead.

**Comment by ryandesign** [comment]
Thanks! Much better.

```
INFO: lib.i18n: OSX: LANG='en_US.UTF-8'
INFO: lib.i18n: OSX: LANGUAGE=u'en:pt:ru:tr:th:en_US'
DEBUG: lib.i18n: Sanitized the priority list in LANGUAGE to u'en:C:pt:ru:tr:th:en_US'
```

Now to go fix my OS X language preferences...
