### ISSUE TITLE
Blank error message when opening broken/corrupt files which have ampersands (&) in the name

### ISSUE THREAD

**Issue by jadesreich** [mypaint/mypaint#391]
Saved something then accidentally hit the new page button, promptly opened a new page and now it won't open my .ora file.  I tried opening it in gimp and it does so just fine.  I'm running windows 8.1 and mypaint 2.0. Any suggestions?

**Comment by achadwick** [comment]
@jadesreich MyPaint 2.0 hasn't been released yet. 1.2.0 is in development - are you running a recent alpha or beta build? Where did you download it from? Please paste the full version number from Help → About MyPaint so I can figure out what you're running.

I'm not sure what command you tried. MyPaint doesn't have a new page button, or pages. Was this File → New?

How did you try to open the .ora file with MyPaint?

(This issue tracker isn't really a user support forum, but I'll see what I can do. There may be something that needs fixing here.)

**Comment by achadwick** [comment]
Also, if there are any specific error messages associated with this, I'd really like to see those. You should be able to copy the texts from our error dialogs into the Windows clipboard and paste them here.

I won't ask you to share the file you were working on just yet, and I'd understand if you're not able to do that.

**Comment by jadesreich** [comment]
Yes I'm running the beta sorry.  I got it from https://github.com/mypaint/mypaint/releases.  Here is the full version 1.2.0-beta.0+gitexport.adc9031.   

It was the "start with a new blank canvas".  

I tried opening it through the mypaint file menu then open.  (ctrl O) I even tried shutting everything down, and trying it again to no avail.  

It seems to try and come up with an error log but it doesn't actually say anything.

I don't really mind sharing it isn't anything special, however it doesn't seem to support .ora files, and I've no clue what the easiest way for you to check it would be.

Thanks for any assistance you can give.  Sorry for the inconvenience.

**Comment by achadwick** [comment]
> It seems to try and come up with an error log but it doesn't actually say anything.

Is this the window that says "A programming error has been detected."? Try clicking on the "▶ Details..." button.

**Comment by jadesreich** [comment]
Here's a screen shot of it, seeing as it doesnt give me the details button.  ![screenshot error](https://cloud.githubusercontent.com/assets/13614359/9028446/440a5f56-3936-11e5-97a1-863aa254a1ef.png)

**Comment by jadesreich** [comment]
umm...my bad here the screen in question.
![single screen screenshot error](https://cloud.githubusercontent.com/assets/13614359/9028456/952fddac-3936-11e5-895b-2ddcf9f6fb21.png)

**Comment by achadwick** [comment]
That's new! :fearful:
Of course, it's not very helpful as a diagnostic method.

I guess I should make a release with #385's fix in it soon, so you can at least see console output in opaque situations like these.

I'm assuming that this is a broken file. Are you able to open other .ora files?
If you want to attach the broken file here - your call - you can rename it to have a ".png" extension, and drag it in. Github doesn't know how to preview OpenRaster files attached like that, but they can be downloaded.

(Speaking of renaming, OpenRaster/.ora is just a zipfile internally - you can rename it to .zip too if you need to recover data)

**Comment by achadwick** [comment]
Further information collected from the wiki (standard disclaimer: "please do not use the wiki for making bug reports - it won't be read, and the wiki is for user documentation and project guff").... :grinning: 

> I recently drew something and it won't open in my paint.  I tried opening gimp up and it imports it without a problem.  That being said I still have more work to do in paint.  I'm running windows 8.1 and my paint 2.0.  Any suggestions?

**Comment by jadesreich** [comment]
Yes other .ora files open without a problem.
![mergedimage]
(https://cloud.githubusercontent.com/assets/13614359/9050931/2febb930-3a11-11e5-8905-76c82afdebee.png) 
I renamed this one to a .zip and it finally actually gives an error.  FYI

**Comment by achadwick** [comment]
That's a PNG file, not ORA. Is that the image that was originally named “D & D map.ora”? If so, then it just had the wrong extension, let me just see what happens if I do the same...

![image](https://cloud.githubusercontent.com/assets/61299/9056889/00008a48-3a8e-11e5-8d66-8e37952f8784.png)

Ha! looks like we have our bug.

**Comment by achadwick** [comment]
It's supposed to be producing an error message like:

> Error loading “a.ora”.  
> Reason: File is not a zip file  
> The logs may have more detail about this error.

but the ampersand is clearly breaking it. The same blank error comes up if I make a junk file with an ampersand in the name and try and load it, and it doesn't matter if the file is supposed to be PNG or ORA: *any* error about loading a file with an "&" in the same produces the blank message.

To reproduce:

    touch 'x & y.ora'
    mypaint 'x & y.ora'     # blank error message
    touch 'x & y.png'
    mypaint 'x & y.png'     # blank error message

Compare and contrast:

    mypaint '1s & 0s.ora'    # no error - that's how you make a new named file on the command line
    ; draw something sand then save it, it'll use the name above
    mypaint '1s & 0s.ora'    # no blank error message, file is good.
