### ISSUE TITLE
Move codebase to Python 3

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#392]
Python 3 has been out since 2008. It is high time the MyPaint codebase was updated to use it.

(Simple description, lots of work, might run into some scons issues...!)

**Comment by QuLogic** [comment]
I probably should have asked this earlier, but are you planning on supporting both 2 and 3 simultaneously?

**Comment by achadwick** [comment]
Hmm, good question, given that we build the python extension. Can scons reliably generate either, on all platforms? I'm not sure it can.

It may be worth moving to distutils/setuptools first.

**Comment by odysseywestra** [comment]
What left thats need to be ported to python3?

**Comment by jplloyd** [comment]
There may be some minor issue lurking still, but otherwise everything is now compatible with Python 3 (excluding the icon export script - easily fixed).
