### ISSUE TITLE
Scons Failed to Build due to Parse output

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#397]
MyPaint failed to build when I tried to install it in ```/usr/local```

Ubuntu Gnome 15.04

Commit Ver: 6048998bf56d6260af95c24b8fcdc26a5e5f5df5

```
scons: Building targets ...
burn_versions(["mypaint"], ["mypaint.py"])
scons: *** [mypaint] RuntimeError : Failed to parse output of "git describe --tags --long --dirty --always". The base MYPAINT_VERSION (1.2.0-beta.0) from the code must be present in the output of this command ('v1.1.0-1569-g6048998-dirty'). The local repo may be missing a tag named "v1.2.0-beta.0", or we need to add another case for parsing git output.
Traceback (most recent call last):
  File "/usr/lib/scons/SCons/Action.py", line 1064, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/albert/Share/github/mypaint/SConscript", line 50, in burn_versions
    script_header += lib.meta._get_release_info_script(gitprefix="git")
  File "./lib/meta.py", line 273, in _get_release_info_script
    base, formal, ceremonial = _get_versions(gitprefix=gitprefix)
  File "./lib/meta.py", line 216, in _get_versions
    ver = base_version,
RuntimeError: Failed to parse output of "git describe --tags --long --dirty --always". The base MYPAINT_VERSION (1.2.0-beta.0) from the code must be present in the output of this command ('v1.1.0-1569-g6048998-dirty'). The local repo may be missing a tag named "v1.2.0-beta.0", or we need to add another case for parsing git output.
scons: building terminated because of errors.
```

**Comment by achadwick** [comment]
How are you updating your local repo from github? `git pull` or `git fetch`?

What is the output of `git tag`?

Note: 

> [...] The local repo may be missing a tag named "v1.2.0-beta.0", [...]

**Comment by odysseywestra** [comment]
I update my local repo by pulling changes from master mypaint as a remote and then fast forwarding my local and pushing the changes in my fork.

Here is the output of ```git tag```

```
albert@Helios:~/Share/github/mypaint$ git tag
v0.2
v0.3
v0.4
v0.4.1
v0.5.0
v0.6.0
v0.7.0
v0.8.0
v0.9.0
v0.9.0-beta1
v1.0.0
v1.1.0
v1.1.0-rc1
v1.1.0-rc2
v1.1.0-rc3
```

**Comment by odysseywestra** [comment]
My chain of commands to update mypaint follows:
```
$ cd libmypaint
$ git pull upstream master
$ git push
$ cd mypaint
$ git pull upstream master
$ git submodule update --init --force
$ git push
$ sudo scons prefix=/usr/local install --clean
$ sudo scons prefix=/usr/local install
```

**Comment by achadwick** [comment]
Okay, that's a slightly unusual way of doing things. I wonder if you're out on your own branch, effectively? Anyway, you need the beta tag available locally if you want the version to be right (at the moment). Does `git fetch upstream --tags` update your local tags usefully? In other words, does `gitk` show `v1.2.0-beta.0` as part of your history (a hundred or so revisions back from now)?

**Comment by achadwick** [comment]
It might be better if we don't assume users will have any local tags that we use during the build. Arguably trying to achieve the nice scheme documented in adc90311996f37679f84440f590a723d30295534's commit message for everyone is overkill.

I recently had to to relax some of this for Travis builds, which changed the way they did tag updates recently for some reason: 6309622e6fc253c116f766f01091c85ea2f02efd.

I'd be happy to relax it further and make it accept cases where the most recent tag doesn't match the one in the code, and just not filling in the number-of-revisions-since but in the long-winded version string we stick in the about box.

**Comment by odysseywestra** [comment]
Yeah, I do that to keep my fork isolated and to consonantly stay up to date to upstream. Plus it was one of the methods github recommended me to do. 

Yup it all I need to do was to update the tags and it build it just fine. Instead of coding a way around, maybe just put that in the install notes as one of the things a user has to make sure to do when a new version tag is added?

Anyways thanks for the help. I can now continue testing mypaint. ^^
