### ISSUE TITLE
Export dialog is titled "Save"

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#399]
Noticed when looking at #398. The Export dialog has the same title as the Save As dialog. If #398 makes export do more complicated things than save, like sticky formats, the dialog should be different (and is there more we can do than just retitle it?)

Flagging as Post-1.2 because we can't add new strings in the final 1.2 development stages.

**Comment by achadwick** [comment]
### Good new starter task

This is a seemingly minor change that actually has some decisions to make. It would be easy for one of us to do the job, but I'd like to give a first-timer the opportunity to learn, if possible.

### What needs to be done

- Get yourself a Github account.
  - Check out the [hello-world tutorial](https://guides.github.com/activities/hello-world/) they suggest. It's good stuff.
  - Read up on the [branching model](https://guides.github.com/introduction/flow/) too.
- _Add a comment_ below saying that you want to work on this.
  - One of us will assign it to you
- _Fork_ the main MyPaint repository into _your personal area_ on Github.
  - This is a copy that you work on, with full control over it.
- _Clone_ your forked repository to your computer
  - `git clone git@github.com:YOURNAME/mypaint.git`
- _Branch_ your clone, just for this job
  - `git checkout -b issue399-retitle-export-dialog`
- Edit `gui/filehandling.py`, and fix up the save_as_dialog() method.
  - This is an ancient module, full of ancient legacy code. Perhaps it needs some TLC! :skull: :tulip: :heart:
  - The method already makes the distinction between Save As and Export.
  - However note that the dialog is constructed and stored in a member variable.
    - It probably shouldn't be. Could self.init_save_dialog() just return a one-time dialog?
    - Look at what get_open_dialog() does. Is that a better model?
  - And check out the try: finally: mess on the end. Looks like there's an old GTK bug we're working around.
  - Test MyPaint can still run from within your clone
  - _Add_ your changes (use `git add gui/filehandling.py` for this)
  - _Commit_ what you added with `git commit`. [Here's how to write the commit message](https://github.com/mypaint/mypaint/wiki/Contributing-Patches#commit-messages).
- _Push_ your branch back to your area in Github
  - This publishes your changes so we can see them.
- Send a _Pull Request_ to us, from your branch to our `master` branch
  - You can refer to this issue in the PR's description or its comments as `mypaint/mypaint#399`.
  - That's it! We may ask you to revisit the branch and revise it, but if it's a clean set of changes we won't need to and you'll be done as soon as we merge your code.
  - Celebrate! You just made your first pull request :tada: 

You can ask us to help at any stage. We all remember having to learn this stuff too. Saying "I don't know" or "I don't understand" is a _positive_ thing here! :bouquet: 

There are some really detailed video guides to this process on <http://makeapullrequest.com/>, and MyPaint has a growing text-based [Contributing guide](https://github.com/mypaint/mypaint/wiki/Contributing) in English on its wiki.

### Going a little further: internationalization! :earth_asia: 

There are a few file dialogs in that module which have an ellipsis (three dots, "`...`") in their titles. The open dialog is one of them. The dots should probably be removed, because those three dots are for buttons and menu items which launch a dialog. It's a minor consistency thing, but worth it.

In a second commit in the same PR, you could replace the `_()` gettext call with a call to our newer `C_()` function, and change the string to be translated. `C_("context", "string")` is nicer for our translators, so we ask that new code uses in place of `gettext()` or its more usual `_()` alias. The context tells translators where the string appears in the user interface. have a look at what the other calls to `C_()` re doing. It's really important for our translators to be able to distinguish between something titled "Open" in a "File" menu vs. the same string in a "Scratchpad" menu vs. the same string (again) on a button or in the title of a dialog!

This little add-on is definitely a related change, so we'd be happy to review it at the same time :grinning:

**Comment by malligaraj** [comment]
Hey @achadwick ,
       I am new to Open source software and I want to learn about contributing. I would like to work on this bug if its okay with you :)

**Comment by achadwick** [comment]
@malligaraj Sure, I'll assign it to you now. It's night here, but I can answer questions in the morning :sleeping: 

You may get an accidental and incorrect message from github telling you that your initial access is read+write. We set read+only access for new remote collaborators on `first-timers-only` issues immediately afterwards because the Pull Request system is more productive: it builds in code review and feedback!

(meta: I might review this process. It's a bit awkward!)

**Comment by malligaraj** [comment]
@achadwick Alright, thank you. I will start with it and contact you if I am stuck!

**Comment by achadwick** [comment]
@malligaraj No problem. Happy to review any changes you put in a PR, or answer any questions you need answering :smiley:

**Comment by malligaraj** [comment]
Hey @achadwick,
        I made a pull request (#645) with re-title of Export dialog and a slight change in the way init_save_dialog() returns a dialog. Could you please have a look at the pull request and see if I am going in the right direction and help me with the question that I have in the pull request comment :smile:

**Comment by achadwick** [comment]
Given the syntax changes, let's leave this in the pipeline for 1.3.o only, not 1.2.1.

In which case, all merged and fixed :tada:
Thanks, @malligaraj !
