### ISSUE TITLE
.PSD files are no longer supported?

### ISSUE THREAD

**Issue by Teyphas** [mypaint/mypaint#400]
Just noticed that new beta can't even see .psd files. When tried to drag on to canvas got obvious message. I don't know which logs are out there containing that secret information ^^
![capture](https://cloud.githubusercontent.com/assets/7257207/9140403/73825690-3d4a-11e5-98ea-ed6a4d36e47e.PNG)

**Comment by odysseywestra** [comment]
I don't think MyPaint has ever supported .psd files. It only supports open
raster (.ora).You are better off opening it in GIMP and then saving it as
an .ora, though you may have to adjust the file.

**Comment by Teyphas** [comment]
@odysseywestra Actually, it supported .psd files in previous beta, even with preview and in early builds there was .psd support also. Not that it's something I can't live without, but sometimes I used MyPaint for outlines in my psd files.

**Comment by odysseywestra** [comment]
Well in the past couple years since I've used, psd support was never added. It has been talked about in #122 and are willing to accept patches to add support . So basically sadly it's not a high priority for MyPaint.

**Comment by achadwick** [comment]
MyPaint has never supported Photoshop format. Perhaps you're thinking of Krita or GIMP?

Closing as a dup of #122 .

**Comment by tumagonx** [comment]
@Teyphas do you means alpha builds from me? that was gdk-pixbuf PSD read only support. Gdkpixbuf has several third party modules such svg, webp and psd.

**Comment by Teyphas** [comment]
@tumagonx  Ah. well..Silly me. Yes, I had this one 1.1.1-alpha.20150319+git.4d5bd9b before. Alright :) Thanks for opening my eyes.

**Comment by achadwick** [comment]
@tumagonx Interesting! I guess it would only load an aggregated/static image though, not layers?

(SVG support is included in the betas here, and I really want to allow the load dialog and recents to support any format that GdkPixbuf can load. I had a play, and it's not hard to get a list of file extensions - but it's one of those things that will need string changes.)

(There's also the Python Imaging Library, one of the batteries that get included with Python. One day, maybe.)

**Comment by tumagonx** [comment]
@achadwick yes, it a very basic support and development has been stalled long time ago.

**Comment by 0ion9** [comment]
@achadwick : PIL is not included with Python. I just doublechecked. (`yaourt -Ql python | grep PIL` and `yaourt -Ql python2 | grep PIL`).
Also, if we are serious about moving to Python 3, then we shouldn't write new code depending on PIL, but instead the fork Pillow, as PIL was last updated in 2009, whereas Pillow is [actively maintained](https://github.com/python-pillow/Pillow) and supports Python 3.

**Comment by achadwick** [comment]
@0ion9 Of course, you're right.

* Pillow is what Debian install as `python-pil`. Old PIL is basically dead.
* It's a separate module from core Python, but it's widely available across the platforms we support:  <https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-Pillow> for example.
* I want to start work on porting to Python 3 after the 1.2.0 release is out: #392
