### ISSUE TITLE
Inverse eraser (increase alpha instead of decrease)

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#407]
This is the painting mode opposite to Eraser.

By the idea it should work exactly as Eraser, in exception it should increase alpha (till 1.0) instead of decrease.

**Comment by achadwick** [comment]
Please raise this as an issue against the brush engine, libmypaint, as well. You will need to provide us with an algorithm, or a pointer to somewhere that it's implemented already, and kindly link back to this request using `mypaint/mypaint#407` type notation so that they can be looked at together. There will be UI work for MyPaint.

Leaving this request open as a UI request, but this need support in the brush engine first.

**Comment by 0ion9** [comment]
.. It's implemented in GIMP.. AFAIK it's literally what loentar says: Eraser subtracts from alpha, Anti-Erase adds to it. There is no effect on color. Implementation [here](https://git.gnome.org/browse/gimp/tree/app/operations/gimpoperationantierasemode.c#n95)

**Comment by loentar** [comment]
Not exactly as GIMP. GIMP just adds opacity, even if the area is totally transparent. 

I'd like to increase opacity only if pixel's alpha > 0. If alpha = 0 don't change it.

Please see what I mean. The right half of image is after applying anti-eraser, solid rectangle brush with 50% opacity.

![anti-eraser](https://cloud.githubusercontent.com/assets/4038431/9250620/2ce21234-41d7-11e5-9928-96c3ab55ef03.png)

The same image on checker pattern to see opacity.
![anti-eraser-checker](https://cloud.githubusercontent.com/assets/4038431/9250697/c6844e66-41d7-11e5-9da1-0fc6af7b7c54.png)

**Comment by achadwick** [comment]
Please report this at <https://github.com/mypaint/libmypaint/issues> as well.

**Comment by martinxyz** [comment]
As long as MyPaint stores colors in pre-multiplied alpha, GIMP-style anti-eraser is not possible: the color information is multiplied by zero in places where the alpha is zero, so there is no way to recover it. But increasing the alpha as suggested should be possible as long as you don't overdo it. It could work by applying a gamma curve to the alpha channel (or anything else that doesn't amplify the alphas close to zero too much). The sharp edge in your "expected" image is probably not achievable without visible color noise and/or banding around the edges, especially after a save-load round-trip through 8bpc.

(Premultiplied alpha has the nice (IMHO) property that only visible information is stored, e.g. there is no hidden image behind every layer which could influence blending or smudging tools by bringing back colors that have long been erased.)

**Comment by AesaraB** [comment]
Consolidated into #1219
