### ISSUE TITLE
Upgrading 1.0.0 to 1.2.0 doesn't work on Windows 7 x64

### ISSUE THREAD

**Issue by braintorch** [mypaint/mypaint#409]
It seems that installer need some improvement because when I installed 1.2.0-beta.0.73+gitexport.1932648 over existing 1.0.0 installation mypaint refused to start. Old version shortcut still was there on my desktop and it launched old version fine though I still have heavy issues when I try to use my tablet.

**Comment by achadwick** [comment]
Thanks for reporting, but there's not a lot that can be done here.

(1.2.0 has not been released yet. Do you want to try a more recent beta than beta.0.73? beta.1 is out...!)

Please uninstall the old version first using *Add and Remove Programs*. This style of in-place upgrade is not supported (two different authors, the best part of two stable versions apart, the version being uninstalled is not supported any more, and I think there may be two different (un)installer types at play here - but I'm not sure about the latter). As I understand it, this is a fault with an old, unsupported version meaning you'll have to uninstall it manually and do any cleanup you need first. The supported version should present as "MyPaint w32" or "MyPaint w64" in your start menu, and for beta.1 on your desktop if you choose to install a desktop icon.

That said, the recent beta releases I've made should be capable of replacing *each other*, if I've understood Inno Setup correctly.

Old and new releases can be downloaded from <https://github.com/mypaint/mypaint/releases> if you need to go back and forth to find something that works with your hardware.
