### ISSUE TITLE
Where did 'Hide Layer' and 'Lock Layer' go?

### ISSUE THREAD

**Issue by ydahhrk** [mypaint/mypaint#414]
Is this normal?

![Iconless Layers palette](https://dl.dropboxusercontent.com/u/95836775/MyPaint/LayersNoIcons.png)

I recall when I upgraded to <del>1.2</del> beta 1.2 the eye (Hide/show layer) and lock (prevent edits) icons were moved to the <del>right</del> left. At some point then they randomly disappeared. I don't know how to retrieve them :(
(Renaming the ~/.mypaint folder doesn't do anything.)

I was using the 1.2.0-beta.1+gitexport.a7012b4 version. I upgraded to the current master (dc79f2564e) and the problem persists.

Ubuntu 14.04.

**Comment by achadwick** [comment]
(Version 1.2 has not been released yet - we're still in beta)

No, that's not normal. There has been one recent change: eye and lock should be on the left now, and type icons on the right (after #144 was closed):

![flippedlayout](https://cloud.githubusercontent.com/assets/61299/9093288/20311146-3ba3-11e5-94ec-bf64b4458eb1.png)

I did some minor work on the column widths as part of it. Perhaps it's related. Can you investigate whether reinstating any of the lines deleted by 6048998bf56d6260af95c24b8fcdc26a5e5f5df5 fixes the problem?

Quick question: do you get the folder icon appearing on the right if you make a group?

**Comment by ydahhrk** [comment]
> (Version 1.2 has not been released yet - we're still in beta)

I know :)

> eye and lock should be on the left now

Oops, yes, that's what I meant :)
(see the scratched text in my original post.)

> Can you investigate whether reinstating any of the lines deleted by 6048998 fixes the problem?

Ok, working.

> Quick question: do you get the folder icon appearing on the right if you make a group?

No.

**Comment by achadwick** [comment]
(bit in brackets was mostly for future searchers - sorry ☺)

I can't reproduce this in a VM with MyPaint master (running in-tree, with a fresh config) and Ubuntu 14.04 LTS. As part of my testing, I upgraded from GTK 3.10.8-0ubuntu1.5 to GTK 3.10.8-0ubuntu1.6.

It should look like

![image](https://cloud.githubusercontent.com/assets/61299/9428722/fc073f1e-49af-11e5-956b-16596238c0b7.png)

Do you get any difference when running with 

    ./mypaint -c /tmp/mypaint-confarea-throwaway-1

from within the source tree?

**Comment by ydahhrk** [comment]
> Can you investigate whether reinstating any of the lines deleted by 6048998 fixes the problem?

Ok, I'm confused.

Yes; reverting this file does fix the problem (I'm going to try line by line shortly). But was this commit included in the 1.2.0-beta.1+gitexport.a7012b4 pseudo-release?

I realize I might have not explained myself that well, so here's what happened:

1. I upgraded to 1.2.0-beta.1+gitexport.a7012b4. The icons moved to the left.
2. I started painting.
3. _while I was painting_, the icons disappeared at some point.
4. Then I tested with the latest master, and the icons remained invisible.

So yes, that you don't see it a freshly-installed VM is expected. There's something that seems to trigger it. But the fact my active state (~/.mypaint) has nothing to do with it baffles me.

> Do you get any difference when running with

> ./mypaint -c /tmp/mypaint-confarea-throwaway-1

> from within the source tree?

Nope. The icons are still invisible.

**Comment by ydahhrk** [comment]
I FORGOT TO MENTION.

I'm not using Unity; I'm using gnome (`apt-get install gnome-session-fallback`)

**Comment by ydahhrk** [comment]
>  I FORGOT TO MENTION.

> I'm not using Unity; I'm using gnome (apt-get install gnome-session-fallback)

Oh, never mind, I guess.

Switching back to Unity doesn't fix it.

**Comment by ydahhrk** [comment]
These ones:

	col.set_sizing(Gtk.TreeViewColumnSizing.FIXED)

If I comment them out, the icons return.

**Comment by ydahhrk** [comment]
This works tho:

	col.set_sizing(Gtk.TreeViewColumnSizing.FIXED)
	col.set_fixed_width(24)

Can I pull request this? :>

**Comment by achadwick** [comment]
Thanks for the patch - I'll assume it fixes the issue you've been seeing :)

**Comment by ydahhrk** [comment]
Thank you for your time! (^_^)/ \(^_^)
