### ISSUE TITLE
Not drawing,only other preferences.

### ISSUE THREAD

**Issue by robbieb480** [mypaint/mypaint#422]
At first my tablet pen always showed a color history bar show up when i pressed down. I ended up going to preferences and saw "button 2" had color history so i put no action. Now i"m frustrated because nothings happening at all I cant draw it never works please help me. Every other preference button works but I just don"t see draw or anything like that. at least before when it was on color history it went back and forth draw"d and went back to color history. it works with every other software,and i"m angry with this huge bug because i really love this software i bought my huion tablet just for this software and now i"m being surprised to all these bugs. my mouse works but not my tablet i have a windows 8 and i think i have one of the latest softwares.if you have a way of setting up preferences or fixing this issue please respond. Thank you.Hello thank you for your advice it has been very helpful, but i ended up fixing it by troubleshooting and testing. if this problem continues to occur randomly, and the measure that i have took does not work again i will come back and repost. thank you!

**Comment by achadwick** [comment]
Um, it shouldn't be doing that. Nib should always be button 1. Does the Huion work with the GIMP?

What version of MyPaint are you using please, and what version of the Huion drivers?

You can reset your MyPaint preferences to the way it was before by following the instructions in the FAQ <https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset>. Maybe that would help you out here?

**Comment by achadwick** [comment]
It looks as if this might be a feature request as well?

I'm afraid I can't really help here. MyPaint isn't designed to work with nonsensical input, and it sounds like your tablet is sending button 2 for its nib. Which simply isn't right.

Right now, I've no development plans to allow the draw functionality to be moved to anything other than "button 1", i.e. painting normally.

Please try updating to to the latest Huion drivers from their website: the ones shipped with tablets can often be quite shockingly out of date. In fact, it may be better to uninstall the drivers and reinstall them just in case you have any broken tablet settings.

(Oh, and could you paste the model number in to this issue just in case anyone else is searching our tracker? Thanks!)
