### ISSUE TITLE
Consider a "Discard" option on the recovery screen? 

### ISSUE THREAD

**Issue by yuvilio** [mypaint/mypaint#423]
Sometimes i have recovered images that were just drafts.  I have to use "Recover and Save" and then close the app and discard to get rid of them.  It might  be nice to just have a "Discard" button to tell mypaint to discard the item (maybe to the right or left of "Recover and Save" button?).

![sw-0031](https://cloud.githubusercontent.com/assets/128731/9769681/34fc9050-56f1-11e5-9632-e63f2afdc3ee.png)

**Comment by achadwick** [comment]
The current system is intended to force a choice :D but maybe.

The discard button should leave the dialog open. Practically, it's a dialog, and those buttons are coded responses, so leaving the dialog open will need the code to be tweaked before it can do the workflow you suggest. Also, the addition of an extra button requires a new string for translation, so we can't do that before the release.

(There are a few systems with "keep" checkboxes we could try too, but I'm not sure how well that would play with a {choose one}→{do something with it} workflow.)

**Comment by yuvilio** [comment]
Right,  I'd select each of the backup items shown and hit Discard and mypaint would forget all about it. The onus is still on me to tell mypaint to not worry about those anymore. The dialogue would remain open until i accounted for all of them (or chose one of the other options like Ignore for Now).

**Comment by nekohayo** [comment]
Generally speaking, the current system does not seem to take into account the age of the backups vs the saved file I'm opening in the case of issue #505 (in my case, the file I'm opening thus turns out to be more recent than the automated snapshots, because I've started doing ctrl+S _very_ often...). Or perhaps I renamed the file in question since then. In any case, I am indeed presented with a dozen stale backups if I start mypaint, so it might make sense for such corner cases to have a way to dismiss them.

**Comment by achadwick** [comment]
Right now, tidy-up is manual. We could automate the removal of doc.XXXXXX cache folders without autosaves, I guess - they might hold external file layer data as well, though.

You can drive autorecovery from the menus (see #505), but there's a bad current-file-path handling issue you want to be aware of right now if you do that: #508.

**Comment by odysseywestra** [comment]
An alternative thing we can do is add a checkmark box for "show on start up" to both it window and the settings window. It will at least alleviate the headache of having it pop up every time you open MyPaint if we do not need to recover a file just yet.

**Comment by achadwick** [comment]
It was fairly easy to do, so I implemented both ideas:

![image](https://cloud.githubusercontent.com/assets/61299/12803813/5b15cb90-cae5-11e5-97e6-22204fbab81d.png)

But is that maybe too much UI? Anyway, please send patches/bugs/suggestions to new PRs or issues and I'll take a look at them.

**Comment by odysseywestra** [comment]
We should also get this merged in to the 1.2.x branch as well since it truly needed on windows.

**Comment by achadwick** [comment]
@odysseywestra I'm loath to merge new features to patch releases, but I could if there are a LOT of crashers, and by that I mean more than ⅓ of sessions ending in a hard crash for all users on Windows. Why is it needed so much? Feel free to link trouble reports!

Reopened and retargeted while we discuss a backport into 1.2.1. This is in already for 1.3.0 series on master, but it's still in flux and subject to testing. We can keep this issue open till the new feature is finalized and "Decide Later" of course. Perhaps cherry-pick and squash close to the 1.2.1 release?

(We shouldn't be doing this routinely for new features. At all.)

**Comment by yuvilio** [comment]
Don't think it's too UI . Seems to cover the recovery options nicely.

**Comment by achadwick** [comment]
Okay, this hasn't gained enough support for merging into the 1.2.x branch. 

Retargeting and closing. Please test in master.
