### ISSUE TITLE
AssertionError when importing brush pack "Brushes-08.zip"

### ISSUE THREAD

**Issue by KrowofAgony** [mypaint/mypaint#425]
When the brush pack Brushes-08.zip imports, the following error is displayed afterwards:

```python
Mypaint version: 1.2.0-beta.1+gitexport.a7012b4
System information: Windows-post2012Server-6.3.9600
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint/gui/drawwindow.py", line 764, import_brush_pack_cb(self=<DrawWindow object at 0xce6cdc0 (MyPaintDrawWindow at 0xd772290)>, *junk=(<MenuItem object at 0xf0ed9b0 (GtkMenuItem at 0xf588610)>,))
            for groupname in imported:
                workspace.reveal_tool_widget("MyPaintBrushGroupTool", (groupname,))
  variables: {'groupname': ('local', u'08-ink'), 'workspace.reveal_tool_widget': ('local', <bound method Workspace.reveal_tool_widget of <Workspace object at 0xcef3be0 (MyPaintWorkspace at 0x29f23c0)>>)}
  File "C:\Program Files\MyPaint\share\mypaint/gui/workspace.py", line 418, reveal_tool_widget(self=<Workspace object at 0xcef3be0 (MyPaintWorkspace at 0x29f23c0)>, tool_gtypename='MyPaintBrushGroupTool', tool_params=(u'08-ink',))
                )
                self.add_tool_widget(tool_gtypename, tool_params)
                return
  variables: {'self.add_tool_widget': ('local', <bound method Workspace.add_tool_widget of <Workspace object at 0xcef3be0 (MyPaintWorkspace at 0x29f23c0)>>), 'tool_params': ('local', (u'08-ink',)), 'tool_gtypename': ('local', 'MyPaintBrushGroupTool')}
  File "C:\Program Files\MyPaint\share\mypaint/gui/workspace.py", line 463, add_tool_widget(self=<Workspace object at 0xcef3be0 (MyPaintWorkspace at 0x29f23c0)>, tool_gtypename='MyPaintBrushGroupTool', tool_params=(u'08-ink',))
                        if stack.add_tool_widget(widget, maxnotebooks=3,
                                                 maxpages=maxpages):
                            added = True
  variables: {'maxpages': ('local', 1)}
  File "C:\Program Files\MyPaint\share\mypaint/gui/workspace.py", line 1527, add_tool_widget(self=<ToolStack object at 0xcef81e0 (MyPaintToolStack at 0xd7296c0)>, widget=<BrushGroupTool object at 0xf0e7230 (MyPaintBrushGroupTool at 0xfa31ba0)>, maxnotebooks=3, maxpages=1)
            # Last one should always be the placeholder...
            assert target_notebook is not None
            # ... but don't always just use it.
  variables: {'None': ('builtin', None), 'target_notebook': ('local', None)}
AssertionError: 
```

This issue applies to MyPaint 1.2.0 beta+1gitexport.a7012b4.

**Comment by achadwick** [comment]
Where did you get the brush pack "Brushes-08.zip"? We do not distribute any file by that name.

**Comment by KrowofAgony** [comment]
Actually, yes you do:

https://github.com/mypaint/mypaint/wiki/Brush-Packages

It is under the "08" section.

Stop lying through your teeth.

K, thanks.

-Krow Mitxel

Date: Sat, 12 Sep 2015 14:31:40 -0700

**Comment by achadwick** [comment]
> Stop lying through your teeth.
> 
> K, thanks.

Please drop the accusatory and dismissive tone: it helps no-one in a project that relies on volunteers to operate.

I was mistaken, and I freely apologise for the error.

The gna.org site is not the supported download site for MyPaint currently (that would be the Github release page, and <http://mypaint.intilinux.com/?page_id=6>). It once was, however, and that is where the confusion arose.

The wiki page you have linked to also links to many third-party brush packs which do not carry any sort of support in MyPaint. That could certainly be made clearer. Since the download site is no longer supported, I should probably move that brush pack too, assuming it can be made to work. Since we do historic releases on Github, it could reside happily with 0.9's release.

**Comment by achadwick** [comment]
Right, reproduced. Thanks for the link to where the pack was to be found.

The failure is interesting in that it's a workspace-only problem that hits the second brush *group* to be loaded from the pack, if the set iteration order in the associated log messages it to be believed:

```
INFO: gui.brushmanager: 281 different brushes found in order.conf of brushpack
INFO: gui.drawwindow: Imported brush groups set([u'08-Tanda', u'08-all', u'08-ink', u'08-Ram\xf3n', u'08-Ico-dY', u'08-Deevad', u'08-classic', u'08-experimental'])
```

All of these groups are available if the user chooses to ignore the exception, although that's hardly obvious or helpful. The problem only lies with scripting the reveals of the corresponding group tabs.
