### ISSUE TITLE
KeyError 'scala'

### ISSUE THREAD

**Issue by Rolliboy** [mypaint/mypaint#426]
I have built the new version 
1.2.0-beta.1.96+gitexport.0451151
using MySys64, Win-10 64bit 

At startup I got this error:
```
...
...
  variables: {'params': ('local', {'rotation': 0.0, 'scale': 100.0}), 'template.format': ('local', <built-in method format of str object at 0x0000000018aa7bb8>), 'label.set_text': ('local', gi.FunctionInfo(set_text))}

KeyError: 'scala'
```

**Comment by achadwick** [comment]
That's not enough to go on, sorry - I need the full exception trace to figure out where in the code this is coming from.

"`scala`"? It is possible that this is a bad translation, judging from the string formatting. Please paste the output of `locale -a` and `locale` too.

**Comment by achadwick** [comment]
Yeah - looks like our Italian translators have translated the variable name used when interpolating strings...

```
./it.po:"Z: {scala:.1f}%\n"
```

I'll fix that pronto. The only bit of that string that wants translating are the `Z` and `R` prefixes for zoom and rotation, and maybe the `%` mark - but you can see how it's come about; Python braces-format can sometimes be tricky to understand.

**Comment by achadwick** [comment]
(I guess it's obvious what's going on now - presumably you're using the Italian translation, @Rolliboy ?)

**Comment by Rolliboy** [comment]
You're right, I'm Italian and my locale is it-IT.

I'm facing a problem installing GTK+3 on eclipse pyDev, any link or suggestion? tnx

**Comment by achadwick** [comment]
Sorry, I'm not familiar with eclipse. Shell and Vim FTW :grinning:

If you're able to test that the latest master compiles and runs in your environment, that would be great. Please reopen this bug if this issue returns after a `git pull`.

**Comment by Rolliboy** [comment]
OK updated, compiled and no more errors!
Shell & Vim OMG! :dart: 
tnx
