### ISSUE TITLE
Set up an AppVeyor build for Win32/Win64 CI

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#428]
We've been using [MSYS2](https://msys2.github.io/) as a way of getting MyPaint built on Windows for a few months, with a manual tester's build process documented in [README_WINDOWS.md](https://github.com/mypaint/mypaint/blob/89679e4a4aca734837bdd1531e41ccf5430fb332/README_WINDOWS.md). There is also an automated installer-style build cobbled together in the [windows/](https://github.com/mypaint/mypaint/tree/89679e4a4aca734837bdd1531e41ccf5430fb332/windows) subdirectory. It works pretty well, and people have been testing and play with our code properly on another platform now :smile:

Currently we use Travis CI for the Linux platform, which has proven a helpful canary for broken tests. We should have some form of CI for Windows too, and [AppVeyor](http://www.appveyor.com/) seems like the right fit there: we already do a minimal build of [libmypaint](https://github.com/mypaint/libmypaint) on AppVeyor, after all.

The AppVeyor guys have just added support for MSYS2: appveyor/ci#352, which is excellent news. It looks pretty standard from this high up; looking at the list of [installed software on their build workers](http://www.appveyor.com/docs/installed-software), the only potential clashes I can see is that there's an install of (?native) MinGW, MSYS, Cygwin, and Python on there too. Hopefully our PATHs will be sensible for the build.

**Comment by jplloyd** [comment]
First added in 30ee09c484ae3aff021ffbe5d95bdae6bb16d123 and still ticking. Just cleaning up addressed and outdated issues.
