### ISSUE TITLE
Ever-increasing delay/lag after flipping stylus

### ISSUE THREAD

**Issue by Cyroz** [mypaint/mypaint#429]
First when I start everything works fine, but as I keep drawing the lines keep getting more and more delayed. The problem was when I flipped my stylus to erase.
The first time I flip it works fine and there is no delay. Then it starts getting more delayed every time I flip between the eraser and the pen and then it also stops switching between the eraser and pen and just gets stuck on one of them while still having a big delay. I use Windows 10, Wacom Intuos Pro 5 with 6.3.14-1 driver version and Mypaint w64 0.73

**Comment by achadwick** [comment]
Hi there - thanks for reporting!

* I'm assuming "Mypaint w64 0.73" means "MyPaint-w64 1.2.0-beta.0.73" ☺
* Please report separate problems as separate issues - thanks! Doing this allows us to track and close them meaningfully.
* Please provide more useful bug report titles when reporting bugs. It's more helpful to everyone if you have a summary up there!
* Please could you upgrade to the latest beta, https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.1 and re-test? Thanks.
* Is the mouse thing like the one mentioned in point 2. of #373 ? If so, please raise this as a separate issue.

I'm only going to address the most serious problem in this issue thread. Gotta keep this issue tracker tidy!

Additional delays on subsequent device switches seems really weird. I have similar input hardware and driver software available for testing under Win7, so I'll take a look at it. However do you get any lag like #390 ? the causes might be related, since there seems to be a profile of worsening lag there.

**Comment by Cyroz** [comment]
I updated to the one you linked and still had the problem. The delay effect I get is more like slow position tracking and not really "laggy". The delay seems to come to a stop after a while, it's a bit hard to test since the switching also seem to stop working after a bit. I noticed I have the same problem in Mypaint 1.0 and now I'm pretty sure it has something to do with the latest driver 6.3.14-1 from Wacom. I haven't had this problem with any other software yet. I can't confirm this because Wacom apparently doesn't have the old versions anymore. I didn't have this problem before when I used the old Mypaint and the update is really the only thing that has changed.

**Comment by achadwick** [comment]
Thanks for testing that. There are some videos in that #390 bug report if you want to see what others have observed.

I'm a bit confused by your last comment - you seem to be saying that you had the same problem in MyPaint 1.0, and also that you _didn't_ have this problem before when you used "the old MyPaint" (I'm assuming that means v1.0). Though if you updated the Wacom drivers in the intervening period too, I guess we can't really draw any conclusions about which program/driver/library's at fault :disappointed: I'll see what I can do about trying to replicate this myself with what I have available.

**Comment by Cyroz** [comment]
I updated the driver right before using the 1.2 Beta Mypaint.
My delay didn't look like the one you linked.
 I found an older version of the Wacom driver (6.3.11-4) and I can confirm the problem was with 6.3.14-1. Basically all problems I had disappeared when I switched back. Switching between both sides of the stylus works fine and there is no delay and I can use my mouse fine too.

**Comment by Bluustreak** [comment]
I have this problem as well, or at least something very similar and most likely related to the same issue. You be the judge.

I'm using Windows 7, 16GB ram, GTX760, and a Pentium G3258 clocked to 4.4Ghz

When I start MyPaint up, everything's fine, then after a few minutes, it gets slower, then after a little while more and more and more slow, until the brush is "lagging", as in being delayed, up to 5 seconds after the stroke has been drawn(!)
This is without ever flipping the pen.

I don't recall haivng this issue on Linux.

MyPaint is great program though, and could be a real SAIkiller when it's done :)

**Comment by achadwick** [comment]
@Bluustreak Can you have a look at the videos in #390 and maybe comment there? That's the older and more established Windows lag bug, and the one to look in if your problem has nothing to do with pen end flipping.

I can't see your screen, so I can't be the judge ;) Wherever you report it, please let us know the version numbers of your Wacom drivers and MyPaint too.

**Comment by achadwick** [comment]
@Cyroz , @Bluustreak : There are a couple of new betas to try: v1.2.0-beta.2 and a special "threadfun" build relating to the other windows lag bug (#390) which may help with this one. Can you give it a try with driver version 6.3.14-1 or later please, and see if it fixes the issue?

**Comment by achadwick** [comment]
No feedback on this, and it might be related to #390 or just a driver bug. Deferring till after the 1.2.0 release for the same reason as #390.

**Comment by achadwick** [comment]
@Cyroz, @Bluustreak 
Please respond.

[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has now been released, and it is bundled with a newer GTK in the Windows builds. Can you test it out please, and report back about whether this issue is still present in it? Thanks.

**Comment by jplloyd** [comment]
No response, or other comments, for >3 years. Assumption: no longer an issue.
