### ISSUE TITLE
Win10: loading gi extension fails, causing silent error at startup (console debug: "from . import _gi ImportError: DLL load failed: The specified procedure could not be found")

### ISSUE THREAD

**Issue by Sprakle** [mypaint/mypaint#430]
I'm running on Windows 10, using MyPaint 1.2.0-beta.1 64-bit

When I launch MyPaint w64, nothing seems to happen (no error dialogs or messages)

Launching the console debug version results in this error:

	INFO: mypaint: Debugging output enabled via MYPAINT_DEBUG
	ERROR: mypaint: Specialized Win32 argument handling failed. Please help us determine if this code is still needed, and submit patches if it's not.
	Traceback (most recent call last):
	  File "bin\mypaint", line 108, in win32_unicode_argv
		from ctypes import POINTER, byref, cdll, c_int, windll
	  File "D:\Program Files\MyPaint\lib\python2.7/ctypes/__init__.py", line 10, in <module>
		from _ctypes import Union, Structure, Array
	ImportError: DLL load failed: The specified module could not be found.
	WARNING: mypaint: Falling back to POSIX-style argument handling
	INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'D:\\Program Files\\MyPaint'
	DEBUG: mypaint: datapath: u'D:\\Program Files\\MyPaint\\share\\mypaint'
	DEBUG: mypaint: iconspath: u'D:\\Program Files\\MyPaint\\share\\icons'
	DEBUG: mypaint: old_confpath: None
	DEBUG: mypaint: localepath: u'D:\\Program Files\\MyPaint\\share\\locale'
	DEBUG: mypaint: localepath_brushlib: u'D:\\Program Files\\MyPaint\\share\\locale'
	Traceback (most recent call last):
	  File "bin\mypaint", line 450, in <module>
		init_gettext(localepath, localepath_brushlib)
	  File "bin\mypaint", line 251, in init_gettext
		import lib.i18n
	  File "D:\Program Files\MyPaint\share\mypaint/lib/i18n.py", line 20, in <module>
		import gettext
	  File "D:\Program Files\MyPaint\share\mypaint/lib/gettext.py", line 30, in <module>
		from gi.repository import GLib
	  File "D:\Program Files\MyPaint\lib\python2.7\site-packages/gi/__init__.py", line 42, in <module>
		from . import _gi
	ImportError: DLL load failed: The specified procedure could not be found.
	Press any key to continue . . .

**Comment by achadwick** [comment]
Thanks for the backtrace, and the debug mode output. That's a new one.
Can you try a couple of things please?

1. Is there a `_gi.pyd` file anywhere in the installation directory, `D:\Program Files\MyPaint`? Or your AV quarantine area?
  * It should be installed in `%PROGRAMFILES%\MyPaint\lib\python2.7\site-packages\gi`.
2. Does a deinstall/reinstall fix the issue? This can be done safely, and won't kill your personal configuration.
  * Could it have become corrupt, if it's still there?
3. Are there perhaps any permissions issues preventing the file from being read by Python as it starts?

If gobject-introspection is gone, or is refusing to load for any reason, MyPaint won't be able to do anything at all - including error dialogs or on-screen messages.

**Comment by Sprakle** [comment]
1. There is one copy of that file at `D:\Program Files\MyPaint\lib\python2.7\site-packages\gi\_gi.pyd`

2. Uninstalling and reinstalling seems to have fixed it! I had an earlier version of MyPaint installed before, and instead of uninstalling it first, I simply overwrote the old version with the new installer. I bet that's the source of the problem. Unfortunately I don't remember what version was installed before.

**Comment by achadwick** [comment]
That could be it! Glad it's solved.

Yeah, the Inno Setup installer the betas use isn't smart about uninstalling other installations first that might've been made with something else. It should be good about invoking its own uninstNNN.exe though.
