### ISSUE TITLE
Brush Engine Enhancement: Bristle Strokes

### ISSUE THREAD

**Issue by Ico-dY** [mypaint/mypaint#431]
As explained in Mypaint forum, a way to make bristle strokes would be very useful to have: http://forum.intilinux.com/mypaint-development-and-suggestions/bristle-strokes-in-mypaint/

It's practically impossible to mimic many styles/media without it. Is it really hard to make? ^^

**Comment by achadwick** [comment]
Duplicate of mypaint/libmypaint#8, I think.
