### ISSUE TITLE
Packaging: let users choose whether to install translations

### ISSUE THREAD

**Issue by Labyriinthus** [mypaint/mypaint#438]
I took a look at literally all menus. I even tried re-installing it to check if it had a language option, but all I got was an horridly translated & incomplete Korean version of it (Which is, my laptop's language). Wouldn't it be great to have an Language option in the installation session.

**Comment by achadwick** [comment]
What version of MyPaint are you using here?

What operating system are you using?

There is no language option during installation on Windows, Linux, or Mac OS X. MyPaint always uses the system settings. If a translation is incomplete or incorrect, it can be improved online at https://hosted.weblate.org/engage/mypaint/

**Comment by achadwick** [comment]
(Assuming you're using Windows, we could add an option to drop *all* translations and just use the source US English. Beyond that we'd have to get quite clever if Windows users are to be offered a choice.)

**Comment by achadwick** [comment]
Looks easy enough to offer the option to not install the `<prefix>/share/locale` tree, at least for the Windows InnoSetup installer: https://github.com/mypaint/mypaint/blob/master/windows/innosetup/mypaint.iss.in

Other OSes I'm not as sure about.

**Comment by Labyriinthus** [comment]
Um, thank you! I was maybe a little bit rude, sorry about that. I found out that it was easily manually possible by deleting the 'ko' locale folder in C:\Program Files\MyPaintBeta\share\locale. (backed up just in case.) :)

**Comment by achadwick** [comment]
Don't worry about it, all's cool :grinning: TBH it's a nice feature request to have, thank you for reporting it and giving some background story.

The UI language cannot be changed after the program is loaded, and it seems that's just a fact of life with gettext (the third-party library we use to do the on-the-fly string replacement). However if a particular translation is unaesthetic or unusable, users could have the option to not install the "language packs" for MyPaint.

It's even possible to *break the program* with a sufficiently translation of a template string (those things with `{variables_like_this}` in them). So this may have a real practical benefit for users.

I'm only dropping links in case anyone wants to pick this one up for Windows, but there's nothing particularly platform-specific about this issue.

I've been rattling the collection tin on Twitter asking for some assistance and eyeballs on the Korean translation. Hopefully that'll help :)

I'll retitle this one and have another look at it after the 1.2.0 release.

**Comment by achadwick** [comment]
94be81071209fb83df0ff29e47912cbd37d4f75e addresses this for Windows users: there is now an "Install translations" checkbox during the installer. Expect to see this in the next beta (v1.2.0-beta.3) or the first release candidate for v1.2.0.

Bad translations can be improved by contributing your time and knowledge at <https://hosted.weblate.org/engage/mypaint/>.

**Comment by AlanAlright** [comment]
in Version 1.2.1 (2017-01-21) (Window 10): There is no option showed for translations during the installation process. 
I wanted to change the App language from German to English. I had to overwrite the locale "de" (for German) folder with one of the English ones. It worked.
