### ISSUE TITLE
I can't create a new document

### ISSUE THREAD

**Issue by ianskea** [mypaint/mypaint#445]
I am running  Ubuntu 14.04 and MyPaint 1.2.0~beta.1.168-0dev1ppa1~vivid1

I can't create a new document with File > New Document, Right Click, or with the GUI button.

I can open old documents.

Please advise.

Thank you,

Ian Skea

**Comment by ianskea** [comment]
Maybe I am not understanding that new documents do not have a set size?  Or something like that?

**Comment by achadwick** [comment]
I don't understand what you mean. Do you get any specific error messages? Can you draw strokes? Does the New Document button work?

**Comment by ianskea** [comment]
Hi Andrew, I hit new document and the screen did not seem to change.  I was expecting a document dialogue box?

**Comment by achadwick** [comment]
That's not how New Document works. You just draw then save the results, like in Libre Office or Word.

If you have something already drawn (beyond a very small number of seconds), you will be asked whether you want to save it before the new blank canvas is created.

Anything else happening?

* When you paint, do you get a line, or does nothing appear on screen?
* Similarly, if you draw and then do New Document, does it even give you a new blank canvas? (that would be a bug too)

(Sorry to be awkward, but this issue/bug tracker is not really "for" first-line user support. But if there is a software fault that keeps happening, that is something that should be reported here.)

**Comment by ianskea** [comment]
Yeah -- no worries -- all good.  Sorry for the misunderstanding.  BTW. very nice program.

**Comment by achadwick** [comment]
No problem. Glad it's working OK :)
