### ISSUE TITLE
Using colour picker over the Preview panel from "R" key: raises exception

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#446]
#### Description

When trying to use the colour picker over the preview panel by pressing the "R" key, an exception is raised.

This affects git master as of 3450f85eb32b47214c5d2c30eec023c4e373d72c and ce9819393f172965c17b28dafbb357ac387609fc. I'm using Debian testing+sid, but I suspect the exact GTK/GDK/Cairo package versions aren't very relevant for this one.

#### Steps to reproduce

1. Open the preview panel
2. Move the mouse pointer over it
3. Press the R key.

The exception below is produced in a crash dialog.

#### Traceback

```python
Mypaint version: 1.2.0-beta.1.172+git.77caf48
System information: Linux-4.1.0-1-amd64-x86_64-with-debian-stretch-sid
Traceback (most recent call last):
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/document.py", line 1816, mode_flip_action_activated_cb(self=<gui.document.Document object>, flip_action=<Action object at 0x7fee212228c0 (GtkAction at 0x35b9c30)>)
            if active_doc != self:
                return active_doc.mode_flip_action_activated_cb(flip_action)
  variables: {'flip_action': ('local', <Action object at 0x7fee212228c0 (GtkAction at 0x35b9c30)>), 'active_doc': ('local', None)}
AttributeError: 'NoneType' object has no attribute 'mode_flip_action_activated_cb'
```

**Comment by ncmprhnsbl** [comment]
can confirm this in arch/openbox  , 83a9e7b
