### ISSUE TITLE
feature request: inking mode should support add/delete of control points 

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#450]
Inking mode makes it possible to move control points on a stroke.  How about adding and deleting control points?  

Powerpoint does a nice job on that (to try it, right-click on a curve and select "edit points").
I would suggest the same approach: 
* holding down Ctrl changes the cursor to an X, allowing you to click on a control point to delete it.  (This should be noted in the hint line at the bottom when you're in inking edit mode.)
* hovering over the stroke, but *not* over an existing control point, changes the cursor to a picture of a control point, allowing you to click to add the point there.  Now you *are* over a control point (the new one!) so you can drag it.

**Comment by achadwick** [comment]
Deleting control points is possible using the options dockpanel, but it's a little clunky. Adding nodes is something I'd like in the next phase of development.

See also #227, #339, #224.

**Comment by achadwick** [comment]
Closed with 1a9afb998b5c039114b1000196e6e3a4afef4a8d thru ce6e32ebd15ccf26e003b91d92f85898f1ee1996 extracted from #522. Thanks, @dothiko!
