### ISSUE TITLE
background chooser slows down drawing

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#453]
When the background chooser is open, MyPaint is extremely slow to register and render strokes, even if the background chooser window does not overlap with the drawing window.

This is not a problem when the brush editor window is open.  So it seems mysterious.

**Comment by achadwick** [comment]
Hi - thanks for reporting this.

Could you cut/paste your OS details, and the version of MyPaint you are using, and let me know anything else relevant to this? I also need exact details about the problem if I'm to reproduce this myself.

What does "extremely slow" mean in your report? Are we talking a delay of seconds, or sub-seconds?

Does the problem go away when you close the background chooser window?

**Comment by jeisner** [comment]
Unfortunately I can no longer reproduce it.  :-(  Maybe it was an interaction with some other setting that I've subsequently changed ... or something upstream in X windows ...

For what it's worth: Extremely slow meant a delay of 1-2 seconds, I believe.  The problem went away when I closed the Background window.  At the time, the problem persisted across sessions of MyPaint.

Running Linux Mint 17.
$ uname -a
Linux tree.cs.jhu.edu 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ cat /proc/version
Linux version 3.13.0-37-generic (buildd@kapok) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014
$ lsb_release
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch

**Comment by achadwick** [comment]
Strange. There are few things that happen in the background and hog CPU (like autosave, which can be turned off) and the background window is slow to load the first time for sure. I'll close as WORKSFORME for now though :D
