### ISSUE TITLE
Shift+P has two functions

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#457]
As I understand, a key should never be assignable to two functions, and Edit Preferences... tries to prevent that.
However, Shift+P seems to be assigned (presumably by default) to both Increase Layer Opacity and to Preview.
Both functions are listed on the menus as having Shift+P as a shortcut; what it actually executes is Preview.
I am using 1.2.0-beta.1.168+gitexport.8b4ee65 .

In addition to fixing this assignment, perhaps a build test might be added to warn about double assignments in the default map in future?

**Comment by jeisner** [comment]
Perhaps Preview should be changed to Ctrl+P?
I think Shift+O and Shift+P have historically been Reduce/Increase Layer's Opacity.

(By the way, when I tried to change Preview to Ctrl+P myself in Edit Preferences, this wasn't enough to make Shift+P start working for Increase Layer's Opacity.  To get it to work, I then had to assign Increase Layer's Opacity to a different key and then back to Shift+P.  In short, not only are double assignments bad, but they are even challenging for a user to work around.)

**Comment by achadwick** [comment]
To confuse matters more, there's a layer of fixed, low-priority keybindings for things like the cursor keys and Menu. But this is a duplicate in the defaults for the user-definable keymap and should be fixed because of the difficulties with the duplicate detection in the keybinding editor.

**Comment by achadwick** [comment]
The only heuristic to apply is that more obscure functions should be assigned the fiddlier default binding if there is a clash with something more useful/expected/helpful. In this case, layer opacity is something most people probably wouldn't even expect a binding for, so I'll move them to Shift+Ctrl+{O,P} to resolve the duplication.

It's in the defaults, so unless someone has reassigned it, the change will take effect on the next start of MyPaint.

**Comment by jeisner** [comment]
Are you sure you don't want to just move Preview to Ctrl+P, which is currently unassigned?
Using Shift+Ctrl+{O,P} isn't horrid, I suppose, but it seems unnecessary in this case when it would be possible to keep Shift+{O,P} as in earlier versions.

**Comment by achadwick** [comment]
Could do that too. Maybe we're due a review of the default bindings anyway?

(I definitely want inking mode on its own key, come to think of it)

**Comment by jeisner** [comment]
This is getting off-topic and a full review should probably be its own ticket, but:
Personally I've put inking on I (mnemonic) and flood fill on U (looks like a paint bucket).
So now all the paint tools are near one another (UIOPK) which makes it easy to switch among them.

I/U formerly were assigned to the horizontal/vertical flips.
Perhaps those could be retained on Ctrl+I and Ctrl+U or moved elsewhere.
(I never use them, but I expect they're useful when trying to draw two objects that are roughly mirror images.)
