### ISSUE TITLE
flood fill ignores eraser mode

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#474]
Most of the paint tools can combine with eraser mode.  The tool works the same as before - it just erases instead of drawing.

Flood fill _appears_ to be able to combine with eraser mode in this way.  You can toggle eraser mode on and off, and the eraser icon displays this change of mode.   However, the actual flood fill algorithm just fills with the usual color, rather than the natural behavior - "filling with erasure."

I think it would be **useful** to fill with erasure - among other things, it allows you to undo a previous flood-fill that was on a transparent part of the canvas, or even erase a stroke (if it's completely monochromatic) without affecting other strokes.  It also might be an **easy** extension to the current code.  **However**, if there is some reason not to support fill with erasure, then to avoid confusion, entering flood fill mode should turn eraser mode off, and vice versa. 

(Note when testing this out: You may not currently be able to activate eraser mode by switching to your eraser device - that's bug #448.  But you can do it by pressing E or clicking the eraser icon to put the current brush into eraser mode, either before or after you've selected the paint tool you want.)

**Comment by achadwick** [comment]
Eraser is not really an app-wide boolean flag: it is a proportional brush property.

Should brush alpha count too?

What about the brush's colourize setting?

One answer is "yes, optionally", in which case I can do nothing about this right now because strings are frozen for the upcoming release.

A fundamental reason for saying "no" might be that filling is not done with the brush. But as you say, the toolbar-accessible properties appear to be properties of the program not the brush.

MyPaint may be moving to a multi-brush model (#259) because you can use more than one device at a time with modern hardware. Thus the concept of there being a single central brush may vanish. This report reminds me that we're going to need to be able to apply a consistent set of brush modifiers to all of those device-specific brushes, and that those toolbar buttons need to apply to that.

**Comment by jeisner** [comment]
> Should brush alpha count too?
> What about the brush's colourize setting?

I'd say yes and yes, for reasons below.

> A fundamental reason for saying "no" might be that filling is not done with the brush. But as you say, the toolbar-accessible properties appear to be properties of the program not the brush.

My mental model is that fill mode is a temporary modification of the current brush.  It should keep the color or eraser, alpha, and colourize settings.  The difference is that it doesn't dab; it fills instead.  

The other drawing tools are also temporary modifications of the current brush.  For example, the straight-line tool does dab as usual, but it ignores the pressure of the brush when deciding what those dabs should look like ...

**Comment by jeisner** [comment]
> MyPaint may be moving to a multi-brush model (#259) because you can use more than one device at a time with modern hardware. Thus the concept of there being a single central brush may vanish. This report reminds me that we're going to need to be able to apply a consistent set of brush modifiers to all of those device-specific brushes, and that those toolbar buttons need to apply to that.

I created a new issue #479 for this.  (Summary: I'd actually change the current handling of brush modifiers a bit, even in the single-device world, and I think this solution can be sensibly extended to the multi-device world without having to "apply a consistent set of brush modifiers" to different devices.)

**Comment by jeisner** [comment]
>> Should brush alpha count too?
>> What about the brush's colourize setting?
>
> I'd say yes and yes, for reasons below.

p.s.  And I would also count alpha lock.  

Note that when colourize or alpha lock is turned on, (1) flood fill will have *no effect* if you click on a transparent pixel (just as the brush would have no effect), and (2) perhaps flood fill should be more aggressive when you click on a *non*-transparent pixel.

By (2), I mean that flood fill ordinarily tests whether a reached pixel has the same color as the pixel that was clicked on.  But when in colourize or alpha lock mode, perhaps this test should ignore the same aspects of color that the mode ignores?  

Hmm, come to think of it, I see a reasonable alternative design for flood fill that makes (2) irrelevant:
* If you click on a transparent pixel, then you fill neighbouring transparent pixels (as is true now).  
* But if you click on a non-transparent pixel, then you fill neighbouring non-transparent pixels.
  * The change is that they don't have to have the identical same color.  You just spread out and fill whatever's already on the canvas.
  * Or perhaps you do test that they have a "similar" color.
  * Or better yet, you test they are part of the same stroke, or a stroke done with the same brush settings.

(I rather like the same-stroke version.  Filling an existing stroke, especially with colourize or alpha lock turned on, seems more useful than filling a contiguous region that has absolutely identical color, since with most brushes there will be only a few neighboring pixels with identical color.)
