### ISSUE TITLE
application error when trying to update vector layer from external app

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#476]
Afraid I'm having a devil of a time trying to edit a vector layer using an external app.
There are some issues managing to modify the SVG file at all - I can post those separately.
But when I do manage to do it, I get an error dialog box when MyPaint auto-syncs or when I tell it to sync.
Here is the exception when I tell it to sync.

``` python
Mypaint version: 1.2.0-beta.2+gitexport.7169334
System information: Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.1-rebecca
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/document.py", line 1942, commit_external_layer_edit_cb(self=<gui.document.Document object>, action=<Action object at 0x7f47680f3b90 (GtkAction at 0x221ac90)>)
            layer = self.model.layer_stack.current
            self._layer_edit_manager.commit(layer)
  variables: {'layer': ('local', <VectorLayer u'Vector Layer'>), 'self._layer_edit_manager.commit': ('local', <bound method LayerEditManager.commit of <gui.externalapp.LayerEditManager object at 0x7f4769af0610>>)}
  File "/usr/share/mypaint/gui/externalapp.py", line 289, commit(self=<gui.externalapp.LayerEditManager object>, layer=<VectorLayer u'Vector Layer'>)
                    ))
                model.update_layer_from_external_edit_tempfile(layer, file_path)
                return
  variables: {'model.update_layer_from_external_edit_tempfile': ('local', <bound method Document.update_layer_from_external_edit_tempfile of <Document nlayers=3 bbox=Rect(-576, -192, 1984, 1088) paintonly=False>>), 'layer': ('local', <VectorLayer u'Vector Layer'>), 'file_path': ('local', u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg')}
  File "/usr/share/mypaint/lib/document.py", line 1125, update_layer_from_external_edit_tempfile(self=<Document nlayers=3 bbox=Rect(-576, -192, 1984, 1088) paintonly=False>, layer=<VectorLayer u'Vector Layer'>, file_path=u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg')
            cmd = command.ExternalLayerEdit(self, layer, file_path)
            self.do(cmd)
  variables: {'self.do': ('local', <bound method Document.do of <Document nlayers=3 bbox=Rect(-576, -192, 1984, 1088) paintonly=False>>), 'cmd': ('local', <Edit Layer Externally>)}
  File "/usr/share/mypaint/lib/document.py", line 986, do(self=<Document nlayers=3 bbox=Rect(-576, -192, 1984, 1088) paintonly=False>, cmd=<Edit Layer Externally>)
            self.sync_pending_changes()
            self.command_stack.do(cmd)
  variables: {'cmd': ('local', <Edit Layer Externally>), 'self.command_stack.do': ('local', <bound method CommandStack.do of <CommandStack undo_len=38 redo_len=0>>)}
  File "/usr/share/mypaint/lib/command.py", line 65, do(self=<CommandStack undo_len=38 redo_len=0>, command=<Edit Layer Externally>)
            self._discard_redo()
            command.redo()
            self.undo_stack.append(command)
  variables: {'command.redo': ('local', <bound method ExternalLayerEdit.redo of <Edit Layer Externally>>)}
  File "/usr/share/mypaint/lib/command.py", line 1421, redo(self=<Edit Layer Externally>)
            else:
                layer.load_from_external_edit_tempfile(self._tmpfile)
                self._after = layer.save_snapshot()
  variables: {'layer.load_from_external_edit_tempfile': ('local', <bound method VectorLayer.load_from_external_edit_tempfile of <VectorLayer u'Vector Layer'>>), 'self._tmpfile': ('local', u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg')}
  File "/usr/share/mypaint/lib/layer/data.py", line 804, load_from_external_edit_tempfile(self=<VectorLayer u'Vector Layer'>, tempfile_path=u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg')
            y = self._y
            self.load_surface_from_pixbuf_file(tempfile_path, x=x, y=y)
            redraw_bboxes.append(self.get_full_redraw_bbox())
  variables: {'y': ('local', -181), 'x': ('local', -545), 'self.load_surface_from_pixbuf_file': ('local', <bound method VectorLayer.load_surface_from_pixbuf_file of <VectorLayer u'Vector Layer'>>), 'tempfile_path': ('local', u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg')}
  File "/usr/share/mypaint/lib/layer/data.py", line 262, load_surface_from_pixbuf_file(self=<VectorLayer u'Vector Layer'>, filename=u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg', x=-545, y=-181, feedback_cb=None)
            """Loads the layer's surface from any file which GdkPixbuf can open"""
            fp = open(filename, 'rb')
            try:
  variables: {'fp': (None, []), 'open': ('builtin', <built-in function open>), 'filename': ('local', u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg')}
IOError: [Errno 2] No such file or directory: u'/home/jason/.cache/mypaint/doc._DqR9b/edits/77e88691-c702-474b-9060-adaf2de19076.svg'
```

**Comment by jeisner** [comment]
Hmm, this may be because the SVG file is corrupt.  I tried to edit it using Dia, which might have a bug in SVG export -- neither LibreOffice nor Dia itself likes the resulting file.

**Comment by jeisner** [comment]
Ok, yes, the problem seems to be with Dia.  If you open an SVG file, it will happily save back to that filename, but it will not actually use SVG format  -- for that, you have to use Export rather than Save.

Still, a generic Application Programming Error is not the right way to handle this, is it?  It would be nice to get an explicit error message, saying that the .svg file corresponding to layer "Vector Layer" no longer exists, or is no longer a valid SVG file, as the case may be.  (Yes, I realize that this message has to be translated.)

**Comment by achadwick** [comment]
Might be able to do something a little cleaner for external edits. There's a mechanism in place for nicer error display for regular file loading, and we may be able to re-use the strings.

Inkscape works well for making the external edits, I find, but you should of course be able to use any SVG editing tool.

**Comment by achadwick** [comment]
Those commits should make the exception dialog go away for all the cases I was able to test.

We're repurposing a translated string from another module now, verbatim so we "aren't adding new strings". This should be made more specific as described in the code comment contained in 9de1d48c6bbe324b1a0d7acff37352a52fb30529.

Bumping until after the v1.2.0 release, and redefining as an enhancement (for the string change)

**Comment by jeisner** [comment]
Thanks.  I'll test it when the changes hit the PPA, if that's ok.

**Comment by achadwick** [comment]
@jeisner Is this still happening in v1.2.0 stable?

**Comment by jeisner** [comment]
in 1.2.0+gitexport.f62444e, 
I get no exception dialog if the .svg file is corrupted.
Instead, the vector layer just doesn't update until the .svg file is valid again.

**Comment by achadwick** [comment]
@jeisner Do you get a "Could not load “<UUID>.svg”" message in the footer bar when you corrupt the file? Is this acceptable reporting?

**Comment by jeisner** [comment]
> Do you get a "Could not load “.svg”" message in the footer bar when you corrupt the file? 

Ah, yes, I do get that message (with the name of the file given) when I corrupt the file.

If I explicitly invoke the "Update Layer With External Edits" command:
* If the file is corrupted, the err message in the footer bar comes back.
* If the file is not corrupted, the message instead reports success: "Updated layer ... with external edits".
* If there is no file associated with the layer (because no external editor has been invoked on the layer), then nothing happens.  Shouldn't the command be grayed out in this case?

> Is this acceptable reporting?

Well, evidently I didn't notice the message before. It is rather unobtrusive, and is soon overwritten by another message.

It might be good to have the message be more visible.  Otherwise users might be confused, thinking that the file hadn't changed at all or MyPaint didn't notice the change.  An explicit message saying that the file is missing or corrupted (as appropriate) could help them figure out the problem more quickly.

Of course unobtrusive messages are good in some cases, where you don't want to distract a user who's in the middle of something else.  But in this case, the message is generally the result of an explicit action by the user (perhaps in another program) where they are attempting to update the layer, so I think they would not be distracted to see a pop-up response if something goes wrong.

**Comment by achadwick** [comment]
> * If there is no file associated with the layer (because no external editor has been invoked on the layer), then nothing happens. Shouldn't the command be grayed out in this case?

No, not in that specific case. After invoking the external edit command, there should always be precisely one filename associated with the layer: that created by the most recent external edit. This is the file that gets monitored, assuming you an inotify handles free ☺

**Comment by jeisner** [comment]
>> If there is no file associated with the layer (because no external editor has been invoked on the layer), then nothing happens. Shouldn't the command be grayed out in this case?

> No, not in that specific case. After invoking the external edit command, there should always be precisely one filename associated with the layer: 

Right, but *before* the external edit command has ever been invoked on the current layer, there is no association, so the update command should IMHO be grayed out.

**Comment by achadwick** [comment]
> Right, but before the external edit command has ever been invoked on the current layer, there is no association, so the update command should IMHO be grayed out.

Good plan, but a different use case [after file corruption]. Can you report this as a separate enhancement request please?

**Comment by achadwick** [comment]
> result of an explicit action by the user (perhaps in another program)

That would be an implicit action in my book. Best to present a passive but persitent notification, I guess. The footer message is very much not persistent, hence my asking!

Dialogs raise windows in some WMs, or cause "window is ready" notifications in GNOME (which is better, but not everything does that). Either one interrupts flow.

> I think they would not be distracted to see a pop-up response if something goes wrong.

Popup message dialogs are horrid UI, and I try to avoid them wherever possible. Consider the case where a user is editing multiple external files and they all go wrong → user is spammed with popups.

I've been considering [info bars](https://developer.gnome.org/gtk3/stable/GtkInfoBar.html) for a while now, but they do obscure part of the canvas and can be irritating or confusing if there's a lot of badness happening all at once, depending on your decision about wherther to present the messages as a stack or as a single-most-recent message that's just updated over time.

If the user is to be offered an action to fix the problem, perhaps the ability to open a file browser to examine what's going wrong like autosave recovery, an info bar or a dialog is needed. I prefer info bars.

MyPaint's footer is fairly active, so I don't want to clutter its API with stuff for persistent messages. Better to add new API for persistent info messages with optional actions.

**Comment by jeisner** [comment]
(Added the separate enhancement request as #580; I don't have privileges to label it as enhancement.)

I agree with you about popups being annoying.  If you're willing to add another notification mechanism to MyPaint like info bars, great.  

As you suggest, having a single updatable info bar is much better than multiple popups.  You mention the question of whether it should show one message or many:

* If one message (the most recent): There could be a button or scrollbar to show more.

 * If many messages: Rather than stacking all messages that have *ever* shown up, one option would be to show all *currently applicable* messages.  E.g., once a bad file is repaired, the relevant message would vanish from the middle of the stack.  Maybe the user should be able to dispel individual messages, too.  

* Either way: Presumably the user should be able to close the info bar, although it would reopen when a new message arrived.

**Comment by odysseywestra** [comment]
For the most part, this issue is technically fixed. Yes we could improve the notifications part, but if that become an issue later down the road, we can re-open this.
