### ISSUE TITLE
Write from-source Windows build and install docs

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#48]
(Fallout from #47, which was in the end more of a request for support)

Windows needs good instructions in the form of a README of some sort in the main repository. It should ideally tell _very_ new starters wishing to test directly from git and get involved in the project how to pull, build from source, and test MyPaint by running it on the command line from within the tree. Optionally instructions on how to install it, or make installer bundles would be very useful to have too.

I'm not a Windows user and can barely get off the ground with this stuff as a result, so I'm going to have to leave this to someone else.

@tumagonx - would you be willing to pick this one up? A pointer to existing docs of this nature would be something we could use too.

**Comment by achadwick** [comment]
[MSYS2](http://sourceforge.net/projects/msys2/) was recommended to me on IRC, and seems to have a fine range of libs packaged for it and a decent GTK3 version too. For native builds, it looks as if that would be a very nice system.

I've played around with it however, and the sticking point appears to be scons. The scons package available from msys2's pacman system is essentially tailored only for msys python, not the /mingw64 or /mingw32 native build trees. I've not even been able to work around it with a standalone scons-local for some reason, but I'll give it another go when I have a chance.

**Comment by eanbowman** [comment]
I'm having a bit of trouble even running the MyPaint Python scripts. Do I need a specific version of Python?

$ python mypaint.py bdist
Traceback (most recent call last):
  File "mypaint.py", line 217, in <module>
    console_formatter = logging.formatter(log_format)
AttributeError: 'module' object has no attribute 'formatter'

Incidentally, I got this far even in the git bash prompt in Windows, but this output is from MSYS64 trying to compile a binary. What am I missing? (Total noob here.)

**Comment by achadwick** [comment]
@eanbowman 
We don't use distutils/`setup.py`, if that's what you're trying :/ The build system is scons; have a look at `README.md` for how it works on Linux.

You need a Python 2.7, which should come with the standard [logging](https://docs.python.org/2.7/library/logging.html) module.

Some other little horrors I've noticed:

* Win64 builds against NumPy are considered deeply experimental, apparently. Let's not do that.
  * A native mingw32 build ought to work fine on win64.
* Python extensions you compile need to run on a Python interpreter built with the compiler you used.
  * That's a PITA because Python itself only distributes for MSVC.
  * "Raw" mingwXX can cope with that, apparently. I dunno how. Assuming magic.
  * Maybe it's simplest to grab an msys distro and try to use a completely mingwXX toolchain for the build. scons-local is a thing that may be of some assistance here, if one scons is finding the other's libs or python interpreter or both.

but I'm sort of flailing around in the dark myself on Windows as you can probably tell...

**Comment by eanbowman** [comment]
I knew it. Everything seems to use Python 2.x. Had 3.4.2. It didn't like a lot of things. Getting the app to even run is a good first step. :)

**Comment by achadwick** [comment]
Well, I got a little further with the MSYS2 experimentation. Notes dump: https://gist.github.com/achadwick/498358f65a71f88b85d2

Currently I'm stuck at `pkg-config` misbehaving, but hopefully that can be fixed. Anyone able to help out here?

**Comment by tumagonx** [comment]
Andrew, would you mind to add me in this repo? I could fix part of the buildscript and some typos in mypaint.py. Might be overkill to make a fork for just win32 fixes.

**Comment by achadwick** [comment]
@tumagonx No problem. In fact we should open up developer access much more I think.
(Forks are cheap and merges are easy; but close collaboration is golden).

If we're opening up access to lots of people though, we should begin organizing things by (extremely loose and fluid) team in Github. I hope you don't mind being the first person testing out a slightly new organizational structure. I've created @mypaint/collaborators just now, with read/write access to both current repositories and issue tracker powers. Stand by for an invite! :tada:

The intent of the team setup is to open up access for everything in the repos to our occasional contributors. If anyone else wants access, just ask.

**Comment by achadwick** [comment]
I quite like MSYS2. Hopefully what I'm doing with that doesn't screw things up for other Windows builds.

**Comment by achadwick** [comment]
Little update for people still watching this one: I've just pushed a bag of scripts that generates setup.exe-style installers from a git checkout: https://github.com/mypaint/mypaint/tree/master/windows .  Let me know how practical this is please - and feel free to report new bugs or documentation issues against mypaint for it.
