### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by ryandesign** [mypaint/mypaint#482]
Please release MyPaint 1.2.0 stable. MyPaint 1.1.0 was released almost 3 years ago and does not build on any of the 3 most recent versions of OS X (10.9 Mavericks, 10.10 Yosemite, 10.11 El Capitan) as [reported a long time ago](https://gna.org/bugs/index.php?21981). The 1.2.0 beta versions build fine but users would like to have a blessed stable version.

**Comment by achadwick** [comment]
Hi there! I'm surprised there isn't a bug about this yet. This can be it.

There are a number of bugs and requests which need finishing first, but we're getting there. Time is in short supply though - perhaps you can help?

* Milestone [MyPaint 1.2.0-beta](https://github.com/mypaint/mypaint/milestones/MyPaint%201.2.0-beta)
* Milestone [MyPaint v1.2.0 project management](https://github.com/mypaint/mypaint/milestones/MyPaint%201.2.0%20project%20management)

**Comment by odysseywestra** [comment]
Yup, just like @achadwick said, the fastest way to get MyPaint 1.2 out is
to help tackel the current bugs we have. Plus spreading the word about
getting it translated would help.

**Comment by achadwick** [comment]
Yep - the link to share for the translation service is <https://hosted.weblate.org/engage/mypaint/>.

**Comment by achadwick** [comment]
As mentioned in <https://github.com/mypaint/mypaint/issues/390#issuecomment-168339960> and #564, I'm delegating the Windows binary part of the v1.2.0 release to @tumagonx.
