### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'has_large_base_value'

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#485]
@rolliboy reported when testing for #390:

> My first test with MyPaint-w64 v1.2.0-beta.2 
> zoomed out 50% selected basic pencil and strarting to draw, 
> nothing happens, I can't perorm any stroke
> when I try to close classic brush panel it will not close.
> Then I tried to change tool clicking eraser icon
> this is the error thrown:
> 
> ```python
> Mypaint version: 1.2.0-beta.2+gitexport.7169334
> System information: Windows-10.0.10240
> Traceback (most recent call last):
>   File "C:\Program Files\MyPaint-BETA2\share\mypaint/gui/brushmodifier.py", line 150, blend_mode_eraser_cb(self=<gui.brushmodifier.BrushModifier object>, action=<ToggleAction object at 0x178b3a50 (GtkToggleAction at 0x2c99a20)>)
>                 self._pop_hist(action)
>             self.set_override_setting("eraser", eraser_wanted)
>   variables: {'self.set_override_setting': ('local', <bound method BrushModifier.set_override_setting of <gui.brushmodifier.BrushModifier object at 0x00000000178d14d0>>), 'eraser_wanted': ('local', True)}
>   File "C:\Program Files\MyPaint-BETA2\share\mypaint/gui/brushmodifier.py", line 100, set_override_setting(self=<gui.brushmodifier.BrushModifier object>, setting_name='eraser', override=True)
>                     settings = self.MODE_FORCED_ON_SETTINGS
>                     if unmod_b.has_large_base_value(setting_name):
>                         settings = unmod_b.get_setting(setting_name)
>   variables: {'setting_name': ('local', 'eraser'), 'unmod_b': ('local', None)}
> AttributeError: 'NoneType' object has no attribute 'has_large_base_value'
> ```
> 
> OS:
> Windows 10 Pro 64 bit (10.0, build 10240)
> 
> HARDWARE:
> Intel(R) Core(TM) i7 CPU 930 @ 2.80GHz (8 CPUs)
> 12GB RAM
> 
> GRAPHIC CARD:
> AMD Radeon HD 5800 Series
> Driver: aticfx64.dll v15.200.1062.1004
> DirectX v11.2

Potentially something that's only persisting in user settings. The error handling needs cleaning up, however. I'll see if I can reproduce this from fresh user settings too.

**Comment by Rolliboy** [comment]
please tell me how to clean user settings and I will retry to test

**Comment by achadwick** [comment]
@Rolliboy no problem: docs are at https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset

**Comment by achadwick** [comment]
@Rolliboy BTW, what do you mean when you say "when I try to close classic brush panel it will not close"? That might require yet another issue, but it sounds like you had an error dialog and other breakages on screen at the time (which might be why some normal stuff was not responding - some/all of these dialogs are modal, and block input elsewhere in the program while you're making choices)

**Comment by Rolliboy** [comment]
I mean the brush panel pinched on right side, not modal.
While is open I'm not able to draw anything except using lines tool! 
And of course clicking on closer on that panel does not perform any closing action. 
Only when I click to full screen icon  it seems the application suddenly restarts  without brush panel on the right side..so I'm able to draw again..

**Comment by achadwick** [comment]
@Rolliboy that is something really weird, and probably different from this rather minor exception issue. I can't reproduce it here. Are you able to report it as a separate issue? Exact numbered steps to reproduce it from a fresh config would be ideal.

(I am not using Windows 10, so a fix may take a while.)

You should of course be able to paint while sidebar panels are visible! It reads almost as if you have some sort of weird screen update issue, but I'm pretty certain that's the latest driver for your system (the AMD site has it as "AMD Catalyst™ Display Driver version 15.20.1062.1004").

**Comment by achadwick** [comment]
@Rolliboy I suspect that you couldn't paint because eraser mode was on. Although I'm not certain the setting took effect, given the exception. A fresh config may fix that, and I'm working on a quick fix for this issue (null unmodified_brushinfo) that will at least make this fault go away, hopefully.

Quick Q: is this exception still happening when you open mypaint?

**Comment by achadwick** [comment]
From #390 

> Ok no more exception resetting user config.

Okay, looks like it was settings-related. I guess it's possible to have a null brush in there, perhaps due to other errors. Let's close up this loophole here, anyway.
