### ISSUE TITLE
I have just compiled it on a fresh debian testing. there is no drawing area

### ISSUE THREAD

**Issue by leandrosansilva** [mypaint/mypaint#486]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 1.2.0-beta.2.25+git.b52eab7
System information: Linux-4.2.0-1-amd64-x86_64-with-debian-stretch-sid
Traceback (most recent call last):
  File "/home/tenchi/projects/mypaint/lib/tiledsurface.py", line 293, _get_tile_numpy(self=<lib.tiledsurface.MyPaintSurface object>, tx=-2, ty=-3, readonly=0)
                # assert self.mipmap_level == 0
                self._mark_mipmap_dirty(tx, ty)
            return t.rgba
  variables: {'self._mark_mipmap_dirty': ('local', <bound method MyPaintSurface._mark_mipmap_dirty of <lib.tiledsurface.MyPaintSurface object at 0x7fe264637290>>), 'tx': ('local', -2), 'ty': ('local', -3)}
  File "/home/tenchi/projects/mypaint/lib/tiledsurface.py", line 307, _mark_mipmap_dirty(self=<lib.tiledsurface.MyPaintSurface object>, tx=-2, ty=-3)
                fac = 2**(level)
                if mipmap.tiledict.get((tx/fac, ty/fac), None) == mipmap_dirty_tile:
                    break
  variables: {'None': ('builtin', None), 'tx': ('local', -2), 'ty': ('local', -3), 'mipmap_dirty_tile': ('global', <lib.tiledsurface._Tile object at 0x7fe268487950>), 'fac': ('local', 2), 'mipmap.tiledict.get': ('local', <built-in method get of dict object at 0x7fe26463f5c8>)}
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

**Comment by achadwick** [comment]
Hi, and thanks for reporting. Please fill in the requested parts of the template so that I know what you were doing when you saw this exception.

Do you have `gir1.2-freedesktop` installed? (note for others reading this: non-Debian systems put `cairo-1.0.typelib` in patchages with different names).

**Comment by briend** [comment]
Just had this issue on a new install of debian testing.  I did apt build-dep mypaint and then built from source.  
This resolves the issue:

sudo apt install python-gi-cairo 

This package is installed automatically as a dependency to mypaint but it is not a build-dependency, which might seem odd but makes sense in that I didn't have to recompile anything after installing it.

I think this can be closed.

**Comment by achadwick** [comment]
Yep, it's mentioned in `debian/control` as a runtime dependency like it should be. However it's not listed as a build dependency because it, er, isn't needed at build time. We don't do many package imports of the main code during build. That's why `apt build-dep mypaint` is insufficient.

It's mentioned in the main project's `README_LINUX.md` as well, and the shell line in there covers all flavours of dependency for brevity.

Nothing needed here, I think.
