### ISSUE TITLE
Internal error when dragging/scaling the canvas view

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#488]
This is random and hard to reproduce issue. I only saw it few times, but it's a bit annoying. The frequency is about one time per 6-10 hours of normal painting process.

I cannot reproduce it reliably, but It happen when moving/scaling the canvas view and then or maybe right after painting.

![screenshot from 2015-11-08 17 40 55](https://cloud.githubusercontent.com/assets/4038431/11020888/f33f819e-863f-11e5-830e-115577b7b113.png)

```python
Mypaint version: 1.2.0-beta.2.18+git.f8a94b0
System information: Linux-3.19.0-23-generic-x86_64-with-Ubuntu-15.04-vivid
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/mode.py", line 1070, __pop_modestack_idle_cb(self=<gui.viewmanip.PanViewMode object>)
            if self.initial_modifiers is not None:
                if self is self.doc.modes.top:
                    self.doc.modes.pop()
  variables: {'self': ('local', <gui.viewmanip.PanViewMode object at 0x7f92c4cbae10>)}
AttributeError: 'NoneType' object has no attribute 'modes'
```

The error is pointing to 
```
        if self.initial_modifiers is not None:
            if self is self.doc.modes.top:
                            ^^^ guess here self.doc is None
                self.doc.modes.pop()
```

Shouldn't first `if` be like this?

```
        if self.doc is not None:
```

**Comment by achadwick** [comment]
That initial modifiers test is for things like modes entered by holding key combos and pressing pointer buttons, so it should probably stay. A better test for the second one is probably

```python
    if self.initial_modifiers is not None:
        if self.doc and (self is self.doc.modes.top):
            self.doc.modes.pop()
```

The `doc` property of a mode should be not-None at any point after the mode is `enter()`ed (IIRC), so something's gone wrong here I think.

**Comment by loentar** [comment]
OK, thanks for clarification.
I've changed the code as you wrote directly in installation and will test it few days.
But guess it shouldn't appear anymore and no side effects are expected.

**Comment by loentar** [comment]
The bug don't appear anymore. Also I didn't noticed any side effects.

**Comment by achadwick** [comment]
Thanks for testing and fixing this one. Do you have a patch containing your changes?

**Comment by loentar** [comment]
I just applied changes as you wrote:

replaced:

        if self is self.doc.modes.top:

to:

        if self.doc and (self is self.doc.modes.top):

After that this bug was not reproducible for me.

**Comment by achadwick** [comment]
Thanks - hope that's sufficient. I haven't managed to reproduce this one myself yet, although the surrounding comments seem to give a hint about how it could be done :neutral_face:
