### ISSUE TITLE
"Reposition Layer" should appear on context menu in Layers panel

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#489]
Most operations on a layer are available through the Layers panel.  Some have dedicated buttons.  Others are harder to find -- they appear on the context menu that you get when you right-click on the layer.

However, Reposition Layer is missing.  Maybe an oversight.  Should it be added to that context menu?

(IMHO, it's a reasonable expectation that all operations on layers should be available through the Layers panel.  In part because playing with the Layers panel is probably a common way that users learn what can be done with layers.)

**Comment by achadwick** [comment]
It's a very simple tweak with some benefit, no reason not to. Let's do that.
