### ISSUE TITLE
brushlib/mypaint-brush-settings-gen.h is missing from repo

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#495]
Sorry for the elementary question:
I may be doing something wrong in trying to build mypaint from source. 
However, I carefully followed the directions in README_LINUX.md (twice from scratch), and scons reports a missing file (which is indeed missing, though I have a brushlib directory and plenty in it):
```
gcc -o brushlib/mypaint-brush-settings.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -Wall -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/usr/include/json-c brushlib/mypaint-brush-settings.c
In file included from brushlib/mypaint-brush-settings.c:17:0:
brushlib/mypaint-brush-settings.h:21:40: fatal error: mypaint-brush-settings-gen.h: No such file or directory
 #include <mypaint-brush-settings-gen.h>
```

Also, earlier in the scons build, I get
```
ImportError: No module named numpy
```
and 
```
ImportError: No module named json
```
even though `import numpy` and `import json` work fine at the Python 2.7.6 repl.

**Comment by achadwick** [comment]
What OS and version of MyPaint is this? From where did you get the source and how?

**Comment by achadwick** [comment]
The .h file is probably missing because you did a `scons --clean` (most likely), or because you don't have a properly updated submodule (less likely).

I can't explain why json and numpy are missing in your build environment.

Please prepare a transcript of what you are doing from a fresh clone in a [gist](https://gist.github.com/).

**Comment by jeisner** [comment]
> What OS and version of MyPaint is this? 

Linux Mint 17.1 Rebecca, derived from Ubuntu 14.04.
My git clone of mypaint has HEAD at 60369db, according to `git rev-parse HEAD`.

> From where did you get the source and how?

I precisely followed the instructions in `README_LINUX.md`, installing dependencies and then starting from a fresh clone:
```
  git clone https://github.com/mypaint/mypaint.git
  cd mypaint
  git submodule update --init --force
```

The .h file exists after the last line, but scons appears to delete the .h file, as shown in this gist:
https://gist.github.com/jeisner/7dbf2c4db9f1724909e3

**Comment by achadwick** [comment]
You are still missing the Python `json` and `numpy` modules somehow.

Please paste the complete output of the following

```
$ which scons
$ dpkg -S `which scons`
$ which python2.7
$ dpkg -S `which python2.7`
$ dpkg -l g++ python-dev python-numpy libgtk-3-dev python-gi-dev gir1.2-gtk-3.0 \
  python-gi-cairo swig scons gettext libpng12-dev liblcms2-dev \
  libjson-c-dev libpython2.7-stdlib | cat
```

**Comment by achadwick** [comment]
Please also check that there's not anything shadowing any of the modules MyPaint needs to build or install in `/usr/local`.

**Comment by achadwick** [comment]
FWIW, I can't reproduce this on Ubuntu 14.04LTS using the following script.

```sh
git clone https://github.com/mypaint/mypaint.git
cd mypaint
ls brushlib
git submodule update --init --force
git status
ls brushlib/*settings*
sudo apt-get install g++ python-dev python-numpy libgtk-3-dev python-gi-dev gir1.2-gtk-3.0 python-gi-cairo swig scons gettext libpng12-dev liblcms2-dev libjson-c-dev
scons
./mypaint -c /tmp/cfgtmp$$
```

**Comment by jeisner** [comment]
Ok, I've fixed it and it builds fine now.  The key was `which python2.7`.  Surprisingly, another package on my system has its *own* copy of python2.7 in its own bin directory, which was ahead of /usr/bin on the path.  That's why the problem wasn't showing up when I ran just python (= /usr/bin/python, a symlink to /usr/bin/python2.7).  Thanks and sorry for the trouble.
