### ISSUE TITLE
Website is down: 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#496]
The website (canonical URL http://mypaint.org, which redirects to http://mypaint.intilinux.com/) is down: it has been returning 503 Service Temporarily Unavailable since Thursday. I have set a request for assistance by email to the domain and site owner, Antonio Rosario Intilisano on the 13th Nov, Cc:ed to Jon and Martin, but have had no reply since.

I am raising this issue so that people know we are looking into the matter. Users are starting to ask.

@jonnor, @martinxyz: Do you have any further information about the ownership of this domain, or what agreements have been in place till now to keep it running? I'm just the janitor here.

**Comment by jonnor** [comment]
Didn't we have SSH and/or cpanel login for that host? Can we get a DB dump
/ backup from there?

mypaint.org domain I control, so I can point it where-ever whenever.

**Comment by achadwick** [comment]
@jonnor Digging. In my password safe, I have only personal forums account, website wordpress account, and an unrelated and defunct techmight cpanel one (techmight used to do our DNS and wiki hosting).

DNS hosting and http redirect for the wiki and whatever I pay for over at mythic-beasts.com. It is reliant on Jon's domain glue records for mypaint.org and mypaint.info pointing at the mythic-beasts servers.

**Comment by achadwick** [comment]
Nothing in my email trawl, sorry.

I've set up something that can be used as a placeholder, now accessible on http://mypaint.github.io

Next question is how we wire it in, and for what future purpose. Reading through <https://help.github.com/articles/adding-a-cname-file-to-your-repository/>.

**Comment by achadwick** [comment]
<http://www.mypaint.org> and <http://mypaint.org> should both be pointing at the placeholder now. I've made some DNS changes; recording what I did here so it can be changed back later.

* mypaint.org was:

    @       300     AAAA    2a00:1098:0:80:1000::17 (redirect.mythic-beasts.com)
    @       300     A       93.93.129.94  (redirect.mythic-beasts.com)
    www     300     CNAME   redirect.mythic-beasts.com.

* mypaint.info remains the same, namely:

    @       300     AAAA    2a00:1098:0:80:1000::17
    @       300     A       93.93.129.94
    www     300     CNAME   redirect.mythic-beasts.com.

1. Changed mypaint.org's DNS in the approved manner:

    @       300     A       192.30.252.153
    @       300     A       192.30.252.154
    www     300     CNAME   mypaint.org.
    (removed AAAA record, since github pages don't advertise one)

2. Pushed a CNAME file in the mypaint.github.io repo with just mypaint.org as its content. Apparently this will generate appropriate redirects from one to the other for incoming requests.

3. Tested it works after watching those 300 second DNS cache lines expire :smile: 

4. mypaint.info has to be different, because Github Pages doesn't support more than one entry in a CNAME file as I understand the docs. I have asked mythic-beasts to change the existing HTTP redirect(s) for mypaint.info, but this may only come through by Monday.

**Comment by Deevad** [comment]
Hi, I tried to access files with my old FTP log/pass ; but it's failing ( note: server speaks Italian? )
Good luck and I hope someone still has a backup/access to the old db and CMS.

FTP connexion log:
```
Status:	Resolving address of intilinux.com
Status:	Connecting to 81.174.68.55:21...
Status:	Connection established, waiting for welcome message...
Response:	220 ProFTPD 1.3.5rc3 Server (Unbit) [81.174.68.55]
Command:	USER mypaintftp
Response:	331 Password richiesta per mypaintftp
Command:	PASS *********
Response:	530 Login non corretto.
Error:	Critical error
Error:	Could not connect to server
```

**Comment by achadwick** [comment]
archive.org is no help for quickly slapping up a downloads page: robots.txt exclusion! :confounded:

**Comment by achadwick** [comment]
Google cache to the rescue. http://mypaint.org/downloads/ is up (since it's what people have been looking for)

**Comment by Deevad** [comment]
I found in my backup/archives the themes + community screenshot from the 2011 campaign + the visual I made for the page. I put all in a zip here; http://www.davidrevoy.com/XYZ/2015-11-15_mypaint-web.zip

**Comment by achadwick** [comment]
Thanks for that, @Deevad. Copy stashed!

/Cc: @odysseywestra are you still interested in site development/maintenance?

**Comment by achadwick** [comment]
Looking through http://jekyllthemes.org/ and trying to decide what we'd want, if we were to go that way. This is why I am not a web designer.

**Comment by achadwick** [comment]
I've reinstated a bunch of old pages in text-only mode into the temp site: all posts since March 2014.

**Comment by Deevad** [comment]
> Looking through http://jekyllthemes.org/ and trying to decide what we'd want, if we were to go that way. This is why I am not a web designer.

I just browsed a bit the themes. I like the design of the place-holder website you made on http://mypaint.org/  : something white, simple, classic. Maybe http://jekyllthemes.org/themes/fengzhichu-theme/ 

> I've reinstated a bunch of old pages in text-only mode into the temp site: all posts since March 2014.
Good!

**Comment by odysseywestra** [comment]
I'm still interested in helping designing and maintaining a website for mypaint.

>I just browsed a bit the themes. I like the design of the place-holder website you made on http://mypaint.org/ : something white, simple, classic. Maybe http://jekyllthemes.org/themes/fengzhichu-theme/

This looks good from my end, and scales nicely. It's a good place to start. Dose anybody have screenshots of the old website. I know it's basic layout, but that’s about it. Unless we can get access to the old website somehow, but I think that is impossible right now.

**Comment by zb13y** [comment]
Can you embed twitter instead of news? I think that new users must see, that there are lots of news within project.

**Comment by odysseywestra** [comment]
@zb13y The old website I believe had a twitter embed so yeah well definably try to integrate it again since twitter is doing really good for mypaint. Right now our focus is get the information from the old website to the new one, and make sure it functioning.

**Comment by odysseywestra** [comment]
btw thank you @Deevad for having that backup( I just pulled it down). It will be nice to use some of the old assets on the new one. I'll have to update the screenshots with the ones from #149 but thanks you. If you have any screenshots please post them there, and I'll be sure to use them.

**Comment by odysseywestra** [comment]
@achadwick could you add me as a contributor ? So that way you wouldn't have to deal with PR from me.

**Comment by Deevad** [comment]
Thank you @odysseywestra for taking care of the update of the screenshot ;)

**Comment by achadwick** [comment]
@odysseywestra Invite sent ☺

**Comment by odysseywestra** [comment]
@achadwick @Deevad You welcome and thanks. ^^

**Comment by odysseywestra** [comment]
I've created two new issues at MyPaint's website repository to help keep it organized.

mypaint/mypaint.github.io#1: [Project] Build MyPaint.org Website
mypaint/mypaint.github.io#2: [Project] Setting up Community Fourm

Let me know what your thoughts are.

**Comment by sam-m888** [comment]
FYI, I've updated the MyPaint wikipedia articles broken links as much as I can.

https://en.wikipedia.org/wiki/MyPaint

**Comment by odysseywestra** [comment]
Alright, I finally have a Debian Server hosted on Digital Ocean which is sponsored by Altispeed up. I'm currently setting up discourse in a docker container, but I'm being held up by a couple of things like SMTP server and DNS management. More information over on github: mypaint/mypaint.github.io#2

**Comment by achadwick** [comment]
I think we can basically declare this one closed now that we have a replacement website and forums up and running. We can continue to tinker with it over in <https://github.com/mypaint/mypaint.github.io>.

Thanks @odysseywestra for taking over the website organization and docs, and for running the new [community forums](http://community.mypaint.org)!
