### ISSUE TITLE
Key bindings do not survive a restart unless they're assigned twice.

### ISSUE THREAD

**Issue by ydahhrk** [mypaint/mypaint#497]
"Color Details Dialog" and "Edit Frame".

1. Reset all configuration, start MyPaint.
2. Assign a shortcut to one of the aforementioned actions.
3. Restart MyPaint. Shortcuts are no longer there.

It's because MyPaint writes the shortcut as a comment in `accelmap.conf`. This is probably because the relevant action's "changed" field is False.

1. Reset all configuration, start MyPaint.
2. Assign a shortcut to "Colors Details Dialog".  
   MyPaint says `INFO: gui.accelmap: Adding new entry 't': '<Actions>/WindowActions/ColorDetailsDialog'`. [This means "changed" is False](https://github.com/mypaint/mypaint/blob/fd4ea161847f1288f10918bb2c4a6726e594574f/gui/accelmap.py#L488).
3. Assign some other value.  
   MyPaint says `Changing entry 'g': '<Actions>/WindowActions/ColorDetailsDialog'`. [This means "changed" is True](https://github.com/mypaint/mypaint/blob/fd4ea161847f1288f10918bb2c4a6726e594574f/gui/accelmap.py#L482).
4. Restart MyPaint. Shortcut is still here.

So, it's weird that these actions are the only ones not present in `Gtk.AccelMap` by default... but shouldn't it write them in the file anyway?

**Comment by achadwick** [comment]
For the record, what OS are you using, and what revision of MyPaint did you see this behaviour in?

Is it reproducible with a clean config (`mypaint -c /tmp/throwawaycfg$$`)?

**Comment by ydahhrk** [comment]
> what OS are you using

Ubuntu 14.04

> and what revision of MyPaint did you see this behaviour in?

fd4ea161847f1288f10918bb2c4a6726e594574f

> Is it reproducible with a clean config (mypaint -c /tmp/throwawaycfg$$)?

Yes

**Comment by ydahhrk** [comment]
Oops, sorry WTF. I meant acd6698a123d3cdf4adb9605a380173d095e7a8b

**Comment by ydahhrk** [comment]
I think I found the reason.

"Color Details Dialog" and "Edit Frame" are the only actions absent from the menus. (File, Edit, View, Brush, etc.)

Because they aren't in the menus, nobody registers them to `Gtk.AccelMap` during initialization. For this reason, when the user applies shortcuts to them, they are being set for the first time. In other words, `AccelMap` thinks they are being initialized, not overridden. So it doesn't know it has to write these shortcuts as non-comments in the file.

I'm going to propose a fix in a few minutes.

(Not that it matters as far as this issue is concerned, but: Why aren't these options not in the menus?)
