### ISSUE TITLE
Huion GT-190 - Pen Buttons Don't Work Properly

### ISSUE THREAD

**Issue by KyuuGryphon** [mypaint/mypaint#500]
I'm not sure where else to ask this, I apologize if this is the wrong place.

Details:
OS: Windows 7 Professional (64-bit)
Tablet: Huion GT-190 Pen Display (Drivers are up-to-date)
MyPaint: 1.2.0-beta.2.0.threadfun+20151029

Before getting a GT-190, I used a Wacom Intuos, which I had no problems with. I've tried multiple other art programs, and haven't encountered this issue on any of them.

Specifically, the input seems to get stuck between two "modes", so to speak. In regular mode, while I can draw just fine using the pen, if I have the side buttons assigned to mouse clicks, they simply don't do anything in MyPaint. Setting them to keyboard keys, oddly enough, works. Even using the mouse itself doesn't work in this mode - the left mouse button will draw, but the right mouse button and clicking on the wheel do nothing.

In the secondary mode (which I'm not entirely sure how to trigger - at times, it seems to be triggered just by opening the start menu, while at others I can't even get it to happen deliberately), the situation is reversed - the right mouse button and middle-clicking will do what they're assigned to do (including via the tablet pen itself), but drawing doesn't work correctly - it produces a sort of "jittering" effect, interpreting one long drawn line as many small, short, hard presses. I'm not sure how to explain it, so image attached.
![mypaint_strokebug](https://cloud.githubusercontent.com/assets/2258511/11235043/c507459c-8d82-11e5-8abf-2dfd8c876742.png)

I've tried multiple versions of MyPaint, both 32 and 64-bit, as well as changing the GTK Input Device settings and reinstalling the tablet drivers, and the same behaviour is always exhibited. I really like MyPaint's different blend brushes, but it's extremely irritating to use properly. 

Oddly, running the debug console version of MyPaint works just fine, which I guess suffices as a workaround, but...

**Comment by achadwick** [comment]
Hi @KyuuGryphon - thanks for reporting!

Does it look like the glitch in #177 at all? Difficult for me to tell. The little dot on the end (or start?) is something I haven't seen before. There's a recent fix in on the development master branch for #177, but it hasn't made it into a release yet. Soon!

**Comment by achadwick** [comment]
@KyuuGryphon Quick thing to try - can you open the Input Device test window (Help → Debug → Test Input Devices…) and try drawing something? The "Device" header should stay the same throughout and not flicker between two names; let me know if that line doesn't stay static while in "glitch mode".

**Comment by KyuuGryphon** [comment]
Hi - Thanks for the quick response!

With regards to #177 - #177 looks (to me) as if it's still drawing a single, unbroken line (just deformed along an axis), while the issue I'm having is creating disjointed lines.

It actually occurred to me on reading your comment that the behaviour I get when in "glitch" mode differs between the 1.2.0 beta and an older 1.0.0 build. The previous image was from the beta, here's what happens in 1.0.0:
![mypaint_strokebug_1](https://cloud.githubusercontent.com/assets/2258511/11248617/e4fa615a-8dd6-11e5-8ee6-4db9cb93f349.png)

Every "pulse" along the line (where it gets thicker) separates the line into multiple penstrokes - using the undo button will only erase lines segment-by-segment.

As far as the Device header on Input Device Test goes - when in "regular" mode, the header reads "HUION Tablet Huion", but while in "glitch" mode, it reads "Core Pointer". Having said that, I'm still not entirely sure on a way to deliberately invoke the glitch mode.

Hope this helps!

**Comment by KyuuGryphon** [comment]
Bah. Update.

On MyPaint 1.2.0beta, it turns out that the line behaviour isn't actually creating disjointed lines as I thought it was - they're continuous, so it might be the same kind of thing as what's happening in #177? Not sure.

Also, it turns out that whatever caused it to start working properly in the first place wasn't actually the debug log - I just had it exhibit the same glitchy behaviour with the debug log open, though mucking about with the Huion driver settings with MyPaint open seemed to fix it...

Going to see if I can get anything useful out of the debug log here.

**Comment by KyuuGryphon** [comment]
Update.

Tried running both the 32-bit and 64-bit versions of the latest beta. They're both producing nearly identical behaviour, and it's even more broken than before.

On the current beta, I just cannot draw using my tablet pen altogether, without doing... something I'm not sure of, which only works for one pen stroke. I can still select menu items via the touch screen, but trying to actually draw floods the debug console with this:

`DEBUG: gui.freehand: Ignoring event from (gtk.gdk.DeviceWintab object at 0x1055CBE0 (GdkDeviceWintab at 0x2CC00C0))`

The 32-bit version behaves the same, but provides different addresses:

`DEBUG: gui.freehand: Ignoring event from (gtk.gdk.DeviceWintab object at 0xC555DEC (GdkDeviceWintab at 0x284F0A8))`

"Glitch mode" (which seems to be enabled by trying to use the side buttons on the pen in MyPaint when focused on another window) still produces the same flood as before, constantly switching devices between the tablet and a default system pointer. In the current beta, though, instead of drawing distorted or disconnected lines, it sort of... trails off, like this:

![mypaint_strokebug_3](https://cloud.githubusercontent.com/assets/2258511/11320338/74b05640-904a-11e5-93ce-d69c1df324ec.png)

**Comment by tumagonx** [comment]
@KyuuGryphon
Does run in compatibility mode to e.g. to XP help the issue?

**Comment by KyuuGryphon** [comment]
Just tried that - It does not.

**Comment by achadwick** [comment]
I hate having workarounds for upstream brokenness. They are so likely to break for differing hardware.

@KyuuGryphon looks like you're tripping over ab2bb78ae81efeebd563f5759239c41ccfaa82f8, which it might be good to revert if it screws up Huions. It was introduced as a prospective fix for #460, which it didn't fix, bit it was kept because it seemed to improve #177 on the Surface Pro. It makes freehand mode ignore motion events after a button-down event from those devices which didn't send the button-down.

This may also be related to c8a84143baefc5b58e8ef9dc33e632a909beaf53, a workaround for Linux evdev tablet drivers (used for Genius, Monoprice, UC-Logic, and Wacom if you're silly enough to use evedev with Wacom hardware) that send zero-pressure events if the pressure doesn't change while painting (#29).

**Comment by achadwick** [comment]
@KyuuGryphon Please can you try the `gui/freehand.py` replacements in <https://gist.github.com/achadwick/7d7232bde3ce41068a6a> in place of the gui/freehand.py in your glitchy MyPaint install?

* "freehand (revert1).py" reverts just the most recent commit, ab2bb78ae81efeebd563f5759239c41ccfaa82f8
* "freehand (revert2).py" reverts both ab2bb78ae81efeebd563f5759239c41ccfaa82f8 and the earlier c8a84143baefc5b58e8ef9dc33e632a909beaf53

Deployment: download from the gist using the Raw button, then just copy them into place over the existing `gui/freehand.py` while MyPaint isn't running. Make a backup copy first.

**Comment by KyuuGryphon** [comment]
Tried using both of those - that does seem to be the cause of not being able to draw on 1.2.0b3, yes.

**Comment by achadwick** [comment]
@KyuuGryphon just to confirm, substituting "freehand (revert1).py" (i.e. reverting ab2bb78ae81efeebd563f5759239c41ccfaa82f8 alone) is sufficient here?

If so, that would be... um, ... interesting for the assumptions and we're making about drawing, which are probably best expressed as:

1. You don't always get a button-1-down and button-1-up event for a single brushstoke;
2. But when you do, they will always at least appear to come from the *same device* as the motion events forming the body of the stroke;
3. Therefore it's OK to give all button-1 events the lead-in- and tail-out-to-zero pressure treatment when the button events happen, treating them as faked zero-pressure motions. Because that really helps with low-res mouse input - users often keep their mouse stock-still when releasing the button.
4. And it's OK to use the button being down as a filter for the evdev bug.

Man oh man.

**Comment by KyuuGryphon** [comment]
Well, both substitutions restore the ability to actually draw in normal mode. The side buttons still don't work properly, and "glitch" mode still occurs and behaves as before. I still can't figure out how I managed to actually allow me to use the side buttons and the main pen at the same time.

**Comment by achadwick** [comment]
Okay, I've done the minimal necessary revert on master. I realize this doesn't make the glitches go away for Huion GT-190 users on Windows 7, or restore their ability to use the side buttons (which I assume are button2 and button3, like on a Wacom).

I'll have to defer this for now in the absence of testing hardware, but I'll look at it again after the release.

@KyuuGryphon The GT-190 is a bit pricey for chasing this one bug. I'm tempted to get a cheaper Huion like the H58L as part of the MyPaint Hardware Library (™, and Amazon wishlist to follow☺). You reckon it might demonstrate this bug?

If anyone can verify or fix (ideally!) this bug with other Huions, please let me know.

**Comment by KyuuGryphon** [comment]
To be honest, the GT-190 is my only real experience with Huion tablets, so I don't know whether different models would produce the same behaviour or not. I'd kind of suspect they'd have similar behaviour - particularly the GT-220, since it shares drivers with the 190 - but I can't really verify it.

Having said that, I'm probably going to do some experiments on my end to see if I can find anything of use - one criticism I remember reading when looking at reviews for the GT-190 before buying it was that the driver software could be quite finicky to install. I haven't seen any odd behaviour in any other programs, so I don't know what the chances of a driver bug are, but it can't hurt to take a look, right? :stuck_out_tongue:

**Comment by achadwick** [comment]
A few updates here:

* [MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is released, with a much newer GTK than 1.2.0 that should fix a ton of tablet bugs. Not sure that glitches like the ones @KyuuGryphon has been seeing would be fixed, but we ship a tablet tester now in the hope of making bug reporting easier and more informative.
* I went and got myself a Huion H610PRO. It works fine with recent builds, although its wintab.dll is *much* slower than my Intuos5's (same MyPaint and computer, switch tablets and drivers, strokes are soooo much smoother on the Wacom...).

**Comment by 09th** [comment]
Hi. About jittering issue - I faced with same behaviour on Genius F-610 and seems that problem is that there is a constant fast switching between "System aggregated pointer" and Stylus. In my case the solution was to disable system pointer for drawing in settings -> devices.

![scr](https://cloud.githubusercontent.com/assets/1531219/23341657/c55a62aa-fc5c-11e6-9016-e55a7d9415a5.jpg)
first line - system pointer disabled, second - enabled

**Comment by AesaraB** [comment]
Consolidated to #1220
