### ISSUE TITLE
Fonts broken (cyrillic) - date column

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#502]
Windows 10 x64, beta 3 x64.
File - Open 

![1](https://cloud.githubusercontent.com/assets/13454470/11323637/fdfc7eda-9138-11e5-8488-1a0e56b8c00b.jpg)

**Comment by tumagonx** [comment]
good catch, this doesn't happen in gtk 3.16.x or older. Coulde you report this upstream?
https://bugzilla.gnome.org/enter_bug.cgi?product=gtk%2B

**Comment by tumagonx** [comment]
This could be pango issue too, if gtk 3.18.x try to use new pango feature that broken on windows though, as it need pango 1.37/1.38 unlike older gtk

**Comment by achadwick** [comment]
Not reproduced in Linux (debian testing/unstable) when running MyPaint as

    LANG=ru_RU LC_ALL=ru_RU.utf8 ./mypaint

I get Cyrillic text, Arabic numerals, presumably what you'd expect. This may not be surprising: it looks very like an upstream encoding issue, and it may be Windows-specific.

@zb13y/@tumagonx: upstream may want locale info. Running our MyPaint builds with the debug console, is a good way of finding out what's happening:

```
INFO: lib.i18n: POSIX: LANG='ru_RU'
INFO: lib.i18n: POSIX: LANGUAGE=None
DEBUG: mypaint: localepath: 'po'
DEBUG: mypaint: localepath_brushlib: 'brushlib/po'
DEBUG: mypaint: getdefaultlocale(): ('ru_RU', 'UTF-8')
DEBUG: mypaint: setlocale(LC_ALL, ''): 'ru_RU.utf8'
DEBUG: mypaint: getpreferredencoding(): 'UTF-8'
DEBUG: mypaint: getlocale(LC_COLLATE): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_CTYPE): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_MESSAGES): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_MONETARY): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_NUMERIC): ('ru_RU', 'UTF-8')
DEBUG: mypaint: getlocale(LC_TIME): ('ru_RU', 'UTF-8')
DEBUG: mypaint: C bindtextdomain('mypaint', 'po'): 'po'
DEBUG: mypaint: C bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('mypaint', 'po'): 'po'
DEBUG: mypaint: Python bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C bindtextdomain('libmypaint', 'brushlib/po'): 'brushlib/po'
DEBUG: mypaint: C bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('libmypaint', 'brushlib/po'): 'brushlib/po'
DEBUG: mypaint: Python bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C textdomain('mypaint'): 'mypaint'
DEBUG: mypaint: Python textdomain('mypaint'): 'mypaint'
DEBUG: gui.main: Adding GTK workarounds...
DEBUG: gui.main: GTK workarounds added.
```

it also lists out the internal modules MyPaint uses for region detection on different platforms.

@tumagonx That build (21 Nov, mypaint 1.2.0-beta.3) should have been picking up pango-1.38.1 if the repo.msys2.org is to believed. Should be gtk3-3.18.3 as well.

**Comment by tumagonx** [comment]
@zb13y I report this upstream as https://bugzilla.gnome.org/show_bug.cgi?id=758504

**Comment by achadwick** [comment]
# Reported upstream

I believe that we cannot do anything about this issue within the MyPaint codebase. Closing.

[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has been released. Please can anyone affected by this bug still try it out and see if this bug is still happening? It contains a newer GLib, and the About box will tell you which one.

(But don't bug us about it. Annoy upstream instead! Link in https://github.com/mypaint/mypaint/issues/502#issuecomment-158793524)

**Comment by zb13y** [comment]
Now i don't have such bug, but dates writen in english. So i don't know is there still such bug or not.

**Comment by achadwick** [comment]
It's better than mojibake, but the dates should be translated. Perhaps we are missing a .mo file in the build.

Please can you investigate in [MSYS2](https://msys2.github.io/) and tell me whether it works there, in a new issue?
