### ISSUE TITLE
Image in statusbar toolbar button for currently selected brush is not scaled to fit

### ISSUE THREAD

**Issue by nekohayo** [mypaint/mypaint#510]
The lower-right corner has a brush picker popup menubutton, with an image of the currently selected brush. The problem is that I can't fully see the thumbnail for that image of the currently selected brush, and in some cases the actual name of the brush is written at the bottom of the thumbnail.

Perhaps it could be scaled to fit the available height?

![capture d ecran de 2015-11-24 15-33-43](https://cloud.githubusercontent.com/assets/479401/11380717/cc77a022-92c5-11e5-925d-cf58e885cbd8.png)

**Comment by achadwick** [comment]
This is intentional, and we even take pains to do a little fade on the bottom to make it look pretty. You'll see the full picture, plus the name and (optional, not widely implemented) description of the brush in the tooltip when you hover.
