### ISSUE TITLE
Zoom tool in toolbar

### ISSUE THREAD

**Issue by nekohayo** [mypaint/mypaint#511]
As the image on #510 reveals, on my Linux build there somehow are no buttons for controlling zoom, on the main toolbar... and yet the Windows version has them. I searched through the menus and preferences and didn't find something that "hides" those toolbar buttons, nor did I see something to that effect in the terminal output when starting. Am I missing something obvious here?

This is the latest git version on Fedora 23 with GNOME.

**Comment by odysseywestra** [comment]
Right click on the tool bar and it will pop a menu.

**Comment by nekohayo** [comment]
...oh! I must have done that years ago and forgot about it.

I was looking for something through menus, as most apps work like that when it comes to showing/hiding toolbar elements. Shouldn't the contents of this popup menu also be available as a "Toolbar" submenu of the toplevel "View" menu?

**Comment by AesaraB** [comment]
I can see the zoom tool on Linux as of v2.0.1. This issue is old, I'm presuming it was added somewhere along the line. Closing as stale.
