### ISSUE TITLE
Alchemy implementation

### ISSUE THREAD

**Issue by budislav** [mypaint/mypaint#523]
Is there any way to implement Alchemy algorithms into MyPaint?
Alchemy can generate cool abstract shapes, can MyPaint have something like that, or even same things?
I made a mockup just to show how it can be implemented in MyPaint UI.

![mypaintandalchemy2](https://cloud.githubusercontent.com/assets/3619927/11604043/25874bf2-9ae8-11e5-905a-785fb03d96ca.png)

**Comment by achadwick** [comment]
I don't know that tool, but for now you can already tell MyPaint to open a layer in an external app.

What does Alchemy do?

**Comment by budislav** [comment]
Here you can see about Alchemy http://al.chemy.org/
and this is a great example what he can do https://www.youtube.com/watch?v=y4OwR1Pj_DU

**Comment by snan** [comment]
Alchemy is a great program and most of my images spend some time in it. Deevad clued me in to it, he used it for some images that he then brought into Mypaint to finish them.

Mypaint has already implemented some of my favorite features of Alchemy (symmetry lines), and the external app layers (it can do both PNG and SVG) seems like it would replace the rest. I don't really see an urgent need for "Pull shapes"  and the like in Mypaint.

**Comment by budislav** [comment]
The most common tool is "standard shapes" with solid shape style. Can we have that?
![untitled-1](https://cloud.githubusercontent.com/assets/3619927/11613067/08f2d57e-9c14-11e5-9c5f-cbdffa2c88d0.png)

**Comment by odysseywestra** [comment]
To be honest this is really out of MyPaint's scope and should be more of a plug-in than be built-in in to MyPaint itself.

**Comment by achadwick** [comment]
Agreed, for now. Let's shelve this. There's a little bit of scope for making arbitrary shapes appear with the brush engine, or even allowing the GUI code to override them. For what it's worth, I think if a plugin ever does something similar, shape overrides have to happen from within mypaint: limbypaint should be kept free of too many geometric dab rendering functions or (woo... slow) SVG rendering.
