### ISSUE TITLE
Brushsetting dialog: value label does not update on Windows

### ISSUE THREAD

**Issue by cortexer** [mypaint/mypaint#524]
The value labels for brush settings are not updated.
Steps to reproduce:
1) Open the brush settings dialog
2) Go to "Basic"->"Radius" (value is 0,40)
3) Go to -> "Hardness" (value is 0,12, but the label still shows 0,40)
4) After clicking on the slider the label updates to the correct value
This seems to happen more or less randomly on all brush setting sliders.

![stuckbrushsettinglabels](https://cloud.githubusercontent.com/assets/13407497/11615067/84fd7542-9c56-11e5-8d33-9b03dddfcef8.jpg)

I tested with Windows build: 1.2.0-beta.3+gitexport.0428646
OS: Windows 10
The problem only seems to appear on Windows.

**Comment by achadwick** [comment]
Reproduced in Linux (debian testing/unstable) under GNOME. Somehow the labels aren't being updated correctly when switching between settings :confused:

**Comment by odysseywestra** [comment]
Reproduced in Linux (Ubuntu Gnome 15.10) Gnome 3.16 as well. So it doesn't look like an upstream problem.

**Comment by achadwick** [comment]
It's a widget redraw issue: it's not redrawing correctly when the GtkAdjustment containing the ranges and values changes. Sometimes resizing the window horizontally is enough to make the text redraw with the correct value.

It may be an upstream thing in GTK, but a workaround is easy enough to manage. I'll do that.
