### ISSUE TITLE
[Support/UI Request?] Toggle toolbar buttons don't indicate their current state

### ISSUE THREAD

**Issue by ShadowKyogre** [mypaint/mypaint#532]
When one toggles the button for erase mode, lock alpha, or lock brightness and opacity, they don't clearly indicate their current state. So what I have to do is to make a test stroke, then undo, then make the stroke with the correct settings.

Anything could help here, ranging from a change in tooltip to a slight change on the button that doesn't break integration with the system colors.

The themes I've tested this with are my handmade own GTK3 theme and wfpaisa-Plane-Gtk3-53ee574.

If it is already providing a way to quickly check the state of these, what's causing these themes to not indicate it properly?

**Comment by achadwick** [comment]
This seems like a simple theming issue, and I don't think it should be addressed in the MyPaint codebase. It is up to the theme designer to make the states distinct.

The default theme is Adwaita, and it looks fine there.
Dark variant:
![adwaita1](https://cloud.githubusercontent.com/assets/61299/11827341/5c1e16b6-a383-11e5-80aa-d21c8da28da4.png)

Light variant:
![adwaita2](https://cloud.githubusercontent.com/assets/61299/11827342/5d8b7b24-a383-11e5-9d9c-98c77f16f610.png)

The only button that changes its appearance is Fullscreen, and I want to keep it that way.
