### ISSUE TITLE
blink in Layer solo

### ISSUE THREAD

**Issue by arrouan** [mypaint/mypaint#544]
I am trying to use mypaint to do scientific presentations.
so far it works great, but I just have 2 questions:

- in 'layer solo' mode, is it possible to stop the blinking mode when switching between layers? (I think in 'layer solo', this blink is useless anyway)
I guess it would require an additional conditional statement in select_layer_below_cb, but I haven't been able to do it properly

-Is it possible to adjust the external margins of the zoom function 'fit to view'?
I see that this is hardcoded in zoom = min((w1-20)/x, (h1-20)/y) (l1772 in document.py). But even if I change 20 to 0, I get a non zero bottom margin. Is it possible to set this argument in the preferences?

thanks for your help

**Comment by achadwick** [comment]
To answer your second question first, it is not possible to set this argument (?) in the preferences.

Please do not pack multiple problems into a single issue report. One issue per problem please.

**Comment by achadwick** [comment]
Reproduced in the latest master: cd1c4e000c207bcd08065ae86754c364d7e97ebd.

I think I agree here, it is a bit strange to blink the layer in solo mode, and I'd be happy to accept a PR for this. The boolean property to test is `[gui.document.Document.]model.layer_stack.current_layer_solo`, and `select_layer_above_cb()` will need to be patched too.

**Comment by arrouan** [comment]
I cannot figure out by which function I should replace 
self.layerblink_state.activate(action)
to update the canvas.

my closest guess is to replace it by
self.normalize_layer_mode_cb(action)
but it only updates the tiles.

I noticed that clicking on any other widow (or desktop) and then clicking back on mypaint does it for me; but I don't know which function is called in the process

Also I guess self.current_layer_changed() in layers.py needs to be changed as well

thank you

**Comment by achadwick** [comment]
@arrouan Perhaps it's best to discuss this in the community forums? <http://community.mypaint.org/>

**Comment by achadwick** [comment]
Addresed on master with b7e59eb0c2a1117030d48e28876dee58275a85ba. Thanks, @arrouan !

I guess the old behaviour was strange enough to warrant this going in 1.2.1 as well.
