### ISSUE TITLE
Msys2_64, Win10 x64 build w/Innosetup package error

### ISSUE THREAD

**Issue by bluecd** [mypaint/mypaint#545]
Runtime error!

Program: C:\Program Files\MyPaint\bin\python2w.exe

This application has requested the Runtime to toerminate it in an unusual way.
Please contact etc etc....

**Comment by tumagonx** [comment]
Can you be more specific what leading to that? :D

**Comment by bluecd** [comment]
Sure. Having Innosetup I get also setup package, after installation, trying to run Mypaint I get above. As simple as it is. ))

**Comment by achadwick** [comment]
@bluecd 
A few initial questions:

1. Were you running `windows/build.sh` from MSYS2 to make this?
2. Is this reproducible with the latest MSYS2 upgrades?
3. Do you get this runtime error immediately?
4. Does this affect MyPaint-w32, MyPaint-w64, or both?

And a quick thing to try: please try running "MyPaint MyPaint w32 (console debug)" or "MyPaint MyPaint w64 (console debug)". This runs MyPaint from a console window which shows Copious Debugging Information. Please paste in the relevant parts of the console output here in backticks like this:

    ```
    Console debug
    output
    goes here
    between the ``` lines.
    
    Warning: it can be very long!
    ```

(The relevant part is normally the bit on the end if you want to cut it down.)

Console debug mode makes MyPaint really slow, but it shows where the crash happens quite reliably.

**Comment by bluecd** [comment]
Ad.1 yes
Ad.2 yes, SHA-1: cd1c4e000c207bcd08065ae86754c364d7e97ebd
Ad.3 yes
Ad.4 MyPaint-64 /I can make x32 build as well-if needed/

How should I invoke /Msys2/ mingw64_shell in console mode?

**Comment by bluecd** [comment]
Same as above with: 
SHA-1: ee1f5bc0004fc0a7360c7a535ada9929dfb4398f
* Bump base version number for 1.2.0-beta.4

Note: Got Python 2.7, 3.4 and 3.5 installed.

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has been released, and it no longer uses InnoSetup. Please can you try it out and see if this bug is still happening?

**Comment by jplloyd** [comment]
No response for >3 years. Assumption: no longer an issue (especially since the windows installer was reworked).
