### ISSUE TITLE
Mypaint.cmd cosmethic issue ??

### ISSUE THREAD

**Issue by bluecd** [mypaint/mypaint#548]
Have to modify by hand 'mingw32' into 'mingw64' in 'mypaint.cmd'
having installed&built from C:\msys64 and its 64bit shell.

**Comment by achadwick** [comment]
No file named mypaint.cmd is installed by mypaint-w64-1.2.0-beta.4-setup.exe from https://github.com/mypaint/mypaint/releases/tag/v1.2.0-beta.4. Which build is this?

**Comment by achadwick** [comment]
Do you mean the mypaint.cmd in the standalone zip build? Looks like that doesn't get tailored like it should.

Is this problem limited to that `mypaint.cmd` only?

**Comment by achadwick** [comment]
Fix tested, and working, at least for the 64-bit build. I assume I'm doing the right thing here based on the filename.

The standalone build is kinda nasty though: it needs to write to itself on the first run (at least). We don't distribute the standalone zipfile right now, its contents should be considered volatile, and I'd really appreciate it if some clever Windows people came up with a better way of bundling stuff :smile:
