### ISSUE TITLE
inktool: ZeroDivisionError when brushstroke ends

### ISSUE THREAD

**Issue by cortexer** [mypaint/mypaint#549]
Drawing with the inktool often leads to a ZeroDivisionError (at the moment when the brushstroke ends).
Does not depend on the input device (also happens when using an ordinary mouse).
Occurs with all brushes.
OS: Windows 10, 64-Bit

MyPaint version and backtrace:
```python
Mypaint version: 1.2.0-beta.4+gitexport.ee1f5bc
System information: Windows-10.0.10586
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint/gui/inktool.py", line 520, _task_queue_runner_cb(self=<gui.inktool.InkingMode object>)
            else:
                callback(*args, **kwargs)
                return True
  variables: {'callback': ('local', <bound method InkingMode._draw_curve_segment of <gui.inktool.InkingMode object at 0x0000000017a47c10>>), 'args': ('local', (<Document nlayers=1 bbox=Rect(256, 192, 960, 704) paintonly=False>, array([  8.77360871e+02,   5.04278213e+02,   4.13489736e-01,
         0.00000000e+00,   0.00000000e+00,   8.15093000e+02]), array([  9.05536161e+02,   4.85723505e+02,   3.08895406e-01,
         0.00000000e+00,   0.00000000e+00,   8.15109000e+02]), array([  9.17349238e+02,   4.77434017e+02,   1.47605083e-01,
         0.00000000e+00,   0.00000000e+00,   8.15109000e+02]), array([  9.17349238e+02,   4.77434017e+02,   1.47605083e-01,
         0.00000000e+00,   0.00000000e+00,   8.15109000e+02]))), 'kwargs': ('local', {'state': {'t_abs': 815.10900000000004}})}
  File "C:\Program Files\MyPaint\share\mypaint/gui/inktool.py", line 475, _draw_curve_segment(self=<gui.inktool.InkingMode object>, model=<Document nlayers=1 bbox=Rect(256, 192, 960, 704) paintonly=False>, p_1=array([  8.77360871e+02,   5.04278213e+02,   4.1...0000000e+00,   0.00000000e+00,   8.15093000e+02]), p0=array([  9.05536161e+02,   4.85723505e+02,   3.0...0000000e+00,   0.00000000e+00,   8.15109000e+02]), p1=array([  9.17349238e+02,   4.77434017e+02,   1.4...0000000e+00,   0.00000000e+00,   8.15109000e+02]), p2=array([  9.17349238e+02,   4.77434017e+02,   1.4...0000000e+00,   0.00000000e+00,   8.15109000e+02]), state={'t_abs': 815.10900000000004})
            for i in xrange(int(steps) + 1):
                t = i / steps
                point = gui.drawutils.spline_4p(t, p_1, p0, p1, p2)
  variables: {'i': ('local', 0), 'steps': ('local', 0.0), 't': (None, [])}
ZeroDivisionError: float division by zero
```

**Comment by achadwick** [comment]
Thanks for the report. Looking into it.

* Often or always? Not managed to reproduce it yet.
* Anything more needed to reproduce than just drawing? Like pressing escape, dragging the canvas...
* Any particular length of line? I've tried short ones and long ones, and ones with just two nodes. Ones with fewer nodes shouldn't even be drawing ☺

Trying with just a mouse for now. The error seems nice and clear, thankfully, so I may just patch up that if it's safe.

**Comment by achadwick** [comment]
@cortexer 
Can you test a quick patch for me? It's a oneliner, so you may be able to apply it manually.

```patch
diff --git a/gui/inktool.py b/gui/inktool.py
index 302aba8..9320616 100644
--- a/gui/inktool.py
+++ b/gui/inktool.py
@@ -470,7 +470,7 @@ class InkingMode (gui.mode.ScrollableModeMixin,
         dist_p1_p2 = math.hypot(p1[0]-p2[0], p1[1]-p2[1])
         steps_d = dist_p1_p2 / self.INTERPOLATION_MAX_SLICE_DISTANCE
         steps_max = float(self.INTERPOLATION_MAX_SLICES)
-        steps = math.ceil(min(steps_max, max(steps_t, steps_d)))
+        steps = math.ceil(min(steps_max, max([2, steps_t, steps_d])))
         for i in xrange(int(steps) + 1):
             t = i / steps
             point = gui.drawutils.spline_4p(t, p_1, p0, p1, p2)
```

**Comment by cortexer** [comment]
Thanks for the patch.
* At least for one out of 20 strokes the zero division occurs.
* On linux builds I was never able to see this problem.
* No further actions than opening a clean MyPaint installation and start drawing using inktool.
* The length of the line makes no difference.
* Meanwhile I found out it only happens on fast brushstrokes. So it depends on how fast the mouse pointer is moving.
* With the patch above I cannot reproduce the problem any more. :smiley:

**Comment by achadwick** [comment]
Okay, it looks like at least some Windows drivers or OS versions send successive events with the same times *and* positions. I'll push a couple of hopeful fixes.

FWIW, I was testing with a real additional mouse on Win7 64-bit (in a VM, but using USB pass-thru).

**Comment by achadwick** [comment]
One remaining question, if you recall: did you see the error only at the start of the captured stroke, only at the end, or in the middle of stroke capture while the pen/button was down?

**Comment by cortexer** [comment]
The error only happened at the moment the pen/button was released. So the release of the button somehow triggered it.
