### ISSUE TITLE
Canvas and viewfinder rectangle are rotating in the inverse direction

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#557]
When we rotate the canvas in clockwise direction, the rectangle on viewfinder is rotating in counterclockwise direction and vice-versa.
I made an small video to illustrate this behavior:
https://youtu.be/PRpvVlJ1naQ

**Comment by achadwick** [comment]
This is the correct behaviour. These actions were changed to be more consistent with the rest of the toolbar buttons in #553.

Consider: the `+` button on the toolbar does not make the rectangle on the Preview dockpanel ("viewfinder") bigger. It makes it smaller.

Toolbar view buttons now affect the canvas within the view.
