### ISSUE TITLE
HSV Triangle seems to be missing (?)

### ISSUE THREAD

**Issue by mufar94** [mypaint/mypaint#560]
Is it removed starting from 1.2.0-beta.4+gitexport.ee1f5bc? Personally, I prefer using it because it's much easier to use.
![image](https://cloud.githubusercontent.com/assets/16100990/12229426/7237eb8e-b882-11e5-92ab-18fe4c50769a.png)

**Comment by achadwick** [comment]
This is correct and intended. See #268.
