### ISSUE TITLE
Error message after resume from suspend when device is unplugged: XI_BadDevice

### ISSUE THREAD

**Issue by lilydjwg** [mypaint/mypaint#562]
```
The program 'mypaint' received an X Window System error.
This probably reflects a bug in the program.
The error was 'XI_BadDevice (invalid Device parameter)'.
```

steps:

1. drawing with my wacom
2. put the system into suspend mode
3. plug out the device
4. resume the system
5. try to use the running mypaint process again.

**Comment by achadwick** [comment]
Please tell me what version of MyPaint this is, and what operating system you are using (and its version too). See <https://github.com/mypaint/mypaint/wiki/Reporting-Bugs> for what we need to begin addressing this, and please try to give me as much information as you possibly can.

* Does this happen every time you suspend and then unplug your device while suspended?
* What did you expect to happen when you did this?
* What happens to MyPaint when this happens?
* Is GIMP or Inkscape affected by this?

To be honest, errors might almost be expected from doing this sort of thing. I'll have a play at my end and see what kind of a mess I can make ☺

**Comment by achadwick** [comment]
I can't reproduce this in GNOME on Debian testing/unstable with master as of 9c640bb4057a6d93721762a975290a166c50a577 and:

* gnome-shell 3.18
* gtk+ 3.18.6
* xserver-xorg 7.7+12
* kernel 4.2.0-1-amd64

After resume, I'm able to carry on painting just as before (by using the trackpad), and I can plug my tablet back in again and (after a brief pause) continue using it as normal. Queued strokes continue to render, even.

Hardware: Dell XPS 13, Intuos 5 over USB.

@lilydjwg Is this still happening? Can you make it happen more than once?

**Comment by lilydjwg** [comment]
I can reproduce it without suspending actually. But I find that after unplugging, mypaint crashes only when I use the mouse middle button to pan the canvas, not when I paint with the left button.

versions:

* Arch Linux x86_64 2016-01-11
* mypaint 1.1.0-5
* awesome 3.5.6-2
* gtk3 3.18.6-2
* xorg-server 1.18.0-3
* linux-lily 4.2.1-1
* xf86-input-wacom 0.32.0-1

Lenovo ThinkPad X250, Wacom Bamboo One S, over USB hub (where my wireless Logitech mouse is connected too).

I've never seen this kind of crashes while unplugging mice or keyboards though. GIMP and Inkscape don't crash either.

**Comment by achadwick** [comment]
Ah, 1.1.0 (which doesn't use GTK3, but I'll assume you have a nice recent GTK2 based on the rest of your system).

Can you test the latest beta for 1.2.0 please, and let me know if this is still happening? <https://github.com/mypaint/mypaint/releases>, or through your distro's normal repositories (AUR?)

You can build it from source instead. MyPaint doesn't need to be installed if you're building it yourself just to test a single thing: <https://github.com/mypaint/mypaint/blob/master/README_LINUX.md>.

**Comment by lilydjwg** [comment]
I've tried the latest version and it doesn't crash any more. Thanks for your time.

PS: it's surprising to see a dark theme for me, as my GTK theme is light.
