### ISSUE TITLE
Release official Windows build of v1.2.0

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#564]
Following on from <https://github.com/mypaint/mypaint/issues/390#issuecomment-168339960>.

After the source release and and PPA binaries are made, MyPaint will need an official Windows build. As mentioned in the issue above, @tumagonx has very kindly offered to take care of this for the 1.2.0 release: his build is by all accounts lag-free, and that's the killer for 1.2.0 on the windows platform.

@tumagonx I'm assigning this issue to you for now. Hope that's OK. When you've made the binary from the official source file on <https://github.com/mypaint/mypaint/releases/tag/v1.2.0>, please upload it there and I'll see to announcing it on Twitter. I think you will have the rights to upload a file there when the release is tagged and published in Github :smile: 

Many thanks for doing this.

**Comment by achadwick** [comment]
Source code for 1.2.0 has been tagged and released. There's a signed tarball of everything (libmypaint and mypaint together) at <https://github.com/mypaint/mypaint/releases/tag/v1.2.0>. Over to you, and thanks once again for offering to help, @tumagonx!

**Comment by tumagonx** [comment]
@achadwick I have made the installers. I can self digisign the
installer but it's not a root-trusted certificate (so kind of
pointless). Do we need such?

On 1/16/16, Andrew Chadwick <notifications@github.com> wrote:
> Source code for 1.2.0 has been tagged and released. There's a signed tarball
> of everything (libmypaint and mypaint together) at
> <https://github.com/mypaint/mypaint/releases/tag/v1.2.0>. Over to you, and
> thanks once again for offering to help, @tumagonx!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/564#issuecomment-172097884


-- 
!tuma

**Comment by tumagonx** [comment]
Is it possible to rsync the file to github? it rather large for me
(37mb each) to upload via http.

On 1/16/16, Bakhtiar Hasmanan <mr.tiar@gmail.com> wrote:
> @achadwick I have made the installers. I can self digisign the
> installer but it's not a root-trusted certificate (so kind of
> pointless). Do we need such?
>
> On 1/16/16, Andrew Chadwick <notifications@github.com> wrote:
>> Source code for 1.2.0 has been tagged and released. There's a signed
>> tarball
>> of everything (libmypaint and mypaint together) at
>> <https://github.com/mypaint/mypaint/releases/tag/v1.2.0>. Over to you,
>> and
>> thanks once again for offering to help, @tumagonx!
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mypaint/mypaint/issues/564#issuecomment-172097884
>
>
> --
> !tuma
>


-- 
!tuma

**Comment by odysseywestra** [comment]
@tumagonx I heard there is a performance hit If they are self signed. Is that correct?

As far as I know the only way to upload binaries to github is http sadly.

**Comment by tumagonx** [comment]
If all executables (exe and dll) self signed, yes some AV will gone
crazy when mypaint started but this is only the installer. It just
that nowadays installer usually signed, but it's okay if not signed
though.

If that's the case I will upload at night when my connection more stable.

On 1/16/16, Albert Westra <notifications@github.com> wrote:
> @tumagonx I heard there is a performance hit If they are self signed. Is
> that correct?
>
> As far as I know the only way to upload binaries to github is http sadly.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/564#issuecomment-172164250


-- 
!tuma

**Comment by tumagonx** [comment]
Because of  continuous error while uploading via http, I had to rsync
the installers to my sourceforge account temporarily. I will grateful
if one of committer willing to help to upload into github. Once
uploaded I will remove it from
http://sourceforge.net/projects/tumagcc/files/.

SHA-1
mypaint-w32-1.2.0-setup.exe D1B0665D9D5F656885D8078007C0C464CD71E33B
mypaint-w64-1.2.0-setup.exe 840D9DECFDA48E08568C0A1016409ED4B1033244

Thank you and sorry for the inconvenience


On 1/16/16, Bakhtiar Hasmanan <mr.tiar@gmail.com> wrote:
> If all executables (exe and dll) self signed, yes some AV will gone
> crazy when mypaint started but this is only the installer. It just
> that nowadays installer usually signed, but it's okay if not signed
> though.
>
> If that's the case I will upload at night when my connection more stable.
>
> On 1/16/16, Albert Westra <notifications@github.com> wrote:
>> @tumagonx I heard there is a performance hit If they are self signed. Is
>> that correct?
>>
>> As far as I know the only way to upload binaries to github is http sadly.
>>
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mypaint/mypaint/issues/564#issuecomment-172164250
>
>
> --
> !tuma
>


-- 
!tuma

**Comment by achadwick** [comment]
@tumagonx Downloaded and verified that the sha1sums match:

    $ sha1sum mypaint*-setup.exe 
    d1b0665d9d5f656885d8078007c0c464cd71e33b  mypaint-w32-1.2.0-setup.exe
    840d9decfda48e08568c0a1016409ed4b1033244  mypaint-w64-1.2.0-setup.exe

I'm assuming that means that sf haven't tampered with the files as they did with GIMP :smiling_imp: 

However I can't get either of these to run on Windows 7 Professional N 64 bit after installation, either from the desktop icon or the start menu item, or from `cmd`:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Test User>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wind
owsPowerShell\v1.0\

C:\Users\Test User>"c:\Program Files\MyPaint\mypaint.exe"

C:\Users\Test User>PATH="c:\Program Files\MyPaint;%PATH%"

C:\Users\Test User>echo %PATH%
"c:\Program Files\MyPaint;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbe
m;C:\Windows\System32\WindowsPowerShell\v1.0\"

C:\Users\Test User>mypaint
'mypaint' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Test User>"c:\Program Files\MyPaint\mypaint.exe"

C:\Users\Test User>cd "c:\Program Files\MyPaint"

c:\Program Files\MyPaint>mypaint

c:\Program Files\MyPaint>
```

Basically nothing happens from the Windows `cmd` shell. No processes are launched that are visible in task manager, and nothing's printed on the console. Trying from an MSYS2 shell, because I can ☺ and that's generally a bit more informative.

```
Test User@win7test MINGW64 ~
$ cd /c/Program\ Files/MyPaint/

Test User@win7test MINGW64 /c/Program Files/MyPaint
$ file *.exe
mypaint.exe:  PE32+ executable (GUI) x86-64 (stripped to external PDB), for MS Windows
unins000.exe: PE32 executable (GUI) Intel 80386, for MS Windows

Test User@win7test MINGW64 /c/Program Files/MyPaint
$ ./mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'C:\\Program Files\\MyPaint'
INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\mypaint.py", line 465, in <module>
  File "C:\Program Files\MyPaint\share\mypaint\gui\main.py", line 95, in main
    from gui import application
  File "C:\Program Files\MyPaint\share\mypaint\gui\application.py", line 48, in <module>
    import lib.document
  File "C:\Program Files\MyPaint\share\mypaint\lib\document.py", line 37, in <module>
    import lib.helpers as helpers
  File "C:\Program Files\MyPaint\share\mypaint\lib\helpers.py", line 26, in <module>
    import mypaintlib
  File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 26, in <module>
    _mypaintlib = swig_import_helper()
  File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 18, in swig_import_helper
    import _mypaintlib
ImportError: DLL load failed: The specified procedure could not be found.

Test User@win7test MINGW64 /c/Program Files/MyPaint
$ PATH="`pwd`:$PATH"

Test User@win7test MINGW64 /c/Program Files/MyPaint
$ echo $PATH
/c/Program Files/MyPaint:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

Test User@win7test MINGW64 /c/Program Files/MyPaint
$ ./mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'C:\\Program Files\\MyPaint'
INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\mypaint.py", line 465, in <module>
  File "C:\Program Files\MyPaint\share\mypaint\gui\main.py", line 95, in main
    from gui import application
  File "C:\Program Files\MyPaint\share\mypaint\gui\application.py", line 48, in <module>
    import lib.document
  File "C:\Program Files\MyPaint\share\mypaint\lib\document.py", line 37, in <module>
    import lib.helpers as helpers
  File "C:\Program Files\MyPaint\share\mypaint\lib\helpers.py", line 26, in <module>
    import mypaintlib
  File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 26, in <module>
    _mypaintlib = swig_import_helper()
  File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 18, in swig_import_helper
    import _mypaintlib
ImportError: DLL load failed: The specified procedure could not be found.

Test User@win7test MINGW64 /c/Program Files/MyPaint
$ ls -l _mypaintlib.pyd
-rwxr-xr-x 1 Test User None 1126912 Jan 16 10:31 _mypaintlib.pyd

```

Let me know if there's anything more you need to help debug this, or if I'm doing something obviously silly.

I notice that the installs include msvcr90.dll too, so as I understand it we can't distribute these files for copyright reasons. It might not be necessary if this was built with mingw-w64.

**Comment by tumagonx** [comment]
Thanks a lot, I think I understand now. During testing I forgot to
downgrade glib to pre 2.45 (association issue) and then I replaced
just the dll but didn't to remove leftovers *.pyc in installdir and it
make everything seems ok after reinstallation. Once I remove the
leftover _gi.pyd failed to load.

I have rebuild pygobject against the correct glib version. Hopefully
it works now (finger crossed).
I'm still uploading, will take some hours.

PS: My binary doesn't contain precompiled *pyc that's why uninstaller
doesn't remove the leftovers cache. And since replacing dll doesn't
imply newer cache, the old cache used.

PS: Can't talk about msvcr90.dll, but either bundling via mergemodule
if using msi or bundling the complete redist installer I can't see how
it different from bundling just the dll. I think py2exe have nice
article about it.


On 1/17/16, Andrew Chadwick <notifications@github.com> wrote:
> @tumagonx Downloaded and verified that the sha1sums match:
>
>     $ sha1sum mypaint*-setup.exe
>     d1b0665d9d5f656885d8078007c0c464cd71e33b  mypaint-w32-1.2.0-setup.exe
>     840d9decfda48e08568c0a1016409ed4b1033244  mypaint-w64-1.2.0-setup.exe
>
> I'm assuming that means that sf haven't tampered with the files as they did
> with GIMP :smiling_imp:
>
> However I can't get either of these to run on Windows 7 Professional N 64
> bit after installation, either from the desktop icon or the start menu item,
> or from `cmd`:
>
> ```
> Microsoft Windows [Version 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
>
> C:\Users\Test User>echo %PATH%
> C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wind
> owsPowerShell\v1.0\
>
> C:\Users\Test User>"c:\Program Files\MyPaint\mypaint.exe"
>
> C:\Users\Test User>PATH="c:\Program Files\MyPaint;%PATH%"
>
> C:\Users\Test User>echo %PATH%
> "c:\Program
> Files\MyPaint;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbe
> m;C:\Windows\System32\WindowsPowerShell\v1.0\"
>
> C:\Users\Test User>mypaint
> 'mypaint' is not recognized as an internal or external command,
> operable program or batch file.
>
> C:\Users\Test User>"c:\Program Files\MyPaint\mypaint.exe"
>
> C:\Users\Test User>cd "c:\Program Files\MyPaint"
>
> c:\Program Files\MyPaint>mypaint
>
> c:\Program Files\MyPaint>
> ```
>
> Basically nothing happens from the Windows `cmd` shell. No processes are
> launched that are visible in task manager, and nothing's printed on the
> console. Trying from an MSYS2 shell, because I can ☺ and that's generally a
> bit more informative.
>
> ```
> Test User@win7test MINGW64 ~
> $ cd /c/Program\ Files/MyPaint/
>
> Test User@win7test MINGW64 /c/Program Files/MyPaint
> $ file *.exe
> mypaint.exe:  PE32+ executable (GUI) x86-64 (stripped to external PDB), for
> MS Windows
> unins000.exe: PE32 executable (GUI) Intel 80386, for MS Windows
>
> Test User@win7test MINGW64 /c/Program Files/MyPaint
> $ ./mypaint
> INFO: mypaint: Installation layout: conventional POSIX-like structure with
> prefix u'C:\\Program Files\\MyPaint'
> INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
> INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
> WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
> INFO: mypaint: Trying platform-specific fallback hacks to find
> bindtextdomain funcs.
> INFO: mypaint: Windows: found working bindtextdomain funcs in
> 'libintl-8.dll' (ctypes)
> Traceback (most recent call last):
>   File "C:\Program Files\MyPaint\mypaint.py", line 465, in <module>
>   File "C:\Program Files\MyPaint\share\mypaint\gui\main.py", line 95, in
> main
>     from gui import application
>   File "C:\Program Files\MyPaint\share\mypaint\gui\application.py", line 48,
> in <module>
>     import lib.document
>   File "C:\Program Files\MyPaint\share\mypaint\lib\document.py", line 37, in
> <module>
>     import lib.helpers as helpers
>   File "C:\Program Files\MyPaint\share\mypaint\lib\helpers.py", line 26, in
> <module>
>     import mypaintlib
>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 26,
> in <module>
>     _mypaintlib = swig_import_helper()
>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 18,
> in swig_import_helper
>     import _mypaintlib
> ImportError: DLL load failed: The specified procedure could not be found.
>
> Test User@win7test MINGW64 /c/Program Files/MyPaint
> $ PATH="`pwd`:$PATH"
>
> Test User@win7test MINGW64 /c/Program Files/MyPaint
> $ echo $PATH
> /c/Program
> Files/MyPaint:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
>
> Test User@win7test MINGW64 /c/Program Files/MyPaint
> $ ./mypaint
> INFO: mypaint: Installation layout: conventional POSIX-like structure with
> prefix u'C:\\Program Files\\MyPaint'
> INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
> INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
> WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
> INFO: mypaint: Trying platform-specific fallback hacks to find
> bindtextdomain funcs.
> INFO: mypaint: Windows: found working bindtextdomain funcs in
> 'libintl-8.dll' (ctypes)
> Traceback (most recent call last):
>   File "C:\Program Files\MyPaint\mypaint.py", line 465, in <module>
>   File "C:\Program Files\MyPaint\share\mypaint\gui\main.py", line 95, in
> main
>     from gui import application
>   File "C:\Program Files\MyPaint\share\mypaint\gui\application.py", line 48,
> in <module>
>     import lib.document
>   File "C:\Program Files\MyPaint\share\mypaint\lib\document.py", line 37, in
> <module>
>     import lib.helpers as helpers
>   File "C:\Program Files\MyPaint\share\mypaint\lib\helpers.py", line 26, in
> <module>
>     import mypaintlib
>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 26,
> in <module>
>     _mypaintlib = swig_import_helper()
>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line 18,
> in swig_import_helper
>     import _mypaintlib
> ImportError: DLL load failed: The specified procedure could not be found.
>
> Test User@win7test MINGW64 /c/Program Files/MyPaint
> $ ls -l _mypaintlib.pyd
> -rwxr-xr-x 1 Test User None 1126912 Jan 16 10:31 _mypaintlib.pyd
>
> ```
>
> Let me know if there's anything more you need to help debug this, or if I'm
> doing something obviously silly.
>
> I notice that the installs include msvcr90.dll too, so as I understand it we
> can't distribute these files for copyright reasons. It might not be
> necessary if this was built with mingw-w64.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/564#issuecomment-172261618


-- 
!tuma

**Comment by tumagonx** [comment]
I think I understand your concern about the msvcr90.
In a nutshell MS provide the redist for Visual Studio user to help
binary distribution. The problem is before VS 2005 it was available as
commercial only (redist as with NET framework), thus msvcr70.dll and
msvcr71.dll only eligible to those licensed users of Pro edition. This
change with VS 2005 till 2015 which have free Express edition.

Of course in strictly manner you (as with other linux users) may not
redistribute it but I as licensed user of VS 2008 Express can. The
same analogy apply to ATL and MFC which before VS 2015 Express can
only redistributed by licensed users of Pro edition.

I already take precaution regarding numpy 64bit which I took from
Gohlke, I use the one without optimization (non-MKL because I'm not
own any of Intel Compiler). This is what I did with mypaint 1.0 too.

Yet I'm not a lawyer :D

updated installers
mypaint-w64-1.2.0-setup.exe 373CD57F4D11792C59F459861FC3A255C096D5AD
mypaint-w32-1.2.0-setup.exe B74D49B0EC5B4FB595BC1D0E0ED2A6FE1E740559


On 1/17/16, Bakhtiar Hasmanan <mr.tiar@gmail.com> wrote:
> Thanks a lot, I think I understand now. During testing I forgot to
> downgrade glib to pre 2.45 (association issue) and then I replaced
> just the dll but didn't to remove leftovers *.pyc in installdir and it
> make everything seems ok after reinstallation. Once I remove the
> leftover _gi.pyd failed to load.
>
> I have rebuild pygobject against the correct glib version. Hopefully
> it works now (finger crossed).
> I'm still uploading, will take some hours.
>
> PS: My binary doesn't contain precompiled *pyc that's why uninstaller
> doesn't remove the leftovers cache. And since replacing dll doesn't
> imply newer cache, the old cache used.
>
> PS: Can't talk about msvcr90.dll, but either bundling via mergemodule
> if using msi or bundling the complete redist installer I can't see how
> it different from bundling just the dll. I think py2exe have nice
> article about it.
>
>
> On 1/17/16, Andrew Chadwick <notifications@github.com> wrote:
>> @tumagonx Downloaded and verified that the sha1sums match:
>>
>>     $ sha1sum mypaint*-setup.exe
>>     d1b0665d9d5f656885d8078007c0c464cd71e33b  mypaint-w32-1.2.0-setup.exe
>>     840d9decfda48e08568c0a1016409ed4b1033244  mypaint-w64-1.2.0-setup.exe
>>
>> I'm assuming that means that sf haven't tampered with the files as they
>> did
>> with GIMP :smiling_imp:
>>
>> However I can't get either of these to run on Windows 7 Professional N 64
>> bit after installation, either from the desktop icon or the start menu
>> item,
>> or from `cmd`:
>>
>> ```
>> Microsoft Windows [Version 6.1.7601]
>> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
>>
>> C:\Users\Test User>echo %PATH%
>> C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wind
>> owsPowerShell\v1.0\
>>
>> C:\Users\Test User>"c:\Program Files\MyPaint\mypaint.exe"
>>
>> C:\Users\Test User>PATH="c:\Program Files\MyPaint;%PATH%"
>>
>> C:\Users\Test User>echo %PATH%
>> "c:\Program
>> Files\MyPaint;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbe
>> m;C:\Windows\System32\WindowsPowerShell\v1.0\"
>>
>> C:\Users\Test User>mypaint
>> 'mypaint' is not recognized as an internal or external command,
>> operable program or batch file.
>>
>> C:\Users\Test User>"c:\Program Files\MyPaint\mypaint.exe"
>>
>> C:\Users\Test User>cd "c:\Program Files\MyPaint"
>>
>> c:\Program Files\MyPaint>mypaint
>>
>> c:\Program Files\MyPaint>
>> ```
>>
>> Basically nothing happens from the Windows `cmd` shell. No processes are
>> launched that are visible in task manager, and nothing's printed on the
>> console. Trying from an MSYS2 shell, because I can ☺ and that's generally
>> a
>> bit more informative.
>>
>> ```
>> Test User@win7test MINGW64 ~
>> $ cd /c/Program\ Files/MyPaint/
>>
>> Test User@win7test MINGW64 /c/Program Files/MyPaint
>> $ file *.exe
>> mypaint.exe:  PE32+ executable (GUI) x86-64 (stripped to external PDB),
>> for
>> MS Windows
>> unins000.exe: PE32 executable (GUI) Intel 80386, for MS Windows
>>
>> Test User@win7test MINGW64 /c/Program Files/MyPaint
>> $ ./mypaint
>> INFO: mypaint: Installation layout: conventional POSIX-like structure
>> with
>> prefix u'C:\\Program Files\\MyPaint'
>> INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
>> INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
>> WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
>> INFO: mypaint: Trying platform-specific fallback hacks to find
>> bindtextdomain funcs.
>> INFO: mypaint: Windows: found working bindtextdomain funcs in
>> 'libintl-8.dll' (ctypes)
>> Traceback (most recent call last):
>>   File "C:\Program Files\MyPaint\mypaint.py", line 465, in <module>
>>   File "C:\Program Files\MyPaint\share\mypaint\gui\main.py", line 95, in
>> main
>>     from gui import application
>>   File "C:\Program Files\MyPaint\share\mypaint\gui\application.py", line
>> 48,
>> in <module>
>>     import lib.document
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\document.py", line 37,
>> in
>> <module>
>>     import lib.helpers as helpers
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\helpers.py", line 26,
>> in
>> <module>
>>     import mypaintlib
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line
>> 26,
>> in <module>
>>     _mypaintlib = swig_import_helper()
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line
>> 18,
>> in swig_import_helper
>>     import _mypaintlib
>> ImportError: DLL load failed: The specified procedure could not be found.
>>
>> Test User@win7test MINGW64 /c/Program Files/MyPaint
>> $ PATH="`pwd`:$PATH"
>>
>> Test User@win7test MINGW64 /c/Program Files/MyPaint
>> $ echo $PATH
>> /c/Program
>> Files/MyPaint:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
>>
>> Test User@win7test MINGW64 /c/Program Files/MyPaint
>> $ ./mypaint
>> INFO: mypaint: Installation layout: conventional POSIX-like structure
>> with
>> prefix u'C:\\Program Files\\MyPaint'
>> INFO: lib.i18n: Windows: LANG='en_US.UTF-8'
>> INFO: lib.i18n: Windows: LANGUAGE='en_GB:en_US'
>> WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
>> INFO: mypaint: Trying platform-specific fallback hacks to find
>> bindtextdomain funcs.
>> INFO: mypaint: Windows: found working bindtextdomain funcs in
>> 'libintl-8.dll' (ctypes)
>> Traceback (most recent call last):
>>   File "C:\Program Files\MyPaint\mypaint.py", line 465, in <module>
>>   File "C:\Program Files\MyPaint\share\mypaint\gui\main.py", line 95, in
>> main
>>     from gui import application
>>   File "C:\Program Files\MyPaint\share\mypaint\gui\application.py", line
>> 48,
>> in <module>
>>     import lib.document
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\document.py", line 37,
>> in
>> <module>
>>     import lib.helpers as helpers
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\helpers.py", line 26,
>> in
>> <module>
>>     import mypaintlib
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line
>> 26,
>> in <module>
>>     _mypaintlib = swig_import_helper()
>>   File "C:\Program Files\MyPaint\share\mypaint\lib\mypaintlib.py", line
>> 18,
>> in swig_import_helper
>>     import _mypaintlib
>> ImportError: DLL load failed: The specified procedure could not be found.
>>
>> Test User@win7test MINGW64 /c/Program Files/MyPaint
>> $ ls -l _mypaintlib.pyd
>> -rwxr-xr-x 1 Test User None 1126912 Jan 16 10:31 _mypaintlib.pyd
>>
>> ```
>>
>> Let me know if there's anything more you need to help debug this, or if
>> I'm
>> doing something obviously silly.
>>
>> I notice that the installs include msvcr90.dll too, so as I understand it
>> we
>> can't distribute these files for copyright reasons. It might not be
>> necessary if this was built with mingw-w64.
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mypaint/mypaint/issues/564#issuecomment-172261618
>
>
> --
> !tuma
>


-- 
!tuma

**Comment by tumagonx** [comment]
@achadwick just wondering whether the new installers are ok or still no good?

**Comment by achadwick** [comment]
Sorry for the delay. Been looking after an older family member for most of the day. Testing now.

Not a lawyer here too :sweat_smile:
From my reading though, I think it's OK if it's listed in your licensed VS's REDIST.txt. If <http://adam.goucher.ca/wordpress/wp-content/uploads/2009/10/redist.txt> is that file, I think you're good to redistribute the files.

Bundling the Visual C++ Redistributable Package `.exe` installer is doubtless fine, and I found that there are Inno Setup recipes for running it after installation in a sensible way.
https://stackoverflow.com/questions/2461848/

Otherwise, the files can be included in the installation tree provided the directory structure doesn't change. Strange situation, but there you go. And I guess that means the existing setup's fine too.

Testing installers now.

**Comment by achadwick** [comment]
@tumagonx 
Looking good in my Windows VM (VirtualBox Win7 64bit, optional DirectX support not installed, so I don't get Win7 Aero effects). I have pressure support with a Wacom Intuos 5 tablet, using the 6.3.13w3 Wacom drivers.

There may also be a need to remove any earlier MyPaint stable installs or betas before installing these, so I'll update the release page with that information. You should be able to edit the release page text as well.

I've uploaded the binaries to the release page, and verified downloads from it match your hashes:

```
$ sha1sum mypaint-*exe
b74d49b0ec5b4fb595bc1d0e0ed2a6fe1e740559  mypaint-w32-1.2.0-setup.exe
373cd57f4d11792c59f459861fc3a255c096d5ad  mypaint-w64-1.2.0-setup.exe
```

Thanks!

**Comment by achadwick** [comment]
@tumagonx You have R/W access to <https://github.com/mypaint/mypaint.github.io> through git or on the github site. Do you want to make an announcement there?

**Comment by tumagonx** [comment]
Thanks, I have removed the files from my SF now

On 1/18/16, Andrew Chadwick <notifications@github.com> wrote:
> @tumagonx
> Looking good in my Windows VM (VirtualBox Win7 64bit, optional DirectX
> support not installed, so I don't get Win7 Aero effects). I have pressure
> support with a Wacom Intuos 5 tablet, using the 6.3.13w3 Wacom drivers.
>
> There may also be a need to remove any earlier MyPaint stable installs or
> betas before installing these, so I'll update the release page with that
> information. You should be able to edit the release page text as well.
>
> I've uploaded the binaries to the release page, and verified downloads from
> it match your hashes:
>
> ```
> $ sha1sum mypaint-*exe
> b74d49b0ec5b4fb595bc1d0e0ed2a6fe1e740559  mypaint-w32-1.2.0-setup.exe
> 373cd57f4d11792c59f459861fc3a255c096d5ad  mypaint-w64-1.2.0-setup.exe
> ```
>
> Thanks!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/564#issuecomment-172394526


-- 
!tuma

**Comment by tumagonx** [comment]
@achadwick Nah my english is not that good, you're definitely better

**Comment by achadwick** [comment]
@tumagonx Not a problem. Huge thanks for all the work and fixes so far!

I've updated the release page <https://github.com/mypaint/mypaint/releases/tag/v1.2.0>.
Let me know if I need to say anything more.
