### ISSUE TITLE
Laggy canvas panning with symmetry

### ISSUE THREAD

**Issue by not-surt** [mypaint/mypaint#565]
Version: PPA 1.2.0+gitexport.f62444e
OS: Xubuntu 15.04 AMD64
Driver: fglrx-updates

Horrible lag occurs when panning the canvas while using a painting tool and symmetry is on.
Only occurs when a painting tool is selected.
When symmetry tool is selected lag is not noticeable.
No lag is noticeable while painting.

**Comment by achadwick** [comment]
Nice and clear so far. Thanks.

* To confirm, this is the canvas not keeping up you when you move it?
* Is this mouse/tablet panning with button 2, or panning using the cursor keys?
* Can you let me know which brush you were using when symmetry was on and you were having the lag?
* Does this kick in at any particular zoom level, or is it worse at any particular zoom levels?
* Any unusually large or slow monitors, dual heads...?
* Is the panning lag the same when the window is smaller, or is it reduced?

If you have the opportunity, please try running the profiler for a case where this doesn't show and compare it to one where it does show. You can upload the PNG results here on Github ☺
Instructions: https://github.com/mypaint/mypaint/blob/v1.2.0/DEBUGGING.md#profiling

**Comment by achadwick** [comment]
Can't reproduce anything noticeable in GNOME on Debian amd64 testing/unstable (GTK 3.18.6) with an Intel Haswell-ULT graphics adapter.

**Comment by achadwick** [comment]
Oh. And I should ask since you're tracking the PPA - do you know if this has only started happening with v1.2.0, or have earlier betas had the same problem?

**Comment by achadwick** [comment]
Can't reproduce with mypaint 1.2.0-0dev1ppa1~vivid1 from [the PPA](https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing/) on Ubuntu 15.04 in a virtual machine with an Intuos 5 (USB pass-thru). Or at least, the lag seems acceptable to me :neutral_face: 

Also can't reproduce with v1.2.0 on the host OS, same tablet.

**Comment by not-surt** [comment]
Yes, canvas movement lagging far behind mouse movement, panning with mouse/tablet MMB.
Tried various brushes, lag occurring with all.
Doesn't seem to be affected by zoom level.
Just using a single 1080p TV as monitor.
Doesn't seem to occur in a window of about half screen area, but does in a window of about three-quarters screen area and larger.
Haven't used MyPaint for a while so I couldn't say if the problem has been present in other recent builds.

I couldn't figure out how to get grof2dot to work, so raw prof files are attached in zip.
[pstats.zip](https://github.com/mypaint/mypaint/files/92767/pstats.zip)

I've noticed that the lag comes and goes.
I might be mid drag with it lagging then it snaps to the mouse cursor and is fine for the rest of the drag.
Also occurs with dedicated pan tool selected.

**Comment by achadwick** [comment]
@not-surt 
Sorry I didn't get to this earlier.

[MyPaint v1.21](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now available. Can you please test to see whether this bug is still present in it, when it's convenient? Thanks.

"The lag comes and goes" makes this sound as though it's going to be highly unreproducable.

**Comment by not-surt** [comment]
Sorry, I'd forgotten about this.
I can't seem to reproduce it now, working fine for me.
I have changed video cards and drivers since (now nvidia), but since no one else is having the issue should be fine to close.
