### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by Klesus** [mypaint/mypaint#568]
I am using 1.2.0+git.f62444e.dirty on Win 7 Ultimate. The language in mypaint is set to swedish, but I want it in english. The closed issue #435 mentions changing language on the Formats tab, but there is no formats tab in the mypaint settings. And if it were it would be translated anyway, which is a problem and the reason why I want mypaint in english in the first place.

How can I change the language displayed. My windows installation is in english if that has (should have) any significance.

**Comment by tumagonx** [comment]
It seems you looking for independent per-app language setting? mypaint
use global setting from your language panel of control panel at Format
tab.

On 1/19/16, Klesus <notifications@github.com> wrote:
> I am using 120+gitf62444edirty on Win 7 Ultimate The language in mypaint is
> set to swedish, but I want it in english The closed issue #435 mentions
> changing language on the Formats tab, but there is no formats tab in the
> mypaint settings And if it were it would be translated anyway, which is a
> problem and the reason why I want mypaint in english in the first place
>
> How can I change the language displayed My windows installation is in
> english if that has (should have) any significance
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/568


-- 
!tuma

**Comment by Klesus** [comment]
Yes I would like to be able to choose language on a per app basis.

As for the control panel, there is no format tab in there as far as I can see. Searching for the string "format" yields nothing relating to language. But in any case, I'm curious, since my windows installation is in english, shouldn't mypaint be in english as well? I'm not sure what settings we are talking about here, since I cannot find this format tab.

**Comment by tumagonx** [comment]
Regional Settings maybe? sorry I dont remember as well since I'm on 8.1/XP

On 1/19/16, Klesus <notifications@github.com> wrote:
> Yes I would like to be able to choose language on a per app basis.
>
> As for the control panel, there is no format tab in there as far as I can
> see. Searching for the string "format" yields nothing relating to language.
> But in any case, I'm curious, since my windows installation is in english,
> shouldn't mypaint be in english as well? I'm not sure what settings we are
> talking about here, since I cannot find this format tab.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/568#issuecomment-172769599


-- 
!tuma

**Comment by Klesus** [comment]
Alright, I found where the Formats tab is located. It's under "Region and language" in the control panel; a big chunk of information left out there IMO. But my format settings I DO want in swedish. Are you telling me it's impossible to have it both ways? That if I want mypaint in english I have to constantly change formatting every time I start up mypaint?

**Comment by tumagonx** [comment]
Well just dont install locales then.

On 1/19/16, Klesus <notifications@github.com> wrote:
> Alright, I found where the Formats tab is located. It's under "Region and
> language" in the control panel; a big chunk of information left out there
> IMO. But my format settings I DO want in swedish. Are you telling me it's
> impossible to have it both ways? That if I want mypaint in english I have to
> constantly change formatting every time I start up mypaint?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/568#issuecomment-172771760


-- 
!tuma

**Comment by tumagonx** [comment]
I meant during install mypaint uncheck "install translations"

On 1/19/16, Bakhtiar Hasmanan <mr.tiar@gmail.com> wrote:
> Well just dont install locales then.
>
> On 1/19/16, Klesus <notifications@github.com> wrote:
>> Alright, I found where the Formats tab is located. It's under "Region and
>> language" in the control panel; a big chunk of information left out there
>> IMO. But my format settings I DO want in swedish. Are you telling me it's
>> impossible to have it both ways? That if I want mypaint in english I have
>> to
>> constantly change formatting every time I start up mypaint?
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mypaint/mypaint/issues/568#issuecomment-172771760
>
>
> --
> !tuma
>


-- 
!tuma

**Comment by Klesus** [comment]
Seems to be the only way, but not ideal IMHO.

**Comment by achadwick** [comment]
Yeah, gettext can be a bit awkward. But it works on all the platforms we support with a bit of coaxing.

There is a workaround for this specific issue already from #438 , so I'm closing it. If someone wants to add user language selection at runtime, than can be done with a separate PR.
