### ISSUE TITLE
Intuos GD-0912-R Pressure not detected

### ISSUE THREAD

**Issue by Hubert21** [mypaint/mypaint#570]
Hello and thanks for your great work,
I am using an old wacom serial tablet, Intuos GD-0912-R, with an Serial to Usb adapter, prolific PL2303 (used driver PL2303_Prolific_DriverInstaller_v1_11_0), and win 8.
Only 32 bits apps do have pressure working.
On the previous versions of Mypaint, e.g. 1.0.0 (32 bits), the pressure was also working fine.
However, on the new 1.2 (32 bits), the pressure is not detected.
On the Input device test, it shows "Device: WACOM Tablet Pressure Stylus", but also "Pressure: (no pressure)" 
(I tried to launch the axischart.py python app, to know if I would get the same error from another gdk3 app, but get the error: EOFError: [Errno 10054] An existing connection was forcibly closed by the remote host)
Any idea how to solve this?
Thanks

**Comment by achadwick** [comment]
Not a clue, sorry. Does it work in GIMP or Krita?

What version of the Wacom driver are you using? What version and how recent is your wintab.dll or wintab32.dll?

**Comment by achadwick** [comment]
TRIAGE: this is an ancient bit of hardware from the days of beige plastic and D-sub serial ports. I doubt Wacom themselves support it these days. This issue is unlikely to turn into anything we can solve in MyPaint with a code commit, so in all likelihood it's a question that should be asked elsewhere. AT BEST it might be resolvable by working with the GDK maintainers, but I'm not even certain this thing has a Wintab presentation, let alone a Windows Ink.

Close in a week if nobody has any bright ideas.

**Comment by achadwick** [comment]
(I should add: you may be able to ask other users on the [Community Forum](http://community.mypaint.org/), which tends to be more popular than this issue tracker. Good luck, and please consider chasing for upstream support at the [GNOME/GTK/GDK Bugzilla](https://bugzilla.gnome.org/buglist.cgi?quicksearch=GD-0912-R). All of MyPaint and GIMP's tablet support comes through the GDK project.)

**Comment by Hubert21** [comment]
Thanks for your replies and links.
The pressure is working fine on Gimp, Krita and Blender (all 32 bits).
The wacom driver used is the 6.1.0-6, from 2008, as on further drivers the serial port was not implemented anymore (few tricks have to be used to let it work on windows 7 and 8, as quickly described in this page: http://7fttallrussian.blogspot.fr/2013/04/how-to-get-serial-wacom-tablet-to-work.html)
The installer the driver contains wintab32.dll version 1.0.4-1, which is installed on windows as C:\Windows\SysWOW64\Wintab32.dll, and it's the one mypaint 1.0.0 is using when running.

**Comment by Hubert21** [comment]
Hello,
I understand that I might be one of the very few who got this bug, so it might not be worth spending much time.
I also didn't report the bug on gtk yet, because it's working on krita and gimp (and on mypaint 1.0), so maybe there is a lib or part of the code where I could spot the difference...
I got axischart.py working (https://gist.github.com/achadwick/54e5b111e5ac908becf1) with a fresh install of python 3.4 and gdk 3.18.6 (via pygi-aio).
The x and y are showing black curves/area, but the pressure, xtilt, ytilt and whell are not showing any info.
It is also running with python 2.7 and gtk 3.0.0, with the same result (x y ok, nothing on pressure tilts and whell)
Would you know any test, e.g. in Python, I could do? (I am thinking of digging inside the code of mypaint 1.0, or in gimp or krita...)

**Comment by achadwick** [comment]
@Hubert21 
I think this has to be a GTK2 vs. GTK3 thing. It's probably not a Python 2.7 vs. Python3 thing.

If it were me, I'd suggest trying to get a minimal msys2 up and running, then trying the axischart program from its "MINGW64" environment. And then running it against both GTK2 and GTK3.

I've added some PyGTK support into the gist. Unluckily, tablet support back in PyGTK was... finicky... and had to be turned on specifically in ways I don't quite remember right now. I'll have a go this evening when I have access to more hardware.

**Comment by achadwick** [comment]
(I didn't really have the time to investigate, sorry)

@Hubert21 
If you're still interested in chasing this bug, please note that [MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) was released recently. It contains a rather newer version of GTK with several fixes for Wintab issues. Please can you test it out, and let us know whether this problem is still happening?

**Comment by Hubert21** [comment]
Hello,
Thanks for reopening this and sorry it took me a while to figure that out!
I still have the same problem with the version 1.2.1. I have found alternatives to mypaint through krita and blender, though I used to be fan of mypaint.
Maybe I will not have this problem with the 2.0 version ; is there any 32bits standalone version of the 2.0a somewhere?
Thanks

**Comment by jplloyd** [comment]
@Hubert21 
Link to latest alpha (32 bit standalone, 7z): https://github.com/mypaint/mypaint/releases/download/v2.0.0-alpha.13/mypaint-git-w32-2.0.0-alpha-master.564-standalone.7z

**Comment by Hubert21** [comment]
Thanks.
In this version of mypaint, the pen position is working, but the pressure is not recognized and mypaint does not even notice when the pen is on the tablet.
It comes with gtk3-demo-event-axes.exe which detect both the tablet and the pressure.
In the gtk3-demo.exe there is a paint section-application, in which I have the same results than in mypaint (pen position of, but no pressure, no detection of the pen on the tablet)

**Comment by jplloyd** [comment]
@Hubert21 That's good info, thanks! I can't promise that this will be fixed in time for 2.0, but the fact that it works in one of the demos at least suggests it's fixable.

**Comment by Hubert21** [comment]
Thanks to you! Don't hesitate to ask me to do some tests ; it seams to me I can do tests/changes directly in the .py files in mingw32\lib\mypaint\lib.
For your information, I get the same results with the mouse: correct pen position, can click on buttons around, but no drawing when I click on the canva.

**Comment by AesaraB** [comment]
[Added to compatibility table](https://github.com/mypaint/mypaint/wiki/Device-support-table)
