### ISSUE TITLE
An extra line after switching from Inking to Freehand tool

### ISSUE THREAD

**Issue by danpla** [mypaint/mypaint#571]
MyPaint draws an extra line after switching from Inking to Freehand tool.

Steps to reproduce:
1. Draw a path using the Inking tool. Delete or "apply" the path.
2. Choose Freehand tool from toolbar or using hotkeys. Move pointer on canvas.

Result: an extra line appears from the last point of the path to the pointer (or the edge of the canvas where pointer entered, if Freehand was selected on toolbar). You can undo it with Ctrl+Z.

![2016-01-20 15_03_21-mypaint](https://cloud.githubusercontent.com/assets/10910745/12449630/417358f6-bf87-11e5-8fde-ec6eaa541c4d.png)

MyPaint 1.2.0 on Windows 7 x64

**Comment by achadwick** [comment]
Reproduced under Linux with GNOME/GTK 3.18.6 using a mouse. Thanks for the clear set of instructions for reproducing this glitch!

**Comment by achadwick** [comment]
Reproduced with a graphics tablet too. Always starting freehand mode's brushwork abruptly in the enter() it receives just after it's created seems to make this go away, and doesn't seem to cause any glitches of its own.

"Abrupt" start and stops are all about tailing brushwork off neatly for certain sequences of input.

There's good cause for not being abrupt when continuing in freehand mode. That second enter() may come from having a PanViewMode pushed onto the mode stack by the user panning the canvas with space *while painting*. Yes, we allow that! When the pan mode is popped, the original FreehandMode object receives a second enter(), and it shouldn't do anything abruptly when painting resumes.

I need to see if there's any subclass of BrushworkMode that needs *non*-abrupt brushwork starts for the initial enter(). There's code here that could be ripped out if there isn't.

Coffee first though! :coffee:

**Comment by achadwick** [comment]
Need to ensure there's no regression on #11 when fixing this.

**Comment by achadwick** [comment]
Pushed for the next patch release, and for the next release proper ☺
