### ISSUE TITLE
Duplicate colors appear in color history when using number keys to pick brushes

### ISSUE THREAD

**Issue by mikshaw** [mypaint/mypaint#573]
In the last couple of commits to master, including 9c640bb and 5170ffc, possibly slightly earlier, choosing a preset brush with a number key and then painting can *sometimes* result in duplicated colors in the color history list... e.g. you end up with 2 or 3 history slots that are just black. I don't know if it happens with any other colors.

"It can be recreated by first populating the history by choosing and painting with bright colours from the default palette, then opening the history panel, and using the default brushkeys 1,2,3,4 many of which restore black. But you have to paint with each of the brushkey-brushes before the history is updated.
Workaround: uncheck 'Brush Shortcut Keys Restore Colour': https://github.com/mypaint/mypaint/wiki/v1.2-Brush-Shortcut-Keys#options " — @achadwick via irc 

Thank you for pointing to the workaround. I would prefer to usually keep my chosen color when swapping brushes anyway, but i wasn't aware of this option.

**Comment by achadwick** [comment]
Fixed! Silly mistake, tests in to stop it from happening again.
