### ISSUE TITLE
Layer color corrector tool

### ISSUE THREAD

**Issue by nekohayo** [mypaint/mypaint#575]
It is very hard for me to consistently pick the "right" colors from the start for every part of my illustrations. The colors do not work in isolation, they need to be harmonized across different elements of the painting, so what works in the beginning might need to be adjusted later on etc. For solid colors, that wouldn't be much of a problem... but the thing is that my many layers are soft shading or textured, so you can't simply overwrite/start over just because you want to correct the color tint and such.

So, trying my luck: I'd really love to have a "Color corrector" dialog in MyPaint allowing me to rebalance a whole layer in one go. Basically, something similar to GIMP's color balance/levels/curves dialogs (or something like the triple color wheels commonly found in video editing software's color correction filters). I don't want to use GIMP (or any third party app) for this: I'd like to be able to do those adjustments directly in MyPaint as the painting evolves, not having to frequently interrupt the workflow or having to worry about exporting/importing compatibility.

**Comment by achadwick** [comment]
Without a plugin system, this feels wrong for MyPaint. I don't want to add it myself right now.

Immediate workaround: perhaps the tool for this is editing the layer in an external tool which does allow rebalancing.
