### ISSUE TITLE
Drawing lag / freeze when freehand drawing with Wacom Bamboo tablet

### ISSUE THREAD

**Issue by NMLevesque** [mypaint/mypaint#576]
When trying to use the freehand drawing function with my tablet it will not render anything until I stop.

Win 8.1 64 bit
1.2.0+git.f62444e.dirty
BAMBOO FUN CTH-661

**Comment by achadwick** [comment]
@NMLevesque Does it look like the problems in the videos in #390 ?

**Comment by NMLevesque** [comment]
Checked for driver updates at Wacom's website and that seems to have fixed it.  Sorry I didn't think of it sooner.

**Comment by achadwick** [comment]
Ah, simple enough this one :grinning:  Glad you got it fixed!

I'll mark the issue closed. If you can, please post a comment saying which driver versions you upgraded from/to. That'll help people searching for known issues!
