### ISSUE TITLE
Cannot start mypaint-1.2.0

### ISSUE THREAD

**Issue by juanitotc** [mypaint/mypaint#577]
mypaint-1.2.0 compiled from source with python-2.7.10

When I try to start mypaint, I get:

$ /usr/local/bin/mypaint
CRITICAL: mypaint: Installation layout: unknown!
Traceback (most recent call last):
  File "/usr/local/bin/mypaint", line 442, in <module>
    = get_paths()
  File "/usr/local/bin/mypaint", line 205, in get_paths
    raise RuntimeError("Unknown install type; could not determine paths")
RuntimeError: Unknown install type; could not determine paths

**Comment by achadwick** [comment]
Hi - looks like an incorrect installation. Please tell me what operating system is this, and how you installed MyPaint.

What does the following print?

```
$ ls -lda /usr/local/share/{locale,mypaint,icons}
```

**Comment by juanitotc** [comment]
Using tinycorelinux 64-bit

Installed with "sudo scons prefix=/usr/local install"

$ ls -lda /usr/local/share/{locale,mypaint,icons}

drwxr-xr-x   29 root     root           580 Jan 27 15:25 /usr/local/share/locale/
drwxr-xr-x    8 root     root           160 Jan 27 11:24 /usr/local/share/mypaint/
drwxr-xr-x    6 root     root           120 Jan 27 11:24 /usr/local/share/icons/

**Comment by achadwick** [comment]
It should be getting further than that. Without examining your installation, I can't go any further though.

Here's the code in question: https://github.com/mypaint/mypaint/blob/v1.2.0/mypaint.py#L158

A couple more questions:

1. Are there any interesting symlink things going on up in your `/usr/local`?
2. Are you able to run MyPaint as `./mypaint` from within your local clone?

**Comment by achadwick** [comment]
Tiny Core is fairly unconventional: <http://tinycorelinux.net/concepts.html>. Which Mode of Operation are you using?

**Comment by juanitotc** [comment]
Sorry, I should have mentioned that tinycorelinux extensions (packages) are squashfs loop mounted and symlinked to the root filesystem.

That being said, the extensions can be loaded in such a way that they are loop mounted, copied to the root filesystem and then unmounted.

I get the same error for both modes.

I'm not sure what is meant by "./mypaint from within your local clone"?

**Comment by juanitotc** [comment]
I just rebooted with everything copied to the filesystem so it looks like a standard linux os, albeit with the entire filesystem in RAM, but the error remains.

Is there some pythonese I can enter in a terminal to help debug?

**Comment by achadwick** [comment]
You could try printing the values of specific variables in that `get_paths()` routine - i.e. edit the file, and insert "`print "INITIAL PATHS:", map(repr, [libpath, localepath, localepath_brushlib, iconspath])`" above that "`if all()`" statement at line 158:

https://github.com/mypaint/mypaint/blob/v1.2.0/mypaint.py#L158

Spaces for indents or Python hisses.

Really this should be diagnosable by turning on the `MYPAINT_DEBUG` environment variable, so I'll patch that up in master.

**Comment by achadwick** [comment]
> I'm not sure what is meant by "./mypaint from within your local clone"?

You can run MyPaint in a local testing mode by running it from its own source tree after it's been built.

```
$ cd /path/to/mypaint-source
$ git submodule update --init --force
$ scons
$ ./mypaint
```

It uses relative locations for things if you do that, but shouldn't apply anything that symlink resolution stuff could trip over. I suspect the `os.path.realpath()` calls are to blame here.

**Comment by juanitotc** [comment]
After adding the print statement I get:

$ mypaint
INITIAL PATHS: ["u'/usr/local/share/mypaint'", "u'/usr/local/share/locale'", "u'/usr/local/share/locale'", "u'/usr/local/share/icons'"]
CRITICAL: mypaint: Installation layout: unknown!
Traceback (most recent call last):
  File "/usr/local/bin/mypaint", line 443, in <module>
    = get_paths()
  File "/usr/local/bin/mypaint", line 206, in get_paths
    raise RuntimeError("Unknown install type; could not determine paths")
RuntimeError: Unknown install type; could not determine paths

**Comment by juanitotc** [comment]
Ah - got it :)

I had not included the files under /usr/local/share/locale as these files are usually not required for an application to work and take up valuable space.

I also had to create the folder ~/.local/share/mypaint as mypaint fails if this does not exist - maybe it could be smarter in this respect :P

Thanks for your help - things now work.

**Comment by achadwick** [comment]
MyPaint can be a bit smarter about a few things here. Patches soon.

Regarding ~/.local and ~/.config: it's already patched in 36adc5d288f4b4c5ab7bd98ee3c6f69860f26522, but that was merged after v1.2.0. Perhaps that's a call for a v1.2.x branch to collect small bugfix backports.

**Comment by juanitotc** [comment]
tinycorelinux mypaint extension uploaded to the corepure64 v7.0 repo :)

**Comment by juanitotc** [comment]
..the extension works in both normal and copy2fs mode

**Comment by achadwick** [comment]
Awesome, thanks! I'll patch in the fixes for the issues you identified.

**Comment by achadwick** [comment]
Patches are now in for 1.3.0, and backported ready for 1.2.1. Closed ☺
