### ISSUE TITLE
Release v1.2.1

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#578]
I've created a [v1.2.x branch](https://github.com/mypaint/mypaint/tree/v1.2.x) for collecting backports and one-off fixes for quick release after v1.2.0. Timeline uncertain right now, but "soon".

**Comment by alexandre-mbm** [comment]
It is empty.

**Comment by achadwick** [comment]
@alexandre-mbm 
> It is empty.

My mistake. I hit Create by accident. I've updated the original bug description.

**Comment by alexandre-mbm** [comment]
And the milestone? After the fixes you may delete my comments.

**Comment by achadwick** [comment]
@alexandre-mbm Its milestone contains this issue.

**Comment by alexandre-mbm** [comment]
Okay. I think I understand now: one-off fixes.

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now up.
