### ISSUE TITLE
El Capitan:Macports: ImportError: No module named AppKit

### ISSUE THREAD

**Issue by xocd** [mypaint/mypaint#579]
Need help getting MyPaint to run, please see below.  Unsuccessfully googled the problem.  Thanks in advance. 

Attempted to install MyPaint on an Apple laptop (15" early 2011)
= System =
OS: 10.11.3
MacPorts 2.3.4  

= Verifying Installation =
Repeated installation command (using MACPORTS_PREFIX='/opt/local') and get:
> sudo port install MyPaint
Password:
--->  Computing dependencies for MyPaint
--->  Cleaning MyPaint
--->  Scanning binaries for linking errors
--->  No broken files found.

= Trying to run it =
== Clicking on app ==
If I click on the app itself nothing happens.

== CLI ==
Attempt to start MyPaint from CLI:
> which MyPaint
/opt/local/bin/MyPaint
> MyPaint &
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/opt/local'
Traceback (most recent call last):
  File "/opt/local/bin/MyPaint", line 450, in <module>
    init_gettext(localepath, localepath_brushlib)
  File "/opt/local/bin/MyPaint", line 255, in init_gettext
    lib.i18n.set_i18n_envvars()
  File "/opt/local/share/mypaint/lib/i18n.py", line 103, in set_i18n_envvars
    from AppKit import NSLocale
ImportError: No module named AppKit

**Comment by achadwick** [comment]
@xocd 
What version of MyPaint is this?
What version of Python is this?
Have you reported this to the MacPorts maintainer?

I don't have a Mac to try this code on, so I'm reliant on testers finding and fixing problems on that platform. The [MyPaint code for i18n setup](https://github.com/mypaint/mypaint/blob/v1.2.0/lib/i18n.py#L102) is copied from [QuodLibet's equivalent](https://github.com/quodlibet/quodlibet/blob/76bb75fa677a8a1db830fbe47d0000788184e903/quodlibet/quodlibet/util/i18n.py#L58), but the OS X branch may not have received any useful testing.

Patches welcome in the first instance for making it work but log an error in the absence of `AppKit`, which until now I have assumed is some standard Apple Python library. Try sticking the `import` statement and the remainder of the darwin setup inside a `try: ... except:` block.

**Comment by xocd** [comment]
@Andrew Chadwick,

First, thanks for your response!

It seems that the python at /opt/local/bin/, which is the one that MacPorts installs and MyPaint uses, does not to know about AppKit.   (I believe /opt/local is the canonical place for MacPorts stuff.)

(Caveat: I am not a pythonist)
I created a file 'test.py' containing just one line: 'from AppKit import NSLocale'.  
- If I type at the CLI 'python test.py' it seems to work (it is using the python that came with the mac which livest at /usr/bin/python).  
- If I type '/opt/local/bin/python2.7 test.py' I get the following error:
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from AppKit import NSLocale
ImportError: No module named AppKit

  There must be a way around this but right now I cannot figure it out.

>What version of MyPaint is this?
Looking at the url below seems to be MyPaint 1.2.0 (port install MyPaint)
 https://www.macports.org/ports.php?by=name&substr=MyPaint

>What version of Python is this?
From reading the Portfile I believe it's using 2.7
https://trac.macports.org/browser/trunk/dports/graphics/MyPaint/Portfile

>Have you reported this to the MacPorts maintainer?
The maintainer is listed as ryandesign, https://github.com/ryandesign. I have not figured out how to report this issue to him  (I am new at github).

Thanks!
Isidro
(aka xocd)

**Comment by achadwick** [comment]
@xocd 
That's \@ryandesign here. Silly me for forgetting.

@ryandesign: can you shed any light on this issue?

I don't know how issues are reported in MacPorts, and they seem to be coming here. This one seems to be a packaging issue, but if there's anything we need to do to MyPaint to make it work, please let us know.

Can I reassign this issue to you to investigate? I don't have access to any Mac hardware.

**Comment by ryandesign** [comment]
MacPorts issues should be reported by [filing a ticket in the MacPorts issue tracker](https://guide.macports.org/chunked/project.html).

This issue was [reported to MacPorts](https://trac.macports.org/ticket/48849) 5 months ago. I advised the reported to report it here because the problem did not happen for me.

It appears that your new localization code has introduced a new dependency on OS X, on pyobjc-cocoa. I can add that dependency to the port in MacPorts.

A MacPorts user [proposed a change to MyPaint code](https://trac.macports.org/attachment/ticket/48849/patch-MyPaint-devel-i18n.diff) to make it fail gracefully if pyobjc-cocoa is not available.

**Comment by ryandesign** [comment]
It may be enough to list the pyobjc-cocoa dependency in the readme. On the other hand, the MacPorts user also noted that he could not get MyPaint to work when using pyobjc-cocoa under OS X 10.7 Lion, so making the use of pyobjc-cocoa optional may be desirable to support those users. I have not yet tested this issue on Lion.

**Comment by achadwick** [comment]
@ryandesign
Thanks for pointing me at that patch. I'll push something like it over lunch, and mention the dependency as an optional tweak.

Do you thin there is any big risk for newer OSX versions of the import segfaulting Python, as mentioned in <https://trac.macports.org/ticket/48849#comment:6>? That sort of thing can't be caught and handled gracefully in Python code.

**Comment by ryandesign** [comment]
> Do you thin there is any big risk for newer OSX versions of the import segfaulting Python

I hope not...

**Comment by xocd** [comment]
OP here.  I am probably confused.  The issue is closed but the problem persists.  I updated MacPorts (port selfupdate).  Uninstalled MyPaint and then re-installed it.  When I try to run it I get:

INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/opt/local'
Traceback (most recent call last):
  File "/opt/local/bin/MyPaint", line 450, in <module>
    init_gettext(localepath, localepath_brushlib)
  File "/opt/local/bin/MyPaint", line 255, in init_gettext
    lib.i18n.set_i18n_envvars()
  File "/opt/local/share/mypaint/lib/i18n.py", line 103, in set_i18n_envvars
    from AppKit import NSLocale
ImportError: No module named AppKit

Is there anything I need to do to get a fixed version?

Thanks,
Isidro

**Comment by ryandesign** [comment]
I haven't made any change for this in MacPorts yet. But you can fix it by running:

```
sudo port install py27-pyobjc-cocoa
```

**Comment by achadwick** [comment]
We've fixed up our docs and code here, and the integration problem is being handled downstream from us in MacPorts: https://trac.macports.org/ticket/48849. Thanks again @ryandesign!
