### ISSUE TITLE
persistent association between layer and external file?

### ISSUE THREAD

**Issue by jeisner** [mypaint/mypaint#581]
During a MyPaint session, the user may edit a layer using an external app.
I believe that the association between the layer and the external file goes away when MyPaint is closed or when the user moves to another drawing.
However, **the file might remain open in the external app**.  So it would be neat if the association were restored when MyPaint came back to the same drawing (on the same machine).
Then MyPaint would automatically slurp in any edits that had already been saved to the file while MyPaint was closed.  Also, any future edits to the file would automatically show up in MyPaint.  

One way to accomplish this would be to store the association (from the MyPaint filename+layer to the external-editor file) under the .cache directory.

This is nicer than the current situation, where I have to relaunch the external app from MyPaint when I come back to the drawing.  That gives me two open windows in the external app, on different versions of the same layer.  One is stale and useless and should be closed, but will I correctly guess which one?  And even after I close the stale window, there are two versions of the file under the .cache directory, one being stale.  In order to save as PNG or SVG from the external editor, I generally have to choose its export command and then correctly pick one of those two files to click on.  In short, it would be nicer to just go on using the old file and, if the external app remained open, the old window.

**Comment by achadwick** [comment]
[NOTE: this request is against v1.2.0.]

It also goes away when a user deletes a layer, despite the old layer having been moved temporarily to the undo stack. It has to. External edits must be transient, self-terminating, non-repeating, and outside the layer model or they'll start doing nasty things like updating layers on the undo stack after their layer has been undoably removed from the tree. They cannot themselves be layer properties in the model without a lot of thought.

Edits create new entries on the undo stack when you save, so this means that the external edits must live outside the undo stack too. But perhaps they could be maintained by the document model?

Sure, layers can have mere string properties, and our OpenRaster XML dialect permits extensions. You'd have to reconstruct ongoing layer edits' filesystem watches after the tree is rebuilt by examining the file system.

Certainly a cleverer way of mediating it than the weakref mess the [current LayerEditManager](https://github.com/mypaint/mypaint/blob/v1.2.x/gui/externalapp.py#L207) uses would be welcome, and I'd be happy to accept good patches that move the messy bits to `lib/` while cleaning them up. I've no immediate plans to do this though.

One huge problem is that a new `.cache/mypaint/doc.XXXXX` folder is created for each new document, and the `edits/` folder lives in there. You're supposed to be able to delete everything to do with a document cache folder at once, at least that was the theory :)

`edits/` could be moved out of the doc cache folder though.

**Comment by odysseywestra** [comment]
Closing in favor of #98. It probably would be best to have a global default app instead of complicating with each layer having it own app defaults.
