### ISSUE TITLE
Downloaded version 1.2 on windows yet not opening when download was finished.

### ISSUE THREAD

**Issue by knifepartyfan** [mypaint/mypaint#587]
I wanted to try to the new release because I loved the new format, but it will never open when I click the icon. Is there any way to actually fix this issue?

**Comment by odysseywestra** [comment]
Sorry but this question is better suited for our community forums over at http://community.mypaint.org since its a user support question.

**Comment by knifepartyfan** [comment]
Seems to be that I can't place this as a topic or comment in the forums. I'll have to try to contact someone else with this, but thanks.

**Comment by odysseywestra** [comment]
I had to approve the post since your a new user on the forums. It's Discourse doing as its design to prevent spam or abuse. I rather it error on side caution. Sorry for that. ^^'

**Comment by odysseywestra** [comment]
I'll go ahead and mark this as closed. It will be reopened if it turns out to be a bug with the installer.
