### ISSUE TITLE
My paint installation through mypaint.iss.in file in Inno Setup

### ISSUE THREAD

**Issue by asp94** [mypaint/mypaint#590]
When i am running this script mypaint.iss.in i am getting an error at line 41
Source: "mingw@BITS@\*"; DestDir: "{app}"; Excludes: "\share\locale\*"; Flags: ignoreversion recursesubdirs createallsubdirs
 No files found matching

I builded the script using build.sh it was successful in the first go.

**Comment by achadwick** [comment]
Hi, thanks for reporting. Please can you answer a few questions about this?

How did you run build.sh the first time? And the second? Please tell me the exact command line you used each time. Are any of those builds sloppy builds (see the output of `windows/buid.sh --sloppy`.

What version of MyPaint is this?

What version of Windows are you running MSYS2 on?

What version of MSYS2 are you running? And which shell did you use?

**Comment by achadwick** [comment]
@asp94 
Sorry to be a pain, but we need more information about your system, and more information about your MyPaint installation if this report is going to be useful to us.

Can you tell me what version of Inno Setup you have installed on your computer please?

mypaint.iss.in is not run directly by ISCC. It's a template file that's used to make the installer.

**Comment by achadwick** [comment]
NVM. Didn't see you'd closed this. How did you resolve the issue, out of interest? The solution may be useful to other people who get the same error.

**Comment by asp94** [comment]
Hi ,
I am using an windows 10 machine. I am installing the updated version of mypaint 1.2.0.
I pulled out of this conversation as I started building the product again from scratch.
