### ISSUE TITLE
Installation through source code

### ISSUE THREAD

**Issue by asp94** [mypaint/mypaint#591]
Getting an error libintl.h file not found/ no such directory exists 

while building mypaint through 
 cd /usr/src/mypaint
 scons

Able to locate file in
 C:\msys64\tmp\mypaint-builds\1502bc9\x86_64\mypaint-w64-1.3.0-alpha\mingw64\include\libintl.h

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
  from . import multiarray
set umask to 0022 (was 0022)
scons: done reading SConscript files.
scons: Building targets ...
gcc -o brushlib/mypaint-brush-settings.o -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 -Wall -g -DHAVE_JSON_C -DHAVE_GETTEXT -Ibrushlib -I/mingw64/include/json-c brushlib/mypaint-brush-settings.c
brushlib/mypaint-brush-settings.c:25:23: fatal error: libintl.h: No such file or directory
compilation terminated.
scons: *** [brushlib/mypaint-brush-settings.o] Error 1
scons: building terminated because of errors.

**Comment by achadwick** [comment]
Hi, thanks for reporting. You may be missing some dependencies. Did you [install what was needed](https://github.com/mypaint/mypaint/blob/master/README_WINDOWS.md#install-mypaints-dependencies) first?

`/tmp/mypaint-builds` is something that only `windows/build.sh` creates, and it is not relevant to this style of build.

This tracker doesn't get many eyes, so you may find you get more useful feedback by asking in the [MyPaint Community Forums][http://community.mypaint.org/] too.

How recent an MSYS2 install is this? If it was from scratch, I can go through the instructions from scratch on my Win7 VM for you to see if I can reproduce this issue.

**Comment by achadwick** [comment]
**TRIAGE NOTE:** looks like a user support request. This is technically the wrong forum for direct user support, reporter has been redirected to one better places to ask.

However there may well be an upstream change we haven't seen yet. It happens. This issue should be closed after a couple of weeks though if no further information is forthcoming that would allow it to be progressed to `bug` or `enhancement` status. Meanwhile, I'll double-check our docs for Windows geeks ☺

**Comment by asp94** [comment]
Hi ,
Thanks for reaching out.
I have downloaded the msys through https://msys2.github.io/ and the dependencies from install-msys2-deps.sh 
I will check building through windows/build.sh
Will post on community forum too thanks, :)

**Comment by achadwick** [comment]
@asp94 I've reviewed the docs, and they work for me.

Can you check your gettext installation please?

```
Test User@win7test MSYS /usr/src/mypaint
$ ls -ld /mingw64/include/libintl.h
-rw-r--r-- 1 Test User None 16677 Nov 30 10:12 /mingw64/include/libintl.h

Test User@win7test MSYS /usr/src/mypaint
$ pacman -Qo /mingw64/include/libintl.h
/mingw64/include/libintl.h is owned by mingw-w64-x86_64-gettext 0.19.6-2

Test User@win7test MSYS /usr/src/mypaint
$ pacman -Ss gettext
mingw32/mingw-w64-i686-gettext 0.19.6-2
    GNU internationalization library (mingw-w64)
mingw64/mingw-w64-x86_64-gettext 0.19.6-2 [installed]
    GNU internationalization library (mingw-w64)
msys/gettext 0.19.6-1 (base-devel) [installed]
    GNU internationalization library
msys/gettext-devel 0.19.6-1 (development)
    GNU Internationalization development utilities
msys/libgettextpo 0.19.6-1 (libraries) [installed]
    GNU Internationalization runtime library
msys/perl-Locale-Gettext 1.05-4 (perl-modules) [installed]
    Permits access from Perl to the gettext() family of functions
```

**Comment by asp94** [comment]
Yes I have checked with the gettext installation
$ pacman -Ss gettext
mingw32/mingw-w64-i686-gettext 0.19.6-2
    GNU internationalization library (mingw-w64)
mingw64/mingw-w64-x86_64-gettext 0.19.6-2 [installed]
    GNU internationalization library (mingw-w64)
msys/gettext 0.19.6-1 (base-devel) [installed]
    GNU internationalization library
msys/gettext-devel 0.19.6-1 (development)
    GNU Internationalization development utilities
msys/libgettextpo 0.19.6-1 (libraries) [installed]
    GNU Internationalization runtime library
msys/perl-Locale-Gettext 1.05-4 (perl-modules) [installed]
    Permits access from Perl to the gettext() family of functions

The problem still persists...I have followed the following steps for installation if you want to review
Updated MSYS 2 using

**Comment by tumagonx** [comment]
@asp94
dirty way: just search libintl.h recursively in your MSYS directory,
is it exist? then copy to gcc's include dir. There is no way gcc would
missed it (its internal search path) unless somehow scons pick
different gcc.exe.

On 2/5/16, asp94 <notifications@github.com> wrote:
> Yes I have checked with the gettext installation
> $ pacman -Ss gettext
> mingw32/mingw-w64-i686-gettext 0.19.6-2
>     GNU internationalization library (mingw-w64)
> mingw64/mingw-w64-x86_64-gettext 0.19.6-2 [installed]
>     GNU internationalization library (mingw-w64)
> msys/gettext 0.19.6-1 (base-devel) [installed]
>     GNU internationalization library
> msys/gettext-devel 0.19.6-1 (development)
>     GNU Internationalization development utilities
> msys/libgettextpo 0.19.6-1 (libraries) [installed]
>     GNU Internationalization runtime library
> msys/perl-Locale-Gettext 1.05-4 (perl-modules) [installed]
>     Permits access from Perl to the gettext() family of functions
>
> The problem still persists...I have followed the following steps for
> installation if you want to review
> Updated MSYS 2 using
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/591#issuecomment-180128709


-- 
!tuma

**Comment by asp94** [comment]
Hi I copied the libintl.h file in the gcc's include dir and the script worked fine. There are couple of header files missing 
I included

**Comment by asp94** [comment]
ABLE TO RESOLVE ALL ISSUES ! thanks for all the help :)

**Comment by achadwick** [comment]
@asp94 Good news, thanks. If you can, please let everyone searching for this issue know how you solved it.
