### ISSUE TITLE
MyPaint fails to start up if ~/.local/share doesn't exist

### ISSUE THREAD

**Issue by ryandesign** [mypaint/mypaint#594]
Starting MyPaint 1.2.0 (installed with MacPorts) for the first time fails:

```
$ mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/opt/local'
INFO: lib.i18n: OSX: LANG='en_US.UTF-8'
INFO: lib.i18n: OSX: LANGUAGE=u'en'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
ERROR: mypaint: No platform-specific fallback for locating bindtextdomain is known for 'darwin'
INFO: gui.application: Created basedir u'/Users/rschmidt/.config/mypaint'
Traceback (most recent call last):
  File "/opt/local/bin/mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/opt/local/share/mypaint/gui/main.py", line 225, in main
    run()
  File "/opt/local/share/mypaint/gui/main.py", line 202, in run
    fullscreen = options.fullscreen,
  File "/opt/local/share/mypaint/gui/application.py", line 223, in __init__
    os.mkdir(basedir)
OSError: [Errno 2] No such file or directory: '/Users/rschmidt/.local/share/mypaint'
```

I worked around the problem by running:

```
mkdir ~/.local/share
```

If MyPaint requires this directory, it should create it.

**Comment by achadwick** [comment]
Hi, thanks for the report. This has already been fixed on our development branches:

* v1.2.1 (branch `v1.2.x`): 6287c50fea276c41d3548660566cb25bf4db7820
* v1.3.0 (branch `master`): 36adc5d288f4b4c5ab7bd98ee3c6f69860f26522

Duplicates part of https://github.com/mypaint/mypaint/issues/577#issuecomment-175630580, but let's let this issue as the main report for this issue. I don't think it's been reported anywhere else.

**Comment by ryandesign** [comment]
> Duplicates part of #577 (comment)

Unrelated, but could you tell me what syntax you used to link to a *comment* of a GitHub ticket?

**Comment by achadwick** [comment]
@ryandesign
You can paste the "time ago" link from the `[username] commented [n-whatevs-ago]` header. Github is smart enough about its own URLs to let you do that.

**Comment by ryandesign** [comment]
Thanks, I overlooked that "*time* ago" was a link. They could make that more obvious!
