### ISSUE TITLE
Copy and pasting images pastes first copied image

### ISSUE THREAD

**Issue by Timmmm** [mypaint/mypaint#595]
On Windows:

1. Copy an image (e.g. using the Snipping Tool).
2. Paste it in MyPaint (this works)
3. Copy another image.
4. Paste it in MyPaint

The result is that the first image is pasted. All future pastes paste the first image. You have to quit MyPaint and re-open it to paste a different image.

**Comment by odysseywestra** [comment]
Hi there, thanks for reporting this. Before we can help you, we will need more information. Please visit our [bug reporting wiki](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs) for what information we need from you.

**Comment by achadwick** [comment]
Cannot reproduce with master as of mypaint 5dce1966971ccf2a6832ed33516bdc72cd3653cd in Debian testing/unstable using the GNOME screenshot tool.

@Timmmm Nice steps for reproducing, thanks!
Please let us know your system details, and what version this is when you can.

**Comment by achadwick** [comment]
Here's our paste implementation on the master branch right now: [gui/document.py line 852](https://github.com/mypaint/mypaint/blob/5dce1966971ccf2a6832ed33516bdc72cd3653cd/gui/document.py#L852). There's no variable that stays in scope for long enough for this problem to be cause by caching within MyPaint itself. I think we're handling the [clipboard](https://developer.gnome.org/gtk3/stable/gtk3-Clipboards.html) correctly, but I may be wrong.

(Despite appearances, our code there is PyGI for GTK3)

**Comment by achadwick** [comment]
Note to (potentially just) myself: when testing in a desktop VM, turn off shared clipboards.

**Comment by Timmmm** [comment]
Double checked; this definitely happens. I'm using Windows 10 Pro with 64-bit Mypaint 1.2.0+git.f62444e.dirty.

By the way I'm so surprised Mypaint uses GTK - normally it looks awful on Windows, but Mypaint looks great!

**Comment by Timmmm** [comment]
Looks like this may be an old issue: http://gna.org/bugs/?18278

**Comment by achadwick** [comment]
@Timmmm
Thanks for the info. I don't doubt it's happening. Clipboards are OS/DE-level things, and the GTK backend has to be customised for it. The exact code executed will be different on all systems. I hope it's fixable.

GTK3 has a much nicer default theme than GTK2 for basically all systems. Before 1.2.x, when MyPaint used the old GTK, our Windows porters had to bundle Windows-ish themes for it or leave it looking horrid. Now that's no longer necessary.

**Comment by cortexer** [comment]
I was able to reproduce this issue (Windows 10 64-Bit, mypaint: latest master head).
I also found a solution, that solves this behaviour.
Please have a look at my PR.

**Comment by achadwick** [comment]
Confirmed in MSYS2 latest on Win7 with 24c7d83a63f8323f506eb20445de5306a46d8ef0.

**Comment by achadwick** [comment]
The fix is good. It's weird that Windows (Gtk)clipboards need their targets polling before a fresh image can be retrieved, but I guess it's fine to do that.

I'm a little nervous about making two asynchronous calls here just for a workaround. There's quite possibly no guarantee they'll be invoked in order. There are synchronous alternatives in Gtk.Clipboard.

**Comment by Timmmm** [comment]
Thanks!

**Comment by achadwick** [comment]
A good one to backport for v1.2.1. There's another clipboard fix we need there too (#603).

**Comment by achadwick** [comment]
Pushed to `v1.2.x` as 6240eceda234143d3edcd2908ab382af4509ffc1 and b2966aaa3d67d595516c1a7adc42de3796842095.
