### ISSUE TITLE
Floating panel window: MyPaint reset floating panel window position at startup.

### ISSUE THREAD

**Issue by dothiko** [mypaint/mypaint#596]
First of all,My system has two monitors,and it is used as a large virtual screen(3840x1200).
Primary monitor is WUXGA, (0,0)〜(1919,1199),in screen coordinate.
Second monitor is FullHD, (1920,0)〜(3839,1079). 
In this situation, Here is how to reproduce the problem:

 1. place floating panel window (ToolStackWindow) at  second monitor.
 2. Close MyPaint. (at this point,~/.mypaint/settings.json has been correctly written the floating window position.I confirmed it by 'cat ~/.mypaint/settings.json' )
 3. Start MyPaint.
 4. MyPaint move the floating window into the center of primary monitor.

I expect MyPaint to place the floating window at second monitor, as I did previous session.

### screenshot with annotation
green rectangle  is primary monitor area, orange rectangle is second monitor area.

#### place the floating window to second monitor (1)
![session_1](https://cloud.githubusercontent.com/assets/14032376/12948555/20a1e488-d046-11e5-8821-9ae356972a98.jpg)

#### when restart mypaint (4)
![session_2](https://cloud.githubusercontent.com/assets/14032376/12948575/3da33212-d046-11e5-9aaf-a6cce40e3ead.jpg)

### my environment
I'm using Ubuntu 14.04.3 (amd64).
Mypaint version is 
MyPaint version 1.2.0+gitexport.f62444e (installed from PPA)
MyPaint version 1.3.0-alpha+git.1ac76bc (cloned from github) 
both have same problem.

### and what I did
And then, I tried investigating MyPaint with debugger,and found a strange line at lib/helpers.py line 74,

```python
    @classmethod
    def new_from_gdk_rectangle(cls, gdk_rect):
        """Creates a new Rect based on a Gdk.Rectangle."""
        return Rect(
            x = gdk_rect.x,
            y = gdk_rect.x,
            w = gdk_rect.width,
            h = gdk_rect.height,
        )
```

the line 'y = gdk_rect.x' seems to be a typo of 'y = gdk_rect.y'...?

I tried changing that line as 'y = gdk_rect.y' ,then mypaint can remember my floating window position as expected, for now.

**Comment by achadwick** [comment]
This is a great report. Thank you for investigating in detail, looks like a cut-and-paste error. Should be an easy fix too.

It could help with the remaining piece of another issue: https://github.com/mypaint/mypaint/issues/550#issuecomment-169943350

**Comment by achadwick** [comment]
This code has been in MyPaint since 8348ceea261005c165d0ec018e715494c663cc19, which was introduced to address typelib omissions like the ones described in #437.

**Comment by achadwick** [comment]
I think this is fixed on master now. Can you pull and re-test please?

It would be a good fix to backport for 1.2.1 if it works OK.

**Comment by dothiko** [comment]
Thanks, @achadwick 
I pulled and re-tested it, and works fine!

**Comment by achadwick** [comment]
Hmm. It seems that autoclose behaviour from a commit message only works on master... :stuck_out_tongue_winking_eye: 

Thanks for confirming the fix.
