### ISSUE TITLE
Error when MyPaint is closed without save document

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#601]
#### Description
When you open MyPaint and after to create a valid document and close the app without save the document, the error appears.
The dialog of error do not working fine, because if you try close the app via "Quit MyPaint", in the terminal I have this message:
```
Traceback (most recent call last):
  File "/home/jag/installs/mypaint-test/gui/gtkexcepthook.py", line 238, in _dialog_response_cb
    if quit_confirmation_func():
  File "/home/jag/installs/mypaint-test/gui/filehandling.py", line 399, in confirm_destructive_action
    save1st_cb.set_margin_start(12)
AttributeError: 'CheckButton' object has no attribute 'set_margin_start'
```
With click on "Ignore Error" button, the app is active, but don't appears in the desktop. The terminal is yet opened.
Perhaps, here is normal, because the app is crashed, but is active as a job, but without the possibility to access it via graphical ui desktop.

My DE is:
Ubuntu Gnome 14.04.2 with GNOME 3.10

#### Steps to reproduce
1. Open MyPaint and create new document,
2. Paint something on canvas,
2. Close the app without save the app.

#### Traceback

```python
Mypaint version: 1.3.0-alpha+git.f31a4be
System information: Linux-3.16.0-60-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/home/jag/installs/mypaint-test/gui/drawwindow.py", line 697, quit_cb(self=<DrawWindow object at 0x7fe3806678c0 (MyPaintDrawWindow at 0x2802a40)>, *junk=(<DrawWindow object at 0x7fe3806678c0 (MyPaintDrawWindow at 0x2802a40)>, <GdkEvent>))
                    "Quit confirm dialog: continue button",
                    u"_Quit",
                ),
  File "/home/jag/installs/mypaint-test/gui/filehandling.py", line 399, confirm_destructive_action(self=<gui.filehandling.FileHandler object>, title=u'Really Quit?', confirm=u'_Quit', offer_save=True)
                save1st_cb.set_margin_bottom(12)
                save1st_cb.set_margin_start(12)
                save1st_cb.set_margin_end(12)
AttributeError: 'CheckButton' object has no attribute 'set_margin_start'
``

**Comment by achadwick** [comment]
Hi - thanks for the report. It's probably explaining what I hope we'll be doing for the next "minor" release...

The `master` branch now requires GTK 3.12, as documented. You should upgrade to Ubuntu 15.04 or later if you want to track new features in development.

The next "minor" release will be 1.3.0, and this is what's being worked on in `master` right now. Requirements are somewhat in flux. At the moment, v1.3.0 might require anything between 3.12 and whatever GTK release will be in the next LTS of Ubuntu (currently Xenial (16.04 LTS) uses GTK 3.18.7 - it is in development, and will release in April).

The `v1.2.x` branch and "patch" releases made from it will continue to support GTK 3.10.

**Comment by loentar** [comment]
I faced with the same issue.. Those who have the same issue and don't want to break anything by installing alpha version of Ubuntu/newer GTK, can fix it with a small patch:

```diff --git a/gui/filehandling.py b/gui/filehandling.py
index 49af93a..8569036 100644
--- a/gui/filehandling.py
+++ b/gui/filehandling.py
@@ -396,8 +396,12 @@ class FileHandler (object):
             save1st_cb.set_vexpand(False)
             save1st_cb.set_margin_top(12)
             save1st_cb.set_margin_bottom(12)
-            save1st_cb.set_margin_start(12)
-            save1st_cb.set_margin_end(12)
+            try:
+                save1st_cb.set_margin_start(12)
+                save1st_cb.set_margin_end(12)
+            except AttributeError:
+                save1st_cb.set_margin_left(12)
+                save1st_cb.set_margin_right(12)
             save1st_cb.set_can_focus(False)  # set back again in show handler
             d.connect(
                 "show",
```
