### ISSUE TITLE
Behavior change in soft-dip-pen brush between 1.1 and 1.2

### ISSUE THREAD

**Issue by darkstalker** [mypaint/mypaint#602]
I recently upgraded to 1.2 and noticed a small change in the deevad/soft-dip-pen brush. When doing a low pressure thin line, it ends being blurred up instead of drawing a thin line. Attached files to show what i mean:

on 1.1:
![lines_soft-dip-pen_11](https://cloud.githubusercontent.com/assets/356503/13067411/807b71a6-d44e-11e5-8445-f89b74e0fac2.png)

on 1.2:
![lines_soft-dip-pen_12](https://cloud.githubusercontent.com/assets/356503/13067414/87cf1d04-d44e-11e5-89e4-b15e959c28a1.png)

Maybe i'm nitpicking, but it's weird that you can't do thin lines with that tool anymore. Probably some extra antialiasing added?

**Comment by 0ion9** [comment]
I guess you want to modify it to reduce "pixel feather" parameter, perhaps to 0.

**Comment by achadwick** [comment]
@darkstalker Is this no longer a problem? Should this brush be changed?

**Comment by darkstalker** [comment]
I fixed it myself by changing the pixel feather as suggested.
