### ISSUE TITLE
Set up a useful ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#606]
Issue reporters frequently have to be asked to supply basic information about new issues. we already use a `CONTRIBUTING.md` that refers people to the [bug reporting guide](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs) and the [Contributing pages](https://github.com/mypaint/mypaint/wiki/Contributing) on the wiki, but this information is hidden away behind links that not many people click.

**[Github have recently added support for templates for new issues](https://github.com/blog/2111-issue-and-pull-request-templates)**. This is just a bit of Markdown, meaning that reporters could be given some [task list checkboxes](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments). If we do that, what ought to go there?

@yourfirstpr and @Charlotteis [remind us](https://twitter.com/yourfirstpr/status/700303824892768257) that the template's job is to make the project more accessible. What can we do there to improve our workflow? There seem to be two main jobs here:
- Leading new reporters through the process of reporting an issue
  - This is a crowd with few coding skills, but deep knowledge in other areas and a very clear idea of what they want, or when something's wrong. MyPaint's userbase is artists, not coders. It's HIGHLY international, meaning that language can be a barrier when reporting.
  - Gathering the information has the checkbox nature, and we really need that reproducibility info for the next stage
  - Basic bug report/triage checkboxes: "I have searched for duplicates", "I've tried this with a fresh config", "I verified that this affects the latest stable version / the latest master HEAD", "I've written up what version this affects / what OS I'm using".
- Providing information to people with (some of) the skills required to fix the bug, and helping them grow their skills
  - These folk will be more technical, a mix of triagers and coders. Sometimes the occasional icon artist or documenter.
  - A canned workflow for us would be an improvement over our current rather lax approach. For starters:
    - Checkbox: someone has managed to reproduce this issue enough for it to be fixed
    - Checkbox: task-is-assigned
    - Checkbox: forked and cloned and branched
    - Checkbox: PR submitted.

The great thing about this is that it puts relevant information in the user's eyeline.

MyPaint already does something a little like this from the exception dialog: we offer a button for searching the tracker, and have a translated template in there on the Submit button that becomes unlocked after a search is started. We HAVE had a couple of reports with just the exception and an uncustomized template, however - perhaps due to the aforementioned language issues.

Perhaps an obvious checkbox-based reporting nature may help with this?

One thing is obvious: we shouldn't let the structure constrain us too much if we do this. Best make it clear that contributors can and should remove tasks which don't make sense.

One stumbling block: who has permissions to edit those checklists or the original post? That may make the ticky-box idea unworkable for the details.

**Comment by achadwick** [comment]
Alternative/less officious approach: **[just the headings](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)**, per the feature documentation.

**Comment by odysseywestra** [comment]
Having a Checklist or a set of instructions for reporting bugs would be a great help. Half of the time, it's spending trying to get the information that is needed before we could help them. With this template system, it could make managing bug reports a bit easier. 

I think we could start out with this template:
```md
MyPaint Version : 

Operating System: 

Description of Bug:

Steps to Reproduce:

Link to 15-30 video illustrating the issue(optional):

For more information about submitting a bug report on our Issue tracker please visit:
https://github.com/mypaint/mypaint/wiki/Reporting-Bugs
```

I know it needs a bit of refining, but it's a start.

**Comment by Charlotteis** [comment]
:wave: :smile: Happy to see this!

**Comment by odysseywestra** [comment]
Also another thing in mind, if it's a feature request they are posting we should point them to the [community forums](http://community.mypaint.org) so it can have further discussion on why and how to implement what they are requesting request.

**Comment by odysseywestra** [comment]
I've also created a [thread](http://community.mypaint.org/t/implement-issue-and-pull-request-templates-for-our-github-repo/211) over on our Community Forums to get some feedback from there as well.

**Comment by achadwick-test** [comment]
Apologies for any noise on this issues. @achadwick here in disguise :tophat: I'm testing to see what temporary collaborators with various levels of access can see and do within issues.

One annoyance is that people with Read access cannot tick checklists in other users' comments, so...

- [ ] Are _user_ ticky-boxes reflected in the completion percentage?

**Comment by achadwick** [comment]
Checklistifying this workflow for the sake of a completion bar isn't practical. It would still be good to assign [outside collaborator](https://help.github.com/articles/repository-permission-levels-for-an-organization/#outside-collaborators) status to people when they ask to be assigned, and make that part of our workflow. Nice and friendly, and it becomes part of their history.

(One project annoyance. Our old read-write team of non-admin devs, `@mypaint/collaborators`, has a really unhelpful name for Github's new permissions model. Let's discuss that over in #615 though)

**Comment by achadwick** [comment]
I've added a first draft, trying for sections and a form-ish look. Hopefully people will be able to figure it out, and hopefully it won't get in the way.

Can people quickly test it out and make sure that the Unicode looks OK?

**Comment by odysseywestra** [comment]
Looks good so far. I would add that if they are unsure it's a bug or need reporting help, to go to the community forums first. We can always link the  For example:

```
[☞ Use our Community Forum for general support questions, or if you need help reporting the bug first: https://community.mypaint.org/c/support.]
```

**Comment by odysseywestra** [comment]
I've push those changes I mentioned above to master. I also wanted to test out editing files directly on Github's website as well. Works well for the most part.

**Comment by zb13y** [comment]
Basic system detailes - add tablets (Model, drivers, and some information like this - 'include your tablet brand and model name/number when reporting a problem with input handling' and maybe advice firstly to try update driver.)

**Comment by achadwick** [comment]
@zb13y
A good page in the wiki telling people how to diagnose tablet issues would help take some of the burden off us as well. I think that's worth it's own issue: #674.

There's a lot of steps to merely diagnosing a tablet issue. Fixing a tablet issue is an even harder problem :tired_face:

**Comment by odysseywestra** [comment]
I'm going to close this since we have a good topic template set up now. If anyones wants to make a change, either open up a new issue ticket or open a pull request with your changes.
