### ISSUE TITLE
Resizing Docks in Window Mode is a Pain

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#61]
As I've been working on MyPaint, one thing that has really grind my gears is how hard it is to resize the windows with the mouse and the fact that when I resize the widgets, the Window will not resize with it.

Is there a way in which when we resize the widgets when they are windowed to stick to the window itself so it can dynamically resize as widget resized? With two or more stack, I would assume the bottom one in the stack would be the one to resize the whole widget.

![example](https://cloud.githubusercontent.com/assets/1840562/3648299/e2c29738-1107-11e4-9e62-51175104d860.png)

**Comment by achadwick** [comment]
**Triage note:** no updates, closing.
