### ISSUE TITLE
Menu: Unnecessary Entries

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#613]
Do we really need to have `current tools` in the edit menu? The reason I'm asking is because it creates unnecessary duplication of menu entries which are available in other menus sections.

![screenshot from 2016-03-02 20-42-09](https://cloud.githubusercontent.com/assets/1840562/13484967/b6596330-e0b7-11e5-9e5f-00d16ed567ed.png)

MyPaint Version: 1.3.0-alpha+git.b7e59eb
Linux Distribution: Ubuntu Gnome 15.10 w/ Gnome 3.16

**Comment by achadwick** [comment]
We could easily drop the radio actions from the menus, and it's a simple job for a new starter. I'll write up what they'd need to do above.

------------------------------------

The only reason this submenu exists is from the old days when everything had to be in the menu to allow accelerator keys to be changed - you'd point at the menu entry and press the new key combo. GTK doesn't allow that any more, so we have the accelerator editor in prefs as a replacement.

MyPaint tool/mode actions have two ways they can be activated:

* There is a single group of radio actions, one per tool/mode
  - That's what you see in _Edit → Current Tool → *_, and the radio-ness is why you see the orange dot above.
  - They also appear on the toolbar, and give the nice pressed-in appearance while they're active
  - If these were to be given keys, pressing the key a second time would have no effect
* There's an associated set of toggling actions, one per radio action
  - These are simple actions, meaning you can activate them at any time
  - These are the one with the key bindings by default
  - They're scattered all over the menus for historical reasons.
  - Pressing their key a second time deactivates the radio action and goes back to what you were doing before (or freehand). It's more convenient, and has some smarts built in.

Removing the Current Tool submenu won't affect these interactions.

**Comment by achadwick** [comment]
### Good new starter task

This is a fairly simple change that will make the UI a bit less complex for our users. It would be easy for one of us to do the job, but I'd like to give a first-timer the opportunity to learn, if possible. -- @achadwick

### What needs to be done

- Get yourself a Github account.
  - Check out the suggested [hello-world tutorial](https://guides.github.com/activities/hello-world/) too. It's good stuff.
  - Read up on the [branching model](https://guides.github.com/introduction/flow/) too.
- _Add a comment_ below saying that you want to work on this.
  - One of us will assign it to you
- _Fork_ the main MyPaint repository into _your personal area_ on Github.
  - This is a copy that you work on, with full control over it.
- _Clone_ your forked repository to your computer
  - `git clone git@github.com:YOURNAME/mypaint.git`
- _Branch_ your clone, just for this job
  - `git checkout -b issue613-remove-submenu`
- Edit `gui/menu.xml`, and remove the submenu named `CurrentModeMenu`
  - Test MyPaint can still run from within your clone
  - _Add_ your changes (use `git add gui/menu.xml` for this)
  - _Commit_ what you added with `git commit`. [Here's how to write the commit message](https://github.com/mypaint/mypaint/wiki/Contributing-Patches#commit-messages).
- _Push_ your branch back to your area in Github
  - This publishes your changes so we can see them.
- Send a _Pull Request_ to us, from your branch to our `master` branch
  - You can refer to this issue in the PR's description or its comments as `mypaint/mypaint#613`.

You can ask us to help at any stage. There are no silly questions, and we all remember having to learn this stuff.

There are some really detailed video guides to this process on <http://makeapullrequest.com/>, and MyPaint has a growing text-based [Contributing guide](https://github.com/mypaint/mypaint/wiki/Contributing) in English on its wiki.

**Comment by caseywilliams** [comment]
Hi, I'd like to start working on MyPaint - can I try this one?

**Comment by odysseywestra** [comment]
Sure go right on ahead. If you have any questions on how to accomplish this, feel free to ask them in our Developers Area category in our [community forums](http://community.mypaint.org).

**Comment by achadwick** [comment]
@caseywilliams 
Sure, I've assigned you to the issue. Our README is probably the best place to start if this is your first time working with MyPaint: <https://github.com/mypaint/mypaint/blob/master/README.md>

(Contrary to what Github might have told you by email, your access to the main repository is read-only right now. Sorry about that. There doesn't seem to be a way we can set default access levels for outside collaborators, and it seems we  need to use the outside collaborators system to assign people. I'm still learning myself, evidently! :blush:)

**Comment by caseywilliams** [comment]
Thanks both - I just realized there's a reference to this menu under [gui/resources.xml](https://github.com/mypaint/mypaint/blob/master/gui/resources.xml#L838) - should I get rid of it there as well?

**Comment by achadwick** [comment]
@caseywilliams 
Good spot, I forgot we had that!

Yes, the surrounding `<child> … </child>` element will need to be removed from `gui/resources.xml`. You can make another commit on your branch with that removal, then push it to update the PR.

**Comment by caseywilliams** [comment]
@achadwick ok, pushed, thanks! Let me know if there's any rebasing or commit message style changes I can make, of course.

**Comment by achadwick** [comment]
@caseywilliams Nothing needed changing, and everything looks great. Thanks for the contribution!
