### ISSUE TITLE
Team structure review

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#615]
I'm reviewing permissions and teams for MyPaint at the moment, and our current team structure has a couple of poor fits right now:

### Rename or split @mypaint/collaborators

Our current read-write team of non-admin devs, @mypaint/collaborators, has a really unhelpful name for Github's new permissions model. The new model allows us to assign any github account which isn't a member of a team an [outside collaborator](https://help.github.com/articles/repository-permission-levels-for-an-organization/#outside-collaborators) status which allows them to get stuff done. Admins like me can give an outside collaborator Read, Write, or even Admin hats.
   - This appears to be the only way to assign an issue to a contributor.
   - Newbs would start off with RO collaborator status when they want to be assigned.
   - I want to ease onboarding and make new contributors feel welcome, so assigning them and naming them officially as collabs is nice.
   - My main issue is the name clash.

### Do we need finer-grained teams?

MyPaint is growing, and projects will be splitting for GIMP/Krita/whatevers' benefit. I don't think it makes much sense to have a single non-core read-write team for all purposes (libmypaint, porting, resource packages, website, ..., community forums, CoC reporting accountability). @mypaint/collaborators and @mypaint/core : how do you see the structures changing (I know @odysseywestra is keen to be community lead)?
   - _Having_ teams is nice for accountability purposes, and saying who we are. It's not all about repository access these days. This does imply being a public member, which not everyone is...
   - Core devs should probably stay as @martinxyz, @jonnor and @achadwick. Assuming it needs a team at all - it was basically "converted from an old admin team". We all have "owner" hats over all of <https://github.com/mypaint>, I think.
   - Separate teams with responsibilities for various areas, maybe?
   - Each team would be allocated a [team maintainer](https://help.github.com/articles/repository-permission-levels-for-an-organization/#team-maintainers).

**Comment by achadwick** [comment]
If we split `Collaborators`, how about:

* `Coders`
   - Basically everyone in the existing `Collaborators` team, plus all of `Core`
   - RW access to repos: `mypaint`, `libmypaint`
   - anyone outside core want to be a team maintainer?
* `Community`
   - RW access to repos: `mypaint.github.io` and anything needed for <http://community.mypaint.org> needs.
   - @odysseywestra as team maintainer
* `Porters`
  - RW access to repos: `debian` and any new ones we make for similar purposes
  - @tumagonx and me

Too much? Too little?

**Comment by odysseywestra** [comment]
It looks good to me so far. We maybe could add a Translators group, but that maybe too much. However it may help in the future by giving the main developers one less thing to worry about. Plus it could a good place for new translators to contact a person who has translated using weblate as well.

**Comment by odysseywestra** [comment]
@achadwick any progress on this? I'm fine with structure you have set up so far. We just need to find a team maintainer for the `Coders` Team.

**Comment by odysseywestra** [comment]
@ShadowKyogre would you be willing to be added the `Porters` team since you maintain the AUR Repository for MyPaint? We could add your PKGBUILD scripts as a separate repository. That way you don't have to be the sole person that has to maintain them in case you want to move on.

**Comment by achadwick** [comment]
Okay, I've split up @mypaint/collaborators and hidden it. It's been converted to RO too, but its members will now find themselves in one or more of:

* @mypaint/community Write access to mypaint.github.io.
* @mypaint/packagers Write access to mypaint.deb and libmypaint.deb right now, but we can add more repos for Windows/Arch/Fedora use. Just ask!
* @mypaint/developers Write access to libmypaint and mypaint.

I've invited a couple of keen repeat patch submitters to @mypaint/developers too.

Think that's it for now.

**Comment by achadwick** [comment]
One more thing though: @mypaint/community, @mypaint/packagers, @mypaint/developers: can you please all set your membership visibility to public please? Not a requirement.

Okay, two more things. Everyone in @mypaint/core should really set up 2fa if they haven't already, and we should probably treat public membership as a requirement for that team. That's because it's synonymous with "project owner". The core team is really only an `@`-mentionable list of all the project owners for the purposes of accountability. It doesn't convey any extra powers.

**Comment by Jehan** [comment]
Hi Andrew,

On Mon, May 30, 2016 at 8:02 PM, Andrew Chadwick <notifications@github.com>
wrote:

> One more thing though: @mypaint/community
> <https://github.com/orgs/mypaint/teams/community>, @mypaint/packagers
> <https://github.com/orgs/mypaint/teams/packagers>, @mypaint/developers
> <https://github.com/orgs/mypaint/teams/developers>: can you please all
> set your membership visibility to public please? Not a requirement.
>

How do you do these things you are saying? I don't mind having a public
membership or whatever you prefer. Most things I do are quite public
anyway. But where do you set this?

I'd like to have as little interaction with github and not spend my days
trying to figure out how things work there, on their web UI. :P

Jehan

Okay, two more things. Everyone in @mypaint/core
> <https://github.com/orgs/mypaint/teams/core> should really set up 2fa if
> they haven't already, and we should probably treat public membership as a
> requirement for that team. That's because it's synonymous with "project
> owner". The core team is really only an @-mentionable list of all the
> project owners for the purposes of accountability. It doesn't convey any
> extra powers.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mypaint/mypaint/issues/615#issuecomment-222535284>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAwhdX3e2kNwT51Ij7QosV6pdU0MK2UPks5qGyYrgaJpZM4Hoj1u>
> .
>



-- 
ZeMarmot open animation film
http://film.zemarmot.net
Patreon: https://patreon.com/zemarmot
Tipeee: https://www.tipeee.com/zemarmot

**Comment by Jehan** [comment]
Hi,

Forget the last email. Found it.

Jehan

On Mon, May 30, 2016 at 8:06 PM, Jehan Pagès <jehan.marmottard@gmail.com>
wrote:

> Hi Andrew,
>
> On Mon, May 30, 2016 at 8:02 PM, Andrew Chadwick <notifications@github.com
> > wrote:
>
>> One more thing though: @mypaint/community
>> <https://github.com/orgs/mypaint/teams/community>, @mypaint/packagers
>> <https://github.com/orgs/mypaint/teams/packagers>, @mypaint/developers
>> <https://github.com/orgs/mypaint/teams/developers>: can you please all
>> set your membership visibility to public please? Not a requirement.
>>
>
> How do you do these things you are saying? I don't mind having a public
> membership or whatever you prefer. Most things I do are quite public
> anyway. But where do you set this?
>
> I'd like to have as little interaction with github and not spend my days
> trying to figure out how things work there, on their web UI. :P
>
> Jehan
>
> Okay, two more things. Everyone in @mypaint/core
>> <https://github.com/orgs/mypaint/teams/core> should really set up 2fa if
>> they haven't already, and we should probably treat public membership as a
>> requirement for that team. That's because it's synonymous with "project
>> owner". The core team is really only an @-mentionable list of all the
>> project owners for the purposes of accountability. It doesn't convey any
>> extra powers.
>>
>> —
>> You are receiving this because you are on a team that was mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/mypaint/mypaint/issues/615#issuecomment-222535284>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAwhdX3e2kNwT51Ij7QosV6pdU0MK2UPks5qGyYrgaJpZM4Hoj1u>
>> .
>>
>
>
>
> --
> ZeMarmot open animation film
> http://film.zemarmot.net
> Patreon: https://patreon.com/zemarmot
> Tipeee: https://www.tipeee.com/zemarmot
>



-- 
ZeMarmot open animation film
http://film.zemarmot.net
Patreon: https://patreon.com/zemarmot
Tipeee: https://www.tipeee.com/zemarmot

**Comment by odysseywestra** [comment]
Do you want us to leave the collaborators group then?

**Comment by achadwick** [comment]
@Jehan OK :smile: 

@odysseywestra Up to you. It's an old grouping, so I could just leave it around. The only reason to though is so that existing `@`-mentions don't break.

**Comment by ShadowKyogre** [comment]
@odysseywestra : Oh man, the notification email got buried with the rest of the notifications! Anyway, yes, I'd like to be part of the porters group.

**Comment by achadwick** [comment]
@ShadowKyogre Sorry for the slow reply. Invite sent!

**Comment by ShadowKyogre** [comment]
@achadwick: Got the invite! Now I just need to push the copy on the AUR into a repo here dedicated to that.

**Comment by ShadowKyogre** [comment]
@achadwick I think I still need a repo created in the mypaint organization to put the PKGBUILD in ^^;.

**Comment by achadwick** [comment]
@ShadowKyogre 
How do you want to organize/name it? We seem to be standardizing on `libmypaint.SOMETHING` and `mypaint.SOMETHING` for build stuff, e.g. [libmypaint.deb](https://github.com/mypaint/libmypaint.deb) for our debianization. 

Is it just going to be a folder with a PKGBUILD file and possible patches for AUR only? Then what about

* "For AUR only" → libmypaint.aur, mypaint.aur
* "It's the canonical PKGBUILD" → libmypaint.pkgbuild, mypaint.pkgbuild
* "It's the canonical PKGBUILD, but only for Arch systems" → libmypaint.arch, mypaint.arch

Or are you wanting something more more all-in-one, like the MyPaint PKGBUILDs for MSYS2 over in [MINGW-packages](https://github.com/Alexpux/MINGW-packages)? There they're building a whole darn platform, one folder per PKGBUILD.

Let me know what you want it to be called, and what form it's going to take. These things are all going to work a little differently, so we should be flexible with naming and organization.

**Comment by ShadowKyogre** [comment]
For contribution purposes, I think the suffixes suggested would work best.

Especially for the canonical PKGBUILD but only for arch case. The PKGBUILDs that aren't mypaint-git (as in the repo'd ones and libmypaint-git) are maintained by different people, so it'd account for that best.

**Comment by achadwick** [comment]
@ShadowKyogre 
Sorry to have not replied earlier.

Would you be OK with a single project-specific repo? Arch isn't constrained in the same way as the crunky old Debian build system, where you have to put a `debian/` subfolder *into* your dist tree. That's why the `.deb` repos are a pair ☺

For Arch and Arch-like build stuff, you don't have to do that. You could use one repo per system if it suits you. What about a structure like:

     pkgbuilds-arch-aur/      <--- repository clone, name TBD but should name system
       +-- libmypaint/
       |     `-- PKGBUILD
       `-- mypaint/
             `-- PKGBUILD

By far the best way of telling me what you want is to do it in your own Github working area and telling me to merge :smile:

**Comment by achadwick** [comment]
(I'll lock this conversation once @ShadowKyogre and myself have finalized the name of the new repo(s). Sorry for the noise, everyone.)

**Comment by ShadowKyogre** [comment]
@achadwick: One repo per system sounds good. Per-system PKGBUILDs are usually interlinked anyway.

As for the repo name, I was thinking of something like this: https://github.com/ShadowKyogre/mypaint.pbd.aur

(( ^note: I have no idea how we'd pull this since we don't have the repos set up yet ))

The gitignore is added there for easy updates to a build folder.

The `pbd` stands for PKGBUILD (it'd be a little unwieldy to type that every time for a subsystem) and `aur` for AUR. Similarly, the ones for Arch would be under a repo named `mypaint.pbd.arch`, and official ones under `mypaint.pbd`. So generally, `mypaint.<pkgtype>.<bulidsys>` should be the format we stick with when making packaging repos. This also keeps it consistent with the debian packaging repos.

----

That being said, importing history with subtree is kind weird to work with. I wanted to import these into the repo from the AUR with complete history without using a submodule since that wouldn't place the files directly in the repo.

For example,
~~~~
git log $(git subtree split --prefix=mypaint-git)
~~~~
Would show you the complete history of the mypaint-git package.

And:
~~~~
# mark the subtree history with a temporary branch
git subtree split --prefix=lib -b split
# this is to upload the PKGBUILD to the AUR
git push ssh://aur@aur.archlinux.org/mypaint-git.git split:master
# last is optional for cleanup
git branch -D split
~~~~

**Comment by ShadowKyogre** [comment]
Before I forget, this is how Arch upstream packaging stores PKGBUILDs: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/mypaint  (a branch per package)
