### ISSUE TITLE
Establish Default Keyboard Shortcuts

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#622]
One thing that we probably need to do is establish default keyboard shortcuts to help ease the use of MyPaint. 

I have created a [spreadsheet listing all of the available keyboard shortcuts from the Preferences Window in MyPaint](https://drive.google.com/open?id=1g0BkDEK1BLSgoWdPOs9NEPTrKbf2f1NEUyrytpwGBnw). It is uploaded up to on my Google Drive account and is shared to the Public via a link. This will allow the MyPaint Community to comment on the document to what shortcuts we should establish as default. The Community could also comment the Description wording as well to make them less confusing if they are right now.

I did mark the ones that do not need to be changed or do not need a shortcut in green such as the Developers options or file management shortcuts for example. The one thing I do need to know is is which keyboard shortcuts to avoid using and not conflict with the Window Manager or Desktop Environment. I can also give you @achadwick or anyone who is willing to help edit status on the document if that will help. 

My Proposal is from now until the end of the month have this document open for comment so we can make the changes. After which I can make the edit to the `/gui/rsources.xml` file so that way it can be available in the next version of MyPaint. Are there any other files that need to be edited as well?

Also I can take this document and create a keyboard mapping vector image that we can host on our wiki documentation for those who need know which keys do what.

**Comment by achadwick** [comment]
@odysseywestra
Definitely worth doing this. I don't have a huge amount of time to spend on it, but it seems like something that's worth throwing open to the wider community. Should I assign you?

A good goal would be for our keyboard mapping to be compatible with GIMP/Krita/Inkscape in a way that doesn't break experienced MyPaint users' expectations.

There is also a default hardwired/secondary keymap to be aware of. It's set up with an internal API call in a couple of places:

* [gui/document.py#L461](https://github.com/mypaint/mypaint/blob/ff04196abe80a769b9cecf0ef80d3072b767bb8c/gui/document.py#L461)
* [gui/drawwindow.py#L184](https://github.com/mypaint/mypaint/blob/ff04196abe80a769b9cecf0ef80d3072b767bb8c/gui/drawwindow.py#L184)

These aren't (and shouldn't be) editable by the user, but that should work with the new defaults we choose.

**Comment by odysseywestra** [comment]
I will be willing to get the ball rolling on this. Just keep in mind, I will probably pick your mind when I apply them to `/gui/resource.gui`

Thanks, I will be aware of those so we don't override them by accident.

I writing the post on the community forms to inform of this. I'll post the link on this issue thread when it is finished.

**Comment by odysseywestra** [comment]
Okay here is the post link:
http://community.mypaint.org/t/deciding-what-our-default-keyboard-shortcuts/246

**Comment by odysseywestra** [comment]
I'm moving this issue to the community forums to help clean up the issue tracker and keep it focused on bugs.
