### ISSUE TITLE
Make Keyboard Mapping Easier to Manage and Navigate

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#623]
Currently using the Keyboard Mapping tool in the preference window is not easy to navigate or to manage. Even though having everything in alphabetical order and searchable is a good start, yet it still feels overwhelming. 

My Proposal is to adapt the layout to that of Gnome Shell's built-in keybaord shortcut editor. It organizes the keyboard shortcuts into specific categories. ![example_01](https://cloud.githubusercontent.com/assets/1840562/13763139/335605bc-ea01-11e5-99e7-f5d48a0101b5.png)

We could categorize our shortcuts by where they are in the main menus. That should make navigation easier. Here is a mockup of what I am proposing:

![mockup_02](https://cloud.githubusercontent.com/assets/1840562/13763758/f0a1b608-ea05-11e5-9fcc-6e9955ee2bec.png)

So what needs to be done to make this possible?

**Comment by achadwick** [comment]
I don't want to do too much with the old GtkAction interface before we move to GtkApplication /GAction/GMenuModel. This is something that will already need a huge rewrite.

GActions don't know where they live in their menu, though you could interrogate the GMenuModel structure to find out.

For me, a better interface to searching is the way forward here.

**Comment by odysseywestra** [comment]
Yeah I understand your thinking on this. I didn't know it was using the old GtkAction interface so yeah I can understand your hesitation on this since it would require a rewrite. I really wish I could write python/GTK right now.

To me it just feels disorganized as it now stands from a UI perspective. If we could organize the GActions via GMenuModel that would at least make the order bearable to scroll through at least. Having this and a better search interface would be a great to improve this.

Here's my mockup of this:
![mockup_03](https://cloud.githubusercontent.com/assets/1840562/13791633/50bd84b8-eaab-11e5-9262-80b190394850.png)

**Comment by odysseywestra** [comment]
Closing issue and continuing conversation on the [Community Forums](http://community.mypaint.org/t/make-keyboard-mapping-easier-to-manage-and-navigate/292). I'm doing this to help our github issue tracker focused on bugs.
