### ISSUE TITLE
Add keyboard Shortcuts to Dock a Panel

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#624]
Currently the only way to dock a panel is to drag and drop the panel to either side of MyPaint. We should have also have a keyboard shortcut to also achieve the same goal. Here are the two proposed shortcuts:

Action | Description | Key Combination
------------ | ------------- | -------------
Dock Panel to the Left | Toggles panel to dock to the left side of MyPaint's interface, or to window mode. |
Dock Panel to the Right | Toggles panel to dock to the right side of MyPaint's interface, or to window mode |

I can leave what key combination to the community, but I think these will be two useful actions to use for managing MyPaint UI.

I have them also listed in the spreadsheet I spoke about in #622  under proposed shortcuts to see if what shortcuts we should assign as default by the community.

**Comment by achadwick** [comment]
This needs to be addressed with buttons in the UI too: see also #139.

Suggest wording like "Moves panel to..." for clarity. BTW, "left" and "right" refer to UI layout flow, which actually flips for a R2L layout! But that's OK provided we mention it in the context for our translators ☺

**Comment by odysseywestra** [comment]
I've also mention in #139 that if we take a page out of Krita way of docking panels, we technically only need one shortcut to assign to Dock or Undock them.

**Comment by odysseywestra** [comment]
I'm closing this issue to continue the conversation on our [Community Forums](http://community.mypaint.org/t/add-keyboard-shortcuts-to-dock-a-panel/294) to help our issue tracker focus on bugs.
