### ISSUE TITLE
Add Keyboard Shortcuts for Inking Tool Options

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#625]
Along with adding the suggested keyboard shortcuts in #623, we should also add keyboard shortcuts for inking tool as well.

Action | Description | Key Combination
------------ | ------------- | -------------
Insert Point | Insert point in the direction of the path for the Inking Tool | 
Delete Point | Delete currently selected point for the Inking Tool |
Simplify Points | Simplify the curve using the Ruemann-Witkam algorithm | 
Cull Points | Cull every other point from the curve | 

These are also added to the spreadsheet in #622 as well under proposed shortcuts.

**Comment by achadwick** [comment]
Closing in favour of #622. These can already have keyboard shortcuts added to them in `gui/resources.xml`, so this can be worked on at the same time in there. The action names are `InsertCurrentNode`, `DeleteCurrentNode`, `SimplifyNodes` and `CullNodes` :smile:

**Comment by odysseywestra** [comment]
Thanks for pointing that out. One less issue to worry about then. Great!
