### ISSUE TITLE
MyPaint for Windows: no console debug version

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#628]
There is no `(console debug)` version available for MyPaint w64 v1.2.0. This makes startup issues like #627 impossible to usefully debug. The `(console debug)` version is installed by the preceding betas, but it is not installed by our official v1.2.0 release.

Affects: Windows 7 (and probably later) at version 1.2.0+git.f62444e.dirty.

@tumagonx Can this be reintroduced for 1.2.1?

**Comment by tumagonx** [comment]
Yes no problem. When 1.2.1 ready I will add console version.

On 3/22/16, Andrew Chadwick <notifications@github.com> wrote:
> There is no `(console debug)` version available for MyPaint w64 v1.2.0. This
> makes startup issues like #627 impossible to usefully debug. The `(console
> debug)` version is installed by the preceding betas, but it is not installed
> by our official v1.2.0 release.
>
> Affects: Windows 7 (and probably later) at version 1.2.0+git.f62444e.dirty.
>
> @tumagonx Can this be reintroduced for 1.2.1?
>
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mypaint/mypaint/issues/628


-- 
!tuma

**Comment by achadwick** [comment]
I think on reflection that v1.2.1 should contain a good, recent version of GTK3. Since the GTK project now has a stable gtk-3-22 (and their master branch is working towards 4.x!). It's been pretty well tested in MSYS2-land, where builds are on hiatus right now, so I think we should consider the version we have available to be reasonably stable.

I will need to do some custom builds of some of mypaint's dependencies. In particular, I want the tablet patches I sent upstream for gtk 3.22.5 to be available to Windows MyPaint users. Versions before that can be _expected_ to not have pressure with up to 50% of tablets on the market due to a silly list iteration bug that I fixed. I fixed tilt on tablets that support it too, and also a regression of the crash during wintab setup. So mypaint 1.2.1 should use gtk 3.22.5 or later, as that's probably the gtk with the best tablet support from recent months.

I've also been working on a generic installer-making tool (achadwick/styrene) that will allow a lot to be automated, but I think we ought only to use that for future builds from master at a point when MSYS2 builds come off hiatus (I reserve the right to develop a better feeling about using styrene before mypaint 1.2.1 is released, and use it for the release).

Either the existing Windows builds scripting in windows or any Styrene build I make will install a `console debug` launcher

**Comment by achadwick** [comment]
MSYS2 is back with a vengeance, and I'm feeling more confident about Styrene as a bundler for our sort of work now. My current test config makes a pretty reasonable build: I've made the console debug launcher use gdb for lib identification in the case of a crash, and I've thrown in a gtk3-demo launcher for tablet testing. Looking good so far.

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now out, and contains a gdb wrapper for reporters to be directed to.
