### ISSUE TITLE
MyPaint Mac OS version cannot start

### ISSUE THREAD

**Issue by Kusine** [mypaint/mypaint#630]
I have just installed MyPaint for Mac OS but the application will not open.

I tried checking the following suggested link but it appears that the link seems to be broken:
http://forum.intilinux.com/mypaint-development-and-suggestions/mac-osx-port/msg9214/#msg9214

- MyPaint version 1.2.0.
- No error message appears.
- I have only tried to repeatedly open the application (without success).
- Steps:
1/ Install MyPaint application to Mac.
2/ MyPaint application is successfully installed in my Applications folder.
3/ Click the MyPaint application, it begins to bounce in the dock but the program does not open.
4/ After a couple of bounces MyPaint eventually closes and the application icon disappears from the dock.

I am running Mac OS 10.11.4 on an iMac.

Thank you for your help with this issue.

**Comment by achadwick** [comment]
That link is outdated. Can you let us know where you found it so that I can go and fix it?

Is this MacPorts? Paging @ryandesign...

@Kusine note that problems with MacPorts ports need to be reported in the MacPorts bug tracker: here's how: https://guide.macports.org/#project.tickets

**Comment by Kusine** [comment]
@achadwick thank you for your prompt reply. I obtained the broken link from the following:

https://github.com/mypaint/mypaint/wiki/FAQ-Mac-OS-X

Yes, MyPaint was installed via MacPorts. I will follow your advice and report the issue in the MacPorts bug tracker. I hope there is a solution. Thank you Andrew for your help.

**Comment by achadwick** [comment]
https://github.com/mypaint/mypaint/wiki/FAQ-Mac-OS-X updated, along with the README. Thanks for the pointer, and best of luck getting it fixed.

(Of course, we'll deal with any actual faults in MyPaint itself here in case our docs are missing a dependency or we're misunderstanding something about OSX or something - just let us know :smile:)

**Comment by Kusine** [comment]
Thank you for your reply and I hope that the issue will be resolved via MacPorts -- I can't wait to try MyPaint!
