### ISSUE TITLE
[HiDPI] Rectangular glitches while drawing

### ISSUE THREAD

**Issue by TuringMachinegun** [mypaint/mypaint#631]
Hi,

I'm running MyPaint on Linux Mint 17.3 (64 bit), and I'm observing rectangular glitches as I draw (screenshot attached)
![squares](https://cloud.githubusercontent.com/assets/8633845/14144145/ddd37ed6-f68e-11e5-9f20-e3f07cfcc8b2.png)

My configuration is maybe non-standard, as I run Linux on a Surface Pro 3.
The glitches appear whether I use the mouse, touch, or pen input. 
I tried both the master and the v1.2.x branches, in case it was a GTK version issue (I understand that the v1.2.x branch supports GTK>= 3.10 and I've got 3.10.8). I also tried the version in the ppa:achadwick/mypaint-testing repository.

The command line output reads:

```
(mypaint:7380): Gtk-CRITICAL **: _gtk_tree_view_column_autosize: assertion 'GTK_IS_TREE_VIEW (tree_view)' failed
(mypaint:7380): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
```

and several 

```
WARNING: gui.freehand: Final evhack event (1124.28, 605.90, 3784305) doesn't match its corresponding motion-notify-event (562.14, 302.95, 3784305). This can be ignored if it's just a one-off occurrence.
```

which shouldn't have anything to do with it (if I move the cursor slowly enough, this warning doesn't appear, but the glitches do)

Mypaint 1.1 works fine though. Any ideas why this might be happening?

**Comment by achadwick** [comment]
That's a very odd one! You're seeing the outlines of the limited redraw rectangles MyPaint uses to keep everything responsive. Sort of shifted down by ~0.5px and right between ~0.5 and ~2px.

* Do the glitches still happen in fullscreen mode (F11, let the sidebars etc. auto-hide 1st)
* Do the glitches disappear when you zoom/pan/rotate/mirror the canvas?
* Are you running HiDPI at all?

I assume it's display-side, but please can you try saving and verify with another program that the glitches are not present in the saved output? :smile: 

Evhack is evil, and the need for it would disappear with GTK 3.12 and beyond, but it seems unlikely to be the source of this error. This glitch looks projection-related, and the evhack stuff is/was merely a way of getting more events-per-second than GTK was prepared to give us back then.

Similarly, upgrading GTK might fix this if it or your theme is playing funny fractional games with border widths or similar.

* Can you try a different theme please? Ideally, the default Adwaita theme. If Mypaint behaves differently, that tells us something.

**Comment by achadwick** [comment]
(Oh, and the GtkTreeView and GtkWindow warnings aren't relevant for this...)

**Comment by TuringMachinegun** [comment]
Hi Andrew,

Yes, the glitches still happen in fullscreen mode, but disappear when I zoom/pan/rotate/mirror the canvas. Interestingly, I just discovered that if the zoom level is anything that is not 100%, the glitches disappear (yaaay!)
Yes, I am running HiDPI.

Adwaita doesn't help, I'll try to upgrade GTK now, and see what happens. I'll update you!

Thanks! :)

**Comment by achadwick** [comment]
> Yes, I am running HiDPI.

Might be it actually. Before you upgrade, can you try turning this off just to see if it can be ruled out?

**Comment by TuringMachinegun** [comment]
I didn't even know there was an option to deactivate it. Yup, withouth HiDPI it works perfectly fine!

**Comment by achadwick** [comment]
Well, that's a workaround anyway. :grin: 

Still, it shouldn't be happening.
I'll have to see what 3.16 or later does in GNOME HiDPI mode on mine when I have a chance, see if it can be replicated. If you still want to upgrade GTK, can you test bot HiDPI and non-HiDPI afterwards and see what you get?

**Comment by TuringMachinegun** [comment]
I'm reading bad things happen to those who try to upgrade to 3.16 on Mint 17.3 with cinnamon, and I'm travelling for work for a couple of weeks: I only have this computer to get work done, and I can't break it (yet) :disappointed:
When I return, I might feel adventurous and break things though, maybe it's time to say goodbye to cinnamon. I'll update you :smile:

**Comment by odysseywestra** [comment]
You could try Gnome Ubuntu 15.10 as a LiveUSB since it dose have 3.16. At least it will help to see if those problems arise with HiDPI mode. Plus you won't have to worry about breaking your machine.

**Comment by TuringMachinegun** [comment]
I can do that, downloading it now

**Comment by achadwick** [comment]
Reproduced in GNOME under Debian testing/unstable, which is currently using `libgtk-3-0` version 3.18.9. Steps to reproduce:

1. Start `gnome-tweak-tool`
2. Under Windows → HiDPI, enter "2" and accept it via the dialog
3. Restart gnome-shell (Alt-F2, type "r" and press return)
4. Start MyPaint 1.2.0 or 1.3.0-alpha as of dca42cd.
5. Zoom to 100%
6. Choose a big brush, pale yellow background, white paint
7. Paint!

![repro1](https://cloud.githubusercontent.com/assets/61299/14194941/a6eec54c-f7ab-11e5-9903-8a22e08486c8.png)

Not only are redraws looking bad, but we need to be respecting the HiDPI setting for the canvas rendering itself! Our "device" space != the device's actual pixels, kinda the definition of HiDPI.

The reported glitch affects every repaint bounding box, and it presents best at z=100%, i.e. what should be 1:1 between the real device and the working document.

Zooming in also reveals a lot of the nasty hacks I added to draw shadows under the onscreen buttons and control points in things like inking mode: :blush: 

![image](https://cloud.githubusercontent.com/assets/61299/14195068/0b03383c-f7ad-11e5-8194-771676f8caf2.png)

That's at z=100%, and it's telling: where we do vector rendering with Cairo, things are real-device pixel-perfect, albeit at twice the size that's ideal for those hairline white edges and drop shadows. Cairo is doing the right thing there. Where we stamp down a bitmap, like in the button icon or the canvas, it's offset a bit and blurry, having passed through a scaling filter.

**Comment by achadwick** [comment]
Reproducible with the mouse, no need for a tablet. I think I'm wrong about the offset too, ignore me there if it makes more sense :stuck_out_tongue_winking_eye:

In case it matters (it might, given the way Cairo works): I'm using Intel graphics hardware:

```
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b) (prog-if 00 [VGA controller])
	Subsystem: Dell Haswell-ULT Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 45
	Memory at f0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by TuringMachinegun** [comment]
Hey, didn't test it yet because I need to buy a USB key for the live cd (still travelling). Would it still be useful for me to test it?
PS. I have the same VGA controller (Haswell-ULT), so it might be a/the factor

**Comment by achadwick** [comment]
@TuringMachinegun probably no need for now: newer GTK+Cairo is just as susceptible.

Here's some things we could look at:

* https://github.com/mypaint/mypaint/blob/v1.2.0/gui/tileddrawwidget.py#L1294

  So one question to ask is: does the problem vanish if this condition is made True all the time? Or equivalently, is the problem any better with stock MyPaint when the canvas is rotated a bit (Ctrl+[ or Ctrl+Left)?

* Does preparing the temporary GdkPixbuf zoomed in again by 2x, then  cairo_paint()ing it with an extra cairo_scale(0.5) fix the issue and make things sharp again?

**Comment by TuringMachinegun** [comment]
For point 1: If the condition is made True all the time, the problem is ameliorated but still there. Here's a screenshot
![condtrue](https://cloud.githubusercontent.com/assets/8633845/14225351/4fefe49a-f8c0-11e5-90d3-0659197fdad8.png)

Yes, if I use stock MyPaint and rotate the canvas, the problem disappears completely.

**Comment by achadwick** [comment]
[Paging @gerroon, who has seen some rectangles in big-screen Windows - do they look like the ones above?]

@TuringMachinegun 
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) has now been released. Please can you confirm whether or not this bug is still happening in that version? Mint boxes should be able to get it from the PPA.

Can anyone bitten by this bug please try running MyPaint with and without the following environment variable and a fresh config each time? Thanks.

    GDK_WIN32_DISABLE_HIDPI=1 mypaint -c /tmp/throwaway_config_1
    mypaint -c /tmp/throwaway_config_2

**Comment by gerroon** [comment]
@achadwick 

Yes It hink they do (I am referring to the first picture TuringMachinegun  posted)

**Comment by achadwick** [comment]
Okay, that should fix HiDPI mode for systems it's supported on. I can only test by setting GDK_SCALE=2 when invoking MyPaint right now, but the approach looks sound ☺

@TuringMachinegun, can you re-test please, and re-open this issue if it's still happening? Please report any glitches or wrongness that occurs if the widget→screen scale changes during runtime as separate issues - I introduced some dubious code to handle that, and it might not work as expected.

**Comment by dphilp** [comment]
Not sure if this was resolved and not released yet, but I'm having exactly this issue on the latest release of MyPaint for Win 10 64 bit, using a new Yoga 920 with mouse/finger/pen.

**Comment by arteniioleg** [comment]
![screenshot from 2017-12-10 13-54-23](https://user-images.githubusercontent.com/28860670/33804639-a989ecee-ddb1-11e7-9ef1-ae256ab4911b.png)

I am on linux, 4k display.

It doesn't happen always. This is what I did: Installed MyPaint > First launch > Draw > Artifacts > Chage background to white > No artifacts > Happy drawing > Close MyPaint > Open MyPaint > Draw > Artifacts > No I can't get rid of them.

**Comment by arteniioleg** [comment]
## The solution

**Rotate** the canvas

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/28860670/33804831-f31319f4-ddb5-11e7-8a09-721af5454364.gif)

**Comment by dphilp** [comment]
Not a "solution", imho.
