### ISSUE TITLE
Wrong icon name for "Change color" menu items

### ISSUE THREAD

**Issue by danpla** [mypaint/mypaint#646]
![2016-04-08-182132_1600x900_scrot](https://cloud.githubusercontent.com/assets/10910745/14388471/f379d71a-fdb6-11e5-9485-45c61b5e0b60.png)

Both items in `gui/resources.xml` refer to "mypaint-color-symbolic", while the actual name is "mypaint-color**s**-symbolic".

MyPaint 1.2.1 from the testing PPA.

**Comment by odysseywestra** [comment]
Thanks for pointing that out. I'll make sure to fix that when I apply the default keyboard settings.
