### ISSUE TITLE
Myriad problems: turning the pen often doesn't change to eraser, periodically unable to do anything but zoom in with hotkeys or save, backup doesn't seem to work

### ISSUE THREAD

**Issue by goblinvomit** [mypaint/mypaint#648]
I'll skip the ones that I've found through searching. 

When I turn my pen to erase, more often than not, it doesn't switch to my chosen eraser brush, and vice versa when switching back. I'm forced to switch manually, and nothing annoys me more than minor inconvenience. I checked the pen debug thing, and the software knows when I turn the pen every time I do it. 

With no apparent pattern, but without fail every time I draw, multiple times, I will lose the ability to do anything except zoom or save using hotkeys (thank fuck I can at least save). I tried every hotkey, and those are the only ones which seem to work. None of the software buttons (like brushes, layers or anything) will work and I can't draw. I have to ctrl+s and then close MyPaint from the taskbar. 

Finally, I cannot load backups. Every time I open MyPaint it asks me if I want to load a backup from weeks ago, when the software crashed, but the option to load it is greyed out. Where are backups stored? Should I have installed outside of Program Files? 

I'm switching back to an older version. I'm losing my mind. Also, just my preference, but I liked the immense simplicity of the older versions.

Thanks!

**Comment by odysseywestra** [comment]
First off thank you for submitting a bug report, sadly I'm going to have to close this issue. The reason being that you reported multiple bugs on one issue thread, and reporters are only allowed one bug report per issue ticket. Plus submitting multiple bugs into one issue ticket make is really difficult to manage. 

Please read our Bug reporting wiki at https://github.com/mypaint/mypaint/wiki/Reporting-Bugs for more information on how to submit bug reports on our Github Repository Issue Tracker. I'm sorry you frustrated with MyPaint right now, but we have to keep our issue tracker organized.

**Comment by achadwick** [comment]
@goblinvomit 
Sorry you're having issues. We try and fix stuff, but if things get reported without details and all in one big mixed bundle of woes, we hardly know where to start.

You may find you get useful feedback and help from the [MyPaint Community Forums](http://community.mypaint.org/).

There's the option of trying a factory reset, just in case it fixes things: https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset

The "load option" - did you mean the dialog response button at the bottom? - should not be greyed out once you have clicked on a backup. Try clicking the auto-save backup line first. This thing can show multiple auto-save backups. It's supposed to be a bit of an interruption and require interaction to make you think about which one to restore in just that scenario. Maybe when the choice is simple, we could automatically select the first line? A discussion for another issue, or a forums thread.

Backup autosaves go in `%LOCALAPPDATA%\Microsoft\Windows\Temporary Internet Files\mypaint` on Windows. Silly location, but it's what GLib considers the standard for cache-like files. GLib is the component we use that provides a measure of independence from OS-specific stuff.

Program Files is the standard location. There's almost no reason to change this beyond personal choice.
