### ISSUE TITLE
Colour history: IndexError: list index out of range

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#649]
Accidentally pressed colour history key - colour changed, i chosed another colour from colour history in dockpanel.

```python
Mypaint version: 1.2.0+git.f62444e.dirty
System information: Windows-8-6.2.9200
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint\gui\history.py", line 170, _button_clicked_cb(self=<ColorHistoryView object at 0x8540360 (gui+history+ColorHistoryView at 0x89e23c0)>, button=<Button object at 0x78131b0 (GtkButton at 0x8a636c0)>, i=4)
            history = mgr.get_history()
            color = history[i]
            mgr.set_color(color)
  variables: {'color': (None, []), 'i': ('local', 4), 'history': ('local', [<RGBColor r=0.8784, g=0.9020, b=0.9373>, <RGBColor r=0.7098, g=0.7608, b=0.6588>, <RGBColor r=0.9922, g=0.9961, b=0.9961>, <HSVColor h=0.1289, s=1.0000, v=0.0000>])}
IndexError: list index out of range
```

P.S. Windows-8-6.2.9200 - i'm using windows 10 1511 10586.218
Previous error message in windows 10 10240:
Mypaint version: 1.2.0-beta.1+gitexport.a7012b4
System information: Windows-10.0.10240

**Comment by achadwick** [comment]
Thanks for the report. That widget turns button clicks into history lookups indexed `0` through `4`. If the history is too short, the last button will try to read from an list element which doesn't exist. Hence this exception :)

**Comment by achadwick** [comment]
(The version the exception came from isn't 1.2.0-beta.1, but that version is probably affected by this too)

(Also, the exception came from Windows 8, not Windows 10.)

**Comment by zb13y** [comment]
> (Also, the exception came from Windows 8, not Windows 10.)

I'm using Windows 10, i don't understand why there are information about windows 8. I'm just telling that in my prevous error messages i got right system information, but now i get misinformation about windows 8. Maybe this happens because of i upadated to windows 10 1511 10586.218, previous version was windows 10 10240.

**Comment by achadwick** [comment]
Okay, Python lies to us about OS versions. :stuck_out_tongue_closed_eyes:

Good to know, I suppose. It won't hold up a fix for this little bug :smile:

**Comment by achadwick** [comment]
Hopefully fixed. I wasn't able to reproduce the error, however.
