### ISSUE TITLE
Undo buffer is too small

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#652]
Current undo buffer stores about 20 last actions which is too small in some cases. Please increase it to something like 100..  Ideally it should be configurable from settings.
I lost big part of work and was not able to recover it due to very limited undo buffer.

**Comment by achadwick** [comment]
Really it could be limited by available memory only, keeping some free for fresh drawing, and being prepared to trim the command stack at the trailing end when the system is low on RAM. We have an open issue about improving it already.

#292 is already scheduled for 1.3.x, so I'll close this as a duplicate and move that one forward for "real" consideration before 1.3.0.
