### ISSUE TITLE
Cloning the layer makes layer selection invalid

### ISSUE THREAD

**Issue by loentar** [mypaint/mypaint#653]
When you clone a layer the selection in layers list remain (source layer is selected). But any painting affects the clone.

The problem: visually selected one layer, but you paint on another.

Here is 2 screencasts:

https://drive.google.com/open?id=0BwvdX1pBENi1MUtfTFQ1WXZvT3c

https://drive.google.com/open?id=0BwvdX1pBENi1ZDNDaHlwNnd4Njg

**Comment by achadwick** [comment]
Reproduced in master as of 5ac00a8d6937e173fc3e07d9e1ec8c2f3641f1c7.

**Comment by achadwick** [comment]
Thanks for the report, and good spot! I think this is fixed now ready for the 1.2.1 release, and for 1.3.0.
