### ISSUE TITLE
Wrong BrushGroupTool behavior after creating brush groups

### ISSUE THREAD

**Issue by danpla** [mypaint/mypaint#654]
Steps to reproduce:
1. Delete the default "favorites" group and create it again
2. Try to add a brush to the "favorites" using (a) the pop-up menu and (b) drag-and-drop

Result:
a. The brush is added to the "favorites", but it's icon is not visible in the grid
b. The brush is added to the non-existing group: it's icon visible in the grid, but you can still add it to the "favorites" via pop-up menu

**The reason**

Each BrushGroupTool is created via ObjFactory, which caches objects. This means that BrushList inside a BrushGroupTool always keeps the reference to the group with which it was created. When this group is removed in BrushManager.delete_group, the list becomes empty.

Since BrushGroupTool for a group is cached, the link in BrushList is not updated when BrushManager creates a new groups with the same name. As a result, when you add a brush via pop-up menu, it's added to the new group, but after drag-and-drop, it's added to the empty list of the BrushList. 

The possible quick but ugly workaround is to connect the BrushList to the BrushManager.groups_changed event to re-assign the group every time.

It's not possible to fix #641 properly without fixing this one first.

**Comment by achadwick** [comment]
Looking at the complexity of this pair of related changes (#641 and #654), I'm only going to fix them on master so that the new code can receive plenty of testing.
