### ISSUE TITLE
HCY Wheel gamut mask doesn't update popup shortcut HCY wheel until next session

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#655]
When you press "C" to pop up the transient HCY Wheel, the gamut mask (or lack thereof) is preserved in a static state from the previous mypaint session.  Any changes to the gamut mask are ignored by the transient popup window.  You might get one update the very first time you try this, after that the gamut mask is never updated until restarting mypaint.
Debian Sid
mypaint 1.3.0-alpha+git.ac2688c
mypaint 1.2.0+gitexport.f62444e
libgtk-3.18.9-1
libgtk-3.20.3-1

**Comment by briend** [comment]
![gamut mask](https://cloud.githubusercontent.com/assets/6015639/14627917/dd5efa42-05ad-11e6-8b45-17b7833e3b2b.png)

**Comment by achadwick** [comment]
Confirmed with v1.2.0 and master at ac2688c1ee4675f497793fae0503fdd84ee588a1 under Debian testing/unstable.

**Comment by achadwick** [comment]
Closing in favour of #889, which has a detailed breakdown of how to reproduce it.
