### ISSUE TITLE
Exception at startup; crashy behaviour with line tool

### ISSUE THREAD

**Issue by hihikoala** [mypaint/mypaint#659]
Up until yesterday (4/22/16), I never had any problems with the lines and curves tool. But now, all of a sudden, every time I try to use it, the program crashes. This also happens with the connected lines, ellipses and circles, and inking tools. Sometimes, the program even crashes right when I open it. And because of these crashes, I cannot recover the unsaved work like I could if I were to accidentally close it. I've been using this program for over a year across many versions, and this has never happened before. I have not updated it since 3/16/16 and this did not happen before or after updating it until now. I like to use these tools a lot, and the crashes make it so I cannot continue working on my projects.

**Comment by odysseywestra** [comment]
Could you provide us with what version of MyPaint you are using? You can find it under Help>About MyPaint. Also tell us which OS, or Linux Distro you are using since MyPaint is a Cross-Platform program.

**Comment by hihikoala** [comment]
It's version 1.2.0 for Windows x32

**Comment by hihikoala** [comment]
*windows 10, x32

**Comment by achadwick** [comment]
Hi there - thanks for the report!

There's not quite enough information in your original report to move this issue forward, sadly. Please read the [bug reporting guidelines](https://github.com/mypaint/mypaint/wiki/Reporting-Bugs). We need more information this particular crash if this report is going to be useful to us.

Tell us *exactly* how it went wrong, and *exactly* what you did to try and fix it for yourself. Be really, really specific. Are there any exception dialogs? Please click on any "more details" buttons or fold-outs. Paste what you see there here. Please don't try reinstalling until you give us the details, or we'll have nothing if your action fixes it.

We need to know what kind of Windows you are running. 64-bit or 32-bit? Win7, Win8, Win10?

Where did you download MyPaint from?

Did any OS updates change your computer on 22 May 2016? You can look in your Windows Update history.

**Comment by achadwick** [comment]
("Crash" can mean the Python code exception handler to users.)

@hihikoala Do you ever get offered the option to continue when it happens?

**Comment by achadwick** [comment]
@hihikoala 
Does "every time I try to use it" mean that every time you try to use a tablet pen to do something, it (crashes or dialogs you or something)?

**Comment by hihikoala** [comment]
Okay, here's everything I know about the problem. My computer runs Windows
10, 64-bit OS but I believe the version of mypaint I have is for 32-bit
because the 64-bit wouldn't work for some reason, I don't remember exactly.
I downloaded version 1.2.0 from the github page linked on mypaint.org. The
most recent update to my computer in the update history was on April 20th.
It updates automatically almost every night so yes, there was one on
*March* 22nd
(May is next month, I think that was a typo), however I don't think that an
update so far back would have been the problem since the issue is recent.

Since the problem began, and never before, every time I open mypaint, it
brings up a dialogue titled "Bug Detected." It says "A programming error
has been detected. You may be able to ignore this error and carry on
working, but you should probably save your work soon. Please tell the
developers about this using the issue tracker if no-one else has reported
it yet." Under a tab marked "Details..." I find a wall of text that says:

>
> ```python
> Mypaint version: 1.2.0+git.f62444e.dirty
> System information: Windows-8-6.2.9200
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\MyPaint\share\mypaint\gui\application.py",
> line 412, _at_application_start(self=<gui.application.Application object>,
> filenames=[], fullscreen=None)
>                 autosave_recovery = gui.autorecover.Presenter(self)
>                 autosave_recovery.run()
>  variables: {'autosave_recovery.run': ('local', <bound method
> Presenter.run of <gui.autorecover.Presenter object at 0x0374F650>>)}
>   File "C:\Program Files (x86)\MyPaint\share\mypaint\gui\autorecover.py",
> line 66, run(self=<gui.autorecover.Presenter object>,
> no_autosaves_dialog=False)
>             autosaves = []
>             for asav in lib.document.get_available_autosaves():
>                 # Another instance may be working in there.
>  variables: {'lib.document.get_available_autosaves': ('global', <function
> get_available_autosaves at 0x04C02B30>), 'asav': ('local',
> AutosaveInfo(path=u'C:\\Users\\Madison\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.3nhl1h\\autosave',
> last_modified=datetime.datetime(2016, 4, 23, 15, 26, 48, 678448),
> thumbnail=<Pixbuf object at 0x7576990 (GdkPixbuf at 0x754b698)>,
> num_layers=8, unsaved_painting_time=0.0, width=1920, height=1080,
> valid=True, cache_in_use=False))}
>   File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\document.py",
> line 1715, get_available_autosaves()
>             if not os.path.isdir(autosave_path):
>                 continue
>             yield AutosaveInfo.new_for_path(autosave_path)
>   variables: {'AutosaveInfo.new_for_path': ('global', <bound method
> type.new_for_path of <class 'lib.document.AutosaveInfo'>>),
> 'autosave_path': ('local',
> u'C:\\Users\\Madison\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.dzlaw8\\autosave')}
>   File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\document.py",
> line 156, new_for_path(cls=<class 'lib.document.AutosaveInfo'>,
> path=u'C:\\Users\\Madison\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.dzlaw8\\autosave')
>             if os.path.exists(thumbnail_path):
>                 thumbnail = lib.pixbuf.load_from_file(thumbnail_path)
>             cache_in_use = False
>   variables: {'thumbnail_path': ('local',
> u'C:\\Users\\Madison\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.dzlaw8\\autosave\\Thumbnails\\thumbnail.png'),
> 'thumbnail': ('local', None), 'lib.pixbuf.load_from_file': ('global',
> <function load_from_file at 0x049C3F30>)}
>   File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\pixbuf.py", line
> 91,
> load_from_file(filename=u'C:\\Users\\Madison\\AppData\\Local\\Microsoft\...\doc.dzlaw8\\autosave\\Thumbnails\\thumbnail.png',
> feedback_cb=None)
>         with open(filename, 'rb') as fp:
>             return load_from_stream(fp, feedback_cb)
>   variables: {'feedback_cb': ('local', None), 'fp': ('local', <closed file
> u'C:\\Users\\Madison\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.dzlaw8\\autosave\\Thumbnails\\thumbnail.png',
> mode 'rb' at 0x03743EE8>), 'load_from_stream': ('global', <function
> load_from_stream at 0x04ACC970>)}
>   File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\pixbuf.py", line
> 114, load_from_stream(fp=<closed file
> u'C:\\Users\\Madison\\AppData\\Loca...\autosave\\Thumbnails\\thumbnail.png',
> mode 'rb'>, feedback_cb=None)
>                 break
>             loader.write(buf)
>         loader.close()
> *(really super duper long line that makes the webpage crash if I paste it
> in, hopefully it's not super important)*
> Error: gdk-pixbuf-error-quark: Fatal error reading PNG image file:
> Decompression error in IDAT (0)
> ```


 There is also the option to either search the tracker, ignore the error,
or quit mypaint. If I ignore, that is the only way to continue. This
dialogue only opens up when I first open the program, and never during use.
Now, the program crashes whenever I try to use a drawing tool that is not
the paint bucket or freehand. It does not crash every single time I try,
but it usually does. When it does, there is no warning or option to
continue, it just freezes for a second, and then a box pops up saying
"MyPaint has crashed. Windows is checking for a solution." just like it
would on any other crashed program. I am then forced to close it and hope I
saved it recently because it does not save any form of scrap for me to
recover. It does not offer me the option to continue in any form.

I have found through trial and error the last time I was working on my
project that it helps to do freehand work before using the other tools. I
opened up the .ora file, did a little bit of freehand clean up, then was
able to use the line tool without an issue. I saved it throughout this
process with no problem. After a while, I saved the image iteration as a
.png for later use. When I tried to continue using the line tool after
this, then it crashed. There are times when I do freehand stuff and then
use the line tool, and it crashes on the first try. There are times where I
only use the line tool and it crashes right away, or it keeps working like
there's no problem at all. The whole thing is very unpredictable and
annoying.

It may be worth mentioning that when I do freehand stuff, I use my wacom
tablet, but I prefer to use the mouse and keyboard for all other tools.
That might affect it in some way, but I don't know. I've also tried using
the tablet when using the line tool and it seemed to have no difference
from the mouse.

That is everything I can tell you about this issue without being guided
step by step to where more information might be hidden away. I'm not a tech
savvy person who knows anything about code, I am just an artist trying to
meet my deadline. Hopefully, what I can tell you is enough to get it fixed.

**Comment by achadwick** [comment]
Thanks for the details! I can't reformat your message enough to make it really readable because it's an email, but I hope the above is OK to work from.

Somehow you have a corrupt image file under `C:\Users\Madison\AppData\Local\Microsoft\Windows\INetCache\mypaint\doc.dzlaw8` in other words, a corrupted or truncated autosave. To fix it:

* Close MyPaint completely
* Move that `doc.dzlaw8` folder (and any other `doc.<randomstring>` folders you have trouble with) to your desktop
* Launch MyPaint again
* Repeat until it works

(Yeah, this isn't supposed to happen. But also we can't account for *everything* that might go wrong on peoples' computers :neutral_face: )

Each `doc.<waffle>` folder is an autosave. A bursted-out view of the document you were working on.

(If there's a lot of bad autosaves, you can safely move the "mypaint" folder in INetcache out of the way)

**Comment by achadwick** [comment]
There's more going on here too. I'm not sure what's going on with the line tool - it sounds like a harder kind of crash? No crash dialog like the one you saw at startup?

Let's solve the startup issue first, so we can investigate it separately.

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) was released recently. Please could you test it out, and let us know whether the bug is still happening?

**Comment by jplloyd** [comment]
No response for >3 years. Assumption: no longer an issue.
