### ISSUE TITLE
An extra scroll event after the "evhack filter"

### ISSUE THREAD

**Issue by danpla** [mypaint/mypaint#670]
#### Description of the problem

I noticed that MyPaint uses too big zooming increments: 100 > 150 > 300 > 550 instead of 100 > 150 > 200 > 300 > 400 > 550. After some "debugging print()s", I found that `ScrollableModeMixin.scroll_cb()` is called twice.

The first (redundant) event always has `Gdk.ScrollDirection.SMOOTH` direction, even if the smooth scrolling is disabled in settings. The "normal" scroll event goes after it.

Most importantly, this extra event begins to appear only after the "evhack filter" is activated, that is, after the first motion event over the canvas. Maybe something is wrong in `lib/eventhack.cpp`.
#### Basic system details

MyPaint version: 1.2.1-beta.1+gitexport.3198e3f and git revision b8991c2 
Operating system: Xubuntu 14.04 x64
Desktop environment: Xfce
#### Steps to reproduce

To scroll before "evhack filter" gets enabled, you must not move your mouse: run MyPaint via terminal so that canvas will appear right under the cursor.
1. (optional) Add `print(event.direction)` at the beginning of `ScrollableModeMixin.scroll_cb()` to see what's happening
2. Start MyPaint as described above
3. Scroll up/down -> one "scroll-event"; normal steps
4. Move the mouse pointer to enable the "evhack filter"
5. Scroll again -> two "scroll-event"s; big steps

**Comment by achadwick** [comment]
I think it's time to drop PPA support for 12.04LTS now that 16.04LTS is out. We should do it with some warning, however.

I've been itching to get rid of evhack for a very long time, and MyPaint has been saying gtk >= 3.12 for a while now without really meaning it. This unwanted scroll event is just another reason to rip out the evhack code, to me.

If we do this, and just call gdk_window_set_event_compression() at window creation, it can be done without breaking backwards compat gratuitously. Just catch the exception and log it for the user. However, input resolution will suffer on legacy platforms with GTK < 3.12.

That's not really a problem if users can upgrade their OS to stable releases with modern GTK libs.

* Current Ubuntu LTS (16.04 "xenial"): GTK 3.18.9 <http://packages.ubuntu.com/libgtk-3-0>
* Current Debian stable ("jessie", 8.4): GTK 3.14.5 <http://packages.debian.org/libgtk-3-0>

Evhack is _genuinely terrible_, X11-specific code of daily increasing irrelevance as Linux moves towards Wayland. It has never worked on Quartz or Win32. Let's just kill it off.

**Comment by achadwick** [comment]
For 1.3.0, since an evhack rip is pretty disruptive, and we shouldn't be making a change this big to a point release branch.

I'll make the PPA announcement separately, since it can be done independently.

**Comment by danpla** [comment]
https://github.com/GNOME/gtk/commit/8bb3a2001f63739e6ee47ee683ceb581d0eac97f

**Comment by achadwick** [comment]
@danpla I'm not understanding what you mean by that commit. It will be included already in Xubuntu 14.04. Or are you saying that's where the fault was introduced?

(PPA/support annoucement made, btw: http://mypaint.org/blog/2016/05/03/support-for-trusty-to-be-discontinued/)

**Comment by danpla** [comment]
@achadwick Maybe it can help to understand what's happening. At least that's the place where the extra event is generated.

**Comment by danpla** [comment]
This issue is not relevant for v1.3.0, since Gdk.Window.set_event_compression() was added in Gtk 3.12.

**Comment by jplloyd** [comment]
The evhack code was removed in c0d38aad1a2f8d6af8ab9f005c05b9f7c41499bc 
I'm closing this since another 1.x release, with the fix backported, is very unlikely.
