### ISSUE TITLE
MyPaint 1.2.1 beta 1 doesn't detect stylus eraser - Wacom Bamboo Pen & Touch (CTH-470) - Windows 10 x64

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#673]
#### Description of the problem

MyPaint 1.2.1 beta 1 doesn't detect stylus eraser (Wacom Bamboo Pen & Touch (CTH-470)), pen works, eraser not. In Input Device Test instead of Wacom Tablet Eraser i see System Agregatted Pointer. I don't have such problems with MyPaint 1.2.0. stable.
### Basic system details

**MyPaint version**: 1.2.1-beta.1+gitexport.3198e3f (Python 2.7.11, GTK 3.20.3, GdkPixbuf 2.34.0, Cairo 1.15.2, GLib 2.48.0)
**Operating system**: Windows 10 x64
**Tablet**: Wacom Bamboo Pen & Touch (CTH-470), driver - 5.3.5-3 (Latest)

**Comment by achadwick** [comment]
Can you draw with the eraser end? Does it receive a different device ID after you've used it (try both ends, then look in  Preferences→Devices and tell me what is listed).

Do you have access to an MSYS2 installation <https://msys2.github.io/>?  With a little coaxing and command-line use, it has a gtk3-demo program available which uses the same libs as the beta. Testing using that will help decide if this is a MyPaint issue.

**Comment by achadwick** [comment]
You have to try both ends of the tablet stylus because initial tool/device detection is broken in Windows GTK. MyPaint has to gain knowledge of available tools as you use them over time :neutral_face:

**Comment by zb13y** [comment]
Pen - Wacom Tablet Pressure Stylus
Eraser - System Agreggated Mouse (I can draw with it, but eraser don't have pressure (like mouse). Also eraser doesn't remember used brush, when i switch stylus end it have same brush that i used with other end.)
Mouse - System Agreggated Mouse

**Comment by achadwick** [comment]
@zb13y 
What does gtk3-demo reveal?

1. Follow the instructions at https://msys2.github.io/
2. Start the msys2 shell corresponding to your MyPaint install ("MINGW64" not "MINGW32" or "MSYS")
3. Type in `pacman -S mingw-w64-x86_64-gtk3` and press Return/Enter. Allow the installation to happen.
4. Type in `gtk3-demo` and press Return/Enter.
5. In the demo program, run the Event Axes demo (see below).
  * **Q:** Is it pressure-sensitive? Does it show an "eraser" name for the eraser end of your stylus?

![gtk3-demo-event-axes](https://cloud.githubusercontent.com/assets/61299/15042731/55d7ad6c-12be-11e6-85d9-49b9163192e5.png)

**Comment by achadwick** [comment]
Mice are currently "[Teflon-coated](https://en.wikipedia.org/wiki/Polytetrafluoroethylene#Applications_and_uses)" in MyPaint. Device settings do not stick to them. There is a comment in the code stating the people sometimes change brushes with the mouse while they are painting with their stylus, and want the stylus to receive the settings :confused:

To be honest, this behaviour is a bit weird and causes problems for users with buggy GDKs.

**Comment by zb13y** [comment]
In demo i also have System Agreggated Mouse with eraser. And i don't get how i can test pressure in demo, it doesn't work even with pen end of stylus.

**Comment by achadwick** [comment]
@zb13y
Unexpected. If you put more pressure on, that circle should get more red and less blurred. Do you only see the crosshairs with the pen?

You might need to try it with the tablet plugged in and working at demo startup.

**Comment by zb13y** [comment]
I see only crosshairs. Pressure works in mypaint 1.2.1 beta 1, but doesn't work in demo. Pen - WACOM Wacom Tablet Pressure Stylus

**Comment by achadwick** [comment]
@zb13y That's very strange. Would you mind confirming that you really are using the same GTK?

```
$ pacman -Ss mingw-w64-x86_64-gtk3
mingw64/mingw-w64-x86_64-gtk3 3.20.3-1 [installed]
    GObject-based multi-platform GUI toolkit (v3) (mingw-w64)
```

I don't know whether Windows needs you to close all other programs that might be using wintab.dll, but you could try that as well.

**Comment by zb13y** [comment]
Yes, same.

mingw64/mingw-w64-x86_64-gtk3 3.20.3-1 [установлен]
    GObject-based multi-platform GUI toolkit (v3) (mingw-w64)

**Comment by zb13y** [comment]
Wacom Bamboo Pen & Touch (CTH-470), driver - 5.3.5-3 works in 1.2.1+gitexport.bcf5a28d (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1).
