### ISSUE TITLE
pixbuflist: redrawing too much, causes slowdowns

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#675]
#### Description of the problem

When brush lists are visible, or when the background window is visible, MyPaint continually redraws any pixbuflist currently seen.

When big lists of brushes are involved, this can cause MyPaint slowdowns when the brush lists are visible, and not at other times: https://community.mypaint.org/t/mypaint-is-slower-on-ubuntu-16-04/342. As the thread slug suggests, this fault may only become visible starting with the GTK in Ubuntu 16.04 LTS ("xenial"). That's GTK 3.18.9.
#### Basic system details

MyPaint version: git revision c24475f920089436aab8037a6bdb3bedeea428a0
Operating system: Debian testing/unstable
Desktop environment: GNOME
#### Steps to reproduce
1. Install everything necessary to get graphical profiling working, as described in https://github.com/mypaint/mypaint/blob/master/DEBUGGING.md#profiling
   - Assign the start/stop profiling command to a convenient hotkey, like F9
2. Start MyPaint with a clean config. Do not draw anything.
3. Open any brush group in the sidebar, or open the backgrounds window.
4. Point the cursor at the canvas.
5. Without moving the cursor, press F9.
6. Without moving the cursor, wait a few seconds.
7. Without moving the cursor, press F9 again.

The profiler output should appear in a file browser window, with generated PNG files. Open the most recent one and have a look. Note the hot path involving the pixbuflist's draw_cb() method. This method should not be being called repeatedly. I'd expect it not to be called at all for the steps above, if it has already been drawn!

The problem can also be reproduced with the popup brush selector on the "B" key, but the profiling graph necessarily has more hair to it then: you need to wiggle the mouse to make the popup go away before you can stop profiling.
#### Profiler output

When it's just the background window:

![profiler1](https://cloud.githubusercontent.com/assets/61299/15073475/92288204-1391-11e6-88f8-0edda9be3195.png)

A more typical case, for a docked brush group:

![profiler2](https://cloud.githubusercontent.com/assets/61299/15073524/ce28744e-1391-11e6-9e1f-e8a88e41957c.png)

Both passes are about 3 seconds long.

**Comment by achadwick** [comment]
Pixbuflist was one of the first things I hacked on when I joined the project. It has always done its layout in a really broken way and it's always been a difficult module to diagnose. Perhaps a rewrite is due.

I strongly prefer the look and layout of our much newer palette windows, to be honest. There is a lot that could be done to improve the look and feel of our brush lists, and there could be code shared between the two if we were to do a rewrite.

* :grinning: I'd quite like to highlight brushes which are in the faves list with a special icon, e.g. a star.
* :bug: Conversely, the colour palette does not respect [RTL text layout](https://en.wikipedia.org/wiki/Right-to-left): see [gui/colors/paletteview.py#L1371] (https://github.com/mypaint/mypaint/blob/fe0207a2ad2c5db372eaf139f786014d2e88c687/gui/colors/paletteview.py#L1371).
* It would be fine for brush previews to scale, probably.
* A centred layout, like the current palette widgets, looks lovely.
* :bulb: Idea: the base class takes care of click sensitivity, sizing, redraws, and layout
  * I guess all subclasses like palettes or brush lists or background lists would need to do is issue some Cairo drawing commands, and handle what happens when the user clicks an item.
* It could be done by composition too, of course. But that leads to a lot of scattered helper functions.

**Comment by danpla** [comment]
Probably the [Gtk.IconView](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/IconView.html#gtk-iconview) is the best solution both for brush lists and the background list. There are many advantages:

  1. MVC: A list can be rendered both with `Gtk.IconView` and `Gk.TreeView`, as in GIMP
  2. Custom models
  3. Custom cell renderers, for example, to draw overlay icons etc.
  4. Good look and feel with various themes; flexibility (paddings, margins, etc.); styling via CSS
  5. Easier to write, easier to maintain

**Comment by achadwick** [comment]
I prefer MVP these days :wink: 

We can get code that's both easier to maintain and more Pythonic than GTK's vaguely MVCish setup for ListViews, TreeViews and IconViews by doing it ourselves and making the separation of responsibilities between the M/V/C or M/V/P elements better. GTK's idea of MVC is that your your model should use GTK code.

To be clear: GTK code does not belong outside top-level view and controller/presenter roles in MyPaint, i.e. it should not be used in `lib/`. We might want a pure-Clutter UI one day, or something similar.

We can use a complete ListView or TreeView M/V cluster in `gui/` as a façade for deeper elements though, and we do just that for the layers tree.

Gtk's ListView is crawling with GTK bugs, and has had numerous regressions in little-tested areas and corner cases such as dnd with a custom model. We end up writing facilities like that for ourselves. I've had some experience of that model of working, and it's really neither pleasant to write nor maintainance-free.

Also we have a way of indicating a nearest partial matches in the colour palette view. I'd like that for brush palettes too! GTK does not provide that.

Anyway, we should probably focus on a quick fix for this issue first. My bad.

**Comment by danpla** [comment]
A call to `get_background_color` leads to an endless "draw" signal. Most likely it's a bug in GTK (although this method is deprecated since 3.16).

Seems like adding `Gtk.StyleContext.save()`/`restore()` around the style context manipulation in `draw_cb` solves the problem (at least on Xubuntu 16.04).

```diff
diff --git a/gui/pixbuflist.py b/gui/pixbuflist.py
index 2ead38c..770b28e 100644
--- a/gui/pixbuflist.py
+++ b/gui/pixbuflist.py
@@ -329,6 +329,7 @@ class PixbufList(Gtk.DrawingArea):
         # Paint the base color, and the list's pixbuf.
         state_flags = widget.get_state_flags()
         style_context = widget.get_style_context()
+        style_context.save()
         bg_color_gdk = style_context.get_background_color(state_flags)
         bg_color = uicolor.from_gdk_rgba(bg_color_gdk)
         cr.set_source_rgb(*bg_color.get_rgb())
@@ -342,6 +343,7 @@ class PixbufList(Gtk.DrawingArea):
         gdkrgba = style_context.get_background_color(
             state_flags | Gtk.StateFlags.NORMAL)
         insertion_color = uicolor.from_gdk_rgba(gdkrgba)
+        style_context.restore()
         # Draw borders
         last_i = len(self.itemlist) - 1
         for i, b in enumerate(self.itemlist):
```

**Comment by danpla** [comment]
Excerpt [from the docs](http://lazka.github.io/pgi-docs/Gtk-3.0/classes/StyleContext.html#Gtk.StyleContext.get_property):
> Note that passing a state other than the current state of self is not recommended unless the style context has been saved with Gtk.StyleContext.save().

**Comment by achadwick** [comment]
@danpla 
If that's a good enough workaround, I'll push it for 1.2.1. Thanks!

**Comment by achadwick** [comment]
Not forgotten about this one, I've just been super-stressed and busy with RL things recently.

**Comment by Sluring** [comment]
No need to hurry for my sake at least. I found an acceptable solution by creating a collection with just the brushes I actually use and hide all other brush sets.

**Comment by achadwick** [comment]
For what it's worth, I can no longer reproduce this under gtk 3.22.4 on X11. I will integrate the suggested patch however, since it tests out OK and is more correct. That ought to make things nicer for GTK 3.18 thru 3.22.
