### ISSUE TITLE
crashing on startup

### ISSUE THREAD

**Issue by grundfall** [mypaint/mypaint#676]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem

[✍ Fill in this section with a clear description of **ONE** problem.]
[☞ Stay on topic. Other problems go in separate issues.]
[☞ Read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs first.]
[☞ Check the title is short but useful. It should echo this description.]
[☞ Pictures and videos help us a lot. You can paste screenshots.]

#### Basic system details

MyPaint version: [✍ 1.2.0 stable, 1.2.1-beta.1, git revision NNNNNNN, …]
Operating system: [✍ Debian 8.3, Ubuntu 16.04, Windows 7, …]
Desktop environment: [✍ GNOME, Xfce, …]

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. [✍ second step]
3. [✍ third step]

#### Backtraces or error messages

```
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by grundfall** [comment]
application tries to start and fails,i have saved the cmd line log:
INFO: mypaint: Debugging output enabled via MYPAINT_DEBUG
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'C:\\Program Files (x86)\\MyPaint'
DEBUG: mypaint: datapath: u'C:\\Program Files (x86)\\MyPaint\\share\\mypaint'
DEBUG: mypaint: iconspath: u'C:\\Program Files (x86)\\MyPaint\\share\\icons'
DEBUG: mypaint: old_confpath: None
DEBUG: mypaint: localepath: u'C:\\Program Files (x86)\\MyPaint\\share\\locale'
DEBUG: mypaint: localepath_brushlib: u'C:\\Program Files (x86)\\MyPaint\\share\\locale'
INFO: lib.i18n: Windows: LANG='en_US'
INFO: lib.i18n: Windows: LANGUAGE='en_US'
DEBUG: lib.i18n: Sanitized the priority list in LANGUAGE to 'en_US:C'
DEBUG: mypaint: localepath: u'C:\\Program Files (x86)\\MyPaint\\share\\locale'
DEBUG: mypaint: localepath_brushlib: u'C:\\Program Files (x86)\\MyPaint\\share\\locale'
DEBUG: mypaint: getdefaultlocale(): ('en_US', 'cp1252')
DEBUG: mypaint: setlocale(LC_ALL, ''): 'English_United States.1252'
DEBUG: mypaint: getpreferredencoding(): 'cp1252'
DEBUG: mypaint: getlocale(LC_COLLATE): ('English_United States', '1252')
DEBUG: mypaint: getlocale(LC_CTYPE): ('English_United States', '1252')
DEBUG: mypaint: getlocale(LC_MONETARY): ('English_United States', '1252')
DEBUG: mypaint: getlocale(LC_NUMERIC): ('English_United States', '1252')
DEBUG: mypaint: getlocale(LC_TIME): ('English_United States', '1252')
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
DEBUG: mypaint: C bindtextdomain('mypaint', u'C:\\Program Files (x86)\\MyPaint\\share\\locale'): 'C:\\Program Files (x86)\\MyPaint\\share\\locale'
DEBUG: mypaint: C bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('mypaint', u'C:\\Program Files (x86)\\MyPaint\\share\\locale'): u'C:\\Program Files (x86)\\MyPaint\\share\\locale'
DEBUG: mypaint: Python bind_textdomain_codeset('mypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C bindtextdomain('libmypaint', u'C:\\Program Files (x86)\\MyPaint\\share\\locale'): 'C:\\Program Files (x86)\\MyPaint\\share\\locale'
DEBUG: mypaint: C bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: Python bindtextdomain('libmypaint', u'C:\\Program Files (x86)\\MyPaint\\share\\locale'): u'C:\\Program Files (x86)\\MyPaint\\share\\locale'
DEBUG: mypaint: Python bind_textdomain_codeset('libmypaint', 'UTF-8'): 'UTF-8'
DEBUG: mypaint: C textdomain('mypaint'): 'mypaint'
DEBUG: mypaint: Python textdomain('mypaint'): 'mypaint'

(python2.exe:896): Gdk-CRITICAL **: gdk_display_get_device_manager: assertion 'GDK_IS_DISPLAY (display)' failed

**Comment by grundfall** [comment]
The problem was with my graphics pad,if i unplug it mypaint works.I then reconnect my pad and everything is ok.

**Comment by odysseywestra** [comment]
I'm closing this bug report. Please next time, fill out the template correctly, and also search the issue tracker.

**Comment by odysseywestra** [comment]
Also if you need help filling out a bug report for MyPaint, open a thread on our [Community Forums](https://community.mypaint.org). We'll be more than happy to help you there.
