### ISSUE TITLE
Windows: drawing lags with image background.

### ISSUE THREAD

**Issue by journey-of-code** [mypaint/mypaint#678]
#### Description of the problem

Drawing lags with image background.
Maybe half a second delay between stroke and appearance.
#### Basic system details

MyPaint version: 1.2.1-beta.1+gitexport.3198e3f
Operating system:  Windows 7, 64 bit
Desktop environment: Standard Windows
Intel Core i7-4712HQ, 16GB RAM.
#### Steps to reproduce
1. Default background from install: plain, yellowish color.
2. Choose pen brush.
3. Draw on canvas -> drawing has no lag.
4. Change background to any image (like grid, for example).
5. Draw on canvas -> drawing lags.

**Comment by achadwick** [comment]
This is very weird. I wonder if it's related to #390 ?

**Q1** Does it always happen whenever you do this from a [fresh MyPaint config](https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset)?
**Q2** After it has started, does switching back to the default background as it was fix things?
**Q3** If you click _Save as Default_ on a background which lags, _and then restart MyPaint_, does it start off without lag now?

This is the default background:

![defbg](https://cloud.githubusercontent.com/assets/61299/15184960/1e8870c8-178f-11e6-8c9a-3b990f9f6872.png)

**Q4** Does changing to any of the nearby plain backgrounds result in lag? These are all small backgrounds: 1x1tile repeats.

**Comment by journey-of-code** [comment]
Not sure if this is related to [#390](https://github.com/mypaint/mypaint/issues/390) - I'm not very familiar with the code foundation of MyPaint.
**A1** A fresh config doesn't change anything.
**A2** Yes. Switching to any of the the marked backgrounds fixes the lag.
![screenshot 044 background](https://cloud.githubusercontent.com/assets/1939047/15185896/35018c66-179b-11e6-909d-a6132a736ff9.png)
**A3** Making it default doesn't change anything.
**A4** See image in A2 which ones lag and which doesn't.

**Comment by achadwick** [comment]
Thanks for that, @journey-of-code. The final two are large in terms of pixels (that's what the **+** means), which is a bit weird.

Perhaps there's something special about the code path which loads them, or their RGBA vs. RGB state or something.

**Comment by achadwick** [comment]
Oh and: **Q5:* does it make a difference whether you are zoomed out or not? What zoom are you trying all of this at?

**Comment by journey-of-code** [comment]
**A5** Zoom matters. With 12.5% there is nearly no difference between backgrounds. With 150%, the lag is nearly 1s for my machine.

**Comment by achadwick** [comment]
@journey-of-code 
Thanks. That's zoomed in so things are 1½ times _bigger_, presumably?

Can you let me know what kind of graphics chipset you have as well?

**Comment by journey-of-code** [comment]
@achadwick : Yes. 12.5% -> everything is small, 150% -> everything is big.
Chipset is Nvidia Quadro K1100M. That is a graphics card in a DELL laptop.
MyPaint 1.0.0 is much faster with the same backgrounds.

**Comment by achadwick** [comment]
@journey-of-code
[MyPaint v1.21](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now available. Can you please download and install, and test to see whether this bug is still present in it? Thanks.

**Comment by journey-of-code** [comment]
@achadwick : Did download and test version 1.2.1+gitexport.bcf5a28d (64-bit).
There is now **no noticeable difference** in lag when I switch the backgrounds as discussed above.
Compared to 1.0.0, the time of ink to screen is still slower, but usable.
The difference is most obvious when filling with fast pen-strokes.
If you are interested, I could go into more detail - for example I don't know if the version of 1.0.0 is 64 or 32 bit.
But I'm pretty happy with 1.2.1 also if that is not addressed. :-)
Keep up the good work.
