### ISSUE TITLE
Cannot drag sidebar tabs to anywhere outside their own group under GTK 3.20.4

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#682]
Pretty simple.. wouldn't be surprised if this was an unintended result of the fix for #643. 
What happens is:
1. Drag tab
2. Things appear to work as usual as long as the drag is in the same tab bar
3. As soon as the cursor leaves tab bar, the drag is literally thrown away (blank 'drag' block slides rapidly back to original location)

I think we are supposed to be able to copy/move brushes via DND between brush groups? That is also, definitely broken (simply does nothing at all -- drag doesn't even start.)

Platform details
=============

* Arch Linux x86_64
* GTK 3.20.4
* monoprice 12" tablet, using
* libinput driver for xorg version 0.19.0 , on
* xorg version 1.18.3

**Comment by achadwick** [comment]
Reproduced on Debian with GTK 3.20.4. Also I can confirm that this is *introduced* by merely upgrading 3.20.3 → 3.20.4.

**Comment by achadwick** [comment]
This isn't a problem with MyPaint: it's reproducible with https://gist.github.com/achadwick/1b3505beb47d65fedfd6

**Comment by achadwick** [comment]
Reported upstream: <https://bugzilla.gnome.org/show_bug.cgi?id=766656>. Please subscribe there.

**Comment by achadwick** [comment]
Seems it's already fixed upstream too, my search-fu is eluding me today :smile: 

https://bugzilla.gnome.org/show_bug.cgi?id=766442
