### ISSUE TITLE
MyPaint 1.2.0 stable does not launch: "python2w.exe has stopped working": possible conflicts with prior install of Windows Python

### ISSUE THREAD

**Issue by LordMystirio** [mypaint/mypaint#687]
# **Description of the problem**

Hello,

 I've been trying to open MyPaint (both 32 and 64 bit versions) on my new laptop without success.

I don't have much technical skills but based on what I've been told on the forum ( https://community.mypaint.org/t/mypaint-wont-start/362/6 ) it seems to have something to do with Python.

Here are some screenshots:
-Python vers.
-Bug MyPaint 64bit
-Bug MyPaint 32bit

![screenshot_99](https://cloud.githubusercontent.com/assets/19631087/15631709/a6000fce-256e-11e6-98cd-6b6a93313972.png)
![screenshot_98](https://cloud.githubusercontent.com/assets/19631087/15631710/a602bd00-256e-11e6-9193-20dae3dd4187.png)
![screenshot_91](https://cloud.githubusercontent.com/assets/19631087/15631720/4b4ec132-256f-11e6-95e4-db5c05781d85.png)

**# Basic system details**

MyPaint version: [✍ 1.2.0 stable 64bit and 1.2.0 stable 32bit, …] Operating system: [✍ Windows 7 Edition Intégrale SP1, …]

# **Steps to reproduce**

1. Try to launch MyPaint
2. ERROR _ It won't launch (see screenshots)

# **Backtraces or error messages**

(see screen captures)

**Comment by achadwick** [comment]
That's strange. @tumagonx, does 1.2.0 stable use the python2w.exe trick? I thought it was a single .exe.

I think I was wrong about your other Python install interfering. But uninstalling it would be a thing to try. I don't want to ask you to do that immediately though.

@LordMystirio Can you please try uninstalling all versions of MyPaint, then cleaning out `c:\Program Files` and `c:\Program Files (x86)` to make sure there are no folders called MyPaint any more? The names may be different on non-English-language Windows, I'm not sure.

Then install MyPaint 1.2.0 again from its release page: https://github.com/mypaint/mypaint/releases/tag/v1.2.0

After this, does MyPaint launch properly?

**Comment by LordMystirio** [comment]
@achadwick : I will try that and let you know. :)

**Comment by achadwick** [comment]
Okay, first let's rule out a config issue.

**1.** Follow the procedure at https://github.com/mypaint/mypaint/wiki/FAQ-Factory-reset then try to start that MyPaint 1.2.0 installation again.

  * Does MyPaint now start? If it does, please tell us.

**2.** If not, try the same careful uninstall again (go to _Add and Remove Programs_ and remove all traces, then go to `c:\Program Files` and `c:\Program Files (x86)` and remove all traces from there)

  * Then install from https://github.com/mypaint/mypaint/releases/tag/v1.2.1-beta.1 - any difference to whether it starts?

  * This version comes with a **MyPaint w64 (console debug)** launcher. Any error messages towards the end of that console stuff?

You can paste machine-type error messages into Github to make them searchable for other people. The console debug mode is very verbose on normal operation, but for a crash only the last 20-30 lines really matter normally.

When pasting long error messages, you can format long stanzas of output between "3 backticks" lines:

    ```
    (long error
    message lines
    go here)
    ```

This makes things clearer to read. Don't forget the Preview tab ↑ :smile:

**Comment by LordMystirio** [comment]
Hi here,

Sorry for the late reply. I simply wanted to make sure I've tried everything.

I followed your instructions (many times actually) but no matter how many times I tried, I can't find "mypaint" folder inside my "%LocalAppData%\" or "Documents and Settings\YOURUSERNAME\" either.  There are many other softwares but not MyPaint. 

I then decided to "directly" search for settings files but samething. It's as if mypaint files and folders are only in Programs (instalation folder) and Downloads (where I downloaded it). 

I don't know what else to do.

**Comment by achadwick** [comment]
@LordMystirio Okay - and just to confirm, you didn't have to uninstall Python or anything?

(I think we're not going to be able to wring a bug report out of this one, but hopefully the approaches you've tried can help other people searching).

**Comment by LordMystirio** [comment]
I confirm that nothing execept MyPaint was uninstalled.
