### ISSUE TITLE
Syntax Error Crash: from __future__ imports must occur at the beginning of file

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#695]
#### Description of the problem
@QuLogic 

This is causing an error upon launch as of 3731fd598970b3756c0c2f944792ba54e7f21601 on Ubuntu Gnome 16.04.

```
  File "./mypaint", line 29
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file
```

#### Basic system details

MyPaint version: 3731fd598970b3756c0c2f944792ba54e7f21601
Operating system: Ubuntu Gnome 16.04
Hardware Information: https://gist.github.com/odysseywestra/a3539a28364308d336ca
Desktop environment: Gnome Shell

#### Steps to reproduce

1) Build commit 3731fd598970b3756c0c2f944792ba54e7f21601 from source
2) Launch MyPaint via the Terminal
3) This Error should pop:
```
  File "./mypaint", line 29
    from __future__ import print_function
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by QuLogic** [comment]
Hmm, I guess Travis doesn't test installed files. Fortunately, in this case, I don't think that `__future__` import is strictly necessary; we can remove it temporarily until the scons versioning is updated.
