### ISSUE TITLE
Groups don't propagate properties to children

### ISSUE THREAD

**Issue by danpla** [mypaint/mypaint#699]
You can make a group invisible or lock it, but it will still be possible to change its children: paint, move, fill etc.

It should be possible for any item in a stack to somehow access the topmost group (but *not* the root stack itself) to return the right values from `visible`, `locked` and other properties. This also means that a group should *not* change properties of its children.

Krita can be used as a reference.

**Comment by achadwick** [comment]
Please report affected versions.

Confirmed in 1.3.0-alpha at 0d50ea7 that it is possible to **draw** on a layer inside a non-visible group. Obviously, the changes are only shown when the group is made visible again. It is **NOT** possible to move such a layer, and the cursor is correctly shown as a "forbidden" cursor.

Confirmed in 1.3.0-alpha at 0d50ea7 that is possible to **draw** on a layer inside a locked group. Changes are rendered immediately. It is also possible to **move** such a layer.

Groups already do not change the properties of their children.

**Comment by achadwick** [comment]
We already have UI for "not showing because a parent group is hidden":

![image](https://cloud.githubusercontent.com/assets/61299/15751715/f6b3f2ec-28e2-11e6-9f4d-3991454b1a7a.png)

There should be similar for "not modifiable because a parent group is locked". But there isn't.

**Comment by achadwick** [comment]
Enforcement is going to be tricky. Testing several parent layers on each input event is a bad idea.

Modes like Freehand, line modes, fill, and move will need to update themselves in response to changes of the current layer, and changes of the locked and visible statuses for any layer. Both are exposed on (broadcast via) the root group IIRC. Our `@event` decorator allows transient observation without GC-breaking reference loops.

IMO it is wrong for the model to enforce this. The view should instead be made properly responsive to model changes instead.

**Comment by achadwick** [comment]
Stuff like the symmetry axis and the frame doesn't reside on any layer really, so those modes shouldn't be locked out depending on what you're looking at.

**Comment by danpla** [comment]
It looks like we can use `RootLayerStack.layers_along_path()` like in [gui/layermanip.py#L209](https://github.com/mypaint/mypaint/blob/0d50ea7b78c82050afd83f1d829afd6a17184061/gui/layermanip.py#L209). We can also add a helper method for convenience, something like `path_is_editable()`, to use with tools instead of direct access to `visible` and `locked` properties.
