### ISSUE TITLE
Actions are not sorted correctly in the keyboard shortcut settings

### ISSUE THREAD

**Issue by bluss** [mypaint/mypaint#700]
#### Description of the problem

Actions are not sorted correctly in the keyboard shortcut settings

#### Steps to reproduce

1. Start MyPaint
2. Use some interesting interface language like Swedish
3. Go to Settings -> Keyboard shortcuts
4. Actions are sorted with actions beginning with Ä first (which is incorrect). *Alfa låst* should be the first one alphabethically.

The bug is due to the table being sorted by the markup string, where Ä is XML-escaped so the locale sensitive sort can not work.

**Comment by odysseywestra** [comment]
Related to #642 and [this thread](https://community.mypaint.org/t/add-support-for-auto-detecting-keyboard-layouts/319) on the Community Forums.

**Comment by achadwick** [comment]
@odysseywestra Looks more like a localization issue. There should be a hidden column in the model for sorting properly, I think, like we do for searching.

It needs to be a [language-aware sort](http://www.unicode.org/reports/tr10/) as well, otherwise Å won't come before Ä.

The column and model setup code is in [gui/accelmap.py](https://github.com/mypaint/mypaint/blob/3731fd598970b3756c0c2f944792ba54e7f21601/gui/accelmap.py).

**Comment by bluss** [comment]
I'd expect does locale based sorting by default.

**Comment by achadwick** [comment]
Halfway there. We no longer sort on markup.

@bluss
I'd think so too, but no:

![image](https://cloud.githubusercontent.com/assets/61299/15806319/8f9158a4-2b38-11e6-8660-807364e41b25.png)

**Comment by achadwick** [comment]
↑ Wait, I'm being a monoglot again and making myself ridiculous :stuck_out_tongue_winking_eye:

The screencap above is with `LANGUAGE=sv_SV`.

The screencap below below is with `LANG=sv_SV`, and illustrates correct behaviour for the [Swedish alphabet](https://en.wikipedia.org/wiki/Swedish_alphabet) (ABC...XYZÅÄÖ):

![image](https://cloud.githubusercontent.com/assets/61299/15806333/facf9978-2b38-11e6-9018-0aaecb33aa89.png)

Here's why that was happening:

```
$ LANGUAGE=sv_SE locale
LANG=en_GB.utf8
LANGUAGE=sv_SE
LC_CTYPE="en_GB.utf8"
LC_NUMERIC=en_GB.utf8
LC_TIME=en_GB.utf8
LC_COLLATE="en_GB.utf8"
LC_MONETARY=en_GB.utf8
LC_MESSAGES="en_GB.utf8"
LC_PAPER=en_GB.utf8
LC_NAME="en_GB.utf8"
LC_ADDRESS="en_GB.utf8"
LC_TELEPHONE="en_GB.utf8"
LC_MEASUREMENT=en_GB.utf8
LC_IDENTIFICATION="en_GB.utf8"
LC_ALL=
$ LANG=sv_SE locale
LANG=sv_SE
LANGUAGE=
LC_CTYPE="sv_SE"
LC_NUMERIC=en_GB.utf8
LC_TIME=en_GB.utf8
LC_COLLATE="sv_SE"
LC_MONETARY=en_GB.utf8
LC_MESSAGES="sv_SE"
LC_PAPER=en_GB.utf8
LC_NAME="sv_SE"
LC_ADDRESS="sv_SE"
LC_TELEPHONE="sv_SE"
LC_MEASUREMENT=en_GB.utf8
LC_IDENTIFICATION="sv_SE"
LC_ALL=
```

Sort order is determined by `SE_COLLATE` now, when it's set. This is the correct behaviour.

**Comment by achadwick** [comment]
Backported and tested on v1.2.x.

**Comment by bluss** [comment]
Thank you. Indeed, LANG must be set to a locale that's generated and existing, depending on distro it might not generate them all.
