### ISSUE TITLE
ubuntu snap

### ISSUE THREAD

**Issue by pixelr0** [mypaint/mypaint#705]
not an issue really, more like a wish/request 

i already have the krita 3.x snap and it works pretty good, a mypaint snap would be a nice thing to have 

that's all.

**Comment by odysseywestra** [comment]
Actually this had been is being discussed over at our community forums. Please continue the conversation there. 

https://community.mypaint.org/t/distributing-mypaint-as-an-appimage-and-or-snap-package/233/7

**Comment by probonopd** [comment]
[This pull request](https://github.com/mypaint/mypaint/pull/740), when merged, will generate and upload an [AppImage](http://appimage.org/) of each commit. It does so by bundling MyPaint, Python, and the required Python modules inside the AppImage.
