### ISSUE TITLE
centos: display of text on buttons is broken.

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#708]
#### Description of the problem

Display of **button text** is broken.
![image](https://cloud.githubusercontent.com/assets/2767425/16175923/c8589b0e-361c-11e6-9b4f-f12ceab959ef.png)

Its looking fine in few like **Recover interupted work?** on startup and **About MyPaint** Where buttons don't  have icons.

![mypaintbuttontext2](https://cloud.githubusercontent.com/assets/2767425/16175964/45074a96-361e-11e6-8ab0-5f3ac3c803c3.jpg)

#### Basic system details

MyPaint version: [v1.2.1-beta.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1-beta.1)
Operating system: CentOS Linux release 7.2.1511 (Core)
Desktop environment: KDE - 4.14.8

#### Steps to reproduce

1. Start MyPaint
2. Open any dialog windows like **open**, **Export**, **Save As...**

#### Backtraces or error messages

None, I can see. 

Let me know if any additional info needed.

**Comment by achadwick** [comment]
What GTK theme is this?

Please show me a screencap of similar buttons in gtk3-demo or (better still) gtk3-widget-factory.

**Comment by achadwick** [comment]
Suspect that this is yet another theming bug, like #158 or #665.

**Comment by cg-cnu** [comment]
Yes, its because of the oxygen theme. Switching to a different theme fixed the issue.

**Comment by achadwick** [comment]
@cg-cnu Do you have a screenie or some confirmation that it's happening in another GTK3 app?

**Comment by cg-cnu** [comment]
@achadwick I don't have any GTK3 apps on my centos except mypaint. I am sure that's the issue with the oxygen theme. If I come across any other app, will send the report.
