### ISSUE TITLE
choose app style with flag

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#709]
Oxygen seems to be buggy and breaking mypaint in lots of places.
While I can shift from oxygen to another style, It would be great if we have the option to choose the style on app launch. 

Its not a new idea, [natron](http://natron.fr/) is having similar problems and they have implemented a work around. A CLI flag like  `` -style Plastique `` would launch natron in plastique, even though the global settings are in oxygen.
 
Not sure how much work it would be, just throwing in the idea. Cheers!

**Comment by achadwick** [comment]
IMO the Oxygen team need to fix their bugs, if that is indeed the source of the trouble. The most convenient method for users to work around the problems with Oxygen (#665 , #158 , #707) is to change their GTK theme.

If you want a local, command-line workaround, this is already implemented in all supported versions of GTK. See <https://developer.gnome.org/gtk3/stable/gtk-running.html> and scroll down to `GTK_THEME`. Here is a single command line that meets your requirements:

    $ GTK_THEME=Adwaita mypaint

**Comment by cg-cnu** [comment]
Wow! That fixes the issue. Thanks for the work around :)
