### ISSUE TITLE
crashes when i use the line tool w/ pencile

### ISSUE THREAD

**Issue by lightning386** [mypaint/mypaint#711]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem

[✍ Fill in this section with a clear description of **ONE** problem.]
[☞ Stay on topic. Separate problems go in separate issues.]
[☞ Read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs first.]
[⚠ If you don't give us enough detail to allow us to reproduce your issue, we cannot help and your report will be closed.]
[☞ Check the title is short but useful. It should echo this description.]
[☞ Pictures and videos help us a lot. You can paste screenshots.]

#### Basic system details

MyPaint version: [✍ 1.2.0 stable, 1.2.1-beta.1, git revision NNNNNNN, …]
Operating system: [✍ Debian 8.3, Ubuntu 16.04, Windows 7, …]
Desktop environment: [✍ GNOME, Xfce, …]

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. [✍ second step]
3. [✍ third step]

#### Backtraces or error messages

```
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by achadwick** [comment]
I can't fix this, you provided no information.

Please fill in the form and submit this bug again.
