### ISSUE TITLE
cpu usage constantly reach about 16% in plasma desktop

### ISSUE THREAD

**Issue by mug896** [mypaint/mypaint#716]
#### Description of the problem

cpu usage constantly reach about 16% in plasma desktop.
If i turn off compositor in plasma desktop setting pannel then problem disappear.
#### Basic system details

MyPaint version: 1.2.1-beta
Operating system: Ubuntu 16.04
Desktop environment: plasma desktop

**Comment by achadwick** [comment]
@mug896 
- Which beta? 1.2.1-beta.1 or 1.2.1-beta.0 ?
  - Please paste what you see in Help -> About MyPaint, including the GTK and other libs versions if you see them.
- What hardware are you using?
- Have you tried under Xfce with the compositor turned on/off, or under GNOME? Please do if you can.

**Comment by achadwick** [comment]
Alternatively, I'd love some **minimal** profiler output comparisons, like in #675. See the "steps to reproduce" there too. If it's doing way too much "pixbuflist:\<blah\>:drawcb" that might be the source of this slowdown, and you might be seeing an duplicate.

**Comment by mug896** [comment]
Here is the information i can see in Help -> About

> 1.2.1-beta.1+gitexport.3198e3f

but i can't see  GTK and other libs versions. how could i see that informations ?

>Im using Intel HD Graphics 3000 

and i have just tried under ubuntu 16.04 Xfce and the result is the same.

if i minimize window then cpu usage drop down to zero in both desktop manager.

**Comment by achadwick** [comment]
Hello - is this still happening?

Please can you re-test on either the `master` or the `v1.2.x` branches? #675 is fixed now, and its fix seems applicable to the exact version of Ubuntu you are using.

**Comment by mug896** [comment]
I have upgraded my linux box to Ubuntu 16.10 
 
and there is no such problem happening any more
 
I'm still using 1.2.1-beta.1+gitexport.3198e3f 


 
-----Original Message-----

**Comment by achadwick** [comment]
Closing as not reproducible.
