### ISSUE TITLE
MyPaint crashed whitescreening laptop while working on an .ora, .ora can no longer be opened

### ISSUE THREAD

**Issue by mamong-gwapo** [mypaint/mypaint#725]
I had a lot of programs opened in the background, MyPaint included. I guess the workload became too much and my laptop whitescreened while I was working in MyPaint. An error message popped up before it did this but it appeared too fast and I wasn't able to read it. I had saved the .ora before my laptop suddenly shut off though. When I tried to open the file again, a programming error pops up and it wouldn't let me open or work on the .ora.

The Error says this:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\MyPaint\library.zip\gui\filehandling.py", line 333, update_preview_cb(no details)
                filename = filename.decode('utf-8')
                pixbuf = helpers.freedesktop_thumbnail(filename)
                if pixbuf:
  File "C:\Program Files (x86)\MyPaint\library.zip\lib\helpers.py", line 168, freedesktop_thumbnail(no details)
                # use the largest stored thumbnail that isn't obsolete
                pixbuf = gdk.pixbuf_new_from_file(fn)
                if file_mtime == pixbuf.get_option("tEXt::Thumb::MTime"):
GError: Failed to load image 'C:\Users\Monique\AppData\Local\mypaint\thumbnails\large\8996ba703d2c729bae09f36988f16d7e.png': Image has zero width
```

I've tried opening it with Gimp but it also failed to open it.
Help? I work on MyPaint 1.2.0 with a Windows 10 hp laptop.

**Comment by achadwick** [comment]
Oho, it looks like the thumbnailing code isn't handling exceptions when it encounters a corrupt file *in your FreeDesktop thumbnail cache area*. That's a bug; MyPaint should probably handle that more gracefully!

@mamong-gwapo 
Was this happening when you were clicking around in the file open dialog, just to give me an idea of when it happened?

----------------------

*In general*, this issue tracker is not for direct user support, but that's a flexible rule. Normally we recommend the [MyPaint Community Forums](http://community.mypaint.org/) for support, or Twitter ([@MyPaintApp](https://twitter.com/MyPaintApp), #mypaint), but it looks like you found a lurking bug here. Thank you so much for the backtrace! It means we can address this issue on two fronts: user support and bug fixin'!

@mamong-gwapo 
Can I ask you to make a backup copy of the OpenRaster file you are trying to open first, just as a matter of safety? It *might* be that it's corrupt, and needs some manual repacking to make it work properly.

**Comment by achadwick** [comment]
On the user support front: @mamong-gwapo, please open `C:\Users\Monique\AppData\Local\mypaint\thumbnails\large` in Windows, and delete the file named `8996ba703d2c729bae09f36988f16d7e.png` in there. This is the corrupted cache file I mentioned, and it isn't important.

You can get rid of the entire `C:\Users\Monique\AppData\Local\mypaint\thumbnails` folder if it's easier :smile: 

It is possible that the file you were trying to open is corrupt as well. I hope not, but getting rid of the faulty cache file should at least allow you to open it if it's OK.

**Comment by achadwick** [comment]
On the bug fixing side: we could make the [update_preview_cb() method](https://github.com/mypaint/mypaint/blob/6cc3d2b737b6aa452d74db1efdfca7d9b33c94c4/gui/filehandling.py#L687) handle the exception, and it looks as if it could be made to show a useful "no preview available" image in place of the preview too.

However it looks as if helpers.freedesktop_thumbnail() might be a better place to handle the GError. It looks as if it's supposed to return None in the case where the thumb couldn't be loaded. Let's make [the erroring call](https://github.com/mypaint/mypaint/blob/6cc3d2b737b6aa452d74db1efdfca7d9b33c94c4/lib/helpers.py#L273) use [our wrapper](https://github.com/mypaint/mypaint/blob/6cc3d2b737b6aa452d74db1efdfca7d9b33c94c4/lib/pixbuf.py#L77) instead, but handle exceptions itself (by logging them and carrying on to return None, or regenerate the thumbnail).

**Comment by achadwick** [comment]
Underlying error is fixed on master and for the upcoming point release.

**Comment by achadwick** [comment]
@mamong-gwapo 
I have to treat your report primarily as a bug report in this place, and the underlying bug is now fixed. I hope you are able to manually repair/delete that thumbnail cache using the information above.

Deleting the thumbnail cache folder should help.

If you still cannot open the `.ora` file, it may still be corrupt. If it is, you may get somewhere by renaming it to `<whatever-you-called-it>.zip`, and seeing whether its layer data can still be salvaged by opening it in Winzip or Explorer. You'll have to [turn off "hide extensions for known file types"](https://support.microsoft.com/en-us/kb/865219) to do this. I don't know where the setting lives in Windows 10, that's a Win7-era link.

Don't forget to make backups first if you're rummaging around inside your .ora file ☺ And good luck.
