### ISSUE TITLE
unable to build mypaint via readme

### ISSUE THREAD

**Issue by pingpong2011** [mypaint/mypaint#727]
I'm trying to build mypaint 1.2->git via the readme (readme in the 1.2 zip version), on a Raspberry Pi 3. I don't think the Raspi3 is the issue though:

I get to the spot where I should do "git submodule update --init --force" and the command is silent. Then I do "scons", and I get an error that "Package libmypaint was not found in the pkg-config search path." and "No package 'libmypaint' found" and then a whole bunch of errors relating to libmypaint.

**Comment by briend** [comment]
Those seem like old instructions.  You'll want to build and install libmypaint first:
https://github.com/mypaint/libmypaint
then build mypaint.
Actually just read this:
https://github.com/mypaint/mypaint/blob/master/README_LINUX.md

:-)

**Comment by achadwick** [comment]
Those are old instructions. Please use the link above with "master" in the path to guild the master branch on git :smile: 

(The big change is that `libmypaint` is now built as a separate entity, hence [pkg-config](https://en.wikipedia.org/wiki/Pkg-config))
