### ISSUE TITLE
Expand (or shrink?) pixel option for the fill tool

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#73]
Krita has an option for its fill tool to expand the area which the bucket tool fills, and it would be a godsend to have the same feature in MyPaint (even if it's maximum range is about 10 pixels or something)
It would also be fantastic if MyPaint could be the first software to implement some sort of "taper fill" feature?

**Comment by achadwick** [comment]
**Triage note:** needs patch, an algorithm, or a pointer to some code. Also, this may be outdated if the goal is to "make it work like Krita": it appears that Krita is changing the way their bucket fill implementation works (#296), so perhaps that's a better way of doing it. Let's see what they do!

This one could be a candidate for an improved MyPaint fill implementation, but like #150 or #296 we still need pointers to some real code to evaluate whether it's a good fit for MyPaint and fo make comparisons.

Let's review this after 1.2 is released, and decide whether to drop it then. And close as WONTFIX if no code links are forthcoming by then.

**Comment by achadwick** [comment]
@freelanceear writes in #443:
> Bucket fill would be a useful tool if you could grow the fill by 1 or 2 pixels so it properly fills things. As it is, even with finely-tuned tolerance, I always end up with a 1-pixel line of empty space. My workflow is to create clean edges with the inking tool, fill the shapes with bucket fill, then paint in detail with lock alpha channel. Having to remove the 1-pixel line for each shape really slows me down. I'm not good with code, but the process would probably be:
> -determine where to fill
> -grow the determined region by 1 pixel (similar to how GIMP lets you grow selections)
> -fill
> For UI, a tick box in the bucket fill options panel would work.
