### ISSUE TITLE
Jagged lines on surface Pro 2 

### ISSUE THREAD

**Issue by RailRanger** [mypaint/mypaint#739]
MyPaint version: [ 1.2.1-beta.1,x64]
Operating system: Windows 8.1 64

I have a Surface Pro 2, lines are very unsmooth in My Paint. I tried the 32bit and 64 bit releases of 1.2.0 and 1.2.1, same problem on both.

I have tried with and without the wacom feel driver, it made no difference. Other programs are fine like Photoshop and Mischief.

Here is a picture of the input panel:
https://dl.dropboxusercontent.com/u/46294175/pictures%20random/probleminputwacom.PNG

Any help would be really helpful, thank you.

**Comment by achadwick** [comment]
Is this a pixel brush? It might just be working as designed, they're slightly strange, those.

Please tell me which brush this is (and try others, really pressure-sensitive ones that aren't pixel-edged things), and try to explain the issue more thoroughly. I'm still confused about what's going on here. It could also be that the input driver is sending incorrectly scaled pressure values, so you only get a handful of possible numeric pressures between 0.0 and 1.0. That's consistent with your screenshot too  :confused:

If you're able to install MSYS2 and gtk3-demo (it's in the architecture-specific "gtk" package) that would be informative. If it's a "notchy pressure thing", it'll affect other programs using libgdk.

Photoshop and Mischief probably use have smarter ways of interfacing with tablet drivers than GTK/GDK, which unfortunately is a bit stone-age in that area.

**Comment by achadwick** [comment]
@RailRanger 
Please respond.

[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) was released recently. Please test it out, and let me know whether this problem is still happening.

**Comment by RailRanger** [comment]
Yes it appears to be much smoother in the new 1.2.1, thanks a lot!

**Comment by achadwick** [comment]
@RailRanger 
Thanks!

For future people reading this: MyPaint v1.2.1 shipped with GTK 3.22.7 on Windows.
