### ISSUE TITLE
Brush field to notes - use and design 

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#74]
I'm studying the new possibilities of the MyPaint brushes to emulate wet glazing (mix including) and some impasto qualities. During the design sessions I've saw that will be interesting to have a field to make the notes about the brush. Is possible to have this field on Brush editor?
To see some samples of these experiments:
https://plus.google.com/104948482158719711754/posts/6ou6E2XYby8
https://plus.google.com/104948482158719711754/posts/Do3ctxtMRb6
https://plus.google.com/104948482158719711754/posts/XCC1QBPvWES
https://plus.google.com/104948482158719711754/posts/115w8jnUwAC [short video]

**Comment by americogobbo** [comment]
I think that the two issues opened by me are #74 and #102 can be thought together... are two aspects of the same instance... control, editing and brush design. My suggestion is to have a great textarea to write the design notes of each brush... this text will be embedded or linked to the brush. When the parameter not in default place is set with bold [#102] is easy identify and to write the notes to help the maintenance of brushes and sets.

**Comment by achadwick** [comment]
![screenshot from 2015-04-15 00 59 01](https://cloud.githubusercontent.com/assets/61299/7149857/b8f366d2-e30a-11e4-912c-4bbff83dd413.png)

This is kinda going to need #102 to be fixed as well before it's useful. It's way to easy to switch bush and lose the text being edited (!)
