### ISSUE TITLE
Appimage builds from Travis are broken

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#742]
Our build's invocation of the Appimage stuff is failing. Example build failure (from https://travis-ci.org/mypaint/mypaint/builds/175674973#L6346):

```
[...]
Resolving github-cloud.s3.amazonaws.com (github-cloud.s3.amazonaws.com)... 54.231.50.50
Connecting to github-cloud.s3.amazonaws.com (github-cloud.s3.amazonaws.com)|54.231.50.50|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 440600 (430K) [application/octet-stream]
Saving to: ‘appimagetool’
100%[======================================>] 440,600     1.28MB/s   in 0.3s   
2016-11-14 11:24:00 (1.28 MB/s) - ‘appimagetool’ saved [440600/440600]
+chmod a+x ./appimagetool
+set +x
This doesn't look like a squashfs image.
Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/probonopd/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

As of 0b7a3db6af146196c94b4b956a2957f0882e1c47 I have had to appended "|| true" to the Travis invocation of our Appimage, so that the Travis checks can still be useful.

@probonopd can you help out? Please comment here and I will assign this issue to you. I'm afraid I do not have time to debug or maintain code I do not run and therefore cannot test, so you are de facto maintainer of this code for now.

**Comment by probonopd** [comment]
It is not your fault. The latest build of
https://github.com/probonopd/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
is broken (also on my local system).
I will revert the latest change on https://github.com/probonopd/AppImageKit.

**Comment by achadwick** [comment]
No problem. I'll keep the appimage generation as an additional nice thing to have on the end, but keep it so that it doesn't fail the build.

**Comment by probonopd** [comment]
Should be working again, can you confirm?
