### ISSUE TITLE
Chocolatey repo

### ISSUE THREAD

**Issue by tauraamui** [mypaint/mypaint#747]
I would like to make a repo for Chocolatey for this program

**Comment by achadwick** [comment]
Thank you for the offer. How would that work? Just wait for releases, or do you need to contribute anything to the MyPaint codebase? Do you need me to make a repository on github for you?

**Comment by achadwick** [comment]
@tauraamui 
Please respond. How do you intend to do this?

**Comment by tauraamui** [comment]
Sorry, I've been really busy :( I was intending to follow the standard steps suggested on Chocolatey's FAQ. I haven't created a repo before, but I think we just need to provide a universally accessible HTTP/HTTPS URL to download the installer

**Comment by achadwick** [comment]
Can I leave it with you, and will you update this issue if I assign it to you? I don't have time to do this.

**Comment by tauraamui** [comment]
Yeah that's fine

**Comment by achadwick** [comment]
@tauraamui 
Done, let me know what needs to be done at our end. The file download will be hosted on github, same as now.

You are now the Choclatey maintainer for MyPaint. Please can you add the details of your packaging efforts to <https://github.com/mypaint/mypaint/wiki/Packaging>?

**Comment by tauraamui** [comment]
Yeah sure, once I've got something working and tested

**Comment by luzpaz** [comment]
Maybe we can make a push to get 1.2.2 in to chocolatey, when it's released ?

**Comment by jplloyd** [comment]
Repeating myself from my comment in the issue referenced above: MyPaint 1.2.2, *if* it were released, would be linux-only (as it only changes installation layout). Unless specifically installation layout was what was holding up this effort, that potential release has no relevance here.

@tauraamui Did you give up on this effort? Were there any particular difficulties that maybe could be addressed on our end?

**Comment by digitalcoyote** [comment]
I've got a repo for automatically pushing package updates. I could add this to my list and build a package for it. Unless someone is still working on it (looks like the last mention of progress was from early 2017)

**Comment by luzpaz** [comment]
@digitalcoyote go for it!

**Comment by digitalcoyote** [comment]
Package should be submitted for review by Chocolatey moderators. If anyone who is a maintainer for this project has a Chocolatey account, adding them as a maintainer of the package would give them management rights (push manual updates) and adds credibility to the package. 

Also, until the first automatic version is approved, I cannot manually submit the stable version (auto-updater pulls latest version). So the current version awaiting moderation requires the ` --pre` switch to be installed. As soon as I get word that they have approved it, I'll try get the stable version packed and pushed to Chocolatey.

**Comment by digitalcoyote** [comment]
Pre-release package (v2.0.0.0-Alpha-12) is live on Chocolatey. I'll try to push the stable version soon.

**Comment by jplloyd** [comment]
@digitalcoyote Thanks for getting this off the ground!

Looking at the files, it appears that what the packages do is basically downloading and running the installers from fixed releases on github. Is there more to it than that?

One thing I noticed is that the stable release only uses the installer for the 32bit release. I'm assuming it's possible to specify which version to download/install depending on whether the users OS is 32bit or 64bit?

**Comment by digitalcoyote** [comment]
I actually pushed that one manually and it appears I left out the 64-bit url. It's not approved yet, so I should be able to push one with both that will replace that one.

**Comment by digitalcoyote** [comment]
After looking back, I realized it would have completely overlooked 32-bit releases moving forward. I added some logic to check for a 32-bit release when updating and use a script that includes that installer if it exists.

**Comment by jplloyd** [comment]
> After looking back, I realized it would have completely overlooked 32-bit releases moving forward. I added some logic to check for a 32-bit release when updating and use a script that includes that installer if it exists.

Nice! The next preview release will have 32-bit packages for windows again. There was a problem with the 32 bit builds for a while, but it's since been fixed.

I created an account on chocolatey (same name as my github account) if you want to add another maintainer. I don't know if it lends any credibility or affects the review process, but a bus factor of 1 is always a risky thing.

**Comment by jplloyd** [comment]
Main package passed review at the end of October.

@digitalcoyote 
The prerelease is still alpha 12, as opposed to 13, if you want to look into updating that.

Ideally updates of prereleases should be automated, but other than that I think this can be considered done.
