### ISSUE TITLE
Can we please get a x64 build for Win?

### ISSUE THREAD

**Issue by gerroon** [mypaint/mypaint#748]
Hi

Can we please get a x64 build for Windows? The last one is 9 months old and the most recent version was pulled out of releases due to signature issues.

I am using 64 bit version of wintab and I would like to try it with that version.

thanks

**Comment by achadwick** [comment]
Duplicate of #578. Expect this to be fixed when 1.2.1 is released, no sooner.

**Comment by achadwick** [comment]
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now out, and contains a w64 installer and an experimental standalone bundle containing the same files.

**Comment by gerroon** [comment]
yaayyyyy thanx man
