### ISSUE TITLE
Segfault MyPaint 1.3.0-alpha+git.2c07a27b

### ISSUE THREAD

**Issue by DigitalKO** [mypaint/mypaint#752]
#### Description of the problem
Get Segfault when click on the title bar of the Input Device Test window, and crash Gnome Shell.

#### Steps to reproduce
1. Choose from the menu:
2. Debug > Test Input Device
3. Then click on the title bar, with mouse or stylus

![screenshot from 2016-12-15 21-27-30](https://cloud.githubusercontent.com/assets/24569830/21241313/59dece8e-c30f-11e6-9d94-6ddd4ee4b903.png)

#### Basic system details

MyPaint version: 1.3.0-alpha+git.2c07a27b
Operating system: Debian SID
Desktop environment:GNOME 3.22

#### Backtraces or error messages

```
Dec 15 21:27:33 debian kernel: python2.7[2998]: segfault at 0 ip 00007f70b4df9129 sp 00007fff19b19570 error 4 in libwayland-client.so.0.3.0[7f70b4df3000+d000]
```

**Comment by achadwick** [comment]
Wayland or Xorg?

Please install all relevant dbgsyms packages and supply a backtrace with gdb. We have instructions here on the wiki. They're heavily Windows/MSYS2-inflected, but the tools we use are the same: https://github.com/mypaint/mypaint/wiki/Debugging-crashes-on-Windows#running-gdb

(You might have to get a bit creative and [force it to dump core](http://stackoverflow.com/questions/17965/how-to-generate-a-core-dump-in-linux-when-a-process-gets-a-segmentation-fault) instead, then analyze that in a fresh session.)

**Comment by achadwick** [comment]
Only stylus, or all pointing devices?

The CPython backtrace is essential for understanding this.

**Comment by DigitalKO** [comment]
Desktop environment: GNOME 3.22 under Wayland.
I will try to do what you asked, as soon as I can.
And all pointing devices crashed Gnome Shell.

**Comment by achadwick** [comment]
@DigitalKO 
Just reviewing crasher bugs after the release of 1.2.1 on the stable branch. Is this still happening?

To be honest, if GNOME-Shell (and Wayland?) are crashing too, this sounds like a Wayland issue. It should be reported upstream too if it is still happening.

**Comment by jplloyd** [comment]
Stale Wayland issue. Cannot reproduce with stable release, even when manually disabling the x11 backend (by commenting out the lines below). 

https://github.com/mypaint/mypaint/blob/368862d0831df29bf1696a8f9406e2d41ea0a5f5/gui/main.py#L57-L58
