### ISSUE TITLE
mypaint.org CSS issue

### ISSUE THREAD

**Issue by cprn** [mypaint/mypaint#754]
Your website's CSS assumes font and background themes to be _black-on-white_ by default. Please, consider specifying font and background colour for every style as modern browsers often derive colours from system theme or provide an option to set them manually (e.g. Firefox: _Preferences > Content > Colours..._) rendering your website unreadable in case of _white-on-black_ defaults.

I'm sorry for posting here and if you don't care you can just close the ticket but you have no website specific project so there's no correct way of submitting issues.

**Comment by odysseywestra** [comment]
We actually do have a specific repository for MyPaint's website. You can
post the issue there. I'm also open to any PR if you wish to fix it
yourself. Just remember, the site uses GitHub's web service which uses
Jekyll as the backbend.

MyPaint.org repository:
https://github.com/mypaint/mypaint.github.io

**Comment by cprn** [comment]
Sorry, my bad, I somehow missed it. Thank you for correcting me.
