### ISSUE TITLE
No Release File on MyPaint Testing PPA for Ubuntu 16.10

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#759]
#### Description of the problem

The [MyPaint Testing PPA](https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing) on Ubuntu 16.10 says it doesn't have a Release file for its version. This prevents Ubuntu from installing the Git version of MyPaint.

#### Basic system details

MyPaint version: Ubuntu PPA Version[Git Master]
Operating system: Ubuntu Gnome 16.10
Desktop environment: Gnome 3.20

#### Steps to reproduce

1. Load Ubuntu 16.10 or in my case Ubuntu Gnome 16.10
2. Add the [MyPaint Testing PPA](https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing) with `sudo apt-add-repository ppa:achadwick/mypaint-testing`
3. `sudo apt-get update`
4. Error in `apt-get` should Pop up.

#### Backtraces or error messages

```
W: The repository 'http://ppa.launchpad.net/achadwick/mypaint-testing/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/achadwick/mypaint-testing/ubuntu/dists/yakkety/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

#### Workaround

For now just build from [Source](https://github.com/mypaint/mypaint/blob/master/README_LINUX.md) on Ubuntu 16.10 if you want the Git Version of MyPaint.

**Comment by achadwick** [comment]
Is this only for Yakkety?

**Comment by achadwick** [comment]
(Yakkety is not listed in <https://github.com/mypaint/libmypaint.deb/blob/master/build_ppa_uploads.py#L19>. Time to get that 1.2.1 release out the door. Everyone's nagging at me to get it done.)

**Comment by achadwick** [comment]
@odysseywestra 
[MyPaint v1.2.1](https://github.com/mypaint/mypaint/releases/tag/v1.2.1) is now up on the PPAs, meaning that there should be a yakkety Release file for apt to see. Can you confirm whether or not this bug is still happening please?

**Comment by achadwick** [comment]
@odysseywestra 
Yakkety builds have been uploaded. I assume all is OK.
