### ISSUE TITLE
Bring back 0.8's "straight lines to a point" feature.

### ISSUE THREAD

**Issue by reelance** [mypaint/mypaint#76]
Holding shift + clicking to draw a straight line would draw it to the last point you painted on in 0.8 through 1.0. It doesn't seem like this is possible in 1.1 with the new straight line features and it makes large perspective grids hard to draw accurately and quickly.

This was easy and fast in 0.8 to 1.0:
![oldlines](https://cloud.githubusercontent.com/assets/8432816/3899405/5bd48288-227b-11e4-8740-6d52f84a2e61.png)
This is my best attempt to do it in 1.1. Avoiding fraying on the vanishing points is difficult:
![newlines](https://cloud.githubusercontent.com/assets/8432816/3899404/5bcda4a4-227b-11e4-9d8c-f1b5c1afcaa9.png)

**Comment by odysseywestra** [comment]
Closing this in favour of #152 since it would do what exactly in the scope of this issue and more.
