### ISSUE TITLE
Blank error message when mypaint installed with not latin path

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#767]
#### Description of the problem

![blankerror124r32](https://cloud.githubusercontent.com/assets/13454470/22293329/f8d57fb0-e330-11e6-9c19-38a5b905ad88.jpg)

#### Basic system details

MyPaint version: 1.2.1+gitexport.bcf5a28d (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)
Operating system: Windows 10 x64 1607 14393.693

#### Steps to reproduce

Install MyPaint with not latin path, e.g. C:\ывмвымывм\МайПэинт

**Comment by jplloyd** [comment]
#768 covers the actual problem
