### ISSUE TITLE
Error: Unable to launch bash.exe

### ISSUE THREAD

**Issue by Poputchik** [mypaint/mypaint#771]
**[Edited on @Poputchik's behalf -- @achadwick]**

After installing Mypaint 1.2.1 32bit on windows 7 32 bit program will not run (Error: Unable to launch bash.exe). When you try to run the file bash.exe there is a message that the version of this file does not match the bitness of the system (I understand that the file is not for windows 32 bit). Please check the version bash.exe included in the build Mypaint 1.2.1 32 bit.

**Comment by odysseywestra** [comment]
Please provide information that the template requires please. Otherwise we cannot help you and will have to close the issue. You can edit your original post.

**Comment by Poputchik** [comment]
After installing Mypaint 1.2.1 32bit on windows 7 32 bit program will not run (Error: Unable to launch bash.exe). When you try to run the file bash.exe there is a message that the version of this file does not match the bitness of the system (I understand that the file is not for windows 32 bit). Please check the version bash.exe included in the build Mypaint 1.2.1 32 bit.

**Comment by zb13y** [comment]
Same issue in the forum.
https://community.mypaint.org/t/error-prevents-launch-win32-version-1-2-1-1/594

**Comment by achadwick** [comment]
From the forums:

> I just loaded version 1.2.1-1 for Windows, uninstalled the old version per instructions, installed the new version, and have tried to launch the program.

> I only get an error message:

> Unable to launch Bash.exe

> Anyone know how to get it working?

And:

> More today: I re downloaded both the standalone version and the installer, win32 to be clear. I then uninstalled MyPaint, as well as Krita since I was to install a newer version of that as well. Then I rebooted the computer.

> I unzipped and tried to start the standalone version, and got the same error.

> I then reinstalled the installer version, same results.

> I then tried every combination available in Win8.1's compatibility mode dialog for both MyPaint.exe and Bash.exe. In every case I either got the same error, or no response at all when I tried to start the program.

> If it helps: I'm running Win8.1 on a Baytrail tablet w/ wacom digitizer: Asus Vivotab Note 8.

> Is anyone else able to run this?

**Comment by achadwick** [comment]
@Poputchik 
When you say:

> there is a message that the version of this file does not match the bitness of the system

I want to see this error message. Please provide the text of this error message.

In the meantime, I will try to make a rebuild.

**Comment by achadwick** [comment]
Okay, egg on face moment. Side-by-side install of msys2-i686 and msys2-x86_64 from <https://msys2.github.io/>:

```
Test User@win7test MSYS ~
$ file /c/msys{32,64}/usr/bin/bash.exe
/c/msys32/usr/bin/bash.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
/c/msys64/usr/bin/bash.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

We bundle (effectively) the /usr/bin/bash.exe from the distribution under which styrene runs because a) it is needed to run the post-install scriptlets that need to be run to adapt the installation to a new root, and b) sometimes the Exec lines in .desktop files are too complex for CreateProcessW()'s tiny mind.

Rebuilding, excuse the noise.

**Comment by achadwick** [comment]
Build done and uploaded for testing. Preview link: <https://filebin.net/9v2pgf9db124r4z2>!

Please can anyone affected by this bug on 32-bit Windows 7 download `mypaint-w32-1.2.1_20170129a-installer.exe` and install it? I want screenshots of any and all error messages, if possible.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

3c3024f062d72bbbab4ba42fa325a962e3958fa9c08098261987008d3334e042  mypaint-w32-1.2.1+20170129a-installer.exe
414f49d4227c19dd54f026e8fbaaa5a8495a80b3ffe3aa5abf6a5ceaac0316a5  mypaint-w64-1.2.1+20170129a-installer.exe
5e0b10ee47ed88b46751cbb454c45f2444f21217dc178df5c0c3fb7dace7b24a  mypaint-w32-1.2.1+20170129a-standalone.zip
a43d61175e69aa592009fb8d56fe6ad53a35ad5bf48c56de606a9fd8ff318a64  mypaint-w64-1.2.1+20170129a-standalone.zip
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEwCOR9Luk8OKyfGv/bjA34Sh4spkFAliOPlEACgkQbjA34Sh4
splmFw/8CIguHChTgIkJP5WfVOdsMSOLRPG+pp8JDguWTUyP2yMk/NOvryZzE9l/
0wsPwHs4gCE8phh5/K4TTk7gOxkV+xOmEdOtUN6qo0ItXrXYwq3Zf+hYvW/Lz41V
yIPn156NTdM9d8uDeCyUtDv473DHQ6kjz/KaVGGnWSxN9iEfHBVtGwA8IjM80fTG
8iI8MW1uX9Tby/vIXHqDi9yEmXVYK7xhx3autTU07xJM9c18XC77RU6WZjNIcywD
t3zyBI5Mlw7mwnl8g60Zb2XG1ZC6XYER8+PTrZVEt5O2jYp/FYKvmuc5FKNFYgin
ETLi1lg2qzWU/x6k3cPkJqCaswHHZuXYN9Jafwp7TW3wXK+w+LuMjzEfG3/Mo46U
Kmoi4GempQZtxZ8NEnuB6mR9lAoWVl2r/LKkMks4RUXRq6QpmmJmYR7t8fXquHtK
vDwFqjcMeTFLKmiUBq+O69T+3/y4U7KZ2bvFjQvp80ibU+TD5lV58XfH6zncutJ+
/q04PMar7fgk+K0HVaCXKYP3H5YUOdQumvOPYKRuW7JBl2MnflTE+BGG5oShUNrj
rjdzLXg4T5LNMh8SoG6NFsJaQbH3LIiJr0lH0jofq+unJ3K/muTkK0KtKMwdpOXb
WU/fFUfhp5LK1SyC7hVWdG1i7A03VC5sxGiZTneDSu3xbYZ+Pjo=
=947z
-----END PGP SIGNATURE-----
```

**Comment by achadwick** [comment]
(Filebin has mangled the filenames. Sigh. Please note the missing `+` if you are verifying the filebin download.)

**Comment by Poputchik** [comment]
After downloading and installing your proposed setup.exe the program is started. Thank you so quickly corrected. Please forgive me, I was not able to timely and qualitatively describe the problem.

**Comment by achadwick** [comment]
@Poputchik
It is no problem, really. Thank you for testing, and the feedback is useful no matter how it's collected!

Updating the release now. This may take some time.

**Comment by achadwick** [comment]
Build tested and updated. I've updated the release like so:

* `mypaint-w32-1.2.1-20170129a-installer.exe` replaces `mypaint-w32-1.2.1-1-installer.exe`
* `mypaint-w64-1.2.1-20170129a-installer.exe` replaces `mypaint-w64-1.2.1-1-installer.exe`
* `mypaint-w32-1.2.1-20170129a-standalone.zip` replaces `mypaint-w32-1.2.1-1-standalone.zip`
* `mypaint-w64-1.2.1-20170129a-standalone.zip` replaces `mypaint-w64-1.2.1-1-standalone.zip`

I'm using dates to identify builds now; it seems more useful to do it that way. The previous two signed SHA256SUM files have been consolidated into `SHA256SUMS-windows-20170129a.txt` which covers all 4 of the above release files.

This bug should now be fixed. Thanks to everyone who reported the issue!
