### ISSUE TITLE
Option to choose language of the program in mypaint.

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#772]
All programs have such option (krita, gimp, inkscape), mypaint must have it too. It something basic that user are expecting for. As i understood there are some limitations with gettext. But such enhancement must be, may be in the future. There was one solution for it https://github.com/mypaint/mypaint/issues/438, but now there are no such option in the setup. Better to create such option in program, not in the setup.

**Comment by achadwick** [comment]
Yes. The "install translations" checkbox has been lost with the transition to Styrene-made installers. That would be a nice feature to have, but it's hard to implement in a really generic way.

Startup order will make this tricky. It is necessary to set the language environment variables before importing GTK.

**Comment by achadwick** [comment]
There's an interesting use case for this on the Windows platform in #795 (and some speculation about using GSettings as our prefs storage backend, but I prefer keeping it simple.)

**Comment by jplloyd** [comment]
Missed this issue before. Language options are now part of the user preferences.
