### ISSUE TITLE
BrushEditor should hide inputs for constants

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#777]
There are 10 or so settings that are "constant" (only their base value is used during drawing).  But Mypaint allows the user to create brush dynamics for these settings, which will be very confusing (and a waste of time) since they are ignored.  I think it shouldn't be too hard to change the building of the interface such that when a constant is encountered, the Brush Dynamics section is not rendered, looking something like this:

![constants](https://cloud.githubusercontent.com/assets/6015639/22634104/08d2ded8-ebe4-11e6-8faa-8620aab25c1d.jpg)

**Comment by achadwick** [comment]
Just pushed a bunch of tidyups which results in...

![image](https://cloud.githubusercontent.com/assets/61299/22671227/185b10a0-ecc5-11e6-8849-3ee2c0dac6cf.png)

Simpler titles and a cleaner look, I think.

**Comment by briend** [comment]
That was quick!  Looks and works great!  Thanks Andrew!
