### ISSUE TITLE
Crash all time when click button interface [Win10, particularly colour palette windows]

### ISSUE THREAD

**Issue by deividhero** [mypaint/mypaint#788]
Hello, when I am using the application and I click on some button interface it crashes. Especially when I try to select the color palette. This prevents me from using the program well. I do not know if it is a problem of my PC or MyPaint but with other applications I have no problem and the tablet works well, as well as the drivers are well installed.

Thanks in advance and **excuse my English**.

**Comment by achadwick** [comment]
Hi there. We have not heard this before.

* What operating system are you using? Windows, Linux, Mac? I am assuming Windows becuase you said "drivers".
* What version of the operating system are you using?
* Did you get MyPaint from <https://github.com/mypaint/mypaint/releases>?
* What version of MyPaint? Please go to `Help`→`About MyPaint` and Ctrl+C/Ctrl-V all the info here.
* When "it crashes", what happens in detail?
* What is your preferred language, and what language does MyPaint use in its menus and other texts?

**Comment by achadwick** [comment]
You can write in your preferred language if it is more comfortable. We'll try to understand.

**Comment by deividhero** [comment]
@achadwick ¡Gracias por atenderme!

**RESPUESTAS**

- Estoy utilizando _Windows 10_.
- 64 bits.
- Sí, es oficial.

> 1.2.1+gitexport.bcf5a28d

> (Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)

- El programa se pone inmediatamente en modo "_No responde_" y la pantalla se pone ligeramente blanca. Finalmente he de forzar el cierre desde el administrador de tareas.

- Español estándar

**Comment by achadwick** [comment]
@deividhero 

1. Please can you test whether the GTK3-Demo tablet test program ("Event Axes"/"Touch and Drawing Tablets") works? It will have been installed with MyPaint v1.2.1.

2. Can you make GTK3-Demo go into "Not Responding" mode by some other method? [We know that the "OpenGL Area" demo is broken - don't try that!]

3. Is there a difference between your a) your computer mouse or trackpad, and b) your graphics tablet?

4. What graphics tablet are you using? We will need the exact model and manufacturer.

-----

/google translate...

> 1. ¿Puede probar si funciona el programa de prueba de tabletas GTK3-Demo ("Event Axes" / "Touch and Drawing Tablets")? Se instaló con MyPaint v1.2.1.

> 2. ¿Puedes hacer que GTK3-Demo entre en modo "No responde" por algún otro método? [Sabemos que la demostración "OpenGL Area" está rota - no intentes eso!]

> 3. ¿Hay alguna diferencia entre su el ratón del ordenador o el trackpad, y su tableta gráfica?

> 4. ¿Qué tableta gráfica está utilizando? Necesitaremos el modelo y el fabricante exactos.

**Comment by deividhero** [comment]
@achadwick 

De acuerdo. Hay novedades, he formateado y he cambiado de sistema operativo a Windows 7 (64) pero sigo teniendo el mismo problema.

1. Ejecuto _gtk3-demo-event-axes_ y puedo comprobar que el lápiz digital de la tableta gráfica funciona correctamente con diferentes tipos de presión. Procedo a las siguientes pruebas...

> **Aplication Class** No sucede nada, el texto se pone en cursiva.
>
> **Assistant** Se abre un cuadro, introduzco una palabra y aplico cambios. Parece funcionar.
>
> **Benchmark** 
>
>  > **Fishbowl:** Todo parece funcionar correctamente a unos fps estables entre 60-50 a mayor cantidad de iconos.
> 
> > ![image](https://cloud.githubusercontent.com/assets/22795898/23609990/074ce1d2-0271-11e7-8f08-492cf10798cf.png)
> 
>  **Builder:** Comprobación de todos los botones. Funciona adecuadamente.
>
>  **Buton boxes:** Comprobación de todos los botones. Funciona adecuadamente.
>
>  **Change Display:** Primer fallo localizado. Cuando pulso el botón "close" el programa deja de funcionar y _gtk3-demo-event-axes_ se cierra. (He realizado varias veces el mismo procedimiento y no varía)
>
> ![image](https://cloud.githubusercontent.com/assets/22795898/23610235/23051f60-0272-11e7-8f87-a98814b1950b.png)
>
> Segundo fallo localizado, no estoy seguro (?). Cuando pulso el botón "Change" de la parte inferior, aparece un texto en la segunda pantalla, hago click pero no sucede nada. Me vi obligado a cerrar _gtk3-demo-event-axes_ a través del administrador de tareas.
>
> ![image](https://cloud.githubusercontent.com/assets/22795898/23610448/c2982d42-0272-11e7-9e8a-52f47b5ee12a.png)
>
> **Clipboard:** Funciona correctamente.
>
> **Color Chooser:** Funciona correctamente.
>
> **Combo Boxes:** Funciona correctamente.
>
> **Cursors**  Funciona correctamente.
>
> **Dialogs and Message Boxes**: Funciona correctamente.
>
> **Drawing Area**: Funciona correctamente.
>
> **Entry**
>
> > Entry Buffer: Funciona correctamente.
>
> > Entry Completion: Funciona correctamente.
>
> > Search Entry: Funciona correctamente.
>
> > Delayed Search Entry: Funciona correctamente.
>
> Expander: Funciona correctamente.
>
> Flow Box: Funciona correctamente.
>
> Foreign drawging: No puedo interactuar con nada.
>
> Gestures: Funciona correctamente.
>
> Header Bar: Funciona correctamente.
>
> Icon View: Funciona correctamente.
>
> > Icon View Basics: Funciona correctamente.
>
> > Editing and Drag-and-Drop: Funciona correctamente.

(Editing post, wait a second)

**Comment by achadwick** [comment]
@deividhero 
There is no need to be absolutely exhaustive. The question was more "please click on several buttons and see if that's just a button breaks" // No hay necesidad de ser absolutamente exhaustivo. La pregunta era más "por favor, haga clic en varios botones y ver si eso es sólo un botón se rompe" :smile:

**Comment by deividhero** [comment]
@achadwick 

Demasiado tarde. De todas formas creo que ésto puede ayudaros a localizar más fácilmente el problema, he tratado de ser lo más objetivo posible.

Revisa de nuevo el post, ahora está completo.

**Comment by deividhero** [comment]
¿Hola? ¿Qué creéis que puede provocar el fallo?

**Comment by ydahhrk** [comment]
> No entiendo muy bien ésta pregunta, pero supongo que no hay ninguna diferencia, quizá la configuración de la tableta es diferente:

Creo que lo que está preguntando es si la tableta es lo que causa el problema.

Si enciendes MyPaint sin tener la tableta conectada, ¿de todos modos estalla?

=================

> I don't understand this question very well, but I suppose there's no difference. Maybe the tablet configuration is different:

I think that he's asking whether the tablet seems to be the cause of the problem.

If you boot MyPaint with the tablet disconnected from the computer, does it blow up still?

**Comment by timbeaudet** [comment]
I was getting this issue and I think the cause is by dragging the pen while selecting a color. What I mean is I can crash 100% of the time on the color palette by pressing down and dragging across the colors. If I just click once, it will work.

Issue is, with a tablet sometimes the pen gets close enough to 'drag' and thus causes this crash to happen - a lot more often than I'd like.

**Comment by hanvyj** [comment]
Also have this issue:
```

Faulting application name: python2w.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.17763.914, time stamp: 0xfb6790ac
Exception code: 0x80000003
Fault offset: 0x00000000000bd162
Faulting process ID: 0x648
Faulting application start time: 0x01d5e115377373a7
Faulting application path: D:\Program Files\mypaint-w64\mingw64\bin\python2w.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 193a1a0a-bcdd-48c8-8943-57d930b1ed83
Faulting package full name: 
Faulting package-relative application ID: 
```

Can be reproduced by dragging a brush.

**Comment by jplloyd** [comment]
@hanvyj Can you reproduce this in the latest release?

Download the standalone package here: https://ci.appveyor.com/api/buildjobs/x3rigegft10sh556/artifacts/out%2Fbundles%2Fmypaint-git-w64-2.0.0-alpha-master.614-standalone.7z

Unpack it with 7zip or similar and run mypaint.exe (will take a little while the first time). Make sure to unpack it to a new directory (unless you want to clutter up your download folder).

_As with any Windows issue, I will reiterate that we have no devs who are regular Windows users. If any dev wants to join the team to handle these issues they will be welcome with open arms._

**Comment by hanvyj** [comment]
Issue seems to be resolved in that version for me on windows 10!

**Comment by jplloyd** [comment]
Good, we'll assume the original issue is resolved as well, until proven otherwise.
