### ISSUE TITLE
v1.2.1: Cannot start on Fedora 25 Wayland

### ISSUE THREAD

**Issue by dyskette** [mypaint/mypaint#791]
#### Description of the problem
mypaint cannot start under wayland, just showing a TypeError in the terminal. 

- It works fine under Xorg.

#### Basic system details

MyPaint version: 1.2.1 stable
Operating system: Fedora 25
Desktop environment: GNOME Wayland

#### Steps to reproduce

1. Install it from here: [32 bits](https://copr-be.cloud.fedoraproject.org/results/dyskette/tests/fedora-25-i386/00528144-mypaint/) or [64 bit](https://copr-be.cloud.fedoraproject.org/results/dyskette/tests/fedora-25-x86_64/00528144-mypaint/)
2. Open mypaint in GNOME wayland session

#### Backtraces or error messages

```python
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr'
INFO: lib.i18n: POSIX: LANG='es_MX.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
Gdk-Message: Unable to load exchange from the cursor theme
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 464, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/usr/share/mypaint/gui/main.py", line 95, in main
    from gui import application
  File "/usr/share/mypaint/gui/application.py", line 54, in <module>
    import filehandling
  File "/usr/share/mypaint/gui/filehandling.py", line 31, in <module>
    import drawwindow
  File "/usr/share/mypaint/gui/drawwindow.py", line 39, in <module>
    import quickchoice
  File "/usr/share/mypaint/gui/quickchoice.py", line 25, in <module>
    import gui.colortools
  File "/usr/share/mypaint/gui/colortools.py", line 20, in <module>
    from colors.hcywheel import HCYAdjusterPage
  File "/usr/share/mypaint/gui/colors/hcywheel.py", line 379, in <module>
    class HCYMaskEditorWheel (HCYHueChromaWheel):
  File "/usr/share/mypaint/gui/colors/hcywheel.py", line 397, in HCYMaskEditorWheel
    __rotate_cursor = gdk.Cursor(gdk.EXCHANGE)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gdk.py", line 329, in __new__
    return cls.new(*args, **kwds)
TypeError: constructor returned NULL
```

### Solution
The fix is already in master, it was introduced in #658. Specifically in commit b08a23d. With that change, it works fine for me under Wayland.

**Comment by danpla** [comment]
Note that there are still some deprecated `Gdk.Cursor.new()` constructors in the code waiting to be replaced by `Gdk.Cursor.new_for_display()`.

`gdk.Cursor(cursor_type)` == `Gdk.Cursor(cursor_type)` == `Gdk.Cursor.new(cursor_type)`:
[ pygobject/gi/overrides/Gdk.py
](https://github.com/GNOME/pygobject/blob/78defd2ab5f1935a6226336eaa08727e7516fb02/gi/overrides/Gdk.py#L324)

**Comment by manuq** [comment]
@dyskette the flatpak package works fine in Fedora 25 under Wayland, http://mypaint.org/downloads/

**Comment by achadwick** [comment]
I'm going to test #911 as a potential fix for this in master.

**Comment by jplloyd** [comment]
Stale issue. Latest releases work fine on Wayland systems with XWayland support.
