### ISSUE TITLE
Mypaint crashes often when saving

### ISSUE THREAD

**Issue by mamong-gwapo** [mypaint/mypaint#794]
Sometimes saving causes a "Mypaint has stopped working" message to pop up. I use ctrl+s to save by the way.
Here's the error message upon opening the program. I've tried uninstalling then re-installing but it's still there every time I open it.
```python
Mypaint version: 1.2.0+git.f62444e.dirty
System information: Windows-8-6.2.9200
Traceback (most recent call last):
  File "C:\Program Files (x86)\MyPaint\share\mypaint\gui\application.py", line 412, _at_application_start(self=<gui.application.Application object>, filenames=[], fullscreen=None)
                autosave_recovery = gui.autorecover.Presenter(self)
                autosave_recovery.run()
  variables: {'autosave_recovery.run': ('local', <bound method Presenter.run of <gui.autorecover.Presenter object at 0x04D78CB0>>)}
  File "C:\Program Files (x86)\MyPaint\share\mypaint\gui\autorecover.py", line 66, run(self=<gui.autorecover.Presenter object>, no_autosaves_dialog=False)
            autosaves = []
            for asav in lib.document.get_available_autosaves():
                # Another instance may be working in there.
  variables: {'lib.document.get_available_autosaves': ('global', <function get_available_autosaves at 0x045F4AF0>), 'asav': ('local', AutosaveInfo(path=u'C:\\Users\\Monique\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.7iuoeh\\autosave', last_modified=datetime.datetime(2017, 1, 8, 11, 7, 33, 635772), thumbnail=<Pixbuf object at 0x6d860d0 (GdkPixbuf at 0x6db5150)>, num_layers=3, unsaved_painting_time=0.0, width=2112, height=4544, valid=True, cache_in_use=False))}
  File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\document.py", line 1715, get_available_autosaves()
            if not os.path.isdir(autosave_path):
                continue
            yield AutosaveInfo.new_for_path(autosave_path)
  variables: {'AutosaveInfo.new_for_path': ('global', <bound method type.new_for_path of <class 'lib.document.AutosaveInfo'>>), 'autosave_path': ('local', u'C:\\Users\\Monique\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.7k274r\\autosave')}
  File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\document.py", line 156, new_for_path(cls=<class 'lib.document.AutosaveInfo'>, path=u'C:\\Users\\Monique\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.7k274r\\autosave')
            if os.path.exists(thumbnail_path):
                thumbnail = lib.pixbuf.load_from_file(thumbnail_path)
            cache_in_use = False
  variables: {'lib.pixbuf.load_from_file': ('global', <function load_from_file at 0x041AE130>), 'thumbnail_path': ('local', u'C:\\Users\\Monique\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.7k274r\\autosave\\Thumbnails\\thumbnail.png'), 'thumbnail': ('local', None)}
  File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\pixbuf.py", line 91, load_from_file(filename=u'C:\\Users\\Monique\\AppData\\Local\\Microsoft\...\doc.7k274r\\autosave\\Thumbnails\\thumbnail.png', feedback_cb=None)
        with open(filename, 'rb') as fp:
            return load_from_stream(fp, feedback_cb)
  variables: {'fp': ('local', <closed file u'C:\\Users\\Monique\\AppData\\Local\\Microsoft\\Windows\\INetCache\\mypaint\\doc.7k274r\\autosave\\Thumbnails\\thumbnail.png', mode 'rb' at 0x06D71498>), 'load_from_stream': ('global', <function load_from_stream at 0x041C0930>), 'feedback_cb': ('local', None)}
  File "C:\Program Files (x86)\MyPaint\share\mypaint\lib\pixbuf.py", line 114, load_from_stream(fp=<closed file u'C:\\Users\\Monique\\AppData\\Loca...\autosave\\Thumbnails\\thumbnail.png', mode 'rb'>, feedback_cb=None)
                break
            loader.write(buf)
        loader.close()
  variables: {'loader.write': ('local', gi.FunctionInfo(write)), 'buf': ('local', '\x00\x00\x00\x00 [NUL bytes! so many NULs snipped! -- achadwick] \x00\x00\x00\x00\x00\x00\x00\x00\x00')}
Error: gdk-pixbuf-error-quark: Unrecognized image file format (3)
```

**Comment by achadwick** [comment]
Thanks for the report. You have two problems! And Issues can only really cope with one sensible, but let's try to be helpful :grinning: 

1. It's crashing when you try to save. That's not good, but there's nothing for me to go on for that in this report. I can't fix that yet :cry: 

2. More annoyingly and in your face: it looks like you've got a dud thumbnail file in an old MyPaint cache folder. We should be handling that exception rather more... gracefully, and I think we can fix that for you right now :smile: 

Something to bear in mind for the original crasher: there's a more recent version of MyPaint out, v1.2.1. Please be sure to uninstall 1.2.0 before installing 1.2.1. Is the new version just as crashy? Pulling this down may fix up some issues with saving too: it could be a third-party library that we bundle causing all of this (libpng, I am looking at youuu).

If that doesn't fix it, or even if you don't want to try upgrading just yet, please try getting rid of the dud thumbnail file (it's `doc.7k274r\autosave\Thumbnails\thumbnail.png` inside the MyPaint cache folder, `C:\Users\Monique\AppData\Local\Microsoft\Windows\INetCache\mypaint`). You have to delete this file while MyPaint is not running. You should be able to get going again after this: the thumbs are only needed for the autosave recovery dialog to look pretty.

There might be quite a few `doc.******` folders with thumbnail.png files in there. If in doubt, and especially if Windows Explorer doesn't show a preview for them, you might want to have a 

Flagging this one as a bug 'cos we should be hiding that exception and maybe using a "missing image" icon if the thumbnail load fails.

It's a big effort sorting out the kind of crasher you're seeing when saving, so if that's still happening after the upgrade and the cleanup, please report it as a separate issue. Thanks!

**Comment by jplloyd** [comment]
No user followup. Assuming suggested solutions fixed the problem.
