### ISSUE TITLE
Support reading from stdin to make mypaint more pipeline friendly

### ISSUE THREAD

**Issue by Earnestly** [mypaint/mypaint#797]
This is a feature request--maybe even a pipe dream--for mypaint to learn how to read files from stdin.  The use case for me is simply to pipe the output from a screen capture tool into the input of mypaint with needing to create and manage temporary files.  This allows for quick and easy annotation using my graphics tablet.

Ultimately it would be really nice if mypaint could also write to stdout making my entire pipeline of tools work like: `maim -f png /dev/stdout | mypaint - > /dev/stdout | curl somefilebin` without any additional logic and without creating specialised programs.

I don't suspect this work flow is usual for GUI programs but that fact shouldn't be a limit to composition with other unrelated tools.  I also don't expect this is be implemented but to me it's worth considering.

Thanks regardless of the outcome for this lovely tool.

**Comment by achadwick** [comment]
Too fiddly and annoying to wire into the more program (always having to remember that STDOUT might be hooked up to an image processing too? Ugh.)

I think this sort of thing is better implemented as a separate script, using a tempfile and redirection of the MyPaint subprocess's STDOUT somewhere harmless.

Also, I don't see any demand for it and you are the only requester so far.

**Comment by achadwick** [comment]
Okay, one thumbs up so far. Maybe that's some user-demand :stuck_out_tongue_winking_eye::smile:

A stumbling point for this is that MyPaint uses libmypaint and a pile of its own C++ which likes to indicate error conditions with printf(), not fprintf(). Somebody will need to chase those down and make them behave.

I've tried named pipes. Nope - and in fact trying to use one will break saving due to our use of replace().

**Comment by jplloyd** [comment]
I agree that a script is the right tool for this job. @Earnestly, you can make a thread in the (community forums)[https://community.mypaint.org/] if you want to discuss this further, to also see if anyone else wants this functionality.
