### ISSUE TITLE
Pick Context: for huge strokes, the "blink" overlay doesn't disappear till the next stroke is picked

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#8]
Migrated here from [Gna! bug 18780](https://gna.org/bugs/?18780):

> [...] if you make a huge stroke then attempt to pick it with Pick Context, the stroke blink state is entered and you see the stroke highlighted. However sometimes the blink state is never left. Not sure what's going on here, possibly a race condition: it seems to happen more frequently for really huge strokes. To reproduce (on my pretty fast desktop replacement laptop):
> 1. Pick a nice light colour and background so the blink is more visible. 
> 2. Zoom all the way out. I'm working on master since 6d624040c2a was merged so this is one level further than 0.9.1, say. 
> 3. Pick a simple, big brush to save time and make processing faster. I used experimental/pixelblocking. Make it huge too, set the radius to max. 
> 4. Make the window big. Doesn't matter if fullscreened or not. 
> 5. Paint a huge stroke across the canvas, then a smaller one. This can be done with either the mouse or a stylus, and can be a straight-line stroke too. 
> 6. Pick the big one with "W", notice how stroke-blink is never left. You can even add and switch layers and it won't go away. 
> 7. Pick the smaller one with "W", and notice how stroke-blink is left quickly.

Confirmed as still happening on the current git master, fc4fafa.

**Comment by achadwick** [comment]
Screenshot from #331 demonstrating the problem:

> While using pick stroke and layer, the grey overlay highlight which appears while picking is not turning off. What I observed is, it happens more on a stroke which is drawn with a relatively huge brush or a long stroke. To get rid of it you need to pick another stroke.
> 
> ![media-20150531](https://cloud.githubusercontent.com/assets/2767425/7901790/7adbb8fe-07b8-11e5-9d21-4ddcfd2d6736.png)
-- reported by @cg-gnu

**Comment by achadwick** [comment]
That batch of commits taken together should fix this, and also make the stroke blinking experience better generally. Please test, and let me know if this one comes back!

**Comment by martinxyz** [comment]
Hey @achadwick this is great, I never thought this would ever get fixed. And you're even documenting my old code ... keep rocking :-)

It just occurred to me that I once fixed a nasty memory leak in this area of code. I think there is a regression test for it, but it was very slow so probably it will be disabled by default (20 minutes or something until you could be sure, the bug did only happen with the full GUI enabled). Maybe it still runs.

**Comment by cg-cnu** [comment]
@achadwik Awesome! will let u know.
