### ISSUE TITLE
Update the Windows build scripting to use setup.py & styrene

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#808]
Let's get CI rolling for MyPaint with continuous delivery of builds as artefacts from Appveyor.

@odysseywestra has been doing a lot of work on this recently, but I think the styrene config I've been using should be the source of our bundles. 

The first part of this is already done; just the mypaint[-git].cfg needs merging now.

**Comment by odysseywestra** [comment]
I just tested the latest appveyor build that use styrene on a Windows 10 VM and my HP that has Windows 7 on it. They installed and so far work as intended. Probably want to create a second one without all the debug tools for tagged releases to keep the installer size down.

Also here is a couple of other stuff that could probably be deleted in the bundle:
/mingw*/share/icons/Adwaita/*
/var/lib/pacman/*

Overall looking good. I sure users will be glad that Windows builds are back again. ^_^

**Comment by achadwick** [comment]
Surprisingly the default window decorations on Windows, and GTK theme need the Adwaita icons. The styrene config [tries to keep those](https://github.com/mypaint/mypaint/blob/master/windows/styrene/mypaint.cfg#L41).

The pacman indexes in the bundle's /var can be safely got rid of, since we don't intend to run pacman again once the bundle is prepared. Note that the package cache doesn't live within the image: styrene uses the same cache as your normal MSYS2 install.

All files in /var/lib/pacman/local *except for* packagename/install can be got rid of too. They're indexes of that got installed, and package descriptions.

What else? Baobab tells me that the next biggest areas are:

* mingw64/lib/python2.7/test → 31M, guess that's not needed
* mingw64/usr/share/mypaint/backgrounds → 30.8M   :smile:
* mingw64/bin → 76.2 MB, I guess we could strip the stuff in there. It's mostly DLLs, not sure if they're all needed.

**Comment by odysseywestra** [comment]
Heres a file break down of mingw64/bin:
```
[albert@Helios ~]$ ls -Ssh /mypaint-git-*/mingw64/bin
total 73M
 36M libopenblas.dll               6.5M libgtk-3-0.dll             2.2M libeay32.dll                   1.9M libgettextlib-0-19-8-1.dll         1.6M libpython2.7.dll
1.5M libepoxy-0.dll                1.4M libgio-2.0-0.dll           1.4M libstdc++-6.dll                1.3M libxml2-2.dll                      1.3M libgfortran-3.dll
1.2M libgdk-3-0.dll                1.1M libglib-2.0-0.dll          1.1M libiconv-2.dll                 992K libp11-kit-0.dll                   972K libcairo-2.dll
880K libmypaint-1-4-0.dll          668K libpixman-1-0.dll          660K libfreetype-6.dll              592K libharfbuzz-0.dll                  500K libgmp-10.dll
496K libturbojpeg-0.dll            464K libjpeg-8.dll              460K libtiff-5.dll                  436K libjasper-4.dll                    408K ssleay32.dll
376K libgettextpo-0.dll            368K liblcms2-2.dll             328K libquadmath-0.dll              316K libgettextsrc-0-19-8-1.dll         312K libfontconfig-1.dll
300K libgobject-2.0-0.dll          288K libfreeglut.dll            276K libpcre-1.dll                  252K libpcre16-0.dll                    248K libpango-1.0-0.dll
240K libpcre32-0.dll               240K libcroco-0.6-3.dll         232K librsvg-2-2.dll                232K libreadline7.dll                   228K libpng16-16.dll
228K libgirepository-1.0-1.dll     224K libgraphite2.dll           184K libgdk_pixbuf-2.0-0.dll        164K libcairo-script-interpreter-2.dll  160K libgomp-1.dll
160K libexpat-1.dll                156K libjson-glib-1.0-0.dll     152K liblzma-5.dll                  144K liblzo2-2.dll                      132K libatk-1.0-0.dll
132K libintl-8.dll                 100K libtasn1-6.dll             100K libjson-c-2.dll                 96K libpangowin32-1.0-0.dll             92K zlib1.dll
 88K libpangoft2-1.0-0.dll          84K libminizip-1.dll            84K libgcc_s_seh-1.dll              76K libbz2-1.dll                        68K update-mime-database.exe
 68K libpangocairo-1.0-0.dll        64K libhistory7.dll             64K libpcrecpp-0.dll                56K libwinpthread-1.dll                 56K glib-compile-schemas.exe
 56K libasprintf-0.dll              52K libharfbuzz-gobject-0.dll   52K gtk-update-icon-cache-3.0.exe   48K libgdbm-4.dll                       48K libgailutil-3-0.dll
 44K libpcreposix-0.dll             44K libcharset-1.dll            44K edit.dll                        40K libatomic-1.dll                     40K libcairo-gobject-2.dll
 36K libffi-6.dll                   36K libgmpxx-4.dll              32K libgtkreftestprivate-0.dll      32K gtk-query-immodules-3.0.exe         28K win7appid.exe
 28K gdk-pixbuf-query-loaders.exe   28K libgmodule-2.0-0.dll        28K gspawn-win64-helper.exe         24K libtermcap-0.dll                    24K libssp-0.dll
 24K libtiffxx-5.dll                24K libharfbuzz-icu-0.dll       20K libgthread-2.0-0.dll            20K python2.7.exe                       20K python2.exe
 20K python2w.exe                   20K python.exe                  20K mypaint                        4.0K mypaint-ora-thumbnailer            4.0K update-mime-database.exe.manifest

```
I'm guessing we need lilibopenblas.dll?

Also with the backgrounds, they could bundled separately, with the exception of a few? That way it could be an optional download for at least windows.

There is also /mingw64/share/locale that takes up a bit of space as well. Is there a way the languages can be an option where it can be downloaded if selected. We could probably do the same for the backgrounds as well.

**Comment by odysseywestra** [comment]
I'm wonder with Adwaita, if we could use a different theme that doesn't require those icons. Arc-theme is a popular choice. Or we can make our own custom theme that fits the windows 10 look. It would be interesting if we can in the future provide MyPaint in the Windows Store for all the 10s users. Hair brain idea I know.

**Comment by odysseywestra** [comment]
Here is a few others we probably don't need:
 * /mingw64/lib/python2.7/distutils/*
 * /mingw64/lib/python2.7/ensurepip/*

We could also get rid of any *.pyc and *.pyo files since they are just compiled python files. It will make first time launch longer, but will save on bandwidth. If that is the case we should provide a splash screen to at least let the user know yes, MyPaint is launching.

**Comment by achadwick** [comment]
Bear in mind that these are only disk sizes, not archive/installer sizes. Disk is cheap.

Images won't compress too well: they are already compressed. We could leave out the hi-res backgrounds, and it's worth having a sort through the normal backgrounds to get rid of ones that are ugly.

Code artifacts like .py/.pyc/.pyo and natural language artifacts compress pretty small, so I'm not worried about them. I want .py code to be present in the bundle so that users know where they are, even if they're not used.

I have no interest in making a Windows 10 lookalike theme, or bundling one, or changing from Adwaita. Themes are enough of a PITA to deal with anyway, let's not introduce the same hell onto the Windows platform. We've done the required work around Adwaita to make the bundle smaller.

Yep, libopenblas.dll is a requirement of numpy ☺

IMO, much of this should be fixed upstream in MSYS2. The gtk3 package contains all the headers and development stuff as well as just the DLLs, so it's way too big really for easy deployment with something like styrene (although tbf the Qt one was way worse when I looked last...)

We can keep on refining the installer size with PRs and commits, but I think the work on this is done now. Thanks for all the great Appveyor integration work and the ideas!
