### ISSUE TITLE
[Wayland] Cursor "TypeError: constructor returned NULL" exception when editing button mapping key.

### ISSUE THREAD

**Issue by jigpu** [mypaint/mypaint#809]
#### Description of the problem

When attempting to edit the the key combination used to trigger an action within the "Pointer Button Mappings" preferences, an exception is thrown causing the "Bug Detected" window to appear. This occurs as soon as the pointer is moved over the "Edit binding for 'FOO'" window. Perhaps related to bug #791?

#### Basic system details

MyPaint version: 1.3.0-alpha+git.be1fe883
Operating system: Arch Linux
Desktop environment: GNOME (Wayland session)
Packages: Python 2.7.13, GTK 3.22.15, GdkPixbuf 2.36.6, Cairo 1.14.8, GLib 2.52.1

#### Steps to reproduce

1. Start MyPaint
2. Open the program preferences (e.g. "Edit" -> "Edit Preferences")
3. Choose the "Buttons" panel
4. Double-click on one of the keyboard shortcuts in the "Button press" column
5. Move the mouse over the "Edit binding for 'FOO'" window that appears
6. A "Bug Detected" window pops up, and an exception is logged to the console

#### Backtraces or error messages

```
Gdk-Message: Unable to load mouse from the cursor theme
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/buttonmap.py", line 544, in _bp_edit_box_enter_cb
    window.get_display(), Gdk.CursorType.MOUSE)
TypeError: constructor returned NULL
```

**Comment by achadwick** [comment]
Gah. I thought we'd tracked down all of those and fixed them.

It's Wayland-specific. However given how ugly the MOUSE cursor looks on X11, let's try something else.

**Comment by achadwick** [comment]
CROSSHAIR should be OK on Wayland according to <https://github.com/mypaint/mypaint/issues/750#issuecomment-267335732>, so let's use that.
