### ISSUE TITLE
"Move layer" and "pan view" icons are too similar

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#81]
I've noted that when we try modify the canvas position of an active layer all layer are moved.
I've tested with two layer with simple strokes and when I've tried move one of these layers I've these messages on terminal, but I don't know if are relevance about this question:

WARNING: gui.freehand: Remove motion event compression workaround: removing evhack filter (<TiledDrawWidget object at 0x7fdce80e91e0 (TiledDrawWidget at 0x29ef610)>, <gui.freehand.FreehandMode object at 0x7fdcdc3c8450>)
WARNING: gui.freehand: Add motion event compression workaround: using evhack filter (<TiledDrawWidget object at 0x7fdce80e91e0 (TiledDrawWidget at 0x29ef610)>, <gui.freehand.FreehandMode object at 0x7fdcdc3c8450>)

**Comment by achadwick** [comment]
Trivial improvement that won't need any string changes. Assigning to the first beta milestone.
