### ISSUE TITLE
Add, or Invite Users to MyPaint's Teams

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#813]
Could @achadwick or anyone from the @mypaint/core invite the following users to the following teams. I would do it myself, but I don't have the ability to invite users outside the MyPaint organization.

Community Team:
@daiyi
Developers Team:
@briend @ShadowKyogre @manuq @dothiko @blackwarthog

These users have been pretty active on bringing features to MyPaint and deserve the ability to work on MyPaint directly. We'll probably want to merge in their pull-request as feature branches, like @briend's Smudge Blending. It will also give libmypaint some developers it needs to review PRs.

**Comment by achadwick** [comment]
Done. Invites sent to @daiyi, @briend, @manuq, @dothiko and @blackwarthog.

@ShadowKyogre is already a member of @mypaint/developers. Sorry if you got an unnecessary invitation :smile:

**Comment by blackwarthog** [comment]
Thank you :)

**Comment by dothiko** [comment]
Thank you very much  :smile:

**Comment by manuq** [comment]
Thanks Andrew. I'll try to help with anything I can.

**Comment by daiyi** [comment]
Thanks a lot! Will have some free time to get back to web development soon, yay summer (:

**Comment by briend** [comment]
Thank you!  I'll try to step up my git game and be more careful!  Oh and maybe learn to program :-)
