### ISSUE TITLE
Add Repositories to Community Team with Read Permission

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#815]
Could @achadwick or anyone from @mypaint/core team add the mypaint, and libmypaint repositories to the community team with read permission? It will allow the team to edit the Wiki's of both repositories and thus adding documentation as one of the responsibilities of the Community Team.

https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by achadwick** [comment]
Done, although I think everyone's Read by default normally for an Open Source project.

Has this solved an active problem at all?

**Comment by odysseywestra** [comment]
It was an issue I had with another project I noticed. Yeah I may have had read and write access to that repository, but with any repository outside of it that were within the organization, I couldn't edit the wiki pages even though I had read access since it was a public repository. That was about a year back so that may have changed.
