### ISSUE TITLE
viewzoom is not handled logarithmically

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#816]
The docs for the new viewzoom input say:

```
{
            "displayed_name": "Zoom Level", 
            "hard_maximum": 4.15, 
            "hard_minimum": -2.77, 
            "id": "viewzoom", 
            "normal": 0.0, 
            "soft_maximum": 4.15, 
            "soft_minimum": -2.77, 
            "tooltip": "The current zoom level of the canvas view.  Logarithmic: 100% is 0.  200% is .69, 25% is -1.38"
        },  
```

but freehand passes this in as the value for "scale", which is just a flat multiplier between 1/16 and 64. Please can you fix up whichever of these is in error on master ASAP?

**Comment by briend** [comment]
Sorry, I need to clarify that.  It is in relation to the current brush's base radius.  I think I had to do that to make it useable, and forgot to update the description.

**Comment by achadwick** [comment]
Ah, I'd never have guessed that ☺
Is the mypaint code all correct then? I'll close this when there's a PR or a commit in libmypaint for the corrected wording.

**Comment by briend** [comment]
Ok I updated the language to give a good brush example.  I know it's a bit odd to have the zoom in "log" numbers but, well, there was a good(ish) reason for it I think.  I see you merged the pull so I'll close this. Thanks!
