### ISSUE TITLE
viewrotation is not in degrees

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#817]
The viewrotation input for libmypaint should probably be in degrees, for compatibility with libmypaint's Ascension input. However lib.freehand passes it in as the value for "tdw.rotation", which is an angle in radians.

**Comment by briend** [comment]
I convert it to degrees in libmypaint here
https://github.com/mypaint/libmypaint/blob/master/mypaint-brush.c#L472
so I can apply it as a calibration to ascension, etc.  Maybe this can be closed (not sure I understand)?

**Comment by achadwick** [comment]
Okay - for the purposes of the libmypaint api, it would be a lot better to specify that all input angles are in degrees. But provided everything's documented, I guess it's OK.
