### ISSUE TITLE
Huion GT-190/Cursor Offset

### ISSUE THREAD

**Issue by laszlar** [mypaint/mypaint#82]
I've been looking for a solution for quite some time, and I can't find anything. Currently I'm running: 

Windows 8.1 (64-bit)
AMD HD 7970
Huion GT-190 (Tablet Monitor) 

I would love to use Mypaint, but when I try to use it the cursor offset is quite bad when I put the pen to the tablet. I've seen all the responses for the same exact issue for Wacom (not Huion) and to update the drivers for the HID compliant Mouse. Tried that and everything is up to date (and even the tablet drivers are up to date also). I tried other software (Inkscape, DrawPlus, Microsoft Paint, Artweaver) and they all worked fine. However, when I tried GIMP it ran into the same exact issue. Any suggestions? Please?

**Comment by achadwick** [comment]
Sorry for not responding earlier, @laszlar. Is this issue still happening with 1.2.0-beta? Now that it's out, I think we can safely say that 1.0.0 is too old an installation for us to support here.

You can find it on https://github.com/mypaint/mypaint/releases

**Comment by laszlar** [comment]
Hey Andrew,

Interestingly enough it was a driver issue with the Huion. I spoke with
Huion and they offered a new driver within that week that corrected a
cursor offset from the touch input (pen). I think this was back in October
of 2014?... at least I think so.

Anyway, thank you for getting back to me!

-Laszlo

**Comment by achadwick** [comment]
Thanks for the update, and good news! I'll close the issue here.

It'd be helpful for other Windows Huion users if you could dig out the Huion driver version number you're using now that fixed the problem, or provide a link to their download page, but the date should be of use.
