### ISSUE TITLE
Adding Snap Package Build Support

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#820]
I'm working on bringing Snap Package support to MyPaint. I have a feature branch setup up here: https://github.com/mypaint/mypaint/tree/snap_package . It still needs some work since this is my first time trying to create a snap package. Plus since MyPaint doesn't have full support for pip, I need to use custom build commands. Once everything is ironed out, I'll merge this in and enable auto-publish on https://build.snapcraft.io/.

@manuq since we worked together on getting flatpak setup, could you help me with this one as well? We may also need to add the external app patch too.

If anyone has any experience with snap packages, I'll appreciate any advice you may have.

**Comment by manuq** [comment]
@odysseywestra  sounds great, I would like to help. I looked at the snapcraft.yaml in your branch. I have installed snapd in my Fedora 25 but it seems snapcraft command in not packaged for my system, so I can't  build locally. Is your snap in a store in order to try it?

**Comment by manuq** [comment]
It seems snapcraft is for Ubuntu only. At least the `stage-packages` option that you used for dependencies is a list of Ubuntu packages. So I will be able to help as a tester only.

**Comment by odysseywestra** [comment]
Just letting you know can use snapcraft can be installed with Docker: https://snapcraft.io/docs/build-snaps/trusty . I have to do it that way cause I use Antegros which is based of Arch.

**Comment by manuq** [comment]
Ah thanks. I will try Docker then.

**Comment by odysseywestra** [comment]
I'm going to hold off on this for now. I'll reopen this issue when I'm ready to tackle this or have a volunteer who is willing maintain a snap package.
