### ISSUE TITLE
setup.py clean/test doesn't rebuild _mypaintlib.so

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#821]
if you run 
scons --clean
scons
python setup.py clean
python setup.py test
it will re-use a stale _mypaintlib.so that is in the build/lib.xxxx folder

**Comment by odysseywestra** [comment]
You need to use...
```
python setup.py clean --all
rm -vf lib/*_wrap.c*
```
..If you want a clean slate to work on. We probably need to update the build docs to reflect that.

**Comment by briend** [comment]
Sorry, my mistake. :-(

**Comment by briend** [comment]
I'll try to update the build doc :-)
