### ISSUE TITLE
Latest Appimages Builds Crash. Fail to Load libgdk-3.so.0

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#828]
#### Description of the problem

The latest appimage builds from our Travis CI crash when launched in Antergos Arch and in Ubuntu Gnome 17.04. This seems to have been happening back to 066b01c18ef5a0a126f1857df3e1a76ba90b5447 which is the farthest I can go back due to transfer.sh 14 day retention span. @probonopd since you add auto-build appimage support for Tavis-ci, could you please look into this?

#### Basic system details

MyPaint version: From 066b01c18ef5a0a126f1857df3e1a76ba90b5447 to latest Commit
Operating system(s): Antegros Arch, Ubuntu Gnome 17.04
Desktop environment: Gnome Shell

[More information about my laptop](https://gist.github.com/odysseywestra/a3539a28364308d336ca)

#### Steps to reproduce

1. Download the latest Appimage from Transfer.sh
    * https://transfer.sh/Qp9xw/MyPaint-1.3.0-alpha-gitexport.83fe746.glibc2.15-x86_64.AppImage
2. Allow it to be executable with `$ chmod a+x MyPaint*.AppImage`
3. Launch in the terminal with `./MyPaint*.Appimage
4. Error should pop up.

#### Backtraces or error messages

```
[albert@laptop ~]$ ./MyPaint-1.3.0-alpha-gitexport.83fe746.glibc2.15-x86_64.AppImage 
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_MyPain0uK7s3/usr/bin//mypaint.wrapper.
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPain0uK7s3/usr'
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None

** (process:8117): WARNING **: Failed to load shared library 'libgtk-3.so.0' referenced by the typelib: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_nominal_glyph_func

** (process:8117): WARNING **: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /usr/lib/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_nominal_glyph_func
Traceback (most recent call last):
  File "/tmp/.mount_MyPain0uK7s3/usr/bin/mypaint", line 464, in <module>
    from gui import main
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/mypaint/gui/main.py", line 22, in <module>
    from gi.repository import Gtk
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/importer.py", line 68, in load_module
    dynamic_module._load()
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/module.py", line 296, in _load
    self._overrides_module = importlib.import_module('gi.overrides.' + self._namespace)
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 75, in <module>
    class Widget(Gtk.Widget):
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/module.py", line 183, in __getattr__
    interfaces = tuple(interface for interface in get_interfaces_for_object(info)
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/module.py", line 109, in get_interfaces_for_object
    interfaces.append(getattr(module, name))
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/module.py", line 222, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/tmp/.mount_MyPain0uK7s3/usr/lib/python2.7/dist-packages/gi/types.py", line 221, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface
```

**Comment by probonopd** [comment]
Please try:

```
./MyPaint-1.3.0-alpha-gitexport.83fe746.glibc2.15-x86_64.AppImage --appimage-extract
find squashfs-root/ -name *harfbuzz* -delete
squashfs-root/AppRun
```

Does it work then?

**Comment by probonopd** [comment]
By the way, the AppImage builds are missing on the download page.

**Comment by odysseywestra** [comment]
> Does it work then?

Yes, doing the above works.

> By the way, the AppImage builds are missing on the download page.

We just haven't gotten around to it yet. Plus we don't have a permanent storage for them yet.

**Comment by odysseywestra** [comment]
@probonopd I'm looking a bintray atm as a possible place to store the alpha appimages. Probably for release, we'll store them in our github release page.

**Comment by probonopd** [comment]
> Yes, doing the above works

Adding the rm command to https://github.com/mypaint/mypaint/blob/master/appimage/appimage.sh#L77 should do the trick then.

**Comment by odysseywestra** [comment]
Okay when I get a chance latter on today, I'll push the change to the script.

**Comment by odysseywestra** [comment]
Okay, I tested on my fork of MyPaint and it launches again. Pushing changes to Master.
