### ISSUE TITLE
Appimage: Apply a Theme to Interface

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#829]
One thing that has been bugging about the MyPaint appimage is the lack of the Adwaita Theme applied. Right now it use a really ugly theme though it is functional. @probonopd is there a way to apply the Adwaita Theme or a way for it to use the system theme?

**Comment by probonopd** [comment]
What happens if you `export GTK_THEME=Adwaita`?

**Comment by odysseywestra** [comment]
Added it here on my fork: https://github.com/odysseywestra/mypaint/blob/master/appimage/appimage.sh#L10
However, nothing happened when I downloaded and launched that commit version from transfer.sh

**Comment by odysseywestra** [comment]
I also did a search within its `/squashfs-root` folder. No mention of any adwaita gtk theme, or color scheme. Is there a package related to adwaita that wasn't installed?

**Comment by odysseywestra** [comment]
I tried to use Arc theme, but since it requires GTK 3.14, it doesn't render correctly. 14.04 which is what Travis-ci uses ships with GTK 3.10.

**Comment by probonopd** [comment]
Please check whether you really need to add all of the latest additions to the AppImage (include icon themes and everything), it makes the AppImage way much larger. I think Adwaita can be assumed to be part of each target system. We need to find out how we can make it to load the Adwaita theme, but that is probably a question for the application and/or GTK developers.

Looking at https://github.com/jessevdk/gtk-mac-bundler/blob/master/examples/gtk3-launcher.sh it may be necessary to play with some environment variables such as `GTK_DATA_PREFIX`.

**Comment by probonopd** [comment]
The proper way to do this would be to get rid of the need to bundle `./usr/lib/x86_64-linux-gnu/libgtk-3.so.0` and make it work with the `libgtk-3.so.0` provided by the system. That way, the system's themes would be used.

When I currently delete the bundled library, then I get:

```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/home/linux/squashfs-root/usr'
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=''
INFO: lib.i18n: Value of LANGUAGE after cleanup: ''
././/bin/python: symbol lookup error: /usr/lib64/libgtk-3.so.0: undefined symbol: gdk__private__
```

I don't know yet why this is. Maybe some GTK expert knows?

**Comment by probonopd** [comment]
As a workaround, you can make the bundled `./usr/lib/x86_64-linux-gnu/libgtk-3.so.0` load its resources from the system `/usr` by reverting the binpatch:

```
sed -i -e 's|././|/usr|g' ./usr/lib/x86_64-linux-gnu/libgtk-3.so.0
```

In this case, it is defintiely not necessary to bundle the Adwaita resources inside the AppImage, since the system ones will be used.

**Comment by odysseywestra** [comment]
> I don't know yet why this is. Maybe some GTK expert knows?
Could you answer this @achadwick since this is your area of expertise?

What do we do about Desktop Environments that don't ship GTK like KDE and LXQT? If that would cause problems for them, then I would pack in a theme with the appimage. Doesn't have to be Adwaita. Just a theme that can work on GTK 3.10 that can also switch to it a dark variant. Otherwise we may also need to apply a patch disabling the feature in the preferences and just go to a dark theme by default.

Besides users already know if they are going to use at least this appimage, flatpak, or snap packages, the initial file sizes downloads are going to be big. Plus once we get the kinks hashed out, I would like to work on getting the delta updates setup for this. I'll leave the update thing for another issue though.

**Comment by probonopd** [comment]
Until Gtk+ 3 is ABI stable (also the versions in LTS and Enterprise distros, so in a couple of years), it would probably be the easiest to either bundle one theme or go without themes. It looks like Gtk+ 3 (at least the versions in LTS and Enterprise distros) are not mature yet so that one could use their themes with bundled Gtk+ 3.

**Comment by odysseywestra** [comment]
Closing since @aferrero2707 create a appimage build system that fixed a lot of the issues I had a the time.
