### ISSUE TITLE
[Feature Request] - Crosshair Pointer Improvements

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#83]
For the artists that use the Crosshair pointer to paint or draw is very difficult to have the notion of the task to scale a brush, up or down, the size mainly but this discussion maybe important to other parameters present on Tool Options tab.
I'm not know if is possible... but would be useful when we use the crosshair to have the possibility a key to interact  with the Circle instances of pointer, only to show the circle when this key is down, for example.
A good improvement for me is also to have a label directly on the circle pointer (over canvas) with the nominal dimension in pixels (diameter preferable).
In my cases to resolve this question I've made some fixed brushes, 0.2, 0.4 mm (based on 300 ppi) that I use as reference.
In alternative would be interesting to have in alternative or also a label with nominal values of the tool options parameters.

**Comment by odysseywestra** [comment]
@americogobbo Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue.

**Comment by jplloyd** [comment]
I think this can be considered to be solved by the [resolution](https://github.com/mypaint/mypaint/issues/293#issuecomment-663418372) to #293, since switching to resize mode (even without resizing) will give a visual representation of what the circular brush cursor would show (even better, since the resize circle is not constrained by a maximum cursor size).
