### ISSUE TITLE
Bundle gtk3-demo in our Windows styrene installers

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#834]
For debugging reports like #830, it would be helpful to include gtk3-demo.exe as part of the build. The styrene [gtk3-examples.cfg](https://github.com/achadwick/styrene/blob/33286cd8e9dc6de122e53856e5199bb98bfff55c/gtk3-examples.cfg) already has one, so it's probably just a question of merging the launcher definitions and dependent files into our own [windows/styrene/mypaint.cfg](https://github.com/mypaint/mypaint/blob/be1fe883b3a8b031188dc5fb2828ee2ca67ce261/windows/styrene/mypaint.cfg).

**Comment by odysseywestra** [comment]
Could I get someone from @mypaint/developers team who use Windows to download and install this [alpha build](https://ci.appveyor.com/project/odysseywestra/mypaint-vekbs/build/1.3.0-alpha+master.211/job/kwfwf06w0m5bol6k/artifacts) from my fork of MyPaint? If it shows the launchers and works, I'll push the change to Master.

**Comment by briend** [comment]
The gtk+ demo seems to work:
![image](https://user-images.githubusercontent.com/6015639/28177606-34ac54ce-67b0-11e7-82df-6776dbf3eaf4.png)


but the mypaint doesn't launch:
![image](https://user-images.githubusercontent.com/6015639/28177445-ab856b54-67af-11e7-9c98-70660cdf22a9.png)

also the gtk3-demo-event-axes.exe seems to be trying to run gtk3-demo without the exe? (maybe?)
![image](https://user-images.githubusercontent.com/6015639/28177654-5559657c-67b0-11e7-8c36-9b9189376211.png)

**Comment by odysseywestra** [comment]
@briend Okay I amended the commit with fixes. The new alpha builds should be ready in 30 minutes in the link below. Thank you for testing these out.

https://ci.appveyor.com/project/odysseywestra/mypaint-vekbs/build/job/1ogfmjk3twxixoco/artifacts

**Comment by briend** [comment]
trying now!

**Comment by briend** [comment]
Awesome, everything seems to work.  mypaint, the demo, and the event-axes.  Thanks @odysseywestra !

**Comment by odysseywestra** [comment]
Okay, Awesome! I was able to test it finally(Test Laptop being temperamental with Windows 7) and was able to open it as well. Pushing changes to Master.
