### ISSUE TITLE
Genius Mousepen i608 tablet   mapping problem

### ISSUE THREAD

**Issue by paulcross2017** [mypaint/mypaint#837]
#### Description of the problem

  Genius Mousepen i608 tablet  is a  wacom intuos like pen tablet replacement.  It works fine in other painting software such as SAI, Opencanvas, photoshop. But with mypaint (1.0 or 1.2.1) it will cause a mapping problem, no matter where you paint, only  a small area of mypaint canvas can  be painted on. 

Same problem have been encourted by someone else. there is a video link to show that:https://www.youtube.com/watch?v=tVz0GThhwWY&spfreload=10

#### Basic system details

MyPaint version: 1.0, 1.2,  1.2.1
Operating system: windows 7 x64

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. paint on canvas

#### Backtraces or error messages

```
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by paulcross2017** [comment]
Problem solved.

Just need to reinstall the windows 7 x64 operating system  and  install the Driver 5.02.

**Comment by achadwick** [comment]
Thanks for the report! Windows tablet integration issues can be a pain to fix, and it's always useful to have a searchable solution to a problem somewhere.
