### ISSUE TITLE
Preserve brush Hue when picking achromatic colors from canvas

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#838]
Currently if you "color pick" anything on that canvas that lacks color, the hue gets reset to "red".  This can be problematic if you are using a brush that has dynamic colors adjustments, or if you use the keyboard shortcuts for lighten/darken or increase/decrease saturation.  Or if you were planning to re-adjust your color with the sliders for saturation, and brightness.  The color wheels and sliders all preserve the Hue even for achromatic colors, so I think it makes sense for the color picker to do the same.

I can see why it behaves that way-- there's no hue information in an RGB value like 1,1,1, so hue=0 is logical.  Except, we DO know what the previous brush color was, and it probably makes more sense to just keep that hue instead.  It should be pretty easy to tweak the colorpicker code so that it compares the new pick_color with the old brush color and, in an achromatic case, set the new brush color hue to the old brush color's hue.

**Comment by briend** [comment]
What's funny is that GIMP and Photoshop (and I assume others)  will all flip your Hue to Red when picking achromatic colors (white, black, greys).

**Comment by 0ion9** [comment]
Well, preserving the previous hue does make the design sjightly stateful / modal[1], which is not usually expected from a colorpicker. That said, I don't think it's a strong enough reason to justify not trying this

[1] That is, given a set of colors ABCDEF, where F is achromatic, picking  A->B->F  may result in a different colorpicker state than picking C->D->F

**Comment by briend** [comment]
Red (0) would be fine if there was no previous brush state (or an achromatic brush state).  As far as being expected; I would bet people would be more surprised to see their color wheel flip to red arbitrarily than they would seeing it remain where it was a moment before they picked a grey color.  I mean, I noticed it before but I didn't care until I started playing with the H/C/Y picker referenced above, where it actually matters a lot :-)

Using the previous brush hue is not entirely rational, but I think it must be more rational than always reverting to Red, right?

**Comment by 0ion9** [comment]
Like I said, it's worth a try; If hardly anyone complains, I guess it will be a good choice. I'm just generally wary of modal behaviour. as IME it tends to load up the user's experience with things to track. It has to prove itself on a case-by-case basis.

**Comment by briend** [comment]
Give it a try!

**Comment by briend** [comment]
Corel Painter 2016 flips the hue to 160 (blue) for achromatic colors.  Just thought that was interesting they chose that instead of red for some reason.  I will bundle this with the HCY picker since it's the same code:  https://github.com/mypaint/mypaint/issues/835
