### ISSUE TITLE
Cursor doesn't update its eraser status when "eraser" key is pressed while painting

### ISSUE THREAD

**Issue by iirelu** [mypaint/mypaint#84]
I frequently need to change the eraser status while the brush is held down (usually as my tablet is so old the nib gets stuck in and sends erroneous pressure reports a lot) and it's very disorienting when the cursor doesn't update like it would otherwise. The cursor only updates once there's no pressure being applied.

Cursor updates fail with the mouse is held down, too.

**Comment by odysseywestra** [comment]
I'm going to go ahead and closed this in I'm unable to repoduece the latest rolling-appimage releases. The Status icon is updating while I am drawing. Feel free to reopen the issue if this is still happening to @iirelu .
