### ISSUE TITLE
BrushEditor leaves extra input mappings in brush files

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#840]
If you ever edit a brush and add some input dynamics to a brush, the file will grow and contain two inert mapping points for it even if you delete/clear the inputs:

                "tilt_declination": [
                    [
                        0.0, 
                        0.0
                    ], 
                    [
                        90.0, 
                        0.0
                    ]
                ]

This seems to add a lot of clutter and actually might be causing issues in the brush engine, see https://github.com/mypaint/libmypaint/issues/100 and https://github.com/mypaint/libmypaint/issues/99

**Comment by achadwick** [comment]
Yikes, we should filter that out somehow.  Can you give me some minimal, clear steps to reproduce, from a fresh config?  For the throwaway config used by `python setup.py demo`, ideally.

Just to confirm, this only happens if you save the modified brush, correct?

**Comment by achadwick** [comment]
Actually, never mind. reproduced here :smile: 

1. Clean out old demo files in /tmp: `rm -fr /tmp/demo-*`
2. Start Mypaint with `python setup.py demo`
3. Press <kbd>Ctrl+B</kbd>, and make the Brush settings Editor window bigger if needed
4. Left hand side: click _Basic → Snap to pixel_ in the tree. This has no mapping for the default brush
5. Middle area:
   * Unfold (click "`>`" for) _Brush Dynamics → Pressure_
   * Move the Pressure slider to a non-default value.
   * Click on the unfolded graph to add a point.
   * Click on the reset button at the end of the Pressure slider (the one that looks like a cleaning brush)
      * The graph resets (expected), and the slider goes back to zero (also expected)
6. Bottom right: click on Save.
7. In a separate terminal window, run `less /tmp/demo-*/_config/brushes/deevad/2B_pencil.myb`. Search for `snap_to_pixel`.

Expected:

```json
        "snap_to_pixel": {
            "base_value": 0.0, 
            "inputs": {}
        }, 
```

Observed:

```json
        "snap_to_pixel": {
            "base_value": 0.0, 
            "inputs": {
                "pressure": [
                    [
                        0.0, 
                        0.0
                    ], 
                    [
                        1.0, 
                        0.0
                    ]
                ]
            }
        }, 
```

**Comment by achadwick** [comment]
I guess the "Expected" value above is what we want for things which have been explicitly reset.

I think we only need to do this when the reset button is clicked, right? That's how you're supposed to reset a setting to its default value and set it to non-dynamic.

Are there any other user actions which should nuke the curve points?

**Comment by briend** [comment]
>Are there any other user actions which should nuke the curve points?
That's an interesting question.   Issue #826 might be relevant.  Maybe the clear button nukes *everything* and we don't allow sliding to absolute zero since that would store a bunch of worthless points?

**Comment by achadwick** [comment]
Clear button (for a dynamic/setting) now nukes everything to do with that dynamic/setting :smile:

**Comment by briend** [comment]
Thanks @achadwick !!
