### ISSUE TITLE
Move MyPaint Brushes to New Repository

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#842]
We should probably start the process of moving the brushes to their own repository. This will allow other projects to use the brushes without having to clone MyPaint to do so. Plus it will allow us to put a version control on them so we can avoid issues like mypaint/libmypaint#101. @Jehan has a repo started at https://github.com/Jehan/mypaint-data. We could either fork that repo or have that person transfer ownership to us so we can continue it.

In the meantime we should create new branches for each repo and make the necessary changes for each package that we as a community maintain such as:

- [ ] MyPaint.deb - @mypaint/packagers 
- [ ] Libmypaint.deb - @mypaint/packagers 
- [ ] Flatpak Package - @manuq 
- [ ] Appimage - @probonopd (Submit PR)
- [ ] AUR packages - @ShadowKyogre, me
- [ ] Mingw & Msys2 Packages - @achadwick 

`mypaint-brushes` or `libmypaint-brushes` could be a good names for the package, but if anyone has a better name for the package, I'm sure we're all ears. 

Okay that about what I know of the MyPaint Brushes situation, if anyone has anything to add or other concerns we need to address please let your voice be known below. I'll edit this post as we get new info.

Also as a parting question, should we also do this to our backgrounds as well?

**Comment by Jehan** [comment]
>  @Jehan has a repo started at https://github.com/Jehan/mypaint-data.

The right repo is actually now: https://github.com/Jehan/mypaint-brushes
I [renamed long ago](https://github.com/mypaint/mypaint/pull/538#issuecomment-178107722) when @achadwick was telling me he didn't like the naming `mypaint-data`. I guess I should get rid of this old repo to avoid confusion.

> We could either fork that repo or have that person transfer ownership to us so we can continue it.

I am happy to give ownership right now if you ask me. I never planned and never will to maintain this repository. It was created under my name for the sole reason that I don't have the rights to create a new repo under mypaint organization. But the goal has always been to just give this to MyPaint as soon as possible. :-)
I just updated the repository a few hours ago. It is now fully up-to-date with the contents of `mypaint` repo and has the full git history of everything which happened to brushes.
See also #538.

**Comment by Jehan** [comment]
P.S.: I just tried to transfer ownership, but it tells me in error: "You don’t have the permission to create repositories on mypaint". Apparently I can't transfer ownership if I don't have repo creation permission.

I would propose you temporarily give me repository creation permission. @achadwick knows me (well… we met at LGM) and I am in GIMP and libmypaint team. Hopefully that's enough for the trust I won't do anything bad. :P

**Comment by AtsusaKaneytza** [comment]
I was wondering about this, thank goodness.
I had to track down a new download for Luovatone's "Tone" brushes because they were on the old repository, which is inaccessible. He also hasn't posted them on his DeviantART or Youtube. But here's the .ZIP file, thanks to this MyPaint community page: https://community.mypaint.org/t/cant-find-luovatones-brushset-v2-tone-help/758
[tone_v2.zip](https://github.com/mypaint/mypaint/files/1400892/tone_v2.zip)

**Comment by briend** [comment]
I've gone ahead and merged this, and right away some stuff is broken.  As soon as this PR is merged in MING, the windows builds should be fine:
https://github.com/Alexpux/MINGW-packages/pull/4757
need to take a look at the other packaging

**Comment by odysseywestra** [comment]
I'm guessing this is technically done?
