### ISSUE TITLE
AppImage missing on download page

### ISSUE THREAD

**Issue by probonopd** [mypaint/mypaint#849]
http://mypaint.org/downloads/ now contains the Flatpak but not the AppImage. Please add the AppImage.

Now, to link to the AppImage you need to host the AppImage at a location with a constant URL.

You can host them for the releases on GitHub Releases.
For continuous builds, check https://github.com/probonopd/uploadtool for an easy way to get them on GitHub Releases, too.

**Comment by odysseywestra** [comment]
The reason it not up on the website cause it's not fully ready. My goal is to have flatpak, appimage, and in the future snap package to be constant with package from our nightly-ppa. #829 needs to be addressed first, and there is a canvas performance problem that needs to be addressed as well. We can add you to the developers team if you wish so you work on them. I can help out with testing if you need me to.

**Comment by probonopd** [comment]
Not needed; I have sent a PR that addresses #829. As for Flatpak and Snap I can't help you, sorry.

**Comment by Symbian9** [comment]
Any news here? I want AppImage too

**Comment by Lvaskz** [comment]
any progress with appimage? Download from travis is not so easy

**Comment by Symbian9** [comment]
Here are unofficial nightly AppImage

- https://github.com/aferrero2707/mypaint-appimage/releases

But, I hope, that @mypaint team will solve this issue

**Comment by odysseywestra** [comment]
Now that the appimage is much more stable, I feel much more comfortable putting about on the Download Page of the website. Closing.

**Comment by aferrero2707** [comment]
@odysseywestra could you clarify what happens with the experimental AppImage I proposed? In #829 you mention that it solves several issues that were bugging you in the past, which is really great.
So, are you proposing to use my AppImage build scripts as the official ones? In this case, I will continue supporting them and help fixing AppImage-related issues when they appear.
As for wether to integrate or not the scripts into the MyPaint repository, I have no preferences... however, if you are happy with the current setup (build & deploy scripts in a separate repository, and nightly builds) then I propose to keep it like that...

**Comment by briend** [comment]
I think we should fork @aferrero2707's appimage repo into the MyPaint org as its own repo.  That way we can pull in updates from @aferrero2707 if he is kind enough to support us ;-), and we can keep the mypaint repo commit messages cleaner and more related to mypaint code.

**Comment by briend** [comment]
I cloned it over here:
https://github.com/mypaint/mypaint-appimage
The build still pulls in various other resources but I don't really think we should try to clone all of those.

Kicked off a test build.  Not quite sure how to link the mypaint git commits to trigger an appimage build yet, but I haven't really looked much yet

**Comment by probonopd** [comment]
The naming of the file `MyPaint---20190207.AppImage` is very strange, and a `.zsync` file is missing. The standard naming would be `MyPaint-20190207-x86_64.AppImage` and `MyPaint-20190207-x86_64.AppImage.zsync`. linuxdeployqt should generate the `.zsync` file automatically and use the correct naming if you `export VERSION=20190207` prior to calling it.

**Comment by aferrero2707** [comment]
@briend 
Concerning the automated triggering of AppImage builds, I have personally two approaches:
1. have a cron job that checks the git head of the source repository and compares it with the commit hash of the most recent successful build, and builds a new package only of the commits differ
2. have the travis CI configuration directly in the source project, and clone the scripts repository when building. In this case, the builds can be directly triggered by commits in the sources repository

I am typically using the first approach for projects that have several branches for which AppImages should be regularly built. This is the case for example of RawTherapee, for which I am providing nightly packages for at least three or four different branches. It also works when I have no developer access to the sources repository, like in the GIMP case.

The second approach is good for projects in which the development occurs mostly in a single branch, or projects for which only one or two branches is worth being packaged. That's the case of my own PhotoFlow project.

@probonopd 
Yes, the naming needs to be improved. I normally use the following scheme: 
`Project_name-branch-git_describe-date-arch.AppImage`.

I will look into how to generate the zsync file, as I am not using linuxdeploy(qt) for the packaging....

**Comment by probonopd** [comment]
To achieve this, please `export branch-git_describe-date` before invoking `linuxdeployqt`.

**Comment by odysseywestra** [comment]
Probably be a good idea to open a new issue ticket to keep things on topic.
