### ISSUE TITLE
I can't install via CLI (openSUSE Tumbleweed)

### ISSUE THREAD

**Issue by marcoparavano** [mypaint/mypaint#854]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
![screenshot_20170824_184833](https://user-images.githubusercontent.com/25709765/29679319-c053e768-8901-11e7-87b2-8d5e1e93465b.png)

[☞ Please search before posting to avoid duplicates.]

#### Description of the problem

[✍ Fill in this section with a clear description of **ONE** problem.]
[☞ Stay on topic. Separate problems go in separate issues.]
[☞ Read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs first.]
[⚠ If you don't give us enough detail to allow us to reproduce your issue, we cannot help and your report will be closed.]
[☞ Check the title is short but useful. It should echo this description.]
[☞ Pictures and videos help us a lot. You can paste screenshots.]

#### Basic system details

MyPaint version: [✍ 1.2.0 stable, 1.2.1-beta.1, git revision NNNNNNN, …]
Operating system: [✍ Debian 8.3, Ubuntu 16.04, Windows 7, …]
Desktop environment: [✍ GNOME, Xfce, …]

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. [✍ second step]
3. [✍ third step]

#### Backtraces or error messages

```
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by achadwick** [comment]
Paging and assigning to @manuq, as our friendly `flatpak/` maintainer.

@marcoparavano: This is very likely to be a local configuration issue at your end. I don't understand flatpak myself, sadly.

**Comment by manuq** [comment]
Thanks for noticing it. Yes I am able to reproduce it. It seems the GPG key of flathub.org has changed.

**Comment by manuq** [comment]
@marcoparavano for the moment you can do:
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.mypaint.MyPaint
```

**Comment by marcoparavano** [comment]
many thanks.

Il 29/Ago/2017 18:59, "manuq" <notifications@github.com> ha scritto:

**Comment by marcoparavano** [comment]
marco@COLORS:~> flatpak remote-add --if-not-exists flathub
https://flathub.org/repo/flathub.flatpakrepo
marco@COLORS:~> flatpak install flathub org.mypaint.MyPaint
Required runtime for org.mypaint.MyPaint/x86_64/stable
(org.gnome.Platform/x86_64/3.24) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/3.24 from flathub

13 delta parts, 91 loose fetched; 204224 KiB transferred in 213 seconds
seconds remainingg
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from
repo: GPG verification enabled, but no summary signatures found

what is now the error?

2017-08-29 19:11 GMT+02:00 Marco Paravano <paravano.marco@gmail.com>:

**Comment by marcoparavano** [comment]
I want to install the lastest version of mypaint via Flatpak on a pc with
opensuse tumbleweed but I am not so expert of opensuse tumbleweed, sorry


2017-08-29 19:40 GMT+02:00 Marco Paravano <paravano.marco@gmail.com>:

**Comment by manuq** [comment]
I updated the flatpakref and the issue has been fixed.
Hi @marcoparavano, can you try again with the original command?
```
flatpak install --from https://raw.githubusercontent.com/mypaint/mypaint/master/flatpak/mypaint-stable.flatpakref
```

**Comment by marcoparavano** [comment]
Here we are:

marco@COLORS:~> flatpak install --from
https://raw.githubusercontent.com/mypaint/mypaint/master/flatpak/mypaint-stable.flatpakref
Installing: org.mypaint.MyPaint/x86_64/stable
Required runtime for org.mypaint.MyPaint/x86_64/stable
(org.gnome.Platform/x86_64/3.24) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/3.24 from flathub


error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from
repo: GPG verification enabled, but no summary signatures found

Maybe there is something wrong in my openSUSE Tumbleweed....

2017-09-01 15:08 GMT+02:00 manuq <notifications@github.com>:

**Comment by marcoparavano** [comment]
I've asked a friend of mine to try install MyPaint with Flatpak. The three
images attached below come from his computer (openSUSE Tumbleweed in
Virtual Box). I hope they help to recognize the error. Maybe the problem is
the fact that we both are running openSUSE Tumbleweed with KDE Plasma 5
desktop environment....
Thanks and regards.

2017-09-01 15:20 GMT+02:00 Marco Paravano <paravano.marco@gmail.com>:
