### ISSUE TITLE
Change Hue clockwise/anticlockwise is reversed

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#859]
Not sure how I haven't noticed this until now... but change hue clockwise actually goes counterclockwise, and counterclockwise goes clockwise.  Anyone else notice this?  I even checked my locale and it _wasn't_ set for Australia.  I propose we just change the label since we don't want to break people's custom keymaps.

**Comment by achadwick** [comment]
The Shift+Q and Shift+W keys currently have the right effect on the colour wheel, to my eyes. On a QWERTY keyboard, anyway.

Worth swapping the labels and fixing the internal action names. There's some history to this issue: this has happened before, I think.

The menu should have the "Clockwise" label first, but I think that will be the case after the label swap.

(IMO, these should use the HCY model too, but that requires a deeper internal change.)

**Comment by achadwick** [comment]
Internal names are already OK: "IncreaseHue" adds 0.15 to the HSV "h" component. I'll fix the doc comments on the callbacks too, which are also wrong :smile:
