### ISSUE TITLE
'Programming error' when clicking button 2 repeatedly to cycle color history

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#86]
Not sure what else I can say about this one -- I have button2 configured to cycle color history, and it does this.. but occasionally it also generates this 'programming error' report, with the following backtrace:

```python3
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/document.py", line 553, button_press_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7fa30966e820 (TiledDrawWidget at 0x2bb6640)>, event=<void>)
return self._dispatch_named_action(None, tdw, event,
   action_name)
# User-configurable forbidding of particular devices
  variables: {'action_name': ('local', u'ColorHistoryPopup')}
  File "/usr/share/mypaint/gui/document.py", line 695, _dispatch_named_action(self=<gui.document.Document object>, win=None, tdw=<TiledDrawWidget object at 0x7fa30966e820 (TiledDrawWidget at 0x2bb6640)>, event=<void>, action_name=u'ColorHistoryPopup')
# Pointer: popup states handle these themselves sanely.
handler.activate(event)
return True
  variables: {'handler.activate': ('local', <bound method State.activate of <gui.stategroup.State object at 0x7fa306c0f950>>), 'event': ('local', <void at 0x3c1e2f0>)}
  File "/usr/share/mypaint/gui/stategroup.py", line 144, activate(self=<gui.stategroup.State object>, action_or_event=<void>)
# currently, we only support mouse buttons being pressed here
assert e.type == gdk.BUTTON_PRESS
# let's just note down what mous button that was
  variables: {'gdk.BUTTON_PRESS': ('global', 4), 'e.type': ('local', <enum GDK_2BUTTON_PRESS of type GdkEventType>)}
AssertionError: 
```

MyPaint version: git e629c7e "Fix exception when releasing modified space bar"
GTK+ version: 3.13.7.9.g0ef0b98 (git) .. also tested with 3.11.6
Distro: Arch Linux, 64bit
Tablet: Monoprice 12x9

Since the latest commit seems relevant, I tried to reproduce the problem using spacebar, but it never occurs, it only occurs when rapidly clicking the actual Button2.

**Comment by achadwick** [comment]
@0ion9: please can you give me *exact* instructions about how to reproduce this starting from a fresh configuration, i.e. running as `./mypaint -c /tmp/testcfg$$` in a new Terminal window? Include anything you have to do to get your buttons set up in the way needed to reproduce this bug.

**Comment by 0ion9** [comment]
Sure, that's easy:

1. Go into buttons config
2. Remove 'popup menu' -> button3  mapping
3. Add 'Color History' -> button3 mapping
4. close dialog
5. click  button3 like mad.

That's it.

**Comment by loentar** [comment]
This assertion is failed:

stategroup.py:
```
                # currently, we only support mouse buttons being pressed here
                assert e.type == gdk.BUTTON_PRESS
```

But if you press right button quickly twice or three times `e.type` will be not `gdk.BUTTON_PRESS` but `2BUTTON_PRESS` or `3BUTTON_PRESS`.
There properties are protected, so it must be get it using `getattr`.

Patch to fix the issue: https://gist.github.com/loentar/464d0ca08ce9c3deb866

**Comment by jy2wong** [comment]
@loentar: looks like it stops the programming error window from popping up. I'm worried that eating the extra clicks may cause problems elsewhere, though.

Regardless, no need to use getattr; directly using pygobject's `gdk.EventType.{DOUBLE,TRIPLE}_BUTTON_PRESS` works just fine.

Speaking of pygobject... @achadwick, what's the current situation with pygtk and pygobject? Would replacing all `gdk.BUTTON_PRESS`es with `gdk.EventType.BUTTON_PRESS` and such cause unforetold disaster?

**Comment by loentar** [comment]
@jy2wong I painted many hours with that patch, and didn't notice any *new* issues.

As you said, this does work:
```
if e.type == gdk.EventType.DOUBLE_BUTTON_PRESS or e.type == gdk.EventType.TRIPLE_BUTTON_PRESS:
```

I don't code on python and GDK, so that was only the solution I found.
