### ISSUE TITLE
zero length  files in mypaint package

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#860]
MyPaint version:MyPaint-1.3.0-git.f7d69f5.glibc2.15-x86_64.AppImage
Operating system: fatdog Linux 710 found at http://www.murga-linux.com/puppy/viewtopic.php?t=109067
Desktop environment: JWM + Rox filer + GTK2

While making a  fatdog  package I saw the following message in  the terminal.
It's not important but I will report it anyway...

```WARNING:  zero length file usr/share/X11/locale/fi_FI.UTF-8/XI18N_OBJS
WARNING:  zero length file usr/share/X11/locale/el_GR.UTF-8/XI18N_OBJS
WARNING:  zero length file usr/share/X11/locale/am_ET.UTF-8/XI18N_OBJS
WARNING:  zero length file usr/share/python/debpython/__init__.py
WARNING:  zero length file usr/lib/python2.7/email/mime/__init__.py
WARNING:  zero length file usr/lib/python2.7/pydoc_data/__init__.py
WARNING:  /usr/share/man (with possibly not gzipped man pages) detected
WARNING:  /usr/share/info (with possibly not gzipped info pages) detected

```

**Comment by achadwick** [comment]
None of those paths have anything to do with MyPaint.

Also, https://duckduckgo.com/?q=what+is+"__init__.py"
