### ISSUE TITLE
Ability to lock hover menu in fullscreen mode (Win 10)

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#870]
#### Description of the problem

Ability to lock hover menu in fullscreen mode. Now there are problems with drawing in fullscreen, even if interface hided, it shows up when user hovers top-side-bottom borders. So it's hard to draw near borders.

#### Basic system details

MyPaint version: [1.2.1+gitexport.bcf5a28d (Stable) and last alpha 1.3.0 from AppVeyor]
Operating system: [Windows 10x64 1703 15063.674]

#### Steps to reproduce

1. Start MyPaint
2. Open fullscreen
3. Hide interface
4. Hover borders

**Comment by achadwick** [comment]
Press tab to turn off autohide if it bothers you, or don't draw near the borders.

Users need to be able to access the interface when they don't have a keyboard, and there is no effective way of doing this right now other than the current "hover" solution. Therefore I don't intend to work on this.

Currently the auto-show is inactive if the pen is down. This ameliorates one source of irritation.

**Comment by zb13y** [comment]
I think this is problem. I see the fullscreen mode as "fullscreen canvas" without interface. And i see mypaint as simple canvas for drawing without interface, i remember that it was like this in previous versions. This is major.

> Users need to be able to access the interface when they don't have a keyboard, and there is no effective way of doing this right now other than the current "hover" solution. 

There are solution - uncheck autohide in menu. I just don't get for what this mode, if user can't draw freely in it?
If user need interface it can open it with tab (or button on stylus and pad). There are no need in hover.

> Currently the auto-show is inactive if the pen is down.

It's hard to draw like this, it allways shows up.

Pleae open this again. Fullscreen mode - base of the MyPaint.

**Comment by briend** [comment]
Maybe there is room for improvement.  I don't usually use fullscreen but here are my thoughts:
* auto-show is instant when cursor reaches an edge.  Maybe a tiny delay of 1/4 second would prevent most accidental auto-show without introducing pain for intentional unhides.
* panels don't "re-hide" automatically unless you lift the stylus away from pad for a long moment.  In my mind, as soon as I start drawing again I am done with the panels and would expect them to autohide immediately.  So, maybe a stroke_started event can re-hide the panels?

**Comment by zb13y** [comment]
> auto-show is instant when cursor reaches an edge. Maybe a tiny delay of 1/4 second would prevent most accidental auto-show without introducing pain for intentional unhides.

Don't think this is good idea, i think it will not work.

Here are my new proposal. But it have one minus (for user with only pen).
1. If autohide doesn't work, then there are no reason to leave it. https://github.com/mypaint/mypaint/issues/874
2. If autohide/autoshow removed, then if interface hided, there are problem with accessing to interface in fullscreen with only pen without buttons.
3. So the solution is to open fullscreen mode always with interface.
4. If user have keyboard or assigned button on the pen, he can hide interface and open it. If user don't have keyboard or assigned button on the pen, then user can't hide interface.
5. (optional) New problem, how to hide inteface with only one click, tap by pen.
6. (optional) Add one special button on interface that hide mostly all interface, but leaves this button to reopen interface. So user can watch his work without interface and draw without interface. This solution have one small minus - button that doesn't hide.

**Comment by briend** [comment]
> Don't think this is good idea, i think it will not work.
Could you explain why think so?  To me, the only reason it might not work is if you move your cursor to the edge for more than a few moments, which IMO doesn't happen when one is wildly sketching :-).  Your solutions are adding quite a bit more complexity and reduced functionality for people w/o keyboard.

Here is a relevant comparison to browsers.  Google Chrome seems to suffer from the keyboard problem:
https://productforums.google.com/forum/#!topic/chrome/ndKT1iyTaZQ
You can't get out of fullscreen without a keyboard.  Come on, Google!

On the other hand, Firefox seem to implement the idea that I suggested.   In Firefox, go into full screen and zip your cursor around bumping into all the edges (briefly! like you are sketching).  Nothing happens.  But move to the top edge and after a moment, the top bar will auto unhide.  +1 for Firefox!  Hope you don't mind @achadwick  I'm going to reopen this :-).

**Comment by zb13y** [comment]
Hm, i understood. So the goal is to add time that will give chance to user start new stroke near border. And if user starts to draw, unhide is locked (as now). But 500 ms is low, maybe 1500-2000 ms?

**Comment by briend** [comment]
Well, we could try different amounts of time to see what works best.  We should start as low as possible  to avoid creating a new annoyance

**Comment by briend** [comment]
I've been using fullscreen more often and this is starting to annoy me, so I might actually work on it soon :-)

**Comment by briend** [comment]
@zb13y I opened a pull request that adds 500ms delay, which seems to be about right imo.   Can you test?  There should be a windows build available from this PR here shortly:
https://ci.appveyor.com/project/achadwick/mypaint
direct link:
https://ci.appveyor.com/project/achadwick/mypaint/build/job/38sqsk84ec7eu0cc

**Comment by zb13y** [comment]
Unfortunately, now i can't test it.
