### ISSUE TITLE
Trying to swap Layer subwindow to other sidebar causes error/crash?

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#872]
**Specs:**
PC: Microsoft Surface 3
Stylus: Surface Pen 3
OS: Windows 10, 64-bit
Build: MyPaint 32-bit, 1.3.0-alpha+git.0b19fce4
_(Python 2.7.14, GTK 3.22.24, GdkPixbuf 2.36.11, Cairo 1.15.6, GLib 2.54.1)_

**The Error:**
Tried swapping multiple subwindows from the right side of the interface to the left. I got an actual error message from MyPaint when I tried moving the "Layers" subwindow, but I ignored it. Then, trying to do it more often (ie: brush folders, brush & color history, and settings tab) MyPaint froze, and then I got a "python.exe has stopped responding" error.
When I reopened MyPaint, the panels I tried to move to the left weren't visible, so I restored them. When I toggled the Layer panel, it reappeared on the left side. I think the main cause of the error is crowding a subwindow area with multiple tabs.

**Steps to Reproduce:**
1. Open MyPaint
2. Open up multiple subwindows, docking them on one side of the screen. (Example: Settings, Layers, Color Wheel, Palette, Brush & Color History, Favorite Brushes, and any mypaint brush folder)
3. Dock any windows except for the Layers. I would say the important step is to try not to "unclutter" the subwindow with multiple tabs.
4. Attempt to dock the Layers window.
5. Attempt to dock the Layers window to the opposite side to produce crash(?)
6. Attempt to dock other subwindows to opposite side to produce crash

This is the error message I get when I reproduced the error:

```python
Mypaint version: 1.3.0-alpha+git.0b19fce4
System information: Windows-10-10.0.15063-SP0
Using: Python 2.7.14, GTK 3.22.24, GdkPixbuf 2.36.11, Cairo 1.15.6, GLib 2.54.1
Traceback (most recent call last):
  File "C:/Program Files (x86)/mypaint-git-w32/mingw32/lib/mypaint/gui/workspace.py", line 1358, _deferred_swap_tool_widget_sidebar(self=<workspace._Notebook object at 0x0ef96734 (gui+workspace+_Notebook at 0x097f4b78)>, page=<workspace._ToolWidgetNotebookPage object at 0x0...workspace+_ToolWidgetNotebookPage at 0x0e8707d8)>)
                src_stack.remove_tool_widget(tool_widget)
                targ_stack.add_tool_widget(tool_widget)
                targ_stack.reveal_tool_widget(tool_widget)
  variables: {'targ_stack.add_tool_widget': ('local', <bound method ToolStack.add_tool_widget of <workspace.ToolStack object at 0x0987698c (MyPaintToolStack at 0x02dd0920)>>), 'tool_widget': ('local', None)}
  File "C:/Program Files (x86)/mypaint-git-w32/mingw32/lib/mypaint/gui/workspace.py", line 1634, add_tool_widget(self=<workspace.ToolStack object at 0x0987698c (MyPaintToolStack at 0x02dd0920)>, widget=None, maxnotebooks=None, maxpages=3)
            # We're good to go.
            target_notebook.append_tool_widget_page(widget)
            if self.workspace:
  variables: {'widget': ('local', None), 'target_notebook.append_tool_widget_page': ('local', <bound method _Notebook.append_tool_widget_page of <workspace._Notebook object at 0x0efb7cac (gui+workspace+_Notebook at 0x0f3ef2d0)>>)}
  File "C:/Program Files (x86)/mypaint-git-w32/mingw32/lib/mypaint/gui/workspace.py", line 1200, append_tool_widget_page(self=<workspace._Notebook object at 0x0efb7cac (gui+workspace+_Notebook at 0x0f3ef2d0)>, tool_widget=None)
                page = _ToolWidgetNotebookPage()
                page.add(tool_widget)
                label = self._make_tab_label(tool_widget)
  variables: {'tool_widget': ('local', None), 'page.add': ('local', gi.FunctionInfo(add))}
TypeError: Argument 1 does not allow None as a value
```

**Comment by jplloyd** [comment]
Can't replicate this with the latest stable release. I think this was related to an upstream issue that was fixed over a year ago. If it still happens with the latest stable release, make a comment and we'll reopen this.
