### ISSUE TITLE
Canvas Skewed / Stretching in comparison to Reality

### ISSUE THREAD

**Issue by crankbolt** [mypaint/mypaint#873]
[⚠ This tracker is for fixing and improving MyPaint.]
[☞ Use our Community Forum for support queries, or to suggest new features: https://community.mypaint.org.]
[☞ Please search before posting to avoid duplicates.]

#### Description of the problem

[✍ I am having issues with the canvas being stretched horizontally, as you can see in the pictures below the actual dimensions in reality are skewed when rendered to the canvas.  Not sure if this is because of my monitor and resolution or if it is the tablet.  Since Ultrawide monitors are pretty popular I thought I would explain the issues I am having.  

![intuos3dmypaint](https://user-images.githubusercontent.com/18075720/32138184-74428018-bbfc-11e7-99cd-b8fe6b2d6990.png)
![widthmypaint](https://user-images.githubusercontent.com/18075720/32138193-8299a808-bbfc-11e7-8370-33ff4f40c130.png)
![heightmypaint](https://user-images.githubusercontent.com/18075720/32138196-852624fc-bbfc-11e7-8213-601f1720facb.png)

 .]

[☞ Pictures and videos help us a lot. You can paste screenshots.]

#### Basic system details

MyPaint version: [✍ 1.2.1+gitexport.bcf5a28d]
Operating system: [✍Windows 10 Professional]
Desktop environment: [✍ N/A - Windows Default]
Monitor: Dell dell ultrasharp u3417w 
Resolution Setting: 3440 x 1440px
Tablet : Intuos 3D / 216.0 x 135.0 mm (8.5 x 5.3 in)
Tablet Model : CTH-690
Wacom Driver: 6.3.25-5

#### Steps to reproduce

[☞ Tell us how to reproduce the bug in clear, numbered steps.]

1. Start MyPaint
2. [✍ Using the tablet (which has a dot grid printed on the surface) draw a perfect square connecting the dots on the surface]
3. [✍ Compare the lengths from dot to dot on the actual tablet to the lengths which are rendered on the canvas in mypaint]
4. [Note the significant stretching horizontally, I used Meazure V 2.0.1 to confirm that the image is skewed nearly 100px

None

```
[✍ Paste any error messages here between the ``` lines.]
```

**Comment by briend** [comment]
Look in your Wacom driver settings.  You need to change the Wacom to map to the monitor size.  You will lose some working surface on the tablet though as it will letterbox it

**Comment by crankbolt** [comment]
My goodness, thank you for the quick reply!  I am not sure how I missed this, I really appreciate your help!
