### ISSUE TITLE
Panning/rotating etc re-renders tiles instead of using cache

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#877]
I noticed panning can slow down (well, for me with the OCIO testing), and when I turn on visualize rendering it lights up whenever panning, zooming, rotating etc.  Should these operations use the cache?  I can understand if you move a layer you have to re-render all the tiles, but panning should theoretically not require that.

**Comment by achadwick** [comment]
Visualize Rendering shows where it renders tiles (which may come from the cache, or may be re-rendered there and then), not where cache hits take place.

**Comment by briend** [comment]
Oh good!  Thank you!
