### ISSUE TITLE
Proposal: Use Raspberry Pi 3 as a performance test platform

### ISSUE THREAD

**Issue by hzulla** [mypaint/mypaint#885]
#### Basic system details

MyPaint version: [1.2 from Raspbian repo](http://archive.raspbian.org/raspbian/pool/main/m/mypaint/)
Operating system: [Raspbian Stretch](https://www.raspberrypi.org/downloads/raspbian/)
Desktop environment: Raspberry Pi Desktop (LXDE variant)

#### Steps to reproduce

1. Give Wacom bamboo [graphics tablet as a Christmas present to your kid](https://www.raspberrypi.org/forums/viewtopic.php?t=198613)
2. Install Wacom drivers on your kid's Raspberry Pi 3
3. Install MyPaint from Raspbian repo
4. Let your kid draw with it
5. Wait half an hour
6. Watch MyPaint lag and or crash
7. Marvel at the surprising range of curse words that you didn't know your kid already knew

#### Description of the problem

*This issue is a request to MyPaint developers to use the Raspberry Pi 3 as a testing platform for benchmarks and performance hacking.* As the old saying goes: If you want to improve the performance of a software project, give the developers a slow computer. The RPi3 is that computer. It is readily available, on first glance it is fast enough for casual MyPaint use, but once you actually use it on that device, things will soon go wrong. It appears that the RPi3 marks the breaking point of MyPaint's hardware requirements.
 
* Input starts [lagging](#883) in certain conditions
* MyPaint locks up repeatedly when using the Color Bucket fill tool (but steps were not reproducable)
* It is possible to lock up the operating system itself while using MyPaint, requiring a power-cycle (again, steps were not reproducable, possibly memory-related?)

The easy way out is obvious - abandon the RPi3 and get a faster computer. But then again, the RPi3 is so close to being useful, it seems that there is not much missing.

And there seem to be a number of low-hanging fruit worth chasing, as written down in two long documents on how to improve performance for [libmypaint](https://github.com/mypaint/libmypaint/blob/master/PERFORMANCE) and [MyPaint](https://github.com/mypaint/mypaint/blob/master/doc/PERFORMANCE). These documents are old and it is entirely unclear how many of these ideas have been tried out since @jonnor suggested them.

So with these ideas out there and the fact that the RPi3 is the first "own" computer for many youngsters out there, please try to make MyPaint work better on it.

It is also possible that this isn't an issue with MyPaint itself, but just with the way it is packaged for Raspbian. It is using the Debian packaging and there may be suboptimal settings or library choices coming with it. If that is the case, please help the Debian/Raspbian developers to improve things there.

Thanks.

**Comment by achadwick** [comment]
Okay, noted. Not a great deal that I can do about this myself, however.

Do you have any specific patches for the codebase right now? I really would appreciate some patches that improve performance, or patches to improve the documentation.

I do not have this hardware available to test with, unfortunately, so I have to rely on users to send in patches.

The lockups with fill are a thing. The implementation should provide way better feedback than at present: the fill needs to proceed in a background idler of some sort so that GTK can run a bit.  Or some future thready thing.

If you are locking up your OS, you are likely to be encountering an out of memory condition. That is something I'd definitely like to address with some smarter code - can we use on-disk caches to any great effect? Could MyPaint refuse to allocate a tile on tiny machines?

At this point, this issue is a discussion thread. I'd like to either move it towards something concrete that can be done by a developer, or close it.

**Comment by hzulla** [comment]
First of all, thanks.

A helpful thing would be if the `PERFORMANCE` documents could be updated to reflect the current state of the code. Have any of these proposed ideas already been tried, which ideas are (still) worth chasing?

Also, it might help if you could have a look at Raspis/Debian's packaging. The Debian developers are doing a great job to get software distributed to a wide range of hardware, but sometimes a little help from an application's core developer can help identify suboptimal compiler settings or library choices.

Finally, I can only ask more core developers to try MyPaint on the RPi3 for themselves. A few tweaks may achieve a lot on that platform.

**Comment by DanielJoyce** [comment]
The Raspberry Pi uses propietary 3D drivers AFAIK. If the perf degrades or crashes, I'd suspect those first. Is there anything in the logs or x log?

**Comment by hzulla** [comment]
The RPi foundation is funding development of an open source driver, which is slowly coming to the mainline kernel. Have to admit I do not know which driver is currently in use on Raspbian, but at least they are working on it.

That said, I doubt that it is the graphics driver, but suspect memory issues. The RPi only has 1GB of memory.

Will have to find how to properly log the problems.

**Comment by achadwick** [comment]
IO performance to SD may be causing issues during painting. Try turning "Back up unsaved work" off, and please report back whether that makes a difference.

**Comment by hzulla** [comment]
Yes, it seems to make things better.

I will try later with my kid at the helm. Let's see if she can crash it again.

**Comment by hzulla** [comment]
Ok, the "automated backups" setting seems to make a major difference. My kid painted with her graphics tablet yesterday for about 1.5 hours without a crash.

I didn't watch over her should all the time, so I don't know which mypaint tools she was using and it's unclear wether the "fill tool" freezes mentioned above are also fixed by the setting.

So, this improves things. mypaint is still fairly laggy and slow on the RPi3, so there is room for improvement, but it's fast enough for my kid.

**Comment by hzulla** [comment]
Another 1hr drawing session today. The RPi didn't crash, but turned unresponsive twice for several seconds, once while using the fill tool. MyPaint would always return from that, but my kid was quite frustrated.

We moved to the i5 desktop afterwards. First thing she did in MyPaint was use the graphics tablet to scribble "dear dad, this computer is much better" with the symmetry tool active.

**Comment by jplloyd** [comment]
While I agree with the general sentiment about improving performance, I don't think it's reasonable to optimize around a platform that at most a tiny minority of users would be using. 

The reasonable thing to do is to set a regular x86 CPU to run at a lower clock (e.g. using a power-saving governor mode) when doing general gui testing, and optionally artificially limiting memory allocation for the process.
