### ISSUE TITLE
UGEE 2150 GT -OFFSET 

### ISSUE THREAD

**Issue by PencilKnight** [mypaint/mypaint#886]
So its my first time posting something here, i have a big problem atm. 
My Ugee worked fine till 12 am but after an windows update i got a weird offset problem in Krita, PS and even SAI doesnt work anymore. i have no offset if im just browsing or do something aside of entering the driver menu or a paintingprogram. The offset isnt stable ist like the further i turn to the left side, the bigger the offset gets. 
I hope someone out there can help me :s !
My monitors have both the res of 1920x1080, zoom is at 100% 
my operating system is win 10 
im working atm on ps cs 5 

It works all fine if i switch to duplicate or on only using the ugee

**Comment by achadwick** [comment]
Does this affect MyPaint?  Which version of MyPaint does it affect please?  Please paste the entire wodge of versions out of the "About MyPaint" dialog.

Please try reinstalling your Ugee drivers if you haven't already.

Offsets in Windows multi-monitor settings are distressingly common, and there is nothing we can do about it until the GTK project fix it. 

An alpha build of MyPaint might help, as it could be using a newer libgtk.

**Comment by PencilKnight** [comment]
not anymore somehow with the newer patch from ugee it got solved!
Im sorry for not closing this thread :( :s
