### ISSUE TITLE
Gamut mask does not match between editor and 

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#889]
#### Description of the problem

As reported by [@ArykaBrimmer on Twitter](https://twitter.com/ArykaBrimmer/status/954921049069514753), editing the gamut mask in the HCY tool's options does not update all the connected colour wheels of that type.

#### Basic system details

MyPaint version: 1.3.0-alpha+git.612be97c (Python 2.7.14, GTK 3.22.26, GdkPixbuf 2.36.11, Cairo 1.15.8, GLib 2.54.2)
Operating system: Debian testing/unstable
Desktop environment: Xfce

#### Steps to reproduce

1. Start MyPaint
2. If necessary, open the HCY Wheel in a sidebar.
3. Open its Gamut Mask editor by clicking on the wrench icon
4. Click on Clear if necessary.
5. Create a new mask shape by clicking in the wheel
6. Click on OK to accept the new mask.
7. Click in the lower-left corner colour indicator to bring up the chooser popup
8. Set it to "HCY wheel" if necessary
9. Note that the masks match for now.
10. Open the Gamut Mask Editor again, and repeat steps 5 through 8.
11. Note that the mask in the indicator popup no longer matches.

### Screenshot

![](https://pbs.twimg.com/media/DUCPhFjV4AAlWeu.jpg:large)

**Comment by briend** [comment]
Maybe same as #655?

**Comment by achadwick** [comment]
Yep. The insight from that old issue is that the mask is read from prefs at start.

The mask needs to be treated like the existing managed palette in the central ColorManager object. That way, other wheels and colour selectors might be extended to use it too.  Currently it's just read from prefs once at startup by each HCY wheel instance.

Closing #655 in favour of this one.

**Comment by jplloyd** [comment]
Fixed in 4b474abfe3cc4fcb10fbdf6f3df719960bb2bfc7

It is not a very satisfactory solution in terms of code quality, but I think that fixing it properly would require a substantial refactoring of the classes in the module. It is at least fully functional, and a very readable patch.
