### ISSUE TITLE
Use Rec 709 luminance weights and linear for HCY tools

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#890]
I'm creating a patch here:
https://github.com/briend/mypaint/tree/LumaFix1

Some background from Bruce Lindbloom:
http://www.brucelindbloom.com/index.html?Eqn_RGB_XYZ_Matrix.html

> Perhaps you've learned that you can compute the luminance of an RGB color by taking 30% of its red component plus 59% of its green component plus 11% of its blue component. These weightings are often expressed in three-digit precision as 29.9% red, 58.7% green and 11.4% blue. Did you ever wonder where these weightings came from?

>You can find them in the above table as the relative Y values for red, green and blue for the NTSC color model. The more precise weightings are 29.8839% red, 58.6811% green and 11.4350% blue. But it should also be obvious that the real RGB weightings depend upon the color system in use. So the "standard" weightings are incorrect for other RGB systems like sRGB or Adobe RGB (1998).

>Another relevant fact is that these weightings must be made in a linear RGB space, that is, after the gamma companding function has been removed. It is very common to see the weightings applied bluntly to the companded RGB values, which is wrong.

On the left is unpatched mypaint and an attempt to "luminance match (Y)"  (using alt-R or pick luma- Luma is the wrong word here) the yellow color with the other colors.  As you can see, it is pretty unsatisfactory.  On the right is a patched mypaint with the sRGB luminance weights and the functions to convert to linear beforehand
![lumafix](https://user-images.githubusercontent.com/6015639/35224962-2a4f131e-ff44-11e7-89e3-3325e9099eb0.png)

Here we can verify correctness by loading into Krita and converting the image to linear, then performing a desaturate- as you can see the colors disappear into each other because the luminosity is the same.
![lumafix2](https://user-images.githubusercontent.com/6015639/35225652-203ae0c2-ff46-11e7-8e0b-2f9ee8cbe81a.png)

There are several things affected, the HCY circle, guis, and even the HCY palette "fill gap" option.  The bottom row of the palette in each screenshot was done with an HCY Fill Gap and the results are quite a bit different (better imo).

It would be really nice to get all the luminance  stuff to match and be "correct".  I know W3C has this standard here that we were following:
https://www.w3.org/TR/compositing-1/#blendingnonseparable

I can't really explain why the W3C is wrong, but it is :-).  The problem is if we fix the blending modes it will change the way existing images look.  At least with this current patch it should only affect the visuals of the interface and not break any old files.

**Comment by achadwick** [comment]
I see it's tripping all the HCY tests. Have you made it luminance instead of luma by accident or by design?

```
File "C:/projects/mypaint/lib/color.py", line 503, in lib.color.HCYColor.__init__
Failed example:
    HCYColor(color=RGBColor(0.5, 0.5, 0.5))
Expected:
    <HCYColor h=0.0000, c=0.0000, y=0.5000>
Got:
    <HCYColor h=0.0000, c=0.0000, y=0.2140>
```

The HCY circle looks way too bright at the edge. It needs to be as equiluminant as possible: that's the whole idea.

Luma is nice in that the HCY selector's Y (or Y') ramp looks nice and evenly gradated all the way up. That's a specific design goal here: steps of brightness should have the same meaning as screen.

(For layer compositing, we cannot just willy-nilly break OpenRaster, so please keep _that_ part as Rec.601 :) The linear vs. gamma-corrected thing needs some thought: in particular, MyPaint should use 16bpp linear internally (with a wider gamut than sRGB!), but detection of that and conversion to/from it is gonna need a format flag.)

Don't forget our own greyscale display filter, which should be helpful in testing this.

**Comment by briend** [comment]
I suppose I made it Luminance (Y) whereas before it was Luma (Y').  I'm still learning the difference :-)

The HCY circle is definitely weird, I think we need to look at the that grey gradient applied to the cairo wedges which is sorta an approximation anyway (the src says it is a "cheeky approximation"? ;-)

> Luma is nice in that the HCY selector's Y (or Y') ramp looks nice and evenly gradated all the way up. That's a specific design goal here: steps of brightness should have the same meaning as screen.

I think Luminance (Y) and not Y' will get us better results here.  Look at the screenshot again and compare the horizontal Hue bars on the component sliders.  The version on the right is much more consistent as far as luminance to the eyes/screen.  The left version has darks spots and looks splotchy.  It's hard to deny that the yellow-on-blue example is clearly off by a lot-- whereas for a lot of colors it's easy to say "hmm, that looks about right".

>(For layer compositing, we cannot just willy-nilly break OpenRaster, so please keep that part as Rec.601 :) The linear vs. gamma-corrected thing needs some thought: in particular, MyPaint should use 16bpp linear internally (with a wider gamut than sRGB!), but detection of that and conversion to/from it is gonna need a format flag.)

Agreed, I don't want to break ORA or existing stuff, I just want my colorpicker to work ;-).  The internal mypaint working space is definitely a MUCH bigger topic than this :-)

>Don't forget our own greyscale display filter, which should be helpful in testing this
I'm not sure, to really compare luminance the whole thing needs to be converted to linear.  I had to use Krita to double check my screenshots

**Comment by briend** [comment]
Hmmm
https://github.com/mypaint/mypaint/blob/master/gui/colors/adjbases.py#L1245-L1249

I think it would work a lot better if we could just use the HCY functions to reduce the chroma towards the middle of the circle, no?

**Comment by briend** [comment]
>Luma is nice in that the HCY selector's Y (or Y') ramp looks nice and evenly gradated all the way up. That's a specific design goal here: steps of brightness should have the same meaning as screen.

Oh yeah I see what you mean.  So, my changes make Hue look much nicer, but messes up the Y scale.  Maybe we can have both and use Y for the Hue and Chroma but Y' for the actual visual of the Y scale.  Should be possible. . .

**Comment by briend** [comment]
Interesting I cannot find a solid definition of HCY.  "HCY" alone implies luminance, which would necessitate the linear conversion.  This seems to fit the description here:
http://chilliant.blogspot.com/2012/08/rgbhcy-in-hlsl.html
but even this page links to another that uses the terms "luma" on it.  Also, there are several HCY' (luma) converters out there.

However, I think HCY (not Y') is what we ultimately want for achieving the equiluminance per slice, etc.  What really threw me off was that is we simply replace the Rec 601 weights with Rec 709 weights, it gets WORSE.  Somehow, by using the wrong weights it somewhat compensates for not doing the linear conversions.  So, we really need to do both, I think.

**Comment by briend** [comment]
Some progress, maybe.  That "cheeky" saturation gamma thing is actually not a problem at all, I didn't understand what it was doing really (barely do now).  And it is using the HCY functions to get the colors so nevermind about that.  So I added some 2.4 power functions to the Y scale and it seems really nice now, better than original with more even distribution of values.  Saturated blue is in a much more reasonable location on the Y axis, I think.  

The issue with the bright edges on the wheel is also evident on the Chroma slider.  As C reduces, we also get darker for some reason.  Haven't figured that out yet.

![screenshot from 2018-01-23 00-10-13](https://user-images.githubusercontent.com/6015639/35262471-1a01defe-ffd2-11e7-91a3-66cf8f2c554d.png)
![screenshot from 2018-01-23 00-12-13](https://user-images.githubusercontent.com/6015639/35262470-19e53466-ffd2-11e7-9bf9-d01e44dba0b8.png)

**Comment by briend** [comment]
So, I'm pretty confused.  The current HCY code seems to use algorithms from this [GLHS paper ](https://books.google.com/books?id=QwUMbEISxgQC&pg=PA56&lpg=PA56&dq=GLHS:+A+Generalized+Lightness,+Hue,+and+Saturation+Color+Model&source=bl&ots=HxFV8jrrpo&sig=Zde01RxmpJL9xxiNFD4WqXuZkcI&hl=en&sa=X&ved=0ahUKEwjdtv-Qku_YAhVR4WMKHYqYAP8Q6AEITjAI#v=onepage&q=GLHS%3A%20A%20Generalized%20Lightness%2C%20Hue%2C%20and%20Saturation%20Color%20Model&f=false)that is extremely hard to find the full text of.

I'm thinking of exchanging the HCY functions with some python ported versions of these functions:
https://github.com/tobspr/GLSL-Color-Spaces/blob/master/ColorSpaces.inc.glsl
These are clearly using luminance as in Y and not Y'.  So, maybe Chroma will work better.  Failing that we might need to use something more powerful like colorspacious:
https://github.com/njsmith/colorspacious

**Comment by briend** [comment]
closing this, going to suggest something else.... this problem is much bigger than I thought
