### ISSUE TITLE
AssertionError on autosave

### ISSUE THREAD

**Issue by black-silence** [mypaint/mypaint#893]
#### Description

Current git version sometimes crashes when autosaving.

#### Steps to reproduce

Mypaint was open for a while, I had a Graphire 4 plugged in, but was using firefox so mypaint wasn't really active. It happened several times but I can't say I can force it to reproduce.

#### Traceback

```python
Mypaint version: 1.3.0-alpha+git.046ec8fb
System information: Linux-4.14.15-1-ARCH-x86_64-with-glibc2.2.5
Using: Python 2.7.14, GTK 3.22.26, GdkPixbuf 2.36.10, Cairo 1.15.10, GLib 2.54.0
Traceback (most recent call last):
  File "/usr/lib/mypaint/lib/document.py", line 565, _autosave_countdown_cb(self=<Document nlayers=1 bbox=Rect(640, 128, 640, 1152) paintonly=False>)
            self.sync_pending_changes(flush=True)
            self._queue_autosave_writes()
            self._autosave_countdown_id = None
  variables: {'self._queue_autosave_writes': ('local', <bound method Document._queue_autosave_writes of <Document nlayers=1 bbox=Rect(640, 128, 640, 1152) paintonly=False>>)}
  File "/usr/lib/mypaint/lib/document.py", line 586, _queue_autosave_writes(self=<Document nlayers=1 bbox=Rect(640, 128, 640, 1152) paintonly=False>)
            assert not self._autosave_processor.has_work()
            assert self._autosave_dirty
            oradir = os.path.join(self._cache_dir, CACHE_DOC_AUTOSAVE_SUBDIR)
  variables: {'self._autosave_dirty': ('local', False)}
AssertionError: 
```

**Comment by gwojcik** [comment]
This problem start to appear after commit 23bde159c0efb355d which added line:
``` python
        self.sync_pending_changes(flush=True)
```
in `_autosave_countdown_cb` in `lib/document.py`

Passing `flush=True` to sync_pending_changes in `_autosave_countdown_cb` also causes other problems. It causes writing to canvas currently edited shape in inking, line and other tools.

In some situations it can cause this AssertionError.
**Steps to reproduce**
1. chose connected lines tool. 
2. draw first segment of line
3. press left mouse button, wait for couple of seconds, `_autosave_countdown_cb` will be called and line will be saved on canvas.
4. release mouse button
5. after couple of seconds another `_autosave_countdown_cb` will be called and AssertionError will appear.

It looks like `_queue_autosave_writes` is called two times, for automatic periodic save and after release mouse button. In first `_autosave_cleanup_cb` is called and self._autosave_dirty is set to False, second call to `_queue_autosave_writes` fails on assertion.

**Comment by briend** [comment]
I'm noticing this error too, typically when I alt-tab and leave mypaint to go back to browsing or whatever.

**Comment by achadwick** [comment]
It's a call for syncing changes from (future per-doc) palettes and perspective points into the per-doc settings. But maybe the granularity is wrong. Perhaps the ObservableDict should have a sync-pending-changes mechanism too.

The AssertionError went away in 9ef48a3308bfcff3e425f2e532fb505ed7409511 (lazy commit!), but if it's disrupting the inking tool, that's bad.

Let's also check that 5d3c2be2e58adb770f624b1b0ac03e84383d8c38 didn't indtroduce any nasties. Anyone want to pick up this bug to work on?

**Comment by achadwick** [comment]
So to recap, it's inappropriate to sync the entire doc for autosave backups (specially not full) merely because there may be addons with data to write to the settings. Instead, let's just sync the per-doc settings at those critical times.

Autosave backups are designed to be not too particular about data sync to prevent weird behaviour like the inking mode's current line being summarily finished when the doc needs to do an autosave backup.

Autosave backups are broken for other reasons right now: #904, but that might be unrelated.

**Comment by achadwick** [comment]
I just checked with the inker, and 8790eb3 fixes _that_ undesirable behaviour. I'm using that as a proxy for this bug's original issue.

@gwojcik as you've had a good look at this one, can you please look into the additional _queue_autosave_writes()?

@black-silence autosave backups are currently broken on master for other reasons so you will not be able to test this without a local development copy just yet. I'm working on this today (see #904).
