### ISSUE TITLE
Last alpha's doesn't work. Windows 10.

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#902]
#### Description of the problem

Last alpha's doesn't work. 1.3.0-alpha+master.188 - works.

#### Basic system details

MyPaint version: [1.3.0-alpha+master.223 also 1.3.0-alpha+master.214]
Operating system: [Windows 10 1709 16299.248]

#### Steps to reproduce

1. Start MyPaint

#### Backtraces or error messages

```
[Running python2.exe...
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'C:/Program Files/mypaint-git-w64/mingw64'
INFO: lib.i18n: Windows: LANG='ru_RU'
INFO: lib.i18n: Windows: LANGUAGE='ru_RU'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'ru_RU'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
Traceback (most recent call last):
  File "mingw64/bin/mypaint", line 465, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/gui/main.py", line 96, in main
    from gui import application
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/gui/application.py", line 47, in <module>
    import lib.document
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/document.py", line 27, in <module>
    from lib.fileutils import safename
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/fileutils.py", line 26, in <module>
    import lib.helpers
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/helpers.py", line 27, in <module>
    import mypaintlib
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 17, in <module>
    _mypaintlib = swig_import_helper()
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 16, in swig_import_helper
    return importlib.import_module('_mypaintlib')
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _mypaintlib
python2.exe exited with status 1.
Press return to close this window.
]
```

**Comment by briend** [comment]
Yow, yeah these have been broken for a while now, #188  (Jan 8th 2018) does seem to be the last good build.  The weird thing is, I have a local MSYS2 installation and I can create Windows bundles that work just fine.  So I'm not sure what the difference is other than my MSYS2 installation being more up-to-date than AppVeyor's.  @achadwick  any ideas?  I saw there were a few commits to Styrene around the time it broke, but like I said my own MSYS2 is working.  Maybe we just need to wait for AppVeyor to update the build images to new versions of MSYS2?

**Comment by achadwick** [comment]
Weird: there should be a `pacman -Syu` in the build, so AppVeyor's build should be OK.

I'm chasing some oddities with recent Py3 fixes on MSYS right now, but I'll try to see what's up.

**Comment by briend** [comment]
I setup my own appveyor and tried various build images (2015, 2017, 2017 preview) and they are all broken in this same way.  The build scripts do not upgrade or even update the cache, probably for good reason-- I tried inserting a pacman -Sy into the appveyor script (just so I could install a new package) and it seemed to trigger a massive upgrade that killed the build.

**Comment by briend** [comment]
I just tried the latest alpha windows build and it appears to be fixed.
