### ISSUE TITLE
Revert autosaving back to set minutes rather than "inactivity", or allow users to choose the autosave style

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#903]
Mypaint 1.2.1 stable release

I was in the middle of working on an important file, and when I tried to save it, MyPaint had an error. Turns out that the error was that the file wouldn't save. (probably because my file was saving to Google Drive and couldn't sync yet, so this part isn't the MyPaint bug.)
I thought it would be fine because I have autosave turned on.
Except that I checked my preferences, when I tried to re-open the file, and because the autosave is based on inactivity rather than just as set quantity of time, I lost all my progress because I was working on the file non-stop. I tried checking the autosave cache, but nothing.
And before anyone tells me that I shouldn't have been testing mypaint to use this file: again, it was a stable release.
This style of autosaving is not efficient or good for artists, and counterintuitive. Not to mention, immensely frustrating. Again, autosave should give peace of mind for artists, and the inactivity basis of this autosave does the complete opposite. If the inactivity autosave works for people, that's fine; but it doesn't work for me, and I don't want other users to get blindsided by it.

**Comment by achadwick** [comment]
:-1: Using a specified quantity of time would be highly counterproductive given the nature of the autosave feature. It might potentially interrupt users work more rudely than the current inactivity-based timer, and cause them to think MyPaint is laggy and slow.

Press Ctrl+S if you want to save the document now. The automated backup feature is a disaster recovery tool, not a substitute for regular saving.

Do not rely on the automated backup feature as a save tool. It isn't The clue is literally there in the name of the feature.

In your case, I'm sorry. Pressing Ctrl+Shift+S and saving to a different file may help in a scenario like this. You didn't give me the error message, so I have no idea what the original problem was.

I strongly recommend you turn off this feature if it doesn't work for you.

**Comment by AtsusaKaneytza** [comment]
@achadwickI just said that I did press "CTRL+S" to attempt to save my file (And again, I tried to save the file MANUALLY to the location I have it stored at multiple times!) And does the situation I JUST described in this post was a situation where I DID attempt to save the file normally but it didn't. So no, I am not using autosave as substitute for regular saving obviously. Because I just said that I tried to do a normal save and it didn't.
And I did not save the file in a different location because I am used to getting MyPaint error messages when I'm trying to save a file, and the file is in tact after the error message (whether I quit MyPaint or I ignore the error manually.)
So you're disregarding my entire post because you don't believe that a file that doesn't sync correctly to a cloud save doesn't count as "disaster recovery?" Even though I suggested an alternate solution for the feature that addresses your concern about people mistaking MyPaint for being laggy?
Again, my situation, despite you not believing it to be "disaster recovery" was a file that I was working on for a client, using a STABLE release build of the software so I wouldn't have to make a report like this.
And I see the discussion of this feature being implemented is in #90, with @iirelu saying what I just did: have various options in the settings in response to the concern you address , or if I'ere: autosave slowing down someone's computer.
https://github.com/mypaint/mypaint/issues/90#issuecomment-54753202
And again, to address my original issue: MyPaint had an error message popup before I closed the software. So shouldn't the prompt of an error message during the use of MyPaint at ANY TIME prompt an autosave, especially when I have no idea what the error is, or if I have no idea how to report it?

**Comment by briend** [comment]
Please try to reproduce the original error when you tried to save it, and create a new issue for that and paste the entire error message.  It sounds like you get a lot of error messages and just ignore them, please don't do that-- report the errors so they can get fixed.  From what I know about Google Drive it really shouldn't cause any problems to save to it.

Regarding the autosave, I think if it was strictly based on time (saving every 10 seconds or whatever) then you'd probably get a hiccup in your drawing all the time, which would be really annoying.

**Comment by AtsusaKaneytza** [comment]
@briend I will do what you asked of me regarding posting error messages more often.
However, regarding the autosave thing again:  Medibang Paint and FireAlpaca are (popular) free softwares that have time interval-based autosaves, which are optional in the user's settings. (FA is intended for ease of use on slower/older PCs as well)
There is a slight pause when autosaving the file, but I'd hardly call that an annoyance with regards to making sure an artwork is backed up.

**Comment by colin-heberling** [comment]
I strongly agree with AtsusaKaneytza that there needs to be an option for time-interval-based autosaving.  As it stands now, the autosave feature doesn't even work as a disaster recovery tool because if you're drawing/painting the entire time before you decide to manually save, and there's a bug which prevents it from saving (see my issue #1155, later comments related to version 2.0), then the inactivity condition will not trigger an autosave, so you're left with nothing.  If the autosave occurred based on time then until the saving bug is fixed (which it seems like no one can reproduce the bug on command yet) then users would lose a lot less of their work.  I've used Krita which implements the time-based autosaving, and I haven't seen any lags due to autosaving.  Besides, the time interval of the autosave should be configurable anyway, or able to be turned off completely.
