### ISSUE TITLE
python3 thumbnail/png issue

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#905]
If your image does not already have a thumbnail generated, it seems to error when you click on it.  There should be a preview thumbnail on the right side, but instead it errors.  However, it does successfully open if you ignore the error (edit- unless it is a PNG file)

Reproduce: run mypaint demo w/ python3.  Navigate to folder with images and observer previews.  If they are all working, open a terminal and copy one of the pictures manually to avoid thumbnail generation.  Observe the copy in the File-Open dialog again and it should have a generic icon and error message when clicked on.

Debian Stable
XFCE 4.12
MyPaint 1.3.0-alpha+git.b'feb564c5\n' 
(Python 3.5.3, GTK 3.22.11, GdkPixbuf 2.36.5, Cairo 1.14.8, GLib 2.50.3)

> WARNING: lib.helpers: thumb: cache file '/home/bd/.cache/thumbnails/large/a85d5f90cc3ae9716dbe609f21968f25.png' looks corrupt ('gdk-pixbuf-error-quark: Unrecognized image file format (3)'). It will be regenerated.

The thumbnail file will be created but zero bytes.  If you delete the thumbnail it comes right back again as soon as you click on the filename from MyPaint File Open Dialog, but it is zero bytes again.

> Traceback (most recent call last):
>   File "/tmp/demo-ei765k8x/lib/mypaint/gui/filehandling.py", line 980, in update_preview_cb
>     pixbuf = helpers.freedesktop_thumbnail(filename)
>   File "/tmp/demo-ei765k8x/lib/mypaint/lib/helpers.py", line 295, in freedesktop_thumbnail
>     **png_opts
>   File "/tmp/demo-ei765k8x/lib/mypaint/lib/pixbuf.py", line 78, in save
>     list(kwargs.values()),  # option_values
> TypeError: Item 1: Must be string, not bytes

Also, I just realized loading PNG files doesn't work.  Loading JPG or ORA files is fine though.  I think these are closely related so I'll keep it as one issue:

> ERROR: lib.document: Failed to load '/home/bd/Documents/ART/2013-06-29.png'
> Traceback (most recent call last):
>   File "/tmp/demo-6300vby3/lib/mypaint/lib/document.py", line 1482, in load
>     load_method(filename, **kwargs)
>   File "/tmp/demo-6300vby3/lib/mypaint/lib/document.py", line 1692, in load_png
>     bbox = self.load_layer_from_png(filename, 0, 0, progress, **kwargs)
>   File "/tmp/demo-6300vby3/lib/mypaint/lib/document.py", line 1303, in load_layer_from_png
>     bbox = s.load_from_png(filename, x, y, progress, **kwargs)
>   File "/tmp/demo-6300vby3/lib/mypaint/lib/tiledsurface.py", line 613, in load_from_png
>     convert_to_srgb,
> TypeError: in method 'load_png_fast_progressive', argument 1 of type 'char *'
> ERROR: gui.filehandling: IO failed (user-facing explanations: Could not load “2013-06-29.png”. / Error loading “2013-06-29.png”.
> 
> Reason: in method 'load_png_fast_progressive', argument 1 of type 'char *'
> 
> The logs may have more detail about this error.)
> Traceback (most recent call last):
>   File "/tmp/demo-6300vby3/lib/mypaint/gui/filehandling.py", line 316, in call
>     result = func(*args, **kwargs)
>   File "/tmp/demo-6300vby3/lib/mypaint/lib/document.py", line 1497, in load
>     raise FileHandlingError(error_str)
> lib.errors.FileHandlingError: Error loading “2013-06-29.png”.
> 
> Reason: in method 'load_png_fast_progressive', argument 1 of type 'char *'
> 
> The logs may have more detail about this error.

**Comment by achadwick** [comment]
Just noticed the first issue myself. It's a problem with `lib.pixbuf.save()`, which is being needlessly fussy about those special PNG options args the thumbnailer needs to pass when saving the cached preview. It boils down to `str` being a Unicode type in Py3 and not in Py2.

I'll be solving it this evening in the Python 3 Porting Approved Manner (by throwing test cases at it to reproduce, then making sure any fix works verifiably across the board).

:snake: :snake: :snake: :bug: :snake:

**Comment by achadwick** [comment]
The **second issue** looks like a swig string passing cockup to our custom PNG reader (`lib/fastpng.c` and `.h`). C-style funcs receiving `char *` looked OK on mine. <s>Works for me</s> ... I mean, evidently there's some variance between systems...!

:thinking: It may be simpler to pass a file-like object to `load_png_fast_progressive()` as well. Something like the reinstated way of working in acb10b6bc162b3d14cb51aeaf99e62fe816fa034.

Anyway, it's unrelated to the first backtrace you gave. It might be quite dependent on your environment too. Can you report it separately, with lots of OS detail and the output of `locale` and `locale -a` please?

Also, please can you test that one with [`clean --all` / `build_ext --swig=/path/to/swig3.0`, `build`, `demo`] as well please? See then end of `.travis.yml` for an example. Swig 3 or later _may_ be needed for Py3 support, and string handling is a thing that has changed some between old and new swig. Swig 3 is available from Ubuntu backports as far back as Trusty, so it can be considered widely available.

**Comment by briend** [comment]
Thanks @achadwick, I'll do more thorough testing tonight

**Comment by achadwick** [comment]
@briend
Please report the loading issue separately when you can, thanks! That code may need yet another rewrite to cover all the target platforms. It's looking unreliable in Py3 on Windows right now :roll_eyes::newspaper_roll:
