### ISSUE TITLE
Pen Pressure on Windows

### ISSUE THREAD

**Issue by kelunik** [mypaint/mypaint#909]
#### Description of the problem

Thanks for MyPaint! I'm using it on Windows and it's working pretty fine so far, except for the pressure of pencils. I'm on a Lenovo ThinkPad L380 Yoga, which has a touch pen built-in that supports different pressure levels. Other programs work fine with different pressure applied.

Is this a known issue? Did I miss some way to configure the pen? The settings just show it as "mouse" with two axes, I guess a pen with pressure support should show up as three axes there? Not sure, whether pressure is considered an axis.

#### Basic system details

MyPaint version: 1.2.0-beta.1 / 1.2.1
Operating system: Windows 10
Desktop environment: Windows

#### Steps to reproduce

1. Start MyPaint.
2. Draw with a pencil.
3. There's no difference based on the pressure.

**Comment by odysseywestra** [comment]
Go to Help>Debug>Test Input Device, and then draw on the canvas so you can see if MyPaint even sees the pressure input. Posing a screenshot here would be nice as well. If MyPaint cannot see pressure, then this my be an upstream issue with GTK/GDK(what we use for pen support), and will probably have to be reported there as well.

I'm also assuming you tired our latest alpha build as well? You can get them here: http://mypaint.org/downloads/#windows

**Comment by kelunik** [comment]
@odysseywestra It says `(no pressure) / (no tilt)` (translated from the German interface), so I guess it has to be reported upstream. Do you have a link to the correct repository?

**Comment by odysseywestra** [comment]
@kelunik This should have the info for what you need to do: https://github.com/mypaint/mypaint/wiki/Debugging-tablet-issues-on-Windows#reporting-bugs-in-gtk-or-gdk

**Comment by kelunik** [comment]
My bad, installing the WinTab driver helped! Interesting that it worked in other programs without the driver... https://support.lenovo.com/de/de/downloads/ds502297

Thanks for your help!
