### ISSUE TITLE
Portable MyPaint for PC

### ISSUE THREAD

**Issue by ghost** [mypaint/mypaint#91]
I want to take this program with me everywhere I go.

For every stable version, please release two portable 7z archives for us PC users. One 32-bit build, one 64-bit build.

7-Zip compresses well, and most PC users who go portable have enough gumption to learn how to extract a 7z file.

**Comment by achadwick** [comment]
**Triage note:** Discussion petered out ages ago. No plans to implement this for 1.2 or beyond *within the MyPaint core team*. Unofficial builds may do something quite different, and you should badger them about it. Tidying up... if anybody wants this, come back with a plan.

\</ruthless-triager-mode\>

**Comment by GordCaswell** [comment]
PortableApps.com has released a Portable package of MyPaint 1.2.0: https://community.mypaint.org/t/mypaint-portable-1-2-0-released-by-portableapps-com/460
