### ISSUE TITLE
Version user brush paths

### ISSUE THREAD

**Issue by Jehan** [mypaint/mypaint#914]
#### Description of the problem

If I understand correctly, currently user-installed brushes should be inside `$XDG_DATA_HOME/mypaint/brushes`.
Following our process to make brushes more generically used by other projects, which means separating the `libmypaint` library and `mypaint-brushes` (#842) into separate versionned packages, it would be nice if the user-installed data (brush in particular) were versionned too. Especially since we currently have crashes when loading some v2 brushes into libmypaint v1 (https://github.com/mypaint/libmypaint/issues/101).
And anyway even with no crashes, brushes evolve and may lose compatibility with time, which is ok and expected.

The `mypaint-brushes` installation package is versionned. Could we also version the data directory for user-installed data?

I would like to propose: `$XDG_DATA_HOME/mypaint/<version>/brushes`, i.e. `$XDG_DATA_HOME/mypaint/2.0/brushes` for newer data.

Once such a path is well "standardized" upstream (i.e. by MyPaint project), it will be very easy for other projects to look in these folders to also load user-installed data, and do so in a versionned way depending on which libmypaint version we are using.
Thanks!

P.S.: I am proposing this versionning happens from MyPaint 2, since it never even had a release. Then we can consider any brushes in older non-versionned path to be v1 data.

**Comment by odysseywestra** [comment]
Versioning has been applied to the brush repository. We are currently at 2.0.1
