### ISSUE TITLE
Palette editor gets confused with duplicate colors

### ISSUE THREAD

**Issue by briend** [mypaint/mypaint#922]
MyPaint 1.3.0-alpha+git.82ce4549
Debian Stable, Windows 10, etc

Issue:  When you have duplicate colors in the palette editor it becomes very difficult to click on them and it becomes confused.

Reproduce:  Open the editor with the wrench button and clear the palette.  Add a few rows and then add two identical colors and another different color.  Now try selecting each color, and then an empty box, and try selecting one of the colors again.  Often times you won't be able to select either of the duplicate colors (or drag+drop them anywhere) until you perform some additional actions like selecting a 3rd color that is unique, or just clicking around randomly on empty squares.  Sometimes a different box is selected even though you didn't click on it, for instance if you click the "1st" red box, the "2nd" red box might get selected.

Notes:  I think it has something to do with the "nearest match" code that the palette uses.  Whenever you select a new brush color, this function kicks in to select the nearest palette color.  However, this function seems pretty redundant to activate when you are actually clicking on a palette color.  Maybe this behavior is a separate issue to the first.

I believe the relevant code is around here:
https://github.com/mypaint/mypaint/blob/master/lib/palette.py#L310

![image](https://user-images.githubusercontent.com/6015639/38656578-46dedd96-3dd0-11e8-82d3-1381cf4f5b5c.png)

**Comment by briend** [comment]
Not to get too off-topic but maybe even use a color appearance model (yeah I've been goofing around with colorspacious ciecam a lot lately) to only match colors within a certain small distance and probably be a bit more accurate than RGB

**Comment by WilliamDann** [comment]
I want to try and solve this

**Comment by 0ion9** [comment]
@briend Sorry, this is an off-topic post, but I couldn't figure out how else to contact you on github:

Your pull request https://github.com/mypaint/mypaint/pull/853 consistently times out ('This page is taking way too long to load. Sorry about that. Please try refreshing and contact us if the problem persists.')-- ie. I can't view it at all. Has been the case for about a week now, at least.

Just mentioning in case there is something you could do to fix it or at least an identifiable cause for it. Maybe it's the huge pile of comments?

**Comment by briend** [comment]
Yeah it's a huge pile of hound comments that killed it.   I actually closed the PR but will make a new one once I clean it up more. It's the HCYtools branch in my github
