### ISSUE TITLE
Mypaint crashes on musl

### ISSUE THREAD

**Issue by Vintodrimmer** [mypaint/mypaint#927]
#### Description of the problem
Mypaint on MUSL opens, but the moment cursor gets into the canvas, it crashes with the following error:
```
fish: “mypaint” terminated by signal SIGSEGV (Address boundary error)
```
If I run it as `gdb -ex 'r /usr/bin/mypaint' -ex q python2`, the error is as follows:
```
Thread 1 "python2" received signal SIGSEGV, Segmentation fault.
0x00007fffe5faa0f3 in ?? () from /lib/libgomp.so.1
A debugging session is active.

        Inferior 1 [process 18443] will be killed.

Quit anyway? (y or n)
```

#### Basic system details
MyPaint version: 1.2.1
Operating system: Void Linux
Desktop environment: bspwm

#### Steps to reproduce
1. Start MyPaint
2. Place the cursor into the painting area or move it if it's there already
3. Experience the crash

#### Backtraces or error messages

```
Segmentation fault
```

![screenshot](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2018-04-28-19%3A59%3A31-screenshot.png)

**Comment by jplloyd** [comment]
Interesting that you did not run into the same linker issues as #927 seeing as it apparently wasn't fixed until the month after: void-linux/void-packages/issues/3924

At any rate, I'm not sure there's anything we can do apart from add an option to explicitly disable openmp in the build(s). If anyone wants to dig up and solve the underlying issue, that would be preferred of course.

**Comment by jplloyd** [comment]
Added option to disable: d8e73645f207c0a2ed710616d7ab1b3aac95ed05

Comment on the case: https://github.com/mypaint/mypaint/issues/945#issuecomment-517983604_
