### ISSUE TITLE
consider tagging a new git release

### ISSUE THREAD

**Issue by anthraxx** [mypaint/mypaint#929]
Hi, the latest release is quite old and it would be awesome distro wise to get a new release. This includes cool major things like getting rid of the old scons build, easily use system library for libmypaint instead of statically linking and other neat things.

**Comment by aoloe** [comment]
... currently, in debian testing there is a conflict between libmaypaint-common (probably needed by gimp) and mypaint-data (needed by the current version of mypaint)...

it would be nice to see a release that resolves this...

**Comment by aoloe** [comment]
see also https://github.com/mypaint/mypaint/issues/918 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894757

**Comment by jplloyd** [comment]
MyPaint 2.0 is now released: https://github.com/mypaint/mypaint/releases/tag/v2.0.0
