### ISSUE TITLE
Feature request: Can you add the mypaint.appimage to this site

### ISSUE THREAD

**Issue by Lvaskz** [mypaint/mypaint#931]
Hi, I would like to download appimage a better way instead of to find it in the travis.

**Comment by odysseywestra** [comment]
Duplicate of #849.

To summarize there are a couple of show stoppers issues that are preventing us from deploying it fully. Plus we need to look into possibly moving the appimage building on appveyor since it provides a much newer Ubuntu LTS than travis. PR are welcome in this case.
