### ISSUE TITLE
Large borders around images when saved

### ISSUE THREAD

**Issue by teleportingtortoise** [mypaint/mypaint#933]
#### Description of the problem

I'm getting large amounts of blank space around drawings when saving.

#### Basic system details

MyPaint version: Windows x64 AppVeyor build 324
Operating system: Windows 10, latest update

#### Steps to reproduce

1. Start MyPaint
2. Draw
3. Save file or scrap

**Comment by briend** [comment]
324 was the PR build for the perspective mode.  @gwojcik might know more, but I'll close this for now.  Thanks for reporting!

**Comment by gwojcik** [comment]
@briend I don't known about any bug in perspective mode that could cause this, but there is other way of reproducing this. Using erase mode can expand canvas like drawing in normal mode. After saving places touched in erase mode will be included as blank space.
