### ISSUE TITLE
Mypaint crashes when colour swatches are moved.

### ISSUE THREAD

**Issue by Adrakaris** [mypaint/mypaint#935]
#### Description of the problem
I use a drawing tablet with mypaint (HUIOn Q11K) and when I click on the colour swatches sometimes it will crash. I have since realised that this is because when I click on the colour sometimes my pen will move slightly, causing the swatches to recognise as me trying to move them. This is not an issue with my graphics tablet. I have tried the same thing with my mouse and am able to reproduce it consistently, although sometimes it will not crash on the first move. This applies also in the actual editor window for the swatches.

#### Basic system details
MyPaint version: 1.2.1+gitexport.bcf5a28d
Operating system: Windows 10
Desktop environment: Default Win10 i guess

#### Steps to reproduce

1. Start MyPaint
2. try moving several of the colour swatches at the top left
3. It crashes suddenly without warning, with no error message, losing everything and leaving you hoping that there is a backup saved.

Here is a video just in case:
https://youtu.be/Mms_fpkDVjg

#### Backtraces or error messages

```

```

**Comment by briend** [comment]
Can you please try the latest alpha build for windows?  You can use the standalone zip file so you don't need to "install" it:
https://ci.appveyor.com/project/achadwick/mypaint/build/1.3.0-alpha+master.334
Here's a direct link to the zip file:
https://ci.appveyor.com/api/buildjobs/a917vdrmaesw05o8/artifacts/out%2Fbundles%2Fmypaint-git-w64-1.3.0-alpha-master.334-standalone.zip

**Comment by briend** [comment]
Great, you can install it if you'd like by digging into the MINGW64 and then artifacts:
https://ci.appveyor.com/project/achadwick/mypaint/build/1.3.0-alpha+master.334/job/a917vdrmaesw05o8/artifacts
