### ISSUE TITLE
libjson-c.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by ahloiscreamo** [mypaint/mypaint#936]
#### Description of the problem
Today i upgraded to fedora 28
later i went to open mypaint as usual and it failed to start, below is my terminal output-
```

azrulFTW@localhost:~|⇒  mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr/local'
INFO: mypaint: There is an old-style configuration area in u'/home/azrulFTW/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOME and $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
Traceback (most recent call last):
  File "/usr/local/bin/mypaint", line 463, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/usr/local/share/mypaint/gui/main.py", line 96, in main
    from gui import application
  File "/usr/local/share/mypaint/gui/application.py", line 49, in <module>
    import lib.document
  File "/usr/local/share/mypaint/lib/document.py", line 37, in <module>
    import lib.helpers as helpers
  File "/usr/local/share/mypaint/lib/helpers.py", line 26, in <module>
    import mypaintlib
  File "/usr/local/share/mypaint/lib/mypaintlib.py", line 17, in <module>
    _mypaintlib = swig_import_helper()
  File "/usr/local/share/mypaint/lib/mypaintlib.py", line 16, in swig_import_helper
    return importlib.import_module('_mypaintlib')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: libjson-c.so.2: cannot open shared object file: No such file or directory

```
I already have libjson-c installed
```
[root@localhost]~# dnf install json-c
Last metadata expiration check: 0:58:28 ago on Tue 29 May 2018 09:40:22 PM +08.
Package json-c-0.13.1-2.fc28.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[root@localhost]~# dnf install json-c-devel
Last metadata expiration check: 0:58:51 ago on Tue 29 May 2018 09:40:22 PM +08.
Package json-c-devel-0.13.1-2.fc28.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[root@localhost]~# 

```
Also what is the proper way to uninstall mypaint-git before trying to install again?
i try make uninstall, that doesnt work.Thanks
#### Basic system details

MyPaint version: latest mypaint git
Operating system: fedora 28
Desktop environment: Gnome

**Comment by myfreeweb** [comment]
You need to rebuild libmypaint, `json-c` recently bumped its version to `libjson-c.so.4`

**Comment by ahloiscreamo** [comment]
I got gcc error on rebuild
`azrulFTW@localhost:~/Downloads/libmypaint-master|
⇒  ./autogen.sh

I am testing that you have the tools required to build
libmypaint from git. This test is not foolproof.

checking for libtool >= 1.5 ... Major version might be too new (2.4.6)
checking for autoconf >= 2.62 ... yes (version 2.69)
checking for automake >= 1.13 ... yes (version 1.15.1)
checking for intltool >= 0.40.1 ... yes (version 0.51.0)
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4macros'.
libtoolize: linking file 'm4macros/libtool.m4'
libtoolize: linking file 'm4macros/ltoptions.m4'
libtoolize: linking file 'm4macros/ltsugar.m4'
libtoolize: linking file 'm4macros/ltversion.m4'
libtoolize: linking file 'm4macros/lt~obsolete.m4'
Checked mypaint-brush-settings-gen.h: up to date, not rewritten
Checked brushsettings-gen.h: up to date, not rewritten
configure.ac:84: installing './compile'
configure.ac:60: installing './missing'
Makefile.am: installing './depcomp'
azrulFTW@localhost:~/Downloads/libmypaint-master|
⇒  ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for platform... unix
checking whether to turn on debugging... no
checking whether to turn on profiling... no
checking for JSON... yes
checking for library containing floorf... -lm
checking for library containing powf... none required
checking for library containing expf... none required
checking for library containing fabsf... none required
checking whether C compiler accepts -fsanitize=undefined... yes
checking whether the linker accepts -fsanitize=undefined... no
checking whether NLS is requested... yes
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.26.2
checking for XML::Parser... ok
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for library containing dgettext... none required
checking for gobject-introspection... yes
checking for GLIB... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating doc/Makefile
config.status: creating gegl/libmypaint-gegl-2.0.pc
config.status: creating gegl/Makefile
config.status: creating libmypaint-2.0.pc
config.status: creating Makefile
config.status: creating po/Makefile.in
config.status: creating tests/Makefile
config.status: creating tests/gegl/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

  Configured libmypaint 2.0.0-alpha

azrulFTW@localhost:~/Downloads/libmypaint-master|
⇒  sudo make install
[sudo] password for azrulFTW: 
Making install in .
make[1]: Entering directory '/home/azrulFTW/Downloads/libmypaint-master'
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/azrulFTW/Downloads/libmypaint-master/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
depbase=`echo brushmodes.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT brushmodes.lo -MD -MP -MF $depbase.Tpo -c -o brushmodes.lo brushmodes.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT brushmodes.lo -MD -MP -MF .deps/brushmodes.Tpo -c brushmodes.c  -fPIC -DPIC -o .libs/brushmodes.o
depbase=`echo fifo.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT fifo.lo -MD -MP -MF $depbase.Tpo -c -o fifo.lo fifo.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT fifo.lo -MD -MP -MF .deps/fifo.Tpo -c fifo.c  -fPIC -DPIC -o .libs/fifo.o
depbase=`echo helpers.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT helpers.lo -MD -MP -MF $depbase.Tpo -c -o helpers.lo helpers.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT helpers.lo -MD -MP -MF .deps/helpers.Tpo -c helpers.c  -fPIC -DPIC -o .libs/helpers.o
depbase=`echo mypaint-mapping.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-mapping.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-mapping.lo mypaint-mapping.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-mapping.lo -MD -MP -MF .deps/mypaint-mapping.Tpo -c mypaint-mapping.c  -fPIC -DPIC -o .libs/mypaint-mapping.o
depbase=`echo mypaint-brush.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-brush.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-brush.lo mypaint-brush.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-brush.lo -MD -MP -MF .deps/mypaint-brush.Tpo -c mypaint-brush.c  -fPIC -DPIC -o .libs/mypaint-brush.o
depbase=`echo mypaint-brush-settings.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-brush-settings.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-brush-settings.lo mypaint-brush-settings.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-brush-settings.lo -MD -MP -MF .deps/mypaint-brush-settings.Tpo -c mypaint-brush-settings.c  -fPIC -DPIC -o .libs/mypaint-brush-settings.o
mypaint-brush-settings.c:24: warning: "GETTEXT_PACKAGE" redefined
 #define GETTEXT_PACKAGE "libmypaint"
 
In file included from mypaint-brush-settings.c:17:
./config.h:8: note: this is the location of the previous definition
 #define GETTEXT_PACKAGE "libmypaint-2.0"
 
depbase=`echo mypaint-fixed-tiled-surface.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-fixed-tiled-surface.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-fixed-tiled-surface.lo mypaint-fixed-tiled-surface.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-fixed-tiled-surface.lo -MD -MP -MF .deps/mypaint-fixed-tiled-surface.Tpo -c mypaint-fixed-tiled-surface.c  -fPIC -DPIC -o .libs/mypaint-fixed-tiled-surface.o
depbase=`echo mypaint-rectangle.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-rectangle.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-rectangle.lo mypaint-rectangle.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-rectangle.lo -MD -MP -MF .deps/mypaint-rectangle.Tpo -c mypaint-rectangle.c  -fPIC -DPIC -o .libs/mypaint-rectangle.o
depbase=`echo mypaint-surface.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-surface.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-surface.lo mypaint-surface.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-surface.lo -MD -MP -MF .deps/mypaint-surface.Tpo -c mypaint-surface.c  -fPIC -DPIC -o .libs/mypaint-surface.o
depbase=`echo mypaint-tiled-surface.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-tiled-surface.lo -MD -MP -MF $depbase.Tpo -c -o mypaint-tiled-surface.lo mypaint-tiled-surface.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT mypaint-tiled-surface.lo -MD -MP -MF .deps/mypaint-tiled-surface.Tpo -c mypaint-tiled-surface.c  -fPIC -DPIC -o .libs/mypaint-tiled-surface.o
depbase=`echo operationqueue.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT operationqueue.lo -MD -MP -MF $depbase.Tpo -c -o operationqueue.lo operationqueue.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT operationqueue.lo -MD -MP -MF .deps/operationqueue.Tpo -c operationqueue.c  -fPIC -DPIC -o .libs/operationqueue.o
depbase=`echo rng-double.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT rng-double.lo -MD -MP -MF $depbase.Tpo -c -o rng-double.lo rng-double.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT rng-double.lo -MD -MP -MF .deps/rng-double.Tpo -c rng-double.c  -fPIC -DPIC -o .libs/rng-double.o
depbase=`echo tilemap.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT tilemap.lo -MD -MP -MF $depbase.Tpo -c -o tilemap.lo tilemap.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT tilemap.lo -MD -MP -MF .deps/tilemap.Tpo -c tilemap.c  -fPIC -DPIC -o .libs/tilemap.o
depbase=`echo utils.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -MT utils.lo -MD -MP -MF $depbase.Tpo -c -o utils.lo utils.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_POSIX_C_SOURCE=200809L -g -O2 -MT utils.lo -MD -MP -MF .deps/utils.Tpo -c utils.c  -fPIC -DPIC -o .libs/utils.o
/bin/sh ./libtool  --tag=CC   --mode=link gcc -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -D_POSIX_C_SOURCE=200809L -g -O2 -version-info 0:0:0 -no-undefined  -o libmypaint-2.0.la -rpath /usr/local/lib brushmodes.lo fifo.lo helpers.lo mypaint-mapping.lo mypaint.lo mypaint-brush.lo mypaint-brush-settings.lo mypaint-fixed-tiled-surface.lo mypaint-rectangle.lo mypaint-surface.lo mypaint-tiled-surface.lo operationqueue.lo rng-double.lo tilemap.lo utils.lo  -ljson-c  -lgobject-2.0 -lglib-2.0  -lm 
libtool: link: rm -fr  .libs/libmypaint-2.0.la .libs/libmypaint-2.0.lai .libs/libmypaint-2.0.so .libs/libmypaint-2.0.so.0 .libs/libmypaint-2.0.so.0.0.0
libtool: link: gcc -shared  -fPIC -DPIC  .libs/brushmodes.o .libs/fifo.o .libs/helpers.o .libs/mypaint-mapping.o .libs/mypaint.o .libs/mypaint-brush.o .libs/mypaint-brush-settings.o .libs/mypaint-fixed-tiled-surface.o .libs/mypaint-rectangle.o .libs/mypaint-surface.o .libs/mypaint-tiled-surface.o .libs/operationqueue.o .libs/rng-double.o .libs/tilemap.o .libs/utils.o   -ljson-c -lgobject-2.0 -lglib-2.0 -lm  -g -O2   -Wl,-soname -Wl,libmypaint-2.0.so.0 -o .libs/libmypaint-2.0.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libmypaint-2.0.so.0" && ln -s "libmypaint-2.0.so.0.0.0" "libmypaint-2.0.so.0")
libtool: link: (cd ".libs" && rm -f "libmypaint-2.0.so" && ln -s "libmypaint-2.0.so.0.0.0" "libmypaint-2.0.so")
libtool: link: ( cd ".libs" && rm -f "libmypaint-2.0.la" && ln -s "../libmypaint-2.0.la" "libmypaint-2.0.la" )
CPPFLAGS="" CFLAGS="-D_POSIX_C_SOURCE=200809L -g -O2" LDFLAGS="" CC="gcc" PKG_CONFIG="/usr/bin/pkg-config" GI_HOST_OS="" DLLTOOL="false" CFLAGS="-D_POSIX_C_SOURCE=200809L -g -O2" LDFLAGS=" -lm " CPPFLAGS=" -I." CXXFLAGS="" /usr/bin/g-ir-scanner  --warn-all --pkg="glib-2.0" --namespace="MyPaint" --nsversion="2.0" --identifier-prefix="MyPaint" --symbol-prefix="mypaint_" --add-include-path="." --add-include-path="`/usr/bin/pkg-config --define-variable=datadir="/usr/local/share" --variable=girdir gobject-introspection-1.0`" --namespace=MyPaint --nsversion=2.0 --libtool="/bin/sh ./libtool"  --include=GObject-2.0 --include=GLib-2.0    --library=libmypaint-2.0.la  --cflags-begin -I/usr/include/json-c  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   --cflags-end  mypaint-brush.h mypaint-brush-settings.h mypaint-brush-settings-gen.h mypaint-fixed-tiled-surface.h mypaint-rectangle.h mypaint-surface.h mypaint-tiled-surface.h brushmodes.c libmypaint.c mypaint-brush-settings.c mypaint-rectangle.c operationqueue.c utils.c fifo.c mypaint-mapping.c mypaint.c mypaint-surface.c rng-double.c helpers.c mypaint-brush.c mypaint-fixed-tiled-surface.c mypaint-tiled-surface.c tilemap.c libmypaint-2.0.la Makefile --output MyPaint-2.0.gir
annobin: MyPaint_2.0.c: Error: plugin built for compiler version (8.2.1) but run with compiler version (8.1.1)
cc1: error: fail to initialize plugin /usr/lib/gcc/x86_64-redhat-linux/8/plugin/annobin.so
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/g-ir-scanner", line 66, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 547, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 422, in create_binary
    gdump_parser.get_error_quark_functions())
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 302, in compile_introspection_binary
    return dc.run()
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 168, in run
    introspection_obj = self._compile(c_path)
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 208, in _compile
    self._options.init_sections)
  File "/usr/lib64/gobject-introspection/giscanner/ccompiler.py", line 251, in compile
    output_dir=os.path.abspath(os.sep))
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
make[1]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:160: MyPaint-2.0.gir] Error 1
make[1]: Leaving directory '/home/azrulFTW/Downloads/libmypaint-master'
make: *** [Makefile:844: install-recursive] Error 1
azrulFTW@localhost:~/Downloads/libmypaint-master|
⇒  
`
A simple google point me to  this fedora bug https://bugzilla.redhat.com/show_bug.cgi?id=1574478

**Comment by ahloiscreamo** [comment]
no longer valid. ive uninstall everything and start from scratch.they compile and work well.
![screenshot from 2019-03-01 22-34-17](https://user-images.githubusercontent.com/9318372/53644733-397de100-3c72-11e9-90f0-f826523716fb.png)
