### ISSUE TITLE
Does Anyone Use A XP-Pen deco 02 Graphics Tablet?

### ISSUE THREAD

**Issue by jiutian67** [mypaint/mypaint#939]
I am looking for some buying information about digital drawing tablets and pens. I would like to purchase an entry level drawing tablet and pen. I totally want the pen to have an eraser end which I have done some initial research and found out not all pens for drawing pads/tablets have an eraser end. I use adobe Illustrator, some Photoshop, for most of my design/graphics work on PC.

I want something inexpensive but again really want it to be portable and the eraser end functionality is a must have. I would like to pay as far under $200 as possible. The research I have done has shown that the ones at a price point under $100 lack the eraser end is barely available (haven’t found one yet) and the wireless factor is available but not with a whole bunch of variety in models available. Important note is that I will be using it with a Windows 10 laptop.

I was going to get the XP-Pen deco 02 graphics tablet ( https://www.amazon.com/XP-PEN-Graphics-Battery-free-Shortcut-pressure/dp/B07DCS9D9Q ) . The DECO 02 drawing tablet have an eraser at the end of the pen .The stylus supports 8192 levels of pressure sensitivity and the graphics pad has a 10 x 5.63 inch working area .it seems perfect.Any advice for an up and coming artist , good/bad experiences and so on?.

Any advice is appreciated. Thank you.

**Comment by burlen** [comment]
@jiutian67 any chance you would update this post with your experiences? I'm buying a tablet for my son and looking for info.

**Comment by calwas** [comment]
This is a pretty old post (and not really a MyPaint issue), but... I have ax XP-Pen Deco 01 and can recommend it. The 01 is similar to the 02, but does not have an eraser tip or the roller wheel. I enjoy using the 01 and find it more pleasant to use than my Wacom Intuos Large. I use Windows 10 Pro, and the 01 works with every art program I throw at it, including MyPaint. One day I had a problem updating the 01 driver and tech support was very responsive and helpful. XP-Pen has an excellent reputation. I'm considering buying another of their tablets. Cheers.

**Comment by jplloyd** [comment]
Good to know that it works with MyPaint, but since the issue tracker is not meant for general discussion I'm closing this.
