### ISSUE TITLE
Error in"/usr/share/doc-base/libmypaint", line 20: all "Format" sections are invalid.

### ISSUE THREAD

**Issue by LinuxOpa** [mypaint/mypaint#940]
ubuntu 18.04 x64, apt update
libmypaint 1.4.0~7-ubu18.04.3~ppa~c196a86

install-docs --verbose --check /usr/share/doc-base/libmypaint :

Warning in `/usr/share/doc-base/libmypaint': unknown area.
Warning in "/usr/share/doc-base/libmypaint", line 11: File mask "/usr/share/doc/libmypaint/libmypaint.sgml.gz" does not match any files.
Warning in "/usr/share/doc-base/libmypaint", line 14: File mask "/usr/share/doc/libmypaint/libmypaint.ps.gz" does not match any files.
Warning in "/usr/share/doc-base/libmypaint", line 17: File mask "/usr/share/doc/libmypaint/libmypaint.text.gz" does not match any files.
Warning in "/usr/share/doc-base/libmypaint", line 20: File "/usr/share/doc/libmypaint/html/index.html" does not exist.
Error in"/usr/share/doc-base/libmypaint", line 20: all "Format" sections are invalid.
/usr/share/doc-base/libmypaint: Serious error found, file is not registered.

Translated with www.DeepL.com/Translator

German Original:

install-docs --verbose --check /usr/share/doc-base/libmypaint :

Warnung in `/usr/share/doc-base/libmypaint': unbekannter Bereich: »unknown«.
Warnung in »/usr/share/doc-base/libmypaint«, Zeile 11: Dateimaske »/usr/share/doc/libmypaint/libmypaint.sgml.gz« passt auf keine Dateien.
Warnung in »/usr/share/doc-base/libmypaint«, Zeile 14: Dateimaske »/usr/share/doc/libmypaint/libmypaint.ps.gz« passt auf keine Dateien.
Warnung in »/usr/share/doc-base/libmypaint«, Zeile 17: Dateimaske »/usr/share/doc/libmypaint/libmypaint.text.gz« passt auf keine Dateien.
Warnung in »/usr/share/doc-base/libmypaint«, Zeile 20: Datei »/usr/share/doc/libmypaint/html/index.html« exisitiert nicht.
Fehler in »/usr/share/doc-base/libmypaint«, Zeile 20: alle »Format«-Abschnitte sind ungültig.
/usr/share/doc-base/libmypaint: Schwerwiegender Fehler gefunden, die Datei wird nicht registriert.

**Comment by jplloyd** [comment]
I can't see any traces of doc-base files in the libmypaint repo, nor in the doc generation, so I assume this support has been added by packagers

If this is important to you, I would suggest reopening it in https://github.com/mypaint/libmypaint with some title like "Add doc-base support", but before that I suggest you ask/notify the maintainer of the ppa you're using.
