### ISSUE TITLE
Revert Global pressure mapping to default and brush/eraser size

### ISSUE THREAD

**Issue by TheMiziko** [mypaint/mypaint#944]
Hello ! Is there any way to revert Global pressure mapping to default values, and make eraser/brush remember their size when I swap between them ?

**Comment by jplloyd** [comment]
Better late than never.

The default pressure mapping is simply linear. There is no single-click way of reverting it in the GUI, but you can just drag all points outside of the drawing area to remove them, leaving the last two points at the lower left and the top right corner respectively.

As for having brushes remember their size, you can use the history panel to switch to brushes you've used previously - they will use the same parameters they had when you last used them.

Another alternative is to use the brush shortcut slots and re-assign the brush to the same slot after you have modified their size. I don't think there are any other ways of getting that functionality.

For future user support or feature requests, do open a topic in [the forums](https://community.mypaint.org/).
