### ISSUE TITLE
[Feature Request] - Rotate Symmetry Line

### ISSUE THREAD

**Issue by android272** [mypaint/mypaint#947]
Currently, you can only make vertical symmetry lines mirroring your image horizontally. But some images require a different line of symmetry. It would be nice if you could rotate the line of symmetry.

I think Inkscape has a nice solution to this problem. In Inkscape when you make a guide you pull from one of the rulers making either a horizontal or vertical guide. After moving a guide wherever your mouse is when you let go of the guide a small dot is placed on the guide. This is the pivot point of the guide and all guides have them.

If you hold shift + click and drag above or below this point then move the guide then instead of moving the guide, you will rotate the guide on that pivot point. Holding Shift + ctrl will rotate and snap the guide every 15°s. Holding Ctrl + click and dragging on a guide moves the pivot point without moving the guide its self.

It is my opinion that this is the mechanic that MyPaint's symmetry lines need to make them more functional for most works of art that our users will work on.

**Comment by odysseywestra** [comment]
Triage Note: I think we should keep this one here instead of moving it to the community forums. Since we have a symmetry tool, this will be a must have to a lot of Artists who make patterns or such.

**Comment by jplloyd** [comment]
I actually implemented most of what's needed to add this, and have it be performant (some basic matrix stuff). I've put in on hold as the code on the gui side required more work than I thought. We definitely should add the angle to the set_symmetry_state interface in libmypaint before its 2.0 release, so we don't have to break the API to implement this later on.

**Comment by jplloyd** [comment]
Adjustable symmetry angle available as of 7d95cfaa76cf789215fb87017efdfb62538627f8.

Could do with some additional QoL, like adjusting the angle by dragging on the canvas, but it is otherwise fully functional.
