### ISSUE TITLE
Instructions for compiling MyPaint without sudo

### ISSUE THREAD

**Issue by aoloe** [mypaint/mypaint#949]
Currently, the latest release of MyPaint has been dropped from Debian testing (and probably the latest Ubuntu) and it's hard to compile its current code.

I've followed the instruction for installing libmypaint and MyPaint, but i failed to run the resulting binary.
The peculiarity: I refuse to mess with my system, when installing self compiled code:

`sudo make install`

is not an option for me.

Can you please provide build instructions for both mypaint and libmypaint that do not require sudo rights?

At the end of the day (or, better, late in the night) I could find a way to get MyPaint to run, by using the "nix" package management... but it's was not really a pleasant experience and could not give me (yet) a working package on an old eeepc.

**Comment by jplloyd** [comment]
Better late than never. There is now a [new section](../blob/master/BUILDING.md#building-and-installing-locally) in the build instructions that describe how to accomplish this step-by-step.

**Comment by aoloe** [comment]
thanks!

it's still a bit too complex for my taste, but nice to see that it's now documented!
