### ISSUE TITLE
Pasting an image on Windows 7 64 bit crashes pythonw

### ISSUE THREAD

**Issue by watercolorhearts** [mypaint/mypaint#951]
Pythonw.exe has stopped working it says, after pasting in an image copied to clipboard. The dimensions were approximately 500x600 pixels or so.
http://prntscr.com/lro1i6

MyPaint version: 1.2.1+gitexport.bcf5a28d
(Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1)
Operating system: Windows 7

1. Start MyPaint
2. Copy ImAGE
3. Press Ctrl+V on the stage

**Comment by jplloyd** [comment]
Neither Windows 7 32bit nor Windows 10 64 bit _crashes_ for me, **but** nor are the images pasted. Instead I get the "Clipboard does not contain an image" error (not correct, as evidenced by pasting into other ms-paint). This is still the case with the latest master.

**Comment by jplloyd** [comment]
@watercolorhearts I really can't seem to induce a crash by copy/pasting, so I'll refer to your case.

1: Was the crash consistent (did it happen every time)?
2: Does it happen with any type of image?
3: Does it happen no matter where the image was copied from?

And if you are able, can you test if the issue persists in the latest alpha (links under "assets"):
https://github.com/mypaint/mypaint/releases/tag/v2.0.0-alpha.12

**Comment by jplloyd** [comment]
Issue reporter is not responding and since Windows 7 is EOL in a couple of weeks (it's been 10 years already...), I think we may just drop trying to support it in general (unless someone volunteers to do it).
