### ISSUE TITLE
Can't run the demo due to pygobject-3.0 dependency

### ISSUE THREAD

**Issue by RustyRaptor** [mypaint/mypaint#953]
#### Description of the problem
The demo will not run because it's asking for pygobject-3.0

I don't know what package it wants exactly but I appear to have pygobject installed both using pip, pip3 and the Ubuntu 18.04 package manager as ``` python-gi python-gi-cairo python3-gi python3-gi-cairo gir1.2-gtk-3.0 ```  
If there is another pygobject-3.0 package I can't find it. 

#### Basic system details
MyPaint version:
```
commit 462f14d542af83bd2db462e3d6210bee5d7ae9b0 (HEAD -> master, origin/master, origin/HEAD)
Merge: f2bfe822 62775cf8
Author: Brien Dieterle <briend@gmail.com>
Date:   Thu Dec 6 21:20:21 2018 -0800

    Merge pull request #952 from briend/brushes-data
    
    Brushes data package dependency
```
Operating system: [Kubuntu 18.04]
Desktop environment: [KDE Plasma]

#### Steps to reproduce

1. Start MyPaint using the instructions in the README

#### Backtraces or error messages

```
Package pygobject-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pygobject-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pygobject-3.0' found
Traceback (most recent call last):
  File "setup.py", line 655, in <module>
    ext_modules=get_ext_modules(),
  File "setup.py", line 565, in get_ext_modules
    extra_compile_args=extra_compile_args,
  File "setup.py", line 503, in pkgconfig
    universal_newlines=True,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--libs', 'pygobject-3.0', 'glib-2.0', 'libpng', 'lcms2', 'gtk+-3.0', 'libmypaint-2.0', 'mypaint-brushes-2.0']' returned non-zero exit status 1

```

**Comment by briend** [comment]
You probably need to install mypaint-brushes
https://github.com/mypaint/mypaint-brushes

mypaint now depends on libmypaint and mypaint-brushes

**Comment by RustyRaptor** [comment]
> You probably need to install mypaint-brushes
> https://github.com/mypaint/mypaint-brushes
> 
> mypaint now depends on libmypaint and mypaint-brushes

Why would that be? I actually got the "no package libmypaint" and "no package mypaint-brushes-2.0" messages but I already fixed them by building libmypaint and mypaint-brushes from source.

**Comment by briend** [comment]
I was just guessing, sorry.  Actually I think you will need 
python-gi-dev
I will update the docs, but let me know if that helps

**Comment by RustyRaptor** [comment]
Ok I did that and I think that fixed it. Though I did 2 other things as well 
1. I ran ```pkg-config --variable=brushesdir mypaint-brushes-2.0``` in the mypaint-brushes source directory. 
2. I installed python3-venv in addition to the stuff here. 
https://pygobject.readthedocs.io/en/latest/devguide/dev_environ.html
