### ISSUE TITLE
Tanda brush  -->  splatter-04  doesn't  show any paint

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#968]
#### Basic system details

MyPaint version: mypaint w64 2.0.0-alpha-git.be215fba
Operating system: windows 10 home 64 bit

#### Steps to reproduce
1. Start MyPaint
2.  Tanda brush  -->  splatter-04  doesn't  show any paint.
It seems  to be ignored,   but  the  cursor  still moves and  the brush seems to be selected.
All the  other  brushes are fine.

**Comment by briend** [comment]
Thanks!  This will be available in the next binary release
