### ISSUE TITLE
New vector layer warning

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#969]
#### Basic system details
MyPaint version: mypaint w64 2.0.0-alpha-git.be215fba
Operating system: windows 10 home 64 bit
Problems  with  the vector layer  has  been   reported  years ago by others
but  I will report it anyway.

#### Steps to reproduce
1. Start MyPaint
2.  Open a new document  and go  to menu
Mypaint > Layer > New Vector Layer ...
3.  There is warning  message  on screen  which  can  be dismissed and the user
can continue to use   mypaint but without  a new vector layer.

I don't have  inkscape  installed on  my computer  which  is  brand-new.

**Comment by odysseywestra** [comment]
You need to have a application that capable of editing svg files. If you don't the error is going to pop up.
----
Tiage Note: Check back in a week to see if user responds.

**Comment by AesaraB** [comment]
Closed as stale
