### ISSUE TITLE
feature request: Edit layer in external app menu entry for bitmap layers

### ISSUE THREAD

**Issue by blurymind** [mypaint/mypaint#97]
We have the option for vector layers. Why not also have it  for bitmap layers?
Quickly opening the layer in gimp or krita would allow for some quick tweaks with tools missing in mypaint.

Of course we can just copy and paste from clipboard atm. But that is kind of adding extra clicks and manual steps to do in the workflow.

**Comment by mikshaw** [comment]
Very cool that this works now, thanks @achadwick 

The window behavior is a little annoying on my desktop (dwm), but things like this usually seem to end up being some conflict between the window manager and Xorg. When i open the external application it doesn't come to the front even with alt-tab, so i have to manually move mypaint out of the way. Using multiple monitors seems to be even more troublesome.  Again it's probably nothing to do with mypaint itself, but thought i'd mention it.
