### ISSUE TITLE
Convert to Normal Paint bug - wrong mode

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#970]
#### Basic system details
MyPaint version: mypaint w64 2.0.0-alpha-git.be215fba
Operating system: windows 10 home 64 bit

#### Steps to reproduce
1. Start MyPaint
2.  Import a picture  ....
mypaint > Layer  >  Import Layer
3.  Choose a picture (jpeg or png)  and it shows colors correctly in  mypaint  window.
4.  Do a conversion  of layer
mypaint > Convert to Normal Paint Layer
5. I notice that there is too much red i.e. reddish tinge
6.  I change  the  layer mode  from  'Paint' to 'Normal'.  This solves the problem
and  the  mypaint  window  now shows the image  accurately.

----------------------------------------------------------------------------

In a related bug.....

#### Steps to reproduce
1. Start MyPaint
2.  Import a picture  ....
mypaint > Layer  >  Import Layer
3.  Choose a picture (jpeg or png)  and it shows colors correctly in  mypaint  window.
4. mypaint > Layer  > New Layer from Visible
5. I notice that there is too much red i.e. reddish tinge
6.  I change  the  layer mode of the newest layer  from  'Paint' to 'Normal'.  
This reduces  the red tinge  but  not fully.
7. I turn off the visiblility  icon of the original imported layer and this solves  the   color problem
i.e. the correct colors of image are  shown.
____________________________________________________

**Comment by briend** [comment]
This should be mostly fixed.  Need to test more edge cases and those refactoring things.  Compositing pigment is much more complicated than I first thought. . .

**Comment by briend** [comment]
Please try out the latest appveyor build:
https://ci.appveyor.com/project/achadwick/mypaint
Thanks for testing!
