### ISSUE TITLE
Shortcuts don't work in non-latin keyboard layouts

### ISSUE THREAD

**Issue by ystr** [mypaint/mypaint#974]
The title says it all, MyPaint reads localized text input instead of actual physical keys.

How to reproduce: switch to Cyrillic, try any key combination
Versions and systems: probably all of them (I tested 1.2.1 and 2.0.0 under Win32 and 1.2.0 under Debian 9 / GNOME).

The fix is to remove the event.group parameter from translate_keyboard_state in gui/keyboard.py.

**Comment by AesaraB** [comment]
Duplicate of #642
