### ISSUE TITLE
Dieterle brushes not compatible  with mypaint 1.2.1

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#978]
MyPaint version: mypaint-w64-1.2.1-20170129a-installer
Operating system: windows 10  64 bit

#### Steps to reproduce
My favorites had some  Dieterle brushes inside it .  I was using  mypaint 1.2.1
and  found  that it was  crashing  when  I tried to  use a Dieterle brush .  There was a warning  that there
was a gtk  error.  Then  the  crash.

**Comment by briend** [comment]
Weird, brush issues like this should have been fixed back here:

https://github.com/mypaint/libmypaint/issues/74

which is included in 1.2.1.  Could you post the error message?

**Comment by don570** [comment]
shareable link
https://drive.google.com/open?id=1d-n4bMQ0dpGXT58L65yja2OSzdsVjCi6

I decided  to clear my computer  of  mypaint installs using  uninstall script and start
with a fresh install  of
https://github.com/mypaint/mypaint/releases/download/v1.2.1/mypaint-w32-1.2.1-20170129a-installer.exe

Despite a fresh install  there  was  favorites  and  lost and found brushes ??  (see image)
In the file  'error -mypaint121'  there is  the  error output when I  try to  use  a Dieterle brush.
I append  the  standard  crash message as well.

Note that this isn't  important to me since  mypaint   2.0  works well.

**Comment by briend** [comment]
Looking at your logs I'm pretty certain this was fixed here:
https://github.com/mypaint/mypaint/issues/967

I had goofed up two brushes and uploaded corrupted copies.  Sorry about that, and thanks for getting those logs!
