### ISSUE TITLE
[Feature Request] - edit layer with external app- remember choice of app+preferences window

### ISSUE THREAD

**Issue by blurymind** [mypaint/mypaint#98]
I wish we dont have to select the software we edit the layer with every time we open with external app. A small tick box to "remember choice for this layer type". This would of course also add the need to add it as an entry in mypaint's preferences window.

Preferences window new entries:
External app for Vector layer, external app for bitmap layers - select between: 
ask every time, 
custom command,
etc

**Comment by odysseywestra** [comment]
@blurymind Could you move this thread over to https://community.mypaint.org/c/feature-requests? I'm working on cleaning up the issue tracker by move all feature requests there so we can get community feedback. If you can also set your post as a wiki that way we can edit the scope of the feature request that would be awesome as well. Don't forget to link back to here as well so I can keep track of it incase we need to reopen the issue. Thanks.

**Comment by AesaraB** [comment]
Consolidated into #1217
