### ISSUE TITLE
Fresh install of linux  -  tablet  not  recognized

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#982]
#### Basic system details

MyPaint version: version 1.2.1  recent
Operating system:   fatdog64 linux  version  800
Desktop environment: Rox file  manager,  openbox

#### Steps to reproduce

1.   Fresh  frugal  install of  fatdog64 linux  version  800
2.  I booted it up for first time (no  save  file) and launched mypaint as first app to test.
3. I noticed  that  pressure wasn't  working  with my  wacom bamboo  tablet.
4.  I opened  mypaint  preferences  and  noticed  that  only device   that is listed is  the mouse
5.  I closed  mypaint  and opened  GIMP.   It didn't recognize pressure either,  but  I opened up it's  
input devices  preference  and  saw that Wacom tablet  was  listed.  I activated  the  pressure and  checked  that
brushes were  working properly  with  GIMP.
6. I re-launched mypaint  and it works  properly  with pressure now.  In the mypaint preferences
the  tablet is now  listed.
_____________________________________________________________________________________________

**Comment by AesaraB** [comment]
Hi, which drawing tablet was this on?
