### ISSUE TITLE
Merge layer command  switches invisible to visible

### ISSUE THREAD

**Issue by don570** [mypaint/mypaint#983]
Merge layer command  switches an invisible lower layer to  a visible layer  when  merge command done

#### Basic system details

MyPaint version: recent  2.0   
https://github.com/mypaint/mypaint/releases/download/v2.0.0-alpha.8/mypaint-git-w64-2.0.0-alpha-master.467-installer.exe
Operating system: windows 10  or  fatdog64  linux

#### Steps to reproduce

1. Start MyPaint 2.0
2. use  paint brush  on first layer
3. create a second layer  and  paint on it
4.  Make  first layer invisible (by clicking on  eye icon)
5.  Go back to top layer and  do a merge  layers command
6.  The  lower  layer  becomes visible in the  resulting  layer

Note :   When  I checked in  a previous version  of  mypaint  --->  1.3
the  invisible  layer  remained  invisible   during  merging  process  which  is what  I
 wanted and expected.
________________________________________________________________________________

**Comment by briend** [comment]
So if you have two layers, and the bottom layer is invisible. . ..  are you selecting the top layer and choosing the "Merge Layer Down" command?  Are you expecting the two layers to be merged but the resulting layer to be made invisible?  Or are you expecting nothing to happen because the command should not pay attention to invisible layers?

**Comment by don570** [comment]
> are you selecting the top layer and choosing the "Merge Layer Down" command?

Yes.     It is also possible to do a merge layers by clicking  the merge icon in the side panel

> Are you expecting the two layers to be merged but the resulting layer to be made invisible? 
No .  I want the  result  to be what I see with  my  eyes  before  the  merge  command is done.

> because the command should not pay attention to invisible layers?
Absolutely!!!

I found out about  this  bug  when  I did a pencil trace on  the  lower layer   ,  then  put   color  in  the 
higher  layer.   I then  made  the  lower  layer  invisible since  I didn't  want  the pencil trace to be
seen  in the final output.   Of course I could have  saved the file  to disk with  both layers,
but  I wanted a simpler file  with  one  layer.

**Comment by briend** [comment]
Ah, yep I broke this. Should be fixed now though in master!  Thanks for reporting!   Interestingly, GIMP doesn't allow you to destroy an invisible layer like this, but Krita does.

**Comment by don570** [comment]
When I checked  the latest  Gimp appimage  2.10
The developers  have an unusual solution  to the  problem of merging a visible  layer with an invisible
layer.          **They  grey out the  command  so it can't be done!!!!**
_____________________________________________________________________________

**Comment by briend** [comment]
In GIMP if there are 3 layers and the middle layer is not visible, you can merge down from the top but it will "skip" the middle layer and merge with the bottom layer.  There's an argument for either way, but maybe we should just leave it alone :-p
