### ISSUE TITLE
Flatpack 2.0.0 alpha nightly can not be installed.

### ISSUE THREAD

**Issue by Fritigern** [mypaint/mypaint#985]
#### Description of the problem

Attempting to install the nightly flatpack in Kubuntu 18.10 fails.
```
$ flatpak remote-add --no-gpg-verify --user mypaint-master-repo http://flatpak-repo.manuq.com.ar
$ flatpak --user install mypaint-master-repo org.mypaint.MyPaint-Nightly
error: The application org.mypaint.MyPaint-Nightly/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.24 which was not found
```

#### Basic system details

MyPaint version: None, but attempted to install a nightly for 2.0.0 alpha
Operating system: GNU/Linux, Kubuntu 18.10
Desktop environment: Plasma5

#### Steps to reproduce

I think it's rather clear from my previous description, but I will do this anyway, to make sure I haven't overlooked anything.

1. Ensure that your Kubuntu 18.10 system is set up to use Flatpak
2. Attempt to install the MyPaint 2.0.0 nightly flatpak as described at http://mypaint.org/downloads/
3. Observe how the installation gets aborted because of uninstallable dependencies on some Gnome libraries.

#### Backtraces or error messages

```
error: The application org.mypaint.MyPaint-Nightly/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.24 which was not found
```

**Comment by jplloyd** [comment]
@manuq Do you know what the problem might be here? I have only used flatpak a couple of times, and never worked the package configuration bit.
