### ISSUE TITLE
Right-Click 'Edit Brush Settings' With A Lot Of Brushes Causes Crash.

### ISSUE THREAD

**Issue by ghost** [mypaint/mypaint#987]
#### Description of the problem
Trying to open the 'brush editor' via a right-click 'edit brush settings' causes some items to crash Mypaint. Seems like more than half of the brushes and not always the same ones ...

![Peek 2019-03-16 00-59](https://user-images.githubusercontent.com/47613607/54471486-a7a0c880-4787-11e9-8dc5-fec038ae4653.gif)

#### Basic system details
MyPaint version: 1.2.1+git.bcf5a28.dirty (Flathub)
Operating system: Fedora 29
Desktop environment: GNOME

#### Steps to reproduce
1. Start MyPaint
2. Right click on item in 'Brush Pane'.
3. Select 'Edit brush settings'.
4. Cross your fingers?

#### Backtraces or error messages
The following is from after I click on the given 'edit brush settings'; No idea if it's relevant. 
```
/app/share/mypaint/gui/brusheditor.py:118: PyGTKDeprecationWarning: The keyword(s) "page_incr, step_incr" have been deprecated in favor of "page_increment, step_increment" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  step_incr=0.01, page_incr=0.1)
/app/share/mypaint/gui/brusheditor.py:129: PyGTKDeprecationWarning: The keyword(s) "page_incr, step_incr" have been deprecated in favor of "page_increment, step_increment" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  step_incr=0.01, page_incr=0.1)
/app/share/mypaint/gui/brusheditor.py:134: PyGTKDeprecationWarning: The keyword(s) "page_incr, step_incr" have been deprecated in favor of "page_increment, step_increment" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  step_incr=0.01, page_incr=0.1)
WARNING: gui.brusheditor: Setting u'pressure_gain_log' should be added to a group

```

**Comment by jplloyd** [comment]
Reporter deleted their account and I cannot reproduce this on Fedora 30 with either v1.2.1 or the latest master. If you are reading this because it has happened to you, post details in a comment in this issue and we'll reopen it.
