### ISSUE TITLE
Unable to open PNG files

### ISSUE THREAD

**Issue by SkitsTheSkitty** [mypaint/mypaint#988]
#### Description of the problem

I cannot open PNG files in MyPaint. While it does not crash, it does load an error message. Using No Double Buffering did not help reduce the issue. If I need to go into more detail, I'm happy to help.

#### Basic system details

MyPaint version: 2.0.0-alpha+git.55af8eac
Operating system: Windows 10
Desktop environment: Modern

#### Steps to reproduce

1. Start MyPaint
2. Open any PNG file

#### Error Message

```
Error loading "x.png".
Reason: PNG reader failed: Get-buffer callback failed
The logs may have more detail about this error.
```

**Comment by don570** [comment]
Same  problem  in  linux.   'PNG reader failed'
jpegs  will open fine.
![screenshot-error](https://user-images.githubusercontent.com/19693002/54792739-4f5e4080-4c37-11e9-9ad9-f80777447887.png)

**Comment by briend** [comment]
Thanks for reporting this, the [latest commit broke this.](https://github.com/mypaint/mypaint/commit/55af8eac4fd70d943798294e848cfc53a5fdd0a4#diff-6bacc0012fb0bc75ee6c7fa794d8a5bc)  I had forgotten to include a parameter for a new preference (configurable transfer function for legacy behavior).   Oddly it didn't affect ORA files which are really PNG files in disguise.  I'll have a patch in a moment
