### ISSUE TITLE
Toolbar cuts off right-hand buttons when window width is small

### ISSUE THREAD

**Issue by afcady** [mypaint/mypaint#990]
The toolbar should wrap into a second line instead of losing buttons.

An inferior alternative would be some kind of overflow menu that showed the rest of the buttons temporarily (such as the one used by firefox).

As it is, on my tablet (or any small resolution tablet), rotating the display isn't practical since many of the toolbar buttons are important to using the application but they aren't available in rotation.

**Comment by jplloyd** [comment]
There should be an overflow menu button just to the left of the "color adjusters" button. Which version are you running, if that button does not appear there?

**Comment by jplloyd** [comment]
Well, the inferior alternative is already implemented. Maybe wrapping will be added as an option in the future. If the overflow arrow (pointing downwards) is not actually visible for you, make a comment and we'll reopen this issue.
