### ISSUE TITLE
Error instalation MyPaint Fedora 29

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [mypaint/mypaint#995]
my operating system is fedora 29
i am using Python 3.7.3
#### Description of the problem:
Anyone know what installation error this is?

[root@lauriano mypaint]# python setup.py demo
running demo
running build_ext
building 'lib._mypaintlib' extension
swigging lib/mypaintlib.i to lib/mypaintlib_wrap.cpp
swig -python -Wall -noproxydel -c++ -I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/pygobject-3.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0/ -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/local/include/libmypaint-2.0 -I/usr/include/json-c -DNO_TESTS -o lib/mypaintlib_wrap.cpp lib/mypaintlib.i
gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/pygobject-3.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0/ -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/local/include/libmypaint-2.0 -I/usr/include/json-c -I/usr/include/python3.7m -c lib/mypaintlib_wrap.cpp -o build/temp.linux-x86_64-3.7/lib/mypaintlib_wrap.o -Wall -Wno-sign-compare -Wno-write-strings -D_POSIX_C_SOURCE=200809L -DNO_TESTS -g -fopenmp -pthread -DMYPAINT_BRUSHES_DIR=\"/usr/local/share/mypaint-data/2.0/brushes\" -O3
<command-line>: warning: missing terminating " character
lib/mypaintlib_wrap.cpp:176:11: fatal error: Python.h: No such file or directory
 # include <Python.h>
           ^~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by briend** [comment]
You may be missing some build dependencies, such as python3-devel package.

**Comment by jplloyd** [comment]
Yes, this error will turn up if python3-devel (or equivalent packages) is not installed when building with python 3. Commands for installing python-version-specific packages are now added to the build instructions.
