### ISSUE TITLE
Impossible to recover the Forums password (or register again with an email address)

### ISSUE THREAD

**Issue by aoloe** [mypaint/mypaint#996]
Since the forums do not send emails anymore, it's impossible to recover a password or sign up with an email address.

**Comment by jplloyd** [comment]
@odysseywestra Should this be considered resolved? It seems registrations work again, but I'm not sure to what extent the email system is now "stable".

**Comment by odysseywestra** [comment]
Yes, I enabled email again, so this shouldn't be a problem. If still is a problem, those issues need to be posted on the [mypaint/mypaint.github.io](https://github.com/mypaint/mypaint.github.io/issues) issue page.
