### ISSUE TITLE
State of Libre Graphics 2019

### ISSUE THREAD

**Issue by aoloe** [mypaint/mypaint#997]
Since I cannot get into the forums anymore, here is a request that I would love if somebody could take care of (or forward to the forums):

<hr>

The [Libre Graphics Meeting 2019](https://libregraphicsmeeting.org/2019/) is just around the corner!

As usual, the first conference will be the [State of Libre Graphics](https://libregraphicsmeeting.org/2019/schedule-thur-30-05/), where we will give an overview of what has happened during the last year in the world of Libre Graphics.

You're very welcome to submit three slides for your project. They will be presented by the moderator of the _State of Libre Graphics_.
Instructions for submitting the slides can be found in the Github repository that will contain all slides:

<https://github.com/libregraphicsmeeting/state-of-lg-2019>

Don't hesitate to [open a ticket](https://github.com/libregraphicsmeeting/state-of-lg-2019/issues) in the repository if you have further questions.

And, of course, you're very welcome to [join us in Saarbrücken](https://libregraphicsmeeting.org/2019/registration/)!

<hr>

here is a "markdown" version, ready to be copy pasted:

```markdown
The [Libre Graphics Meeting 2019](https://libregraphicsmeeting.org/2019/) is just around the corner!

As usual, the first conference will be the [State of Libre Graphics](https://libregraphicsmeeting.org/2019/schedule-thur-30-05/), where we will give an overview of what has happened during the last year in the world of Libre Graphics.

You're very welcome to submit three slides for your project. They will be presented by the moderator of the _State of Libre Graphics_.
Instructions for submitting the slides can be found in the Github repository that will contain all slides:

<https://github.com/libregraphicsmeeting/state-of-lg-2019>

Don't hesitate to [open a ticket](https://github.com/libregraphicsmeeting/state-of-lg-2019/issues) in the repository if you have further questions.

And, of course, you're very welcome to [join us in Saarbrücken](https://libregraphicsmeeting.org/2019/registration/)!
```

**Comment by briend** [comment]
Will do!  Thanks!!

**Comment by jplloyd** [comment]
LGM 2019 is over, so I'm closing this.
