### ISSUE TITLE
Remove the mailing list from the contact page

### ISSUE THREAD

**Issue by aoloe** [mypaint/mypaint#998]
https://github.com/mypaint/mypaint/wiki/Community-and-Contacts

contains a link to the mailing list, which does not seem to exist anymore...

**Comment by aoloe** [comment]
it should also be removed fro mthe irc subject...

... if you still want to have an irc channel...

**Comment by jplloyd** [comment]
I removed the dead link to the mailing list and the link to the IRC. 
Sampling the irc logs for the past few years, it seems to unfortunately mostly to be a place where user questions come to die, and even those questions have been very rare recently (3 years or so).
